### ISSUE TITLE
Flaky e2e test: EmptyDir volumes should support r/w (Failed 2 times in the last 30 runs. Stability: 93 %)

### ISSUE THREAD

**Issue by quinton-hoole** [GoogleCloudPlatform/kubernetes#10657] opened 2015-07-02 00:52 UTC

**Comment by jszczepkowski** [comment] 2015-07-06 15:16
I've spent some time looking into this issue. I couldn't reproduce it on my e2e cluster, even though I run the test ~50 times. I think that the problem may be with timeout in testContainerOutputInNamespace method (test/e2e/util.go:858). The timeout for waiting for container to generate the expected output is only 1 minute. It may be too small in our case. I suggest we extend the timeout and check if it helps.

**Comment by pmorie** [comment] 2015-07-06 15:29
Are you running in gce or locally? I sometimes get the 'slow test' warning
on these but the time lovally is rarely over 35s. We should definitely pin
this down since there are about to be like 8 more of these cases to cover
non-root and local storage medium.

**Comment by jszczepkowski** [comment] 2015-07-07 07:34
I was running it on GCE.

**Comment by quinton-hoole** [comment] 2015-07-08 22:39
@brendandburns kindly offered to dig into this one today

**Comment by brendandburns** [comment] 2015-07-08 22:56
Looking at a failing apiserver log:
```
curl https://storage.googleapis.com/kubernetes-jenkins/logs/kubernetes-e2e-gce/7449/_artifacts/104.154.59.229%3A22-kube-apiserver.log | grep e2e-tests-emptydir-j2rxf
```

vs. a passing apiserver log:
```
curl https://storage.googleapis.com/kubernetes-jenkins/logs/kubernetes-e2e-gce/7481/_artifacts/130.211.116.155%3A22-kube-apiserver.log | grep e2e-tests-emptydir-gr85j
```

I see that the apiserver is kicking back a 503 when the tests fails.

There are several things wrong with this:

1) The client should signal an error and it doesn't appear to be doing so
2) I'm not sure why we're kicking back a 503 (service unavailable)

Will dig in more.

**Comment by brendandburns** [comment] 2015-07-08 23:53
Having dug into this some more, I think this had the same root cause as the bug that @saad-ali fixed yesterday in https://github.com/GoogleCloudPlatform/kubernetes/pull/10880

**Comment by quinton-hoole** [comment] 2015-07-08 23:54
Checking...

**Comment by brendandburns** [comment] 2015-07-09 00:08
Given offline discussions w/ @quinton-hoole the remaining failures we see in e2e appear to be caused by https://github.com/GoogleCloudPlatform/kubernetes/issues/10622#issuecomment-119742554

Closing this.

**Comment by quinton-hoole** [comment] 2015-07-09 00:08
Many thanks @brendandburns !  One less issue to track down :-)

**Closed by brendandburns** 2015-07-09 00:08 UTC
Labels: priority/P1, team/testing
