### ISSUE TITLE
backtrace from kubelet server

### ISSUE THREAD

**Issue by thockin** [GoogleCloudPlatform/kubernetes#4127] opened 2015-02-04 21:00 UTC
goroutine 191 [running]:
github.com/GoogleCloudPlatform/kubernetes/pkg/httplog.(*respLogger).WriteHeader(0xc20a24d800, 0x1f4)
        /go/src/github.com/GoogleCloudPlatform/kubernetes/_output/dockerized/go/src/github.com/GoogleCloudPlatform/kubernetes/pkg/httplog/log.go:182 +0x9a
net/http.Error(0x7f2e36cd0138, 0xc20a24d800, 0xc2092c6450, 0x27, 0x1f4)
        /usr/src/go/src/net/http/server.go:1274 +0x9a
github.com/GoogleCloudPlatform/kubernetes/pkg/kubelet.(*Server).error(0xc2081416a0, 0x7f2e36cd0138, 0xc20a24d800, 0x7f2e36cc0a80, 0xc2099c4440)
        /go/src/github.com/GoogleCloudPlatform/kubernetes/_output/dockerized/go/src/github.com/GoogleCloudPlatform/kubernetes/pkg/kubelet/server.go:109 +0x124
github.com/GoogleCloudPlatform/kubernetes/pkg/kubelet.(*Server).serveStats(0xc2081416a0, 0x7f2e36cd0138, 0xc20a24d800, 0xc20aaa7930)
        /go/src/github.com/GoogleCloudPlatform/kubernetes/_output/dockerized/go/src/github.com/GoogleCloudPlatform/kubernetes/pkg/kubelet/server.go:357 +0x38d
github.com/GoogleCloudPlatform/kubernetes/pkg/kubelet.(*Server).handleStats(0xc2081416a0, 0x7f2e36cd0138, 0xc20a24d800, 0xc20aaa7930)
        /go/src/github.com/GoogleCloudPlatform/kubernetes/_output/dockerized/go/src/github.com/GoogleCloudPlatform/kubernetes/pkg/kubelet/server.go:241 +0x46
github.com/GoogleCloudPlatform/kubernetes/pkg/kubelet.*Server.(github.com/GoogleCloudPlatform/kubernetes/pkg/kubelet.handleStats)·fm(0x7f2e36cd0138, 0xc20a24d800, 0xc20aaa7930)
        /go/src/github.com/GoogleCloudPlatform/kubernetes/_output/dockerized/go/src/github.com/GoogleCloudPlatform/kubernetes/pkg/kubelet/server.go:95 +0x45
net/http.HandlerFunc.ServeHTTP(0xc2080aa210, 0x7f2e36cd0138, 0xc20a24d800, 0xc20aaa7930)
        /usr/src/go/src/net/http/server.go:1265 +0x41
net/http.(*ServeMux).ServeHTTP(0xc20814b1d0, 0x7f2e36cd0138, 0xc20a24d800, 0xc20aaa7930)
        /usr/src/go/src/net/http/server.go:1541 +0x17d
github.com/GoogleCloudPlatform/kubernetes/pkg/kubelet.(*Server).ServeHTTP(0xc208141680, 0x7f2e36cd0100, 0xc2094a7680, 0xc20aaa7930)
        /go/src/github.com/GoogleCloudPlatform/kubernetes/_outp

**Comment by dchen1107** [comment] 2015-02-11 17:59
cc/ @bprashanth who wants to help with this one, but I couldn't assign it to him somehow.

**Comment by yujuhong** [comment] 2015-02-11 21:24
The backtrace appears frequently in my kubelet.log after the http 500 error.

```
I0211 21:14:10.090880    4709 server.go:351] GET /stats/default/elasticsearch-logging-controller-fplln/95ede68c-b232-11e4-9d4a-42010af07227/elasticsearch-logging?num_stats=0: (53.248208ms) 500
goroutine 101 [running]:
github.com/GoogleCloudPlatform/kubernetes/pkg/httplog.(*respLogger).WriteHeader(0xc20823b380, 0x1f4)
        /go/src/github.com/GoogleCloudPlatform/kubernetes/_output/dockerized/go/src/github.com/GoogleCloudPlatform/kubernetes/pkg/httplog/log.go:182 +0x9a
net/http.Error(0x7f2ce96235d8, 0xc20823b380, 0xc208188ff0, 0x27, 0x1f4)
        /usr/src/go/src/net/http/server.go:1274 +0x9a
github.com/GoogleCloudPlatform/kubernetes/pkg/kubelet.(*Server).error(0xc2080e46c0, 0x7f2ce96235d8, 0xc20823b380, 0x7f2ce9613a80, 0xc2081435f0)
        /go/src/github.com/GoogleCloudPlatform/kubernetes/_output/dockerized/go/src/github.com/GoogleCloudPlatform/kubernetes/pkg/kubelet/server.go:109 +0x124
github.com/GoogleCloudPlatform/kubernetes/pkg/kubelet.(*Server).serveStats(0xc2080e46c0, 0x7f2ce96235d8, 0xc20823b380, 0xc2080fe410)
        /go/src/github.com/GoogleCloudPlatform/kubernetes/_output/dockerized/go/src/github.com/GoogleCloudPlatform/kubernetes/pkg/kubelet/server.go:393 +0x38d
github.com/GoogleCloudPlatform/kubernetes/pkg/kubelet.(*Server).handleStats(0xc2080e46c0, 0x7f2ce96235d8, 0xc20823b380, 0xc2080fe410)
        /go/src/github.com/GoogleCloudPlatform/kubernetes/_output/dockerized/go/src/github.com/GoogleCloudPlatform/kubernetes/pkg/kubelet/server.go:277 +0x46
github.com/GoogleCloudPlatform/kubernetes/pkg/kubelet.*Server.(github.com/GoogleCloudPlatform/kubernetes/pkg/kubelet.handleStats)·fm(0x7f2ce96235d8, 0xc20823b380, 0xc2080fe410)
        /go/src/github.com/GoogleCloudPlatform/kubernetes/_output/dockerized/go/src/github.com/GoogleCloudPlatform/kubernetes/pkg/kubelet/server.go:95 +0x45
net/http.HandlerFunc.ServeHTTP(0xc20807d820, 0x7f2ce96235d8, 0xc20823b380, 0xc2080fe410)
        /usr/src/go/src/net/http/server.go:1265 +0x41
net/http.(*ServeMux).ServeHTTP(0xc208189c80, 0x7f2ce96235d8, 0xc20823b380, 0xc2080fe410)
        /usr/src/go/src/net/http/server.go:1541 +0x17d
github.com/GoogleCloudPlatform/kubernetes/pkg/kubelet.(*Server).ServeHTTP(0xc2080e46a0, 0x7f2ce96235a0, 0xc208146640, 0xc2080fe410)
        /go/src/github.com/GoogleCloudPlatform/kubernetes/_outp
I0211 21:14:10.124401    4709 server.go:351] GET /stats/default/monitoring-influx-grafana-controller-0133o/95f0120a-b232-11e4-9d4a-42010af07227/influxdb?num_stats=0: (3.735993ms) 200
I0211 21:14:10.127235    4709 server.go:351] GET /stats/default/monitoring-influx-grafana-controller-0133o/95f0120a-b232-11e4-9d4a-42010af07227/grafana?num_stats=0: (1.858126ms) 500
goroutine 101 [running]:
github.com/GoogleCloudPlatform/kubernetes/pkg/httplog.(*respLogger).WriteHeader(0xc208166a20, 0x1f4)
        /go/src/github.com/GoogleCloudPlatform/kubernetes/_output/dockerized/go/src/github.com/GoogleCloudPlatform/kubernetes/pkg/httplog/log.go:182 +0x9a
net/http.Error(0x7f2ce96235d8, 0xc208166a20, 0xc208229bf0, 0x27, 0x1f4)
        /usr/src/go/src/net/http/server.go:1274 +0x9a
github.com/GoogleCloudPlatform/kubernetes/pkg/kubelet.(*Server).error(0xc2080e46c0, 0x7f2ce96235d8, 0xc208166a20, 0x7f2ce9613a80, 0xc208233920)
        /go/src/github.com/GoogleCloudPlatform/kubernetes/_output/dockerized/go/src/github.com/GoogleCloudPlatform/kubernetes/pkg/kubelet/server.go:109 +0x124
github.com/GoogleCloudPlatform/kubernetes/pkg/kubelet.(*Server).serveStats(0xc2080e46c0, 0x7f2ce96235d8, 0xc208166a20, 0xc2081c4ea0)
        /go/src/github.com/GoogleCloudPlatform/kubernetes/_output/dockerized/go/src/github.com/GoogleCloudPlatform/kubernetes/pkg/kubelet/server.go:393 +0x38d
github.com/GoogleCloudPlatform/kubernetes/pkg/kubelet.(*Server).handleStats(0xc2080e46c0, 0x7f2ce96235d8, 0xc208166a20, 0xc2081c4ea0)
        /go/src/github.com/GoogleCloudPlatform/kubernetes/_output/dockerized/go/src/github.com/GoogleCloudPlatform/kubernetes/pkg/kubelet/server.go:277 +0x46
github.com/GoogleCloudPlatform/kubernetes/pkg/kubelet.*Server.(github.com/GoogleCloudPlatform/kubernetes/pkg/kubelet.handleStats)·fm(0x7f2ce96235d8, 0xc208166a20, 0xc2081c4ea0)
        /go/src/github.com/GoogleCloudPlatform/kubernetes/_output/dockerized/go/src/github.com/GoogleCloudPlatform/kubernetes/pkg/kubelet/server.go:95 +0x45
net/http.HandlerFunc.ServeHTTP(0xc20807d820, 0x7f2ce96235d8, 0xc208166a20, 0xc2081c4ea0)
        /usr/src/go/src/net/http/server.go:1265 +0x41
net/http.(*ServeMux).ServeHTTP(0xc208189c80, 0x7f2ce96235d8, 0xc208166a20, 0xc2081c4ea0)
        /usr/src/go/src/net/http/server.go:1541 +0x17d
github.com/GoogleCloudPlatform/kubernetes/pkg/kubelet.(*Server).ServeHTTP(0xc2080e46a0, 0x7f2ce96235a0, 0xc208147220, 0xc2081c4ea0)
        /go/src/github.com/GoogleCloudPlatform/kubernetes/_outp
```

**Comment by thockin** [comment] 2015-02-11 22:35
Is this the backtrace that comes from kubelet/server.go func (s *Server)
ServeHTTP()?

Maybe we need better log messages indicating WHY it is stack dumping and
maybe a better filter when when it should?

**Comment by bprashanth** [comment] 2015-02-12 01:26
I've actually witnessed something that looks a little more invidious, with a similar stack trace. 

```
github.com/GoogleCloudPlatform/kubernetes/pkg/httplog.(*respLogger).WriteHeader(0x4c2081c8b40, 0x190)
	/usr/local/google/home/beeps/goproj/src/github.com/GoogleCloudPlatform/kubernetes/_output/local/go/src/github.com/GoogleCloudPlatform/kubernetes/pkg/httplog/log.go:182 +0x9a
net/http.Error(0x7f4333655be0, 0x4c2081c8b40, 0xbbf030, 0x1d, 0x190)
	/usr/lib/google-golang/src/net/http/server.go:1274 +0x9a
github.com/GoogleCloudPlatform/kubernetes/pkg/kubelet.(*Server).handlePodStatus(0x4c20814c280, 0x7f4333655be0, 0x4c2081c8b40, 0x4c20816f790, 0x4c20836ba01)
	/usr/local/google/home/beeps/goproj/src/github.com/GoogleCloudPlatform/kubernetes/_output/local/go/src/github.com/GoogleCloudPlatform/kubernetes/pkg/kubelet/server.go:247 +0x28c
github.com/GoogleCloudPlatform/kubernetes/pkg/kubelet.(*Server).handlePodInfoVersioned(0x4c20814c280, 0x7f4333655be0, 0x4c2081c8b40, 0x4c20816f790)
	/usr/local/google/home/beeps/goproj/src/github.com/GoogleCloudPlatform/kubernetes/_output/local/go/src/github.com/GoogleCloudPlatform/kubernetes/pkg/kubelet/server.go:232 +0x4b
github.com/GoogleCloudPlatform/kubernetes/pkg/kubelet.*Server.(github.com/GoogleCloudPlatform/kubernetes/pkg/kubelet.handlePodInfoVersioned)·fm(0x7f4333655be0, 0x4c2081c8b40, 0x4c20816f790)
	/usr/local/google/home/beeps/goproj/src/github.com/GoogleCloudPlatform/kubernetes/_output/local/go/src/github.com/GoogleCloudPlatform/kubernetes/pkg/kubelet/server.go:93 +0x45
net/http.HandlerFunc.ServeHTTP(0x4c20810e8c0, 0x7f4333655be0, 0x4c2081c8b40, 0x4c20816f790)
	/usr/lib/google-golang/src/net/http/server.go:1265 +0x41
net/http.(*ServeMux).ServeHTTP(0x4c2080af800, 0x7f4333655be0, 0x4c2081c8b40, 0x4c20816f790)
	/usr/lib/google-golang/src/net/http/server.go:1541 +0x17d
github.com/GoogleCloudPlatform/kubernetes/pkg/kubelet.(*Server).ServeHTTP(0x4c20814c260, 0x7f43336555b8, 0x4c2083243c0, 0x4c20816f790)
	/usr/local/google/home/beeps/goproj/src/github.com/GoogleCloudPlatform/kubernetes/_output/local/go/src/github.com/GoogleCloudPlatform/kubernetes/pkg/kub
```

The kubelet goroutine will crash if asked for the status of a ghost pod (i.e /api/v1beta1/podInfo?podID=&podNamespace=). I can reproduce it with the following test (it's fairly hacky): https://gist.github.com/bprashanth/8a49d750b1a867e6f65e

When it happens kubectl displays several (typically 1-4) undefined pods:
```
Running: ./cluster/../_output/local/bin/linux/amd64/kubectl get pods
POD                 IP                  CONTAINER(S)        IMAGE(S)            HOST                  LABELS              STATUS
                                                                                127.0.0.1/127.0.0.1   <none>              Unknown
```

etcd has the key, and the scheduler seemingly keeps trying to schedule the pod on the same minion: 
```
I0211 17:15:29.633359   15168 factory.go:274] Attempting to bind php8038 to 127.0.0.1
I0211 17:15:29.642731   15168 scheduler.go:85] Failed to bind pod: pod  is already assigned to host 127.0.0.1
E0211 17:15:29.642794   15168 factory.go:227] Error scheduling default php8038: pod  is already assigned to host 127.0.0.1; retrying
```

The pods in etcd don't seemed to have ever reached the kubelet, so its possible that these are the pods deleted before they reached 'Running'. Thoughts?

**Comment by yujuhong** [comment] 2015-02-12 01:57
The ghost pods you observed may be from the race condition between pod scheduling and deletion (see #3950). I have a PR #4326 that should stop the ghost pods from being created. The root cause of the race condition, should be addressed in another issue #4188.

I think this bug is about when to dump the stack trace and add more clarity, like @thockin suggested.

**Comment by bprashanth** [comment] 2015-02-12 18:48
I agree that this shouldn't be conflated with the ghost pod issue. So tldr sounds like there might be several scenarios leading to (possible malformed) urls causing kubelete goroutine stack traces, and we want clarity.

**Comment by bprashanth** [comment] 2015-02-13 05:37
The stacktrace with `serveStats` is happening because we find the pod and not the container (i.e the application container in the pod either dies or hasn't started yet between `kubelet.GetPodByName` and `cadvisor.GetContainerInfo`, so we only find the pause container, not the application). In either case I think it's appropriate to return `http.StatusNotFound` (404) directly from the handler and surface this information, without a stacktrace.

The second stacktrace might be a little confusing to someone debugging the kubelet because `/api/v1beta1/podInfo?podID=&podNamespace=` rightfully returns a 400, which generally means it's the client's problem. I can include `http.StatusBadRequest` in the stack trace whitelist for the kubelet server.

@thockin thoughts?

**Comment by thockin** [comment] 2015-02-13 17:24
Yeah, I don't think backtrace is useful for "real" conditions like not
found.

**Comment by bprashanth** [comment] 2015-02-27 19:57
Adding clarity and preventing the stack dump should 'fix' this issue (https://github.com/GoogleCloudPlatform/kubernetes/pull/4508). #4489 discusses different http return codes and even more clarity, since we can't really do anything about a request for the stats of a container that hasn't started yet.

**Closed by bprashanth** 2015-02-27 19:57 UTC
Labels: kind/bug, priority/P1, team/node
