### ISSUE TITLE
Etcd Minion

### ISSUE THREAD

**Issue by UserTaken** [GoogleCloudPlatform/kubernetes#10284] opened 2015-06-24 12:15 UTC
`Minion` was changed to `node` but that is not reflected in Etcd as the default path is still `/registry/minions`.

**Comment by mbforbes** [comment] 2015-06-24 18:28
Can you give a bit more detail to help me triage this? Is this a bug or just needs a docs change?

**Comment by UserTaken** [comment] 2015-06-24 18:42
@mbforbes `$ etcdctl ls --recursive /registry` still shows `/registry/minions/` instead of `/registry/nodes/`. i'm uncertain if this is intentional or an oversight.

**Comment by mbforbes** [comment] 2015-06-24 23:04
@davidopp do you have context or know who might?

**Comment by lavalamp** [comment] 2015-06-24 23:11
Essentially, https://github.com/GoogleCloudPlatform/kubernetes/blob/master/pkg/registry/minion/etcd/etcd.go#L53 is wrong.

However, changing it requires data migration, which is probably why it wasn't done.

This is an internal detail that clients should not depend on (only apiserver talks to etcd!), so it's probably not terribly important.

**Comment by mikedanese** [comment] 2015-06-24 23:20
#1111 The minon->node migration is not complete.

**Comment by davidopp** [comment] 2015-06-25 07:36
Closing this since it is "working as intended." We're continuing to work on unifying the terminology (though I think the last time we discussed this, going back to "minion" rather than finishing the transition to "node" was actually winning in the polling). Anyway, the relevant issue is the one @mikedanese mentioned.

**Closed by davidopp** 2015-06-25 07:36 UTC
Labels: priority/P3, team/master
