### ISSUE TITLE
List inconsistent among object types.

### ISSUE THREAD

**Issue by erictune** [GoogleCloudPlatform/kubernetes#2602] opened 2014-11-25 17:05 UTC
Events takes a field selector but the other ones don't.

Suggest adding `fields labels.Selector` and `labels labels.Selector` to `events` type and all other corresponding types, so that a person can call:
`c.Pods(ns).List()` to get all pods or `c.Events(ns).Select(someSelector).Project(someOtherSelector).List()`
or various other combinations.

```
$ grep 'func.*List(' pkg/client/*.go | grep -v fake

pkg/client/endpoints.go:func (c *endpoints) List(selector labels.Selector) (result *api.EndpointsList, err error) {
pkg/client/events.go:func (e *events) List(label, field labels.Selector) (*api.EventList, error) {
pkg/client/minions.go:func (c *minions) List() (*api.MinionList, error) {
pkg/client/pods.go:func (c *pods) List(selector labels.Selector) (result *api.PodList, err error) {
pkg/client/replication_controllers.go:func (c *replicationControllers) List(selector labels.Selector) (result *api.ReplicationControllerList, err error) {
pkg/client/services.go:func (c *services) List(selector labels.Selector) (result *api.ServiceList, err error) {
```

**Comment by bgrant0607** [comment] 2015-02-05 04:04
Closing as dupe of #1362.

**Closed by bgrant0607** 2015-02-05 04:04 UTC
Labels: api/cluster, area/usability, priority/P2, team/UX
