### ISSUE TITLE
Service latency test tolerances issue. 

### ISSUE THREAD

**Issue by timothysc** [GoogleCloudPlatform/kubernetes#10348] opened 2015-06-25 13:36 UTC
We've been experiencing issues when we try to validate a HA-cluster of ~25 nodes.   The test states that 'Median latency should be less than 20 seconds', but it seems like the test tolerances are a bit tight, as if they designed for a very small test cluster with 1 etcd.  

Our current stats are:
INFO: 50 %ile: 47.782314518s
INFO: 90 %ile: 1m5.380307982s
INFO: 99 %ile: 1m9.184195579s

I don't think 20 sec would work on a reasonably large sized cluster. 

@lavalamp @roberthbailey @rrati

**Comment by brendandburns** [comment] 2015-06-25 13:43
closing as a dupe of https://github.com/GoogleCloudPlatform/kubernetes/issues/10248

**Closed by brendandburns** 2015-06-25 13:43 UTC

**Comment by lavalamp** [comment] 2015-06-25 17:54
I hope to fix this test today. Thanks for the data point.
