### ISSUE TITLE
RC keeps creating new pods if there's an issue starting a container, even after RC is deleted

### ISSUE THREAD

**Issue by rawlingsj** [GoogleCloudPlatform/kubernetes#6291] opened 2015-04-01 14:04 UTC
The scenario is when a replication controller is created which starts a pod that will always error (an issue in a CMD start.sh script for example), the failed pod is left 'Exited' and 30 seconds later a new pod is scheduled.

This continues to happen even if the replication controller is deleted, the pods are still endlessly scheduled resulting in many many failed containers.  This seems to result in high CPU usage of the docker process if left for a while.

**Comment by smarterclayton** [comment] 2015-04-01 14:13
I wonder if we need to do a better job of aggressively garbage collecting repeated failures of containers on the host (if the Kubelet detects a pod is in a repeat fail loop, only the last N pods should be kept, instead of using the regular garbage collection policy).

**Comment by bprashanth** [comment] 2015-04-01 14:21
1. The rc will keep trying to match its replica count. It only knows to detect the status of a pod. So if the container exiting leaves it in a non-running state (i.e Failed or Succeeded) the rc will create a new one. What status is your crashing pod? 

2. You should `stop` the rc, deleting the rc will still leave the pods lying around. So the other components of the system (scheduler, kubelet) will keep trying to run them. 

3. Container gc https://github.com/GoogleCloudPlatform/kubernetes/issues/3649

**Comment by rawlingsj** [comment] 2015-04-01 15:26
> The rc will keep trying to match its replica count. It only knows to detect the status of a pod. So if the container exiting leaves it in a non-running state (i.e Failed or Succeeded) the rc will create a new one. What status is your crashing pod?

It was Failed



> You should stop the rc, deleting the rc will still leave the pods lying around. So the other components of the system (scheduler, kubelet) will keep trying to run them.

Yep that makes complete sense, I didn't stop the RC first

**Comment by bprashanth** [comment] 2015-04-01 16:43
Seems like the gc issue is discussed on another bug, and the solution to the rc problem is to call stop. Please re-open if this isn't the case.

**Comment by rawlingsj** [comment] 2015-04-01 17:35
Agreed thanks.

**Comment by smarterclayton** [comment] 2015-04-01 19:52
I'm confused - for a run-forever pod, why would it get mark failed and why wouldn't the replication controller back off?  This has changed from previous behavior if so.

**Comment by bprashanth** [comment] 2015-04-01 20:25
RestartPolicy should be honored. I didn't see a mention of RestartPolicy=Never in the initial report, is that what's happening? I believe the default policy is restart always for pods created through an rc (https://github.com/GoogleCloudPlatform/kubernetes/blob/master/pkg/api/validation/validation.go#L910).

**Comment by yujuhong** [comment] 2015-04-01 20:37
Replication controller only work with RestartPolicy=Always pods.

There is one scenario where the pod status may be failed even though the restart policy is always -- when kubelet explicitly rejects the pod.
https://github.com/GoogleCloudPlatform/kubernetes/blob/master/pkg/kubelet/kubelet.go#L1595

**Comment by smarterclayton** [comment] 2015-04-01 21:05
James, do you have the json/yaml for the replication controller that was creating the pods?

----- Original Message -----

**Comment by bprashanth** [comment] 2015-04-01 21:29
The rc can only *create* a pod with restartpolicy=always, it will manage pods with restart=never because it checks selectors and nothing else. So if you have:
* rc: 
  - replicas: 1
  - selectors: foo
* pod1: 
  - restartpolicy: Always
  - labels: foo

and you create:
* pod2:   
  - restartpolicy: Never    
  - labels: foo    

And the rc picks pod1 to kill, and pod2 dies, a new pod will be created with `RestartPolicy=Always`. This has always happened AFAIK, essentially we treat RestartPolicy like any other field in the spec, nothing special to the rc. 

Re kubelet: That's desirable IIUC. In almost every case that the kubelet rejects pods, the scheduler will too, unless you have static pods on the kubelet the scheduler doesn't know about. In that case, the Failed status is desirable because the rc will recreate the pod, and hopefully the scheduler will send it to another host.

**Comment by smarterclayton** [comment] 2015-04-01 21:45
I think what I'm getting at though is that creating a process that fails to start doesn't sound like Failed (failed was very specific, meaning that it's been rejected).  I don't think that's the case yujuhong was describing here.  So I wouldn't expect a pod process that dies unexpectedly to trigger Failed in a way that schedules new pods.  I know whether a "Never" pod was involved or not.

**Comment by bprashanth** [comment] 2015-04-01 22:24
Ah, then it's a 'pod shouldn't be in failed' bug. The contract of the rc is that it will restart failed pods that have matching selectors, changing this doesn't make sense to me. @rawlingsj if you can provide more info about the pods failure mode please reopen (and re-title).

**Comment by smarterclayton** [comment] 2015-04-01 22:37
The only criteria I was aware of for a RestartAlways pod being in failed was kubelet rejected.  Are you saying that's not the case?

**Comment by bprashanth** [comment] 2015-04-01 22:55
That sounds like what the bug is about, from my somewhat limited comprehension of https://github.com/GoogleCloudPlatform/kubernetes/issues/6291#issuecomment-88522471 at least.

**Comment by rawlingsj** [comment] 2015-04-22 13:12
@smarterclayton sorry I missed your request for json / yaml.  I can put a test case together quickly and add a comment today.

**Comment by rawlingsj** [comment] 2015-04-22 14:21
Ok so I've created a really basic example to hopefully demonstrate the issue.  The container will always fail, in the example it hard codes an error exit code to simulate something going wrong in a start script..

https://github.com/rawlingsj/kubernetes6291/blob/master/start.sh#L1

This is the replication controller config I'm using..

```
{
  "id": "kubernetes6291-controller",
  "kind": "ReplicationController",
  "apiVersion": "v1beta1",
  "desiredState": {
    "replicas": 1,
    "replicaSelector": {"name": "kubernetes6291"},
    "podTemplate": {
      "desiredState": {
        "manifest": {
          "version": "v1beta1",
          "id": "kubernetes6291",
          "containers": [{
            "name": "kubernetes6291",
            "image": "rawlingsj/kubernetes6291"
          }]
        }
      },
      "labels": {
        "name": "kubernetes6291"
      }
    }
  },
  "labels": {
    "name": "kubernetes6291"
  }
}
```

This results in the replication controller endlessly scheduling pods that will fail.  This is only meant to demonstrate the issue but there doesn't seem to be any fail safe limits that prevent thousands of pods being created which can eventually leave a machine unresponsive if left unnoticed.

**Comment by smarterclayton** [comment] 2015-04-22 14:26
We have limits and quota, they're just not turned on by default.  The kubelet should be delaying the failure of pods eventually.  I think the real point of this issue should be that the system should reduce the impact of perm-failed containers on the rest of the system (we've noticed this in real use, that a perm failing container starts to drain both Kubelet and Master resources due to the increased traffic of client requests and polling).

**Comment by derekwaynecarr** [comment] 2015-04-22 14:43
So quota does not really help here if I understand the issue.  A pod whose restart policy is set to always is always counted against your quota even if its in a failed state because we know the kubelet will just restart it.  It's not like there are new pods being created in this scenario.  To the apiserver, its just the same pod getting restarted.  I think this topic is more an issue with the Kubelet and what it should do if it sees the same container repeatedly fail in a quick period.

**Comment by bgrant0607** [comment] 2015-04-22 14:46
See also #2529

**Comment by smarterclayton** [comment] 2015-04-22 14:54
Do we want to track the kubelet part of this issue (kubelet retries every 3 seconds FOREVER to restart perm failed pods) or the other?

**Comment by bgrant0607** [comment] 2015-04-29 01:32
A POD with phase=Failed should never be restarted by Kubelet. It shouldn't reach that phase for mere container failures if RestartPolicy=Always. If that is happening, it is most definitely a bug.

**Comment by bgrant0607** [comment] 2015-04-29 01:39
If the Kubelet issue is the only one remaining, we might as well just use this issue.

**Comment by yujuhong** [comment] 2015-04-29 17:26
If I read the issue correctly, this is not a problem of creating new *pods*, but rather about creating new *containers*. If a container is doomed to fail and the restart policy for the pod is "always", kubelet will periodically examine the pod status and creates new containers if needed. This could potentially stress the system unnecessarily.

@bgrant0607, I don't think the issue is about kubelet restarting failed pods. The pod should be in the *running* state with an increasing number of dead containers.

There is an open issue to back off restarting containers to resolve issue like this (#4121). I had written some code, but the PR is currently on hold due to the container runtime refactoring in kubelet. I think we can close this as a dupe. Please reopen if this is not true.

**Closed by yujuhong** 2015-04-29 17:26 UTC
Labels: priority/P2, team/master, team/node
