### ISSUE TITLE
Pull request builder flaking on DNS / Probing container

### ISSUE THREAD

**Issue by zmerlynn** [GoogleCloudPlatform/kubernetes#10622] opened 2015-07-01 14:50 UTC
http://goto.google.com/prkubekins/job/kubernetes-pull-build-test-e2e-gce/1456 is an example, but I've seen it a bunch:

```
Kubernetes e2e suite.DNS should provide DNS for the cluster
Kubernetes e2e suite.Probing container with readiness probe that fails should never be ready and never restart
```

I'm not seeing similar failures on kubernetes-e2e-gce-parallel

**Comment by zmerlynn** [comment] 2015-07-01 14:50
cc @ixdy @quinton-hoole

**Comment by ixdy** [comment] 2015-07-01 20:46
The flaky tests have occurred on all of the executors, so it doesn't seem like it's related to that.

A lot of the recent failures are all on #10487 (e.g. builds 1486, 1484, 1474, 1473, 1466) though there are failures for other PRs earlier than that.

Still digging...

**Comment by ixdy** [comment] 2015-07-01 20:48
The probing container test failed on the kubernetes-e2e-gce-parallel build once: https://pantheon.corp.google.com/storage/browser/kubernetes-jenkins/logs/kubernetes-e2e-gce-parallel/2531/

**Comment by ixdy** [comment] 2015-07-01 20:50
Also a DNS flake in build 2490 on June 29: https://cloud.google.com/console/storage/kubernetes-jenkins/logs/kubernetes-e2e-gce-parallel/2490/

**Comment by ixdy** [comment] 2015-07-01 20:53
The probing container test shows an error message like the following before failing:
```
STEP: Collecting events from namespace "e2e-tests-container-probe-3x5iw".
INFO: event for nginx-e8a70908-1ffd-11e5-be80-42010af07603: {scheduler } scheduled: Successfully assigned nginx-e8a70908-1ffd-11e5-be80-42010af07603 to pull-e2e-0-minion-nfdy
INFO: event for nginx-e8a70908-1ffd-11e5-be80-42010af07603: {kubelet pull-e2e-0-minion-nfdy} pulled: Pod container image "gcr.io/google_containers/pause:0.8.0" already present on machine
INFO: event for nginx-e8a70908-1ffd-11e5-be80-42010af07603: {kubelet pull-e2e-0-minion-nfdy} created: Created with docker id 3956dffea70e
INFO: event for nginx-e8a70908-1ffd-11e5-be80-42010af07603: {kubelet pull-e2e-0-minion-nfdy} started: Started with docker id 3956dffea70e
INFO: event for nginx-e8a70908-1ffd-11e5-be80-42010af07603: {kubelet pull-e2e-0-minion-nfdy} pulled: Successfully pulled image "nginx"
INFO: event for nginx-e8a70908-1ffd-11e5-be80-42010af07603: {kubelet pull-e2e-0-minion-nfdy} failed: Failed to create docker container with error: API error (500): error creating aufs mount to /var/lib/docker/aufs/mnt/669e5d583ce9b05fe811ea4f8556f6e115d89d4eb5737ed98090948af4b7cd18-init: invalid argument

INFO: event for nginx-e8a70908-1ffd-11e5-be80-42010af07603: {kubelet pull-e2e-0-minion-nfdy} failed: Failed to create docker container with error: API error (500): error creating aufs mount to /var/lib/docker/aufs/mnt/17239846605d44aed3864d9203a4b25a77f34a5f8004ab150d0de2e2ac6f07a8-init: invalid argument

INFO: event for nginx-e8a70908-1ffd-11e5-be80-42010af07603: {kubelet pull-e2e-0-minion-nfdy} failed: Failed to create docker container with error: API error (500): error creating aufs mount to /var/lib/docker/aufs/mnt/75bbee02176bd7c5e69f8a26c0841bc01046d0ed28e765d529e1c8d71162752f-init: invalid argument

INFO: event for nginx-e8a70908-1ffd-11e5-be80-42010af07603: {kubelet pull-e2e-0-minion-nfdy} failed: Failed to create docker container with error: API error (500): error creating aufs mount to /var/lib/docker/aufs/mnt/8d2e609778cff6ac51765719dd023d7bf501a4ca883085033db8c9db3ee4b735-init: invalid argument

INFO: event for nginx-e8a70908-1ffd-11e5-be80-42010af07603: {kubelet pull-e2e-0-minion-nfdy} failed: Failed to create docker container with error: API error (500): error creating aufs mount to /var/lib/docker/aufs/mnt/b2f3f8a07398d4738a544141893cd54da24923e193e7897b2ab1013fd8672634-init: invalid argument

INFO: event for nginx-e8a70908-1ffd-11e5-be80-42010af07603: {kubelet pull-e2e-0-minion-nfdy} failed: Failed to create docker container with error: API error (500): error creating aufs mount to /var/lib/docker/aufs/mnt/e8cfbc6e95caf523a5a4a9338fb71c6d245084b02d9be926b200cc1fd5e0a3c4-init: invalid argument

INFO: event for nginx-e8a70908-1ffd-11e5-be80-42010af07603: {kubelet pull-e2e-0-minion-nfdy} failed: Failed to create docker container with error: API error (500): error creating aufs mount to /var/lib/docker/aufs/mnt/a6d77f267addd85fa132b5e9db7da93ca74ae258fea71b0098f6a4e6d2c4ebcb-init: invalid argument

INFO: event for nginx-e8a70908-1ffd-11e5-be80-42010af07603: {kubelet pull-e2e-0-minion-nfdy} failed: Failed to create docker container with error: API error (500): error creating aufs mount to /var/lib/docker/aufs/mnt/1f3de7151e52bf8026519b0a245e8861c033506d69ecb9896b90f6458c250a36-init: invalid argument

INFO: event for nginx-e8a70908-1ffd-11e5-be80-42010af07603: {kubelet pull-e2e-0-minion-nfdy} failed: Failed to create docker container with error: API error (500): error creating aufs mount to /var/lib/docker/aufs/mnt/2cff807974c6149dc02047c1798f0303a9c327ccc43c9d55595f7ce80b1c5801-init: invalid argument

INFO: event for nginx-e8a70908-1ffd-11e5-be80-42010af07603: {kubelet pull-e2e-0-minion-nfdy} failed: Failed to create docker container with error: API error (500): error creating aufs mount to /var/lib/docker/aufs/mnt/9f2e297afd646a3bd2cb52005cb04d66dea70d43c077c5e59564147302ae7feb-init: invalid argument

INFO: event for nginx-e8a70908-1ffd-11e5-be80-42010af07603: {kubelet pull-e2e-0-minion-nfdy} failed: Failed to create docker container with error: API error (500): error creating aufs mount to /var/lib/docker/aufs/mnt/eda7977d57fccc4f8a8914ecdcbb0b82e2fd20fdde37e8accd3a42b5e6a6a4c3-init: invalid argument

STEP: Destroying namespace "e2e-tests-container-probe-3x5iw" for this suite.
• Failure [100.284 seconds]
```

I'm not sure how to interpret this.

**Comment by ixdy** [comment] 2015-07-01 20:54
Similar error messages from the DNS test.
```
INFO: event for dns-test-dfa67cf7-1ffd-11e5-869d-42010af07603: {scheduler } scheduled: Successfully assigned dns-test-dfa67cf7-1ffd-11e5-869d-42010af07603 to pull-e2e-0-minion-nfdy
INFO: event for dns-test-dfa67cf7-1ffd-11e5-869d-42010af07603: {kubelet pull-e2e-0-minion-nfdy} pulled: Pod container image "gcr.io/google_containers/pause:0.8.0" already present on machine
INFO: event for dns-test-dfa67cf7-1ffd-11e5-869d-42010af07603: {kubelet pull-e2e-0-minion-nfdy} created: Created with docker id 6359a7570a4b
INFO: event for dns-test-dfa67cf7-1ffd-11e5-869d-42010af07603: {kubelet pull-e2e-0-minion-nfdy} started: Started with docker id 6359a7570a4b
INFO: event for dns-test-dfa67cf7-1ffd-11e5-869d-42010af07603: {kubelet pull-e2e-0-minion-nfdy} created: Created with docker id 763b2e1358ce
INFO: event for dns-test-dfa67cf7-1ffd-11e5-869d-42010af07603: {kubelet pull-e2e-0-minion-nfdy} started: Started with docker id 763b2e1358ce
INFO: event for dns-test-dfa67cf7-1ffd-11e5-869d-42010af07603: {kubelet pull-e2e-0-minion-nfdy} pulled: Successfully pulled image "gcr.io/google_containers/dnsutils"
INFO: event for dns-test-dfa67cf7-1ffd-11e5-869d-42010af07603: {kubelet pull-e2e-0-minion-nfdy} created: Created with docker id de33cca553e1
INFO: event for dns-test-dfa67cf7-1ffd-11e5-869d-42010af07603: {kubelet pull-e2e-0-minion-nfdy} started: Started with docker id de33cca553e1
INFO: event for dns-test-dfa67cf7-1ffd-11e5-869d-42010af07603: {kubelet pull-e2e-0-minion-nfdy} pulled: Successfully pulled image "gcr.io/google_containers/jessie-dnsutils"
INFO: event for dns-test-dfa67cf7-1ffd-11e5-869d-42010af07603: {kubelet pull-e2e-0-minion-nfdy} failed: Failed to create docker container with error: API error (500): error creating aufs mount to /var/lib/docker/aufs/mnt/13ba216123e17f3189be739f5e1cce06a3ffa0dddc02b5c7d9bd4eda33e7f70b-init: invalid argument

INFO: event for dns-test-dfa67cf7-1ffd-11e5-869d-42010af07603: {kubelet pull-e2e-0-minion-nfdy} failed: Failed to create docker container with error: API error (500): error creating aufs mount to /var/lib/docker/aufs/mnt/34a61d31c14ce0be078057f1e6b6727aa95aef9551d082cd25c4cb44c18a0f96-init: invalid argument
```
etc.

Is there some issue with docker that we're hitting?

**Comment by zmerlynn** [comment] 2015-07-01 21:04
cc @dchen1107 !

**Comment by zmerlynn** [comment] 2015-07-01 21:06
The reason I opened this bug is that I saw multiple cases yesterday where the pull builder turned up one of these, I asked it to retest, and it went away.

**Comment by ixdy** [comment] 2015-07-01 21:08
Yeah, I am not sure why this is occurring much more heavily on the pull builder than on our post builders.

**Comment by dchen1107** [comment] 2015-07-01 23:17
I believe you are running into this issue: https://github.com/docker/docker/issues/13742

**Comment by ixdy** [comment] 2015-07-02 00:57
The docker errors are from the kubelets, not from our Jenkins instance, so I'm not sure that issue is (entirely) related.

**Comment by zmerlynn** [comment] 2015-07-02 22:47
I just got hit by a bunch, and they seem to clump on these tests. I had to look back at some other PRs to see if I was going insane, but #10680 got this clump:
```
Kubernetes e2e suite.Probing container with readiness probe should not be ready before initial delay and never restart
Kubernetes e2e suite.DNS should provide DNS for the cluster
Kubernetes e2e suite.DNS should provide DNS for services
Kubernetes e2e suite.Kubectl client Simple pod should support exec
```

And my #10687 just got hit with this about 3-4 times, all of which seem kubelet related:
```
Kubernetes e2e suite.DNS should provide DNS for the cluster
Kubernetes e2e suite.DNS should provide DNS for services
Kubernetes e2e suite.Probing container with readiness probe should not be ready before initial delay and never restart
Kubernetes e2e suite.Kubectl client Simple pod should support exec
Kubernetes e2e suite.Kubectl client Simple pod should support port-forward
```

**Comment by zmerlynn** [comment] 2015-07-02 22:47
I tested #10687 manually and can't get those to repro.

**Comment by quinton-hoole** [comment] 2015-07-06 19:58
@ixdy Any progress on this one?  It's one of our few remaining v1.0 priority 0's.

**Comment by ixdy** [comment] 2015-07-06 20:05
No progress. I have no idea why docker is failing more consistently on the pull request jenkins.

**Comment by ixdy** [comment] 2015-07-06 20:06
The DNS tests were already using images from gcr.io, so the fix in #10758 seems unlikely to be the issue.

**Comment by quinton-hoole** [comment] 2015-07-07 15:29
@ixdy are you busy debugging, or do we need to find someone else?

**Comment by quinton-hoole** [comment] 2015-07-07 15:31
@ixdy Is it perhaps the GCE project in which you're running that has badly configured network routes or load balancers?

**Comment by ixdy** [comment] 2015-07-07 19:35
I'm not actively debugging. I don't really know where to look.

Nothing about the GCE project used for the pull request Jenkins looks any different from the other GCE projects.

**Comment by ixdy** [comment] 2015-07-07 19:38
It also seems like these tests aren't failing anymore?

`Services should serve a basic endpoint from pods` is looking flaky, but I haven't checked the post-commit Jenkins to see if it's flaky there too.

**Comment by quinton-hoole** [comment] 2015-07-07 20:22
OK, I guess I'll take it then.

**Comment by quinton-hoole** [comment] 2015-07-08 17:59
@krousey kindly stepped up to take this one - reassigned.

**Comment by quinton-hoole** [comment] 2015-07-08 18:03
Note that these DNS failures are not limited to the pull request builder.  Our normal Jenkins runs are seeing similar errors:

e.g. 

1. job/kubernetes-e2e-gce-parallel/3023/
1. job/kubernetes-e2e-gce-parallel/3035/
1. job/kubernetes-e2e-gce-parallel/3028/

I'm increasingly convinced that there are some wrong network configs (or quota limits) on the underlying GCE projects.  Checking...

**Comment by quinton-hoole** [comment] 2015-07-08 18:11
No, there's nothing obviously wrong in the underlying GCE project (although it would be good for @krousey to double-check me).

Back to you @krousey ...

**Comment by krousey** [comment] 2015-07-08 18:54
The framework occurs in the generic framework cleanup and is not specific to DNS or probe tests. It's waiting for all nodes to be ready. For each failure, the same node is in a not ready state with the reason: `network not configured correctly`

**Comment by krousey** [comment] 2015-07-08 19:01
It seems this might be a new failure and unrelated to the original.

**Comment by krousey** [comment] 2015-07-08 20:13
That reason is given here https://github.com/GoogleCloudPlatform/kubernetes/blob/master/pkg/kubelet/kubelet.go#L2066 and the boolean that determines it is only modified here https://github.com/GoogleCloudPlatform/kubernetes/blob/master/pkg/kubelet/kubelet.go#L1951 . Neither of the log messages in that function show up in the kubelet log, so I assume the branch that executed was https://github.com/GoogleCloudPlatform/kubernetes/blob/master/pkg/kubelet/kubelet.go#L1962 . 

@dchen1107 It seems that `len(kl.podCIDR) == 0` is causing some e2e test flakiness. I'm not that familiar with kubelet. What does it mean for this to be empty?

**Comment by krousey** [comment] 2015-07-08 20:18
cc @cjcullen @roberthbailey

**Comment by krousey** [comment] 2015-07-08 21:55
I think we have two separate issues here. In

* job/kubernetes-e2e-gce-parallel/3023/
* job/kubernetes-e2e-gce-parallel/3035/
* job/kubernetes-e2e-gce-parallel/3028/

We seem to have a single flake in node readiness that gets reported multiple times for each cleanup that happens to run at that time. It happens in the middle of a test run and then goes away. The root cause of this is unknown. @cjcullen noticed a race at https://github.com/GoogleCloudPlatform/kubernetes/blob/b27a8e1d902adf5ef0e3e4c4a248e40642879f88/pkg/kubelet/kubelet.go#L2098 that probably needs to be protected by `kl.networkConfigMutex`. This may be the cause of it... somehow.

Since the node status is updated in a 30 second loop, we could add logic to the tests to retry up to 30-60 seconds after the last status update on the failing nodes. This would probably reduce random test failures, but wouldn't solve the underlying issue.

The second issue seems to be docker failing to build containers like in job/kubernetes-e2e-gce-parallel/3046/.

```
E0708 20:05:35.510816    3077 manager.go:1579] Error running pod "dns-test-a6805741-25ac-11e5-8fa6-42010af01555_e2e-tests-dns-8q0vk" container "jessie-querier": API error (500): error creating aufs mount to /var/lib/docker/aufs/mnt/b2a84be51ae21ce45bc2cf1ecb944be2b4345c25798af0249260874185622e64-init: invalid argument
```

**Comment by krousey** [comment] 2015-07-08 23:33
I forked the AUFS issue off on it's own.

**Comment by quinton-hoole** [comment] 2015-07-09 00:15
To be clear, the "first" issue above looks as follows in the logs:

**All nodes should be ready after test**, Not ready nodes: [...[{Ready False 2015-07-08 05:23:10 -0700 PDT 2015-07-08 05:23:10 -0700 PDT **network not configured correctly** }] ...

**Comment by quinton-hoole** [comment] 2015-07-09 00:16
The above is also causing remaining failures in #10657

**Comment by quinton-hoole** [comment] 2015-07-10 16:42
@krousey Is there anything left to do in this issue, or can we close it.  Seems like we still need to track down the "network no configured correctly" issue, and the "AUFS mount" issue, but there are separate issues tracking those?

**Comment by krousey** [comment] 2015-07-10 18:02
@quinton-hoole Nothing left. The root causes have other issues and my change mitigates the effect of the most common one.

**Closed by krousey** 2015-07-10 18:02 UTC
Labels: priority/P0, team/testing
