### ISSUE TITLE
TestRunExposeService broken at head

### ISSUE THREAD

**Issue by satnam6502** [GoogleCloudPlatform/kubernetes#11115] opened 2015-07-11 16:41 UTC
The test was expecting ` you will also need to explicitly open a firewall`.

```
--- FAIL: TestRunExposeService (0.01s)
	expose_test.go:173: expose-external-service: unexpected output: &api.Service{TypeMeta:api.TypeMeta{Kind:"", APIVersion:""}, ObjectMeta:api.ObjectMeta{Name:"foo", GenerateName:"", Namespace:"", SelfLink:"", UID:"", ResourceVersion:"", Generation:0, CreationTimestamp:util.Time{Time:time.Time{sec:0, nsec:0, loc:(*time.Location)(nil)}}, DeletionTimestamp:(*util.Time)(nil), Labels:map[string]string{"svc":"test"}, Annotations:map[string]string(nil)}, Spec:api.ServiceSpec{Ports:[]api.ServicePort{api.ServicePort{Name:"default", Protocol:"UDP", Port:14, TargetPort:util.IntOrString{Kind:0, IntVal:14, StrVal:""}, NodePort:0}}, Selector:map[string]string{"func":"stream"}, ClusterIP:"", Type:"LoadBalancer", DeprecatedPublicIPs:[]string(nil), SessionAffinity:""}, Status:api.ServiceStatus{LoadBalancer:api.LoadBalancerStatus{Ingress:[]api.LoadBalancerIngress(nil)}}}
```

**Comment by satnam6502** [comment] 2015-07-11 16:42
@ixdy @quinton-hoole @davidopp

**Comment by satnam6502** [comment] 2015-07-11 16:45
```
$ git log
commit 1b370599ccf271741e657335c4943cb8c7dba28b
Merge: 80e9236 9c84d01
Author: Zach Loafman <zml@google.com>
Date:   Fri Jul 10 21:13:41 2015 -0700

    Merge pull request #11103 from brendandburns/v1.0.0-merge-to-master

    V1.0.0 merge to master
```

**Comment by zmerlynn** [comment] 2015-07-11 17:46
Dupe of #11105, and culprit misidentified :)

**Closed by zmerlynn** 2015-07-11 17:46 UTC
Labels: area/test, kind/bug, priority/P0, team/testing

**Comment by satnam6502** [comment] 2015-07-11 18:35
Ah, OK. Well, my 10 hour flight did not have wifi so I did not have time to catch up with the existing issues.
