### ISSUE TITLE
kubectl.sh reports pods from wrong cluster

### ISSUE THREAD

**Issue by satnam6502** [GoogleCloudPlatform/kubernetes#4298] opened 2015-02-10 22:29 UTC
`kubectl.sh get pods` reports pods from the wrong project. I have no way of listing the pods in the `kubernetes-scale` project because `kubectl.sh` now only wants to show me pods in the `kubernetes-satnam` project. The `PROJECT` environment variable is not set. The banner information from `kubectl` reports the detection of the project being set to `kubernetes-scale`. But look at the minions: they are for a different cluster running in the `kubernetes-satnam` project (a cluster that was created after the kubernetes-scale cluster was created). I think I have reported something similar before.

```
$ echo $PROJECT

$ cat cluster/gce/config-default.sh 
...
KUBE_GCE_INSTANCE_PREFIX=k100
PROJECT=kubernetes-scale
KUBE_GCE_ZONE=asia-east1-b
NUM_MINIONS=100
...
$ cluster/kubectl.sh get pods
Project: kubernetes-scale
Zone: asia-east1-b
Running: cluster/../cluster/gce/../../_output/dockerized/bin/linux/amd64/kubectl get pods
POD                                          IP                  CONTAINER(S)            IMAGE(S)                            HOST                                                               LABELS                                   STATUS
elasticsearch-logging-controller-0133o       10.244.0.7          elasticsearch-logging   dockerfile/elasticsearch            kubernetes-minion-1.c.kubernetes-satnam.internal/130.211.126.213   name=elasticsearch-logging               Running
kibana-logging-controller-fplln              10.244.0.6          kibana-logging          kubernetes/kibana:1.0               kubernetes-minion-1.c.kubernetes-satnam.internal/130.211.126.213   name=kibana-logging                      Running
monitoring-heapster-controller-gziey         10.244.2.6          heapster                kubernetes/heapster:v0.6            kubernetes-minion-3.c.kubernetes-satnam.internal/146.148.69.38     name=heapster,uses=monitoring-influxdb   Running
monitoring-influx-grafana-controller-oh43e   10.244.1.6          influxdb                kubernetes/heapster_influxdb:v0.3   kubernetes-minion-2.c.kubernetes-satnam.internal/104.154.39.253    name=influxGrafana                       Running
                                                                 grafana                 kubernetes/heapster_grafana:v0.3                                                                                                                
skydns-ls6k1                                 10.244.3.6          etcd                    quay.io/coreos/etcd:latest          kubernetes-minion-4.c.kubernetes-satnam.internal/130.211.120.144   k8s-app=skydns                           Running
                                                                 kube2sky                kubernetes/kube2sky:1.0                                                                                                                         
                                                                 skydns                  kubernetes/skydns:2014-12-23-001  
```

**Comment by jlowdermilk** [comment] 2015-02-10 22:45
Can you run `kubectl.sh config view` and paste output?

**Comment by satnam6502** [comment] 2015-02-10 22:47
```
$ cluster/kubectl.sh config view
Project: kubernetes-scale
Zone: asia-east1-b
Running: cluster/../cluster/gce/../../_output/dockerized/bin/linux/amd64/kubectl config view
clusters:
  k100:
    certificate-authority: /usr/local/google/home/satnam/.kube/k100/kubernetes.ca.crt
    server: https://130.211.253.58
  kubernetes:
    certificate-authority: /usr/local/google/home/satnam/.kube/kubernetes/kubernetes.ca.crt
    server: https://146.148.68.120
contexts:
  k100:
    cluster: k100
    user: k100-admin
  kubernetes:
    cluster: kubernetes
    user: kubernetes-admin
current-context: kubernetes
preferences: {}
users:
  k100-admin:
    auth-path: /usr/local/google/home/satnam/.kube/k100/kubernetes_auth
  kubernetes-admin:
    auth-path: /usr/local/google/home/satnam/.kube/kubernetes/kubernetes_auth
```

**Comment by jlowdermilk** [comment] 2015-02-10 22:52
It's not a bug. `kube-up.sh` for gce sets the current context on successful cluster creation so it can validate cluster health using kubectl. You can switch the context to another cluster by running `kubectl config use-context <context>`, where in this case <context> = k100.

If that doesn't fix for you, please reopen.

**Comment by satnam6502** [comment] 2015-02-10 22:56
So to use a different cluster I need to have `cluster/gce/config-default.sh` have the right information, perhaps make sure `PROJECT` etc. are properly set **and** run `kubectl config use-context`?

**Comment by satnam6502** [comment] 2015-02-10 22:58
And after I do all that, I still get the wrong response?
```
$ cluster/kubectl.sh config use-context k100
Project: kubernetes-scale
Zone: asia-east1-b
Running: cluster/../cluster/gce/../../_output/dockerized/bin/linux/amd64/kubectl config use-context k100
$ cluster/kubectl.sh get pods
Project: kubernetes-scale
Zone: asia-east1-b
Running: cluster/../cluster/gce/../../_output/dockerized/bin/linux/amd64/kubectl get pods
POD                                          IP                  CONTAINER(S)            IMAGE(S)                            HOST                                                               LABELS                                   STATUS
elasticsearch-logging-controller-0133o       10.244.0.7          elasticsearch-logging   dockerfile/elasticsearch            kubernetes-minion-1.c.kubernetes-satnam.internal/130.211.126.213   name=elasticsearch-logging               Running
kibana-logging-controller-fplln              10.244.0.6          kibana-logging          kubernetes/kibana:1.0               kubernetes-minion-1.c.kubernetes-satnam.internal/130.211.126.213   name=kibana-logging                      Running
monitoring-heapster-controller-gziey         10.244.2.6          heapster                kubernetes/heapster:v0.6            kubernetes-minion-3.c.kubernetes-satnam.internal/146.148.69.38     name=heapster,uses=monitoring-influxdb   Running
monitoring-influx-grafana-controller-oh43e   10.244.1.6          influxdb                kubernetes/heapster_influxdb:v0.3   kubernetes-minion-2.c.kubernetes-satnam.internal/104.154.39.253    name=influxGrafana                       Running
                                                                 grafana                 kubernetes/heapster_grafana:v0.3                                                                                                                
skydns-ls6k1                                 10.244.3.6          etcd                    quay.io/coreos/etcd:latest          kubernetes-minion-4.c.kubernetes-satnam.internal/130.211.120.144   k8s-app=skydns                           Running
                                                                 kube2sky                kubernetes/kube2sky:1.0                                                                                                                         
                                                                 skydns                  kubernetes/skydns:2014-12-23-001                  
```

**Comment by satnam6502** [comment] 2015-02-10 22:59
It's also highly confusing the have `kubectl.sh` report:
```
Project: kubernetes-scale
Zone: asia-east1-b
```
and then work on an entirely different cluster.

**Comment by satnam6502** [comment] 2015-02-10 23:02
You might enjoy this and what is reported as the current context:

```
$ cluster/kubectl.sh config use-context k100
Project: kubernetes-scale
Zone: asia-east1-b
Running: cluster/../cluster/gce/../../_output/dockerized/bin/linux/amd64/kubectl config use-context k100
$ cluster/kubectl.sh config view
Project: kubernetes-scale
Zone: asia-east1-b
Running: cluster/../cluster/gce/../../_output/dockerized/bin/linux/amd64/kubectl config view
clusters:
  k100:
    certificate-authority: /usr/local/google/home/satnam/.kube/k100/kubernetes.ca.crt
    server: https://130.211.253.58
  kubernetes:
    certificate-authority: /usr/local/google/home/satnam/.kube/kubernetes/kubernetes.ca.crt
    server: https://146.148.68.120
contexts:
  k100:
    cluster: k100
    user: k100-admin
  kubernetes:
    cluster: kubernetes
    user: kubernetes-admin
current-context: kubernetes
preferences: {}
users:
  k100-admin:
    auth-path: /usr/local/google/home/satnam/.kube/k100/kubernetes_auth
  kubernetes-admin:
    auth-path: /usr/local/google/home/satnam/.kube/kubernetes/kubernetes_auth
```

**Comment by jlowdermilk** [comment] 2015-02-10 23:09
OK, that output/behavior is confusing and unhelpful. I'll fix it.

In the meantime, try `cluster/kubectl.sh config use-context k100 --global` to switch context.

**Comment by jlowdermilk** [comment] 2015-02-11 20:48
To summarize offline discussion for how to fix creating/deleting/interacting with multiple clusters

Problems:
- Cluster creation/teardown gets cluster info from cluster/KUBERNETES_PROVIDER/util.sh, but interacting with a running cluster (`kubectl *`) gets cluster info from a `.kubeconfig` file only.
- `cluster/kubectl.sh` is misleading about what cluster `kubectl` will talk to.
- The fact `cluster/kubectl.sh` exists at all is an annoyance.

Proposal:
- Store cluster spec in `.kubeconfig` extensions, and have cluster/KUBERNETES_PROVIDER/util.sh read said config and use it to export necessary shell variables. All config required to create/delete the cluster will be specified in a `.kubeconfig` file, and kube-up/kube-down will read said config using `kubeconfig view`.
- For now: make `cluster/kubectl.sh` report current the `.kubeconfig` context and cluster that will be used.
- For later: deprecate cluster/kubectl.sh. It's primary function is finding a built kubectl binary, though it also does some special setup for gke testing.

**Comment by jlowdermilk** [comment] 2015-02-12 01:52
After some experimentation, I have to retract the above proposal. .kubeconfig extensions can't be used to store arbitrary values, at least not using `kubectl config set`.

So the first bullet is to implement something like what was proposed in #3525. I do still intend to make cluster/kubectl.sh report the current context and cluster; also need to update all providers to set config in their kube-up.sh.

**Comment by satnam6502** [comment] 2015-02-12 04:35
Power to you. Let me know how I can help. Although I am working on a P1 fixit bug for the next week.

**Comment by jlowdermilk** [comment] 2015-02-20 23:34
I'm going to close this as the initial problem has a workaround for now, and action items are better represented in other issues:
- #3525 for better cluster deployment solution
- #4428 for fixing .kubeconfig behavior.

**Closed by jlowdermilk** 2015-02-20 23:34 UTC
Labels: area/usability, priority/P1, team/UX
