### ISSUE TITLE
Pod init hooks

### ISSUE THREAD

**Issue by bkeroackdsc** [GoogleCloudPlatform/kubernetes#9836] opened 2015-06-16 01:11 UTC
I have a container in a pod whose only job is to populate some configuration values within the pod-local etcd on startup. This works fine except that after it exits successfully Kubernetes continually respawns it over and over again.

My current hack is to append ``&& tail -f /dev/null`` to the container command to allow it to "run" indefinitely. 

It would be great if Kubernetes allowed one to specify certain containers as non-respawning in the pod spec.

**Comment by mikedanese** [comment] 2015-06-16 01:30
Is it possible for you to use a container lifecycle hook? http://godoc.org/github.com/GoogleCloudPlatform/kubernetes/pkg/api/v1#Lifecycle

RestartPolicy is almost what you want but it is applied over all the containers in a pod. http://godoc.org/github.com/GoogleCloudPlatform/kubernetes/pkg/api/v1#RestartPolicy

**Comment by bkeroackdsc** [comment] 2015-06-16 03:16
@mikedanese RestartPolicy would be perfect if only it were per-container rather than pod.

I wouldn't mind trying to implement this if there's interest.

**Comment by mikedanese** [comment] 2015-06-16 03:26
cc @bgrant0607 for api changes.

**Comment by thockin** [comment] 2015-06-16 04:12
The corner cases around mixed-restart-policy pods is not worth the energy.
This is what lifecycle hooks should do, and if they aren't sufficient, we
should make them sufficient.

**Comment by davidopp** [comment] 2015-06-16 05:46
It's true that the most common use cases of sidecar containers, for example data loader and log saver, will run forever. However, IIRC we've occasionally told people to use sidecar containers for various kinds of initial configuration, and in those cases it seems that having the sidecar run once to completion and the other pod restart would be desirable.

I guess the lifecycle hook proposal would be that you merge the configuration container logic into the main container's logic, so that you have just one container, and have the PreStart hook invoke the former?

Anyway, I don't have a strong opinion.

**Comment by thockin** [comment] 2015-06-16 05:50
We've thrown out the idea of having two stages in a pod - stage 1 only
completes when stage 0 is done.  E.g. all the containers in stage 1 have
completed successfully.  Like so many other things, it is a matter of
priority and making time for it among the ocean of other things going on :)

**Comment by davidopp** [comment] 2015-06-16 05:54
Yeah, I was assuming the user would be responsible for orchestrating the dependency between the two containers (e.g. the application in the main container would wait until the configuration data was populated by the other container before finishing its startup).

**Comment by bgrant0607** [comment] 2015-06-16 15:29
Pod-level hook or container volume #831 would be the right solution.

Original discussion re. restart policy was #127.

**Comment by bgrant0607** [comment] 2015-06-20 04:04
Closing as a dupe of #4282

**Closed by bgrant0607** 2015-06-20 04:04 UTC
Labels: area/cluster-api, area/usability, priority/P3, team/node
