### ISSUE TITLE
externalLoadBalancer GCE API should allow equivalent services in different clusters to share a load balancer

### ISSUE THREAD

**Issue by mikedanese** [GoogleCloudPlatform/kubernetes#10505] opened 2015-06-29 22:21 UTC
The target pool would contain the nodes in both clusters. This is required for multi-cluster HA/load-balancing.

**Comment by bgrant0607** [comment] 2015-06-29 23:13
Dupe of #3683. Please comment there and close this.

See also #4235

**Closed** 2015-06-29 23:20 UTC
Labels: priority/P2, team/cluster
