### ISSUE TITLE
Namespace needs to be specified to kubectl when already present in pod spec

### ISSUE THREAD

**Issue by satnam6502** [GoogleCloudPlatform/kubernetes#7789] opened 2015-05-05 19:11 UTC
If a pod spec has a namespace specified it must still be specified by a flag when creating it with `kubectl`. I've already had a discussion about this with @smarterclayton and @jlowdermilk but I think it was deemed to be "worked as intended". However, @bgrant0607 considers this a bug.

```
$ cat music-db-pod1.yaml 
apiVersion: v1beta3
kind: Pod
metadata:
  name: music-db1
  namespace: mytunes
  labels:
    name: music
spec:
  containers:
  - name: es
    image: satnam6502/elasticsearch:1.3
    ports:
    - name: es
      containerPort: 9200
    - name: es-transport
      containerPort: 9300
  - name: kibana
    image: satnam6502/kibana
    ports:
    - name: kibana
      containerPort: 5601
$ kubectl create -f music-db-pod1.yaml 
Error: the namespace from the provided object "mytunes" does not match the namespace "default". You must pass '--namespace=mytunes' to perform this operation.
$ kubectl create -f music-db-pod1.yaml --namespace=mytunes
pods/music-db1
```

**Comment by jlowdermilk** [comment] 2015-05-05 20:35
@smarterclayton, so should `kubectl create` use namespace provided in schema only if default is unset, or should schema namespace overwrite command namespace?

**Comment by smarterclayton** [comment] 2015-05-05 20:38
Command namespace should overwrite schema namespace on create.  Update, Delete, and Get are harder to answer.

----- Original Message -----

**Comment by bgrant0607** [comment] 2015-05-05 22:25
I think it clearly violates POLS for an implicit setting (kubeconfig context, esp. the default one) to override an explicit one (namespace in schema).

I understand that we want to make it easy to export objects from one namespace and import them into another, but I think we should provide a mechanism to scrub the objects first, for example, removing the explicit namespace (and status, readonly fields, etc.).

If no namespace is specified in the schema, then I'd expect the one from kubeconfig to be used.

If a namespace is explicitly specified on the command line and that conflicts with the one in the schema, kubectl should raise an error.

**Comment by smarterclayton** [comment] 2015-05-05 22:27
Which is what we do today.  I'm ok leaving it as is.

**Comment by bgrant0607** [comment] 2015-05-05 22:32
Well, it would be nice for the implicit setting to be overridden by the explicit one without an error.

**Comment by hobti01** [comment] 2015-05-15 08:22
One would expect this to work, but it doesn't:
`kubectl create -f /manifestsInManyNamespaces/`

If I specify no namespace, the `default` namespace colliding with the namespace in the schema is unexpected.

Without allowing the schema to take precedence over "unspecified", there is not a way to deploy multiple manifests in different namespaces without knowing or inspecting all the namespaces.  This would tie into https://github.com/GoogleCloudPlatform/kubernetes/issues/5840

**Comment by smarterclayton** [comment] 2015-05-15 14:34
Someone should have to send a flag.  With --all-namespaces being set, that could potentially be supported.  You still need a default namespace.  Create in many namespaces is an optional, non-default mode, because it is dangerous.

----- Original Message -----

**Comment by hobti01** [comment] 2015-05-15 14:44
I can see the potential for abuse.  It seems that  https://github.com/GoogleCloudPlatform/kubernetes/pull/7024 implements a flag of sorts with --namespace="*" instead of --all-namespaces

**Comment by smarterclayton** [comment] 2015-05-15 15:02
Originally, but it was supposed to switch to --all-namespaces.

----- Original Message -----

**Comment by BugRoger** [comment] 2015-06-11 14:34
I was trying to put all infrastructure related resources into their own namespace. A side effect of this regression is that manifests have to live in the `default` namespace.

e.g. given the namespace `cluster` directly in the manifest, kubelet will complain with:
```
kubelet.go:1159] Failed creating a mirror pod "fluentd-to-elasticsearch-10.97.90.138_cluster": the namespace of the provided object does not match the namespace sent on the request
```

**Comment by smarterclayton** [comment] 2015-06-12 16:16
Just because you said that - openshift recently switched to creating our system level service accounts in a namespace (configurable) called "openshift-infra".  We should try to have a common pattern between Kube and OpenShift there.  What name were you going to default to, "cluster"?

----- Original Message -----

**Comment by BugRoger** [comment] 2015-06-15 08:24
> What name were you going to default to, "cluster"?
Yes, after creating too many namespaces (like `monitoring`, `logging`, ..) we figured that there is a trade-off between namespaces and filtering. I chose `cluster` as a "global" bucket for infrastructure like services. Though I'm in no way married to that term.

On the concrete problem, I would expect that the kubelet starts its manifests with the `--all-namespaces` flag or similar.

**Comment by bgrant0607** [comment] 2015-06-24 20:45
cc @krousey

**Comment by krousey** [comment] 2015-06-25 17:50
So from what I gather the behavior we want is something like this:

Namespace in .kube/config | Namespace on command line | Namespace in spec | Result
-------------------------------------|------------------------------------------|----------------------------|---------
* | Yes | Yes | Error if command line and spec disagree
* | Yes | No | Use command line namespace
* | No | Yes | Use spec namespace even if it disagrees with .kube/config
Yes | No | No | Use .kube/config namespace
No |  No | No | Use "default" namespace

Is this right? From what I can tell, I might be able to do this by checking the context's LocationOfOrigin. Still haven't found where the namespace flag is used though, so I have to track that down.

**Comment by deads2k** [comment] 2015-06-25 20:03
> Is this right?

If .kube/config=yes and spec=yes and they conflict, do you expect an error?  



> Still haven't found where the namespace flag is used though, so I have to track that down.

Flags are bound here: https://github.com/GoogleCloudPlatform/kubernetes/blob/master/pkg/kubectl/cmd/util/factory.go#L332, passed here: https://github.com/GoogleCloudPlatform/kubernetes/blob/master/pkg/client/clientcmd/client_config.go#L63, and used here: https://github.com/GoogleCloudPlatform/kubernetes/blob/master/pkg/client/clientcmd/client_config.go#L266.  Basically, whether the name came from a flag or the .kube/config is transparent to callers who get client.Configs.

**Comment by krousey** [comment] 2015-06-25 20:57
cc @ghodss

**Comment by krousey** [comment] 2015-06-25 21:00
> If .kube/config=yes and spec=yes and they conflict, do you expect an error?

I don't think so. On May 5, @bgrant0607 said

> Well, it would be nice for the implicit setting to be overridden by the explicit one without an error.

I believe he was referring to that case specifically.

**Comment by smarterclayton** [comment] 2015-06-25 22:05
As a user I think you want explicit to override, not error.  I think.

**Comment by krousey** [comment] 2015-06-25 22:24
It looks like to accomplish this, I would need to expose DirectClientConfig's overrides somehow. https://github.com/GoogleCloudPlatform/kubernetes/blob/5520386b18/pkg%2Fclient%2Fclientcmd%2Fclient_config.go#L54

**Comment by krousey** [comment] 2015-06-25 22:25
> As a user I think you want explicit to override, not error.  I think.

@bgrant0607 comments on this?

**Comment by smarterclayton** [comment] 2015-06-25 22:28
I think I'm agreeing with Brian's comment.

**Comment by krousey** [comment] 2015-06-25 22:31
@smarterclayton Ah ok. I thought you were commenting on the first row I listed where it's explicit on the command line and in the spec.

**Comment by bgrant0607** [comment] 2015-07-06 17:13
I believe this was fixed by PR #10493

**Closed by bgrant0607** 2015-07-06 17:13 UTC
Labels: component/CLI, kind/bug, kind/friction, priority/P2, team/UX

**Comment by anguslees** [comment] 2017-02-17 06:49
I believe the:
`*	No	Yes	Use spec namespace even if it disagrees with .kube/config`
case from the above table was *not* implemented by PR #10493.

Specifically I have config files that contain explicit namespace statements.  Works fine out of cluster, works in-cluster (no .kube/config) with 1.4.x kubectl's, fails in-cluster with 1.5.x.  I would like it to work the same in/out of cluster, or I would like a `--do-what-i-say` flag :/

**Comment by smarterclayton** [comment] 2017-02-17 14:54
Yeah, it should be consistent.  Can you spawn an issue for it?

**Comment by geekofalltrades** [comment] 2017-12-05 00:49
Did the followup issue ever get created? I would love to go track it.

I've got a manifest that creates RBAC resources in both my-namespace and kube-system. My `.kube/config` is using a context with `namespace: my-namespace`. When I try to apply or create the manifest, the resources in `kube-system` will not create.

```
error: the namespace from the provided object "kube-system" does not match the namespace "my-namespace". You must pass '--namespace=kube-system' to perform this operation.
```
