### ISSUE TITLE
replicationcontroller watch does not update when status.replicas changes

### ISSUE THREAD

**Issue by stefwalter** [GoogleCloudPlatform/kubernetes#4525] opened 2015-02-18 09:48 UTC
If i watch replicationcontroller objects (with ```/api/v1beta3/watch/replicationcontrollers```), and change it's ```spec.replicas```, even after the new pods are created the watch never reports a "MODIFIED" event when the value of ```status.replicas``` changes.

Do watches fail to report a "MODIFIED" event when a calculate field of an object changes?

**Comment by stefwalter** [comment] 2015-02-18 09:52
Here is the watch event when ```spec.replicas``` changes:

```
{"type":"MODIFIED","object":{"kind":"ReplicationController","apiVersion":"v1beta3","metadata":{"name":"frontendcontroller","namespace":"default","selfLink":"/api/v1beta3/replicationcontrollers/frontendcontroller","uid":"77d4f7fa-b751-11e4-83f7-10c37bdb8410","resourceVersion":"2967925","creationTimestamp":"2015-02-18T10:35:25+01:00","labels":{"name":"frontendcontroller","template":"ruby-helloworld-sample"}},"spec":{"replicas":4,"selector":{"name":"frontend"},"template":{"metadata":{"creationTimestamp":null,"labels":{"name":"frontend","template":"ruby-helloworld-sample"}},"spec":{"volumes":null,"containers":[{"name":"ruby-helloworld","image":"openshift/ruby-hello-world","ports":[{"containerPort":8080,"protocol":"TCP"}],"env":[{"name":"ADMIN_USERNAME","value":"admin6TM"},{"name":"ADMIN_PASSWORD","value":"xImx1tHR"},{"name":"MYSQL_ROOT_PASSWORD","value":"rQHfVnTo"},{"name":"MYSQL_DATABASE","value":"root"}],"resources":{},"terminationMessagePath":"/dev/termination-log","imagePullPolicy":"IfNotPresent","capabilities":{}}],"restartPolicy":{"always":{}},"dnsPolicy":"ClusterFirst"}}},"status":{"replicas":3}}}
```

Here is the watch event for the new pod being created:

```
{"type":"ADDED","object":{"kind":"Pod","apiVersion":"v1beta3","metadata":{"name":"frontendcontroller-182tv","generateName":"frontendcontroller-","namespace":"default","selfLink":"/api/v1beta3/pods/frontendcontroller-182tv","uid":"d783a23d-b752-11e4-83f7-10c37bdb8410","resourceVersion":"2967926","creationTimestamp":"2015-02-18T10:45:15+01:00","labels":{"name":"frontend","template":"ruby-helloworld-sample"}},"spec":{"volumes":null,"containers":[{"name":"ruby-helloworld","image":"openshift/ruby-hello-world","ports":[{"containerPort":8080,"protocol":"TCP"}],"env":[{"name":"ADMIN_USERNAME","value":"admin6TM"},{"name":"ADMIN_PASSWORD","value":"xImx1tHR"},{"name":"MYSQL_ROOT_PASSWORD","value":"rQHfVnTo"},{"name":"MYSQL_DATABASE","value":"root"}],"resources":{},"terminationMessagePath":"/dev/termination-log","imagePullPolicy":"IfNotPresent","capabilities":{}}],"restartPolicy":{"always":{}},"dnsPolicy":"ClusterFirst"},"status":{"phase":"Pending"}}}
```

And there are no further watch "MODIFIED" events from the replication controller. Retrieving the replication controller, clearly shows the ```status.replicas``` field is now ```4```.

```
{
  "kind": "ReplicationController",
  "apiVersion": "v1beta3",
  "metadata": {
    "name": "frontendcontroller",
    "namespace": "default",
    "selfLink": "/api/v1beta3/namespaces/default/replicationcontrollers/frontendcontroller",
    "uid": "77d4f7fa-b751-11e4-83f7-10c37bdb8410",
    "resourceVersion": "2967925",
    "creationTimestamp": "2015-02-18T10:35:25+01:00",
    "labels": {
      "name": "frontendcontroller",
      "template": "ruby-helloworld-sample"
    }
  },
  "spec": {
    "replicas": 4,
    "selector": {
      "name": "frontend"
    },
    "template": {
      "metadata": {
        "creationTimestamp": null,
        "labels": {
          "name": "frontend",
          "template": "ruby-helloworld-sample"
        }
      },
      "spec": {
        "volumes": null,
        "containers": [
          {
            "name": "ruby-helloworld",
            "image": "openshift/ruby-hello-world",
            "ports": [
              {
                "containerPort": 8080,
                "protocol": "TCP"
              }
            ],
            "env": [
              {
                "name": "ADMIN_USERNAME",
                "value": "admin6TM"
              },
              {
                "name": "ADMIN_PASSWORD",
                "value": "xImx1tHR"
              },
              {
                "name": "MYSQL_ROOT_PASSWORD",
                "value": "rQHfVnTo"
              },
              {
                "name": "MYSQL_DATABASE",
                "value": "root"
              }
            ],
            "resources": {},
            "terminationMessagePath": "/dev/termination-log",
            "imagePullPolicy": "IfNotPresent",
            "capabilities": {}
          }
        ],
        "restartPolicy": {
          "always": {}
        },
        "dnsPolicy": "ClusterFirst"
      }
    }
  },
  "status": {
    "replicas": 4
  }
}
```

**Comment by stefwalter** [comment] 2015-02-18 12:56
This is with v0.10.0

**Comment by bgrant0607** [comment] 2015-02-18 15:09
Yes, sorry. Known issue. Dupe of #2726 and #4429.

**Closed by bgrant0607** 2015-02-18 15:09 UTC
