### ISSUE TITLE
Kubelet kills POD container after other containers when the containers have changed

### ISSUE THREAD

**Issue by vishh** [GoogleCloudPlatform/kubernetes#4759] opened 2015-02-24 02:02 UTC
cAdvisor API is not accessible from the node. It is accessible from inside the cadvisor container though. This is the reason for the cadvisor e2e test to fail and the recent heapster errors reported by users.
The cadvisor version itself hasn't changed recently though.

**Comment by vishh** [comment] 2015-02-24 02:03
cc @vmarmol

**Comment by vmarmol** [comment] 2015-02-24 02:04
There were some changes recently around port forwarding (@thockin?) that may be the cause.

**Comment by vishh** [comment] 2015-02-24 02:06
From the node:
```shell
kubernetes-minion-1jkk:~$ curl -X GET  http://localhost:4194/api/v1.1/machine/
curl: (52) Empty reply from server
```
From the cadvisor container:
```shell
kubernetes-minion-1jkk:~$ sudo docker exec -it 95982d9d81c2 /bin/sh
/ # wget http://localhost:8080/api/v1.2/containers/
Connecting to localhost:8080 (127.0.0.1:8080)
index.html           100% |***********************************************************************************************************************************************************| 49118   0:00:00 ETA
```

**Comment by rjnagal** [comment] 2015-02-24 02:11
@fbalejko reported the same issue today. Restarting the container seems to fix it. So, its something to do with the initial setup.

**Comment by vmarmol** [comment] 2015-02-24 02:15
Could this be due to Docker 1.5?

**Comment by rjnagal** [comment] 2015-02-24 06:50
@fbalejko test machine is running Docker 1.4.1

It looks like cadvisor container is sharing its networking with the pause container as usual, but the pause container got restarted, so the networking setup isn't working anymore. Restarting cadvisor connects it to the newer instance of the pause container and it starts working again.

```
  $ sudo docker ps
  ...
  80a93a11222        kubernetes/pause:go                    "/pause"               13 hours ago        Up 13 hours         0.0.0.0:4194->8080/tcp   
                        k8s_POD.252debe0_cadvisor-agent.file-6bb810db-kubernetes-minion-igxg.file_c3d9c6cbab14b59a9452fccef9d4eb5c_000b12c9        
            
  742a89f6ae85        google/cadvisor:0.8.0                  "/usr/bin/cadvisor"    13 hours ago        Up 13 hours                                  
                        k8s_cadvisor.8d424740_cadvisor-agent.file-6bb810db-kubernetes-minion-igxg.file_c3d9c6cbab14b59a9452fccef9d4eb5c_e6d19728  
...
```

However docker inspect shows that cadvisor is connected to network of a different pause container:

```
$ sudo docker inspect 742a89f6ae85
"IpcMode": "container:670951d3b94c55ff65d22162a6ad16eea0847f321afaf2fb1f8e68b5a92609c5",
        "Links": null,
        "LxcConf": null,
        "NetworkMode": "container:670951d3b94c55ff65d22162a6ad16eea0847f321afaf2fb1f8e68b5a92609c5",
        "PortBindings": {
            "8080/tcp": [
                {
                    "HostIp": "",
                    "HostPort": "4194"
                }
            ]
        },
```

And that container died soon after it started

```
$ sudo docker ps -a | grep 670951d3b94c
670951d3b94c        kubernetes/pause:go                    "/pause"               13 hours ago        Exited (2) 13 hours ago 
```

Kubelet killed the pause container.
I think this is kubelet's doing. It tried to restart both pause and cadvisor container. It kills and restarts cadvisor container which connects to existing pause container. Then, it goes ahead and kills/restarts the pause container, leaving the new cadvisor container hanging.

```
I0223 17:01:02.091756    4859 kubelet.go:1129] pod "cadvisor-agent.file-6bb810db-kubernetes-minion-igxg.file" container "cadvisor" hash changed (499795593 vs 2369931072). Container will be killed and re-created.
I0223 17:01:02.091785    4859 kubelet.go:896] Killing container with id "3eb7638333efbcdb9b9fab425f5c9963189e70953ef3a0f006d0ae8253707c2a" and name
 "/k8s_cadvisor.1dca4689_cadvisor-agent.file-6bb810db-kubernetes-minion-igxg.file_c3d9c6cbab14b59a9452fccef9d4eb5c_20f1496c"
...
I0223 17:01:03.202042    4859 event.go:137] Event(api.ObjectReference{Kind:"BoundPod", Namespace:"file-6bb810db-kubernetes-minion-igxg", Name:"cadvisor-agent", UID:"c3d9c6cbab14b59a9452fccef9d4eb5c", APIVersion:"v1beta2", ResourceVersion:"", FieldPath:"spec.containers{cadvisor}"}): reason: 'created' Created with docker id 742a89f6ae85213d9b226becdd6048683e96bc70df64121727c716671e603895
I0223 17:01:03.244041    4859 kubelet.go:896] Killing container with id "670951d3b94c55ff65d22162a6ad16eea0847f321afaf2fb1f8e68b5a92609c5" and name
 "/k8s_POD.252debe0_cadvisor-agent.file-6bb810db-kubernetes-minion-igxg.file_c3d9c6cbab14b59a9452fccef9d4eb5c_0159ea51"
```

Maybe this is related to infra pods issue reported by @smarterclayton earlier, or maybe just an ordering issue in kubelet. @dchen1107

**Comment by vmarmol** [comment] 2015-02-24 07:06
Thanks for the detailed debugging @rjnagal :) with your report I think I found the issue.

In [syncPod()](https://github.com/GoogleCloudPlatform/kubernetes/blob/master/pkg/kubelet/kubelet.go#L1013) we check if the container has changed and print the [hash changed](https://github.com/GoogleCloudPlatform/kubernetes/blob/master/pkg/kubelet/kubelet.go#L1120) message above. *After* that we [restart](https://github.com/GoogleCloudPlatform/kubernetes/blob/master/pkg/kubelet/kubelet.go#L1189) the POD container. We should be doing this before the container restart as you pointed out.

I'm assigning this to myself and I will fix tomorrow. Will also rename the bug and re-purpose it.

**Comment by rjnagal** [comment] 2015-02-24 07:10
cool, I was just staring at that code. All yours :+1:

**Comment by dchen1107** [comment] 2015-02-24 15:03
Thanks for debugging the issue. This is a regression we introduced lately.

**Comment by zmerlynn** [comment] 2015-02-24 15:14
And when @vishh added the test, we all assumed it was the test failing. Sorry, @vishh. :)

**Comment by vishh** [comment] 2015-02-24 18:11
@zmerlynn: I fell for that until I realized that the basic networking can also fail :)

**Closed** 2015-02-24 21:37 UTC
Labels: kind/bug, priority/P0, team/node
