### ISSUE TITLE
Field selectors are incomplete and inconsistent.

### ISSUE THREAD

**Issue by brendandburns** [GoogleCloudPlatform/kubernetes#3042] opened 2014-12-18 22:00 UTC
We currently have a limited set of field selectors for listing pods:
https://github.com/GoogleCloudPlatform/kubernetes/blob/master/pkg/registry/pod/rest.go#L140

And not for any other resources.

We need to do two things:
1. Unify "field selectors" and "label selectors" into a single selector map.
2. Use reflection to support arbitrary field selectors, without resorting to the hack above.

I propose that we unify on "explicit labels" which are the contents of the labels field, and "implicit labels" which are all fields in the API object.  (indeed explicit labels can be seen as syntactic sugar on top of implicit labels ".metadata.labels.foo=bar")

**Comment by bgrant0607** [comment] 2015-03-10 21:30
Note that we're currently going in the opposite direction of unification.

But we do need to make the support consistent.

This isn't really a bug.

**Comment by bgrant0607** [comment] 2015-03-10 21:30
See #5171.

**Comment by lavalamp** [comment] 2015-03-11 17:15
Is there anything concrete to do here? They're now versioned and it seems we're not going to merge them.

**Comment by bgrant0607** [comment] 2015-03-11 17:18
Dupe of #1362.

**Closed by bgrant0607** 2015-03-11 17:18 UTC
Labels: api/cluster, area/usability, kind/enhancement, kind/gsoc, priority/P2, status/help-wanted, team/UX
