### ISSUE TITLE
Pods hang in pending state indefinitely

### ISSUE THREAD

**Issue by heytrav** [GoogleCloudPlatform/kubernetes#4891] opened 2015-02-27 09:59 UTC
When trying to start pods in my CoreOS cluster, they stay in a *Pending* state indefinitely and I cannot see any sign that the docker containers are being downloaded or anything else that would indicate that it is doing something to activate the controller. I am not sure if the problem is with my configuration but I thought I'd ask to see if someone else had encountered this problem.

Here is one of the controllers that I have been trying to run.
```yaml
id: elasticsearch-data
kind: ReplicationController
apiVersion: v1beta1
desiredState:
    replicas: 1
    replicaSelector:
        component: elasticsearch
        role: data
    podTemplate:
        desiredState:
            manifest:
                version: v1beta1
                id: elasticsearch-data
                containers:
                    - name: elasticsearch-data
                      image: quay.io/heytrav/elasticsearch:v0.0.8-data
                      ports:
                          - name: transport
                            containerPort: 9300
                      volumeMounts:
                          - name: es-persistent-storage
                            mountPath: "/data"
                            readOnly: false
                volumes:
                    - name: es-persistent-storage
                      source:
                          emptyDir: {}
        labels:
            component: elasticsearch
            role: data

```

I'm not really seeing much in the logs to indicate that there is something wrong, but the pod hangs in a *Pending* state:

```
core@bart ~/staging $ kubectl get pods
POD                        IP                  CONTAINER(S)         IMAGE(S)                                    HOST                LABELS                              STATUS
elasticsearch-data-gziey                       elasticsearch-data   quay.io/heytrav/elasticsearch:v0.0.8-data   10.132.218.185/     component=elasticsearch,role=data   Pending
```

I initially tried this on a 3 node cluster at Digital Ocean and now currently on just a single node. 

Here are the binaries that I'm running
```
core@bart ~ $ kube-controller-manager --version
Kubernetes v0.11.0-dirty
core@bart ~ $ kube-kubelet --version
-bash: kube-kubelet: command not found
core@bart ~ $ kubelet --version
Kubernetes v0.11.0-dirty
core@bart ~ $ kube-proxy --version
Kubernetes v0.11.0-dirty
core@bart ~ $ kube-scheduler --version
Kubernetes v0.11.0-dirty
core@bart ~ $ kube-api-server
-bash: kube-api-server: command not found
core@bart ~ $ kube-apiserver --version
Kubernetes v0.11.0-dirty
```

Any help debugging this would be appreciated

**Comment by thockin** [comment] 2015-02-27 18:18
Can you run kubectl get events?

**Comment by heytrav** [comment] 2015-02-27 18:30
```
core@bart ~ $ kubectl get pods
POD                        IP                  CONTAINER(S)         IMAGE(S)                                    HOST                LABELS                              STATUS
elasticsearch-data-gziey                       elasticsearch-data   quay.io/heytrav/elasticsearch:v0.0.8-data   10.132.218.185/     component=elasticsearch,role=data   Pending


core@bart ~ $ kubectl get events
FIRSTSEEN                         LASTSEEN                          COUNT               NAME                       KIND                SUBOBJECT           REASON              SOURCE                    MESSAGE
Fri, 27 Feb 2015 01:46:57 +0000   Fri, 27 Feb 2015 01:46:57 +0000   1                   104.236.200.4              Minion                                  starting            {kubelet 104.236.200.4}   Starting kubelet.
Fri, 27 Feb 2015 06:59:02 +0000   Fri, 27 Feb 2015 06:59:02 +0000   1                   rabbitmq-fplln             Pod                                     scheduled           {scheduler }              Successfully assigned rabbitmq-fplln to 10.132.218.185
Fri, 27 Feb 2015 08:45:52 +0000   Fri, 27 Feb 2015 08:45:52 +0000   1                   104.236.200.4              Minion                                  starting            {kubelet 104.236.200.4}   Starting kubelet.
Fri, 27 Feb 2015 09:07:57 +0000   Fri, 27 Feb 2015 09:07:57 +0000   1                   elasticsearch-data-gziey   Pod                                     scheduled           {scheduler }              Successfully assigned elasticsearch-data-gziey to 10.132.218.185
Fri, 27 Feb 2015 09:24:05 +0000   Fri, 27 Feb 2015 09:24:05 +0000   1                   104.236.200.4              Minion                                  starting            {kubelet 104.236.200.4}   Starting kubelet.
Fri, 27 Feb 2015 09:24:20 +0000   Fri, 27 Feb 2015 09:24:20 +0000   1                   elasticsearch-data-gziey   Pod                                     scheduled           {scheduler }              Successfully assigned elasticsearch-data-gziey to 10.132.218.185

```

**Comment by derekwaynecarr** [comment] 2015-02-27 18:38
I am seeing a similar but slightly different issue where pods and nodes are always reporting an "Unknown" status.  I can see when I create a pod that it is scheduled, and when I describe the pod, I can see the containers were pulled and started, but the actual status is not changing to running.

**Comment by thockin** [comment] 2015-02-27 18:41
@dchen1107 @davidopp who have been looking at the state-setting logic

**Comment by dchen1107** [comment] 2015-02-27 20:37
@derekwaynecarr Which version you are running into this issue? I fixed an Unknown status issue (#4188) a while back by 

1) Kubelet generates PodStatus when node is reachable
2) Adding error handling to system when docker API calls failed. 

But there is still an issue when a node status is not-reachable, all bounded pods on that node will be reset to Unknown. Please run kubectl get nodes to see the status of node. 

@heytrav From what you posted above, it looks like kubelet doesn't know pod is scheduled to the node since there are no events coming from kubelet except starting ones.

**Comment by derekwaynecarr** [comment] 2015-02-27 20:39
This was on HEAD this morning.

**Comment by dchen1107** [comment] 2015-02-27 20:45
@derekwaynecarr Can you run kubectl get nodes when Unknown issue occurs?

**Comment by heytrav** [comment] 2015-02-27 20:46
@dchen1107 I've suspected that it is something like that, but am not sure if I configured something incorrectly or if there is indeed a bug. Any advice how I can diagnose this?

**Comment by dchen1107** [comment] 2015-02-27 20:55
@heytrav   Can I have the command how you run kubelet? Also can you run kubelet with --v=4 and post the log somewhere I can take a look?

**Comment by derekwaynecarr** [comment] 2015-02-27 21:06
I am about to fly but I will report back if I see the issue later.

**Comment by brendandburns** [comment] 2015-02-27 21:10
Most always this is caused by hostname / machine flag mismatch between the
master and kubelet.  You may need to set --hostname-override on the kubelet
binary.

Brendan

**Comment by heytrav** [comment] 2015-02-27 21:10
@dchen1107  here's what I'm running (I just added --v=4, but the rest is the same)
```
[Service]
EnvironmentFile=/etc/network-environment
ExecStartPre=/usr/bin/wget -N -P /opt/bin https://storage.googleapis.com/kubernetes-release/release/v0.11.0/bin/linux/amd64/kubelet
ExecStartPre=/usr/bin/chmod +x /opt/bin/kubelet
ExecStart=/opt/bin/kubelet \
--v=4 \
--address=10.132.218.185 \
--api_servers=http://10.132.218.185:8080 \
--port=10250 \
--hostname_override=104.236.200.4 \
--logtostderr=true
Restart=always
RestartSec=10
```

The log output is [here](https://paste.nothing.net.nz/e824fd). I tried resizing the replication controller down to 0 and back to 1 again and didn't see any effect.

**Comment by brendandburns** [comment] 2015-02-27 21:27
What is the IP address of your node?  You are setting --address=10.132.218.185
but setting --hostname_override=104.236.200.4

I would expect them to be equal.

Also, what are you specifying for the --machines=<...> param for
kube-controller-manager?

Or are you using the CoreOS tool that discovers machines from fleet?

--brendan

**Comment by heytrav** [comment] 2015-02-27 21:35
@brendandburns I think that was it actually! I changed the `--hostname_override` to `10.132.218.185` and that seemed to fix it.  

This solves my particular issue. Thanks a lot for the tip!

**Comment by dchen1107** [comment] 2015-02-27 22:30
I am closing the issue based on the last updates from @heytrav 

@derekwaynecarr please file an issue when you saw the error next time. Thanks!

**Closed by dchen1107** 2015-02-27 22:30 UTC
Labels: kind/support
