### ISSUE TITLE
Automatically restart etcd

### ISSUE THREAD

**Issue by brendandburns** [GoogleCloudPlatform/kubernetes#3852] opened 2015-01-28 00:45 UTC
We don't currently automatically restart etcd.  We should.

**Comment by dchen1107** [comment] 2015-01-28 01:40
Can we run etcd as a Pod without resource limit, so that we could benefit directly from 
1) RestartPolicy: Always
2) resource monitoring and logging

**Comment by davidopp** [comment] 2015-02-19 08:04
When I bring up an e2e cluster (i.e.  go run hack/e2e.go --up), without even running any of the e2e tests against it, it appears that monit is repeatedly killing and restarting etcd:

davidopp@e2e-test-davidopp-master:~$ more /var/log/monit.log
[UTC Feb 19 07:39:16] info     : monit: generated unique Monit id 1540c2008045e91d127485b47f17f66e and stored to '/var/lib/monit/id'
[UTC Feb 19 07:39:16] info     : Starting monit daemon
[UTC Feb 19 07:39:16] error    : State file '/var/lib/monit/state': Unable to read magic
[UTC Feb 19 07:39:16] info     : 'system_e2e-test-davidopp-master.c.striped-torus-760.internal' Monit started
[UTC Feb 19 07:39:18] info     : monit daemon with pid [5620] killed
[UTC Feb 19 07:39:18] info     : 'system_e2e-test-davidopp-master.c.striped-torus-760.internal' Monit stopped
[UTC Feb 19 07:39:18] info     : Starting monit daemon
[UTC Feb 19 07:39:18] info     : 'system_e2e-test-davidopp-master.c.striped-torus-760.internal' Monit started
[UTC Feb 19 07:39:18] error    : 'etcd' failed, cannot open a connection to INET[127.0.0.1:4001/v2/keys/] via TCP
[UTC Feb 19 07:39:18] info     : 'etcd' trying to restart
[UTC Feb 19 07:39:18] info     : 'etcd' stop: /etc/init.d/etcd
[UTC Feb 19 07:39:18] info     : 'etcd' start: /etc/init.d/etcd
[UTC Feb 19 07:41:18] error    : 'etcd' failed, cannot open a connection to INET[127.0.0.1:4001/v2/keys/] via TCP
[UTC Feb 19 07:41:18] info     : 'etcd' trying to restart
[UTC Feb 19 07:41:18] info     : 'etcd' stop: /etc/init.d/etcd
[UTC Feb 19 07:41:18] info     : 'etcd' start: /etc/init.d/etcd
[UTC Feb 19 07:43:18] error    : 'etcd' failed, cannot open a connection to INET[127.0.0.1:4001/v2/keys/] via TCP
[UTC Feb 19 07:43:18] info     : 'etcd' trying to restart
[UTC Feb 19 07:43:18] info     : 'etcd' stop: /etc/init.d/etcd
[UTC Feb 19 07:43:18] info     : 'etcd' start: /etc/init.d/etcd
[UTC Feb 19 07:45:18] error    : 'etcd' failed, cannot open a connection to INET[127.0.0.1:4001/v2/keys/] via TCP
[UTC Feb 19 07:45:18] info     : 'etcd' trying to restart
[UTC Feb 19 07:45:18] info     : 'etcd' stop: /etc/init.d/etcd
[UTC Feb 19 07:45:18] info     : 'etcd' start: /etc/init.d/etcd
[...]

I examined the etcd logs and there is nothing suspicious there. 

I suspect this may be the cause of some of the e2e test flakiness.

**Comment by gmarek-google** [comment] 2015-02-19 11:10
I think this particular problem is caused by firewall settings.
```
gmarek@kubernetes-master:/var/log$ sudo curl localhost:4001/v2/keys
curl: (7) Failed to connect to ::1: Network is unreachable
gmarek@kubernetes-master:/var/log$ sudo curl `hostname -i`:4001/v2/keys
{"action":"get","node":{"dir":true,"nodes":[{"key":"/registry","dir":true,"modifiedIndex":3,"createdIndex":3}],"m
odifiedIndex":3,"createdIndex":3}}
```

**Comment by davidopp** [comment] 2015-02-19 23:33
#4587 actually didn't fix the problem. Here's the monit.log:

[UTC Feb 19 23:22:25] info     : monit: generated unique Monit id fbbda12a42c24d5f59eaef6e63002ed2 and stored to '/var/lib/monit/id'
[UTC Feb 19 23:22:25] info     : Starting monit daemon
[UTC Feb 19 23:22:25] error    : State file '/var/lib/monit/state': Unable to read magic
[UTC Feb 19 23:22:25] info     : 'system_e2e-test-davidopp-master.c.striped-torus-760.internal' Monit started
[UTC Feb 19 23:22:26] info     : monit daemon with pid [5481] killed
[UTC Feb 19 23:22:26] info     : 'system_e2e-test-davidopp-master.c.striped-torus-760.internal' Monit stopped
[UTC Feb 19 23:22:27] info     : Starting monit daemon
[UTC Feb 19 23:22:27] info     : 'system_e2e-test-davidopp-master.c.striped-torus-760.internal' Monit started
[UTC Feb 19 23:22:32] error    : 'etcd' failed, cannot open a connection to INET[kubernetes-master:4001/v2/keys/] via TCP
[UTC Feb 19 23:22:32] info     : 'etcd' trying to restart
[UTC Feb 19 23:22:32] info     : 'etcd' stop: /etc/init.d/etcd
[UTC Feb 19 23:22:32] info     : 'etcd' start: /etc/init.d/etcd
[UTC Feb 19 23:24:37] error    : 'etcd' failed, cannot open a connection to INET[kubernetes-master:4001/v2/keys/] via TCP
[UTC Feb 19 23:24:37] info     : 'etcd' trying to restart
[UTC Feb 19 23:24:37] info     : 'etcd' stop: /etc/init.d/etcd
[UTC Feb 19 23:24:37] info     : 'etcd' start: /etc/init.d/etcd
[UTC Feb 19 23:26:43] error    : 'etcd' failed, cannot open a connection to INET[kubernetes-master:4001/v2/keys/] via TCP
[UTC Feb 19 23:26:43] info     : 'etcd' trying to restart
[UTC Feb 19 23:26:43] info     : 'etcd' stop: /etc/init.d/etcd
[UTC Feb 19 23:26:43] info     : 'etcd' start: /etc/init.d/etcd
[UTC Feb 19 23:28:48] error    : 'etcd' failed, cannot open a connection to INET[kubernetes-master:4001/v2/keys/] via TCP
[UTC Feb 19 23:28:48] info     : 'etcd' trying to restart
[UTC Feb 19 23:28:48] info     : 'etcd' stop: /etc/init.d/etcd
[UTC Feb 19 23:28:48] info     : 'etcd' start: /etc/init.d/etcd
[UTC Feb 19 23:30:53] error    : 'etcd' failed, cannot open a connection to INET[kubernetes-master:4001/v2/keys/] via TCP
[UTC Feb 19 23:30:53] info     : 'etcd' trying to restart
[UTC Feb 19 23:30:53] info     : 'etcd' stop: /etc/init.d/etcd
[UTC Feb 19 23:30:53] info     : 'etcd' start: /etc/init.d/etcd

**Comment by davidopp** [comment] 2015-02-19 23:34
The reason the fix didn't work is that it hard-codes the hostname as kubernetes-master but the hostname may actually be anything. For example, in e2e test the master hostname is e2e-test-${USER}-master

**Comment by davidopp** [comment] 2015-02-20 07:20
This is fixed by changing etcd to startup with  -bind-addr 0.0.0.0:4001

I'm sending a PR now.

**Comment by davidopp** [comment] 2015-02-20 07:21
(And thanks to @a-robinson for figuring out the problem was that etcd wasn't listening on the localhost address.)

**Closed** 2015-02-20 16:07 UTC
Labels: priority/P0
