### ISSUE TITLE
v1.0.0 known issues / FAQ accumulator

### ISSUE THREAD

**Issue by thockin** [GoogleCloudPlatform/kubernetes#10760] opened 2015-07-06 16:47 UTC
This issue is intended to accumulate known errata / issues / workarounds so we can produce a useful doc upon release.  If you have a known issue that is worth putting in our 1.0 release notes, please add a comment here of the form "NEW: ..." and write a paragraph explaining the issue and the workaround or repercussions or whatever.  The core team will accumulate these into a final doc.

**Comment by thockin** [comment] 2015-07-07 20:16
NEW: If multiple Pods use the same RBD volume in read-write mode, it is possible data on the RBD volume could get corrupted. This problem has been found in environments where both apiserver and etcd rebooted and Pod were redistributed.

A workaround is to ensure there is no other Ceph client uses the RBD volume before mapping RBD image in read-write mode. For example, rados -p poolname listwatchers image_name.rbd can list RBD clients that are mapping the image.

**Comment by dchen1107** [comment] 2015-07-10 19:53
#10659: exec probes as broken in v1 due to resource leakage caused by docker. 
#10868: docker load sometimes hang, which causes kube-apiserver cannot start. Restarting docker daemon should fix the issue.
#11027: by default allow-privileged is on for kubernetes. Document how to disable it through salt configuration.
#10891: due to master node is not registered to kube-apiserver, heapster doesn't collect stats from master node. The issue should fixed in v1.X release.
#10653: memory leakage in heapster and influxdb
# https://github.com/GoogleCloudPlatform/heapster/issues/399: Wrong node cpu/mem limit metrics from heapster

**Comment by thockin** [comment] 2015-07-10 20:50
Services that use port 10250 can not set type = LoadBalancer because of an issue in GCE firewalls.  This will be fixed in a future update

**Comment by dchen1107** [comment] 2015-07-17 17:20
#11435 addon services cannot be created / deleted through kubectl/API.

**Comment by saad-ali** [comment] 2015-07-20 19:43
GCE PD Issues:
* https://github.com/GoogleCloudPlatform/kubernetes/issues/11231#issuecomment-122049113 If a pod with a GCE PD is created and deleted in rapid sucession, it may fail to attach/mount correctly leaving PD data inaccessible (or corrputed in the worst case).
  * Suggested temporary work around: introduce a 1-2 minute delay between deleting and recreating a pod with a PD on the same node.
* https://github.com/GoogleCloudPlatform/kubernetes/issues/11321 Explicit errors while detaching GCE PD could prevent PD from ever being detached
* https://github.com/GoogleCloudPlatform/kubernetes/issues/11302 GCE PDs may sometimes fail to attach

Fix for the first two is in review: #11561
Last one is still under investigation.

**Closed** 2015-07-21 00:34 UTC
Labels: kind/documentation, priority/P1, team/any
