### ISSUE TITLE
RESTARTS count error when "get pods --watch"

### ISSUE THREAD

**Issue by jiangyaoguo** [GoogleCloudPlatform/kubernetes#12485] opened 2015-08-10 17:14 UTC
I use /hack/local-up-cluster to start a local k8s. And operate like below:
```console
./cluster/kubectl.sh run my-nginx --image=nginx --replicas=2 --port=80
CONTROLLER   CONTAINER(S)   IMAGE(S)   SELECTOR       REPLICAS   AGE
my-nginx     my-nginx       nginx      run=my-nginx   2          0s
```
```console
./cluster/kubectl.sh get pods --watch
```
Then I use "docker kill " to kill one container of rc for thrice. Here is result:
```console
./cluster/kubectl.sh get pods --watch
NAME             READY     STATUS    RESTARTS   AGE
my-nginx-kn1zy   0/1       Running   0          6s
my-nginx-msjcr   1/1       Running   0          6s
NAME             READY     STATUS    RESTARTS   AGE
my-nginx-kn1zy   1/1       Running   0          10s
my-nginx-kn1zy   0/1       Running   1         51s
my-nginx-kn1zy   1/1       Running   1         1m
my-nginx-kn1zy   0/1       Running   2         1m
my-nginx-kn1zy   1/1       Running   2         1m
my-nginx-kn1zy   0/1       Running   3         3m
my-nginx-kn1zy   1/1       Running   3         3m
my-nginx-kn1zy   1/1       Running   2         4m
``` 
The "RESTARTS" is supposed to be 3. But it will be changed to 2 at last . Is there reason which will cause RESTARTS reduce?

**Comment by yujuhong** [comment] 2015-08-10 18:13
Thanks for reporting the issue. There has been a regression of restart count recently. We are planning to fix this shortly.

Closing this as a duplicate of #11948

**Closed by yujuhong** 2015-08-10 18:13 UTC
