### ISSUE TITLE
Error post deployment in azure kubectl get minions Error: Get http://localhost:8080/api/v1beta3/minions: dial tcp 127.0.0.1:8080: connection refused

### ISSUE THREAD

**Issue by srakesh28** [GoogleCloudPlatform/kubernetes#9034] opened 2015-05-30 03:34 UTC
Hi,

I have tried this steps but it fails to get minions. 

core@kube-00 ~ $ kubectl get minions
Error: Get http://localhost:8080/api/v1beta3/minions: dial tcp 127.0.0.1:8080: connection refused

Deployment was successful without any errors and I can see the all nodes up and running in azure.

Please assist .. 
Thank you

**Comment by srakesh28** [comment] 2015-05-30 03:48
Error message posted : 
Waiting for cluster initialization.

  This will continually check to see if the API for kubernetes is reachable.
  This might loop forever if there was some uncaught error during start
  up.

...............................................................................................................................................................................................................................

Next step: kubectl run my-nginx --image=nginx --replicas=2 --port=80
Error: unknown command "run"
Run 'kubectl help' for usage.

**Comment by yaroska** [comment] 2015-06-01 00:37
I have the same problem.

**Comment by errordeveloper** [comment] 2015-06-01 15:03
Can someone close this please, it's a duplicate of #9036.

**Closed** 2015-06-02 17:52 UTC
Labels: kind/support

**Comment by srakesh28** [comment] 2015-06-02 17:56
Does this mean I can now download the latest version and re-try install on Azure ?

**Comment by errordeveloper** [comment] 2015-06-02 18:05
Sure, it should work if you pull from master and rerun the provisions
scripts.
