### ISSUE TITLE
Kubelet repeatedly logs "Cannot get host IP: cannot get node: node <name> not found"

### ISSUE THREAD

**Issue by roberthbailey** [GoogleCloudPlatform/kubernetes#8571] opened 2015-05-20 16:37 UTC
From https://groups.google.com/d/msg/google-containers/WPGJsSmGV6g/Ux5Q22veyEAJ

Hi there,

hope you can help me. Our kubelets post the following error multiple times per minute :

E0520 10:34:48.111760    1360 kubelet.go:1973] Cannot get host IP: host IP unknown; known addresses: []

E0520 10:34:58.108223    1360 kubelet.go:1973] Cannot get host IP: host IP unknown; known addresses: []

They are running within the AWS cloud and the hostnames of the machine are also specified within the /etc/hosts file. In effect i have no idea why the kublet is not able to get its host ip. By the way the api-server and kublets are behind firewalls(security groups), do i need to open some special ports? Nevertheless the communication between the different parts of kubernetes seems to work, very smooth. So what do i miss? Many thanks in advance.

Regards
Stefan

**Comment by roberthbailey** [comment] 2015-05-20 16:40
It looks like the error is trying to set the host ip for a pod: https://github.com/GoogleCloudPlatform/kubernetes/blob/master/pkg/kubelet/kubelet.go#L2095-L2100

**Comment by justinsb** [comment] 2015-05-20 18:53
Could this be this issue?

https://github.com/GoogleCloudPlatform/kubernetes/issues/7962#issuecomment-100415474

We seem to be sensitive to the DHCP option set used..

And oops ... apparently there is a patch, but blocked on me.  I will look at it.

**Comment by theiq** [comment] 2015-05-21 07:48
I am not sure, because we are using Kubernetes on AWS. Nevertheless it was not specified as cloud-provider

**Comment by theiq** [comment] 2015-05-21 09:28
I just checked the VPC and it seems to be set up correctly.

The DHCP options are set as follows:
domain-name = eu-central-1.compute.internal
domain-name-servers = AmazonProvidedDNS

The /etc/resolv.conf
nameserver 172.31.0.2
search eu-central-1.compute.internal

And a ping to the hostname als works:
PING ip-172-31-6-144 (172.31.6.144) 56(84) bytes of data.
64 bytes from ip-172-31-6-144 (172.31.6.144): icmp_seq=1 ttl=64 time=0.033 ms

**Comment by kelseyhightower** [comment] 2015-05-24 18:50
I have confirmed this is also an issue on VMware, which leads me to believe this might be affecting most platforms.

**Comment by manolitto** [comment] 2015-05-26 12:37
Can confirm this issue for current master on AWS eu-west-1:

DHCP options set:
domain-name = eu-west-1.compute.internal
domain-name-servers = AmazonProvidedDNS

/etc/resolv.conf:
nameserver 172.20.0.2
search eu-west-1.compute.internal

ping:
PING ip-172-20-1-9.eu-west-1.compute.internal (172.20.1.9) 56(84) bytes of data.
64 bytes from ip-172-20-1-9.eu-west-1.compute.internal (172.20.1.9): icmp_seq=1 ttl=64 time=0.020 ms

kubelet.log:
...
E0526 12:34:36.882276    1821 kubelet.go:1988] Cannot get host IP: cannot get node: node ip-172-20-1-9 not found
E0526 12:34:36.896213    1821 kubelet.go:1988] Cannot get host IP: cannot get node: node ip-172-20-1-9 not found
E0526 12:34:36.900087    1821 kubelet.go:1988] Cannot get host IP: cannot get node: node ip-172-20-1-9 not found
E0526 12:34:36.900797    1821 kubelet.go:1988] Cannot get host IP: cannot get node: node ip-172-20-1-9 not found
E0526 12:34:37.034118    1821 kubelet.go:1988] Cannot get host IP: cannot get node: node ip-172-20-1-9 not found
E0526 12:34:37.036233    1821 kubelet.go:1458] error getting node: node ip-172-20-1-9 not found
...

**Comment by edword** [comment] 2015-06-01 20:37
Not sure if it's from the same issue/regression, but we seem to be seeing something similar on GCE/GKE as well : 

/etc/resolv.conf:
domain c.gl.internal.
search c.gl.internal. 819891788074.google.internal. google.internal.
nameserver 169.254.169.254
nameserver 10.240.0.1     

ping:
PING k8s-gl-integration-master.c.gl.internal (10.240.221.250) 56(84) bytes of data.
64 bytes from k8s-gl-integration-master.c.gl.internal (10.240.221.250): icmp_req=1 ttl=64 time=0.
023 ms

kubelet.log:
...
E0601 20:35:36.338502    8745 kubelet.go:1767] Cannot get host IP: cannot get node: node k8s-gl-integration-master not found
E0601 20:35:36.343673    8745 kubelet.go:1767] Cannot get host IP: cannot get node: node k8s-gl-integration-master not found
E0601 20:35:36.344361    8745 kubelet.go:1767] Cannot get host IP: cannot get node: node k8s-gl-integration-master not found
E0601 20:35:36.353530    8745 kubelet.go:1767] Cannot get host IP: cannot get node: node k8s-gl-integration-master not found

**Comment by justinsb** [comment] 2015-06-04 01:24
I don't think this is an AWS issue.  We've had reports of it happening on VMWare & GCE also, and I've confirmed that personally on GCE.

Further, when I changed things so that the minion name _could_ be resolved (https://github.com/justinsb/kubernetes/commit/ebc69c290bfa40a84df605266010aba9a728df83) kubelet on the master then registered itself as a node and it started getting pod assignments.

I think I might need to unassign myself from this issue; I think there's some design issues here (how do we want to stop the master from registering as a node, presuming that we want to do that).

I'm also going to change the subject to not be AWS specific.

**Comment by justinsb** [comment] 2015-06-04 02:05
(Also marked this as v1-candidate, I believe that is the correct way to flag it as being something we should probably fix for v1)

**Comment by alex-mohr** [comment] 2015-06-09 23:32
Looks like something the kubelet team could more productively diagnose.  @dchen1107  ?

**Comment by alex-mohr** [comment] 2015-06-09 23:34
Note: the error seems to only be for the kubelet on the master node.  Are we launching it with an invalid flag?

**Comment by roberthbailey** [comment] 2015-06-10 17:00
@theiq @manolitto @edword - Can anyone confirm whether this is only seen on the master machine or if it is also seen on the node machines as well?

**Comment by theiq** [comment] 2015-06-10 17:10
it was seen especially on the nodes (non-masters). have to check the new version 0.19 for this error

**Comment by dchen1107** [comment] 2015-06-10 19:30
I raised the priority to P1 since ppl reports such error messages on non-master node. I suspect the problem is caused by misconfigured node, but still we need to understand it more and update the troubleshooting guide for this. On master node, we need to introduce a flag to stop register itself with cluster. 

@theiq which cloud provider is your cluster on? Also are you using --hostname_overrides to start your kubelet? 

I talked to @mikedanese, he will take a deep look at the issue. Thanks!

**Comment by theiq** [comment] 2015-06-11 09:48
I just checked the kubelet logs and it seems that the error is gone with the new 0.19.

Before we used Kubernetes on AWS. We tried both with and without  --hostname_overrides finally, with no difference at all.

**Comment by mikedanese** [comment] 2015-06-11 15:47
I've been reading through the code and I've tried to reproduce but have been unable to do so. If this happens again, please save the full kubelet logs (preferable at log level `--v=4`) and paste a link to them here. Also if it's possible to reproduce with any of the local cloud providers, please let me know the steps.

**Comment by justinsb** [comment] 2015-06-12 04:46
So I'm trying to get to the bottom of this on AWS.  I'm pretty sure the error happens because kubelet tries to get information about itself, and in order to do that is queries (cached) information from the API nodes collection.  See GetNode & GetHostIP in pkg/kubelet/kubelet.go.

I'm not clear whether the kubelet on the master is supposed to register itself as a node.  If not, I don't see how this error could not still be happening.  If the master is supposed to register, I don't see how we stop pods from being scheduled on to the master node.

I had the idea that maybe the master registers itself, but it is somehow hidden, but that just doesn't seem to be the case.

Any hints gratefully received!

**Comment by roberthbailey** [comment] 2015-06-12 05:00
On GCE I disabled the kubelet on the master from registering itself in the cluster (see https://github.com/GoogleCloudPlatform/kubernetes/blob/master/cluster/saltbase/salt/kubelet/default#L25-L28). I think it would be ok to allow it to register, assuming you wanted to be able to use it for running work in the cluster.

**Comment by justinsb** [comment] 2015-06-12 15:26
Thanks @roberthbailey - I had overlooked that change you made in salt!

By adding that to the branch I am working on I got past the problem I was working on.  (BTW, I really don't want normal pods on the master, not least because we don't have kube-proxy on the master!)

However, I do still see this issue, though only on the master. This is on GCE 0.18.2 (and on something close to head on AWS). On the master, I see this every 10 seconds (I'm ignoring any errors during bringup)...

```
E0612 15:12:34.717424    5862 kubelet.go:1535] error getting node: node kubernetes-master not found
E0612 15:12:34.755526    5862 kubelet.go:2109] Cannot get host IP: cannot get node: node kubernetes-master not found
E0612 15:12:34.757562    5862 kubelet.go:2109] Cannot get host IP: cannot get node: node kubernetes-master not found
E0612 15:12:34.761308    5862 kubelet.go:2109] Cannot get host IP: cannot get node: node kubernetes-master not found
E0612 15:12:34.766022    5862 kubelet.go:2109] Cannot get host IP: cannot get node: node kubernetes-master not found
```

This makes sense, because the master node is not registered, so any attempt at getting the node will fail.

The "Cannot get host IP" (line 2109) repeated 4 times is from generatePodStatus.  I have 4 pods running on master (etcd, kube-controller, kube-scheduler, kube-apiserver).  

The "error getting node" (line 1535) is from checkNodeSelectorMatching.

I think we have two options:

1) We can special-case around it; I _think_ none of the pods on the master have selectors, so we can check that first in checkNodeSelectorMatching and early-exit if there are no selectors.  generatePodStatus is harder, but we could check if client was nil and either insert an empty string or something like the no-cloud logic in setNodeStatus.  We may be able to simply check if client==nil and skip a lot of these updates, but I don't know the consequences.

2) Currently syncNodeStatus is a no-op if there is no client.  Instead, we could still construct and update the local node status, but we would just keep it locally and not post it when we had no client. Then GetNode and everything would still work, and we would have one code-path (except for whether we get the node from the API or a local variable).

My preference is for option 2 - there's a lot of logic in constructing the node status, and it feels very logical to let all that existing code just work.  But this late in the game, I can see that special-casing may be more appropriate.

**Comment by roberthbailey** [comment] 2015-06-12 15:57
It seems like that check should be skipped if the apiserver isn't passed to the kubelet. 

This looks like an error to anyone looking through the kubelet logs, but we want the kubelet to work in stand-alone mode too, and in stand-alone mode we will see this error for all statically configured pods (as we do on the master).

**Comment by roberthbailey** [comment] 2015-06-12 15:58
@dchen1107

**Comment by dchen1107** [comment] 2015-06-12 16:25
Sounds like we confirmed the problem only occurs on master node, not minions. I am lowering the priority back to P2 now since it is spam. But we should fix those misleading messages. @mikedanese has a pending fix for it.

**Comment by justinsb** [comment] 2015-06-12 23:26
Awesome - though I think the call from checkNodeSelectorMatching will still spam the logs.  We'll see once I get to my next rebased test run!

**Comment by mikedanese** [comment] 2015-06-12 23:31
I'm hoping that get's called much less often.

**Comment by mikedanese** [comment] 2015-06-12 23:32
Uh oh :( you may be right.

**Closed** 2015-06-16 22:59 UTC
Labels: priority/P2, team/node
