### ISSUE TITLE
NoDiskConflict() should not reject multiple read-only PD mounts

### ISSUE THREAD

**Issue by runningwild** [GoogleCloudPlatform/kubernetes#8478] opened 2015-05-19 01:53 UTC
Easy to reproduce.  My setup is a single pod (master) and a replication controller (slaves) that should put one pod on each minion.  The master schedules on one machine, N-1 slaves schedule on all other machines, and 1 slave is left in state Pending and the error 'NoDiskConflictNode' shows up on a kubectl describe.

**Comment by satnam6502** [comment] 2015-05-19 06:56
Can you prepare a PR or point us to a snapshot which we can repo to make sure we are on the same page as well as node? Thank you.

**Comment by satnam6502** [comment] 2015-05-19 06:56
And please put down that knife.

**Comment by runningwild** [comment] 2015-05-19 14:12
1. Make a disk named 'workspace' (or make the appropriate changes below)
2. Start a cluster with 3 minions.
3. Use the files listed below to do this...
```bash
  kubectl create master.json
  kubectl create slaves.json
```

master.json
```json
{
  "id": "master",
  "kind": "Pod",
  "apiVersion": "v1beta1",
  "labels": {
    "app": "master",
    "stats": "stats"
  },
  "desiredState": {
    "manifest": {
      "version": "v1beta1",
      "id": "master",
      "containers": [{
        "name": "master",
        "image": "kubernetes/pause",
        "imagePullPolicy": "PullAlways",
        "volumeMounts": [
          {
            "mountPath": "/workspace",
            "name": "workspace"
          }
        ]
      }],
      "volumes": [
        {
          "name": "workspace",
          "source": {
            "persistentDisk": {
                "pdName":   "workspace",
                "fsType":   "ext4",
                "readOnly": true
            }
          }
        }
      ]
    }
  }
}
```

slaves.json
```json
{
  "id": "slaves-controller",
  "kind": "ReplicationController",
  "apiVersion": "v1beta1",
  "desiredState": {
    "replicas": 3,
    "replicaSelector": {"name": "slaves"},
    "podTemplate": {
      "desiredState": {
        "manifest": {
          "version": "v1beta1",
          "id": "placerSlaveController",
          "containers": [{
            "name": "slave",
            "image": "kubernetes/pause",
            "imagePullPolicy": "PullAlways",
            "volumeMounts": [{
                "mountPath": "/data",
                "name": "workspace"
            }]
          }],
          "volumes": [{
            "name": "workspace",
            "source": {
              "persistentDisk": {
                  "pdName":   "workspace",
                  "fsType":   "ext4",
                  "readOnly": true
              }
            }
          }]
        }
      },
      "labels": {
        "name": "slaves"
      }
    }
  },
  "labels": {"name": "slaves"}
}
```

**Comment by vishh** [comment] 2015-05-19 21:23
What version of kubernetes are you running? Can you provide the output of `kubectl version`?
Can you also post the complete output of `kubectl describe` on your slave pods?

**Comment by runningwild** [comment] 2015-05-19 21:40
Versions:
```bash
$ kubectl version
Client Version: version.Info{Major:"0", Minor:"16", GitVersion:"v0.16.1", GitCommit:"b933dda5369043161fa7c7330dfcfbc4624d40e6", GitTreeState:"clean"}
Server Version: version.Info{Major:"0", Minor:"17", GitVersion:"v0.17.0", GitCommit:"82f8bdac06ddfacf493a9ed0fedc85f5ea62ebd5", GitTreeState:"clean"}
```

This slave is working properly:
```bash
$ kubectl describe pod slaves-controller-kyrck
W0519 21:36:18.377248   18600 request.go:289] field selector: v1beta1 - events - involvedObject.id - slaves-controller-kyrck: need to check if this is versioned correctly.
W0519 21:36:18.377480   18600 request.go:289] field selector: v1beta1 - events - involvedObject.namespace - default: need to check if this is versioned correctly.
W0519 21:36:18.377594   18600 request.go:289] field selector: v1beta1 - events - involvedObject.uid - d67d28c7-fe6e-11e4-bd80-42010af032d5: need to check if this is versioned correctly.
Name:				slaves-controller-kyrck
Image(s):			kubernetes/pause
Host:				kubernetes-minion-7e8m/107.178.213.192
Labels:				name=slaves
Status:				Running
Replication Controllers:	slaves-controller (3/3 replicas created)
Containers:
  slave:
    Image:		kubernetes/pause
    State:		Running
      Started:		Tue, 19 May 2015 21:34:49 +0000
    Ready:		True
    Restart Count:	0
Conditions:
  Type		Status
  Ready 	True
Events:
  FirstSeen				LastSeen			Count	From					SubobjectPath				Reason		Message
  Tue, 19 May 2015 21:34:32 +0000	Tue, 19 May 2015 21:34:32 +0000	1	{scheduler }									scheduled	Successfully assigned slaves-controller-kyrck to kubernetes-minion-7e8m
  Tue, 19 May 2015 21:34:42 +0000	Tue, 19 May 2015 21:34:42 +0000	1	{kubelet kubernetes-minion-7e8m}						failedMount	Unable to mount volumes for pod "slaves-controller-kyrck_default": Could not attach disk: Timeout after 10s
  Tue, 19 May 2015 21:34:43 +0000	Tue, 19 May 2015 21:34:43 +0000	1	{kubelet kubernetes-minion-7e8m}						failedSync	Error syncing pod, skipping: Could not attach disk: Timeout after 10s
  Tue, 19 May 2015 21:34:44 +0000	Tue, 19 May 2015 21:34:44 +0000	1	{kubelet kubernetes-minion-7e8m}	implicitly required container POD	created		Created with docker id caf39f4b736d20d26302f79416c5a6c9d97dd5c4b0bccc0a031507f30142429f
  Tue, 19 May 2015 21:34:44 +0000	Tue, 19 May 2015 21:34:44 +0000	1	{kubelet kubernetes-minion-7e8m}	implicitly required container POD	pulled		Successfully pulled image "gcr.io/google_containers/pause:0.8.0"
  Tue, 19 May 2015 21:34:44 +0000	Tue, 19 May 2015 21:34:44 +0000	1	{kubelet kubernetes-minion-7e8m}	implicitly required container POD	started		Started with docker id caf39f4b736d20d26302f79416c5a6c9d97dd5c4b0bccc0a031507f30142429f
  Tue, 19 May 2015 21:34:48 +0000	Tue, 19 May 2015 21:34:48 +0000	1	{kubelet kubernetes-minion-7e8m}	spec.containers{slave}			pulled		Successfully pulled image "kubernetes/pause"
  Tue, 19 May 2015 21:34:49 +0000	Tue, 19 May 2015 21:34:49 +0000	1	{kubelet kubernetes-minion-7e8m}	spec.containers{slave}			created		Created with docker id 39e5eef26189ab6437b3efeb8cfc47fc845483cf38cf8e3f8de5bcef6941fab0
  Tue, 19 May 2015 21:34:49 +0000	Tue, 19 May 2015 21:34:49 +0000	1	{kubelet kubernetes-minion-7e8m}	spec.containers{slave}			started		Started with docker id 39e5eef26189ab6437b3efeb8cfc47fc845483cf38cf8e3f8de5bcef6941fab0
```

This slave is not:
```bash
$ kubectl describe pod slaves-controller-ku9oc
W0519 21:37:55.237497   18648 request.go:289] field selector: v1beta1 - events - involvedObject.id - slaves-controller-ku9oc: need to check if this is versioned correctly.
W0519 21:37:55.237779   18648 request.go:289] field selector: v1beta1 - events - involvedObject.namespace - default: need to check if this is versioned correctly.
W0519 21:37:55.237945   18648 request.go:289] field selector: v1beta1 - events - involvedObject.uid - d67d9032-fe6e-11e4-bd80-42010af032d5: need to check if this is versioned correctly.
Name:				slaves-controller-ku9oc
Image(s):			kubernetes/pause
Host:				/
Labels:				name=slaves
Status:				Pending
Replication Controllers:	slaves-controller (3/3 replicas created)
Containers:
Events:
  FirstSeen				LastSeen			Count	From		SubobjectPath	Reason			Message
  Tue, 19 May 2015 21:34:32 +0000	Tue, 19 May 2015 21:34:32 +0000	1	{scheduler }			failedScheduling	Error scheduling: failed to find fit for pod: &{{ } {slaves-controller-ku9oc slaves-controller- default /api/v1beta3/namespaces/default/pods/slaves-controller-ku9oc d67d9032-fe6e-11e4-bd80-42010af032d5 427 2015-05-19 21:34:32 +0000 UTC <nil> map[name:slaves] map[kubernetes.io/created-by:{"kind":"SerializedReference","apiVersion":"v1beta3","reference":{"kind":"ReplicationController","namespace":"default","name":"slaves-controller","uid":"d67ae275-fe6e-11e4-bd80-42010af032d5","apiVersion":"v1beta3","resourceVersion":"424"}}]} {[{workspace {<nil> <nil> 0xc2082e0cf0 <nil> <nil> <nil> <nil> <nil> <nil> <nil>}}] [{slave kubernetes/pause [] []  [] [] {map[] map[]} [{workspace false /data}] <nil> <nil> <nil> /dev/termination-log Always 0xc208397ea0}] Always <nil> ClusterFirst map[]  false} {Pending []    []}}Node kubernetes-minion-7e8m: NoDiskConflictNode kubernetes-minion-w944: NoDiskConflictNode kubernetes-minion-shk4: NoDiskConflict
  Tue, 19 May 2015 21:34:33 +0000	Tue, 19 May 2015 21:34:33 +0000	1	{scheduler }			failedScheduling	Error scheduling: failed to find fit for pod: &{{ } {slaves-controller-ku9oc slaves-controller- default /api/v1beta3/namespaces/default/pods/slaves-controller-ku9oc d67d9032-fe6e-11e4-bd80-42010af032d5 427 2015-05-19 21:34:32 +0000 UTC <nil> map[name:slaves] map[kubernetes.io/created-by:{"kind":"SerializedReference","apiVersion":"v1beta3","reference":{"kind":"ReplicationController","namespace":"default","name":"slaves-controller","uid":"d67ae275-fe6e-11e4-bd80-42010af032d5","apiVersion":"v1beta3","resourceVersion":"424"}}]} {[{workspace {<nil> <nil> 0xc20824c270 <nil> <nil> <nil> <nil> <nil> <nil> <nil>}}] [{slave kubernetes/pause [] []  [] [] {map[] map[]} [{workspace false /data}] <nil> <nil> <nil> /dev/termination-log Always 0xc2083e3980}] Always <nil> ClusterFirst map[]  false} {Pending []    []}}Node kubernetes-minion-7e8m: NoDiskConflictNode kubernetes-minion-w944: NoDiskConflictNode kubernetes-minion-shk4: NoDiskConflict
  Tue, 19 May 2015 21:34:35 +0000	Tue, 19 May 2015 21:34:35 +0000	1	{scheduler }			failedScheduling	Error scheduling: failed to find fit for pod: &{{ } {slaves-controller-ku9oc slaves-controller- default /api/v1beta3/namespaces/default/pods/slaves-controller-ku9oc d67d9032-fe6e-11e4-bd80-42010af032d5 427 2015-05-19 21:34:32 +0000 UTC <nil> map[name:slaves] map[kubernetes.io/created-by:{"kind":"SerializedReference","apiVersion":"v1beta3","reference":{"kind":"ReplicationController","namespace":"default","name":"slaves-controller","uid":"d67ae275-fe6e-11e4-bd80-42010af032d5","apiVersion":"v1beta3","resourceVersion":"424"}}]} {[{workspace {<nil> <nil> 0xc20816db90 <nil> <nil> <nil> <nil> <nil> <nil> <nil>}}] [{slave kubernetes/pause [] []  [] [] {map[] map[]} [{workspace false /data}] <nil> <nil> <nil> /dev/termination-log Always 0xc208286620}] Always <nil> ClusterFirst map[]  false} {Pending []    []}}Node kubernetes-minion-shk4: NoDiskConflictNode kubernetes-minion-7e8m: NoDiskConflictNode kubernetes-minion-w944: NoDiskConflict
  Tue, 19 May 2015 21:34:39 +0000	Tue, 19 May 2015 21:34:39 +0000	1	{scheduler }			failedScheduling	Error scheduling: failed to find fit for pod: &{{ } {slaves-controller-ku9oc slaves-controller- default /api/v1beta3/namespaces/default/pods/slaves-controller-ku9oc d67d9032-fe6e-11e4-bd80-42010af032d5 427 2015-05-19 21:34:32 +0000 UTC <nil> map[name:slaves] map[kubernetes.io/created-by:{"kind":"SerializedReference","apiVersion":"v1beta3","reference":{"kind":"ReplicationController","namespace":"default","name":"slaves-controller","uid":"d67ae275-fe6e-11e4-bd80-42010af032d5","apiVersion":"v1beta3","resourceVersion":"424"}}]} {[{workspace {<nil> <nil> 0xc208277050 <nil> <nil> <nil> <nil> <nil> <nil> <nil>}}] [{slave kubernetes/pause [] []  [] [] {map[] map[]} [{workspace false /data}] <nil> <nil> <nil> /dev/termination-log Always 0xc208269060}] Always <nil> ClusterFirst map[]  false} {Pending []    []}}Node kubernetes-minion-7e8m: NoDiskConflictNode kubernetes-minion-w944: NoDiskConflictNode kubernetes-minion-shk4: NoDiskConflict
  Tue, 19 May 2015 21:34:47 +0000	Tue, 19 May 2015 21:34:47 +0000	1	{scheduler }			failedScheduling	Error scheduling: failed to find fit for pod: &{{ } {slaves-controller-ku9oc slaves-controller- default /api/v1beta3/namespaces/default/pods/slaves-controller-ku9oc d67d9032-fe6e-11e4-bd80-42010af032d5 427 2015-05-19 21:34:32 +0000 UTC <nil> map[name:slaves] map[kubernetes.io/created-by:{"kind":"SerializedReference","apiVersion":"v1beta3","reference":{"kind":"ReplicationController","namespace":"default","name":"slaves-controller","uid":"d67ae275-fe6e-11e4-bd80-42010af032d5","apiVersion":"v1beta3","resourceVersion":"424"}}]} {[{workspace {<nil> <nil> 0xc20823b110 <nil> <nil> <nil> <nil> <nil> <nil> <nil>}}] [{slave kubernetes/pause [] []  [] [] {map[] map[]} [{workspace false /data}] <nil> <nil> <nil> /dev/termination-log Always 0xc2081a2000}] Always <nil> ClusterFirst map[]  false} {Pending []    []}}Node kubernetes-minion-shk4: NoDiskConflictNode kubernetes-minion-7e8m: NoDiskConflictNode kubernetes-minion-w944: NoDiskConflict
  Tue, 19 May 2015 21:35:03 +0000	Tue, 19 May 2015 21:35:03 +0000	1	{scheduler }			failedScheduling	Error scheduling: failed to find fit for pod: &{{ } {slaves-controller-ku9oc slaves-controller- default /api/v1beta3/namespaces/default/pods/slaves-controller-ku9oc d67d9032-fe6e-11e4-bd80-42010af032d5 427 2015-05-19 21:34:32 +0000 UTC <nil> map[name:slaves] map[kubernetes.io/created-by:{"kind":"SerializedReference","apiVersion":"v1beta3","reference":{"kind":"ReplicationController","namespace":"default","name":"slaves-controller","uid":"d67ae275-fe6e-11e4-bd80-42010af032d5","apiVersion":"v1beta3","resourceVersion":"424"}}]} {[{workspace {<nil> <nil> 0xc2083fb7a0 <nil> <nil> <nil> <nil> <nil> <nil> <nil>}}] [{slave kubernetes/pause [] []  [] [] {map[] map[]} [{workspace false /data}] <nil> <nil> <nil> /dev/termination-log Always 0xc208301c20}] Always <nil> ClusterFirst map[]  false} {Pending []    []}}Node kubernetes-minion-7e8m: NoDiskConflictNode kubernetes-minion-w944: NoDiskConflictNode kubernetes-minion-shk4: NoDiskConflict
  Tue, 19 May 2015 21:35:35 +0000	Tue, 19 May 2015 21:35:35 +0000	1	{scheduler }			failedScheduling	Error scheduling: failed to find fit for pod: &{{ } {slaves-controller-ku9oc slaves-controller- default /api/v1beta3/namespaces/default/pods/slaves-controller-ku9oc d67d9032-fe6e-11e4-bd80-42010af032d5 427 2015-05-19 21:34:32 +0000 UTC <nil> map[name:slaves] map[kubernetes.io/created-by:{"kind":"SerializedReference","apiVersion":"v1beta3","reference":{"kind":"ReplicationController","namespace":"default","name":"slaves-controller","uid":"d67ae275-fe6e-11e4-bd80-42010af032d5","apiVersion":"v1beta3","resourceVersion":"424"}}]} {[{workspace {<nil> <nil> 0xc20845d0e0 <nil> <nil> <nil> <nil> <nil> <nil> <nil>}}] [{slave kubernetes/pause [] []  [] [] {map[] map[]} [{workspace false /data}] <nil> <nil> <nil> /dev/termination-log Always 0xc208457a80}] Always <nil> ClusterFirst map[]  false} {Pending []    []}}Node kubernetes-minion-shk4: NoDiskConflictNode kubernetes-minion-7e8m: NoDiskConflictNode kubernetes-minion-w944: NoDiskConflict
  Tue, 19 May 2015 21:36:35 +0000	Tue, 19 May 2015 21:36:35 +0000	1	{scheduler }			failedScheduling	Error scheduling: failed to find fit for pod: &{{ } {slaves-controller-ku9oc slaves-controller- default /api/v1beta3/namespaces/default/pods/slaves-controller-ku9oc d67d9032-fe6e-11e4-bd80-42010af032d5 427 2015-05-19 21:34:32 +0000 UTC <nil> map[name:slaves] map[kubernetes.io/created-by:{"kind":"SerializedReference","apiVersion":"v1beta3","reference":{"kind":"ReplicationController","namespace":"default","name":"slaves-controller","uid":"d67ae275-fe6e-11e4-bd80-42010af032d5","apiVersion":"v1beta3","resourceVersion":"424"}}]} {[{workspace {<nil> <nil> 0xc2083721e0 <nil> <nil> <nil> <nil> <nil> <nil> <nil>}}] [{slave kubernetes/pause [] []  [] [] {map[] map[]} [{workspace false /data}] <nil> <nil> <nil> /dev/termination-log Always 0xc2083968e0}] Always <nil> ClusterFirst map[]  false} {Pending []    []}}Node kubernetes-minion-w944: NoDiskConflictNode kubernetes-minion-shk4: NoDiskConflictNode kubernetes-minion-7e8m: NoDiskConflict
  Tue, 19 May 2015 21:36:36 +0000	Tue, 19 May 2015 21:36:36 +0000	1	{scheduler }			failedScheduling	Error scheduling: failed to find fit for pod: &{{ } {slaves-controller-ku9oc slaves-controller- default /api/v1beta3/namespaces/default/pods/slaves-controller-ku9oc d67d9032-fe6e-11e4-bd80-42010af032d5 427 2015-05-19 21:34:32 +0000 UTC <nil> map[name:slaves] map[kubernetes.io/created-by:{"kind":"SerializedReference","apiVersion":"v1beta3","reference":{"kind":"ReplicationController","namespace":"default","name":"slaves-controller","uid":"d67ae275-fe6e-11e4-bd80-42010af032d5","apiVersion":"v1beta3","resourceVersion":"424"}}]} {[{workspace {<nil> <nil> 0xc208258690 <nil> <nil> <nil> <nil> <nil> <nil> <nil>}}] [{slave kubernetes/pause [] []  [] [] {map[] map[]} [{workspace false /data}] <nil> <nil> <nil> /dev/termination-log Always 0xc20829a580}] Always <nil> ClusterFirst map[]  false} {Pending []    []}}Node kubernetes-minion-7e8m: NoDiskConflictNode kubernetes-minion-w944: NoDiskConflictNode kubernetes-minion-shk4: NoDiskConflict
  Tue, 19 May 2015 21:36:38 +0000	Tue, 19 May 2015 21:36:38 +0000	1	{scheduler }			failedScheduling	Error scheduling: failed to find fit for pod: &{{ } {slaves-controller-ku9oc slaves-controller- default /api/v1beta3/namespaces/default/pods/slaves-controller-ku9oc d67d9032-fe6e-11e4-bd80-42010af032d5 427 2015-05-19 21:34:32 +0000 UTC <nil> map[name:slaves] map[kubernetes.io/created-by:{"kind":"SerializedReference","apiVersion":"v1beta3","reference":{"kind":"ReplicationController","namespace":"default","name":"slaves-controller","uid":"d67ae275-fe6e-11e4-bd80-42010af032d5","apiVersion":"v1beta3","resourceVersion":"424"}}]} {[{workspace {<nil> <nil> 0xc2083d8ab0 <nil> <nil> <nil> <nil> <nil> <nil> <nil>}}] [{slave kubernetes/pause [] []  [] [] {map[] map[]} [{workspace false /data}] <nil> <nil> <nil> /dev/termination-log Always 0xc208426120}] Always <nil> ClusterFirst map[]  false} {Pending []    []}}Node kubernetes-minion-w944: NoDiskConflictNode kubernetes-minion-shk4: NoDiskConflictNode kubernetes-minion-7e8m: NoDiskConflict
  Tue, 19 May 2015 21:36:42 +0000	Tue, 19 May 2015 21:36:42 +0000	1	{scheduler }			failedScheduling	Error scheduling: failed to find fit for pod: &{{ } {slaves-controller-ku9oc slaves-controller- default /api/v1beta3/namespaces/default/pods/slaves-controller-ku9oc d67d9032-fe6e-11e4-bd80-42010af032d5 427 2015-05-19 21:34:32 +0000 UTC <nil> map[name:slaves] map[kubernetes.io/created-by:{"kind":"SerializedReference","apiVersion":"v1beta3","reference":{"kind":"ReplicationController","namespace":"default","name":"slaves-controller","uid":"d67ae275-fe6e-11e4-bd80-42010af032d5","apiVersion":"v1beta3","resourceVersion":"424"}}]} {[{workspace {<nil> <nil> 0xc2082e0300 <nil> <nil> <nil> <nil> <nil> <nil> <nil>}}] [{slave kubernetes/pause [] []  [] [] {map[] map[]} [{workspace false /data}] <nil> <nil> <nil> /dev/termination-log Always 0xc2082e2c60}] Always <nil> ClusterFirst map[]  false} {Pending []    []}}Node kubernetes-minion-7e8m: NoDiskConflictNode kubernetes-minion-w944: NoDiskConflictNode kubernetes-minion-shk4: NoDiskConflict
  Tue, 19 May 2015 21:36:50 +0000	Tue, 19 May 2015 21:36:50 +0000	1	{scheduler }			failedScheduling	Error scheduling: failed to find fit for pod: &{{ } {slaves-controller-ku9oc slaves-controller- default /api/v1beta3/namespaces/default/pods/slaves-controller-ku9oc d67d9032-fe6e-11e4-bd80-42010af032d5 427 2015-05-19 21:34:32 +0000 UTC <nil> map[name:slaves] map[kubernetes.io/created-by:{"kind":"SerializedReference","apiVersion":"v1beta3","reference":{"kind":"ReplicationController","namespace":"default","name":"slaves-controller","uid":"d67ae275-fe6e-11e4-bd80-42010af032d5","apiVersion":"v1beta3","resourceVersion":"424"}}]} {[{workspace {<nil> <nil> 0xc2083df7a0 <nil> <nil> <nil> <nil> <nil> <nil> <nil>}}] [{slave kubernetes/pause [] []  [] [] {map[] map[]} [{workspace false /data}] <nil> <nil> <nil> /dev/termination-log Always 0xc2083e29c0}] Always <nil> ClusterFirst map[]  false} {Pending []    []}}Node kubernetes-minion-7e8m: NoDiskConflictNode kubernetes-minion-w944: NoDiskConflictNode kubernetes-minion-shk4: NoDiskConflict
  Tue, 19 May 2015 21:37:06 +0000	Tue, 19 May 2015 21:37:06 +0000	1	{scheduler }			failedScheduling	Error scheduling: failed to find fit for pod: &{{ } {slaves-controller-ku9oc slaves-controller- default /api/v1beta3/namespaces/default/pods/slaves-controller-ku9oc d67d9032-fe6e-11e4-bd80-42010af032d5 427 2015-05-19 21:34:32 +0000 UTC <nil> map[name:slaves] map[kubernetes.io/created-by:{"kind":"SerializedReference","apiVersion":"v1beta3","reference":{"kind":"ReplicationController","namespace":"default","name":"slaves-controller","uid":"d67ae275-fe6e-11e4-bd80-42010af032d5","apiVersion":"v1beta3","resourceVersion":"424"}}]} {[{workspace {<nil> <nil> 0xc208404360 <nil> <nil> <nil> <nil> <nil> <nil> <nil>}}] [{slave kubernetes/pause [] []  [] [] {map[] map[]} [{workspace false /data}] <nil> <nil> <nil> /dev/termination-log Always 0xc208407220}] Always <nil> ClusterFirst map[]  false} {Pending []    []}}Node kubernetes-minion-7e8m: NoDiskConflictNode kubernetes-minion-w944: NoDiskConflictNode kubernetes-minion-shk4: NoDiskConflict
  Tue, 19 May 2015 21:37:38 +0000	Tue, 19 May 2015 21:37:38 +0000	1	{scheduler }			failedScheduling	Error scheduling: failed to find fit for pod: &{{ } {slaves-controller-ku9oc slaves-controller- default /api/v1beta3/namespaces/default/pods/slaves-controller-ku9oc d67d9032-fe6e-11e4-bd80-42010af032d5 427 2015-05-19 21:34:32 +0000 UTC <nil> map[name:slaves] map[kubernetes.io/created-by:{"kind":"SerializedReference","apiVersion":"v1beta3","reference":{"kind":"ReplicationController","namespace":"default","name":"slaves-controller","uid":"d67ae275-fe6e-11e4-bd80-42010af032d5","apiVersion":"v1beta3","resourceVersion":"424"}}]} {[{workspace {<nil> <nil> 0xc208464870 <nil> <nil> <nil> <nil> <nil> <nil> <nil>}}] [{slave kubernetes/pause [] []  [] [] {map[] map[]} [{workspace false /data}] <nil> <nil> <nil> /dev/termination-log Always 0xc2084688a0}] Always <nil> ClusterFirst map[]  false} {Pending []    []}}Node kubernetes-minion-7e8m: NoDiskConflictNode kubernetes-minion-w944: NoDiskConflictNode kubernetes-minion-shk4: NoDiskConflict
```

**Comment by thockin** [comment] 2015-05-19 22:10
Can't reproduce.

I just ran this pod twice and both instances are running and can find the
PD mounted.  Cna you try running this (obvious adjust the pdName and the
host.

```
apiVersion: v1beta3
kind: Pod
metadata:
  generateName: thtest-
  labels:
      name: thtest
  namespace: default
spec:
  containers:
  - command:
    - "sleep"
    - "1000"
    image: busybox
    name: sleep
    volumeMounts:
    - mountPath: /pd
      name: pd
  host: kubernetes-minion-jrlj
  volumes:
  - name: pd
    gcePersistentDisk:
        pdName: testssd
        fsType: ext4
        readOnly: true

```

**Comment by runningwild** [comment] 2015-05-19 22:20
Yes, that works fine.  So perhaps this is specific to replication controllers?

**Comment by thockin** [comment] 2015-05-19 22:22
I'll try that.

**Comment by thockin** [comment] 2015-05-19 22:35
I still made it work.

apiVersion: v1beta3
kind: ReplicationController
metadata:
  labels:
    name: thtest
  name: thtest
  namespace: default
spec:
  replicas: 3
  selector:
    name: thtest
  template:
    metadata:
      generateName: thtest-
      labels:
          name: thtest
      namespace: default
    spec:
      containers:
      - command:
        - "sleep"
        - "1000"
        image: busybox
        name: sleep
        volumeMounts:
        - mountPath: /pd
          name: pd
      host: kubernetes-minion-jrlj
      volumes:
      - name: pd
        gcePersistentDisk:
            pdName: testssd
            fsType: ext4
            readOnly: true

**Comment by runningwild** [comment] 2015-05-19 22:58
Works for me too.  But this doesn't:

1. Take the first file you showed (after piping it through ```sed s/thtest/foobar/g``` and call it master.yaml.
2. Take the second file you showed, remove the host line, and call it slave.yaml.
3. ```kubectl create -f master.yaml```
4. ```kubectl create -f slave.yaml```

Summary: A replication controller won't choose a machine to run on if another pod has already mounted the disk it needs, unless it is told specifically what machine to use.
That doesn't seem like a clean summary, but that's what I'm seeing.

**Comment by thockin** [comment] 2015-05-20 00:33
Ahh, maybe it's the scheduling part that we're dodging by manually assigning a host?

@davidopp

**Comment by davidopp** [comment] 2015-05-20 00:41
I can take a look. I'm not aware of a scheduling rule that prevents pods that mount the same PD from running on the same node, yet that seems like the only explanation based on what you guys observed.

**Comment by davidopp** [comment] 2015-05-31 20:24
Very sorry for the delay. There is in fact a scheduling rule that explains the behavior you're seeing. See the function NoDiskConflict here: https://github.com/GoogleCloudPlatform/kubernetes/blob/master/plugin/pkg/scheduler/algorithm/predicates/predicates.go#L84

The comment is:
```
// NoDiskConflict evaluates if a pod can fit due to the volumes it requests, and those that
// are already mounted. Some times of volumes are mounted onto node machines.  For now, these mounts
// are exclusive so if there is already a volume mounted on that node, another pod can't schedule
// there. This is GCE specific for now.
```

I'm going to close this issue since it is working as intended. Please reopen if you have additional questions.

**Comment by thockin** [comment] 2015-05-31 20:30
Can we re-purpose this bug to mean "this should work for read-only PD
mounts" ?

On Sun, May 31, 2015 at 1:25 PM, David Oppenheimer <notifications@github.com

**Comment by davidopp** [comment] 2015-05-31 20:39
Yeah, that sounds reasonable. I'll rename.

**Comment by runningwild** [comment] 2015-06-01 12:19
Made PR #9056 which prevents a disk conflict if both requested volumes are in read only mode.

As a side note: I comically now have the problem that slaves sometimes schedule on the same machine, is there a recommended way to avoid that?

**Comment by davidopp** [comment] 2015-06-06 22:36
Right now the only way to avoid having two pods schedule onto the same machine is to have them each request enough resources such that they won't fit on the same machine. See #3945 for more details.

Thanks for your PR!

**Closed by davidopp** 2015-06-06 22:36 UTC
Labels: area/scheduling, kind/bug, priority/P1, team/master
