### ISSUE TITLE
New GCE nodes are missing node-ip-range metadata

### ISSUE THREAD

**Issue by mwuertinger** [GoogleCloudPlatform/kubernetes#6251] opened 2015-03-31 22:22 UTC
# Summary
Adding new node to a k8s cluster on Google Compute Engine (GCE) by modifying the associated instance group does not work. The newly created instances never enter the Ready state.

# How to reproduce?
- Download and extract latest ``kubernetes.tar.gz`` release (0.14.0) from Github.
- ``MINION_DISK_SIZE=100GB cluster/kube-up.sh``
- Wait till cluster becomes fully available.
- ``cluster/kubectl.sh get minions``
```
    NAME                                          LABELS    STATUS
    kubernetes-minion-daa5.c.<project>.internal   <none>    Ready
    kubernetes-minion-e5h9.c.<project>.internal   <none>    Ready
    kubernetes-minion-rzky.c.<project>.internal   <none>    Ready
    kubernetes-minion-sbcr.c.<project>.internal   <none>    Ready
```
- Go to the developer console [1] and adjust the instance group size from 4 to 10 instances (I found no way to do this using ``gcloud``).
- Wait a while
- ``cluster/kubectl.sh get minions``
```
NAME                                          LABELS    STATUS
kubernetes-minion-6g8n.c.<project>.internal   <none>    NotReady
kubernetes-minion-c6g0.c.<project>.internal   <none>    NotReady
kubernetes-minion-daa5.c.<project>.internal   <none>    Ready
kubernetes-minion-e5h9.c.<project>.internal   <none>    Ready
kubernetes-minion-er8q.c.<project>.internal   <none>    NotReady
kubernetes-minion-iuer.c.<project>.internal   <none>    NotReady
kubernetes-minion-j0ht.c.<project>.internal   <none>    NotReady
kubernetes-minion-rzky.c.<project>.internal   <none>    Ready
kubernetes-minion-sbcr.c.<project>.internal   <none>    Ready
kubernetes-minion-zvt7.c.<project>.internal   <none>    NotReady
```

# Workaround
The minions can be saved by adding the ``node-ip-range`` metadata field to each of them using the following command:
```bash
  gcloud compute instances add-metadata \
    --zone $ZONE \
    $MINION_INSTANCE_NAME \
    --metadata node-ip-range=10.244.0.0/24
```

# Background information
- The node template which is created by the ``create-node-template()`` function in ``cluster/gce/util.sh`` does not contain the ``node-ip-range`` metadata field.
- The ``node-ip-range`` metadata field is added for all minions in a loop in the ``kube-up()`` function:
```bash
  # Create the routes and set IP ranges to instance metadata, 5 instances at a time.
  for (( i=0; i<${#MINION_NAMES[@]}; i++)); do
    create-route "${MINION_NAMES[$i]}" "${MINION_IP_RANGES[$i]}" &
    add-instance-metadata "${MINION_NAMES[$i]}" "node-ip-range=${MINION_IP_RANGES[$i]}" &

    if [ $i -ne 0 ] && [ $((i%5)) -eq 0 ]; then
      echo Waiting for a batch of routes at $i...
      wait-for-jobs
    fi

  done
```
- The variable ``MINION_IP_RANGES`` is determined in ``cluster/gce/config-default.sh``:
```bash
subnets=()

for ((node_num=0; node_num<node_count; node_num++)); do
  subnets+=("$next_node"/"${node_subnet_size}")
  next_node=$(increment_ipv4 $next_node $node_subnet_count)
done

CLUSTER_IP_RANGE="10.244.0.0/16"
MINION_IP_RANGES=($(eval echo "${subnets[@]}"))
```

[1] `https://console.developers.google.com/project/<project>/compute/instanceGroups/list`

**Comment by zmerlynn** [comment] 2015-03-31 23:11
I'm sorry you ran into this. This is a known issue that @	tkulczynski is working on fixing in #5246 (and a dupe of #4610 and probably others), but it's going to be a little while before that lands. Thanks for the bug report, though - it was awesome to see such detail. We definitely want this use case to work and are working hard to get it in.

cc @cjcullen

**Closed by zmerlynn** 2015-03-31 23:11 UTC

**Comment by mwuertinger** [comment] 2015-03-31 23:20
I created a pull request with a dirty hack that solves the problem for me. Although seeing little chance of this getting merged it might help other people running into the same issue until #5246 is fixed.

https://github.com/GoogleCloudPlatform/kubernetes/pull/6254
