### ISSUE TITLE
500 error when trying to delete a namespace

### ISSUE THREAD

**Issue by abonas** [GoogleCloudPlatform/kubernetes#6462] opened 2015-04-06 13:01 UTC
Created the following namespace:
https://github.com/GoogleCloudPlatform/kubernetes/blob/master/examples/kubernetes-namespaces/v1beta3/namespace-prod.json

While there were no entities associated with it,
tried to delete it by accessing:
http://KubeMasterIP:8080/api/v1beta3/namespaces/production
with DELETE

Got the following 500 err:
{
  "kind": "Status",
  "apiVersion": "v1beta3",
  "metadata": {},
  "status": "Failure",
  "message": "converting  to : type names don't match (Namespace, DeleteOptions), and no conversion 'func (v1beta3.Namespace, api.DeleteOptions) error' registered.",
  "code": 500
}

cc @derekwaynecarr

**Comment by derekwaynecarr** [comment] 2015-04-06 14:31
that's a new one to me... are you seeing this failure currently on HEAD?

**Comment by abonas** [comment] 2015-04-06 15:14
@derekwaynecarr
I have the code up to date correct to 3 days ago.
(set on  b9babb56b0962a22a93bcbaa02729f2da67dbf11)

**Comment by derekwaynecarr** [comment] 2015-04-08 21:17
I just tried to reproduce this on master with following steps:

```shell
$ cluster/kubectl.sh create -f examples/kubernetes-namespaces/namespace-dev.json
$ curl -i -X DELETE -k -u vagrant:vagrant https://10.245.1.2/api/v1beta3/namespaces/development
HTTP/1.1 200 OK
Server: nginx/1.4.7
Date: Wed, 08 Apr 2015 21:15:49 GMT
Content-Type: application/json
Content-Length: 494
Connection: keep-alive

{
  "kind": "Namespace",
  "apiVersion": "v1beta3",
  "metadata": {
    "name": "development",
    "selfLink": "/api/v1beta3/namespaces/development",
    "uid": "3201a85f-de34-11e4-8201-0800279696e1",
    "resourceVersion": "27586",
    "creationTimestamp": "2015-04-08T21:14:08Z",
    "deletionTimestamp": "2015-04-08T21:15:49Z",
    "labels": {
      "name": "development"
    }
  },
  "spec": {
    "finalizers": [
      "kubernetes"
    ]
  },
  "status": {
    "phase": "Terminating"
  }
}
$ cluster/kubectl.sh get namespaces
NAME      LABELS    STATUS
default   <none>    Active
development   name=development   Terminating
```

After waiting for namespace to terminate, it is then removed.

Closing this as I cannot reproduce.

**Closed by derekwaynecarr** 2015-04-08 21:17 UTC
Labels: kind/bug, priority/P1, team/master
