### ISSUE TITLE
GKE: Hard rebooting nodes does not work

### ISSUE THREAD

**Issue by chaten** [GoogleCloudPlatform/kubernetes#6930] opened 2015-04-16 20:05 UTC
All of our nodes in GKE were pegged at 100% cpu and could not be ssh'd into, so I was forced to reboot them all from the console. When starting up, it seems google-startup-script is run after salt-minion has started. The script then fails with
```
Apr 16 19:45:00 k8s-dev1-c-blue-node-1 startupscript: == Installing salt-common_2014.1.13+ds-1~bpo70+1_all.deb, ignore dependency complaints (will fix later) ==
Apr 16 19:45:00 k8s-dev1-c-blue-node-1 startupscript: (Reading database ... 40258 files and directories currently installed.)
Apr 16 19:45:00 k8s-dev1-c-blue-node-1 startupscript: Preparing to replace salt-common 2014.1.13+ds-1~bpo70+1 (using salt-common_2014.1.13+ds-1~bpo70+1_all.deb) ...
Apr 16 19:45:00 k8s-dev1-c-blue-node-1 startupscript: Unpacking replacement salt-common ...
Apr 16 19:45:01 k8s-dev1-c-blue-node-1 startupscript: Setting up salt-common (2014.1.13+ds-1~bpo70+1) ...
Apr 16 19:45:01 k8s-dev1-c-blue-node-1 startupscript: Processing triggers for man-db ...
Apr 16 19:45:02 k8s-dev1-c-blue-node-1 startupscript: == Installing salt-minion_2014.1.13+ds-1~bpo70+1_all.deb, ignore dependency complaints (will fix later) ==
Apr 16 19:45:02 k8s-dev1-c-blue-node-1 startupscript: (Reading database ... 40258 files and directories currently installed.)
Apr 16 19:45:02 k8s-dev1-c-blue-node-1 startupscript: Preparing to replace salt-minion 2014.1.13+ds-1~bpo70+1 (using salt-minion_2014.1.13+ds-1~bpo70+1_all.deb) ...
Apr 16 19:45:02 k8s-dev1-c-blue-node-1 startupscript: Salt shall not start.
Apr 16 19:45:02 k8s-dev1-c-blue-node-1 startupscript: invoke-rc.d: policy-rc.d denied execution of stop.
Apr 16 19:45:02 k8s-dev1-c-blue-node-1 startupscript: Unpacking replacement salt-minion ...
Apr 16 19:45:02 k8s-dev1-c-blue-node-1 startupscript: Setting up salt-minion (2014.1.13+ds-1~bpo70+1) ...
Apr 16 19:45:02 k8s-dev1-c-blue-node-1 startupscript: Salt shall not start.
Apr 16 19:45:02 k8s-dev1-c-blue-node-1 startupscript: invoke-rc.d: policy-rc.d denied execution of start.
Apr 16 19:45:02 k8s-dev1-c-blue-node-1 startupscript: Processing triggers for man-db ...
Apr 16 19:45:02 k8s-dev1-c-blue-node-1 startupscript: == Installing unmet dependencies ==
Apr 16 19:45:02 k8s-dev1-c-blue-node-1 startupscript: Reading package lists...
Apr 16 19:45:03 k8s-dev1-c-blue-node-1 startupscript: Building dependency tree...
Apr 16 19:45:03 k8s-dev1-c-blue-node-1 startupscript: Reading state information...
Apr 16 19:45:03 k8s-dev1-c-blue-node-1 startupscript: 0 upgraded, 0 newly installed, 0 to remove and 4 not upgraded.
Apr 16 19:45:03 k8s-dev1-c-blue-node-1 startupscript: == Finished installing Salt ==
Apr 16 19:45:03 k8s-dev1-c-blue-node-1 startupscript: salt-minion started in defiance of runlevel policy, aborting startup.
Apr 16 19:45:03 k8s-dev1-c-blue-node-1 startupscript: Finished running startup script /var/run/google.startup.script
```
 The only way to recover these hosts is to do
```sh
sudo service salt-minion stop
sudo service google-startup-scripts start
```
on each host.

**Comment by zmerlynn** [comment] 2015-04-16 22:23
I'm sorry you ran into this. It's a dupe of #5666.

**Comment by zmerlynn** [comment] 2015-04-16 22:24
Do you know what caused your original issue?

**Comment by zmerlynn** [comment] 2015-04-16 22:52
I'm closing this in favor of the original, bumping the original priority and working on it.

**Closed by zmerlynn** 2015-04-16 22:52 UTC
Labels: kind/bug, priority/P1, team/cluster-lifecycle

**Comment by chaten** [comment] 2015-04-16 23:10
Not at the moment. Thankfully, we have a cluster that hasn't died yet, but has a 78 load avg on our n1.standard.4. Containers are getting killed very often, but that looks like an issue w/our liveness probe.

Docker & Kubelet are taking up the majority of the CPU
```
$ top
082 root      20   0  448m 259m  15m S  98.7  1.7  23:15.69 kubelet
4450 root      20   0 7186m 269m  11m S  68.0  1.8   1235:07 docker   
```

There are 68 veth interfaces at the moment on that node.
CAdvisor has been killed 4 times due to OOM. It is possible we have it oversubscribed, but currently there is 7GB free on that node.

and this is repeated in the logs for kubelet
```
W0416 22:46:42.939702    8082 docker.go:767] found a container with the "k8s" prefix, but too few fields (5): "k8s_POD.5426ef83_cadvisor-agent.file-6bb810db-k8s-qa1-c-blue-node-1.file_d3de30998479ba8b551557ea9bc3b064_4fb46b5e"
```
