### ISSUE TITLE
0.11 pods state unknown then minion unavailable

### ISSUE THREAD

**Issue by rreinurm** [GoogleCloudPlatform/kubernetes#4829] opened 2015-02-25 23:20 UTC
I had managed produce the issue with GCE Container Engine and also had same issue then deployed Kubernetes cluster using provided script. In case one minion is down (in my tests I stopped the vm) then previously deployed containers are not rescheduled to other minions and state of container is "unknown". 
In case pod with unknown state is deleted manually, then pod is scheduled to be deployed on other available minion.  

If the minion was started, then all pods with unknown state were started on that minion as well.
In my test cluster I tried to set up redundancy for redis-master service and tried to see if self healing works then vm should not be available.

**Comment by ddysher** [comment] 2015-02-26 00:47
Thanks for reporting.  How did you stop the vm, just shutting it down?  Have you deleted it explicitly using kubectl delete?

nodecontroller will delete the pods in the node after 5min.  There might be some problem deleting the pods.

**Comment by rreinurm** [comment] 2015-02-26 08:00
Yes, I shut it down using stop functionality from gce command line or from web console. After 30 minutes the pod's state was still unknown on the same host. 

For deletion I have used kubectl delete then I deployed my own kubernetes master or then I used google gce preview then:
 gcloud preview container pods delete <pod name>

**Comment by pires** [comment] 2015-02-26 08:55
I can reproduce with Vagrant VMs.

**Comment by ddysher** [comment] 2015-02-26 16:20
Looks like a namespace issue #4832

Can you verify it works for you?  The stopped node will be detected immediately, but pods on it will only be deleted after 5min.  You can control the time using flag pod_eviction_timeout.

Deleting the node through kubectl delete will leave the pods unknown (if you don't stop the node first).  We should improve this.

**Comment by rreinurm** [comment] 2015-02-26 22:47
I tried the latest master and verified that the related fix was included. Then I rebuild and set up Kubernetes cluster in vagrant, then unfortunately it didn't work. The interesting thing was then I queried kubectl get events, then I noticed that new pod was rescheduled to same node, even then the node was down.

The first schedule, then node was up:
`Thu, 26 Feb 2015 22:20:32 +0000   Thu, 26 Feb 2015 22:20:32 +0000   1                   redis-master-controller-gziey   Pod                                                     scheduled           {scheduler }           Successfully assigned redis-master-controller-gziey to 10.245.1.4`

The second schedule, then node was down:
`Thu, 26 Feb 2015 22:24:47 +0000   Thu, 26 Feb 2015 22:24:47 +0000   1                   redis-master-controller-oh43e   Pod                                                     scheduled           {scheduler }           Successfully assigned redis-master-controller-oh43e to 10.245.1.4`

But the result is the I query pods then status for redis-master:
`redis-master-controller-oh43e                       redis-master        dockerfile/redis                   10.245.1.4/             app=redis,name=redis-master                           Unknown`

**Comment by ddysher** [comment] 2015-02-27 03:35
That's odd.  Not sure what's going on here. I failed to create a vagrant cluster myself, posted issue here #4302.  So I'll need more information from your side.

Can you post all events and logs from kube-controller-manager and kube-apiserver?  It would be useful if you can also post the sequence of commands (actions) you've used.  Thanks!

**Comment by ddysher** [comment] 2015-03-27 19:15
The issue is not feasible now, closing.  Feel free to reopen if it happends again.

**Closed by ddysher** 2015-03-27 19:15 UTC
Labels: priority/support, team/any, team/master
