### ISSUE TITLE
REST api - some errors return as json and some as plain text

### ISSUE THREAD

**Issue by abonas** [GoogleCloudPlatform/kubernetes#5491] opened 2015-03-15 16:41 UTC
This causes overhead on client side when parsing the errors since need to recheck content type for every error in order not to parse plain text as json (some libraries fail on that).
The errors message format should be standardized.

Examples:
404: Page Not Found
Content-Type: text/plain; charset=utf-8

405 Method Not Allowed
Content-Type: text/plain

409 Conflict
Content-Type: application/json

500 Internal Server Error
Content-Type: application/json

**Comment by abonas** [comment] 2015-03-15 16:57
cc @simon3z

**Comment by bgrant0607** [comment] 2015-03-16 20:28
Duplicate of #4347.

**Closed by bgrant0607** 2015-03-16 20:28 UTC
Labels: api/cluster, area/usability, priority/P2, team/master, team/UX
