### ISSUE TITLE
Rebooting a node makes docker daemon fail to start

### ISSUE THREAD

**Issue by amontalban** [GoogleCloudPlatform/kubernetes#7028] opened 2015-04-18 22:29 UTC
Hey guys,

I'm trying to follow this guide that was provided during Kubernetes Workshop:

https://docs.google.com/document/d/1q3MuEDyghasoIvWDO4L5kFtFt813OYzjHtW5ET7WGRk

And then when I tried to test if the controller started a new pod when I powered off the node where the pod is running it took some time to detect that the node was down and start new pods on a healthy node.

After I start the node again the docker daemon didn't start properly and Kubernetes tried to start the pods in the failing node over and over again. After SSHing to the node and starting the docker daemon manually the pods started without issues.

An extract of the /var/log/docker.log on the failing node is available here: https://gist.github.com/amontalban/23e249ebc8dce04a4922

PS: I pressed enter before writing the whole bug :)

Thank you!

**Comment by roberthbailey** [comment] 2015-04-18 22:33
doesn't what?

**Comment by amontalban** [comment] 2015-04-18 22:36
Hey guys,

I'm trying to follow this guide that was provided during Kubernetes Workshop:

https://docs.google.com/document/d/1q3MuEDyghasoIvWDO4L5kFtFt813OYzjHtW5ET7WGRk

And then when I tried to test if the controller started a new pod when I powered off the node where the pod is running it took some time to detect that the node was down and start new pods on a healthy node.

After I start the node again the docker daemon didn't start properly and Kubernetes tried to start the pods in the failing node over and over again. After SSHing to the node and starting the docker daemon manually the pods started without issues.

An extract of the /var/log/docker.log on the failing node is available here: https://gist.github.com/amontalban/23e249ebc8dce04a4922

PS: I pressed enter before writing the whole bug :)

Thank you!

**Comment by roberthbailey** [comment] 2015-04-18 22:42
@amontalban - Thanks for the bug report. This definitely seems like a problem on the node that should have been detected and resolved automatically by the system. 

/cc @zmerlynn who has been looking at reboots recently. 

@dchen1107 - shouldn't the kubelet detect an unhealthy docker daemon and refuse to start? And monit should notice that the docker daemon is unhealthy and restart it as well.

**Comment by brendandburns** [comment] 2015-04-20 02:58
Triaging to Dawn, feel free to re-assign.

**Comment by zmerlynn** [comment] 2015-04-20 16:23
When you ssh'd in, I assume you probably saw the broken node setup warning? I think this is just a dupe of #6930, which would leave a node in a broken state where `salt` never gets called, which would result in `cbr0`.

**Comment by quinton-hoole** [comment] 2015-04-20 16:29
I think that we need an end-to-end test for this, as it's a basic kubernetes feature for which I don't think that we have any test coverage yet.  We might alternatively be able to build a suitable integration test, which should be faster to run.  I'll open an issue for that now.

**Comment by zmerlynn** [comment] 2015-04-20 16:32
Yeah, I was going to write one as part of #6930, but it takes about 5m right now to reach a stable state. It's absolutely NOT an integration test. It basically has to be a shell test that calls `ssh-to-node reboot`.

**Comment by zmerlynn** [comment] 2015-04-20 16:33
I'm a little resistant to add that to our existing e2e runs. I've been thinking a "fat" nightly suite where we could dump stuff like that.

**Comment by dchen1107** [comment] 2015-04-20 16:38
@roberthbailey Like @zmerlynn mentioned above, it looks like cluster / node initialization issue, most likely related to configure_vm.sh.

**Comment by quinton-hoole** [comment] 2015-04-20 17:16
zmerlynn@ agreed, rather run fat tests like that less frequently.  The scalability tests similarly run less frequently.  Perhaps you can add other fat tests there?

**Comment by zmerlynn** [comment] 2015-04-27 15:45
This should've been closed along with #5666 / #6930.

**Closed by zmerlynn** 2015-04-27 15:45 UTC
Labels: kind/bug, priority/P1, team/cluster-lifecycle, team/node
