### ISSUE TITLE
Flake in volume binder...

### ISSUE THREAD

**Issue by brendandburns** [GoogleCloudPlatform/kubernetes#9843] opened 2015-06-16 03:57 UTC
From https://travis-ci.org/GoogleCloudPlatform/kubernetes/jobs/66970232

```
E0616 03:48:14.528037   25337 util.go:69] Recovered from panic: runtime.errorCString{cstr:0x11f7133} (runtime error: invalid memory address or nil pointer dereference)
/home/travis/gopath/src/github.com/GoogleCloudPlatform/kubernetes/_output/local/go/src/github.com/GoogleCloudPlatform/kubernetes/pkg/util/util.go:63
/home/travis/gopath/src/github.com/GoogleCloudPlatform/kubernetes/_output/local/go/src/github.com/GoogleCloudPlatform/kubernetes/pkg/util/util.go:54
/usr/local/go/src/pkg/runtime/panic.c:248
/usr/local/go/src/pkg/runtime/panic.c:552
/usr/local/go/src/pkg/runtime/os_linux.c:237
/home/travis/gopath/src/github.com/GoogleCloudPlatform/kubernetes/_output/local/go/src/github.com/GoogleCloudPlatform/kubernetes/pkg/client/cache/reflector.go:207
/home/travis/gopath/src/github.com/GoogleCloudPlatform/kubernetes/_output/local/go/src/github.com/GoogleCloudPlatform/kubernetes/pkg/client/cache/reflector.go:181
/home/travis/gopath/src/github.com/GoogleCloudPlatform/kubernetes/_output/local/go/src/github.com/GoogleCloudPlatform/kubernetes/pkg/client/cache/reflector.go:100
/home/travis/gopath/src/github.com/GoogleCloudPlatform/kubernetes/_output/local/go/src/github.com/GoogleCloudPlatform/kubernetes/pkg/util/util.go:112
/home/travis/gopath/src/github.com/GoogleCloudPlatform/kubernetes/_output/local/go/src/github.com/GoogleCloudPlatform/kubernetes/pkg/util/util.go:113
/usr/local/go/src/pkg/runtime/proc.c:1445
==================
WARNING: DATA RACE
Read by goroutine 16:
  github.com/GoogleCloudPlatform/kubernetes/pkg/client/testclient.(*Fake).Invokes()
      /home/travis/gopath/src/github.com/GoogleCloudPlatform/kubernetes/_output/local/go/src/github.com/GoogleCloudPlatform/kubernetes/pkg/client/testclient/testclient.go:63 +0x78
  github.com/GoogleCloudPlatform/kubernetes/pkg/client/testclient.(*FakePersistentVolumeClaims).List()
      /home/travis/gopath/src/github.com/GoogleCloudPlatform/kubernetes/_output/local/go/src/github.com/GoogleCloudPlatform/kubernetes/pkg/client/testclient/fake_persistent_volume_claims.go:32 +0x124
  github.com/GoogleCloudPlatform/kubernetes/pkg/volumeclaimbinder.func·003()
      github.com/GoogleCloudPlatform/kubernetes/pkg/volumeclaimbinder/_test/_obj_test/persistent_volume_claim_binder.go:65 +0x25a
  github.com/GoogleCloudPlatform/kubernetes/pkg/client/cache.(*ListWatch).List()
      /home/travis/gopath/src/github.com/GoogleCloudPlatform/kubernetes/_output/local/go/src/github.com/GoogleCloudPlatform/kubernetes/pkg/client/cache/listwatch.go:63 +0x66
  github.com/GoogleCloudPlatform/kubernetes/pkg/client/cache.(*Reflector).listAndWatch()
      /home/travis/gopath/src/github.com/GoogleCloudPlatform/kubernetes/_output/local/go/src/github.com/GoogleCloudPlatform/kubernetes/pkg/client/cache/reflector.go:134 +0xd1
  github.com/GoogleCloudPlatform/kubernetes/pkg/client/cache.func·005()
      /home/travis/gopath/src/github.com/GoogleCloudPlatform/kubernetes/_output/local/go/src/github.com/GoogleCloudPlatform/kubernetes/pkg/client/cache/reflector.go:100 +0x6d
  github.com/GoogleCloudPlatform/kubernetes/pkg/util.func·004()
      /home/travis/gopath/src/github.com/GoogleCloudPlatform/kubernetes/_output/local/go/src/github.com/GoogleCloudPlatform/kubernetes/pkg/util/util.go:112 +0x5e
  github.com/GoogleCloudPlatform/kubernetes/pkg/util.Until()
      /home/travis/gopath/src/github.com/GoogleCloudPlatform/kubernetes/_output/local/go/src/github.com/GoogleCloudPlatform/kubernetes/pkg/util/util.go:113 +0xbb
Previous write by goroutine 14:
  github.com/GoogleCloudPlatform/kubernetes/pkg/client/testclient.(*FakePersistentVolumes).Watch()
      /home/travis/gopath/src/github.com/GoogleCloudPlatform/kubernetes/_output/local/go/src/github.com/GoogleCloudPlatform/kubernetes/pkg/client/testclient/fake_persistent_volumes.go:62 +0x206
  github.com/GoogleCloudPlatform/kubernetes/pkg/volumeclaimbinder.func·002()
      github.com/GoogleCloudPlatform/kubernetes/pkg/volumeclaimbinder/_test/_obj_test/persistent_volume_claim_binder.go:49 +0x26f
  github.com/GoogleCloudPlatform/kubernetes/pkg/client/cache.(*ListWatch).Watch()
      /home/travis/gopath/src/github.com/GoogleCloudPlatform/kubernetes/_output/local/go/src/github.com/GoogleCloudPlatform/kubernetes/pkg/client/cache/listwatch.go:68 +0x89
  github.com/GoogleCloudPlatform/kubernetes/pkg/client/cache.(*Reflector).listAndWatch()
      /home/travis/gopath/src/github.com/GoogleCloudPlatform/kubernetes/_output/local/go/src/github.com/GoogleCloudPlatform/kubernetes/pkg/client/cache/reflector.go:157 +0x702
  github.com/GoogleCloudPlatform/kubernetes/pkg/client/cache.func·005()
      /home/travis/gopath/src/github.com/GoogleCloudPlatform/kubernetes/_output/local/go/src/github.com/GoogleCloudPlatform/kubernetes/pkg/client/cache/reflector.go:100 +0x6d
  github.com/GoogleCloudPlatform/kubernetes/pkg/util.func·004()
      /home/travis/gopath/src/github.com/GoogleCloudPlatform/kubernetes/_output/local/go/src/github.com/GoogleCloudPlatform/kubernetes/pkg/util/util.go:112 +0x5e
  github.com/GoogleCloudPlatform/kubernetes/pkg/util.Until()
      /home/travis/gopath/src/github.com/GoogleCloudPlatform/kubernetes/_output/local/go/src/github.com/GoogleCloudPlatform/kubernetes/pkg/util/util.go:113 +0xbb
Goroutine 16 (running) created at:
  github.com/GoogleCloudPlatform/kubernetes/pkg/client/cache.(*Reflector).RunUntil()
      /home/travis/gopath/src/github.com/GoogleCloudPlatform/kubernetes/_output/local/go/src/github.com/GoogleCloudPlatform/kubernetes/pkg/client/cache/reflector.go:100 +0x130
  github.com/GoogleCloudPlatform/kubernetes/pkg/controller/framework.(*Controller).Run()
      /home/travis/gopath/src/github.com/GoogleCloudPlatform/kubernetes/_output/local/go/src/github.com/GoogleCloudPlatform/kubernetes/pkg/controller/framework/controller.go:94 +0x1cb
Goroutine 14 (running) created at:
  github.com/GoogleCloudPlatform/kubernetes/pkg/client/cache.(*Reflector).RunUntil()
      /home/travis/gopath/src/github.com/GoogleCloudPlatform/kubernetes/_output/local/go/src/github.com/GoogleCloudPlatform/kubernetes/pkg/client/cache/reflector.go:100 +0x130
  github.com/GoogleCloudPlatform/kubernetes/pkg/controller/framework.(*Controller).Run()
      /home/travis/gopath/src/github.com/GoogleCloudPlatform/kubernetes/_output/local/go/src/github.com/GoogleCloudPlatform/kubernetes/pkg/controller/framework/controller.go:94 +0x1cb
==================
==================
WARNING: DATA RACE
Read by goroutine 16:
  runtime.growslice()
      /usr/local/go/src/pkg/runtime/slice.goc:58 +0x0
  github.com/GoogleCloudPlatform/kubernetes/pkg/client/testclient.(*Fake).Invokes()
      /home/travis/gopath/src/github.com/GoogleCloudPlatform/kubernetes/_output/local/go/src/github.com/GoogleCloudPlatform/kubernetes/pkg/client/testclient/testclient.go:63 +0xec
  github.com/GoogleCloudPlatform/kubernetes/pkg/client/testclient.(*FakePersistentVolumeClaims).List()
      /home/travis/gopath/src/github.com/GoogleCloudPlatform/kubernetes/_output/local/go/src/github.com/GoogleCloudPlatform/kubernetes/pkg/client/testclient/fake_persistent_volume_claims.go:32 +0x124
  github.com/GoogleCloudPlatform/kubernetes/pkg/volumeclaimbinder.func·003()
      github.com/GoogleCloudPlatform/kubernetes/pkg/volumeclaimbinder/_test/_obj_test/persistent_volume_claim_binder.go:65 +0x25a
  github.com/GoogleCloudPlatform/kubernetes/pkg/client/cache.(*ListWatch).List()
      /home/travis/gopath/src/github.com/GoogleCloudPlatform/kubernetes/_output/local/go/src/github.com/GoogleCloudPlatform/kubernetes/pkg/client/cache/listwatch.go:63 +0x66
  github.com/GoogleCloudPlatform/kubernetes/pkg/client/cache.(*Reflector).listAndWatch()
      /home/travis/gopath/src/github.com/GoogleCloudPlatform/kubernetes/_output/local/go/src/github.com/GoogleCloudPlatform/kubernetes/pkg/client/cache/reflector.go:134 +0xd1
  github.com/GoogleCloudPlatform/kubernetes/pkg/client/cache.func·005()
      /home/travis/gopath/src/github.com/GoogleCloudPlatform/kubernetes/_output/local/go/src/github.com/GoogleCloudPlatform/kubernetes/pkg/client/cache/reflector.go:100 +0x6d
  github.com/GoogleCloudPlatform/kubernetes/pkg/util.func·004()
      /home/travis/gopath/src/github.com/GoogleCloudPlatform/kubernetes/_output/local/go/src/github.com/GoogleCloudPlatform/kubernetes/pkg/util/util.go:112 +0x5e
  github.com/GoogleCloudPlatform/kubernetes/pkg/util.Until()
      /home/travis/gopath/src/github.com/GoogleCloudPlatform/kubernetes/_output/local/go/src/github.com/GoogleCloudPlatform/kubernetes/pkg/util/util.go:113 +0xbb
Previous write by goroutine 14:
  github.com/GoogleCloudPlatform/kubernetes/pkg/client/testclient.(*FakePersistentVolumes).Watch()
      /home/travis/gopath/src/github.com/GoogleCloudPlatform/kubernetes/_output/local/go/src/github.com/GoogleCloudPlatform/kubernetes/pkg/client/testclient/fake_persistent_volumes.go:62 +0x1a4
  github.com/GoogleCloudPlatform/kubernetes/pkg/volumeclaimbinder.func·002()
      github.com/GoogleCloudPlatform/kubernetes/pkg/volumeclaimbinder/_test/_obj_test/persistent_volume_claim_binder.go:49 +0x26f
  github.com/GoogleCloudPlatform/kubernetes/pkg/client/cache.(*ListWatch).Watch()
      /home/travis/gopath/src/github.com/GoogleCloudPlatform/kubernetes/_output/local/go/src/github.com/GoogleCloudPlatform/kubernetes/pkg/client/cache/listwatch.go:68 +0x89
  github.com/GoogleCloudPlatform/kubernetes/pkg/client/cache.(*Reflector).listAndWatch()
      /home/travis/gopath/src/github.com/GoogleCloudPlatform/kubernetes/_output/local/go/src/github.com/GoogleCloudPlatform/kubernetes/pkg/client/cache/reflector.go:157 +0x702
  github.com/GoogleCloudPlatform/kubernetes/pkg/client/cache.func·005()
      /home/travis/gopath/src/github.com/GoogleCloudPlatform/kubernetes/_output/local/go/src/github.com/GoogleCloudPlatform/kubernetes/pkg/client/cache/reflector.go:100 +0x6d
  github.com/GoogleCloudPlatform/kubernetes/pkg/util.func·004()
      /home/travis/gopath/src/github.com/GoogleCloudPlatform/kubernetes/_output/local/go/src/github.com/GoogleCloudPlatform/kubernetes/pkg/util/util.go:112 +0x5e
  github.com/GoogleCloudPlatform/kubernetes/pkg/util.Until()
      /home/travis/gopath/src/github.com/GoogleCloudPlatform/kubernetes/_output/local/go/src/github.com/GoogleCloudPlatform/kubernetes/pkg/util/util.go:113 +0xbb
Goroutine 16 (running) created at:
  github.com/GoogleCloudPlatform/kubernetes/pkg/client/cache.(*Reflector).RunUntil()
      /home/travis/gopath/src/github.com/GoogleCloudPlatform/kubernetes/_output/local/go/src/github.com/GoogleCloudPlatform/kubernetes/pkg/client/cache/reflector.go:100 +0x130
  github.com/GoogleCloudPlatform/kubernetes/pkg/controller/framework.(*Controller).Run()
      /home/travis/gopath/src/github.com/GoogleCloudPlatform/kubernetes/_output/local/go/src/github.com/GoogleCloudPlatform/kubernetes/pkg/controller/framework/controller.go:94 +0x1cb
Goroutine 14 (running) created at:
  github.com/GoogleCloudPlatform/kubernetes/pkg/client/cache.(*Reflector).RunUntil()
      /home/travis/gopath/src/github.com/GoogleCloudPlatform/kubernetes/_output/local/go/src/github.com/GoogleCloudPlatform/kubernetes/pkg/client/cache/reflector.go:100 +0x130
  github.com/GoogleCloudPlatform/kubernetes/pkg/controller/framework.(*Controller).Run()
      /home/travis/gopath/src/github.com/GoogleCloudPlatform/kubernetes/_output/local/go/src/github.com/GoogleCloudPlatform/kubernetes/pkg/controller/framework/controller.go:94 +0x1cb
==================
E0616 03:48:14.529348   25337 util.go:69] Recovered from panic: runtime.errorCString{cstr:0x11f7133} (runtime error: invalid memory address or nil pointer dereference)
/home/travis/gopath/src/github.com/GoogleCloudPlatform/kubernetes/_output/local/go/src/github.com/GoogleCloudPlatform/kubernetes/pkg/util/util.go:63
/home/travis/gopath/src/github.com/GoogleCloudPlatform/kubernetes/_output/local/go/src/github.com/GoogleCloudPlatform/kubernetes/pkg/util/util.go:54
/usr/local/go/src/pkg/runtime/panic.c:248
/usr/local/go/src/pkg/runtime/panic.c:552
/usr/local/go/src/pkg/runtime/os_linux.c:237
/home/travis/gopath/src/github.com/GoogleCloudPlatform/kubernetes/_output/local/go/src/github.com/GoogleCloudPlatform/kubernetes/pkg/client/cache/reflector.go:207
/home/travis/gopath/src/github.com/GoogleCloudPlatform/kubernetes/_output/local/go/src/github.com/GoogleCloudPlatform/kubernetes/pkg/client/cache/reflector.go:181
/home/travis/gopath/src/github.com/GoogleCloudPlatform/kubernetes/_output/local/go/src/github.com/GoogleCloudPlatform/kubernetes/pkg/client/cache/reflector.go:100
/home/travis/gopath/src/github.com/GoogleCloudPlatform/kubernetes/_output/local/go/src/github.com/GoogleCloudPlatform/kubernetes/pkg/util/util.go:112
/home/travis/gopath/src/github.com/GoogleCloudPlatform/kubernetes/_output/local/go/src/github.com/GoogleCloudPlatform/kubernetes/pkg/util/util.go:113
/usr/local/go/src/pkg/runtime/proc.c:1445
PASS
coverage: 59.2% of statements
Found 2 data race(s)
FAIL	github.com/GoogleCloudPlatform/kubernetes/pkg/volumeclaimbinder	1.177s
```

**Comment by thockin** [comment] 2015-06-16 04:09
@markturansky for an assist

**Comment by a-robinson** [comment] 2015-06-29 17:10
I saw this again today in build https://travis-ci.org/GoogleCloudPlatform/kubernetes/jobs/68838567
```
E0629 16:54:05.755283   26054 util.go:69] Recovered from panic: runtime.errorCString{cstr:0x11f4133} (runtime error: invalid memory address or nil pointer dereference)
/home/travis/gopath/src/github.com/GoogleCloudPlatform/kubernetes/_output/local/go/src/github.com/GoogleCloudPlatform/kubernetes/pkg/util/util.go:63
/home/travis/gopath/src/github.com/GoogleCloudPlatform/kubernetes/_output/local/go/src/github.com/GoogleCloudPlatform/kubernetes/pkg/util/util.go:54
/usr/local/go/src/pkg/runtime/panic.c:248
/usr/local/go/src/pkg/runtime/panic.c:552
/usr/local/go/src/pkg/runtime/os_linux.c:237
/home/travis/gopath/src/github.com/GoogleCloudPlatform/kubernetes/_output/local/go/src/github.com/GoogleCloudPlatform/kubernetes/pkg/client/cache/reflector.go:207
/home/travis/gopath/src/github.com/GoogleCloudPlatform/kubernetes/_output/local/go/src/github.com/GoogleCloudPlatform/kubernetes/pkg/client/cache/reflector.go:181
/home/travis/gopath/src/github.com/GoogleCloudPlatform/kubernetes/_output/local/go/src/github.com/GoogleCloudPlatform/kubernetes/pkg/client/cache/reflector.go:100
/home/travis/gopath/src/github.com/GoogleCloudPlatform/kubernetes/_output/local/go/src/github.com/GoogleCloudPlatform/kubernetes/pkg/util/util.go:112
/home/travis/gopath/src/github.com/GoogleCloudPlatform/kubernetes/_output/local/go/src/github.com/GoogleCloudPlatform/kubernetes/pkg/util/util.go:113
/usr/local/go/src/pkg/runtime/proc.c:1445
==================
WARNING: DATA RACE
Read by goroutine 16:
  github.com/GoogleCloudPlatform/kubernetes/pkg/client/testclient.(*Fake).Invokes()
      /home/travis/gopath/src/github.com/GoogleCloudPlatform/kubernetes/_output/local/go/src/github.com/GoogleCloudPlatform/kubernetes/pkg/client/testclient/testclient.go:63 +0x78
  github.com/GoogleCloudPlatform/kubernetes/pkg/client/testclient.(*FakePersistentVolumeClaims).List()
      /home/travis/gopath/src/github.com/GoogleCloudPlatform/kubernetes/_output/local/go/src/github.com/GoogleCloudPlatform/kubernetes/pkg/client/testclient/fake_persistent_volume_claims.go:32 +0x124
  github.com/GoogleCloudPlatform/kubernetes/pkg/volumeclaimbinder.funcÂ·003()
      github.com/GoogleCloudPlatform/kubernetes/pkg/volumeclaimbinder/_test/_obj_test/persistent_volume_claim_binder.go:65 +0x25a
  github.com/GoogleCloudPlatform/kubernetes/pkg/client/cache.(*ListWatch).List()
      /home/travis/gopath/src/github.com/GoogleCloudPlatform/kubernetes/_output/local/go/src/github.com/GoogleCloudPlatform/kubernetes/pkg/client/cache/listwatch.go:63 +0x66
  github.com/GoogleCloudPlatform/kubernetes/pkg/client/cache.(*Reflector).listAndWatch()
      /home/travis/gopath/src/github.com/GoogleCloudPlatform/kubernetes/_output/local/go/src/github.com/GoogleCloudPlatform/kubernetes/pkg/client/cache/reflector.go:134 +0xd1
  github.com/GoogleCloudPlatform/kubernetes/pkg/client/cache.funcÂ·005()
      /home/travis/gopath/src/github.com/GoogleCloudPlatform/kubernetes/_output/local/go/src/github.com/GoogleCloudPlatform/kubernetes/pkg/client/cache/reflector.go:100 +0x6d
  github.com/GoogleCloudPlatform/kubernetes/pkg/util.funcÂ·004()
      /home/travis/gopath/src/github.com/GoogleCloudPlatform/kubernetes/_output/local/go/src/github.com/GoogleCloudPlatform/kubernetes/pkg/util/util.go:112 +0x5e
  github.com/GoogleCloudPlatform/kubernetes/pkg/util.Until()
      /home/travis/gopath/src/github.com/GoogleCloudPlatform/kubernetes/_output/local/go/src/github.com/GoogleCloudPlatform/kubernetes/pkg/util/util.go:113 +0xbb

Previous write by goroutine 14:
  github.com/GoogleCloudPlatform/kubernetes/pkg/client/testclient.(*FakePersistentVolumes).Watch()
      /home/travis/gopath/src/github.com/GoogleCloudPlatform/kubernetes/_output/local/go/src/github.com/GoogleCloudPlatform/kubernetes/pkg/client/testclient/fake_persistent_volumes.go:62 +0x206
  github.com/GoogleCloudPlatform/kubernetes/pkg/volumeclaimbinder.funcÂ·002()
      github.com/GoogleCloudPlatform/kubernetes/pkg/volumeclaimbinder/_test/_obj_test/persistent_volume_claim_binder.go:49 +0x26f
  github.com/GoogleCloudPlatform/kubernetes/pkg/client/cache.(*ListWatch).Watch()
      /home/travis/gopath/src/github.com/GoogleCloudPlatform/kubernetes/_output/local/go/src/github.com/GoogleCloudPlatform/kubernetes/pkg/client/cache/listwatch.go:68 +0x89
  github.com/GoogleCloudPlatform/kubernetes/pkg/client/cache.(*Reflector).listAndWatch()
      /home/travis/gopath/src/github.com/GoogleCloudPlatform/kubernetes/_output/local/go/src/github.com/GoogleCloudPlatform/kubernetes/pkg/client/cache/reflector.go:157 +0x702
  github.com/GoogleCloudPlatform/kubernetes/pkg/client/cache.funcÂ·005()
      /home/travis/gopath/src/github.com/GoogleCloudPlatform/kubernetes/_output/local/go/src/github.com/GoogleCloudPlatform/kubernetes/pkg/client/cache/reflector.go:100 +0x6d
  github.com/GoogleCloudPlatform/kubernetes/pkg/util.funcÂ·004()
      /home/travis/gopath/src/github.com/GoogleCloudPlatform/kubernetes/_output/local/go/src/github.com/GoogleCloudPlatform/kubernetes/pkg/util/util.go:112 +0x5e
  github.com/GoogleCloudPlatform/kubernetes/pkg/util.Until()
      /home/travis/gopath/src/github.com/GoogleCloudPlatform/kubernetes/_output/local/go/src/github.com/GoogleCloudPlatform/kubernetes/pkg/util/util.go:113 +0xbb

Goroutine 16 (running) created at:
  github.com/GoogleCloudPlatform/kubernetes/pkg/client/cache.(*Reflector).RunUntil()
      /home/travis/gopath/src/github.com/GoogleCloudPlatform/kubernetes/_output/local/go/src/github.com/GoogleCloudPlatform/kubernetes/pkg/client/cache/reflector.go:100 +0x130
  github.com/GoogleCloudPlatform/kubernetes/pkg/controller/framework.(*Controller).Run()
      /home/travis/gopath/src/github.com/GoogleCloudPlatform/kubernetes/_output/local/go/src/github.com/GoogleCloudPlatform/kubernetes/pkg/controller/framework/controller.go:94 +0x1cb

Goroutine 14 (running) created at:
  github.com/GoogleCloudPlatform/kubernetes/pkg/client/cache.(*Reflector).RunUntil()
      /home/travis/gopath/src/github.com/GoogleCloudPlatform/kubernetes/_output/local/go/src/github.com/GoogleCloudPlatform/kubernetes/pkg/client/cache/reflector.go:100 +0x130
  github.com/GoogleCloudPlatform/kubernetes/pkg/controller/framework.(*Controller).Run()
      /home/travis/gopath/src/github.com/GoogleCloudPlatform/kubernetes/_output/local/go/src/github.com/GoogleCloudPlatform/kubernetes/pkg/controller/framework/controller.go:94 +0x1cb
==================
==================
WARNING: DATA RACE
Read by goroutine 16:
  runtime.growslice()
      /usr/local/go/src/pkg/runtime/slice.goc:58 +0x0
  github.com/GoogleCloudPlatform/kubernetes/pkg/client/testclient.(*Fake).Invokes()
      /home/travis/gopath/src/github.com/GoogleCloudPlatform/kubernetes/_output/local/go/src/github.com/GoogleCloudPlatform/kubernetes/pkg/client/testclient/testclient.go:63 +0xec
  github.com/GoogleCloudPlatform/kubernetes/pkg/client/testclient.(*FakePersistentVolumeClaims).List()
      /home/travis/gopath/src/github.com/GoogleCloudPlatform/kubernetes/_output/local/go/src/github.com/GoogleCloudPlatform/kubernetes/pkg/client/testclient/fake_persistent_volume_claims.go:32 +0x124
  github.com/GoogleCloudPlatform/kubernetes/pkg/volumeclaimbinder.funcÂ·003()
      github.com/GoogleCloudPlatform/kubernetes/pkg/volumeclaimbinder/_test/_obj_test/persistent_volume_claim_binder.go:65 +0x25a
  github.com/GoogleCloudPlatform/kubernetes/pkg/client/cache.(*ListWatch).List()
      /home/travis/gopath/src/github.com/GoogleCloudPlatform/kubernetes/_output/local/go/src/github.com/GoogleCloudPlatform/kubernetes/pkg/client/cache/listwatch.go:63 +0x66
  github.com/GoogleCloudPlatform/kubernetes/pkg/client/cache.(*Reflector).listAndWatch()
      /home/travis/gopath/src/github.com/GoogleCloudPlatform/kubernetes/_output/local/go/src/github.com/GoogleCloudPlatform/kubernetes/pkg/client/cache/reflector.go:134 +0xd1
  github.com/GoogleCloudPlatform/kubernetes/pkg/client/cache.funcÂ·005()
      /home/travis/gopath/src/github.com/GoogleCloudPlatform/kubernetes/_output/local/go/src/github.com/GoogleCloudPlatform/kubernetes/pkg/client/cache/reflector.go:100 +0x6d
  github.com/GoogleCloudPlatform/kubernetes/pkg/util.funcÂ·004()
      /home/travis/gopath/src/github.com/GoogleCloudPlatform/kubernetes/_output/local/go/src/github.com/GoogleCloudPlatform/kubernetes/pkg/util/util.go:112 +0x5e
  github.com/GoogleCloudPlatform/kubernetes/pkg/util.Until()
      /home/travis/gopath/src/github.com/GoogleCloudPlatform/kubernetes/_output/local/go/src/github.com/GoogleCloudPlatform/kubernetes/pkg/util/util.go:113 +0xbb

Previous write by goroutine 14:
  github.com/GoogleCloudPlatform/kubernetes/pkg/client/testclient.(*FakePersistentVolumes).Watch()
      /home/travis/gopath/src/github.com/GoogleCloudPlatform/kubernetes/_output/local/go/src/github.com/GoogleCloudPlatform/kubernetes/pkg/client/testclient/fake_persistent_volumes.go:62 +0x1a4
  github.com/GoogleCloudPlatform/kubernetes/pkg/volumeclaimbinder.funcÂ·002()
      github.com/GoogleCloudPlatform/kubernetes/pkg/volumeclaimbinder/_test/_obj_test/persistent_volume_claim_binder.go:49 +0x26f
  github.com/GoogleCloudPlatform/kubernetes/pkg/client/cache.(*ListWatch).Watch()
      /home/travis/gopath/src/github.com/GoogleCloudPlatform/kubernetes/_output/local/go/src/github.com/GoogleCloudPlatform/kubernetes/pkg/client/cache/listwatch.go:68 +0x89
  github.com/GoogleCloudPlatform/kubernetes/pkg/client/cache.(*Reflector).listAndWatch()
      /home/travis/gopath/src/github.com/GoogleCloudPlatform/kubernetes/_output/local/go/src/github.com/GoogleCloudPlatform/kubernetes/pkg/client/cache/reflector.go:157 +0x702
  github.com/GoogleCloudPlatform/kubernetes/pkg/client/cache.funcÂ·005()
      /home/travis/gopath/src/github.com/GoogleCloudPlatform/kubernetes/_output/local/go/src/github.com/GoogleCloudPlatform/kubernetes/pkg/client/cache/reflector.go:100 +0x6d
  github.com/GoogleCloudPlatform/kubernetes/pkg/util.funcÂ·004()
      /home/travis/gopath/src/github.com/GoogleCloudPlatform/kubernetes/_output/local/go/src/github.com/GoogleCloudPlatform/kubernetes/pkg/util/util.go:112 +0x5e
  github.com/GoogleCloudPlatform/kubernetes/pkg/util.Until()
      /home/travis/gopath/src/github.com/GoogleCloudPlatform/kubernetes/_output/local/go/src/github.com/GoogleCloudPlatform/kubernetes/pkg/util/util.go:113 +0xbb

Goroutine 16 (running) created at:
  github.com/GoogleCloudPlatform/kubernetes/pkg/client/cache.(*Reflector).RunUntil()
      /home/travis/gopath/src/github.com/GoogleCloudPlatform/kubernetes/_output/local/go/src/github.com/GoogleCloudPlatform/kubernetes/pkg/client/cache/reflector.go:100 +0x130
  github.com/GoogleCloudPlatform/kubernetes/pkg/controller/framework.(*Controller).Run()
      /home/travis/gopath/src/github.com/GoogleCloudPlatform/kubernetes/_output/local/go/src/github.com/GoogleCloudPlatform/kubernetes/pkg/controller/framework/controller.go:94 +0x1cb

Goroutine 14 (running) created at:
  github.com/GoogleCloudPlatform/kubernetes/pkg/client/cache.(*Reflector).RunUntil()
      /home/travis/gopath/src/github.com/GoogleCloudPlatform/kubernetes/_output/local/go/src/github.com/GoogleCloudPlatform/kubernetes/pkg/client/cache/reflector.go:100 +0x130
  github.com/GoogleCloudPlatform/kubernetes/pkg/controller/framework.(*Controller).Run()
      /home/travis/gopath/src/github.com/GoogleCloudPlatform/kubernetes/_output/local/go/src/github.com/GoogleCloudPlatform/kubernetes/pkg/controller/framework/controller.go:94 +0x1cb
==================
E0629 16:54:05.756603   26054 util.go:69] Recovered from panic: runtime.errorCString{cstr:0x11f4133} (runtime error: invalid memory address or nil pointer dereference)
/home/travis/gopath/src/github.com/GoogleCloudPlatform/kubernetes/_output/local/go/src/github.com/GoogleCloudPlatform/kubernetes/pkg/util/util.go:63
/home/travis/gopath/src/github.com/GoogleCloudPlatform/kubernetes/_output/local/go/src/github.com/GoogleCloudPlatform/kubernetes/pkg/util/util.go:54
/usr/local/go/src/pkg/runtime/panic.c:248
/usr/local/go/src/pkg/runtime/panic.c:552
/usr/local/go/src/pkg/runtime/os_linux.c:237
/home/travis/gopath/src/github.com/GoogleCloudPlatform/kubernetes/_output/local/go/src/github.com/GoogleCloudPlatform/kubernetes/pkg/client/cache/reflector.go:207
/home/travis/gopath/src/github.com/GoogleCloudPlatform/kubernetes/_output/local/go/src/github.com/GoogleCloudPlatform/kubernetes/pkg/client/cache/reflector.go:181
/home/travis/gopath/src/github.com/GoogleCloudPlatform/kubernetes/_output/local/go/src/github.com/GoogleCloudPlatform/kubernetes/pkg/client/cache/reflector.go:100
/home/travis/gopath/src/github.com/GoogleCloudPlatform/kubernetes/_output/local/go/src/github.com/GoogleCloudPlatform/kubernetes/pkg/util/util.go:112
/home/travis/gopath/src/github.com/GoogleCloudPlatform/kubernetes/_output/local/go/src/github.com/GoogleCloudPlatform/kubernetes/pkg/util/util.go:113
/usr/local/go/src/pkg/runtime/proc.c:1445
PASS
coverage: 59.2% of statements
Found 2 data race(s)
FAIL	github.com/GoogleCloudPlatform/kubernetes/pkg/volumeclaimbinder	1.269s
```

**Comment by thockin** [comment] 2015-06-29 17:15
@markturansky again

**Comment by a-robinson** [comment] 2015-06-30 01:14
And again. This isn't the cause of all our travis flakes, but it's definitely not helping: https://travis-ci.org/GoogleCloudPlatform/kubernetes/jobs/68901823

@markturansky - could you please take a look at this tomorrow?

**Comment by markturansky** [comment] 2015-06-30 01:19
Any tips on reproducing?  My tests are set to run with "-race".

**Comment by a-robinson** [comment] 2015-06-30 01:21
This is the commandline that travis uses:
```bash
KUBE_RACE="-race" KUBE_COVER="y" KUBE_GOVERALLS_BIN="$HOME/gopath/bin/goveralls" KUBE_TIMEOUT='-timeout 300s' KUBE_COVERPROCS=8 KUBE_TEST_API_VERSIONS="${KUBE_TEST_API_VERSIONS}" KUBE_TEST_ETCD_PREFIXES="${KUBE_TEST_ETCD_PREFIXES}" ./hack/test-go.sh -- -p=2
```

**Comment by markturansky** [comment] 2015-07-30 03:52
@mikedanese Is this closed by #10783?

**Comment by mikedanese** [comment] 2015-07-30 05:33
Yes I believe so. I'll monitor it over the next couple days.

**Closed by mikedanese** 2015-07-30 05:33 UTC
Labels: priority/P1, team/testing

**Comment by karlkfi** [comment] 2015-08-07 05:22
xref: #10775
