### ISSUE TITLE
kube-dns name not reported by kubectl cluster-info

### ISSUE THREAD

**Issue by satnam6502** [GoogleCloudPlatform/kubernetes#7934] opened 2015-05-07 23:48 UTC
```
Cluster validation succeeded
Done, listing cluster services:

Starting cluster using os distro: debian
current-context: "kubernetes-logging_kubernetes"
Running: cluster/../cluster/gce/../../cluster/../cluster/../cluster/gce/../../cluster/../_output/dockerized/bin/linux/amd64/kubectl cluster-info
Kubernetes master is running at https://146.148.41.184
elasticsearch-logging is running at https://146.148.41.184/api/v1beta3/proxy/namespaces/default/services/elasticsearch-logging
kibana-logging is running at https://146.148.41.184/api/v1beta3/proxy/namespaces/default/services/kibana-logging
 is running at https://146.148.41.184/api/v1beta3/proxy/namespaces/default/services/kube-dns
$ kubectl version
Client Version: version.Info{Major:"0", Minor:"16+", GitVersion:"v0.16.2-591-g65bd04fc5134d7-dirty", GitCommit:"65bd04fc5134d7b1a1af520016a6d3f28be65750", GitTreeState:"dirty"}
Server Version: version.Info{Major:"0", Minor:"16+", GitVersion:"v0.16.2-591-g65bd04fc5134d7-dirty", GitCommit:"65bd04fc5134d7b1a1af520016a6d3f28be65750", GitTreeState:"dirty"}
```

**Comment by roberthbailey** [comment] 2015-05-08 00:05
Dupe of #7922.

**Closed by roberthbailey** 2015-05-08 00:05 UTC
Labels: kind/bug, priority/P2, team/UX
