### ISSUE TITLE
swagger json is invalid

### ISSUE THREAD

**Issue by sym3tri** [GoogleCloudPlatform/kubernetes#4083] opened 2015-02-03 22:44 UTC
does not validate with swagger-tools CLI tool: https://github.com/apigee-127/swagger-tools/blob/master/docs/CLI.md#validate

**Comment by a-robinson** [comment] 2015-02-03 22:58
cc @nikhiljindal

**Comment by nikhiljindal** [comment] 2015-02-03 23:26
Thanks for reporting this Ed!

Can you please share the command you executed (specifically the arguments you passed) and the error you got?

**Comment by sym3tri** [comment] 2015-02-03 23:42
sure, no problem...

I downloaded all the references json files from: http://kubernetes.io/swagger-spec/
Then I ran:
```
swagger-tools validate root.json api.json version.json v1beta1.json v1beta2.json v1beta3.json
```
which produces:
```
  API Declaration (/api) Errors:

    #/basePath: String does not match pattern ^https?://: 172.17.130.36:8282

  API Declaration (/version) Errors:

    #/basePath: String does not match pattern ^https?://: 172.17.130.36:8282

  API Declaration (/api/v1beta1) Errors:

    #/models/v1beta1.Service/properties/publicIPs/items: Data does not match any schemas from 'oneOf'
      #/models/v1beta1.Service/properties/publicIPs/items: Expected type object but found type array
      #/models/v1beta1.Service/properties/publicIPs/items: Data is valid against more than one schema from 'oneOf'
      #/models/v1beta1.Service/properties/publicIPs/items: Expected type object but found type array
    #/basePath: String does not match pattern ^https?://: 172.17.130.36:8282

  API Declaration (/api/v1beta2) Errors:

    #/models/v1beta2.Service/properties/publicIPs/items: Data does not match any schemas from 'oneOf'
      #/models/v1beta2.Service/properties/publicIPs/items: Expected type object but found type array
      #/models/v1beta2.Service/properties/publicIPs/items: Data is valid against more than one schema from 'oneOf'
      #/models/v1beta2.Service/properties/publicIPs/items: Expected type object but found type array
    #/basePath: String does not match pattern ^https?://: 172.17.130.36:8282

  API Declaration (/api/v1beta3) Errors:

    #/models/v1beta3.ServiceSpec/properties/publicIPs/items: Data does not match any schemas from 'oneOf'
      #/models/v1beta3.ServiceSpec/properties/publicIPs/items: Expected type object but found type array
      #/models/v1beta3.ServiceSpec/properties/publicIPs/items: Data is valid against more than one schema from 'oneOf'
      #/models/v1beta3.ServiceSpec/properties/publicIPs/items: Expected type object but found type array
    #/basePath: String does not match pattern ^https?://: 172.17.130.36:8282

8 errors and 0 warnings
```

**Comment by cjcullen** [comment] 2015-02-12 02:07
After learning about swagger for a day...

It looks like we should probably make basePath = "http://kubernetes.io/swagger-spec"
If that is the right way to go, we could just replace the localhost apiserver URL with the kubernetes.io one in the swagger generation script.

I can't find anything wrong with how publicIPs are defined, and it is especially confusing that it is complaining about using oneOf (which we aren't using AFAICT).

I'm going to have to defer to @nikhiljindal for resolution on this one.

**Comment by cjcullen** [comment] 2015-02-12 20:00
If I'm understanding it correctly, that online validator only validates against the 2.0 schema, which would explain why it thinks we have several missing properties at the base level.

**Comment by nikhiljindal** [comment] 2015-02-24 04:15
1. Regarding duplicate body params: That has been fixed but the swagger-spec used to generate the documentation on kubernetes.io was not updated. Will send a PR for that. (We need to automate that: https://github.com/GoogleCloudPlatform/kubernetes/issues/4763)

2. This sounds like a bug that needs fixing.

We use https://github.com/emicklei/go-restful to generate our swagger-spec. We should check if the sample go-restful examples pass this validation check.

**Comment by nikhiljindal** [comment] 2015-02-26 20:03
Sent https://github.com/GoogleCloudPlatform/kubernetes/pull/4863 to update the spec.

**Comment by bgrant0607** [comment] 2015-03-11 18:48
@nikhiljindal What's left to be done here?

**Comment by nikhiljindal** [comment] 2015-03-11 20:43
Last time I tried I was having problems installing swagger-tools.
Let me try that again.

**Comment by nikhiljindal** [comment] 2015-03-11 20:45
Work to be done is to see if go-restful sample examples pass the validation. If not, then we need to fix upstream. Else the issue is in our code.

**Comment by nikhiljindal** [comment] 2015-03-12 04:58
There were 2 validation errors:

1. basePath didnt have a schema. This was an issue in our code. Sent https://github.com/GoogleCloudPlatform/kubernetes/pull/5342 to fix that.
2. "Data does not match any schemas from 'oneOf'. Expected type object but found type array" errors. This is an issue with the way go-restful generates swagger spec. Filed https://github.com/emicklei/go-restful/issues/186 for that.

We can mark this issue fixed when https://github.com/GoogleCloudPlatform/kubernetes/pull/5342 is submitted and when https://github.com/emicklei/go-restful/issues/186 is fixed upstream.

**Comment by bgrant0607** [comment] 2015-03-12 05:43
Is (2) the cause of #3757?

**Comment by nikhiljindal** [comment] 2015-03-13 06:07
Now, that we have fixed those issues, we are getting a new set of errors and warnings (58 errors and 119 warnings):



```
API Declaration (/api/v1beta1) Errors:

    #/models/v1beta1.Container/properties/command/items/$ref: Model could not be resolved: string
    #/models/v1beta1.Endpoints/properties/endpoints/items/$ref: Model could not be resolved: string
    #/models/v1beta1.ExecAction/properties/command/items/$ref: Model could not be resolved: string
    #/models/v1beta1.Service/properties/publicIPs/items/$ref: Model could not be resolved: string
    #/apis/8/path: API requires path parameter but it is not defined: name
    #/apis/14/path: API requires path parameter but it is not defined: path:*
    #/apis/14/path: API requires path parameter but it is not defined: path:*
    #/apis/14/path: API requires path parameter but it is not defined: path:*
    #/apis/14/path: API requires path parameter but it is not defined: path:*
    #/apis/24/path: API requires path parameter but it is not defined: path:*
    #/apis/24/path: API requires path parameter but it is not defined: path:*
    #/apis/24/path: API requires path parameter but it is not defined: path:*
    #/apis/24/path: API requires path parameter but it is not defined: path:*
    #/apis/54/path: API requires path parameter but it is not defined: path:*
    #/apis/54/path: API requires path parameter but it is not defined: path:*
    #/apis/54/path: API requires path parameter but it is not defined: path:*
    #/apis/54/path: API requires path parameter but it is not defined: path:*
    #/apis/58/path: API requires path parameter but it is not defined: path:*
    #/apis/58/path: API requires path parameter but it is not defined: path:*
    #/apis/58/path: API requires path parameter but it is not defined: path:*
    #/apis/58/path: API requires path parameter but it is not defined: path:*

  API Declaration (/api/v1beta1) Warnings:

    #/models/v1beta1.Capabilities: Model is defined but is not used: v1beta1.Capabilities
    #/models/v1beta1.ContainerManifest: Model is defined but is not used: v1beta1.ContainerManifest
    #/models/v1beta1.EmptyDirVolumeSource: Model is defined but is not used: v1beta1.EmptyDirVolumeSource
    #/models/v1beta1.ExecAction: Model is defined but is not used: v1beta1.ExecAction
    #/models/v1beta1.GCEPersistentDiskVolumeSource: Model is defined but is not used: v1beta1.GCEPersistentDiskVolumeSource
    #/models/v1beta1.GitRepoVolumeSource: Model is defined but is not used: v1beta1.GitRepoVolumeSource
    #/models/v1beta1.HTTPGetAction: Model is defined but is not used: v1beta1.HTTPGetAction
    #/models/v1beta1.Handler: Model is defined but is not used: v1beta1.Handler
    #/models/v1beta1.HostPathVolumeSource: Model is defined but is not used: v1beta1.HostPathVolumeSource
    #/models/v1beta1.Lifecycle: Model is defined but is not used: v1beta1.Lifecycle
    #/models/v1beta1.LimitRangeSpec: Model is defined but is not used: v1beta1.LimitRangeSpec
    #/models/v1beta1.LivenessProbe: Model is defined but is not used: v1beta1.LivenessProbe
    #/models/v1beta1.Minion.labels: Model is defined but is not used: v1beta1.Minion.labels
    #/models/v1beta1.Namespace.labels: Model is defined but is not used: v1beta1.Namespace.labels
    #/models/v1beta1.NamespaceSpec: Model is defined but is not used: v1beta1.NamespaceSpec
    #/models/v1beta1.NamespaceStatus: Model is defined but is not used: v1beta1.NamespaceStatus
    #/models/v1beta1.NodeResources: Model is defined but is not used: v1beta1.NodeResources
    #/models/v1beta1.NodeStatus: Model is defined but is not used: v1beta1.NodeStatus
    #/models/v1beta1.NodeSystemInfo: Model is defined but is not used: v1beta1.NodeSystemInfo
    #/models/v1beta1.ObjectReference: Model is defined but is not used: v1beta1.ObjectReference
    #/models/v1beta1.Pod.labels: Model is defined but is not used: v1beta1.Pod.labels
    #/models/v1beta1.Pod.nodeSelector: Model is defined but is not used: v1beta1.Pod.nodeSelector
    #/models/v1beta1.PodState: Model is defined but is not used: v1beta1.PodState
    #/models/v1beta1.PodTemplate: Model is defined but is not used: v1beta1.PodTemplate
    #/models/v1beta1.PodTemplate.annotations: Model is defined but is not used: v1beta1.PodTemplate.annotations
    #/models/v1beta1.PodTemplate.labels: Model is defined but is not used: v1beta1.PodTemplate.labels
    #/models/v1beta1.PodTemplate.nodeSelector: Model is defined but is not used: v1beta1.PodTemplate.nodeSelector
    #/models/v1beta1.ReplicationController.labels: Model is defined but is not used: v1beta1.ReplicationController.labels
    #/models/v1beta1.ReplicationControllerState: Model is defined but is not used: v1beta1.ReplicationControllerState
    #/models/v1beta1.ReplicationControllerState.replicaSelector: Model is defined but is not used: v1beta1.ReplicationControllerState.replicaSelector
    #/models/v1beta1.ResourceQuotaSpec: Model is defined but is not used: v1beta1.ResourceQuotaSpec
    #/models/v1beta1.ResourceQuotaStatus: Model is defined but is not used: v1beta1.ResourceQuotaStatus
    #/models/v1beta1.ResourceRequirements: Model is defined but is not used: v1beta1.ResourceRequirements
    #/models/v1beta1.RestartPolicy: Model is defined but is not used: v1beta1.RestartPolicy
    #/models/v1beta1.RestartPolicyAlways: Model is defined but is not used: v1beta1.RestartPolicyAlways
    #/models/v1beta1.RestartPolicyNever: Model is defined but is not used: v1beta1.RestartPolicyNever
    #/models/v1beta1.RestartPolicyOnFailure: Model is defined but is not used: v1beta1.RestartPolicyOnFailure
    #/models/v1beta1.Secret.data: Model is defined but is not used: v1beta1.Secret.data
    #/models/v1beta1.SecretVolumeSource: Model is defined but is not used: v1beta1.SecretVolumeSource
    #/models/v1beta1.Service.labels: Model is defined but is not used: v1beta1.Service.labels
    #/models/v1beta1.Service.selector: Model is defined but is not used: v1beta1.Service.selector
    #/models/v1beta1.TCPSocketAction: Model is defined but is not used: v1beta1.TCPSocketAction
    #/models/v1beta1.VolumeSource: Model is defined but is not used: v1beta1.VolumeSource

  API Declaration (/api/v1beta2) Errors:

    #/models/v1beta2.Container/properties/command/items/$ref: Model could not be resolved: string
    #/models/v1beta2.Endpoints/properties/endpoints/items/$ref: Model could not be resolved: string
    #/models/v1beta2.ExecAction/properties/command/items/$ref: Model could not be resolved: string
    #/models/v1beta2.Service/properties/publicIPs/items/$ref: Model could not be resolved: string
    #/apis/9/path: API requires path parameter but it is not defined: path:*
    #/apis/9/path: API requires path parameter but it is not defined: path:*
    #/apis/9/path: API requires path parameter but it is not defined: path:*
    #/apis/9/path: API requires path parameter but it is not defined: path:*
    #/apis/12/path: API requires path parameter but it is not defined: name
    #/apis/17/path: API requires path parameter but it is not defined: path:*
    #/apis/17/path: API requires path parameter but it is not defined: path:*
    #/apis/17/path: API requires path parameter but it is not defined: path:*
    #/apis/17/path: API requires path parameter but it is not defined: path:*
    #/apis/18/path: API requires path parameter but it is not defined: path:*
    #/apis/18/path: API requires path parameter but it is not defined: path:*
    #/apis/18/path: API requires path parameter but it is not defined: path:*
    #/apis/18/path: API requires path parameter but it is not defined: path:*
    #/apis/24/path: API requires path parameter but it is not defined: path:*
    #/apis/24/path: API requires path parameter but it is not defined: path:*
    #/apis/24/path: API requires path parameter but it is not defined: path:*
    #/apis/24/path: API requires path parameter but it is not defined: path:*

  API Declaration (/api/v1beta2) Warnings:

    #/models/v1beta2.Capabilities: Model is defined but is not used: v1beta2.Capabilities
    #/models/v1beta2.ContainerManifest: Model is defined but is not used: v1beta2.ContainerManifest
    #/models/v1beta2.EmptyDirVolumeSource: Model is defined but is not used: v1beta2.EmptyDirVolumeSource
    #/models/v1beta2.ExecAction: Model is defined but is not used: v1beta2.ExecAction
    #/models/v1beta2.GCEPersistentDiskVolumeSource: Model is defined but is not used: v1beta2.GCEPersistentDiskVolumeSource
    #/models/v1beta2.GitRepoVolumeSource: Model is defined but is not used: v1beta2.GitRepoVolumeSource
    #/models/v1beta2.HTTPGetAction: Model is defined but is not used: v1beta2.HTTPGetAction
    #/models/v1beta2.Handler: Model is defined but is not used: v1beta2.Handler
    #/models/v1beta2.HostPathVolumeSource: Model is defined but is not used: v1beta2.HostPathVolumeSource
    #/models/v1beta2.Lifecycle: Model is defined but is not used: v1beta2.Lifecycle
    #/models/v1beta2.LimitRangeSpec: Model is defined but is not used: v1beta2.LimitRangeSpec
    #/models/v1beta2.LivenessProbe: Model is defined but is not used: v1beta2.LivenessProbe
    #/models/v1beta2.Minion.labels: Model is defined but is not used: v1beta2.Minion.labels
    #/models/v1beta2.Namespace.labels: Model is defined but is not used: v1beta2.Namespace.labels
    #/models/v1beta2.NamespaceSpec: Model is defined but is not used: v1beta2.NamespaceSpec
    #/models/v1beta2.NamespaceStatus: Model is defined but is not used: v1beta2.NamespaceStatus
    #/models/v1beta2.NodeResources: Model is defined but is not used: v1beta2.NodeResources
    #/models/v1beta2.NodeStatus: Model is defined but is not used: v1beta2.NodeStatus
    #/models/v1beta2.NodeSystemInfo: Model is defined but is not used: v1beta2.NodeSystemInfo
    #/models/v1beta2.ObjectReference: Model is defined but is not used: v1beta2.ObjectReference
    #/models/v1beta2.Pod.labels: Model is defined but is not used: v1beta2.Pod.labels
    #/models/v1beta2.Pod.nodeSelector: Model is defined but is not used: v1beta2.Pod.nodeSelector
    #/models/v1beta2.PodState: Model is defined but is not used: v1beta2.PodState
    #/models/v1beta2.PodTemplate: Model is defined but is not used: v1beta2.PodTemplate
    #/models/v1beta2.PodTemplate.annotations: Model is defined but is not used: v1beta2.PodTemplate.annotations
    #/models/v1beta2.PodTemplate.labels: Model is defined but is not used: v1beta2.PodTemplate.labels
    #/models/v1beta2.PodTemplate.nodeSelector: Model is defined but is not used: v1beta2.PodTemplate.nodeSelector
    #/models/v1beta2.ReplicationController.labels: Model is defined but is not used: v1beta2.ReplicationController.labels
    #/models/v1beta2.ReplicationControllerState: Model is defined but is not used: v1beta2.ReplicationControllerState
    #/models/v1beta2.ReplicationControllerState.replicaSelector: Model is defined but is not used: v1beta2.ReplicationControllerState.replicaSelector
    #/models/v1beta2.ResourceQuotaSpec: Model is defined but is not used: v1beta2.ResourceQuotaSpec
    #/models/v1beta2.ResourceQuotaStatus: Model is defined but is not used: v1beta2.ResourceQuotaStatus
    #/models/v1beta2.ResourceRequirements: Model is defined but is not used: v1beta2.ResourceRequirements
    #/models/v1beta2.RestartPolicy: Model is defined but is not used: v1beta2.RestartPolicy
    #/models/v1beta2.RestartPolicyAlways: Model is defined but is not used: v1beta2.RestartPolicyAlways
    #/models/v1beta2.RestartPolicyNever: Model is defined but is not used: v1beta2.RestartPolicyNever
    #/models/v1beta2.RestartPolicyOnFailure: Model is defined but is not used: v1beta2.RestartPolicyOnFailure
    #/models/v1beta2.Secret.data: Model is defined but is not used: v1beta2.Secret.data
    #/models/v1beta2.SecretVolumeSource: Model is defined but is not used: v1beta2.SecretVolumeSource
    #/models/v1beta2.Service.labels: Model is defined but is not used: v1beta2.Service.labels
    #/models/v1beta2.Service.selector: Model is defined but is not used: v1beta2.Service.selector
    #/models/v1beta2.TCPSocketAction: Model is defined but is not used: v1beta2.TCPSocketAction
    #/models/v1beta2.VolumeSource: Model is defined but is not used: v1beta2.VolumeSource

  API Declaration (/api/v1beta3) Errors:

    #/models/v1beta3.Container/properties/command/items/$ref: Model could not be resolved: string
    #/models/v1beta3.ExecAction/properties/command/items/$ref: Model could not be resolved: string
    #/models/v1beta3.ServiceSpec/properties/publicIPs/items/$ref: Model could not be resolved: string
    #/apis/5/path: API requires path parameter but it is not defined: path:*
    #/apis/5/path: API requires path parameter but it is not defined: path:*
    #/apis/5/path: API requires path parameter but it is not defined: path:*
    #/apis/5/path: API requires path parameter but it is not defined: path:*
    #/apis/13/path: API requires path parameter but it is not defined: path:*
    #/apis/13/path: API requires path parameter but it is not defined: path:*
    #/apis/13/path: API requires path parameter but it is not defined: path:*
    #/apis/13/path: API requires path parameter but it is not defined: path:*
    #/apis/43/path: API requires path parameter but it is not defined: path:*
    #/apis/43/path: API requires path parameter but it is not defined: path:*
    #/apis/43/path: API requires path parameter but it is not defined: path:*
    #/apis/43/path: API requires path parameter but it is not defined: path:*
    #/apis/55/path: API requires path parameter but it is not defined: name

  API Declaration (/api/v1beta3) Warnings:

    #/models/v1beta3.Capabilities: Model is defined but is not used: v1beta3.Capabilities
    #/models/v1beta3.EventSource: Model is defined but is not used: v1beta3.EventSource
    #/models/v1beta3.ExecAction: Model is defined but is not used: v1beta3.ExecAction
    #/models/v1beta3.HTTPGetAction: Model is defined but is not used: v1beta3.HTTPGetAction
    #/models/v1beta3.Handler: Model is defined but is not used: v1beta3.Handler
    #/models/v1beta3.Lifecycle: Model is defined but is not used: v1beta3.Lifecycle
    #/models/v1beta3.LimitRangeSpec: Model is defined but is not used: v1beta3.LimitRangeSpec
    #/models/v1beta3.NamespaceSpec: Model is defined but is not used: v1beta3.NamespaceSpec
    #/models/v1beta3.NamespaceStatus: Model is defined but is not used: v1beta3.NamespaceStatus
    #/models/v1beta3.NodeSpec: Model is defined but is not used: v1beta3.NodeSpec
    #/models/v1beta3.NodeStatus: Model is defined but is not used: v1beta3.NodeStatus
    #/models/v1beta3.NodeSystemInfo: Model is defined but is not used: v1beta3.NodeSystemInfo
    #/models/v1beta3.ObjectReference: Model is defined but is not used: v1beta3.ObjectReference
    #/models/v1beta3.PodSpec: Model is defined but is not used: v1beta3.PodSpec
    #/models/v1beta3.PodSpec.nodeSelector: Model is defined but is not used: v1beta3.PodSpec.nodeSelector
    #/models/v1beta3.PodStatus: Model is defined but is not used: v1beta3.PodStatus
    #/models/v1beta3.PodTemplateSpec: Model is defined but is not used: v1beta3.PodTemplateSpec
    #/models/v1beta3.Probe: Model is defined but is not used: v1beta3.Probe
    #/models/v1beta3.ReplicationControllerSpec: Model is defined but is not used: v1beta3.ReplicationControllerSpec
    #/models/v1beta3.ReplicationControllerSpec.selector: Model is defined but is not used: v1beta3.ReplicationControllerSpec.selector
    #/models/v1beta3.ReplicationControllerStatus: Model is defined but is not used: v1beta3.ReplicationControllerStatus
    #/models/v1beta3.ResourceQuotaSpec: Model is defined but is not used: v1beta3.ResourceQuotaSpec
    #/models/v1beta3.ResourceQuotaStatus: Model is defined but is not used: v1beta3.ResourceQuotaStatus
    #/models/v1beta3.ResourceRequirements: Model is defined but is not used: v1beta3.ResourceRequirements
    #/models/v1beta3.RestartPolicy: Model is defined but is not used: v1beta3.RestartPolicy
    #/models/v1beta3.RestartPolicyAlways: Model is defined but is not used: v1beta3.RestartPolicyAlways
    #/models/v1beta3.RestartPolicyNever: Model is defined but is not used: v1beta3.RestartPolicyNever
    #/models/v1beta3.RestartPolicyOnFailure: Model is defined but is not used: v1beta3.RestartPolicyOnFailure
    #/models/v1beta3.Secret.data: Model is defined but is not used: v1beta3.Secret.data
    #/models/v1beta3.ServiceSpec: Model is defined but is not used: v1beta3.ServiceSpec
    #/models/v1beta3.ServiceSpec.selector: Model is defined but is not used: v1beta3.ServiceSpec.selector
    #/models/v1beta3.ServiceStatus: Model is defined but is not used: v1beta3.ServiceStatus
    #/models/v1beta3.TCPSocketAction: Model is defined but is not used: v1beta3.TCPSocketAction
```

Will try to fix them one by one :)

**Comment by nikhiljindal** [comment] 2015-03-17 05:26
Filed https://github.com/apigee-127/swagger-tools/issues/182 for the "Model could not be resolved: string" error.

**Comment by bgrant0607** [comment] 2015-03-17 05:34
IMO, a reasonable fix to the "path:*" messages would be to not use go-restful for proxy and redirect, as I don't consider them part of the API.

**Comment by bgrant0607** [comment] 2015-03-17 05:36
"$ref" used for string -- sounds like instances of #3757.

**Comment by bgrant0607** [comment] 2015-03-17 05:39
As for all of the "Model is defined but not used" warnings -- that's #3756.

**Comment by nikhiljindal** [comment] 2015-03-25 21:31
All errors except the "API requires path parameter but it is not defined" should now be fixed by
https://github.com/GoogleCloudPlatform/kubernetes/pull/5938

**Comment by brendandburns** [comment] 2015-03-27 05:28
I'm seeing more errors (for v1beta1 at least), https://github.com/emicklei/go-restful/pull/199 fixes part of it.

**Comment by brendandburns** [comment] 2015-03-27 05:32
Concretely, I'm currently seeing:

```
  API Declaration (/api/v1beta3) Errors:

    #/resourcePath: Resource path could not be resolved: /api/v1beta3
    #/models/v1beta3.Binding/properties/annotations/$ref: Model could not be resolved: v1beta3.ObjectMeta.annotations
    #/models/v1beta3.Binding/properties/labels/$ref: Model could not be resolved: v1beta3.ObjectMeta.labels
    #/models/v1beta3.Endpoints/properties/annotations/$ref: Model could not be resolved: v1beta3.ObjectMeta.annotations
    #/models/v1beta3.Endpoints/properties/labels/$ref: Model could not be resolved: v1beta3.ObjectMeta.labels
    #/models/v1beta3.Event/properties/annotations/$ref: Model could not be resolved: v1beta3.ObjectMeta.annotations
    #/models/v1beta3.Event/properties/labels/$ref: Model could not be resolved: v1beta3.ObjectMeta.labels
    #/models/v1beta3.LimitRange/properties/annotations/$ref: Model could not be resolved: v1beta3.ObjectMeta.annotations
    #/models/v1beta3.LimitRange/properties/labels/$ref: Model could not be resolved: v1beta3.ObjectMeta.labels
    #/models/v1beta3.LimitRangeItem/properties/max/$ref: Model could not be resolved: v1beta3.ResourceList
    #/models/v1beta3.LimitRangeItem/properties/min/$ref: Model could not be resolved: v1beta3.ResourceList
    #/models/v1beta3.Namespace/properties/annotations/$ref: Model could not be resolved: v1beta3.ObjectMeta.annotations
    #/models/v1beta3.Namespace/properties/labels/$ref: Model could not be resolved: v1beta3.ObjectMeta.labels
    #/models/v1beta3.Node/properties/annotations/$ref: Model could not be resolved: v1beta3.ObjectMeta.annotations
    #/models/v1beta3.Node/properties/labels/$ref: Model could not be resolved: v1beta3.ObjectMeta.labels
    #/models/v1beta3.NodeStatus/properties/capacity/$ref: Model could not be resolved: v1beta3.ResourceList
    #/models/v1beta3.Pod/properties/annotations/$ref: Model could not be resolved: v1beta3.ObjectMeta.annotations
    #/models/v1beta3.Pod/properties/labels/$ref: Model could not be resolved: v1beta3.ObjectMeta.labels
    #/models/v1beta3.PodTemplateSpec/properties/annotations/$ref: Model could not be resolved: v1beta3.ObjectMeta.annotations
    #/models/v1beta3.PodTemplateSpec/properties/labels/$ref: Model could not be resolved: v1beta3.ObjectMeta.labels
    #/models/v1beta3.ReplicationController/properties/annotations/$ref: Model could not be resolved: v1beta3.ObjectMeta.annotations
    #/models/v1beta3.ReplicationController/properties/labels/$ref: Model could not be resolved: v1beta3.ObjectMeta.labels
    #/models/v1beta3.ResourceQuota/properties/annotations/$ref: Model could not be resolved: v1beta3.ObjectMeta.annotations
    #/models/v1beta3.ResourceQuota/properties/labels/$ref: Model could not be resolved: v1beta3.ObjectMeta.labels
    #/models/v1beta3.ResourceQuotaSpec/properties/hard/$ref: Model could not be resolved: v1beta3.ResourceList
    #/models/v1beta3.ResourceQuotaStatus/properties/hard/$ref: Model could not be resolved: v1beta3.ResourceList
    #/models/v1beta3.ResourceQuotaStatus/properties/used/$ref: Model could not be resolved: v1beta3.ResourceList
    #/models/v1beta3.ResourceRequirements/properties/limits/$ref: Model could not be resolved: v1beta3.ResourceList
    #/models/v1beta3.ResourceRequirements/properties/requests/$ref: Model could not be resolved: v1beta3.ResourceList
    #/models/v1beta3.Secret/properties/annotations/$ref: Model could not be resolved: v1beta3.ObjectMeta.annotations
    #/models/v1beta3.Secret/properties/labels/$ref: Model could not be resolved: v1beta3.ObjectMeta.labels
    #/models/v1beta3.Service/properties/annotations/$ref: Model could not be resolved: v1beta3.ObjectMeta.annotations
    #/models/v1beta3.Service/properties/labels/$ref: Model could not be resolved: v1beta3.ObjectMeta.labels
    #/models/v1beta3.Volume/properties/emptyDir/$ref: Model could not be resolved: v1beta3.EmptyDirVolumeSource
    #/models/v1beta3.Volume/properties/gcePersistentDisk/$ref: Model could not be resolved: v1beta3.GCEPersistentDiskVolumeSource
    #/models/v1beta3.Volume/properties/gitRepo/$ref: Model could not be resolved: v1beta3.GitRepoVolumeSource
    #/models/v1beta3.Volume/properties/hostPath/$ref: Model could not be resolved: v1beta3.HostPathVolumeSource
    #/models/v1beta3.Volume/properties/nfs/$ref: Model could not be resolved: v1beta3.NFSVolumeSource
    #/models/v1beta3.Volume/properties/secret/$ref: Model could not be resolved: v1beta3.SecretVolumeSource
    #/apis/30/path: API requires path parameter but it is not defined: path:*
    #/apis/30/path: API requires path parameter but it is not defined: path:*
    #/apis/30/path: API requires path parameter but it is not defined: path:*
    #/apis/30/path: API requires path parameter but it is not defined: path:*
    #/apis/37/path: API requires path parameter but it is not defined: path:*
    #/apis/37/path: API requires path parameter but it is not defined: path:*
    #/apis/37/path: API requires path parameter but it is not defined: path:*
    #/apis/37/path: API requires path parameter but it is not defined: path:*
    #/apis/41/path: API requires path parameter but it is not defined: name
    #/apis/67/path: API requires path parameter but it is not defined: path:*
    #/apis/67/path: API requires path parameter but it is not defined: path:*
    #/apis/67/path: API requires path parameter but it is not defined: path:*
    #/apis/67/path: API requires path parameter but it is not defined: path:*
```

**Comment by brendandburns** [comment] 2015-03-27 05:32
The annotations and labels are due to not handling generic maps correctly, I need to see what the right Swagger thing is to do there...

**Comment by brendandburns** [comment] 2015-03-27 05:53
with emicklei/go-restful#199, we are down to:

```
    #/models/v1beta3.Volume/properties/emptyDir/$ref: Model could not be resolved: v1beta3.EmptyDirVolumeSource
    #/models/v1beta3.Volume/properties/gcePersistentDisk/$ref: Model could not be resolved: v1beta3.GCEPersistentDiskVolumeSource
    #/models/v1beta3.Volume/properties/gitRepo/$ref: Model could not be resolved: v1beta3.GitRepoVolumeSource
    #/models/v1beta3.Volume/properties/hostPath/$ref: Model could not be resolved: v1beta3.HostPathVolumeSource
    #/models/v1beta3.Volume/properties/nfs/$ref: Model could not be resolved: v1beta3.NFSVolumeSource
    #/models/v1beta3.Volume/properties/secret/$ref: Model could not be resolved: v1beta3.SecretVolumeSource
    #/apis/30/path: API requires path parameter but it is not defined: path:*
    #/apis/30/path: API requires path parameter but it is not defined: path:*
    #/apis/30/path: API requires path parameter but it is not defined: path:*
    #/apis/30/path: API requires path parameter but it is not defined: path:*
    #/apis/37/path: API requires path parameter but it is not defined: path:*
    #/apis/37/path: API requires path parameter but it is not defined: path:*
    #/apis/37/path: API requires path parameter but it is not defined: path:*
    #/apis/37/path: API requires path parameter but it is not defined: path:*
    #/apis/41/path: API requires path parameter but it is not defined: name
    #/apis/67/path: API requires path parameter but it is not defined: path:*
    #/apis/67/path: API requires path parameter but it is not defined: path:*
    #/apis/67/path: API requires path parameter but it is not defined: path:*
    #/apis/67/path: API requires path parameter but it is not defined: path:*
```

I think the remaining Models aren't there because they are pointers...  I'll look into fixing that tomorrow.

**Comment by bgrant0607** [comment] 2015-03-27 06:18
ResourceList (despite the name) is also a map.

**Comment by brendandburns** [comment] 2015-03-28 04:48
Ok, with the combination of https://github.com/emicklei/go-restful/pull/199 https://github.com/emicklei/go-restful/pull/200 and #6117, the swagger API passes the swagger-tools validation.

**Comment by bgrant0607** [comment] 2015-03-28 06:20
Great, thanks!

**Comment by brendandburns** [comment] 2015-03-30 18:17
v1beta3 now passes ```swagger-tools validate ...```  Closing this issue.

**Closed by brendandburns** 2015-03-30 18:17 UTC
Labels: kind/bug, priority/P1, team/UX
