### ISSUE TITLE
Flaky e2e test: Services should be able to change the type and nodeport settings of a service

### ISSUE THREAD

**Issue by quinton-hoole** [GoogleCloudPlatform/kubernetes#8892] opened 2015-05-27 22:20 UTC
This test is failing intermittently on our GCE-based continuous integration system:

(Failed 13 times in the last 30 runs. Stability: 56 %)

Test log below.

@justinsb could you perhaps repro and fix?

Services should be able to change the type and nodeport settings of a service

/go/src/github.com/GoogleCloudPlatform/kubernetes/_output/dockerized/go/src/github.com/GoogleCloudPlatform/kubernetes/test/e2e/service.go:521
Expected error:
    <*errors.errorString | 0xc2083a54e0>: {
        s: "service mutability-service-test in namespace e2e-tests-service-0-dc3d5c9e-660b-4ebb-a87e-e65fd200ce89 doesn't have a LoadBalancer ingress point after 240.00 seconds",
    }
    service mutability-service-test in namespace e2e-tests-service-0-dc3d5c9e-660b-4ebb-a87e-e65fd200ce89 doesn't have a LoadBalancer ingress point after 240.00 seconds
not to have occurred

**Comment by quinton-hoole** [comment] 2015-05-27 22:26
Some more detailed logs:

Services 
  should be able to change the type and nodeport settings of a service
  /go/src/github.com/GoogleCloudPlatform/kubernetes/_output/dockerized/go/src/github.com/GoogleCloudPlatform/kubernetes/test/e2e/service.go:521
[BeforeEach] Services
  /go/src/github.com/GoogleCloudPlatform/kubernetes/_output/dockerized/go/src/github.com/GoogleCloudPlatform/kubernetes/test/e2e/service.go:59
>>> testContext.KubeConfig: /var/lib/jenkins/jobs/kubernetes-e2e-gce/workspace/.kube/config
STEP: Building a namespace api objects
[It] should be able to change the type and nodeport settings of a service
  /go/src/github.com/GoogleCloudPlatform/kubernetes/_output/dockerized/go/src/github.com/GoogleCloudPlatform/kubernetes/test/e2e/service.go:521
STEP: creating service mutability-service-test with type unspecified in namespace e2e-tests-service-0-dc3d5c9e-660b-4ebb-a87e-e65fd200ce89
STEP: creating pod to be part of service mutability-service-test
INFO: Waiting up to 5m0s for pod mutability-service-test-1 status to be running
INFO: Waiting for pod 'mutability-service-test-1' in namespace 'e2e-tests-service-0-dc3d5c9e-660b-4ebb-a87e-e65fd200ce89' status to be '"running"' (found phase: '"Pending"', readiness: false) (5.043481ms)
STEP: changing service mutability-service-test to type=NodePort
STEP: hitting the pod through the service's NodePort
STEP: Checking reachability of http://162.222.179.246:31098
STEP: Got error waiting for reachability of http://162.222.179.246:31098: Get http://162.222.179.246:31098: dial tcp 162.222.179.246:31098: connection refused
STEP: Got error waiting for reachability of http://162.222.179.246:31098: Get http://162.222.179.246:31098: read tcp 162.222.179.246:31098: connection reset by peer
STEP: changing service mutability-service-test to type=LoadBalancer
STEP: waiting up to 4m0s for service mutability-service-test in namespace e2e-tests-service-0-dc3d5c9e-660b-4ebb-a87e-e65fd200ce89 to have a LoadBalancer ingress point
INFO: Waiting for service mutability-service-test in namespace e2e-tests-service-0-dc3d5c9e-660b-4ebb-a87e-e65fd200ce89 to have a LoadBalancer ingress point (2.949619ms)
INFO: Waiting for service mutability-service-test in namespace e2e-tests-service-0-dc3d5c9e-660b-4ebb-a87e-e65fd200ce89 to have a LoadBalancer ingress point (5.006999895s)
INFO: Waiting for service mutability-service-test in namespace e2e-tests-service-0-dc3d5c9e-660b-4ebb-a87e-e65fd200ce89 to have a LoadBalancer ingress point (10.011868664s)
INFO: Waiting for service mutability-service-test in namespace e2e-tests-service-0-dc3d5c9e-660b-4ebb-a87e-e65fd200ce89 to have a LoadBalancer ingress point (15.016960049s)
INFO: Waiting for service mutability-service-test in namespace e2e-tests-service-0-dc3d5c9e-660b-4ebb-a87e-e65fd200ce89 to have a LoadBalancer ingress point (20.02136764s)
INFO: Waiting for service mutability-service-test in namespace e2e-tests-service-0-dc3d5c9e-660b-4ebb-a87e-e65fd200ce89 to have a LoadBalancer ingress point (25.024725263s)
INFO: Waiting for service mutability-service-test in namespace e2e-tests-service-0-dc3d5c9e-660b-4ebb-a87e-e65fd200ce89 to have a LoadBalancer ingress point (30.028584608s)
INFO: Waiting for service mutability-service-test in namespace e2e-tests-service-0-dc3d5c9e-660b-4ebb-a87e-e65fd200ce89 to have a LoadBalancer ingress point (35.039414009s)
INFO: Waiting for service mutability-service-test in namespace e2e-tests-service-0-dc3d5c9e-660b-4ebb-a87e-e65fd200ce89 to have a LoadBalancer ingress point (40.043164677s)
INFO: Waiting for service mutability-service-test in namespace e2e-tests-service-0-dc3d5c9e-660b-4ebb-a87e-e65fd200ce89 to have a LoadBalancer ingress point (45.046707835s)
INFO: Waiting for service mutability-service-test in namespace e2e-tests-service-0-dc3d5c9e-660b-4ebb-a87e-e65fd200ce89 to have a LoadBalancer ingress point (50.050804195s)
INFO: Waiting for service mutability-service-test in namespace e2e-tests-service-0-dc3d5c9e-660b-4ebb-a87e-e65fd200ce89 to have a LoadBalancer ingress point (55.054344138s)
INFO: Waiting for service mutability-service-test in namespace e2e-tests-service-0-dc3d5c9e-660b-4ebb-a87e-e65fd200ce89 to have a LoadBalancer ingress point (1m0.058300223s)
INFO: Waiting for service mutability-service-test in namespace e2e-tests-service-0-dc3d5c9e-660b-4ebb-a87e-e65fd200ce89 to have a LoadBalancer ingress point (1m5.062060196s)
INFO: Waiting for service mutability-service-test in namespace e2e-tests-service-0-dc3d5c9e-660b-4ebb-a87e-e65fd200ce89 to have a LoadBalancer ingress point (1m10.066492908s)
INFO: Waiting for service mutability-service-test in namespace e2e-tests-service-0-dc3d5c9e-660b-4ebb-a87e-e65fd200ce89 to have a LoadBalancer ingress point (1m15.070328839s)
INFO: Waiting for service mutability-service-test in namespace e2e-tests-service-0-dc3d5c9e-660b-4ebb-a87e-e65fd200ce89 to have a LoadBalancer ingress point (1m20.074905936s)
INFO: Waiting for service mutability-service-test in namespace e2e-tests-service-0-dc3d5c9e-660b-4ebb-a87e-e65fd200ce89 to have a LoadBalancer ingress point (1m25.078590877s)
INFO: Waiting for service mutability-service-test in namespace e2e-tests-service-0-dc3d5c9e-660b-4ebb-a87e-e65fd200ce89 to have a LoadBalancer ingress point (1m30.082329596s)
INFO: Waiting for service mutability-service-test in namespace e2e-tests-service-0-dc3d5c9e-660b-4ebb-a87e-e65fd200ce89 to have a LoadBalancer ingress point (1m35.086238996s)
INFO: Waiting for service mutability-service-test in namespace e2e-tests-service-0-dc3d5c9e-660b-4ebb-a87e-e65fd200ce89 to have a LoadBalancer ingress point (1m40.09251103s)
INFO: Waiting for service mutability-service-test in namespace e2e-tests-service-0-dc3d5c9e-660b-4ebb-a87e-e65fd200ce89 to have a LoadBalancer ingress point (1m45.096378126s)
INFO: Waiting for service mutability-service-test in namespace e2e-tests-service-0-dc3d5c9e-660b-4ebb-a87e-e65fd200ce89 to have a LoadBalancer ingress point (1m50.100971174s)
INFO: Waiting for service mutability-service-test in namespace e2e-tests-service-0-dc3d5c9e-660b-4ebb-a87e-e65fd200ce89 to have a LoadBalancer ingress point (1m55.104971597s)
INFO: Waiting for service mutability-service-test in namespace e2e-tests-service-0-dc3d5c9e-660b-4ebb-a87e-e65fd200ce89 to have a LoadBalancer ingress point (2m0.108758672s)
INFO: Waiting for service mutability-service-test in namespace e2e-tests-service-0-dc3d5c9e-660b-4ebb-a87e-e65fd200ce89 to have a LoadBalancer ingress point (2m5.112906985s)
INFO: Waiting for service mutability-service-test in namespace e2e-tests-service-0-dc3d5c9e-660b-4ebb-a87e-e65fd200ce89 to have a LoadBalancer ingress point (2m10.116651437s)
INFO: Waiting for service mutability-service-test in namespace e2e-tests-service-0-dc3d5c9e-660b-4ebb-a87e-e65fd200ce89 to have a LoadBalancer ingress point (2m15.120604242s)
INFO: Waiting for service mutability-service-test in namespace e2e-tests-service-0-dc3d5c9e-660b-4ebb-a87e-e65fd200ce89 to have a LoadBalancer ingress point (2m20.12481699s)
INFO: Waiting for service mutability-service-test in namespace e2e-tests-service-0-dc3d5c9e-660b-4ebb-a87e-e65fd200ce89 to have a LoadBalancer ingress point (2m25.12856499s)
INFO: Waiting for service mutability-service-test in namespace e2e-tests-service-0-dc3d5c9e-660b-4ebb-a87e-e65fd200ce89 to have a LoadBalancer ingress point (2m30.132347728s)
INFO: Waiting for service mutability-service-test in namespace e2e-tests-service-0-dc3d5c9e-660b-4ebb-a87e-e65fd200ce89 to have a LoadBalancer ingress point (2m35.136366549s)
INFO: Waiting for service mutability-service-test in namespace e2e-tests-service-0-dc3d5c9e-660b-4ebb-a87e-e65fd200ce89 to have a LoadBalancer ingress point (2m40.140066401s)
INFO: Waiting for service mutability-service-test in namespace e2e-tests-service-0-dc3d5c9e-660b-4ebb-a87e-e65fd200ce89 to have a LoadBalancer ingress point (2m45.143914838s)
INFO: Waiting for service mutability-service-test in namespace e2e-tests-service-0-dc3d5c9e-660b-4ebb-a87e-e65fd200ce89 to have a LoadBalancer ingress point (2m50.14782781s)
INFO: Waiting for service mutability-service-test in namespace e2e-tests-service-0-dc3d5c9e-660b-4ebb-a87e-e65fd200ce89 to have a LoadBalancer ingress point (2m55.152123095s)
INFO: Waiting for service mutability-service-test in namespace e2e-tests-service-0-dc3d5c9e-660b-4ebb-a87e-e65fd200ce89 to have a LoadBalancer ingress point (3m0.155773222s)
INFO: Waiting for service mutability-service-test in namespace e2e-tests-service-0-dc3d5c9e-660b-4ebb-a87e-e65fd200ce89 to have a LoadBalancer ingress point (3m5.159708338s)
INFO: Waiting for service mutability-service-test in namespace e2e-tests-service-0-dc3d5c9e-660b-4ebb-a87e-e65fd200ce89 to have a LoadBalancer ingress point (3m10.163799009s)
INFO: Waiting for service mutability-service-test in namespace e2e-tests-service-0-dc3d5c9e-660b-4ebb-a87e-e65fd200ce89 to have a LoadBalancer ingress point (3m15.167514951s)
INFO: Waiting for service mutability-service-test in namespace e2e-tests-service-0-dc3d5c9e-660b-4ebb-a87e-e65fd200ce89 to have a LoadBalancer ingress point (3m20.171084581s)
INFO: Waiting for service mutability-service-test in namespace e2e-tests-service-0-dc3d5c9e-660b-4ebb-a87e-e65fd200ce89 to have a LoadBalancer ingress point (3m25.174967149s)
INFO: Waiting for service mutability-service-test in namespace e2e-tests-service-0-dc3d5c9e-660b-4ebb-a87e-e65fd200ce89 to have a LoadBalancer ingress point (3m30.17879221s)
INFO: Waiting for service mutability-service-test in namespace e2e-tests-service-0-dc3d5c9e-660b-4ebb-a87e-e65fd200ce89 to have a LoadBalancer ingress point (3m35.182992286s)
INFO: Waiting for service mutability-service-test in namespace e2e-tests-service-0-dc3d5c9e-660b-4ebb-a87e-e65fd200ce89 to have a LoadBalancer ingress point (3m40.186936793s)
INFO: Waiting for service mutability-service-test in namespace e2e-tests-service-0-dc3d5c9e-660b-4ebb-a87e-e65fd200ce89 to have a LoadBalancer ingress point (3m45.190814542s)
INFO: Waiting for service mutability-service-test in namespace e2e-tests-service-0-dc3d5c9e-660b-4ebb-a87e-e65fd200ce89 to have a LoadBalancer ingress point (3m50.194297847s)
INFO: Waiting for service mutability-service-test in namespace e2e-tests-service-0-dc3d5c9e-660b-4ebb-a87e-e65fd200ce89 to have a LoadBalancer ingress point (3m55.198159332s)
STEP: deleting pod mutability-service-test-1 in namespace e2e-tests-service-0-dc3d5c9e-660b-4ebb-a87e-e65fd200ce89
STEP: deleting service mutability-service-test in namespace e2e-tests-service-0-dc3d5c9e-660b-4ebb-a87e-e65fd200ce89
[AfterEach] Services
  /go/src/github.com/GoogleCloudPlatform/kubernetes/_output/dockerized/go/src/github.com/GoogleCloudPlatform/kubernetes/test/e2e/service.go:68
STEP: Destroying namespace e2e-tests-service-0-dc3d5c9e-660b-4ebb-a87e-e65fd200ce89
STEP: Destroying namespace e2e-tests-service-1-de3de2fd-4225-4382-bc6b-65e6b7835427

• Failure [255.794 seconds]
Services
/go/src/github.com/GoogleCloudPlatform/kubernetes/_output/dockerized/go/src/github.com/GoogleCloudPlatform/kubernetes/test/e2e/service.go:825
  should be able to change the type and nodeport settings of a service [It]
  /go/src/github.com/GoogleCloudPlatform/kubernetes/_output/dockerized/go/src/github.com/GoogleCloudPlatform/kubernetes/test/e2e/service.go:521

  Expected error:
      <*errors.errorString | 0xc2083a54e0>: {
          s: "service mutability-service-test in namespace e2e-tests-service-0-dc3d5c9e-660b-4ebb-a87e-e65fd200ce89 doesn't have a LoadBalancer ingress point after 240.00 seconds",
      }
      service mutability-service-test in namespace e2e-tests-service-0-dc3d5c9e-660b-4ebb-a87e-e65fd200ce89 doesn't have a LoadBalancer ingress point after 240.00 seconds
  not to have occurred

  /go/src/github.com/GoogleCloudPlatform/kubernetes/_output/dockerized/go/src/github.com/GoogleCloudPlatform/kubernetes/test/e2e/service.go:430
------------------------------

**Comment by justinsb** [comment] 2015-05-28 00:47
Looks like I shouldn't create such evil e2e tests.  I will try to reproduce & fix.

**Comment by justinsb** [comment] 2015-05-28 04:14
I have been unable (so far) to reproduce a single failure.  It might be that the timeout (4 minutes) is just too low, particularly if we hit a busy time for GCE.

#8887 adds events for load balancer errors (thanks brendan!)

#8892 logs events when the test fails, by bringin in framework

Hopefully we can both of these merged and this will shed some light on the issue.

**Comment by quinton-hoole** [comment] 2015-05-28 04:16
Thanks Justin.  I'll pull some system logs tomorrow from our clusters, which exhibit the symptom quite readily.

**Comment by justinsb** [comment] 2015-06-05 03:18
@quinton-hoole is this still happening?  Anything in the logs?

**Comment by quinton-hoole** [comment] 2015-06-05 05:24
Yes, it's still happening.  Sorry, I forgot to pull logs for you.  Will do tomorrow.  Assigning to myself :-)

**Comment by brendandburns** [comment] 2015-06-12 23:07
I believe that this is due to load balancer creation in GCE taking a long time.  Merged https://github.com/GoogleCloudPlatform/kubernetes/pull/9724 and I'm going to close this.  Will re-open if it re-occurs.

**Comment by erictune** [comment] 2015-07-07 19:31
Still flaky for me.

**Comment by quinton-hoole** [comment] 2015-07-07 20:18
@etune on our Jenkins CI, it has passed the last ~150 runs without a single failure - i.e. 100% success rate.  Is it perhaps something to do with your test environment?   What percentage failure rate are you seeing?

**Comment by quinton-hoole** [comment] 2015-07-07 20:19
@erictune ^^

**Comment by erictune** [comment] 2015-07-07 20:36
2 of 2 failing.

**Comment by justinsb** [comment] 2015-07-07 20:36
I would love to see log if you have them @erictune

**Comment by erictune** [comment] 2015-07-07 20:45
https://gist.github.com/erictune/19d96228c25609f0d20b

**Comment by justinsb** [comment] 2015-07-07 22:06
Ah!  NodePort on GCE requires you to open the firewall yourself (@erictune)

**Comment by quinton-hoole** [comment] 2015-07-07 22:12
@erictune For what it's worth, we saw one failure of this test on Jenkins just after my comment above.  The first one in quite a while.  Possibly some underlying GCE issue, but I've not yet had time to look into it in any further detail yet.  

<internal Jenkins> /kubernetes-e2e-gce/7459/testReport/junit/(root)/Kubernetes%20e2e%20suite/Services_should_be_able_to_change_the_type_and_nodeport_settings_of_a_service/history/

**Comment by quinton-hoole** [comment] 2015-07-08 00:49
@erictune did you solve your problem?

**Comment by alex-mohr** [comment] 2015-07-09 16:43
From http://kubekins.dls.corp.google.com/view/GKE/job/kubernetes-e2e-gke-staging-0.21/41/consoleText

Services
/go/src/github.com/GoogleCloudPlatform/kubernetes/_output/dockerized/go/src/github.com/GoogleCloudPlatform/kubernetes/test/e2e/service.go:792
  should be able to create a functioning external load balancer
  /go/src/github.com/GoogleCloudPlatform/kubernetes/_output/dockerized/go/src/github.com/GoogleCloudPlatform/kubernetes/test/e2e/service.go:282
------------------------------
S
------------------------------
Services 
  should be able to change the type and nodeport settings of a service
  /go/src/github.com/GoogleCloudPlatform/kubernetes/_output/dockerized/go/src/github.com/GoogleCloudPlatform/kubernetes/test/e2e/service.go:490
[BeforeEach] Services
  /go/src/github.com/GoogleCloudPlatform/kubernetes/_output/dockerized/go/src/github.com/GoogleCloudPlatform/kubernetes/test/e2e/service.go:57
>>> testContext.KubeConfig: /var/lib/jenkins/jobs/kubernetes-e2e-gke-staging-0.21/workspace/.kube/config
STEP: Building a namespace api objects
INFO: Waiting up to 2m0s for service account default to be provisioned in ns e2e-tests-service-0-rdy7v
INFO: Get service account default in ns e2e-tests-service-0-rdy7v failed, ignoring for 5s: serviceaccounts "default" not found
INFO: Service account default in ns e2e-tests-service-0-rdy7v with secrets found. (5.01782695s)
INFO: Waiting up to 2m0s for service account default to be provisioned in ns e2e-tests-service-1-c7plg
INFO: Get service account default in ns e2e-tests-service-1-c7plg failed, ignoring for 5s: serviceaccounts "default" not found
INFO: Service account default in ns e2e-tests-service-1-c7plg with secrets found. (5.005970206s)
[It] should be able to change the type and nodeport settings of a service
  /go/src/github.com/GoogleCloudPlatform/kubernetes/_output/dockerized/go/src/github.com/GoogleCloudPlatform/kubernetes/test/e2e/service.go:490
STEP: creating service mutability-service-test with type unspecified in namespace e2e-tests-service-0-rdy7v
STEP: creating pod to be part of service mutability-service-test
INFO: Pod name webserver: Found 0 pods out of 1
INFO: Pod name webserver: Found 1 pods out of 1
STEP: ensuring each pod is running
INFO: Waiting up to 5m0s for pod webserver-0joa5                                         status to be running
INFO: Found pod 'webserver-0joa5' on node 'gke-jenkins-gke-e2e-staging-0-21-7c5a0f5c-node-beo0'
STEP: trying to dial each unique pod
INFO: Controller webserver: Got non-empty result from replica 1 [webserver-0joa5]: "<pre>\n<a href=\"var/\">var/</a>\n<a href=\"sys/\">sys/</a>\n<a href=\".dockerenv\">.dockerenv</a>\n<a href=\"proc/\">proc/</a>\n<a href=\"etc/\">etc/</a>\n<a href=\".dockerinit\">.dockerinit</a>\n<a href=\"dev/\">dev/</a>\n<a href=\"test-webserver\">test-webserver</a>\n</pre>\n", 1 of 1 required successes so far
STEP: changing service mutability-service-test to type=NodePort
STEP: hitting the pod through the service's NodePort
STEP: Waiting up to 5m0s for the url http://104.154.92.91:32028 to be reachable
INFO: Successfully reached http://104.154.92.91:32028
STEP: changing service mutability-service-test to type=LoadBalancer
STEP: waiting up to 20m0s for service mutability-service-test in namespace e2e-tests-service-0-rdy7v to have a LoadBalancer ingress point
INFO: Waiting for service mutability-service-test in namespace e2e-tests-service-0-rdy7v to have a LoadBalancer ingress point (2.65332ms)
INFO: Waiting for service mutability-service-test in namespace e2e-tests-service-0-rdy7v to have a LoadBalancer ingress point (5.006169606s)
INFO: Waiting for service mutability-service-test in namespace e2e-tests-service-0-rdy7v to have a LoadBalancer ingress point (10.010000536s)
INFO: Waiting for service mutability-service-test in namespace e2e-tests-service-0-rdy7v to have a LoadBalancer ingress point (15.013917143s)
INFO: Waiting for service mutability-service-test in namespace e2e-tests-service-0-rdy7v to have a LoadBalancer ingress point (20.017936098s)
INFO: Waiting for service mutability-service-test in namespace e2e-tests-service-0-rdy7v to have a LoadBalancer ingress point (25.021667608s)
STEP: hitting the pod through the service's NodePort
STEP: Waiting up to 5m0s for the url http://104.154.92.91:32028 to be reachable
INFO: Successfully reached http://104.154.92.91:32028
STEP: hitting the pod through the service's LoadBalancer
STEP: Waiting up to 5m0s for the url http://104.154.88.251:80 to be reachable
INFO: Successfully reached http://104.154.88.251:80
STEP: changing service mutability-service-test update NodePort
STEP: hitting the pod through the service's updated NodePort
STEP: Waiting up to 5m0s for the url http://104.154.92.91:32027 to be reachable
INFO: Successfully reached http://104.154.92.91:32027
STEP: hitting the pod through the service's LoadBalancer
STEP: Waiting up to 5m0s for the url http://104.154.88.251:80 to be reachable
INFO: Got error waiting for reachability of http://104.154.88.251:80: Get http://104.154.88.251:80: net/http: request canceled while waiting for connection (10.000309607s)
INFO: Got error waiting for reachability of http://104.154.88.251:80: Get http://104.154.88.251:80: net/http: request canceled while waiting for connection (15.000535534s)
INFO: Got error waiting for reachability of http://104.154.88.251:80: Get http://104.154.88.251:80: net/http: request canceled while waiting for connection (20.000746152s)
INFO: Got error waiting for reachability of http://104.154.88.251:80: Get http://104.154.88.251:80: net/http: request canceled while waiting for connection (25.000956938s)
INFO: Got error waiting for reachability of http://104.154.88.251:80: Get http://104.154.88.251:80: net/http: request canceled while waiting for connection (30.001189994s)
INFO: Successfully reached http://104.154.88.251:80
STEP: checking the old NodePort is closed
STEP: Waiting up to 5m0s for the url http://104.154.92.91:32028 to be *not* reachable
INFO: Successfully waited for the url http://104.154.92.91:32028 to be *not* reachable
STEP: changing service mutability-service-test back to type=ClusterIP
STEP: stopping RC webserver in namespace e2e-tests-service-0-rdy7v
STEP: deleting service mutability-service-test in namespace e2e-tests-service-0-rdy7v
[AfterEach] Services
  /go/src/github.com/GoogleCloudPlatform/kubernetes/_output/dockerized/go/src/github.com/GoogleCloudPlatform/kubernetes/test/e2e/service.go:66
STEP: Destroying namespace e2e-tests-service-0-rdy7v
STEP: Destroying namespace e2e-tests-service-1-c7plg

• Failure [115.700 seconds]
Services
/go/src/github.com/GoogleCloudPlatform/kubernetes/_output/dockerized/go/src/github.com/GoogleCloudPlatform/kubernetes/test/e2e/service.go:792
  should be able to change the type and nodeport settings of a service [It]
  /go/src/github.com/GoogleCloudPlatform/kubernetes/_output/dockerized/go/src/github.com/GoogleCloudPlatform/kubernetes/test/e2e/service.go:490

  Expected error:
      <*errors.StatusError | 0xc208bd9880>: {
          ErrStatus: {
              TypeMeta: {Kind: "", APIVersion: ""},
              ListMeta: {SelfLink: "", ResourceVersion: ""},
              Status: "Failure",
              Message: "service \"mutability-service-test\" cannot be updated: 101: Compare failed ([3877 != 3885]) [3887]",
              Reason: "Conflict",
              Details: {
                  Name: "mutability-service-test",
                  Kind: "service",
                  Causes: nil,
                  RetryAfterSeconds: 0,
              },
              Code: 409,
          },
      }
      service "mutability-service-test" cannot be updated: 101: Compare failed ([3877 != 3885]) [3887]
  not to have occurred

  /go/src/github.com/GoogleCloudPlatform/kubernetes/_output/dockerized/go/src/github.com/GoogleCloudPlatform/kubernetes/test/e2e/service.go:462
------------------------------

**Comment by justinsb** [comment] 2015-07-09 17:14
@alex-mohr that looks like a client-side issue (and if so, worthy of a new issue?).  I think someone (likely the LB controller) has concurrently changed the service, and the client (the test) needs to retry?

**Comment by quinton-hoole** [comment] 2015-07-09 18:10
@justinsb agreed in theory, although it's curious to me that the version numbers differ by so much.  Seems like there may well be an underlying system problem.  Are we doing something funky under the hood to increment the service version number more than we should?

**Comment by thockin** [comment] 2015-07-10 16:23
Status on this?  @quinton-hoole can you hand-off since you're going AFK ?

**Comment by quinton-hoole** [comment] 2015-07-10 16:45
Yes, suggest that the test code be updated to retry.  Assigning to @krousey to do that, as he was looking for something to keep him out of mischief.

**Comment by krousey** [comment] 2015-07-10 18:14
@quinton-hoole was I? Ok fine... :smile:

**Comment by justinsb** [comment] 2015-07-10 23:52
I have an ancient but still open PR that might also help ... we should be logging events during this test: #8905.  Let me know if we would consider merging it and I will check that it still works.  (It's fairly small, and at this point it might be easier to just recreate it, I have no problems if someone want to do that)

**Comment by krousey** [comment] 2015-07-14 19:34
Spot checked a few builds and haven't seen this error pop up again. Reopen if it happens again.

**Closed by krousey** 2015-07-14 19:34 UTC
Labels: priority/P1, team/cluster, team/testing
