### ISSUE TITLE
apiserver proxy rewrites v1beta1 URLs to include a namespace in the path

### ISSUE THREAD

**Issue by roberthbailey** [GoogleCloudPlatform/kubernetes#5339] opened 2015-03-11 22:42 UTC
Today I launched a pod that was serving an angular app without a service or host port. To access the app, I used the proxy in the apiserver (```/api/v1beta1/proxy/pods/<pod-id>```). This returned the html of the app but none of the css or javascript loaded. Looking at the console, it appeared that the browser was attempting to load the resources from ```/api/v1beta1/ns/default/proxy/pods/<pod-id>``` (note the addition of the default namespace in the path). 

Loading the resources directly (without the namespace) worked as expected. Hitting the URL including the (incorrect) namespace returned a 404. 

We should make sure that any URL rewriting we do is versioned appropriately. 

/cc @timothysc

**Comment by bgrant0607** [comment] 2015-03-12 01:07
cc @nikhiljindal

**Comment by nikhiljindal** [comment] 2015-03-12 01:14
@lavalamp

**Comment by lavalamp** [comment] 2015-03-12 17:21
The bug is that it doesn't work, not that it got rewritten.

**Comment by lavalamp** [comment] 2015-03-12 17:23
Hm, actually I think the bug is that the ```ns/default``` appears before the ```proxy``` instead of after it... That's really weird.

If you access it as ```/api/v1beta1/proxy/ns/default/pods/<pod-id>``` does it then rewrite the paths correctly?

**Comment by roberthbailey** [comment] 2015-03-13 12:06
Tried accessing a service at ```/api/v1beta1/proxy/ns/default/services/<service-id>/``` and accessing a pod at ```/api/v1beta1/proxy/ns/default/pods/<pod-id>```. Both returned a 404.

**Comment by yujuhong** [comment] 2015-03-19 18:25
I couldn't reproduce this issue.

What works for me:
`http://127.0.0.1:8080/api/v1beta1/proxy/pods/frontend-controller-ls6k1`
`http://127.0.0.1:8080/api/v1beta3/proxy/pods/frontend-controller-ls6k1`
`http://127.0.0.1:8080/api/v1beta3/proxy/namespaces/default/pods/frontend-controller-ls6k1`

All of them returned the correct page, while all other combinations returned 404.
This is consistent with the API generated by swagger http://kubernetes.io/third_party/swagger-ui/

@roberthbailey, are you still seeing the same problem?

**Comment by roberthbailey** [comment] 2015-03-20 04:56
@yujuhong I haven't had a chance to re-test this yet, but I did notice that your url with the default namespace is written as `proxy/namespaces/default` while mine was `ns/default/proxy` (without namespaces spelled out). Did you try with ns instead of namespaces?

**Comment by yujuhong** [comment] 2015-03-20 21:34
The namespace change (ns -> namespace) was in this commit that landed on Feb 10th:
https://github.com/GoogleCloudPlatform/kubernetes/pull/3613/commits

Given that there have been many namespace changes, it's likely that the bug has been fixed...

**Comment by roberthbailey** [comment] 2015-03-20 21:47
We found this bug running against the 0.11.0 release which includes that commit. I haven't had a chance to try and reproduce at head.

**Comment by wojtek-t** [comment] 2015-03-23 14:24
cc @bgrant0607 

Somewhat related to this discussion: do we have a plan to uniform it? I think it might be misleading to support both "/ns" and "/namespaces" in URLs and we should support only one (personally I prefer "/namespaces"). Is there any reason to support both? Can we get rid of one of those now (is there any open issue for it?)?

**Comment by yujuhong** [comment] 2015-03-23 17:05
Do we support both? My understanding is that we've switched to "namespaces" after the commit I mentioned above.

**Comment by wojtek-t** [comment] 2015-03-23 19:04
I did just a quick look into a code and saw some places (at least comments) about "/ns". Also the link from the original post has to come from somewhere. But if we just don't support it, I can look deeper into it and try to change those.

**Comment by bgrant0607** [comment] 2015-03-23 21:42
Everything should be switched to /namespaces.

@derekwaynecarr

**Comment by bgrant0607** [comment] 2015-03-23 21:43
See also #5805 and #5763

**Comment by wojtek-t** [comment] 2015-03-24 07:28
Thanks Brian - SGTM

**Comment by yujuhong** [comment] 2015-03-26 00:55
@roberthbailey, the path construction was actually fixed by @lavalamp in #4778, and the fix was not included in the 0.11.0 release (it is in 0.12.0+).

**Comment by bgrant0607** [comment] 2015-03-31 23:59
Is there anything left to fix here, or can this issue be closed?

**Comment by nikhiljindal** [comment] 2015-04-01 00:10
I ran into this today with @satnam6502 
I was trying to access http://localhost:8080/api/v1beta1/proxy/services/monitoring-grafana/ and I saw a bunch of 404s while accessing css and js files.
Looking at the console, all of them were of the form http://localhost:8080/api/v1beta1/proxy/namespaces/default/services/monitoring-grafana/css/grafana.light.min.81a2958f.css

The URLs work if "namespaces/default" is removed from them.

**Comment by lavalamp** [comment] 2015-04-01 00:18
Yeah, I observed this at @nikhiljindal's desk-- it was working previously but not now. I suspect the handler wiring may have changed? @nikhiljindal said he would look at it.

**Comment by nikhiljindal** [comment] 2015-04-01 01:36
cc @derekwaynecarr @smarterclayton 
The issue is that we do not register proxy_handler for "/api/v1beta1/proxy/namespaces/default" paths (http://kubernetes.io/third_party/swagger-ui/).

Treating this as a low priority since this is a v1beta1 only issue.

**Comment by roberthbailey** [comment] 2015-04-27 04:36
@nikhiljindal if you can confirm that this isn't a problem with v1beta3 (which is now the default api version), I'm happy to close as obsolete.

**Comment by nikhiljindal** [comment] 2015-04-27 06:04
Yes. This is a v1beta1 only issue.
Closing.

**Closed by nikhiljindal** 2015-04-27 06:04 UTC
Labels: component/apiserver, kind/bug, priority/P2, team/master
