### ISSUE TITLE
Cleanup and re-architecture Getting Started Guides

### ISSUE THREAD

**Issue by proppy** [GoogleCloudPlatform/kubernetes#2840] opened 2014-12-11 00:15 UTC
- Split between:
  - “cluster setup” (per platform)
  - “quick start” (hello world on a local cluster)
  - “using it” (common tour of kubernetes functionally)
- Make an inventory of existing samples, qualify overlap and deprecate
- Provide individual directory or repo with manifests example for each tutorial
- moving out of date docs between /docs and /contrib
  - put onus on each provider’s maintainer, and ensure it works every release, if it works 3 times, keep it a first class, if not demote it to contrib

Part of #2633

**Comment by bgrant0607** [comment] 2015-02-05 01:30
Closing as dupe of #3578

**Closed by bgrant0607** 2015-02-05 01:30 UTC
Labels: area/documentation, area/usability, priority/P2
