### ISSUE TITLE
kube-proxy: do not fill disk with logs

### ISSUE THREAD

**Issue by alex-mohr** [GoogleCloudPlatform/kubernetes#3943] opened 2015-01-29 19:56 UTC
kube-proxy got into a state where it was writing repeated logs quite quickly.
E0129 18:56:04.831336    5100 proxier.go:102] Accept failed: use of closed network connection
E0129 18:56:04.831341    5100 proxier.go:102] Accept failed: use of closed network connection
It then filled the disk on the node.

We need a way to guarantee kube-proxy limits its log (and all other disk) usage to a given maximum.

> root@k8s-prod3-node-1:/var/log# ls -al /var/log| grep kube-proxy
> -rw-r--r--  1 root root   8701423616 Jan 29 19:48 kube-proxy.log
> -rw-r--r--  1 root root            0 Jan 29 19:17 kube-proxy.log.1
> -rw-r--r--  1 root root      1211900 Jan 29 00:16 kube-proxy.log.2.gz

Part of #3936 long-running clusters.  @dchen1107 for kube-proxy?

**Comment by alex-mohr** [comment] 2015-01-29 19:58
We also presumably need something similar for docker.log and kubelet.log -- Dawn, feel free to spawn new issues if that's easier to track?
  % ls -al /var/log/docker.log 
  -rw-r--r-- 1 root docker 649105408 Jan 29 19:57 /var/log/docker.log
  % ls -al /var/log/kubelet.log
  -rw-r--r-- 1 root root 105021440 Jan 29 19:58 /var/log/kubelet.log

**Comment by thockin** [comment] 2015-01-30 00:10
I would say this is a bug in kube-proxy - it should not get stuck in a loop
on that...

**Comment by dchen1107** [comment] 2015-01-30 17:43
There are two issues raised by this one:

* Why kube-proxy logs so much in this case? Like what @thockin mentioned above, stucking in a loop? or just simply log too much detail? There were several issues reported lately about disk_full caused by kube-proxy.log.

* Current log rotation policy we had is that is a maximum of 5 rotated out files with maxsize as 100M every day, we could adjust it with a smaller size, or different size for different daemons? Or dynamically adjust based on node size? 

cc/ @satnam6502

**Comment by phemmer** [comment] 2015-02-02 17:46
Just ran into this issue myself. All my nodes were stuck with 100% disk used due to `Accept failed: use of closed network connection`.

Here are the log entries leading up to the start of the `Accept failed` spam:

```
I0202 07:45:53.745327    5087 proxier.go:356] Periodic sync
I0202 07:45:53.745400    5087 iptables.go:186] running iptables -N [KUBE-PORTALS-CONTAINER -t nat]
I0202 07:45:53.747898    5087 iptables.go:186] running iptables -C [PREROUTING -t nat -j KUBE-PORTALS-CONTAINER]
I0202 07:45:53.748868    5087 iptables.go:186] running iptables -N [KUBE-PORTALS-HOST -t nat]
I0202 07:45:53.750750    5087 iptables.go:186] running iptables -C [OUTPUT -t nat -j KUBE-PORTALS-HOST]
I0202 07:45:53.752735    5087 iptables.go:186] running iptables -C [KUBE-PORTALS-CONTAINER -t nat -m comment --comment kubernetes-ro -p tcp -m tcp -d 10.79.252.127/32 --dport 80 -j REDIRECT --to-ports 43501]
I0202 07:45:53.754956    5087 iptables.go:186] running iptables -C [KUBE-PORTALS-HOST -t nat -m comment --comment kubernetes-ro -p tcp -m tcp -d 10.79.252.127/32 --dport 80 -j DNAT --to-destination 10.240.231.173:43501]
I0202 07:45:53.759617    5087 iptables.go:186] running iptables -C [KUBE-PORTALS-CONTAINER -t nat -m comment --comment kubernetes -p tcp -m tcp -d 10.79.245.122/32 --dport 443 -j REDIRECT --to-ports 60877]
I0202 07:45:53.761833    5087 iptables.go:186] running iptables -C [KUBE-PORTALS-HOST -t nat -m comment --comment kubernetes -p tcp -m tcp -d 10.79.245.122/32 --dport 443 -j DNAT --to-destination 10.240.231.173:60877]
I0202 07:45:53.763957    5087 iptables.go:186] running iptables -C [KUBE-PORTALS-CONTAINER -t nat -m comment --comment redis -p tcp -m tcp -d 10.79.244.19/32 --dport 6379 -j REDIRECT --to-ports 46227]
I0202 07:45:53.766026    5087 iptables.go:186] running iptables -C [KUBE-PORTALS-HOST -t nat -m comment --comment redis -p tcp -m tcp -d 10.79.244.19/32 --dport 6379 -j DNAT --to-destination 10.240.231.173:46227]
I0202 07:45:53.768256    5087 iptables.go:186] running iptables -C [KUBE-PORTALS-CONTAINER -t nat -m comment --comment streamer -p tcp -m tcp -d 10.79.245.34/32 --dport 80 -j REDIRECT --to-ports 56920]
I0202 07:45:53.770363    5087 iptables.go:186] running iptables -C [KUBE-PORTALS-HOST -t nat -m comment --comment streamer -p tcp -m tcp -d 10.79.245.34/32 --dport 80 -j DNAT --to-destination 10.240.231.173:56920]
I0202 07:45:53.772446    5087 iptables.go:186] running iptables -C [KUBE-PORTALS-CONTAINER -t nat -m comment --comment streamer -p tcp -m tcp -d 104.154.32.176/32 --dport 80 -j REDIRECT --to-ports 56920]
I0202 07:45:53.774570    5087 iptables.go:186] running iptables -C [KUBE-PORTALS-HOST -t nat -m comment --comment streamer -p tcp -m tcp -d 104.154.32.176/32 --dport 80 -j DNAT --to-destination 10.240.231.173:56920]
I0202 07:45:53.776666    5087 iptables.go:186] running iptables -C [KUBE-PORTALS-CONTAINER -t nat -m comment --comment frontend -p tcp -m tcp -d 10.79.246.151/32 --dport 5432 -j REDIRECT --to-ports 42871]
I0202 07:45:53.778782    5087 iptables.go:186] running iptables -C [KUBE-PORTALS-HOST -t nat -m comment --comment frontend -p tcp -m tcp -d 10.79.246.151/32 --dport 5432 -j DNAT --to-destination 10.240.231.173:42871]
I0202 07:45:53.780888    5087 iptables.go:186] running iptables -C [KUBE-PORTALS-CONTAINER -t nat -m comment --comment docker-registry -p tcp -m tcp -d 10.79.240.10/32 --dport 5001 -j REDIRECT --to-ports 52336]
I0202 07:45:53.782914    5087 iptables.go:186] running iptables -C [KUBE-PORTALS-HOST -t nat -m comment --comment docker-registry -p tcp -m tcp -d 10.79.240.10/32 --dport 5001 -j DNAT --to-destination 10.240.231.173:52336]
I0202 07:45:57.076089    5087 iptables.go:186] running iptables -C [KUBE-PORTALS-CONTAINER -t nat -m comment --comment frontend -p tcp -m tcp -d 10.79.246.151/32 --dport 5432 -j REDIRECT --to-ports 42871]
I0202 07:45:57.077444    5087 iptables.go:186] running iptables -D [KUBE-PORTALS-CONTAINER -t nat -m comment --comment frontend -p tcp -m tcp -d 10.79.246.151/32 --dport 5432 -j REDIRECT --to-ports 42871]
I0202 07:45:57.079587    5087 iptables.go:186] running iptables -C [KUBE-PORTALS-HOST -t nat -m comment --comment frontend -p tcp -m tcp -d 10.79.246.151/32 --dport 5432 -j DNAT --to-destination 10.240.231.173:42871]
I0202 07:45:57.080873    5087 iptables.go:186] running iptables -D [KUBE-PORTALS-HOST -t nat -m comment --comment frontend -p tcp -m tcp -d 10.79.246.151/32 --dport 5432 -j DNAT --to-destination 10.240.231.173:42871]
I0202 07:45:57.082067    5087 proxier.go:574] Closed iptables portals for service "frontend"
I0202 07:45:57.082092    5087 proxier.go:479] Adding new service "frontend" at 10.79.241.139:5432/TCP (local :0)
I0202 07:45:57.082161    5087 proxier.go:442] Proxying for service "frontend" on TCP port 45284
E0202 07:45:57.082413    5087 proxier.go:102] Accept failed: accept tcp [::]:42871: use of closed network connection
E0202 07:45:57.082435    5087 proxier.go:102] Accept failed: use of closed network connection
```

All nodes look similar (IP addrs & ports change), and occur within a few seconds of each other.
I'm not sure if this was a result of something I was doing.

Judging from the comment on [line 100](https://github.com/GoogleCloudPlatform/kubernetes/blob/61c4a04ad2fb0b93bab7f9676a875e75a9fe5c32/pkg/proxy/proxier.go#L100), it appears as if there is a check trying to prevent this loop.

**Comment by thockin** [comment] 2015-02-02 18:00
I am out for the morning, can someone P0 this error?

**Comment by dchen1107** [comment] 2015-02-02 18:03
@thockin, I am treating this as P0, and looking at it now.

**Comment by thockin** [comment] 2015-02-02 18:13
Ok, I can help trace the proxy code later today if needed

**Comment by dchen1107** [comment] 2015-02-03 18:48
I couldn't reproduce above "Accepted failed" issue. But #4026 reduce the verbose log from kube-proxy hugely. Close the issue for now. Separate disk management issues will be filed.

**Closed by dchen1107** 2015-02-03 18:48 UTC
Labels: area/hosting, area/reliability, component/proxy, priority/P0

**Comment by phemmer** [comment] 2015-02-03 19:02
@dchen1107 Is there any info I can provide. It's happening several times a day on my systems.

**Comment by thockin** [comment] 2015-02-03 19:14
Can you reproduce it?  Are you running head of tree or a particular version?

**Comment by phemmer** [comment] 2015-02-03 19:38
I havent gotten around to reproducing it on demand, but I usually don't have to wait long before it starts.
I'm using 0.8.1, the version currently being deployed on GKE.

**Comment by dchen1107** [comment] 2015-02-03 19:53
I tried it with both 0.9.2 and HEAD, not with 0.8.1

**Comment by dchen1107** [comment] 2015-02-03 20:05
@phemmer, could you restart kube-proxy with -v=5, and try to reproduce the issue? Please share with us the log. We are going to look into that in detail with a reproduced case. Thanks for your help.

**Comment by phemmer** [comment] 2015-02-03 20:13
@dchen1107 here you go:

```
I0203 20:11:28.001964   28164 proxier.go:356] Periodic sync
I0203 20:11:28.002109   28164 iptables.go:186] running iptables -N [KUBE-PORTALS-CONTAINER -t nat]
I0203 20:11:28.005315   28164 iptables.go:186] running iptables -C [PREROUTING -t nat -j KUBE-PORTALS-CONTAINER]
I0203 20:11:28.007087   28164 iptables.go:186] running iptables -N [KUBE-PORTALS-HOST -t nat]
I0203 20:11:28.008908   28164 iptables.go:186] running iptables -C [OUTPUT -t nat -j KUBE-PORTALS-HOST]
I0203 20:11:28.010779   28164 iptables.go:186] running iptables -C [KUBE-PORTALS-CONTAINER -t nat -m comment --comment kubernetes-ro -p tcp -m tcp -d 10.79.252.127/32 --dport 80 -j REDIRECT --to-ports 57355]
I0203 20:11:28.013317   28164 iptables.go:186] running iptables -C [KUBE-PORTALS-HOST -t nat -m comment --comment kubernetes-ro -p tcp -m tcp -d 10.79.252.127/32 --dport 80 -j DNAT --to-destination 10.240.177.159:57355]
I0203 20:11:28.016068   28164 iptables.go:186] running iptables -C [KUBE-PORTALS-CONTAINER -t nat -m comment --comment kubernetes -p tcp -m tcp -d 10.79.245.122/32 --dport 443 -j REDIRECT --to-ports 48733]
I0203 20:11:28.018216   28164 iptables.go:186] running iptables -C [KUBE-PORTALS-HOST -t nat -m comment --comment kubernetes -p tcp -m tcp -d 10.79.245.122/32 --dport 443 -j DNAT --to-destination 10.240.177.159:48733]
I0203 20:11:28.020966   28164 iptables.go:186] running iptables -C [KUBE-PORTALS-CONTAINER -t nat -m comment --comment redis -p tcp -m tcp -d 10.79.244.19/32 --dport 6379 -j REDIRECT --to-ports 49069]
I0203 20:11:28.023284   28164 iptables.go:186] running iptables -C [KUBE-PORTALS-HOST -t nat -m comment --comment redis -p tcp -m tcp -d 10.79.244.19/32 --dport 6379 -j DNAT --to-destination 10.240.177.159:49069]
I0203 20:11:28.025674   28164 iptables.go:186] running iptables -C [KUBE-PORTALS-CONTAINER -t nat -m comment --comment streamer -p tcp -m tcp -d 10.79.245.34/32 --dport 80 -j REDIRECT --to-ports 49324]
I0203 20:11:28.027779   28164 iptables.go:186] running iptables -C [KUBE-PORTALS-HOST -t nat -m comment --comment streamer -p tcp -m tcp -d 10.79.245.34/32 --dport 80 -j DNAT --to-destination 10.240.177.159:49324]
I0203 20:11:28.029969   28164 iptables.go:186] running iptables -C [KUBE-PORTALS-CONTAINER -t nat -m comment --comment streamer -p tcp -m tcp -d 104.154.32.176/32 --dport 80 -j REDIRECT --to-ports 49324]
I0203 20:11:28.032219   28164 iptables.go:186] running iptables -C [KUBE-PORTALS-HOST -t nat -m comment --comment streamer -p tcp -m tcp -d 104.154.32.176/32 --dport 80 -j DNAT --to-destination 10.240.177.159:49324]
I0203 20:11:28.034377   28164 iptables.go:186] running iptables -C [KUBE-PORTALS-CONTAINER -t nat -m comment --comment docker-registry -p tcp -m tcp -d 10.79.243.237/32 --dport 5001 -j REDIRECT --to-ports 57376]
I0203 20:11:28.036735   28164 iptables.go:186] running iptables -C [KUBE-PORTALS-HOST -t nat -m comment --comment docker-registry -p tcp -m tcp -d 10.79.243.237/32 --dport 5001 -j DNAT --to-destination 10.240.177.159:57376]
I0203 20:11:28.038876   28164 iptables.go:186] running iptables -C [KUBE-PORTALS-CONTAINER -t nat -m comment --comment frontend -p tcp -m tcp -d 10.79.246.151/32 --dport 5432 -j REDIRECT --to-ports 51115]
I0203 20:11:28.041087   28164 iptables.go:186] running iptables -C [KUBE-PORTALS-HOST -t nat -m comment --comment frontend -p tcp -m tcp -d 10.79.246.151/32 --dport 5432 -j DNAT --to-destination 10.240.177.159:51115]
I0203 20:11:28.043253   28164 iptables.go:186] running iptables -C [KUBE-PORTALS-CONTAINER -t nat -m comment --comment database -p tcp -m tcp -d 10.79.255.75/32 --dport 5434 -j REDIRECT --to-ports 48863]
I0203 20:11:28.045413   28164 iptables.go:186] running iptables -C [KUBE-PORTALS-HOST -t nat -m comment --comment database -p tcp -m tcp -d 10.79.255.75/32 --dport 5434 -j DNAT --to-destination 10.240.177.159:48863]
I0203 20:11:31.562232   28164 config.go:233] Setting services {Services:[{TypeMeta:{Kind: APIVersion:} ObjectMeta:{Name:frontend Namespace:hello-openshift-project SelfLink:/api/v1beta1/services/frontend?namespace=hello-openshift-project UID:c2e7e42d-aaa7-11e4-9c66-42010af0c2fd ResourceVersion:776506 CreationTimestamp:2015-02-02 06:50:23 +0000 UTC Labels:map[template:hello-openshift] Annotations:map[]} Spec:{Port:5432 Protocol:TCP Selector:map[name:frontend] PortalIP:10.79.246.151 ProxyPort:0 CreateExternalLoadBalancer:false PublicIPs:[] ContainerPort:{Kind:0 IntVal:8080 StrVal:} SessionAffinity:None} Status:{}} {TypeMeta:{Kind: APIVersion:} ObjectMeta:{Name:frontend Namespace:test SelfLink:/api/v1beta1/services/frontend?namespace=test UID:85eac6f3-aaaf-11e4-9c66-42010af0c2fd ResourceVersion:781980 CreationTimestamp:2015-02-02 07:45:57 +0000 UTC Labels:map[template:ruby-helloworld-sample] Annotations:map[]} Spec:{Port:5432 Protocol:TCP Selector:map[name:frontend] PortalIP:10.79.241.139 ProxyPort:0 CreateExternalLoadBalancer:false PublicIPs:[] ContainerPort:{Kind:0 IntVal:8080 StrVal:} SessionAffinity:None} Status:{}} {TypeMeta:{Kind: APIVersion:} ObjectMeta:{Name:database Namespace:test SelfLink:/api/v1beta1/services/database?namespace=test UID:866caa44-aaaf-11e4-9c66-42010af0c2fd ResourceVersion:781985 CreationTimestamp:2015-02-02 07:45:57 +0000 UTC Labels:map[template:ruby-helloworld-sample] Annotations:map[]} Spec:{Port:5434 Protocol:TCP Selector:map[name:database] PortalIP:10.79.255.75 ProxyPort:0 CreateExternalLoadBalancer:false PublicIPs:[] ContainerPort:{Kind:0 IntVal:3306 StrVal:} SessionAffinity:None} Status:{}} {TypeMeta:{Kind: APIVersion:} ObjectMeta:{Name:streamer Namespace:default SelfLink:/api/v1beta1/services/streamer?namespace=default UID:459ed1dc-a582-11e4-9c66-42010af0c2fd ResourceVersion:3281 CreationTimestamp:2015-01-26 17:39:26 +0000 UTC Labels:map[] Annotations:map[]} Spec:{Port:80 Protocol:TCP Selector:map[name:streamer] PortalIP:10.79.245.34 ProxyPort:0 CreateExternalLoadBalancer:true PublicIPs:[104.154.32.176] ContainerPort:{Kind:1 IntVal:0 StrVal:http-server} SessionAffinity:None} Status:{}} {TypeMeta:{Kind: APIVersion:} ObjectMeta:{Name:docker-registry Namespace:default SelfLink:/api/v1beta1/services/docker-registry?namespace=default UID:6383b2c9-abde-11e4-b20c-42010af0c2fd ResourceVersion:989265 CreationTimestamp:2015-02-03 19:53:56 +0000 UTC Labels:map[template:docker-registry-template] Annotations:map[]} Spec:{Port:5001 Protocol:TCP Selector:map[name:registrypod] PortalIP:10.79.243.237 ProxyPort:0 CreateExternalLoadBalancer:false PublicIPs:[] ContainerPort:{Kind:0 IntVal:5000 StrVal:} SessionAffinity:None} Status:{}} {TypeMeta:{Kind: APIVersion:} ObjectMeta:{Name:kubernetes-ro Namespace:default SelfLink:/api/v1beta1/services/kubernetes-ro?namespace=default UID:03b70a21-a579-11e4-9c66-42010af0c2fd ResourceVersion:3 CreationTimestamp:2015-01-26 16:33:09 +0000 UTC Labels:map[component:apiserver provider:kubernetes] Annotations:map[]} Spec:{Port:80 Protocol:TCP Selector:map[] PortalIP:10.79.252.127 ProxyPort:0 CreateExternalLoadBalancer:false PublicIPs:[] ContainerPort:{Kind:0 IntVal:0 StrVal:} SessionAffinity:None} Status:{}} {TypeMeta:{Kind: APIVersion:} ObjectMeta:{Name:kubernetes Namespace:default SelfLink:/api/v1beta1/services/kubernetes?namespace=default UID:03bb05a4-a579-11e4-9c66-42010af0c2fd ResourceVersion:4 CreationTimestamp:2015-01-26 16:33:09 +0000 UTC Labels:map[component:apiserver provider:kubernetes] Annotations:map[]} Spec:{Port:443 Protocol:TCP Selector:map[] PortalIP:10.79.245.122 ProxyPort:0 CreateExternalLoadBalancer:false PublicIPs:[] ContainerPort:{Kind:0 IntVal:0 StrVal:} SessionAffinity:None} Status:{}} {TypeMeta:{Kind: APIVersion:} ObjectMeta:{Name:redis Namespace:default SelfLink:/api/v1beta1/services/redis?namespace=default UID:5034934a-a57f-11e4-9c66-42010af0c2fd ResourceVersion:2208 CreationTimestamp:2015-01-26 17:18:15 +0000 UTC Labels:map[name:redis] Annotations:map[]} Spec:{Port:6379 Protocol:TCP Selector:map[name:redis] PortalIP:10.79.244.19 ProxyPort:0 CreateExternalLoadBalancer:false PublicIPs:[] ContainerPort:{Kind:1 IntVal:0 StrVal:redis} SessionAffinity:None} Status:{}}] Op:0}
I0203 20:11:31.563828   28164 proxier.go:458] Received update notice: [{TypeMeta:{Kind: APIVersion:} ObjectMeta:{Name:database Namespace:test SelfLink:/api/v1beta1/services/database?namespace=test UID:866caa44-aaaf-11e4-9c66-42010af0c2fd ResourceVersion:781985 CreationTimestamp:2015-02-02 07:45:57 +0000 UTC Labels:map[template:ruby-helloworld-sample] Annotations:map[]} Spec:{Port:5434 Protocol:TCP Selector:map[name:database] PortalIP:10.79.255.75 ProxyPort:0 CreateExternalLoadBalancer:false PublicIPs:[] ContainerPort:{Kind:0 IntVal:3306 StrVal:} SessionAffinity:None} Status:{}} {TypeMeta:{Kind: APIVersion:} ObjectMeta:{Name:streamer Namespace:default SelfLink:/api/v1beta1/services/streamer?namespace=default UID:459ed1dc-a582-11e4-9c66-42010af0c2fd ResourceVersion:3281 CreationTimestamp:2015-01-26 17:39:26 +0000 UTC Labels:map[] Annotations:map[]} Spec:{Port:80 Protocol:TCP Selector:map[name:streamer] PortalIP:10.79.245.34 ProxyPort:0 CreateExternalLoadBalancer:true PublicIPs:[104.154.32.176] ContainerPort:{Kind:1 IntVal:0 StrVal:http-server} SessionAffinity:None} Status:{}} {TypeMeta:{Kind: APIVersion:} ObjectMeta:{Name:docker-registry Namespace:default SelfLink:/api/v1beta1/services/docker-registry?namespace=default UID:6383b2c9-abde-11e4-b20c-42010af0c2fd ResourceVersion:989265 CreationTimestamp:2015-02-03 19:53:56 +0000 UTC Labels:map[template:docker-registry-template] Annotations:map[]} Spec:{Port:5001 Protocol:TCP Selector:map[name:registrypod] PortalIP:10.79.243.237 ProxyPort:0 CreateExternalLoadBalancer:false PublicIPs:[] ContainerPort:{Kind:0 IntVal:5000 StrVal:} SessionAffinity:None} Status:{}} {TypeMeta:{Kind: APIVersion:} ObjectMeta:{Name:kubernetes-ro Namespace:default SelfLink:/api/v1beta1/services/kubernetes-ro?namespace=default UID:03b70a21-a579-11e4-9c66-42010af0c2fd ResourceVersion:3 CreationTimestamp:2015-01-26 16:33:09 +0000 UTC Labels:map[component:apiserver provider:kubernetes] Annotations:map[]} Spec:{Port:80 Protocol:TCP Selector:map[] PortalIP:10.79.252.127 ProxyPort:0 CreateExternalLoadBalancer:false PublicIPs:[] ContainerPort:{Kind:0 IntVal:0 StrVal:} SessionAffinity:None} Status:{}} {TypeMeta:{Kind: APIVersion:} ObjectMeta:{Name:kubernetes Namespace:default SelfLink:/api/v1beta1/services/kubernetes?namespace=default UID:03bb05a4-a579-11e4-9c66-42010af0c2fd ResourceVersion:4 CreationTimestamp:2015-01-26 16:33:09 +0000 UTC Labels:map[component:apiserver provider:kubernetes] Annotations:map[]} Spec:{Port:443 Protocol:TCP Selector:map[] PortalIP:10.79.245.122 ProxyPort:0 CreateExternalLoadBalancer:false PublicIPs:[] ContainerPort:{Kind:0 IntVal:0 StrVal:} SessionAffinity:None} Status:{}} {TypeMeta:{Kind: APIVersion:} ObjectMeta:{Name:redis Namespace:default SelfLink:/api/v1beta1/services/redis?namespace=default UID:5034934a-a57f-11e4-9c66-42010af0c2fd ResourceVersion:2208 CreationTimestamp:2015-01-26 17:18:15 +0000 UTC Labels:map[name:redis] Annotations:map[]} Spec:{Port:6379 Protocol:TCP Selector:map[name:redis] PortalIP:10.79.244.19 ProxyPort:0 CreateExternalLoadBalancer:false PublicIPs:[] ContainerPort:{Kind:1 IntVal:0 StrVal:redis} SessionAffinity:None} Status:{}} {TypeMeta:{Kind: APIVersion:} ObjectMeta:{Name:frontend Namespace:test SelfLink:/api/v1beta1/services/frontend?namespace=test UID:85eac6f3-aaaf-11e4-9c66-42010af0c2fd ResourceVersion:781980 CreationTimestamp:2015-02-02 07:45:57 +0000 UTC Labels:map[template:ruby-helloworld-sample] Annotations:map[]} Spec:{Port:5432 Protocol:TCP Selector:map[name:frontend] PortalIP:10.79.241.139 ProxyPort:0 CreateExternalLoadBalancer:false PublicIPs:[] ContainerPort:{Kind:0 IntVal:8080 StrVal:} SessionAffinity:None} Status:{}}]
I0203 20:11:31.564181   28164 proxier.go:469] Something changed for service "frontend": stopping it
I0203 20:11:31.565576   28164 iptables.go:186] running iptables -C [KUBE-PORTALS-CONTAINER -t nat -m comment --comment frontend -p tcp -m tcp -d 10.79.246.151/32 --dport 5432 -j REDIRECT --to-ports 51115]
I0203 20:11:31.566909   28164 iptables.go:186] running iptables -D [KUBE-PORTALS-CONTAINER -t nat -m comment --comment frontend -p tcp -m tcp -d 10.79.246.151/32 --dport 5432 -j REDIRECT --to-ports 51115]
I0203 20:11:31.569267   28164 iptables.go:186] running iptables -C [KUBE-PORTALS-HOST -t nat -m comment --comment frontend -p tcp -m tcp -d 10.79.246.151/32 --dport 5432 -j DNAT --to-destination 10.240.177.159:51115]
I0203 20:11:31.570586   28164 iptables.go:186] running iptables -D [KUBE-PORTALS-HOST -t nat -m comment --comment frontend -p tcp -m tcp -d 10.79.246.151/32 --dport 5432 -j DNAT --to-destination 10.240.177.159:51115]
I0203 20:11:31.571812   28164 proxier.go:574] Closed iptables portals for service "frontend"
I0203 20:11:31.571846   28164 proxier.go:479] Adding new service "frontend" at 10.79.241.139:5432/TCP (local :0)
I0203 20:11:31.571979   28164 proxier.go:442] Proxying for service "frontend" on TCP port 42769
I0203 20:11:31.571998   28164 proxier.go:491] info: &{portalIP:[0 0 0 0 0 0 0 0 0 0 255 255 10 79 241 139] portalPort:5432 protocol:TCP proxyPort:42769 socket:0xc208178210 timeout:60000000000 publicIP:[] sessionAffinityType:None stickyMaxAgeMinutes:180}
E0203 20:11:31.572362   28164 proxier.go:102] Accept failed: accept tcp [::]:51115: use of closed network connection
E0203 20:11:31.572389   28164 proxier.go:102] Accept failed: use of closed network connection
E0203 20:11:31.572398   28164 proxier.go:102] Accept failed: use of closed network connection
E0203 20:11:31.572412   28164 proxier.go:102] Accept failed: use of closed network connection
E0203 20:11:31.572420   28164 proxier.go:102] Accept failed: use of closed network connection
```

**Comment by thockin** [comment] 2015-02-03 20:54
This gives me a good clue - digging in now

**Comment by thockin** [comment] 2015-02-03 21:48
Got it.  Fix is in testing now.

**Comment by thockin** [comment] 2015-02-03 22:41
PR is out for review.

**Comment by thockin** [comment] 2015-02-04 01:09
The fix for the runaway is in.  We still should do better with log management, though.

**Comment by jmreicha** [comment] 2015-03-13 20:40
I am seeing this as well in 0.8.1.  Is there a way to temporarily fix without upgrading to newer code?

**Comment by dchen1107** [comment] 2015-03-13 20:47
AFAIK Unfortunately there is no a workaround except 
1) changing your logrotation config
2) removing that log file regularly

**Comment by thockin** [comment] 2015-03-13 21:28
if you don't care about the logs you could ln /dev/null /var/lib/kubelet -
might work?

**Comment by cordoval** [comment] 2017-06-27 11:42
I am not using mobi but the same error happens to me on a kops cluster, the "sensitive" defaults for logrotate on kops are 100MB. Minding that the aprox number of rotations is ~7 and there are about 7+ kube related log files. The disk of the default installation gets filled rapidly to ~10GB which in itself also causes no allocation of resources because of disk full which in turn logs more and the cycle repeats endlessly.

My proposal is to suggest turning 100MB into 10MB so at most you loose 1GB of disk if it enters this harmful cycle.
