### ISSUE TITLE
Proxy not working, Unable to load endpoints

### ISSUE THREAD

**Issue by gangadhars** [GoogleCloudPlatform/kubernetes#10480] opened 2015-06-29 14:55 UTC
I install kubernetes using this guide [ubuntu.md] (https://github.com/GoogleCloudPlatform/kubernetes/blob/master/docs/getting-started-guides/ubuntu.md). Then I tried [Guestbook example](https://github.com/GoogleCloudPlatform/kubernetes/tree/master/examples/guestbook) which causing a problem. Redis-slave is unable to sync with redis-master. Here are the logs.

\# kubectl get nodes
```
NAME          LABELS                                       STATUS
172.16.2.73   kubernetes.io/hostname=172.16.2.73           Ready
172.16.2.91   kubernetes.io/hostname=172.16.2.91           Ready
172.16.2.92   kubernetes.io/hostname=172.16.2.92           Ready
172.16.2.96   kubernetes.io/hostname=172.16.2.96           Ready
```

\# kubectl get pods

    POD                  IP           CONTAINER(S)   IMAGE(S)                                         HOST                      LABELS                                                              STATUS    CREATED         MESSAGE
    kube-dns-99zoq       10.1.95.2                                                                    172.16.2.91/172.16.2.91   k8s-app=kube-dns,kubernetes.io/cluster-service=true,name=kube-dns   Running   About an hour
                                      kube2sky       gcr.io/google_containers/kube2sky:1.1                                                                                                          Running   About an hour   last termination: exit code 1
                                      skydns         gcr.io/google_containers/skydns:2015-03-11-001                                                                                                 Running   About an hour
                                      etcd           quay.io/coreos/etcd:v2.0.3                                                                                                                     Running   About an hour
    redis-master-eq6ig   10.1.39.16                                                                   172.16.2.96/172.16.2.96   name=redis-master                                                   Running   About an hour
                                      master         redis                                                                                                                                          Running   About an hour
    redis-slave-f394k    10.1.34.2                                                                    172.16.2.73/172.16.2.73   name=redis-slave                                                    Running   About an hour
                                      slave          kubernetes/redis-slave:v2                                                                                                                      Running   About an hour
    redis-slave-t690b    10.1.46.2                                                                    172.16.2.92/172.16.2.92   name=redis-slave                                                    Running   About an hour
                                      slave          kubernetes/redis-slave:v2                                                                                                                      Running   About an hour
    
\# kubectl get services

    NAME            LABELS                                                              SELECTOR            IP(S)        PORT(S)
    kube-dns        k8s-app=kube-dns,kubernetes.io/cluster-service=true,name=kube-dns   k8s-app=kube-dns    15.1.3.10    53/UDP
    kubernetes      component=apiserver,provider=kubernetes                             <none>              15.1.3.2     443/TCP
    kubernetes-ro   component=apiserver,provider=kubernetes                             <none>              15.1.3.1     80/TCP
    redis-master    name=redis-master                                                   name=redis-master   15.1.3.153   6379/TCP
    redis-slave     name=redis-slave                                                    name=redis-slave    15.1.3.181   6379/TCP
    
\# kubectl logs  redis-slave-t690b

    [9] 29 Jun 07:19:15.432 # WARNING: The TCP backlog setting of 511 cannot be enforced because /proc/sys/net/core/somaxconn is set to the lower value of 128.
    [9] 29 Jun 07:19:15.432 * The server is now ready to accept connections on port 6379
    [9] 29 Jun 07:19:16.432 * Connecting to MASTER redis-master:6379
    [9] 29 Jun 07:19:31.581 # Unable to connect to MASTER: No such file or directory
    [9] 29 Jun 07:19:32.584 * Connecting to MASTER redis-master:6379
    [9] 29 Jun 07:19:47.743 # Unable to connect to MASTER: No such file or directory
    [9] 29 Jun 07:19:48.746 * Connecting to MASTER redis-master:6379

\#  cat /var/log/upstart/flanneld.log

    E0629 00:12:19.331286 23841 main.go:171] Failed to create SubnetManager: 100: Key not found (/coreos.com) [27]
    I0629 00:12:20.333500 23841 main.go:278] Installing signal handlers
    I0629 00:12:20.333742 23841 main.go:138] Determining IP address of default interface
    I0629 00:12:20.334787 23841 main.go:228] Using 172.16.2.73 as external interface
    I0629 00:12:20.336418 23841 subnet.go:334] Picking subnet in range 10.1.1.0 ... 10.1.255.0
    I0629 00:12:20.900225 23841 subnet.go:97] Subnet lease acquired: 10.1.95.0/24
    I0629 00:12:20.907356 23841 main.go:245] UDP mode initialized
    I0629 00:12:20.907526 23841 udp.go:212] Watching for new subnet leases
    I0629 00:12:20.909248 23841 udp.go:237] Subnet added: 10.1.74.0/24
    I0629 00:12:21.340083 23841 udp.go:237] Subnet added: 10.1.8.0/24
    I0629 00:12:21.340703 23841 udp.go:237] Subnet added: 10.1.96.0/24
    
\# cat /var/log/upstart/kube-proxy.log

    E0629 00:12:00.166619   23844 api.go:180] Unable to load endpoints: Get http://172.16.2.73:8080/api/v1beta3/endpoints: dial tcp 172.16.2.73:8080: connection refused
    E0629 00:12:00.171629   23844 api.go:108] Unable to load services: Get http://172.16.2.73:8080/api/v1beta3/services: dial tcp 172.16.2.73:8080: connection refused
    E0629 00:22:15.168869   23844 proxier.go:153] Failed to ensure iptables: error creating chain "KUBE-PORTALS-CONTAINER": exit status 4: Another app is currently holding the xtables lock. Perhaps you want to use the -w option?
    E0629 00:22:15.180001   23844 proxier.go:391] Failed to install iptables KUBE-PORTALS-CONTAINER rule for service "default/redis-master:"
    E0629 00:22:15.180121   23844 proxier.go:168] Failed to ensure portal for "default/redis-master:": error checking rule: exit status 4: Another app is currently holding the xtables lock. Perhaps you want to use the -w option?
    

How to solve proxy errors?

PS: I downloaded git version 0.19.3, but `kubectl version` showing "v0.18.0"

**Comment by gmarek** [comment] 2015-06-29 15:07
IIUC you built the version v0.18.0 using default `cluster/ubuntu/build.sh` setting. We probably need to update that.

Rest of the problems might be caused by this, but I'm not sure.

**Comment by gmarek** [comment] 2015-06-29 15:12
@eparis can you please take a look if 0.20.0 works on Ubuntu and if so change the default?

**Comment by wojtek-t** [comment] 2015-06-29 15:17
cc @mwielgus as he faced the same (or very similar) problem today

**Comment by eparis** [comment] 2015-06-29 15:22
@WIZARD-CXY maybe you can help out here?

**Comment by WIZARD-CXY** [comment] 2015-06-29 15:32
@gmarek I came up with a pr to bump the version to 0.19.3 for ubuntu k8s already.It is waiting for merging. https://github.com/GoogleCloudPlatform/kubernetes/pull/10393

**Comment by WIZARD-CXY** [comment] 2015-06-29 15:39
@gangadhars  First you can get some log of dns pod to see if dns gets wrong.Then make sure http://172.16.2.73:8080  is ok by using `nc -zv 172.16.2.73 8080 `.
I think the most suspicious reason is `Failed to ensure portal for "default/redis-master:": error checking rule: exit status 4: Another app is currently holding the xtables lock. Perhaps you want to use the -w option? ` according to your kube-proxy's log.

**Comment by mwielgus** [comment] 2015-06-29 15:40
This is a different problem from what I had. In my case it was about authentication and an upgrade (sync & rebuild) to 0.20 helped a lot.

**Comment by gangadhars** [comment] 2015-06-29 15:58
I try to build with `K8S_VERSION="v0.20.0"`, I'm facing some errors
```
/home/kube/0.19.3/kubernetes/cluster/ubuntu/kubernetes/server /home/kube/0.19.3/kubernetes/cluster/ubuntu
/home/kube/0.19.3/kubernetes/cluster/ubuntu
cp: cannot stat âkubernetes/server/kubernetes/server/bin/kube-apiserverâ: No such file or directory
cp: cannot stat âkubernetes/server/kubernetes/server/bin/kube-controller-managerâ: No such file or directory
cp: cannot stat âkubernetes/server/kubernetes/server/bin/kube-schedulerâ: No such file or directory
```
I don't understand why it's not building. I download new tar.gz but no use. Now it's not even working for  `K8S_VERSION="v0.18.0"`.

**Comment by gmarek** [comment] 2015-06-29 17:00
Also `cluster/ubuntu/skydns-rc.yaml.template` is in v1beta1, which is just embarrassing....

**Comment by thockin** [comment] 2015-06-29 17:08
The log suggests something else is holding the iptables lock.  we fixed
this at some point in teh not-too-distant past to retry at startup, but
it's possible there's another escape.  If you kill and restart the proxy,
what does the log say?

**Comment by alex-mohr** [comment] 2015-06-30 00:35
[Seems to be re: kube-proxy, so moving to team/cluster]

**Comment by WIZARD-CXY** [comment] 2015-06-30 01:41
@gmarek sorry , I will soon update the api vesion. stay tuned

**Comment by gmarek** [comment] 2015-06-30 05:26
@WIZARD-CXY: thanks. I didn't mean for it to sound this strong. I just didn't knew how to explain it over the IRC and felt embarrassed:)

**Comment by gangadhars** [comment] 2015-06-30 05:45
I build kubenetes with version 0.19.3. When I run `kube-up.sh`, these are the kube-proxy logs. 

```
E0629 22:23:32.367027     849 api.go:180] Unable to load endpoints: Get http://172.16.2.73:8080/api/v1/endpoints: dial tcp 172.16.2.73:8080: connection refused
E0629 22:23:32.371421     849 api.go:108] Unable to load services: Get http://172.16.2.73:8080/api/v1/services: dial tcp 172.16.2.73:8080: connection refused
E0629 22:37:06.129114    6992 api.go:180] Unable to load endpoints: Get http://172.16.2.73:8080/api/v1/endpoints: dial tcp 172.16.2.73:8080: connection refused
E0629 22:37:06.137588    6992 api.go:108] Unable to load services: Get http://172.16.2.73:8080/api/v1/services: dial tcp 172.16.2.73:8080: connection refused
```

**Comment by WIZARD-CXY** [comment] 2015-06-30 05:49
It means kube-proxy can't connect to the apiserver. Make sure your apiserver is healthy and see if there exists some network issue

**Comment by thockin** [comment] 2015-06-30 05:53
is 172.16.2.73 a node or the master?  Above you show it as a node, but you
are trying to connect to it as if it were the master

**Comment by gangadhars** [comment] 2015-06-30 05:54
@thockin 172.16.2.73  is master as well as node. I configured role to "ai".

**Comment by WIZARD-CXY** [comment] 2015-06-30 05:54
@gmarek that's all right. I am updating the kube-dns now.But encounter some problems.I'm asking @thockin for help. He told me using 0.20.0 is ok.So I will give it a try.

**Comment by gangadhars** [comment] 2015-06-30 06:19
@WIZARD-CXY 
kube-controller-manager.log: 
```
E0629 23:06:14.240503   13690 reflector.go:133] Failed to list *api.PersistentVolume: Get http://127.0.0.1:8080/api/v1beta3/persistentvolumes: dial tcp 127.0.0.1:8080: connection refused
E0629 23:06:14.241930   13690 reflector.go:133] Failed to list *api.PersistentVolumeClaim: Get http://127.0.0.1:8080/api/v1beta3/persistentvolumeclaims: dial tcp 127.0.0.1:8080: connection refused
E0629 23:06:15.224364   13690 reflector.go:133] Failed to list *api.ServiceAccount: Get http://127.0.0.1:8080/api/v1beta3/serviceaccounts?fieldSelector=metadata.name%3Ddefault: dial tcp 127.0.0.1:8080: connection refused
E0629 23:06:15.234977   13690 reflector.go:133] Failed to list *api.Pod: Get http://127.0.0.1:8080/api/v1beta3/pods: dial tcp 127.0.0.1:8080: connection refused
E0629 23:06:15.240048   13690 reflector.go:133] Failed to list *api.Service: Get http://127.0.0.1:8080/api/v1beta3/services: dial tcp 127.0.0.1:8080: connection refused
E0629 23:06:15.240079   13690 reflector.go:133] Failed to list *api.Namespace: Get http://127.0.0.1:8080/api/v1beta3/namespaces: dial tcp 127.0.0.1:8080: connection refused
E0629 23:06:15.240099   13690 reflector.go:133] Failed to list *api.Pod: Get http://127.0.0.1:8080/api/v1beta3/pods: dial tcp 127.0.0.1:8080: connection refused
E0629 23:06:15.241599   13690 reflector.go:133] Failed to list *api.ReplicationController: Get http://127.0.0.1:8080/api/v1beta3/replicationcontrollers: dial tcp 127.0.0.1:8080: connection refused
E0629 23:06:15.241630   13690 reflector.go:133] Failed to list *api.Namespace: Get http://127.0.0.1:8080/api/v1beta3/namespaces: dial tcp 127.0.0.1:8080: connection refused
E0629 23:06:15.241650   13690 reflector.go:133] Failed to list *api.PersistentVolume: Get http://127.0.0.1:8080/api/v1beta3/persistentvolumes: dial tcp 127.0.0.1:8080: connection refused
E0629 23:06:15.242683   13690 reflector.go:133] Failed to list *api.PersistentVolumeClaim: Get http://127.0.0.1:8080/api/v1beta3/persistentvolumeclaims: dial tcp 127.0.0.1:8080: connection refused
W0629 23:06:18.222072   13690 nodecontroller.go:244] Missing timestamp for Node 172.16.2.96. Assuming now as a timestamp.
W0629 23:06:23.226340   13690 nodecontroller.go:244] Missing timestamp for Node 172.16.2.73. Assuming now as a timestamp.
W0629 23:06:58.265595   13690 nodecontroller.go:244] Missing timestamp for Node 172.16.2.91. Assuming now as a timestamp.
W0629 23:07:23.293167   13690 nodecontroller.go:244] Missing timestamp for Node 172.16.2.92. Assuming now as a timestamp.
```
kube-apiserver.log:
```
I0629 23:06:03.189247   13689 plugins.go:69] No cloud provider specified.
I0629 23:06:03.192779   13689 master.go:243] Node port range unspecified. Defaulting to 30000-32766.
I0629 23:06:03.197841   13689 master.go:268] Will report 172.16.2.73 as public IP address.
[restful] 2015/06/29 23:06:03 log.go:30: [restful/swagger] listing is available at https://172.16.2.73:6443/swaggerapi/
[restful] 2015/06/29 23:06:03 log.go:30: [restful/swagger] https://172.16.2.73:6443/swaggerui/ is mapped to folder /swagger-ui/
W0629 23:06:15.152228   13689 controller.go:238] Resetting endpoints for master service "kubernetes" to &{{ } {kubernetes  default    0001-01-01 00:00:00 +0000 UTC <nil> map[] map[]} [{[{172.16.2.73 <nil>}] [{ 6443 TCP}]}]}
W0629 23:06:15.852039   13689 controller.go:238] Resetting endpoints for master service "kubernetes-ro" to &{{ } {kubernetes-ro  default    0001-01-01 00:00:00 +0000 UTC <nil> map[] map[]} [{[{172.16.2.73 <nil>}] [{ 7080 TCP}]}]}
I0629 23:06:15.956062   13689 server.go:412] Serving read-only insecurely on 0.0.0.0:7080
I0629 23:06:15.956102   13689 server.go:449] Serving securely on 0.0.0.0:6443
I0629 23:06:15.956114   13689 server.go:476] Serving insecurely on 0.0.0.0:8080
I0629 23:06:17.236719   13689 server.go:459] Using self-signed cert (/var/run/kubernetes/apiserver.crt, /var/run/kubernetes/apiserver.key)
```

**Comment by WIZARD-CXY** [comment] 2015-06-30 06:30
seems after `23:06:15.956114` the apiserver is ok. You can run `nc ` which I give you above on your  node to see if it's ok

**Comment by gangadhars** [comment] 2015-06-30 06:38
@WIZARD-CXY 
#nc -zv 172.16.2.73 8080
```
Connection to 172.16.2.73 8080 port [tcp/http-alt] succeeded!
```

**Comment by WIZARD-CXY** [comment] 2015-06-30 06:41
So kube-proxy should able talk to the apiserver. you can check the log again

**Comment by gangadhars** [comment] 2015-06-30 06:44
There are no new logs. @WIZARD-CXY

**Comment by WIZARD-CXY** [comment] 2015-06-30 06:45
try 'sudo service kube-proxy restart` to restart proxy ?

**Comment by gangadhars** [comment] 2015-06-30 06:55
service kube-proxy restart
```
kube-proxy stop/waiting
kube-proxy start/running, process 27598
```
kube-proxy.log:
No new logs. Showing old ones only.
```
E0629 23:39:05.667750   22927 api.go:180] Unable to load endpoints: Get http://172.16.2.73:8080/api/v1beta3/endpoints: dial tcp 172.16.2.73:8080: connection refused
E0629 23:39:05.668060   22927 api.go:108] Unable to load services: Get http://172.16.2.73:8080/api/v1beta3/services: dial tcp 172.16.2.73:8080: connection refused
E0629 23:43:01.060838   24548 api.go:180] Unable to load endpoints: Get http://172.16.2.73:8080/api/v1beta3/endpoints: dial tcp 172.16.2.73:8080: connection refused
E0629 23:43:01.064583   24548 api.go:108] Unable to load services: Get http://172.16.2.73:8080/api/v1beta3/services: dial tcp 172.16.2.73:8080: connection refused
```

**Comment by thockin** [comment] 2015-06-30 07:00
I see two things wrong,"http" and the port number.  Shouldn't it just be
https://master-ip ?  ps auxw | grep kube-proxy ?

**Comment by WIZARD-CXY** [comment] 2015-06-30 07:05
@thockin The ubuntu k8s is not using https based apiserver unless @gangadhars configured himself

**Comment by thockin** [comment] 2015-06-30 07:10
I thought we totally turned off non-https at this point.  I could be wrong.

**Comment by gangadhars** [comment] 2015-06-30 07:31
How can I configure k82 to use https?

**Comment by thockin** [comment] 2015-06-30 18:43
I don't know the Ubuntu setup, but the primary platforms are all HTTPS - is
there even a non-https port open any more?  On my master I see :8080 bound
to localhost only and :443 exposed.

**Comment by gangadhars** [comment] 2015-07-01 06:16
When I try to deploy loadbalancer I got below logs. 

kube-proxy.logs:
```
E0630 22:57:48.194820   31297 api.go:180] Unable to load endpoints: Get http://172.16.2.73:8080/api/v1beta3/endpoints: dial tcp 172.16.2.73:8080: connection refused
E0630 22:57:48.195091   31297 api.go:108] Unable to load services: Get http://172.16.2.73:8080/api/v1beta3/services: dial tcp 172.16.2.73:8080: connection refused
I0630 23:07:43.465423   31297 proxier.go:469] Opened iptables from-containers public port for service "default/guestbook:" on TCP port 32586
I0630 23:07:43.473430   31297 proxier.go:480] Opened iptables from-host public port for service "default/guestbook:" on TCP port 32586
E0630 23:09:43.193143   31297 proxier.go:153] Failed to ensure iptables: error creating chain "KUBE-PORTALS-CONTAINER": exit status 4: Another app is currently holding the xtables lock. Perhaps you want to use the -w option?
E0630 23:09:43.199048   31297 proxier.go:391] Failed to install iptables KUBE-PORTALS-CONTAINER rule for service "default/kubernetes:"
E0630 23:09:43.199240   31297 proxier.go:168] Failed to ensure portal for "default/kubernetes:": error checking rule: exit status 4: Another app is currently holding the xtables lock. Perhaps you want to use the -w option?
E0630 23:09:43.205587   31297 proxier.go:391] Failed to install iptables KUBE-PORTALS-CONTAINER rule for service "default/kubernetes-ro:"
E0630 23:09:43.205704   31297 proxier.go:168] Failed to ensure portal for "default/kubernetes-ro:": error checking rule: exit status 4: Another app is currently holding the xtables lock. Perhaps you want to use the -w option?
E0630 23:09:43.216212   31297 proxier.go:391] Failed to install iptables KUBE-PORTALS-CONTAINER rule for service "default/redis-master:"
E0630 23:09:43.216316   31297 proxier.go:168] Failed to ensure portal for "default/redis-master:": error checking rule: exit status 4: Another app is currently holding the xtables lock. Perhaps you want to use the -w option?
E0630 23:09:43.220081   31297 proxier.go:391] Failed to install iptables KUBE-PORTALS-CONTAINER rule for service "default/redis-slave:"
E0630 23:09:43.220199   31297 proxier.go:168] Failed to ensure portal for "default/redis-slave:": error checking rule: exit status 4: Another app is currently holding the xtables lock. Perhaps you want to use the -w option?
E0630 23:09:43.224776   31297 proxier.go:391] Failed to install iptables KUBE-PORTALS-CONTAINER rule for service "default/guestbook:"
E0630 23:09:43.224895   31297 proxier.go:168] Failed to ensure portal for "default/guestbook:": error checking rule: exit status 4: Another app is currently holding the xtables lock. Perhaps you want to use the -w option?
E0630 23:09:43.228723   31297 proxier.go:391] Failed to install iptables KUBE-PORTALS-CONTAINER rule for service "default/kube-dns:"
E0630 23:09:43.228838   31297 proxier.go:168] Failed to ensure portal for "default/kube-dns:": error checking rule: exit status 4: Another app is currently holding the xtables lock. Perhaps you want to use the -w option?
E0630 23:10:03.409218   31297 proxysocket.go:92] Dial failed: dial tcp 10.1.90.8:3000: i/o timeout
E0630 23:10:05.409586   31297 proxysocket.go:92] Dial failed: dial tcp 11.1.28.9:3000: i/o timeout
E0630 23:10:09.409909   31297 proxysocket.go:92] Dial failed: dial tcp 10.1.96.10:3000: i/o timeout
E0630 23:10:17.410315   31297 proxysocket.go:92] Dial failed: dial tcp 10.1.90.8:3000: i/o timeout
E0630 23:10:17.410376   31297 proxysocket.go:126] Failed to connect to balancer: failed to connect to an endpoint.
E0630 23:10:18.410938   31297 proxysocket.go:92] Dial failed: dial tcp 11.1.28.9:3000: i/o timeout
E0630 23:10:20.411289   31297 proxysocket.go:92] Dial failed: dial tcp 10.1.96.10:3000: i/o timeout
E0630 23:10:24.411627   31297 proxysocket.go:92] Dial failed: dial tcp 10.1.90.8:3000: i/o timeout
E0630 23:10:32.411905   31297 proxysocket.go:92] Dial failed: dial tcp 11.1.28.9:3000: i/o timeout
```

**Comment by thockin** [comment] 2015-07-01 06:20
Is something else holding the iptables lock?  Some other firewall process
or something?  Firewalld?

**Comment by gangadhars** [comment] 2015-07-01 06:25
@thockin No. firewall is inactive. 
```
# ufw status
Status: inactive
```

**Comment by thockin** [comment] 2015-07-01 06:40
SOMETHING is holding that lock.  `ps auxww` and `netstat -nap` please?

**Comment by gangadhars** [comment] 2015-07-13 05:25
Thanks guys. It's not the proxy problem. Flannel is not running properly. Running ```/root/kube/reconfDocker.sh``` on every node solved the problem. And I tested this on v18. Please update "cluster/ubuntu/skydns-rc.yaml.template" to v1 so that we can use v0.19.3.

**Comment by WIZARD-CXY** [comment] 2015-07-13 05:29
@gangadhars Please check out the latest ubuntu dns deployment approach.It was updated to v1.

**Comment by gangadhars** [comment] 2015-07-13 05:52
Can you provide the link to latest dns deplyment approach? I still seeing v1beeta1 [here](https://github.com/GoogleCloudPlatform/kubernetes/blob/v0.21.1/cluster/ubuntu/skydns-rc.yaml.template)  @WIZARD-CXY

**Comment by WIZARD-CXY** [comment] 2015-07-13 05:57
https://github.com/GoogleCloudPlatform/kubernetes/blob/master/cluster/ubuntu/skydns-rc.yaml.template
It's in master branch.You can use master branch's `deployAddons.sh` to deloy dns.

**Comment by gangadhars** [comment] 2015-07-13 06:00
Thank @WIZARD-CXY. You can close the issue.

**Comment by gmarek** [comment] 2015-07-13 08:13
Thanks @WIZARD-CXY. Closing the issue.

**Closed by gmarek** 2015-07-13 08:13 UTC
Labels: kind/friction, priority/P1, team/cluster
