### ISSUE TITLE
Kubelet syncPod looks like it will start pods that have a 'Succeded' pod phase after a cold-start

### ISSUE THREAD

**Issue by smarterclayton** [GoogleCloudPlatform/kubernetes#7250] opened 2015-04-23 20:57 UTC
Kubelet#SyncPods skips pods that are api.PodFailed, but not pods that are api.PodSucceeded.  This means runOnce success pods get restarted.

Is my reading of the code (we have reports of this behavior) accurate?

**Comment by dchen1107** [comment] 2015-04-23 21:16
@ArtfulCoder Could you please take a look at this?

**Comment by yujuhong** [comment] 2015-04-23 22:16
@smarterclayton, the [code you saw](https://github.com/GoogleCloudPlatform/kubernetes/blob/master/pkg/kubelet/kubelet.go#L1504) was to filter out rejected pods only (the ones could not be run due to problems such as host port conflict, etc). The rejected pods were set to `api.PodFailed earlier` in the code. It has the unintentional side effect that prevents kubelet from syncing the already failed pods.

When per-pod workers are syncing In `syncPod`, they actually look at [the status and restart policy](
https://github.com/GoogleCloudPlatform/kubernetes/blob/master/pkg/kubelet/kubelet.go#L1069) to decide whether to restart the containers. Therefore, kubelet functions as expected.

We should probably make them more consistent -- either both (api.PodFailed & api.PodSucceeded) of them should run `syncPod` or none of should, but this is probably not a p1 bug.

**Comment by smarterclayton** [comment] 2015-04-23 22:39
> On Apr 23, 2015, at 6:17 PM, Yu-Ju Hong <notifications@github.com> wrote:
> 
> @smarterclayton, the code you saw was to filter out rejected pods only (the ones could not be run due to problems such as host port conflict, etc). The rejected pods were set to api.PodFailed earlier in the code. It has the unintentional side effect that prevents kubelet from syncing the already failed pods.
> 
> When per-pod workers are syncing In syncPod, they actually look at the status and restart policy to decide whether to restart the containers. Therefore, kubelet functions as expected.
> 
Ok, just want to verify because on our ~2 week old fork we are seeing terminated pods in Succeeded be restarted on reboot.  I have not yet tested against master but will do so.  Feel free to close this issue and I will reopen if we can get a recreation.

**Comment by yujuhong** [comment] 2015-04-23 23:39
If you have seen this happened, we should not close this bug :)

After giving this a bit more thoughts, I *think* this could happen if the dead containers were all removed (either GC'd by kubelet or lost for other reasons since in your case it happened after the reboot), and then kubelet concludes that the containers were never run and hence decided to start it. In this case, it may never check the restart policy at all. 

I'll need to verify this, but I think it's a possibility. It should rarely happen because our GC policy is not very aggressive...

I think I'm more convinced now that kubelet should pre-filter out all the pods in the terminated state since the pods should not transition out from there. We could double check this condition when syncing to prevent corner cases where kubelet is syncing the terminated pod again before observing the final state transition.

**Comment by smarterclayton** [comment] 2015-04-24 00:03
> On Apr 23, 2015, at 7:39 PM, Yu-Ju Hong <notifications@github.com> wrote:
> 
> If you have seen this happened, we should not close this bug :)
> 
> After giving this a bit more thoughts, I think this could happen if the dead containers were all removed (either GC'd by kubelet or lost for other reasons since in your case it happened after the reboot), and then kubelet concludes that the containers were never run and hence decided to start it. In this case, it may never check the restart policy at all.
> 
I think (but am not positive) that there is a gc bug in the version we are using for short running programs that exit successfully - gc never kicks in at the max container number, or is kicking in wrong.  So the first problem may have been exacerbated by the second.  Also, I know a number of folks clean up containers with scripts, and it's possible they do something like this on reboot (I haven't been able to reproduce the problem yet so I don't know).

**Comment by yujuhong** [comment] 2015-04-24 01:11
I will try to reproduce it tomorrow. If my theory is correct, I should be able to see this happen by manually removing the containers of a succeeded pod.

@smarterclayton, is there a bug open for the erratic GC behaviors you've observed? The container GC code hasn't been touched since its inception, so whatever bugs you discovered are likely to be in HEAD. Given that kubelet relies on inspecting dead containers for information, we should get GC working properly to reduce the need of a separate cleanup script, which could lead to more unexpected behaviors.

**Comment by smarterclayton** [comment] 2015-04-24 01:24
> On Apr 23, 2015, at 9:12 PM, Yu-Ju Hong <notifications@github.com> wrote:
> 
> I will try to reproduce it tomorrow. If my theory is correct, I should be able to see this happen by manually removing the containers of a succeeded pod.
> 
> @smarterclayton, is there a bug open for the erratic GC behaviors you've observed?
> 
Not on Kube, I have repro scenarios I will open.

**Comment by TomasTomecek** [comment] 2015-04-24 09:44
> I should be able to see this happen by manually removing the containers of a succeeded pod.

Exactly.

```
$ get pods
POD                           IP                  CONTAINER(S)        IMAGE(S)            HOST                     LABELS                              STATUS              CREATED
sadc-docker-20150423-090732                       custom-build        buildroot           the-host/172.16.125.41   build=sadc-docker-20150423-090732   Succeeded           26 hours

$ docker ps -a
CONTAINER ID        IMAGE                         COMMAND                CREATED             STATUS                         PORTS               NAMES
8a4844ca5c6b        buildroot:latest              "dock --verbose insi   About an hour ago   Exited (0) About an hour ago                       k8s_custom-build.cf288666_sadc-docker-20150423-090732_default_6c5956b5-e987-11e4-bf2f-fa163e1012c3_53956136

$ docker rm 8a4844ca5c6b
8a4844ca5c6b

<waiting for like 10 seconds>

$ docker ps
CONTAINER ID        IMAGE                         COMMAND                CREATED             STATUS              PORTS               NAMES
12b6c85e6624        buildroot:latest              "dock --verbose insi   10 seconds ago      Up 8 seconds                            k8s_custom-build.cf288666_sadc-docker-20150423-090732_default_6c5956b5-e987-11e4-bf2f-fa163e1012c3_3e6e4c2a
7bf047627ec0        openshift/origin-pod:v0.3.3   "/pod"                 12 seconds ago      Up 9 seconds                            k8s_POD.8081d85a_sadc-docker-20150423-090732_default_6c5956b5-e987-11e4-bf2f-fa163e1012c3_2d624f8b

$ get pods
POD                           IP                  CONTAINER(S)        IMAGE(S)            HOST                     LABELS                              STATUS              CREATED
sadc-docker-20150423-090732   172.17.1.11         custom-build        buildroot           the-host/172.16.125.41   build=sadc-docker-20150423-090732   Running             26 hours
```

I'm pretty sure that @smarterclayton will provide more precise reproducer using plain k8s (in here I used openshift v3).

**Comment by yujuhong** [comment] 2015-04-24 17:18
@TomasTomecek, thanks for the reproduce.

I just tried and I could easily reproduce this on a localhost as well. I will write up a PR to fix this.

**Comment by TomasTomecek** [comment] 2015-04-25 06:30
Thanks @yujuhong! Will try to verify on Monday.

**Comment by yujuhong** [comment] 2015-05-11 20:12
@TomasTomecek, were you able to verify the fix?

**Comment by TomasTomecek** [comment] 2015-05-13 19:08
@yujuhong was waiting until this lands in openshift. We are in a process of testing this now, so will report in a couple of days.

**Comment by yujuhong** [comment] 2015-06-24 23:22
@TomasTomecek, I am closing this assuming the issue has been fixed. Feel free to reopen if it's not true :)

**Closed by yujuhong** 2015-06-24 23:22 UTC
Labels: component/kubelet, kind/bug, priority/P2, team/node
