### ISSUE TITLE
Can't create external load balancer

### ISSUE THREAD

**Issue by satnam6502** [GoogleCloudPlatform/kubernetes#8799] opened 2015-05-26 06:28 UTC
```
$ cat mytunes-service.yaml
kind: Service
metadata:
  name: mytunes
  namespace: mytunes
  labels:
    app: mytunes
spec:
  selector:
    app: mytunes
  ports:
  - name: db
    port: 9200
    targetPort: es
  - name: ui
    port: 5601
    targetPort: kibana
  createExternalLoadBalancer: true
satnam-macbookpro2:blog-logging satnam$ kubectl get service mytunes --namespace=mytunes
NAME      LABELS        SELECTOR      IP(S)        PORT(S)
mytunes   app=mytunes   app=mytunes   10.0.58.74   9200/TCP
                                                   5601/TCP
```

**Comment by roberthbailey** [comment] 2015-05-26 14:06
Are you running from head or from a stable release? A bunch of changes to the load balancers were merged on Friday....

**Comment by satnam6502** [comment] 2015-05-26 14:08
From HEAD.
```
$ kubectl version
Client Version: version.Info{Major:"0", Minor:"17", GitVersion:"v0.17.0", GitCommit:"82f8bdac06ddfacf493a9ed0fedc85f5ea62ebd5", GitTreeState:"clean"}
Server Version: version.Info{Major:"0", Minor:"17+", GitVersion:"v0.17.1-750-gcaad0b7796575a-dirty", GitCommit:"caad0b7796575a489d840ddf819b904bc1cc65c0", GitTreeState:"dirty"}
```

**Comment by satnam6502** [comment] 2015-05-26 14:12
I ended up accessing the Elasticsearch and Kibana services via the proxy at the master instead rather than through an ELB as I wanted for my demo at IFIP WG2.8 :-(

**Comment by a-robinson** [comment] 2015-05-26 22:51
The API for this has changed quite a bit over the last few days, I'm not actually sure at this point whether setting that field will work without setting the `Type` field to "LoadBalancer".
https://github.com/GoogleCloudPlatform/kubernetes/blob/master/pkg/api/v1beta3/types.go#L1063

I'll check into it a little more closely.

**Comment by a-robinson** [comment] 2015-05-26 22:54
Looks like the conversion functions were set up to ensure both fields are in sync, so that shouldn't be the issue.

I'd be interested to see the output of `kubectl get service mytunes -o yaml` (to ensure the system understood your desire for an external load balancer) as well as your kube-controller-manager logs (to see whether/why it failed to create the load balancer).

**Comment by justinsb** [comment] 2015-05-27 01:09
Yes, this is obviously supposed to work :-)

I think if you are using API v1 (and not v1beta3), then createExternalLoadBalancer is no longer supported - you have to specify spec.Type == "LoadBalancer".  And I think that kubectl ignores unknown parameters (?), so you wouldn't be warned in this case.

**Comment by a-robinson** [comment] 2015-05-27 01:11
Yes, it ignores unknown parameters, which is why getting the service back from the API would be enlightening :)

**Comment by justinsb** [comment] 2015-05-27 01:14
Yes, although I have had problems as well where if I use a kubectl that hasn't been compiled with the latest code/schema it seems to drop the new fields, so this may be tricky.  (Is that right & if so is there any way round it?)

**Comment by a-robinson** [comment] 2015-05-27 01:20
That's possible, I unfortunately don't know.

**Comment by satnam6502** [comment] 2015-05-27 07:15
```
$ kubectl get services -o json mytunes --namespace=mytunes
{
    "kind": "Service",
    "apiVersion": "v1beta3",
    "metadata": {
        "name": "mytunes",
        "namespace": "mytunes",
        "selfLink": "/api/v1beta3/namespaces/mytunes/services/mytunes",
        "uid": "13bf4eb6-0371-11e5-b44a-42010af07442",
        "resourceVersion": "1123",
        "creationTimestamp": "2015-05-26T06:33:10Z",
        "labels": {
            "app": "mytunes"
        }
    },
    "spec": {
        "ports": [
            {
                "name": "db",
                "protocol": "TCP",
                "port": 9200,
                "targetPort": "es"
            },
            {
                "name": "ui",
                "protocol": "TCP",
                "port": 5601,
                "targetPort": "kibana"
            }
        ],
        "selector": {
            "app": "mytunes"
        },
        "portalIP": "10.0.57.178",
        "createExternalLoadBalancer": true,
        "sessionAffinity": "None"
    },
    "status": {}
}
```

**Comment by satnam6502** [comment] 2015-05-27 07:18
```
$ kubectl get services -o yaml mytunes --namespace=mytunes
apiVersion: v1beta3
kind: Service
metadata:
  creationTimestamp: 2015-05-26T06:33:10Z
  labels:
    app: mytunes
  name: mytunes
  namespace: mytunes
  resourceVersion: "1123"
  selfLink: /api/v1beta3/namespaces/mytunes/services/mytunes
  uid: 13bf4eb6-0371-11e5-b44a-42010af07442
spec:
  createExternalLoadBalancer: true
  portalIP: 10.0.57.178
  ports:
  - name: db
    port: 9200
    protocol: TCP
    targetPort: es
  - name: ui
    port: 5601
    protocol: TCP
    targetPort: kibana
  selector:
    app: mytunes
  sessionAffinity: None
status: {}
```

**Comment by justinsb** [comment] 2015-05-27 11:08
OK, so v1beta3, so looks like a real failure.  The reason should be in kube-controller-manager logs.  You may be interested in #8760 for an easier way to get this info.

Every time I've seen this on GCE, it has been due to load-balancer quota being hit.  (Potential root cause: I _think_ that cluster/kube-down on GCE doesn't remove load-balancers (?) but only noticed this yesterday and haven't confirmed it yet.)

**Comment by a-robinson** [comment] 2015-05-27 15:51
@justinsb - I can confirm, kube-down doesn't touch load-balancers. We'd really like #4630 so we have a way to clean everything owned by the cluster up, but it could be put in kube-down with a bit of work.

**Comment by satnam6502** [comment] 2015-05-28 12:37
Adding `type: LoadBalancer` causes a load balancer to be ceated:
```
kind: Service
metadata:
  name: mytunes
  namespace: mytunes
  labels:
    app: mytunes
spec:
  selector:
    app: mytunes
  ports:
  - name: db
    port: 9200
    targetPort: es
  - name: ui
    port: 5601
    targetPort: kibana
  type: LoadBalancer
  createExternalLoadBalancer: true
```
and we can see the IP if we get the service:
```
$ kubectl get service mytunes -o yaml --namespace=mytunes
apiVersion: v1beta3
kind: Service
metadata:
  creationTimestamp: 2015-05-28T12:21:31Z
  labels:
    app: mytunes
  name: mytunes
  namespace: mytunes
  resourceVersion: "8713"
  selfLink: /api/v1beta3/namespaces/mytunes/services/mytunes
  uid: 12b1dada-0534-11e5-a229-42010af0c8d3
spec:
  createExternalLoadBalancer: true
  portalIP: 10.0.120.120
  ports:
  - name: db
    nodePort: 30459
    port: 9200
    protocol: TCP
    targetPort: es
  - name: ui
    nodePort: 31104
    port: 5601
    protocol: TCP
    targetPort: kibana
  selector:
    app: mytunes
  sessionAffinity: None
  type: LoadBalancer
status:
  loadBalancer:
    ingress:
    - ip: 104.197.34.51
```
and we also see it from the regular get:
```
$ kubectl get service mytunes --namespace=mytunes
NAME      LABELS        SELECTOR      IP(S)           PORT(S)
mytunes   app=mytunes   app=mytunes   10.0.120.120    9200/TCP
                                      104.197.34.51   5601/TCP
```

**Comment by quinton-hoole** [comment] 2015-05-28 14:01
FYI @a-robinson , we're still leaking a lot of load balancer resources in GCE.  I have to clean them up every few hours for our continuous integration tests.  Are you looking into improving this?

**Comment by justinsb** [comment] 2015-05-28 14:22
@satnam6502 That would be a bug - createExternalLoadBalancer=true should effectively set type=LoadBalancer .  It could be that you "got lucky" when you tried again, but I'll look into it & add a test.

@quinton-hoole Do you suspect the leak is due to a bug in destroying a service with an LB, or due to calling cluster/kube-down while an LB exists, or due to the GKE e2e issue which someone identified this weekend (I think it was @lavalamp) where you're running an old version of something in e2e testing with a known leak?  If it isn't the GKE issue, we could add a count of the GCE load balancers as part of each e2e test to fail the build whenever we leak one (vs failing some unrelated test a few hours later!)

**Comment by quinton-hoole** [comment] 2015-05-28 14:51
@justinsb the leak is probably due to the GKE issue, but I'm not sure.  Thanks for reminding me.  I'll double-check today that we don't have leaks other than that one.

**Comment by justinsb** [comment] 2015-05-28 15:00
@quinton-hoole Great.  We probably should add the load-balancer leak test to the e2e tests anyway, I just have a lot on my plate already and I don't think it is completely trivial because it involves peeking behind the scenes of the k8s API.  But if it helps us find the leak it'll be worth it!  Let me know if it doesn't seem to be the GKE issue.

**Comment by a-robinson** [comment] 2015-05-28 17:28
@quinton-hoole - yeah, adding the sleep before cluster deletion clearly didn't do the trick, unless the jenkins config syncing wasn't working yesterday. There appear to be leaks from the e2e-flaky and e2e-soak clusters as well, so I'm not sure if it's just GKE? I've still never seen one from the GCE e2es, though. I look forward to the results from splitting out GKE into its own project.

**Comment by quinton-hoole** [comment] 2015-05-28 17:41
@a-robinson No, e2e-flaky and e2e-soak are GCE, not GKE clusters.  You can see the exact definition in Jenkins.

**Comment by lavalamp** [comment] 2015-05-28 18:10
@justinsb consider making validation fail if the createExternalLoadBalancer field is on and the type != loadbalancer, that will save people like Satnam a bunch of digging.

**Comment by antoineco** [comment] 2015-06-02 20:12
@satnam6502 you mentioned that you were trying to create an ELB, is the LoadBalancer service type yet supported on AWS?

**Comment by satnam6502** [comment] 2015-06-02 20:31
@antoineco : since I am not allowed to use AWS I don't know :-)
@justinsb ?

**Comment by antoineco** [comment] 2015-06-02 21:19
Don't bother I found my answer inside the cloudprovider code. I'll try with
`createExternalLoadBalancer: true`, thanks for the tip!

**Comment by justinsb** [comment] 2015-06-03 16:05
@antoineco  AWS LB support has now merged.  It should work :-)  (If you have any issues please open a new bug & mention me and ideally AWS ELB.)

The "correct" field to set is Type on the Service Spec.  If you set that to LoadBalancer, that should create a LB.  All API versions support this field now.

API versions up to v1beta3 (but not v1) also support the (legacy)  createExternalLoadBalancer.  If you set this, and do not set Type, then Type will default to LoadBalancer.  I don't think I can validate the case of createExternalLoadBalancer & type != LoadBalancer (@lavalamp) because createExternalLoadBalancer is no longer in api/types and that is what we validate.  Suggestions welcome (if we think this is not just a transitional problem)

**Comment by lavalamp** [comment] 2015-06-03 18:41
@justinsb It sounds like the conversion code should be setting type based on createELB. But we're removing v1beta1, so I guess it's too late to fix.

**Comment by justinsb** [comment] 2015-06-03 20:22
@lavalamp I don't really understand ... here's the code for v1beta3; I think it does what you're asking for:  https://github.com/GoogleCloudPlatform/kubernetes/blob/master/pkg/api/v1beta3/conversion.go#L365-L375

Maybe I could throw a validation error there if createELB & type != LoadBalancer, but I don't think validation is supposed to be happening in here.

**Comment by lavalamp** [comment] 2015-06-03 20:31
Ah, maybe it has a bad interaction with the defaulting code, which runs first: https://github.com/GoogleCloudPlatform/kubernetes/blob/32bb3ae8f170a3d2d410ea097739ab4964cccc3e/pkg/api/v1beta3/defaults.go#L72

**Comment by satnam6502** [comment] 2015-06-03 21:25
So is having to add `type: LoadBalancer` to make my load balancer work still a bug then?

**Comment by justinsb** [comment] 2015-06-03 21:48
If you have to include that (as well as createExternalLoadBalancer: true) with v1beta3, then yes, that is a bug @satnam6502.  (With v1, there is no createELB)

I just tried the guestbook-go example (`find examples/guestbook-go -name "*.json" | xargs -I {} kubectl create -f {}` against master (on AWS) and it worked (created an LB, visible in `kubectl get services guestbook -ojson` and in `kubectl describe services guestbook`)

But note that it was visible in `Client Version: version.Info{Major:"0", Minor:"18+", GitVersion:"v0.18.0-331-g14f9b778f16444", GitCommit:"14f9b778f164444462200031a38e95dc0aae4bcd", GitTreeState:"clean"}` but _not_ in `Client Version: version.Info{Major:"0", Minor:"17", GitVersion:"v0.17.0", GitCommit:"82f8bdac06ddfacf493a9ed0fedc85f5ea62ebd5", GitTreeState:"clean"}`

So is it still failing for you with the guestbook-go example (and I presume you're running on GCE)?  And can you try with a newer client version if you're on 0.17?  (Anyone know if there is a way to actually show the raw JSON?)

**Comment by satnam6502** [comment] 2015-06-03 22:22
It worked with guestbook with the one attempt I made -- but I worry that
this might be a flaky thing?
For my music service example it seems to always fail unless I add the type.

S

**Comment by justinsb** [comment] 2015-06-03 22:50
So if the problem is  flakiness we're trying to address by capturing events on failure (done, I think), and maybe adding a LoadBalancer Creation status to Status (#8992 #9106).  The problem has often been quota, but we don't know if there is another problem also.

The music service case is weird, especially if you do see guestbook-go working with the same createELB/type combination.  It suggests a bug in the service configuration (e.g. that it doesn't work with two ports), but that doesn't make sense if it then works when you specify the type.  I'm inclined to believe flakiness and bad luck.  Any chance we can get the logs from a failed attempt at creating an LB (`/var/log/kube-controller-manager.log` in particular)?

**Comment by satnam6502** [comment] 2015-06-03 23:09
Ugh. Do we need to explicitly create namespaces now?

$ kubectl create -f mytunes-pod-v1.yaml --namespace=mytunes
Error from server: Pod "mytunes-v1" is forbidden: Namespace mytunes does
not exist

**Comment by justinsb** [comment] 2015-06-03 23:26
(Don't know, but maybe #8696.  I haven't really started using namespaces yet myself)

**Comment by satnam6502** [comment] 2015-06-03 23:31
Well once I can create the pods and service I will get you your logs :-)

**Comment by satnam6502** [comment] 2015-06-03 23:47
Still in pain #9224

**Comment by lavalamp** [comment] 2015-06-05 00:34
@satnam6502 Yes, you have to pre-create namespace now.

**Comment by satnam6502** [comment] 2015-06-05 13:11
I now find that even adding the type the load balancer still does not get created.

**Comment by satnam6502** [comment] 2015-06-05 13:13
```
satnam@satnam-linux:~/gocode/src/github.com/GoogleCloudPlatform/kubernetes/examples/blog-logging$ kubectl get -o yaml service mytunes --namespace=mytunes
apiVersion: v1beta3
kind: Service
metadata:
  creationTimestamp: 2015-06-05T13:10:41Z
  labels:
    app: mytunes
  name: mytunes
  namespace: mytunes
  resourceVersion: "155088"
  selfLink: /api/v1beta3/namespaces/mytunes/services/mytunes
  uid: 445a9286-0b84-11e5-9108-42010af02fe3
spec:
  createExternalLoadBalancer: true
  portalIP: 10.0.121.67
  ports:
  - name: db
    nodePort: 0
    port: 9200
    protocol: TCP
    targetPort: es
  - name: ui
    nodePort: 0
    port: 5601
    protocol: TCP
    targetPort: kibana
  publicIPs:
  - 104.197.86.235
  selector:
    app: mytunes
  sessionAffinity: None
  type: LoadBalancer
status:
  loadBalancer: {}
```

**Comment by satnam6502** [comment] 2015-06-05 13:18
The reported LB works but doing a `get` on the service does not report it.
```
$ make get
kubectl get pods,services,endpoints --namespace=mytunes
POD          IP           CONTAINER(S)    IMAGE(S)            HOST                                   LABELS                   STATUS    CREATED   MESSAGE
mytunes-v1   10.244.3.5                                       kubernetes-minion-yssx/104.197.39.67   app=mytunes,version=v1   Running   2 hours   
                          kibana          satnam6502/kibana                                                                   Running   2 hours   
                          elasticsearch   elasticsearch                                                                       Running   2 hours   
NAME      LABELS        SELECTOR      IP(S)         PORT(S)
mytunes   app=mytunes   app=mytunes   10.0.121.67   9200/TCP
                                                    5601/TCP
NAME      ENDPOINTS
mytunes   10.244.3.5:5601,10.244.3.5:9200
```

**Comment by thockin** [comment] 2015-07-13 23:09
is this still alive or can we close it?

**Closed** 2015-07-13 23:14 UTC
Labels: kind/bug, priority/P2, team/cluster
