### ISSUE TITLE
Cluster addons make large clusters unstable (user container's oom_score_adj is misconfigured)

### ISSUE THREAD

**Issue by bprashanth** [GoogleCloudPlatform/kubernetes#9788] opened 2015-06-15 03:31 UTC
1. Setup a 100 node cluster with 0 extra pods
2. Periodically run `kubectl get pods | sort -k 5 -u` till you notice a youger cluster addon, eg:
```
monitoring-heapster-v2-jnxgm                       1/1       Running   0          10m
monitoring-influx-grafana-v1-7kqyf                 2/2       Running   0          17m
fluentd-elasticsearch-e2e-test-beeps-minion-1khh   1/1       Running   0          1h
elasticsearch-logging-v1-abm8p                     1/1       Running   0          2h
fluentd-elasticsearch-e2e-test-beeps-minion-m251   1/1       Running   0          31m
fluentd-elasticsearch-e2e-test-beeps-minion-i8ke   1/1       Running   1          7m
NAME                                               READY     REASON    RESTARTS   AGE
```
At this point you'll probably have some dead nodes, or at least a kubelet restart (related:  https://github.com/GoogleCloudPlatform/kubernetes/issues/7815).

Additional information:
- All my dead nodes had at least 1 addon eg:
```
e2e-test-beeps-minion-0so1   kubernetes.io/hostname=e2e-test-beeps-minion-0so1   NotReady
e2e-test-beeps-minion-0v0x   kubernetes.io/hostname=e2e-test-beeps-minion-21dm   NotReady


cat ~/logs/kube-scheduler.log | grep "Attempting to bind"
I0614 03:23:58.132034      12 factory.go:312] Attempting to bind monitoring-heapster-v2-mtr9x to e2e-test-beeps-minion-0so1
I0614 04:01:28.134103      12 factory.go:312] Attempting to bind elasticsearch-logging-v1-0fjuw to e2e-test-beeps-minion-21dm
```     

- A spike in cpu/memory usage often occurs just before the restart (and it spikes fast, in ~30m):
```
beeps@e2e-test-beeps-minion-21dm:~$ sudo atop -r /var/log/atop/atop_20150614 -b 3:20 -C | grep "PID" -A 3 | head -3
  PID  SYSCPU  USRCPU  VGROW  RGROW  RDDSK  WRDSK ST EXC S  CPU CMD            
11230  20.09s   2m29s     0K     0K     4K   1.6G --   - S  29% java           
 3414   7.08s   9.21s     0K   248K   820K  1032K --   - S   3% kubelet        

beeps@e2e-test-beeps-minion-21dm:~$ sudo atop -r /var/log/atop/atop_20150614 -b 4:00 -C | grep "PID" -A 3 | head -3
  PID  SYSCPU  USRCPU  VGROW  RGROW  RDDSK  WRDSK ST EXC S  CPU CMD            
11230  34.74s   5m01s     0K 272.4M 799.8M 647.7M --   - S  93% java           
 3414  19.81s  20.57s 16392K -4684K   1.0G  2324K --   - S  11% kubelet   
```

- This affects the sd of syncPod response times (and obviously during the outage syncPod doesn't run):
```
I0614 03:52:47.433688    3414 kubelet.go:1121] (kubelet) syncPod = net time for pod elasticsearch-logging-v1-0fjuw 24.630828ms
I0614 03:52:57.639778    3414 kubelet.go:1121] (kubelet) syncPod = net time for pod elasticsearch-logging-v1-0fjuw 192.807391ms
I0614 03:53:07.621054    3414 kubelet.go:1121] (kubelet) syncPod = net time for pod elasticsearch-logging-v1-0fjuw 167.872516ms
I0614 03:53:17.644948    3414 kubelet.go:1121] (kubelet) syncPod = net time for pod elasticsearch-logging-v1-0fjuw 185.237351ms
I0614 03:53:27.494427    3414 kubelet.go:1121] (kubelet) syncPod = net time for pod elasticsearch-logging-v1-0fjuw 29.206469ms
I0614 03:53:37.651265    3414 kubelet.go:1121] (kubelet) syncPod = net time for pod elasticsearch-logging-v1-0fjuw 175.375625ms
I0614 03:53:47.655602    3414 kubelet.go:1121] (kubelet) syncPod = net time for pod elasticsearch-logging-v1-0fjuw 32.494134ms
I0614 03:53:57.655484    3414 kubelet.go:1121] (kubelet) syncPod = net time for pod elasticsearch-logging-v1-0fjuw 18.381837ms
I0614 03:54:07.664289    3414 kubelet.go:1121] (kubelet) syncPod = net time for pod elasticsearch-logging-v1-0fjuw 24.411221ms
I0614 03:54:17.687201    3414 kubelet.go:1121] (kubelet) syncPod = net time for pod elasticsearch-logging-v1-0fjuw 38.721561ms
I0614 03:54:27.692326    3414 kubelet.go:1121] (kubelet) syncPod = net time for pod elasticsearch-logging-v1-0fjuw 33.002448ms
I0614 03:54:37.888149    3414 kubelet.go:1121] (kubelet) syncPod = net time for pod elasticsearch-logging-v1-0fjuw 221.385ms
I0614 03:54:47.702193    3414 kubelet.go:1121] (kubelet) syncPod = net time for pod elasticsearch-logging-v1-0fjuw 29.895014ms
I0614 03:54:57.707271    3414 kubelet.go:1121] (kubelet) syncPod = net time for pod elasticsearch-logging-v1-0fjuw 28.48375ms
I0614 03:55:08.134910    3414 kubelet.go:1121] (kubelet) syncPod = net time for pod elasticsearch-logging-v1-0fjuw 449.835487ms
I0614 03:55:18.859870    3414 kubelet.go:1121] (kubelet) syncPod = net time for pod elasticsearch-logging-v1-0fjuw 920.379739ms
I0614 03:55:28.427633    3414 kubelet.go:1121] (kubelet) syncPod = net time for pod elasticsearch-logging-v1-0fjuw 302.093733ms
```

- Sometimes there are OOMs, these don't affect the kubelet, but the node eventually dies. 
```
beeps@e2e-test-beeps-minion-r1ms:~$ cat /var/log/kern.log | grep "Out of"
Jun 14 03:06:48 e2e-test-beeps-minion-r1ms kernel: [31683.055354] Out of memory: Kill process 16730 (manage_accounts) score 4 or sacrifice child
Jun 14 03:06:48 e2e-test-beeps-minion-r1ms kernel: [31683.251853] Out of memory: Kill process 2343 (manage_addresse) score 4 or sacrifice child
Jun 14 03:06:55 e2e-test-beeps-minion-r1ms kernel: [31684.094101] Out of memory: Kill process 2354 (manage_clock_sy) score 4 or sacrifice child

beeps@e2e-test-beeps-minion-r1ms:~$ cat /var/log/kubelet.log | grep fork
I0614 03:06:07.173569    3392 container.go:363] Failed to update stats for container "/e84a731222ad0fcef8bdc713ca4aaa6a2e8c7df1dcdc38fe342deb05506dcfd6": du command failed on /var/lib/docker/aufs/diff/e84a731222ad0fcef8bdc713ca4aaa6a2e8c7df1dcdc38fe342deb05506dcfd6 with output  - fork/exec /usr/bin/du: cannot allocate memory, continuing to push stats
I0614 03:06:07.025625    3392 container.go:363] Failed to update stats for container "/0f8c0eaf2805abf74565fac3cd0cf781e332160f27d2aaa7cd4db45aa5609d27": du command failed on /var/lib/docker/aufs/diff/0f8c0eaf2805abf74565fac3cd0cf781e332160f27d2aaa7cd4db45aa5609d27 with output  - fork/exec /usr/bin/du: cannot allocate memory, continuing to push stats

... but kubelet is still healthy...

I0614 03:19:20.606510   17152 manager.go:750] (kubelet) dockermanager dockertools GetPods took 1.928699ms
I0614 03:19:20.708280   17152 manager.go:750] (kubelet) dockermanager dockertools GetPods took 1.572725ms
I0614 03:19:20.810046   17152 manager.go:750] (kubelet) dockermanager dockertools GetPods took 1.559437ms
I0614 03:19:20.912091   17152 manager.go:750] (kubelet) dockermanager dockertools GetPods took 1.864913ms
I0614 03:19:21.013862   17152 manager.go:750] (kubelet) dockermanager dockertools GetPods took 1.596476ms

... logs are quiet till I reset the node at 18:18 ...

I0614 18:18:49.292671    2208 server.go:269] Using root directory: /var/lib/kubelet
I0614 18:18:49.292740    2208 manager.go:126] cAdvisor running in container: "/"
```

- Sometimes the kubelet restart without any OOMs, grep nodecontroller logs for evidence:
```
(test_clean_master)$ cat ~/logs/kcm | grep PodEvi
I0614 23:42:45.843681       5 podevictor.go:110] PodEvictor is evicting Pods on Node: e2e-test-beeps-minion-gjds
I0614 23:50:50.927087       5 podevictor.go:110] PodEvictor is evicting Pods on Node: e2e-test-beeps-minion-c5ok
I0614 23:57:14.960444       5 podevictor.go:110] PodEvictor is evicting Pods on Node: e2e-test-beeps-minion-g6wk
I0615 00:21:55.186406       5 podevictor.go:110] PodEvictor is evicting Pods on Node: e2e-test-beeps-minion-hawh
```

related (although you don't need any extra pods to reproduce this issue): https://github.com/GoogleCloudPlatform/kubernetes/issues/7815

**Comment by dchen1107** [comment] 2015-06-15 16:47
Couple comments related to the issue:

1) Why does scheduler try to bind a addons pod to not_ready nodes at the first place?
2) What is the job with process id 11230? I bet it is elasticssearch one since I observed it is using a lot of cpu constantly before.
3) Can you share more kernel log on that oom node? Do you know how many pods are scheduled to the node at a given time when oom occurs? And why? no spreading from scheduler  at all?

**Comment by bprashanth** [comment] 2015-06-15 17:05
> 1) Why does scheduler try to bind a addons pod to not_ready nodes at the first place?

It doesn't, the pod bounces around NotReadying nodes.


> 2) What is the job with process id 11230? I bet it is elasticssearch one since I observed it is using a lot of cpu constantly before.

It's always either heapster or elasticsearch, the java job in the example is elasticsearch.


> 3) Can you share more kernel log on that oom node? 

This is from another node I just reset. 
https://gist.github.com/bprashanth/32c9d22cc39b961a395f

td-agent is the event collector daemon used by fluentd:
```

Jun 15 03:51:32 e2e-test-beeps-minion-1nm0 kernel: [15718.015838] Out of memory: Kill process 3931 (td-agent) score 19 or sacrifice child
Jun 15 03:51:32 e2e-test-beeps-minion-1nm0 kernel: [15718.023653] Killed process 3931 (td-agent) total-vm:390900kB, anon-rss:34360kB, file-rss:4kB
```


> Do you know how many pods are scheduled to the node at a given time when oom occurs? 


2, fluentd and heapster.

```
$ cat ~/logs/kcm  | grep -i "evicting pods.* e2e-test-beeps-minion-1nm0" -A 5
I0615 03:56:01.550502       5 podevictor.go:110] PodEvictor is evicting Pods on Node: e2e-test-beeps-minion-1nm0
I0615 03:56:01.550534       5 nodecontroller.go:427] Delete all pods from e2e-test-beeps-minion-1nm0
W0615 03:56:01.550549       5 request.go:302] field selector: v1 - pods - spec.host - e2e-test-beeps-minion-1nm0: need to check if this is versioned correctly.
I0615 03:56:01.560933       5 nodecontroller.go:438] Delete pod fluentd-elasticsearch-e2e-test-beeps-minion-1nm0
I0615 03:56:01.582468       5 nodecontroller.go:438] Delete pod monitoring-heapster-v2-9dluc
I0615 03:56:01.600577       5 replication_controller.go:305] Too few "default"/"monitoring-heapster-v2" replicas, need 1, creating 1

```

All I have are the cluster addons on this cluster

```
$ kubectl get rc
elasticsearch-logging-v1       elasticsearch-logging   gcr.io/google_containers/elasticsearch:1.4        k8s-app=elasticsearch-logging,version=v1   2
kibana-logging-v1              kibana-logging          gcr.io/google_containers/kibana:1.3               k8s-app=kibana-logging,version=v1          1
kube-dns-v3                    etcd                    gcr.io/google_containers/etcd:2.0.9               k8s-app=kube-dns,version=v3                1
                               kube2sky                gcr.io/google_containers/kube2sky:1.9                                                        
                               skydns                  gcr.io/google_containers/skydns:2015-03-11-001                                               
monitoring-heapster-v2         heapster                gcr.io/google_containers/heapster:v0.14.0         k8s-app=heapster,version=v2                1
monitoring-influx-grafana-v1   influxdb                gcr.io/google_containers/heapster_influxdb:v0.3   k8s-app=influxGrafana,version=v1           1
                               grafana                 gcr.io/google_containers/heapster_grafana:v0.7                       
```

**Comment by dchen1107** [comment] 2015-06-15 17:26
cc/ @thockin on general cluster issues. 

cc/ @saad-ali and @ArtfulCoder  since they are working on heapster scalability issue. Can we have resource limit specified for our addons service? Especially monitoring and logging ones? 

@vishh Why we only have one replica of heaster for monitoring?

**Comment by bprashanth** [comment] 2015-06-15 17:38
Trying to figure out what it's logging I found that on most nodes /var/lib/docker/containers just has 2 containers, pause and fluentd, and neither of them log anything. On some nodes there are more, I guess these are the influxdb and es containers. They produce logs:
https://gist.github.com/bprashanth/5f7949b37aabade3023c

So maybe just telling those 2 to stay really quiet might help.

**Comment by dchen1107** [comment] 2015-06-15 17:41
cc/ @satnam6502 on logging side  (https://github.com/GoogleCloudPlatform/kubernetes/issues/9788#issuecomment-112149413)

**Comment by dchen1107** [comment] 2015-06-15 17:43
@bprashanth You mentioned above that "Sometimes there are OOMs, these don't affect the kubelet, but the node eventually dies" The two OOM killing examples are manage_accounts and manage_addresses, which all belongs to our /system cgroup, but we haven't oom protected them yet. But do you know why that particular node is changed to NotReady from Ready? You can have such information by doing kubectl describe node. Thanks!

**Comment by satnam6502** [comment] 2015-06-15 17:49
Note that PR #9758 will make Cloud Logging the default after which no addons run for logging (unless Elasticsearch is explicitly set as the logging choice).

**Comment by bprashanth** [comment] 2015-06-15 17:54
> (unless Elasticsearch is explicitly set as the logging choice).

aka non-gce clusters right (or can one still use gce from aws)? if that's true it will make this even harder to debug :)

**Comment by satnam6502** [comment] 2015-06-15 17:56
@mr-salty to what extend can people use Cloud Logging from AWS, Azure etc?

**Comment by bprashanth** [comment] 2015-06-15 18:00
> to what extend can people use Cloud Logging from AWS, Azure etc?

Hmm, I'm assuming even if they can, they won't. Each of those probabaly has a gcl equivalent that those people are more familiar with, and until someone writes plugins for them they'll probably stick with ES.

**Comment by vishh** [comment] 2015-06-15 18:16
We can have multiple replicas if required. The plan is to place resource
limits on heapster pod after we profile the pod as part of scalability
testing.

**Comment by mr-salty** [comment] 2015-06-15 18:33
@satnam6502 only GCP services are officially supported at this time, although users can use configuration file settings to specify project and instance metadata on other platforms on an unsupported basis.

**Comment by dchen1107** [comment] 2015-06-15 20:28
Ok, I don't think logging pods causing issues here by analyzing all NotReady nodes, I will explain it below:

Here are what I understood so far:

1) I observed the several nodes having 100% cpu usage all the time from pantheon, which indicates a kernel crash since I saw a similar issue with porch.com case before. I checked the serial log, it is kernel crash. But the node is not reboot. @brendandburns mentioned that there is a "reboot_on_panic" for each instance, we should check that one by default for all instances on GCE and GKE. 

2) @bprashanth I noticed that all minions you created are g1-small (1 vCPU, 1.7 GB memory), which is indeed too small for one replica of heapster managing 100 nodes (we can optimizing heapster's resource usage in the future, but not in 1.0 scope). Here are what we can do:
* Once we have more stats from #5880 to understand resource requirements from heapster based on the workload and nodes, we should place resource limits on heapster pods.
* @erickhan suggested that for GKE / GCE users, we should suggest them to us bigger nodes, instead of g1-small. I made changes for our jenkin-e2e tests to avoid unnecessary overcommit issues last week. We can change our config-default.sh to have a bigger node by default too. I will send pr for that unless someone scream now.
* We can determine the number of replicas based on cluster side based on the result from #5880 too.

3) I found most nodes are not useful because system oom due to heapster. But unfortunately heapster has oom_score_adj -900, which causes other daemons on the node being killed. I haven't figured why heapster misconfigured in @bprashanth cluster since my test cluster doens't have such issue. @vishh ?

**Comment by dchen1107** [comment] 2015-06-15 20:33
According to 3), I realized that because heaspter process is inheritant the oom_score_adj from its parent process docker with -900. Will send PR to fix it now.

**Comment by bprashanth** [comment] 2015-06-15 20:39
> Ok, I don't think logging pods causing issues here by analyzing all NotReady nodes

A heapster/es crash is what got us the first NotReady node though?

> I noticed that all minions you created are g1-small (1 vCPU, 1.7 GB memory), which is indeed too small for one replica of heapster managing 100 nodes (we can optimizing heapster's resource usage in the future, but not in 1.0 scope).

g1-small is essentially what we've been optimizing performance for, I think we recently bumped it up to n1-standard (but that isn't *that* much better). 

Since this is OOMing with 0 extra pods,  customers can just never have a 100 node cluster of g1-smalls because of the 1 or 2 nodes heapster is running on? 

@dchen1107  any idea what are the logs being sent to heapster? It can obviously fit on a g1-small, so why does it go nuts?

**Comment by vishh** [comment] 2015-06-15 20:51
Heapster requires memory to store metrics fromm all nodes in the cluster.
If the cluster size os large, then a g1-small is not sufficient to run
heapster.

Inheriting docker daemon's oom_score_adj is a bug. Dawn is fixing it.

We can turn off heapster on a scale cluster and optimize the rest of the
components for g1-small, if required.

**Comment by satnam6502** [comment] 2015-06-15 20:55
I  will conduct a test with a 100 node cluster set up with Elasticsearch
logging and pods running synthetic loggers on each node and report back.

**Comment by bprashanth** [comment] 2015-06-15 22:06
The oom score will help undead nodes, but the cpu and memory pressure from the addons will still affect syncPods latency making 99%ile type benchmarks hard to achieve (on a 100 node cluster 99%ile fails if one node is slow to start a pod: https://github.com/GoogleCloudPlatform/kubernetes/issues/3954). 

A solution involving more restrictive limit ranges/cgroups is probably out of scope for 1.0, so this is currently a pointless lament :)

**Comment by vishh** [comment] 2015-06-15 22:08
I am curious to know the kind of workloads a user would run on a g1-small
100 node cluster.
Why are we spending on optimizing for g1-small?

**Comment by bprashanth** [comment] 2015-06-15 22:12
Maybe they want to run 30 pause pods :)
We probably should've started off with a bigger node size, meh. But I'm assuming resource pressure will happen on an n1-standard-1 as well (it's just a little bigger right, so it might take a few hours more)?

**Comment by vishh** [comment] 2015-06-15 22:20
I'd expect heapster resource usage to be proportional to the size of the
cluster and not vary over time. We can wait for the scalability test
results before we arrive at any conclusions.

**Comment by saad-ali** [comment] 2015-06-15 23:04
See https://github.com/GoogleCloudPlatform/kubernetes/issues/5880#issuecomment-112233798 for initial scalability test results.

**Comment by lavalamp** [comment] 2015-06-16 01:11
@vishh we use small VMs to keep our test cluster size & cost down. I agree that people probably won't use it that way in the wild.

**Comment by bprashanth** [comment] 2015-06-16 01:16
OTOH, if I was speccing out a kubernetes cluster for production I would pick a 100 node g1-small cluster for the same reasons you just mentioned.

**Comment by lavalamp** [comment] 2015-06-16 01:34
> According to 3), I realized that because heaspter process is inheritant the oom_score_adj from its parent process docker with -900. Will send PR to fix it now.

@dchen1107 it sounds like this was the real P0 problem; now that #9824 is merged, can we close this issue?

> ... cpu and memory pressure from the addons will still affect syncPods latency making 99%ile type benchmarks hard to achieve...

@bprashanth Yeah. But we can split this into two issues: syncPods can get resource-starved; and our own addons are resource hogs. Can we find/file issues for both and close this?

**Comment by bprashanth** [comment] 2015-06-16 01:39
The addons being resource hogs sounds like this issue, so maybe we can just demote it in priority? I'll  fork off a syncPods issue if there isn't one already. We should also surface somewhere that there is a relationship between node and cluster size, just so people aren't surprised.

**Comment by dchen1107** [comment] 2015-06-16 01:51
Can we use this issue for misconfigured oom_score ones? That is a real p0 issue, and I had a fix for it which merged and @brendandburns is going to include it in our 0.19 patch release.

Can we move heapster's resource limits and scalability to  #5880 based on workload and cluster size? 

to me, SyncPod one sounds like #9833?

**Comment by dchen1107** [comment] 2015-06-16 01:54
@bprashanth Please filed a separate one for syncPods if you don't think it is dup of #9833. I am closing this one for now.

**Closed by dchen1107** 2015-06-16 01:54 UTC
Labels: priority/P0, team/cluster, team/master, team/node

**Comment by fgrzadkowski** [comment] 2015-06-16 12:14
@bprashanth I don't think we are optimizing for g1-small. For example scalability e2e jenkins tests are using n1-standard-1 that have twice as much memory (3.75G vs 1.7G).

**Comment by bprashanth** [comment] 2015-06-16 14:38
@fgrzadkowski we recently bumped it up (https://github.com/GoogleCloudPlatform/kubernetes/pull/9678, and that was a pr for the normal e2es, scalability just benefitted from it). For example if you check the build output from the jenkins scalability run of build 1228 you'll see we use g1-smalls.

@dchen1107 on a cluster I setup last night 2 nodes died, 1 recovered, 
(e2e-test-beeps-minion-9sar, e2e-test-beeps-minion-s8eh). The node that's still down was running elasticsearch and the one that recovered was running heapster. It looks like the one that recovered might've had some memory issues ~8hours ago, but no reported OOMs:

```
I0616 05:29:22.342313    3075 container.go:363] Failed to update stats for container "/24423cb95446e509cc5e53a13832c66bec3a7f83923656249589da964da9b1e9": du command failed on /var/lib/docker/aufs/diff/24423cb95446e509cc5e53a13832c66bec3a7f83923656249589da964da9b1e9 with output  - fork/exec /usr/bin/du: cannot allocate memory, continuing to push stats
I0616 05:29:22.358187    3075 container.go:363] Failed to update stats for container "/a447483789dbda0099a29eac72255380119843ce5c17690e5fe77aac0bef405b": du command failed on /var/lib/docker/aufs/diff/a447483789dbda0099a29eac72255380119843ce5c17690e5fe77aac0bef405b with output  - fork/exec /usr/bin/du: cannot allocate memory, continuing to push stats
I0616 05:29:22.944631    3075 container.go:363] Failed to update stats for container "/7668f4ce116142e207a4c2e0084e0091619091b79ab5ef7c2985783f215021dd": du command failed on /var/lib/docker/aufs/diff/7668f4ce116142e207a4c2e0084e0091619091b79ab5ef7c2985783f215021dd with output  - fork/exec /usr/bin/du: cannot allocate memory, continuing to push stats
```

I've haven't recovered the one that's down.

**Comment by dchen1107** [comment] 2015-06-16 17:50
@bprashanth Thanks for conducting the test again.

The only unrecovered node is caused by docker memory leakage. It is a known issue since docker 1.3.0, might even earlier version (https://github.com/docker/docker/issues/9139). Docker 1.7.0-rcX (the one I am currently validating) should have a fix for it. Once you restart docker, the problem should be gone, and the node should be recovered. I saw a similar problem before. On each node, there is a monit healthchecking docker daemon process periodically, in most cases, the docker in such bad state will be restarted by monit.
