### ISSUE TITLE
Authentication error running kubectl proxy

### ISSUE THREAD

**Issue by ddysher** [GoogleCloudPlatform/kubernetes#10115] opened 2015-06-19 20:17 UTC
I followed the explorer example but when I did:

`
curl localhost:8001/api/v1/proxy/namespaces/default/pods/explorer:8080/vars/
`

It returns <h3>Unauthorized</h3>

Maybe something changed in auth/z that the example stop working?  @lavalamp

**Comment by lavalamp** [comment] 2015-06-19 21:02
@mikedanese hm--maybe something broke at head recently?

**Comment by mikedanese** [comment] 2015-06-19 21:20
Tested out #10105 and it seems to fix it. @brendanburns @caesarxuchao

**Comment by mikedanese** [comment] 2015-06-19 22:19
This is fixed on HEAD

**Comment by lavalamp** [comment] 2015-06-20 01:13
Is it? I just sync'd to head and I still have this problem?

**Comment by lavalamp** [comment] 2015-06-20 01:16
OK, I see-- paths that start with /api/ work now, but paths that don't (e.g. /ui/) are still broken. You have to pass --api-prefix=/ to access these paths.

**Comment by lavalamp** [comment] 2015-06-20 01:27
I see. The issue is that the default accepted/rejected things don't allow anything but /api. @brendandburns did you exclude the UI on purpose?

**Comment by lavalamp** [comment] 2015-06-22 22:24
I will fix this breakage.

**Comment by lavalamp** [comment] 2015-06-23 01:59
I'll include my fix in #10070. I'm also adding tests so that I don't have to make this work a third time.

**Comment by ddysher** [comment] 2015-06-23 02:02
:+1:

**Closed** 2015-06-25 20:15 UTC
Labels: kind/support, priority/P1, team/master
