### ISSUE TITLE
Kubelet fails to return stats for a running pod

### ISSUE THREAD

**Issue by vishh** [GoogleCloudPlatform/kubernetes#5716] opened 2015-03-20 17:07 UTC
I0320 17:05:55.585336    4853 server.go:672] GET /api/v1beta1/podInfo?podID=kibana-logging-controller-oh43e&podNamespace=default: (204.26µs) 0 [[Go 1.1 package http] 10.240.203.174:47585]
I0320 17:05:57.768169    4853 server.go:672] GET /stats/default/fluentd-to-elasticsearch-kubernetes-minion-82pn/aac6a5d4-ce59-11e4-b270-42010af0cbae/fluentd-es: (1.873473ms) 404 [[Go 1.1 package http] 10.244.0.5:34698]
I0320 17:05:57.771568    4853 server.go:140] HTTP InternalServerError: Internal Error: unable to find Docker container "b26c28c393667c95ab1ac08fa79cb0556915fd7a5f213c5ced686bc261546966"
I0320 17:05:57.771638    4853 server.go:672] GET /stats/default/kibana-logging-controller-oh43e/96314dee-ce59-11e4-b270-42010af0cbae/kibana-logging: (1.573903ms) 500
goroutine 12563 [running]:
github.com/GoogleCloudPlatform/kubernetes/pkg/httplog.(*respLogger).WriteHeader(0xc208278c00, 0x1f4)
	/go/src/github.com/GoogleCloudPlatform/kubernetes/_output/dockerized/go/src/github.com/GoogleCloudPlatform/kubernetes/pkg/httplog/log.go:188 +0x9a
net/http.Error(0x7fb7c48037a8, 0xc208278c00, 0xc208884f00, 0x72, 0x1f4)
	/usr/src/go/src/net/http/server.go:1274 +0x9a
github.com/GoogleCloudPlatform/kubernetes/pkg/kubelet.(*Server).error(0xc20837a580, 0x7fb7c48037a8, 0xc208278c00, 0x7fb7c47ebc80, 0xc20884fd70)
	/go/src/github.com/GoogleCloudPlatform/kubernetes/_output/dockerized/go/src/github.com/GoogleCloudPlatform/kubernetes/pkg/kubelet/server.go:141 +0x213
github.com/GoogleCloudPlatform/kubernetes/pkg/kubelet.(*Server).serveStats(0xc20837a580, 0x7fb7c48037a8, 0xc208278c00, 0xc208741930)
	/go/src/github.com/GoogleCloudPlatform/kubernetes/_output/dockerized/go/src/github.com/GoogleCloudPlatform/kubernetes/pkg/kubelet/server.go:720 +0x6ff
github.com/GoogleCloudPlatform/kubernetes/pkg/kubelet.(*Server).handleStats(0xc20837a580, 0x7fb7c48037a8, 0xc208278c00, 0xc208741930)
	/go/src/github.com/GoogleCloudPlatform/kubernetes/_output/dockerized/go/src/github.com/GoogleCloudPlatform/kubernetes/pkg/kubelet/server.go:324 +0x46
github.com/GoogleCloudPlatform/kubernetes/pkg/kubelet.*Server.(github.com/GoogleCloudPlatform/kubernetes/pkg/kubelet.handleStats)·fm(0x7fb7c48037a8, 0xc208278c00, 0xc208741930)
	/go/src/github.com/GoogleCloudPlatform/kubernetes/_output/dockerized/go/src/github.com/GoogleCloudPlatform/kubernetes/pkg/kubelet/server.go:122 +0x45
net/http.HandlerFunc.ServeHTTP(0xc2083564f0, 0x7fb7c48037a8, 0xc208278c00, 0xc208741930)
	/usr/src/go/src/net/http/server.go:1265 +0x41
net/http.(*ServeMux).ServeHTTP(0xc20823df80, 0x7fb7c48037a8, 0xc208278c00, 0xc208741930)
	/usr/src/go/src/net/http/server.go:1541 +0x17d
github.com/GoogleCloudPlatform/kubernetes/pkg/kubelet.(*Server).ServeHTTP(0xc20837a560, 0x7fb7c4803770, 0xc2081aa000, 0xc208741930)
	/go/src/github.com/GoogleCloudPlatform/kubernetes/_o [[Go 1.1 package http] 10.244.0.5:34693]
I0320 17:05:57.816109    4853 server.go:672] GET /stats/: (1.221148ms) 0 [[Go 1.1 package http] 10.244.0.5:34693]
I0320 17:05:59.389972    4853 kubelet.go:1238] probe success: fluentd-es
I0320 17:05:59.390332    4853 kubelet.go:1238] probe success: kibana-logging

**Comment by dchen1107** [comment] 2015-03-20 20:21
1) You are running old release:
root@kubernetes-minion-82pn:/var/log# kubelet --version
Kubernetes v0.11.0-1506-g2e7356bca72d1f-dirty
2) I couldn't reproduce the issue from HEAD. 
3) The code used to report such internal error is heavily refactored. 

I am going to close this one. Please reopen it after you upgrade your cluster to the latest one. Thanks!

**Comment by vishh** [comment] 2015-03-20 20:23
Thanks for looking into the issue Dawn. I will try again with a new cluster.

**Closed** 2015-03-20 20:24 UTC
Labels: priority/P1, team/node
