### ISSUE TITLE
Not possible to use selector operators with json selector property

### ISSUE THREAD

**Issue by erictune** [GoogleCloudPlatform/kubernetes#3627] opened 2015-01-20 17:03 UTC
It doesn't appear that there is a way to use an operator other than the implied = with json, which uses
`"selector": { "name:", "foo", "value": "bar"}`.

**Comment by erictune** [comment] 2015-01-20 17:03
forked from #3623

**Comment by bgrant0607** [comment] 2015-01-21 00:33
Dupe of #341 (yes, 3 digit issue).

**Closed by bgrant0607** 2015-01-21 00:33 UTC
Labels: api/cluster
