### ISSUE TITLE
kubelet tries to start pods before cbr0 is set

### ISSUE THREAD

**Issue by lavalamp** [GoogleCloudPlatform/kubernetes#8581] opened 2015-05-20 19:15 UTC
This means the pods may not get an IP address, and if they do start, they'll get killed when cbr0 is changed.

We should not let SyncPods and cbr0 race.

**Comment by roberthbailey** [comment] 2015-05-20 19:39
@cjcullen and I were just discussing this and if allocateCIDRs is set to true (the default on GCE) then a node should register itself as not ready, wait for a cidr allocation, restart docker, and then mark itself as ready.

**Comment by roberthbailey** [comment] 2015-05-20 19:40
Do you know what breaks in the current state? Do any of the pods that we launch on startup (e.g. dns) persist state that wouldn't be completely erased when restarted with a different pod ip?

**Comment by dchen1107** [comment] 2015-05-20 19:56
PR  #7984 was merged a while back, which introduce kubelet configures cbr0 instead of configure-vm.sh. Are we suspect this is the root cause for e2e test failure? The timeline doesn't match here. cc/ @quinton-hoole

**Comment by dchen1107** [comment] 2015-05-20 20:04
Also based on my understanding, there are some racing between pods being scheduled to the node, and kubelet reconfigure cbr0. But once cbr0 is configured, docker would be restarted, thus syncPod will restart all containers. 

cc/ @fgrzadkowski

**Comment by dchen1107** [comment] 2015-05-20 20:32
#6949 is the one enabling master to allocate CIDR to node.

**Comment by roberthbailey** [comment] 2015-05-20 20:34
The master allocating CIDRs was done by @cjcullen in #7984.

**Comment by dchen1107** [comment] 2015-05-20 21:20
Ok, the root cause is out of the order on merging prs. I believe #7984 should fix the issue #8534, and #6949 should have a merge dependency on it here.

**Comment by dchen1107** [comment] 2015-05-20 21:26
The puzzle is resolved, and kubelet is working as the expected. I am closing the issue here.

**Closed by dchen1107** 2015-05-20 21:26 UTC
Labels: team/node

**Comment by lavalamp** [comment] 2015-05-24 21:53
The puzzle is resolved, but kubelet still reboots docker potentially after having started pods, which is a bad user experience. See #8758. Reopening for discussion.
