### ISSUE TITLE
service API access from within a pod

### ISSUE THREAD

**Issue by opaugam** [GoogleCloudPlatform/kubernetes#7698] opened 2015-05-04 12:12 UTC
It appears like I can't use the service API @ 10.0.0.2 (unauthorized even with proper auth + TLS on 0.15 and so far hanging on 0.16). At this point I reverted to using the master directly from within my pods, which is quite sub-optimal. Is there a plan to support access to the service API from within the cluster, typically when implementing a PaaS where pods have the ability to create other pods ?

**Comment by roberthbailey** [comment] 2015-05-05 05:31
On my cluster (launched from ~head today) running on GCE, this works fine both from a node in the cluster and from inside the `fluentd-elasticsearch:1.5` container running on the node:

```
$ sudo docker exec -i -t 981869 bash
root@fluentd-elasticsearch-kubernetes-minion-685r:/# curl --insecure -H "Authorization: Bearer REDACTED" https://10.0.0.2/validate
[
  {
    "component": "controller-manager",
    "health": "success",
    "msg": "ok",
    "err": "nil"
  },
  {
    "component": "scheduler",
    "health": "success",
    "msg": "ok",
    "err": "nil"
  },
  {
    "component": "etcd-0",
    "health": "success",
    "msg": "{\"action\":\"get\",\"node\":{\"dir\":true,\"nodes\":[{\"key\":\"/registry\",\"dir\":true,\"modifiedIndex\":3,\"createdIndex\":3}]}}\n",
    "err": "nil"
  },
  {
    "component": "node-0",
    "health": "success",
    "msg": "ok",
    "err": "nil"
  },
  {
    "component": "node-1",
    "health": "success",
    "msg": "ok",
    "err": "nil"
  },
  {
    "component": "node-2",
    "health": "success",
    "msg": "ok",
    "err": "nil"
  },
  {
    "component": "node-3",
    "health": "success",
    "msg": "ok",
    "err": "nil"
  }
]
```

**Comment by opaugam** [comment] 2015-05-05 11:12
Mmh interesting - the same does not work from a cluster running on AWS & setup via the installer (wget -q -O - https://get.k8s.io | bash).

Is there any provider-specific constraint accessing 10.0.0.2 ? Curling the RO service from within a pod was working great on 0.15 (including AWS) btw.

**Comment by roberthbailey** [comment] 2015-05-05 17:05
I don't have access to an AWS cluster. Maybe @justinsb could test it out and see if he can reproduce the failure?

**Comment by justinsb** [comment] 2015-05-08 15:47
This was recently broken, but I should have fixed it in #7678.  Do you know if the version you're running includes that patch?

**Comment by justinsb** [comment] 2015-05-08 15:48
Note that you have to use a bearer token now for auth (which you can get from a secrets volume whose name I can track down for you if you're not already doing this!)

**Comment by opaugam** [comment] 2015-05-08 16:00
mh ok thanks for heads up ! I'll retry over the weekend - is the secrets volume goodness described somewhere in the docs ? I can hunt for it..

**Comment by justinsb** [comment] 2015-05-09 01:42
I found some docs here: https://github.com/GoogleCloudPlatform/kubernetes/issues/7979

It does sound like maybe this isn't the _official_ way to get a bearer token!

**Comment by opaugam** [comment] 2015-05-09 13:28
looks purr-fect to me - giving it a try.. thanks !

**Comment by opaugam** [comment] 2015-05-11 23:04
Mh i think i'm going to wait for #7101 to land instead. Sounds more like the way it should be.

**Comment by lavalamp** [comment] 2015-05-11 23:13
>  service API @ 10.0.0.2

You should be using the env vars KUBERNETES_RO_SERVICE_HOST and KUBERNETES_RO_SERVICE_PORT, not the ip address directly-- IP address is not guaranteed to be that in every cluster.

But we're deprecating that, anyway-- you already found #7101; also see #5921.

(closing because the other issues mentioned cover this)

**Closed by lavalamp** 2015-05-11 23:13 UTC
Labels: kind/support, priority/P2, team/cluster
