### ISSUE TITLE
HTTP liveness probe weirdness

### ISSUE THREAD

**Issue by kostko** [GoogleCloudPlatform/kubernetes#3041] opened 2014-12-18 21:53 UTC
I am experiencing some weird issues when enabling HTTP liveness probes for some containers. I configure the following for all HTTP-serving containers (this is part of a template used by a replication controller with a single replica):
```
livenessProbe:
  enabled: true
  type: 'http'
  httpGet:
    path: /
    port: 3000
  initialDelaySeconds: 15
```

When this is configured, the following issues start to occur:
* One pod is already running without problems. When I add another replication controller which creates a new pod (also with the liveness probe set), the first pod (the one that was already running) is restarted. This happens even when the two pods are in different namespaces.
* But when a pod's HTTP server fails completely (connection to the port is refused), the liveness probe will not trigger and the pod will not be restarted.

This behavior occurs consistently when I start with no replication controllers and then add them one by one. When I disable the liveness probes on the affected pods/templates, they are no longer restarted in this manner.

**Comment by lavalamp** [comment] 2015-01-02 18:22
Great detective work-- I think it's clear that we shouldn't be including *pointers* in our hash, so we need to revisit that and explicitly hash only the things that we care about.

**Comment by dchen1107** [comment] 2015-01-02 18:56
Adding second replication controller changes the pointer of LivenessProbe in container config is another mystery. We need to make sure not randomly update other fields too.

**Comment by saad-ali** [comment] 2015-01-03 07:24
Dug in to this some more: confirmed that the value of the original container's LivenessProbe doesn't actually change when the second replication controller is created--only the pointer to the LivenessProbe object changes.

It turns out that the instance of the [```api.Container```](https://github.com/GoogleCloudPlatform/kubernetes/blob/master/pkg/api/types.go#l299) object being used to compute the expected hash is not guaranteed to be the same instance for the lifespan of the actual docker container. In fact, every time there is an etcd update (e.g. a new pod is created) a new boundpods object is created and although the values of the existing pod/container container objects don't change, because new instances are created the pointers do change (by design).

So the fix for this is to ensure that the expected hash is computed only on container values not pointers.

One way to ensure this would be to make sure the container object specifies no pointer fields. However, LivenessProbe and Lifecycle, since they are optional, must be able to be set to ```nil```. Thus, pointer fields can't simply be converted to value fields.

Another approach would be to only hash some subset of the values (maybe the name and image) of the container. However, containers  should be destroyed/recreated (meaning the hash must change) if the actual values of any of the container fields changes (e.g. the cpu, memory, volume mounts, liveness probe path, etc.), not just the container name/image. Thus, pointer fields can't simply be disregarded for the hash computation.

Instead the fix must modify the expected hash to be computed on the complete deep values of the entire container object (including the actual LivenessProbe values, instead of the pointer). The easiest way to do this is to marshal the container object to json and compute the hash from the resulting byte array.

**Closed** 2015-01-06 00:05 UTC
Labels: kind/support, priority/P1
