### ISSUE TITLE
GlusterFS Volume Plugin deletes the contents of the mounted volume upon Pod deletion

### ISSUE THREAD

**Issue by wattsteve** [GoogleCloudPlatform/kubernetes#7317] opened 2015-04-24 23:11 UTC
1. Create a set of endpoints to your GlusterFS cluster. Example http://pastebin.com/aysdLxqh
2. Submit a pod that uses the GlusterFS Volume Plugin in ReadWrite Mode (readonly=false) to mount a particular GlusterFS volume. Example http://pastebin.com/4c10Xryh
3. Verify the pod is running
4. List the contents of that GlusterFS Volume and see that your files exist.
5. Stop the pod - "kubectl delete pod glusterfs"
6. List the contents of your GlusterFS Volume and see that your files no longer exist.

Environment:
GlusterFS - verified with GlusterFS running on either Fedora 21 or RHEL 6.5. 
Kubernetes - running on Fedora 21

Note: This issue does not occur if the GlusterFS Volume Plugin is in ReadOnly Mode (readonly=true)

**Comment by thockin** [comment] 2015-04-24 23:52
heh, this is why I wanted to refactor the mount/unmount/cleanup code - get it right once :)

**Comment by vishh** [comment] 2015-04-25 00:05
cc @rootfs

**Comment by childsb** [comment] 2015-04-27 19:34
I went back to commit 841a8a498be059aa1ed71185443476d6b4808f91 (the original merge for glusterfs volume) and couldn't replicate the bug.

after updating to HEAD i could replicate.  so something changed between first merge and HEAD causing issue.

**Comment by jsafrane** [comment] 2015-04-29 08:10
It's caused by commit 275002173e2d7c53b86965016fb0f180f92f8ec9:

```
func (kl *Kubelet) killUnwantedPods(...)
{
    ...
			// Remove the pod directory.
			err = os.RemoveAll(kl.getPodDir(pod.ID))
			if err != nil {
				glog.Errorf("Failed removing pod directory for %q", pod.Name)
				return
			}
}
```

This `os.RemoveAll()` is called *before* unmounting of volumes, which are mounted somewhere into `kl.getPodDir(pod.ID)`.

@yujuhong, why RemoveAll()? It was not there before your commit.

**Comment by jsafrane** [comment] 2015-04-29 09:05
Fixed in PR #7503

**Comment by yujuhong** [comment] 2015-04-29 21:59
> @yujuhong, why RemoveAll()? It was not there before your commit.

Sorry for injecting the bug. I was thinking of moving volume & pod dir cleanup into the function, but it didn't pan out, and the code was left unintentionally. Thanks for fixing it!

 The logic still seems strange in some cases. `cleanupOrphanedVolumes` looks at the containers we failed to kill, and skip cleaning up volumes associated with them. But `cleanupOrphanedPodDirs` doesn't look at the those containers and would just go ahead and remove the directories for all the pods that we *supposedly* killed. I will file and issue later.

**Comment by thockin** [comment] 2015-05-08 06:56
Is this fixed now?  If so, please close.

**Closed** 2015-05-08 14:02 UTC
Labels: priority/P1, team/cluster
