### ISSUE TITLE
Update examples so that we create Services before creating corresponding ReplicationControllers/Pods.

### ISSUE THREAD

**Issue by gmarek** [GoogleCloudPlatform/kubernetes#11154] opened 2015-07-13 15:24 UTC
Currently examples follow wrong pattern of creating RCs first. It makes services spreading no-op.

**Comment by erictune** [comment] 2015-07-14 18:43
@davidopp to confirm if this is a scheduler issue and prioritize

**Comment by davidopp** [comment] 2015-07-14 19:04
This is  a dupe of #11144. Closing.

**Closed by davidopp** 2015-07-14 19:04 UTC
Labels: area/scheduling, kind/example
