### ISSUE TITLE
kubelet log full of errors

### ISSUE THREAD

**Issue by thockin** [GoogleCloudPlatform/kubernetes#8223] opened 2015-05-14 00:27 UTC
Error on reading termination-log /var/lib/kubelet/pods/fa438d63-f986-11e4-9c82-42010af0ae3d/containers/skydns/933ddf81dbaf586e425240432429aa57bec939383e19bfb25d35d478597203f7: open /var/lib/kubelet/pods/fa438d63-f986-11e4-9c82-42010af0ae3d/containers/skydns/933ddf81dbaf586e425240432429aa57bec939383e19bfb25d35d478597203f7: no such file or directory

**Comment by dchen1107** [comment] 2015-05-14 00:34
I think there is a regression lately breaking termination-log.

**Comment by yujuhong** [comment] 2015-05-18 21:37
#8436 might be related to this issue.

**Comment by vmarmol** [comment] 2015-05-27 03:19
Was this fixed by #8436?

**Comment by dchen1107** [comment] 2015-06-08 16:41
No, I still observed such error logs once a while, but so far those errors are red herring, without any breakage. Haven't get down to look into the detail yet.

**Comment by yujuhong** [comment] 2015-07-01 21:15
If a pod gets deleted from the apiserver, kubelet (more specifically, the SyncPods function) would stop the container, and remove the orphaned volumes and pod directories. In the meantime, the per-pod workers (goroutines) may not have terminated yet. Therefore, the workers could be inspecting the containers to generate the status, causing the errors. Note that this does not happen if containers terminated by themselves while the pod is not yet deleted.

The error messages are harmless, since the pods have been deleted and no one would examine the termination logs anyway. However, the fact that kubelet.log is full of such errors is misleading and confusing to users. I think this would be solved by graceful termination...

**Closed** 2015-07-02 07:32 UTC
Labels: priority/P1, team/node
