### ISSUE TITLE
Failed to list *api.Pod: field label not supported: spec.nodeName

### ISSUE THREAD

**Issue by lavalamp** [GoogleCloudPlatform/kubernetes#10263] opened 2015-06-23 22:40 UTC
My kubelet logs are full of this message, and it isn't picking up new pods. I don't think I have relevant differences from head, so filing this issue. I will investigate.

**Comment by bprashanth** [comment] 2015-06-23 22:43
Sounds api version related, might also be the root cause of https://github.com/GoogleCloudPlatform/kubernetes/issues/10257 since the kubelet would find nodes after the relist but not from the watch

**Comment by lavalamp** [comment] 2015-06-23 22:45
This makes the list not work at all-- it's deterministic.

**Comment by lavalamp** [comment] 2015-06-23 22:48
From my apiserver log, it looks like kubelet makes a correct request. so server side problem:

```
GET /api/v1/pods?fieldSelector=spec.nodeName%3Dkubernetes-minion-c51h: (475.526µs) 400
goroutine 2362717 [running]:
github.com/GoogleCloudPlatform/kubernetes/pkg/httplog.(*respLogger).WriteHeader(0xc2085cca80, 0x190)
	/go/src/github.com/GoogleCloudPlatform/kubernetes/_output/dockerized/go/src/github.com/GoogleCloudPlatform/kubernetes/pkg/httplog/log.go:188 +0x9a
github.com/GoogleCloudPlatform/kubernetes/pkg/apiserver.writeJSON(0x190, 0x7fd2888b5d88, 0xc2080da040, 0x7fd2888b5fa0, 0xc2092d9200, 0x7fd2886f7300, 0xc2085cca80, 0x40d501)
	/go/src/github.com/GoogleCloudPlatform/kubernetes/_output/dockerized/go/src/github.com/GoogleCloudPlatform/kubernetes/pkg/apiserver/apiserver.go:312 +0x2b7
github.com/GoogleCloudPlatform/kubernetes/pkg/apiserver.errorJSON(0x7fd2888b76d0, 0xc2092d9180, 0x7fd2888b5d88, 0xc2080da040, 0x7fd2886f7300, 0xc2085cca80, 0x7fd2888c1938)
	/go/src/github.com/GoogleCloudPlatform/kubernetes/_output/dockerized/go/src/github.com/GoogleCloudPlatform/kubernetes/pkg/apiserver/apiserver.go:319 +0xab
github.com/GoogleCloudPlatform/kubernetes/pkg/apiserver.func·023(0xc20a04c600, 0xc20a249c20)
	/go/src/github.com/GoogleCloudPlatform/kubernetes/_output/dockerized/go/src/github.com/GoogleCloudPlatform/kubernetes/pkg/apiserver/resthandler.go:224 +0x56d
github.com/emicklei/go-restful.func·005(0xc20a04c600, 0xc20a249c20)
	/go/src/github.com/GoogleCloudPlatform/kubernetes/Godeps/_workspace/src/github.com/emicklei/go-restful/container.go:215 +0x41
github.com/emicklei/go-restful.(*FilterChain).ProcessFilter(0xc20a04c7e0, 0xc20a04c600, 0xc20a249c20)
	/go/src/github.com/GoogleCloudPlatform/kubernetes/Godeps/_workspace/src/github.com/emicklei/go-restful/filter.go:21 +0xa2
github.com/GoogleCloudPlatform/kubernetes/pkg/apiserver.func·003(0xc20a04c600, 0xc20a249c20, 0xc20a04c7e0)
	/go/src/github.com/GoogleCloudPlatform/kubernetes/_output/dockerized/go/src/github.com/GoogleCloudPlatform/kubernetes/pkg/apiserver/apiserver.go:96 +0x88
github.com/emicklei/go-restful.(*FilterChain).ProcessFilter(0xc20a04c7e0, 0xc20a04c600, 0xc20a249c20)
	/go/src/github.com/GoogleCloudPlatform/kubernetes/Godeps/_workspace/src/ [[kubelet/v0.19.3 (linux/amd64) kubernetes/56528a5] 10.240.237.201:49019]
```

**Comment by lavalamp** [comment] 2015-06-23 22:50
I think the problem is that cluster/kube-push.sh didn't update my apiserver and I have skew from before we fixed that.

**Comment by dchen1107** [comment] 2015-06-24 16:59
Closed it since it is configuration issue in @lavalamp's dev environment.

**Closed by dchen1107** 2015-06-24 16:59 UTC
Labels: priority/P0, team/master, team/node

**Comment by lavalamp** [comment] 2015-06-24 17:50
Yes, sorry, I meant to close this last night. kube-down.sh/kube-up.sh gave me a working cluster again.
