### ISSUE TITLE
kube-apiserver is not restarting when monitored by kubelet

### ISSUE THREAD

**Issue by derekwaynecarr** [GoogleCloudPlatform/kubernetes#7001] opened 2015-04-17 20:02 UTC
I am seeing this many times over the course of a few days when working with a development and am unsure the cause.  I bring up a cluster and the apiserver is running fine, and then for some reason, the kube-apiserver container itself fails.

```ssh
[vagrant@kubernetes-master ~]$ sudo docker ps -a
CONTAINER ID        IMAGE                                                                      COMMAND                CREATED             STATUS                      PORTS               NAMES
a27a41fc9a58        gcr.io/google_containers/etcd:2.0.9                                        "/usr/local/bin/etcd   About an hour ago   Up About an hour                                k8s_etcd-container.1e717455_etcd-server-kubernetes-master_default_0fe7ea4e3416d3daa0786bc643de7560_f2c288e3      
154389bc35aa        e0434809a4e2                                                               "/kube-scheduler --m   About an hour ago   Up About an hour                                k8s_kube-scheduler.24f80b95_kube-scheduler-kubernetes-master_default_f79c2695229fdda04f415c8007e85c74_377c6796   
fe8ceb062579        gcr.io/google_containers/kube-apiserver:245789b39bb5a7d83cd88684b8272608   "/kube-apiserver --a   About an hour ago   Exited (2) 52 minutes ago                       k8s_kube-apiserver.a7d51976_kube-apiserver-kubernetes-master_default_95b19ea324d9ab1d745ebb0f49c513ac_6ed8438c   
e36afa2a1d08        gcr.io/google_containers/pause:0.8.0                                       "/pause"               About an hour ago   Up About an hour                                k8s_POD.1a1fe303_kube-scheduler-kubernetes-master_default_f79c2695229fdda04f415c8007e85c74_e9a042c6              
89e54f95c9eb        gcr.io/google_containers/pause:0.8.0                                       "/pause"               About an hour ago   Up About an hour                                k8s_POD.1a1fe303_kube-apiserver-kubernetes-master_default_95b19ea324d9ab1d745ebb0f49c513ac_c5ab1bda              
dff64ce5917b        gcr.io/google_containers/pause:0.8.0                                       "/pause"               About an hour ago   Up About an hour                                k8s_POD.1a1fe303_etcd-server-kubernetes-master_default_0fe7ea4e3416d3daa0786bc643de7560_080321d6               
```

The kubelet never restarts the kube-apiserver, and the cluster is left in a failed state.

Looking at the kubelet logs, I see messages like the following:

```shell
Apr 17 19:59:46 kubernetes-master kubelet[4501]: W0417 19:59:46.352783    4501 status_manager.go:60] Failed to updated pod status: error updating status for pod "kube-apiserver-kubernetes-master": Get https
Apr 17 19:59:46 kubernetes-master kubelet[4501]: E0417 19:59:46.352447    4501 kubelet.go:1963] Cannot get host IP: cannot get node: node kubernetes-master not found
Apr 17 19:59:46 kubernetes-master kubelet[4501]: E0417 19:59:46.331763    4501 mirror_client.go:68] Failed deleting a mirror pod "kube-apiserver-kubernetes-master_default": dial tcp 10.245.1.2:6443: connect
Apr 17 19:59:46 kubernetes-master kubelet[4501]: E0417 19:59:46.331370    4501 kubelet.go:1301] Deleting mirror pod "kube-apiserver-kubernetes-master_default" because it is outdated
Apr 17 19:59:46 kubernetes-master kubelet[4501]: I0417 19:59:46.331285    4501 event.go:200] Event(api.ObjectReference{Kind:"Pod", Namespace:"default", Name:"kube-apiserver-kubernetes-master", UID:"95b19ea3
Apr 17 19:59:45 kubernetes-master kubelet[4501]: E0417 19:59:45.958972    4501 reflector.go:123] Failed to list *api.Pod: Get https://10.245.1.2:6443/api/v1beta3/pods?fieldSelector=spec.host%3Dkubernetes-ma
Apr 17 19:59:45 kubernetes-master kubelet[4501]: E0417 19:59:45.958712    4501 reflector.go:123] Failed to list *api.Node: Get https://10.245.1.2:6443/api/v1beta3/nodes?fieldSelector=metadata.name%3Dkuberne
Apr 17 19:59:45 kubernetes-master kubelet[4501]: E0417 19:59:45.958712    4501 reflector.go:123] Failed to list *api.Service: Get https://10.245.1.2:6443/api/v1beta3/services: dial tcp 10.245.1.2:6443: conn
Apr 17 19:59:45 kubernetes-master kubelet[4501]: E0417 19:59:45.565861    4501 kubelet.go:1963] Cannot get host IP: cannot get node: node kubernetes-master not found
Apr 17 19:59:45 kubernetes-master kubelet[4501]: I0417 19:59:45.557791    4501 docker.go:347] Pulling image gcr.io/google_containers/kube-apiserver:38e98bcf79cee7f9e0ea3cb267452635 without credentials
A
```

Its not clear to me why it is attempting to re-pull the kube-apiserver in this manner on my development enviornment, versus just using the local loaded and pushed image as part of normal dev-flow:

```ssh
[vagrant@kubernetes-master ~]$ sudo docker images
REPOSITORY                                         TAG                                IMAGE ID            CREATED             VIRTUAL SIZE
gcr.io/google_containers/kube-scheduler            8ffbe8f9368354444a8ff59e81748df4   edcbd0522003        56 minutes ago      17.61 MB
gcr.io/google_containers/kube-controller-manager   6dc0b767a16c95dd893350df89c70639   67db299564b2        56 minutes ago      22.41 MB
<none>                                             <none>                             6bf6a5742bcc        56 minutes ago      27.76 MB
gcr.io/google_containers/kube-apiserver            245789b39bb5a7d83cd88684b8272608   45be92a35805        About an hour ago   27.76 MB
gcr.io/google_containers/kube-controller-manager   5a363b29b9af5ff2a235dfe13f481ce5   c83077bffac3        About an hour ago   22.41 MB
<none>                                             <none>                             e0434809a4e2        About an hour ago   17.61 MB
gcr.io/google_containers/etcd                      2.0.9                              b6b9a86dc06a        9 days ago          12.82 MB
gcr.io/google_containers/pause                     0.8.0                              2c40b0526b63        2 weeks ago         241.7 kB
```

When this happens, I am unable to get the system back in a state to actually re-run my code, as subsequent kube-push triggers do not restart my image.

@dchen1107 @ArtfulCoder - does this make sense to either of you?  It can be a pain in my development workflow, and I am hoping we can come up with a solution.

**Comment by derekwaynecarr** [comment] 2015-04-17 20:15
I need to check what the ImagePullPolicy is that we are applying on the pods we provision, but I think in a development environment, it should be ```Never```

**Comment by derekwaynecarr** [comment] 2015-04-17 20:25
ImagePullPolicy is set to ```IfNotPresent```, it's now not clear to me why it is trying to pull at all in the log.  I noticed my above log output chopped off the message from the event, but it shows an error when trying to pull that image.  Will augment when it happens again.

**Comment by bgrant0607** [comment] 2015-04-17 20:26
cc @erictune

**Comment by dchen1107** [comment] 2015-04-21 23:36
@bprashanth @ArtfulCoder is going to take a look at this first. Is that ok?

**Comment by ArtfulCoder** [comment] 2015-04-22 03:08
In the logs above: 
Loaded  image is: gcr.io/google_containers/kube-apiserver           245789b39bb5a7d83cd88684b8272608

kubelet is looking for gcr.io/google_containers/kube-apiserver:38e98bcf79cee7f9e0ea3cb267452635 
which is not in the docker images list. As a result kubelet cant find the image and fails to restart the kube-apiserver container.

@derekwaynecarr Next time this happens can you check the tag that the /etc/kubernetes/manifests/kube-apiserver.manifest file specifies ? I am quite sure that this must have somehow happened when you did a push..

**Comment by ArtfulCoder** [comment] 2015-04-22 14:10
on GCE, I brought up a cluster. ApiServer came up with tag baddae80acfe8578ea00a9e16aef81b9 



=========== Docker images on master after kube-up ===============
REPOSITORY                                         TAG                                IMAGE ID            CREATED             VIRTUAL SIZE
gcr.io/google_containers/kube-scheduler            9e3e6b30bf550ee3155b057bfb604222   69dbfc104b8f        19 hours ago        18.35 MB
gcr.io/google_containers/kube-controller-manager   0136e7478afddbdefdf8a4ad9b3755b4   2237a4d2fcc7        19 hours ago        23.05 MB
gcr.io/google_containers/kube-apiserver            baddae80acfe8578ea00a9e16aef81b9   3dbfc237673b        19 hours ago        27.65 MB
gcr.io/google_containers/etcd                      2.0.9                              b6b9a86dc06a        2 weeks ago         12.82 MB
gcr.io/google-containers/nginx                     v1                                 70c70495624a        2 weeks ago         165.6 MB
gcr.io/google_containers/fluentd-elasticsearch     1.3                                a69bf7f9cef1        3 weeks ago         583.9 MB
gcr.io/google_containers/pause                     0.8.0                              2c40b0526b63        3 weeks ago         241.7 kB
google/cadvisor                                    0.8.0                              4cde3eeb4b8d        3 months ago        17.79 MB
kubernetes/pause                                   go                                 6c4579af347b        9 months ago        239.8 kB
kubernetes/pause                                   latest                             6c4579af347b        9 months ago        239.8 kB


=========== apiserver container after kub-up================
kube-apiserver-kubernetes-master                               kube-apiserver            gcr.io/google_containers/kube-apiserver:baddae80acfe8578ea00a9e16aef81b9            kubernetes-master/                      <none>                                                              Running   19 hours


============= kube - push =========

I mad changes to apiserver, built and did a push. the new images got loaded on master, as shown  below.

=========== Docker images on master afte kube-push ===============
root@kubernetes-master:/home/abshah# docker images
REPOSITORY                                         TAG                                IMAGE ID            CREATED             VIRTUAL SIZE
gcr.io/google_containers/kube-controller-manager   f578d14f9c15959d8dc6ab072fbcb7dc   bc1b846643a8        5 minutes ago       23.05 MB
gcr.io/google_containers/kube-apiserver            7c934a7962af870eea76522e5e30942c   39b4446aefe7        5 minutes ago       27.65 MB
gcr.io/google_containers/kube-scheduler            84e49c9e6759458267f5db2fe6eea553   f18bc317de7d        5 minutes ago       18.35 MB
gcr.io/google_containers/kube-scheduler            9e3e6b30bf550ee3155b057bfb604222   69dbfc104b8f        19 hours ago        18.35 MB
gcr.io/google_containers/kube-controller-manager   0136e7478afddbdefdf8a4ad9b3755b4   2237a4d2fcc7        19 hours ago        23.05 MB
gcr.io/google_containers/kube-apiserver            baddae80acfe8578ea00a9e16aef81b9   3dbfc237673b        19 hours ago        27.65 MB
gcr.io/google_containers/etcd                      2.0.9                              b6b9a86dc06a        2 weeks ago         12.82 MB
gcr.io/google-containers/nginx                     v1                                 70c70495624a        2 weeks ago         165.6 MB
gcr.io/google_containers/fluentd-elasticsearch     1.3                                a69bf7f9cef1        3 weeks ago         583.9 MB
gcr.io/google_containers/pause                     0.8.0                              2c40b0526b63        3 weeks ago         241.7 kB
google/cadvisor                                    0.8.0                              4cde3eeb4b8d        3 months ago        17.79 MB
kubernetes/pause                                   go                                 6c4579af347b        9 months ago        239.8 kB
kubernetes/pause                                   latest                             6c4579af347b        9 months ago        239.8 kB


======== docker containers on master after kub-push ===========

root@kubernetes-master:/home/abshah# docker ps
CONTAINER ID        IMAGE                                                                               COMMAND                CREATED             STATUS              PORTS               NAMES
8da3f4888e20        gcr.io/google_containers/kube-scheduler:84e49c9e6759458267f5db2fe6eea553            "/kube-scheduler --m   59 seconds ago      Up 59 seconds                           k8s_kube-scheduler.b680b8e_kube-scheduler-kubernetes-master_default_6df4126c1a3983896776b02450fc5ca0_adc5e177
d7b714ba5519        gcr.io/google_containers/kube-controller-manager:f578d14f9c15959d8dc6ab072fbcb7dc   "/kube-controller-ma   59 seconds ago      Up 59 seconds                           k8s_kube-controller-manager.b2683916_kube-controller-manager-kubernetes-master_default_55d7757895d9fce3c023ceb4c461a9af_792f1f3c
5b9f010fb009        gcr.io/google_containers/kube-apiserver:7c934a7962af870eea76522e5e30942c            "/kube-apiserver --a   59 seconds ago      Up 59 seconds                           k8s_kube-apiserver.d7ac0144_kube-apiserver-kubernetes-master_default_7c9f2b2560d5a83ea9b6886b12978cfa_812cfe4a
98e5ef90abbc        gcr.io/google-containers/nginx:v1                                                   "nginx -g 'daemon of   19 hours ago        Up 19 hours                             k8s_nginx.ec9384d3_nginx-kubernetes-master_default_016de97f2eade4dba519455ec02781cf_fbfcefca
65a17d62a149        gcr.io/google_containers/etcd:2.0.9                                                 "/usr/local/bin/etcd   19 hours ago        Up 19 hours                             k8s_etcd-container.1e717455_etcd-server-kubernetes-master_default_0fe7ea4e3416d3daa0786bc643de7560_1eabb913
12e122d2c8d8        gcr.io/google_containers/fluentd-elasticsearch:1.3                                  "\"/bin/sh -c '/usr/   19 hours ago        Up 19 hours                             k8s_fluentd-es.b5bc4193_fluentd-to-elasticsearch-kubernetes-master_default_1923d4df27917ece7f77853378135c36_a6b503ee
968270390a7a        gcr.io/google_containers/pause:0.8.0                                                "/pause"               19 hours ago        Up 19 hours                             k8s_POD.1a1fe303_kube-controller-manager-kubernetes-master_default_55d7757895d9fce3c023ceb4c461a9af_06b6feac
4ddb043f384e        gcr.io/google_containers/pause:0.8.0                                                "/pause"               19 hours ago        Up 19 hours                             k8s_POD.1a1fe303_etcd-server-kubernetes-master_default_0fe7ea4e3416d3daa0786bc643de7560_a34dfd63
063aca52acc5        gcr.io/google_containers/pause:0.8.0                                                "/pause"               19 hours ago        Up 19 hours                             k8s_POD.1a1fe303_nginx-kubernetes-master_default_016de97f2eade4dba519455ec02781cf_568cbd8b
62f0d72e0a6d        gcr.io/google_containers/pause:0.8.0                                                "/pause"               19 hours ago        Up 19 hours                             k8s_POD.1a1fe303_kube-apiserver-kubernetes-master_default_7c9f2b2560d5a83ea9b6886b12978cfa_455053de
0511892369f4        gcr.io/google_containers/pause:0.8.0                                                "/pause"               19 hours ago        Up 19 hours                             k8s_POD.1a1fe303_kube-scheduler-kubernetes-master_default_6df4126c1a3983896776b02450fc5ca0_2b2eea29
8e553dd05461        gcr.io/google_containers/pause:0.8.0                                                "/pause"               19 hours ago        Up 19 hours                             k8s_POD.1a1fe303_fluentd-to-elasticsearch-kubernetes-master_default_1923d4df27917ece7f77853378135c36_f953d4a7



The apiserver got upated correctly,after the push..

**Comment by davidopp** [comment] 2015-05-11 07:36
Should we close this issue?

**Comment by ArtfulCoder** [comment] 2015-05-11 18:54
@derekwaynecarr did you see this issue again ?
If not, maybe we should close it and reopen if required ?
I could not reproduce this.

**Comment by davidopp** [comment] 2015-05-11 20:29
Please reopen if still an issue.

**Closed by davidopp** 2015-05-11 20:29 UTC
Labels: priority/P1, team/node
