### ISSUE TITLE
docker btrfs issue caused by kubelet

### ISSUE THREAD

**Issue by Fandekasp** [GoogleCloudPlatform/kubernetes#3617] opened 2015-01-20 02:52 UTC
I've been struggling on a problem over the past week, that a few pods always fail to run.

When I tried to manually run one of those, I got:
```
core@ip-10-237-218-56 ~ $ docker run -ti kiyoto/fluentd:0.12.1-2.1.5 ls
Unable to find image 'kiyoto/fluentd:0.12.1-2.1.5' locally
Pulling repository kiyoto/fluentd
7d5bd4ed392e: Error pulling image (0.12.1-2.1.5) from kiyoto/fluentd, Driver btrfs failed to get image parent aaabd2b41e22543a7b230c2c892a482e80f99039209b193bdd2b67a526996b30: stat /var/lib/docker/btrfs/subvolumes/aaabd2b41e22543a7b230c2c892a482e80f99039209b193bdd2b67a526996b30: no such file or directory dd2b67a526996b30: no such file or directory
3c20e07c38ce: Error downloading dependent layers
FATA[0058] Error pulling image (0.12.1-2.1.5) from kiyoto/fluentd, Driver btrfs failed to get image parent aaabd2b41e22543a7b230c2c892a482e80f99039209b193bdd2b67a526996b30: stat /var/lib/docker/btrfs/subvolumes/aaabd2b41e22543a7b230c2c892a482e80f99039209b193bdd2b67a526996b30: no such file or directory
```
I could succesfully run the image on another os with different docker version and different backend filesystem, so I did many tests, to conclude that the problem is neither with btrfs, nor with docker, nor with coreos.
I could create another aws autoscaling group, reusing the same versions of those tools, but without kubernetes, and I could sucessfully run that image there as well.
I then removed all components from my cloudformation template, and readded them progressively, to notice that pulling this image only fails when the kubelet is running.

I then tried to run the kubelet with different options, but the bare minimum `/opt/bin/kubelet --etcd_servers=http://127.0.0.1:4001` is enough for docker to fail on that image. Looking at the traceback:
```
core@ip-10-237-218-56 ~ $ /opt/bin/kubelet --etcd_servers=http://127.0.0.1:4001
I0120 02:24:41.867394   28317 node.go:52] Connecting to docker on unix:///var/run/docker.sock
I0120 02:24:41.867526   28317 util.go:128] No api servers specified.
I0120 02:24:41.878683   28317 standalone.go:205] Watching for etcd configs at [http://127.0.0.1:4001]
I0120 02:24:41.885479   28317 plugins.go:56] Registering credential provider: .dockercfg
I0120 02:24:41.885661   28317 logs.go:39] etcd DEBUG: get /registry/nodes/ip-10-237-218-56.ec2.internal/boundpods [http://127.0.0.1:4001]
I0120 02:24:41.885743   28317 logs.go:39] etcd DEBUG: Connecting to etcd: attempt1forkeys/registry/nodes/ip-10-237-218-56.ec2.internal/boundpods?consistent=true&recursive=false&sorted=false
I0120 02:24:41.885815   28317 logs.go:39] etcd DEBUG: send.request.to http://127.0.0.1:4001/v2/keys/registry/nodes/ip-10-237-218-56.ec2.internal/boundpods?consistent=true&recursive=false&sorted=false | method GET
I0120 02:24:41.885868   28317 event.go:92] Event(api.ObjectReference{Kind:"Minion", Namespace:"default", Name:"ip-10-237-218-56.ec2.internal", UID:"ip-10-237-218-56.ec2.internal", APIVersion:"", ResourceVersion:"", FieldPath:""}): status: '', reason: 'starting' Starting kubelet.
I0120 02:24:41.928419   28317 logs.go:39] etcd DEBUG: recv.response.fromhttp://127.0.0.1:4001/v2/keys/registry/nodes/ip-10-237-218-56.ec2.internal/boundpods?consistent=true&recursive=false&sorted=false
I0120 02:24:41.928492   28317 logs.go:39] etcd DEBUG: recv.success.http://127.0.0.1:4001/v2/keys/registry/nodes/ip-10-237-218-56.ec2.internal/boundpods?consistent=true&recursive=false&sorted=false
I0120 02:24:41.928564   28317 logs.go:39] etcd DEBUG: watch /registry/nodes/ip-10-237-218-56.ec2.internal/boundpods [http://127.0.0.1:4001]
I0120 02:24:41.928611   28317 logs.go:39] etcd DEBUG: get /registry/nodes/ip-10-237-218-56.ec2.internal/boundpods [http://127.0.0.1:4001]
I0120 02:24:41.928660   28317 logs.go:39] etcd DEBUG: Connecting to etcd: attempt1forkeys/registry/nodes/ip-10-237-218-56.ec2.internal/boundpods?consistent=true&wait=true&waitIndex=3381
I0120 02:24:41.928695   28317 logs.go:39] etcd DEBUG: send.request.to http://127.0.0.1:4001/v2/keys/registry/nodes/ip-10-237-218-56.ec2.internal/boundpods?consistent=true&wait=true&waitIndex=3381 | method GET
I0120 02:24:41.929632   28317 logs.go:39] etcd DEBUG: recv.response.fromhttp://127.0.0.1:4001/v2/keys/registry/nodes/ip-10-237-218-56.ec2.internal/boundpods?consistent=true&wait=true&waitIndex=3381

core@ip-10-237-218-56 ~ $ curl http://127.0.0.1:4001/v2/keys/registry/nodes
{"errorCode":100,"message":"Key not found","cause":"/registry/nodes","index":3422}

core@ip-10-237-218-56 ~ $ curl http://127.0.0.1:4001/v2/keys/registry/
{"action":"get","node":{"key":"/registry","dir":true,"nodes":[{"key":"/registry/services","dir":true,"modifiedIndex":14,"createdIndex":14},{"key":"/registry/minions","dir":true,"modifiedIndex":37,"createdIndex":37}],"modifiedIndex":14,"createdIndex":14}}

core@ip-10-237-218-56 ~ $
```

Does kubelet try to query `registry/nodes` when only `registry/services` and `registry/minions` are available?
I still don't understand what does kubelet has to do with the btrfs error raised by docker, but the evidence is that everytime I stop kubelet, docker has no problem with the image:
```
core@ip-10-237-218-56 ~ $ sudo systemctl stop kube-kubelet
core@ip-10-237-218-56 ~ $ docker run -ti kiyoto/fluentd:0.12.1-2.1.5 ls
Unable to find image 'kiyoto/fluentd:0.12.1-2.1.5' locally
Pulling repository kiyoto/fluentd
7d5bd4ed392e: Download complete
511136ea3c5a: Download complete
36fd425d7d8a: Download complete
aaabd2b41e22: Download complete
3c20e07c38ce: Download complete
b6ef456c239c: Download complete
b045b0cd49ad: Download complete
7855c14973cc: Download complete
2a24c9b7a5f1: Download complete
c82cadc1856f: Download complete
f0f017241bb0: Download complete
146d795aeab9: Download complete
0f154b063a84: Download complete
c04060062646: Download complete
e1ebcc148e67: Download complete
197ad3ee39c6: Download complete
d8b6573c9c35: Download complete
643b35d35def: Download complete
f2e6d6ac3fb7: Download complete
Status: Downloaded newer image for kiyoto/fluentd:0.12.1-2.1.5
bin   dev  home  lib64  mnt  proc  run   srv  tmp  var
boot  etc  lib   media  opt  root  sbin  sys  usr
```

This issue is a blocker. Since I cannot get the cluster-side logging to work yet (#2918), I'm trying to have a temporary fluentd pod running for application-side logging at first.

Any suggestion?

**Comment by thockin** [comment] 2015-01-20 04:18
Could this and #3611 be related?  If so, think this should be p0.  Who
feels best equipped to dig on this one?

**Comment by Fandekasp** [comment] 2015-01-20 04:20
Yes, I believe it's the same issue :)

**Comment by erictune** [comment] 2015-01-20 16:53
Maybe not related, but CoreOS moved from btrfs to overlay, see kubernetes  issues #3625 #3626 -- sorry I don't have a CoreOS issue.

**Comment by erictune** [comment] 2015-01-20 16:53
@dchen1107  is most likely person to be able to know more about this issue.

**Comment by erictune** [comment] 2015-01-20 17:01
If it happens again, it could help if someone could grab `/proc/$pid/stacks` for all kubelet and dockerd threads (`ps -eLf`).  That would allow us to determine if anyone is currently blocked in the kernel in a devicemapper-related system call.

**Comment by dchen1107** [comment] 2015-01-20 17:29
Which version of kubernetes / kubelet are you running?

**Comment by dchen1107** [comment] 2015-01-20 18:29
Ok I could re-produce the issue on aufs from HEAD:

when kubelet is running:
```
# docker run -ti kiyoto/fluentd:0.12.1-2.1.5 ls
Unable to find image 'kiyoto/fluentd:0.12.1-2.1.5' locally
Pulling repository kiyoto/fluentd
7d5bd4ed392e: Download complete 
511136ea3c5a: Download complete 
36fd425d7d8a: Download complete 
aaabd2b41e22: Download complete 
3c20e07c38ce: Download complete 
b6ef456c239c: Download complete 
b045b0cd49ad: Download complete 
7855c14973cc: Download complete 
2a24c9b7a5f1: Download complete 
c82cadc1856f: Download complete 
f0f017241bb0: Download complete 
146d795aeab9: Download complete 
0f154b063a84: Download complete 
c04060062646: Download complete 
e1ebcc148e67: Download complete 
197ad3ee39c6: Download complete 
d8b6573c9c35: Download complete 
643b35d35def: Download complete 
f2e6d6ac3fb7: Download complete 
Status: Downloaded newer image for kiyoto/fluentd:0.12.1-2.1.5
FATA[0066] Error response from daemon: No such image: kiyoto/fluentd:0.12.1-2.1.5 (tag: 0.12.1-2.1.5) 
```
After I stopped kubelet process, every runs fine.  I am going to mark this as P0, and assign it to myself.

**Comment by dchen1107** [comment] 2015-01-20 19:33
Ok, I think I know the root cause of the issue here. Actually it is indeed caused by Image GC collection (#3097) we introduced recently. 

Current support of gc of image depending on docker's "dangling=true", which gives us a wrong set unused images on a node. Instead it only returns a list of image layers without tag. When a image is pulling, all layers are untagged initially, then tagged later. In this case, some intermediate layers might be removed by kubelet GC, especially with a big image. 

We fixed the similar issues by adding lock during docker image pull triggered by kubernetes. But there is protection for docker image pull outside kubelet. 

To prove my hyperthesis, I add some debugging line to Kubelet, then run 
```
docker run -ti kiyoto/fluentd:0.12.1-2.1.5 ls
Unable to find image 'kiyoto/fluentd:0.12.1-2.1.5' locally
Pulling repository kiyoto/fluentd
7d5bd4ed392e: Download complete 
511136ea3c5a: Download complete 
36fd425d7d8a: Download complete 
aaabd2b41e22: Download complete  <=========== Image layer being removed by GC
...
Status: Downloaded newer image for kiyoto/fluentd:0.12.1-2.1.5
FATA[0102] Error response from daemon: No such image: kiyoto/fluentd:0.12.1-2.1.5 (tag: 0.12.1-2.1.5) 
```

From kubelet.log below, one can see the same image layer is being removed. 
```
I0120 19:02:43.190647   14910 kubelet.go:352] ????GC Before removing image: "aaabd2b41e22543a7b230c2c892a482e80f99039209b193bdd2b67a526996b30"
&{aaabd2b41e22543a7b230c2c892a482e80f99039209b193bdd2b67a526996b30 36fd425d7d8a26bb092cf3ca8c52eb8e47170363f40a3f4e37c9cad401f0e9fe  2014-11-06 20:43:04.968583876 +0000 UTC 88208bb931c00137f3b7e7287354a7e561370e2e3d50f0534e3bc9bd9ebe706b {aa73dc53d3c7   0 0 0  false false false [] map[] false false false [PATH=/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin] [/bin/sh -c #(nop) CMD [/bin/bash]] [] 36fd425d7d8a26bb092cf3ca8c52eb8e47170363f40a3f4e37c9cad401f0e9fe map[]   [] false} 1.3.0  0xc208053e00 amd64 0}
I0120 19:02:43.537718   14910 kubelet.go:356] ?????? GC Remove image: "aaabd2b41e22543a7b230c2c892a482e80f99039209b193bdd2b67a526996b30"
```

I did reopen #157 to re-do Image GC, but didn't treat it as the highest issue in my queue. Now with these issues being reported, I think our current image GC does nothing except introducing issues, and we should remove it or completely disable it: 

1) Issues reported like this. And it is very hard, or unnecessary complicated to fix this issue. 
2) I think when we decided if a image should be GC, it should deal the entire image stacks, not one or two image layers. Even we might fix all race issues today, but we might break the logic later. Removing one or two intermediate layers is very hard to debug. 
3) Since both docker and kubernetes pro all images having tag now. Any images with proper tag wouldn't be removed at all even they are not referred by any container for long time.

cc/ @brendandburns

**Comment by dchen1107** [comment] 2015-01-20 19:35
#3632 is trying to disable garbage collection temporarily.

**Closed** 2015-01-20 22:07 UTC
Labels: kind/bug, priority/P0

**Comment by Fandekasp** [comment] 2015-01-20 23:34
thank you @dchen1107  !

**Comment by haf** [comment] 2015-03-12 19:11
I got this error on CoreOS, current stable (at this date) on DigitalOcean, for a single container that I had never built before -- rebuilding it after changing a single file making up the image, made the problem go away.

```
Removing intermediate container dff273d5ba2c
Step 7 : RUN curl -O -sL https://nodejs.org/dist/v0.12.0/node-v0.12.0-linux-x64.tar.gz &&     tar zxf node-v0.12.0-linux-x64.tar.gz &&     cp -rp node-v0.12.0-linux-x64 /usr/local/ &&     ln -s /usr/local/node-v0.12.0-linux-x64/ /usr/local/node
 ---> Running in 33696ca2e825
time="2015-03-12T18:51:52Z" level="info" msg="Driver btrfs failed to get image parent fd49b0b7b78fa7c3e2b9f2eb653dbb0c203f46e7ff16e8b403128069dd42554d: stat /var/lib/docker/btrfs/subvolumes/fd49b0b7b78fa7c3e2b9f2eb653dbb0c203f46e7ff16e8b403128069dd42554d: no such file or directory"
```
