### ISSUE TITLE
kubelet unable to get details of a scheduled pod (404) / pod stuck in "unknown" status

### ISSUE THREAD

**Issue by soatman** [GoogleCloudPlatform/kubernetes#4068] opened 2015-02-03 20:00 UTC
I0203 19:44:40.163598    4252 server.go:315] GET /api/v1beta1/podInfo?podID=aceb844a-abdc-11e4-9a0a-000d3a302484&podNamespace=default: (39us) 404

Using a replicationController to create the pod... the pod is created successfully, but the container is never provisioned.  Kubelet log indicates that the it tries to get information about the pod in question but is unable to.

Version 0.9.3
Azure

**Comment by a-robinson** [comment] 2015-02-03 20:17
Can you paste the logs from the Kubelet here?

**Comment by dchen1107** [comment] 2015-02-03 21:29
can we have the following outputs:

1) kubectl get minions
2) docker ps -a | grep aceb844a-abdc-11e4-9a0a-000d3a302484

**Comment by soatman** [comment] 2015-02-03 22:06
On the minion in question docker ps -a returns nothing...

The Kubelet logs just repeat this: 
I0203 19:44:40.163598 4252 server.go:315] GET /api/v1beta1/podInfo?podID=aceb844a-abdc-11e4-9a0a-000d3a302484&podNamespace=default: (39us) 404

I'll grab the complete log and attach in a moment.  Note: I did have to manually add 3 minions to my cluster that for whatever reason were not registered properly by kube-up.

**Comment by soatman** [comment] 2015-02-03 22:51
./kubectl.sh get -o json minions
Running: ./../cluster/azure/../../platforms/linux/amd64/kubectl get -o json minions
{
    "kind": "List",
    "creationTimestamp": null,
    "resourceVersion": 72,
    "apiVersion": "v1beta1",
    "items": [
        {
            "kind": "Minion",
            "id": "kubernetes-minion-3.slodock.d2.internal.cloudapp.net",
            "uid": "a24a53a9-abc5-11e4-9a0a-000d3a302484",
            "creationTimestamp": "2015-02-03T16:56:44Z",
            "selfLink": "/api/v1beta1/minions/kubernetes-minion-3.slodock.d2.internal.cloudapp.net?namespace=default",
            "resourceVersion": 9,
            "apiVersion": "v1beta1",
            "namespace": "default",
            "hostIP": "10.0.0.7",
            "resources": {
                "capacity": {
                    "cpu": "1",
                    "memory": 3221225472
                }
            },
            "status": {
                "conditions": [
                    {
                        "kind": "Ready",
                        "status": "Full",
                        "lastTransitionTime": null
                    }
                ]
            }
        },
        {
            "kind": "Minion",
            "id": "kubernetes-minion-4.slodock.d2.internal.cloudapp.net",
            "uid": "b015000b-abc5-11e4-9a0a-000d3a302484",
            "creationTimestamp": "2015-02-03T16:57:07Z",
            "selfLink": "/api/v1beta1/minions/kubernetes-minion-4.slodock.d2.internal.cloudapp.net?namespace=default",
            "resourceVersion": 10,
            "apiVersion": "v1beta1",
            "namespace": "default",
            "hostIP": "10.0.0.8",
            "resources": {
                "capacity": {
                    "cpu": "1",
                    "memory": 3221225472
                }
            },
            "status": {
                "conditions": [
                    {
                        "kind": "Ready",
                        "status": "Full",
                        "lastTransitionTime": null
                    }
                ]
            }
        },
        {
            "kind": "Minion",
            "id": "kubernetes-minion-1.slodock.d2.internal.cloudapp.net",
            "uid": "7db452a8-ab73-11e4-9a0a-000d3a302484",
            "creationTimestamp": "2015-02-03T07:08:44Z",
            "selfLink": "/api/v1beta1/minions/kubernetes-minion-1.slodock.d2.internal.cloudapp.net",
            "resourceVersion": 7,
            "apiVersion": "v1beta1",
            "namespace": "default",
            "hostIP": "10.0.0.5",
            "resources": {
                "capacity": {
                    "cpu": "1",
                    "memory": 3221225472
                }
            },
            "status": {
                "conditions": [
                    {
                        "kind": "Ready",
                        "status": "Full",
                        "lastTransitionTime": null
                    }
                ]
            }
        },
        {
            "kind": "Minion",
            "id": "kubernetes-minion-2.slodock.d2.internal.cloudapp.net",
            "uid": "87027f32-abc5-11e4-9a0a-000d3a302484",
            "creationTimestamp": "2015-02-03T16:55:58Z",
            "selfLink": "/api/v1beta1/minions/kubernetes-minion-2.slodock.d2.internal.cloudapp.net?namespace=default",
            "resourceVersion": 8,
            "apiVersion": "v1beta1",
            "namespace": "default",
            "hostIP": "10.0.0.6",
            "resources": {
                "capacity": {
                    "cpu": "1",
                    "memory": 3221225472
                }
            },
            "status": {
                "conditions": [
                    {
                        "kind": "Ready",
                        "status": "Full",
                        "lastTransitionTime": null
                    }
                ]
            }
        }
    ]
}

Here's a minion.

**Comment by soatman** [comment] 2015-02-03 22:51
./kubectl.sh get -o json minions
Running: ./../cluster/azure/../../platforms/linux/amd64/kubectl get -o json minions
{
    "kind": "List",
    "creationTimestamp": null,
    "resourceVersion": 72,
    "apiVersion": "v1beta1",
    "items": [
        {
            "kind": "Minion",
            "id": "kubernetes-minion-3.slodock.d2.internal.cloudapp.net",
            "uid": "a24a53a9-abc5-11e4-9a0a-000d3a302484",
            "creationTimestamp": "2015-02-03T16:56:44Z",
            "selfLink": "/api/v1beta1/minions/kubernetes-minion-3.slodock.d2.internal.cloudapp.net?namespace=default",
            "resourceVersion": 9,
            "apiVersion": "v1beta1",
            "namespace": "default",
            "hostIP": "10.0.0.7",
            "resources": {
                "capacity": {
                    "cpu": "1",
                    "memory": 3221225472
                }
            },
            "status": {
                "conditions": [
                    {
                        "kind": "Ready",
                        "status": "Full",
                        "lastTransitionTime": null
                    }
                ]
            }
        },
        {
            "kind": "Minion",
            "id": "kubernetes-minion-4.slodock.d2.internal.cloudapp.net",
            "uid": "b015000b-abc5-11e4-9a0a-000d3a302484",
            "creationTimestamp": "2015-02-03T16:57:07Z",
            "selfLink": "/api/v1beta1/minions/kubernetes-minion-4.slodock.d2.internal.cloudapp.net?namespace=default",
            "resourceVersion": 10,
            "apiVersion": "v1beta1",
            "namespace": "default",
            "hostIP": "10.0.0.8",
            "resources": {
                "capacity": {
                    "cpu": "1",
                    "memory": 3221225472
                }
            },
            "status": {
                "conditions": [
                    {
                        "kind": "Ready",
                        "status": "Full",
                        "lastTransitionTime": null
                    }
                ]
            }
        },
        {
            "kind": "Minion",
            "id": "kubernetes-minion-1.slodock.d2.internal.cloudapp.net",
            "uid": "7db452a8-ab73-11e4-9a0a-000d3a302484",
            "creationTimestamp": "2015-02-03T07:08:44Z",
            "selfLink": "/api/v1beta1/minions/kubernetes-minion-1.slodock.d2.internal.cloudapp.net",
            "resourceVersion": 7,
            "apiVersion": "v1beta1",
            "namespace": "default",
            "hostIP": "10.0.0.5",
            "resources": {
                "capacity": {
                    "cpu": "1",
                    "memory": 3221225472
                }
            },
            "status": {
                "conditions": [
                    {
                        "kind": "Ready",
                        "status": "Full",
                        "lastTransitionTime": null
                    }
                ]
            }
        },
        {
            "kind": "Minion",
            "id": "kubernetes-minion-2.slodock.d2.internal.cloudapp.net",
            "uid": "87027f32-abc5-11e4-9a0a-000d3a302484",
            "creationTimestamp": "2015-02-03T16:55:58Z",
            "selfLink": "/api/v1beta1/minions/kubernetes-minion-2.slodock.d2.internal.cloudapp.net?namespace=default",
            "resourceVersion": 8,
            "apiVersion": "v1beta1",
            "namespace": "default",
            "hostIP": "10.0.0.6",
            "resources": {
                "capacity": {
                    "cpu": "1",
                    "memory": 3221225472
                }
            },
            "status": {
                "conditions": [
                    {
                        "kind": "Ready",
                        "status": "Full",
                        "lastTransitionTime": null
                    }
                ]
            }
        }
    ]
}

**Comment by dchen1107** [comment] 2015-02-04 20:59
Thanks for reporting the issue. 

I didn't see kubelet logs here. But from above output, minions are in ready state. Looks like Kubelet never see such BoundPod allocate to it, but apiserver thought it is and query it.

Could you please run: 

1) cat docker.log | grep "aceb844a"
2) kubectl describe pods aceb844a-abdc-11e4-9a0a-000d3a302484

**Comment by soatman** [comment] 2015-02-07 21:38
Output for #1:
Nothing

Output for #2:
./kubectl.sh describe pods aceb844a-abdc-11e4-9a0a-000d3a302484
Running: ./../cluster/azure/../../platforms/linux/amd64/kubectl describe pods aceb844a-abdc-11e4-9a0a-000d3a302484
Name:				aceb844a-abdc-11e4-9a0a-000d3a302484
Image(s):			soatman/dmc-web:0.1.8,soatman/dmc-nginx:0.1.2
Host:				kubernetes-minion-1.slodock.d2.internal.cloudapp.net/
Labels:				environment=prod,name=dmc-web,track=current
Status:				Unknown
Replication Controllers:	dmc-web-controller (1/1 replicas created)
No events.


I'm going to try 0.10.0 and see if the issue is corrected.  Unfortunately that means blowing away this cluster.  I'll open a new issue if it repros on the latest release.

**Comment by dchen1107** [comment] 2015-02-10 01:08
@soatman, From what your latest updates, it proves my initial hyperthesis since both kubelet and docker never see such boundPods, but master thought it should be scheduled to such node.

We do have some pod status flip between Unknown and Running (4188) with 0.10, but that one only happens when the node with heavy load, and also the status flipping, not stucking. Also kubelet reports code 500, not 404. 

Please let us know if you still have the same issue with 0.10. Thanks!

**Comment by dchen1107** [comment] 2015-02-18 03:13
With my recent PR, not included in 0.10 release, all Unknown cases caused by docker's resource temporarily unavailable issue should be fixed. I am going to close this issue. @soatman, please open a new issue when you observed the same issue on 0.11. Thanks!

**Closed by dchen1107** 2015-02-18 03:13 UTC
Labels: kind/support, priority/support, team/node
