### ISSUE TITLE
Service is not exported after updating Pod's container image

### ISSUE THREAD

**Issue by kazegusuri** [GoogleCloudPlatform/kubernetes#4239] opened 2015-02-07 09:29 UTC
I'm trying to update Pod to upgrade a container image to the newer one, but it seems Service environment variables are not exported into the new container. I use kubernetes `v0.10.0`.

```
$ kubectl create -f redis.yml
redis-master

$ kubectl get po
POD                 IP                  CONTAINER(S)        IMAGE(S)            HOST                        LABELS              STATUS
redis-master        10.244.95.12        master              dockerfile/redis    172.17.8.102/172.17.8.102   name=redis-master   Running

$ ssh node-01 "docker inspect ca0b5f5364d4" | jq '.[].Config.Env'
[
  "KUBERNETES_SERVICE_HOST=10.244.127.250",
  "KUBERNETES_SERVICE_PORT=443",
  "KUBERNETES_PORT=tcp://10.244.127.250:443",
  "KUBERNETES_PORT_443_TCP=tcp://10.244.127.250:443",
  "KUBERNETES_PORT_443_TCP_PROTO=tcp",
  "KUBERNETES_PORT_443_TCP_PORT=443",
  "KUBERNETES_PORT_443_TCP_ADDR=10.244.127.250",
  "KUBERNETES_RO_SERVICE_HOST=10.244.221.205",
  "KUBERNETES_RO_SERVICE_PORT=80",
  "KUBERNETES_RO_PORT=tcp://10.244.221.205:80",
  "KUBERNETES_RO_PORT_80_TCP=tcp://10.244.221.205:80",
  "KUBERNETES_RO_PORT_80_TCP_PROTO=tcp",
  "KUBERNETES_RO_PORT_80_TCP_PORT=80",
  "KUBERNETES_RO_PORT_80_TCP_ADDR=10.244.221.205",
  "PATH=/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin",
  "HOME=/root"
]
```

Updating Pod.

```
$ kubectl update -f redis.yml 
redis-master

$ kubectl get po
POD                 IP                  CONTAINER(S)        IMAGE(S)            HOST                        LABELS              STATUS
redis-master        10.244.95.13        master              dockerfile/nginx    172.17.8.102/172.17.8.102   name=redis-master   Running

$ ssh node-01 "docker inspect a23a21e6cf44" | jq '.[].Config.Env'
[
  "PATH=/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin",
  "HOME=/root"
]

```

**Comment by mbforbes** [comment] 2015-02-08 22:15
Forgive me as I'm new to debugging these things: could you please post the `redis.yml` file that you used (before and after, if it changed) so I can repro?

**Comment by kazegusuri** [comment] 2015-02-10 13:19
Before:
```
id: redis-master
kind: Pod
apiVersion: v1beta1
desiredState:
  manifest:
   version: v1beta1
   id: redis-master
   containers: 
     - 
       name: master
       image: dockerfile/redis
       cpu: 100
       ports: 
         - 
           containerPort: 6379
           hostPort: 6379
labels:
 name: redis-master
```

After:

```
id: redis-master
kind: Pod
apiVersion: v1beta1
desiredState:
  manifest:
   version: v1beta1
   id: redis-master
   containers: 
     - 
       name: master
       image: dockerfile/nginx # this line was changed
       cpu: 100
       ports: 
         - 
           containerPort: 6379
           hostPort: 6379
labels:
 name: redis-master
```

**Comment by a-robinson** [comment] 2015-02-11 23:21
I'm completely unable to reproduce this on version 0.10.0. Do you know which version of kubernetes you're running? You can find out by running`kubectl version`

**Comment by a-robinson** [comment] 2015-02-11 23:26
And this is less likely, but while you're at it can you double check that you're inspecting the correct container?

**Comment by kazegusuri** [comment] 2015-02-12 00:12
Hmm, I tried this again on other environment with a build of a current master branch, then I could reproduce it.
I tested with CoreOS on Vagrant and Ubuntu on bare-metal.

**Comment by kazegusuri** [comment] 2015-02-12 02:41
Investigated a little, I found environment variables of the BoundPod  in etcd were cleared after updating a pod.
Service envs are set by `boundPodFactory.MakeBoundPod` via `assignPod` at first creation, but those are not set on updating pod [here](https://github.com/GoogleCloudPlatform/kubernetes/blob/f9a4471ecae87f0f8928ad4e1243397ade871094/pkg/registry/etcd/etcd.go#L265-L271).
Maybe related to #4176

**Comment by a-robinson** [comment] 2015-02-12 07:29
@erictune, have any thoughts on what's going on here?

**Comment by kazegusuri** [comment] 2015-02-21 10:06
I found this was same issue to #4614.  I also use `--etcd_servers` option in kubelet, and this issue is resolved by using `--api_servers` option instead of it.

**Comment by zmerlynn** [comment] 2015-02-21 14:53
Closing as dupe of #4614.

**Closed by zmerlynn** 2015-02-21 14:53 UTC
Labels: kind/bug, priority/P1, team/node
