### ISSUE TITLE
Revist design of Annotations currently stored in docker container name

### ISSUE THREAD

**Issue by saad-ali** [GoogleCloudPlatform/kubernetes#3453] opened 2015-01-14 06:21 UTC
We currently only supports one annotation (container source), and it is stored as part of the docker container name ([pkg/kubelet/types.go#L73](https://github.com/GoogleCloudPlatform/kubernetes/blob/master/pkg/kubelet/types.go#L73)):
```GO
// GetPodFullName returns a name that uniquely identifies a pod across all config sources.
func GetPodFullName(pod *api.BoundPod) string {
	return fmt.Sprintf("%s.%s.%s", pod.Name, pod.Namespace, pod.Annotations[ConfigSourceAnnotationKey])
}

// ParsePodFullName unpacks a pod full name and returns the pod name, namespace, and annotations.
// If the pod full name is invalid, empty strings are returend.
func ParsePodFullName(podFullName string) (podName, podNamespace string, podAnnotations map[string]string) {
	parts := strings.Split(podFullName, ".")
	expectedNumFields := 3
	actualNumFields := len(parts)
	if actualNumFields != expectedNumFields {
		glog.Warningf("found a podFullName (%q) with too few fields: expected %d, actual %d.", podFullName, expectedNumFields, actualNumFields)
		return
	}
	podName = parts[0]
	podNamespace = parts[1]
	podAnnotations = make(map[string]string)
	podAnnotations[ConfigSourceAnnotationKey] = parts[2]
	return
}
```
Example Kubernetes Docker container name:
```
/k8s_mynginx1.18b0b73d_ca4e7148-9ab9-11e4-924c-f0921cde18c1.default.etcd_ca4e7148-9ab9-11e4-924c-f0921cde18c1_7b81f5b7
  ^     ^       ^           ^                                                 ^                                   ^
  |     |       |           |                                                 |                                   |
 prefix |    hash       full pod name                                       uuid                          rand.Uint32()
      container name
```
The delimiter is "```_```", so the full pod name is:
```
ca4e7148-9ab9-11e4-924c-f0921cde18c1.default.etcd
  ^                                   ^        ^
  |                                   |        |
pod name                     pod name space    |
                                           pod source
```
The delimiter is "```.```", and so the source is:
 ```
etcd
```

Questions to consider:
* Will we ever have more then one annotation?
* If so, should annotations be stored in the docker container name, or elsewhere?
* If the annotations should be stored in the container name, what would the key value pairs/delimiters look like (keep in mind that "." is already used as a delimiter for the pod name fields and "_" is used as a delimiter for the container name fields)?
* If the annotations should be stored in the container name, what validation, if any should be done on key/value pairs to avoid parsing errors?

**Comment by thockin** [comment] 2015-01-15 06:53
I see a few problems.

First, keeping the source in the name is sort of gross.  But then everything here is gross.

Second, pod name and namespace are actually validated as DNS subdomains, which means the fullname could be "foo.bar.bat.baz", where the split between namespace and name could be any one of those dots.  Now we append ".etcd" - it's still unparseable.

We should not arbitrarily add annotations here.  The names should be guarded and curated carefully.

I would propose that we retool the name to a more parseable form, something like

```
<prefix>_<container-name>_<container-hash>_<pod-name>_<pod-namespace>_<source>_<pod-uid>_<random>
```

We should define the net container to have a docker name of "NET" (because caps are not allowed through kubernetes API, so no conflicts) or maybe ".net" or else add a field indicating "user" vs "infra".

We should figure out if we really need the random number at the end, and if so, document it.

We should pass these fields around in a struct.

Lastly, we should keep up with docker metadata proposals and make sure we can offload a bunch of this into metadata :)

**Comment by davidopp** [comment] 2015-01-15 07:14
Random terminology complaint: it's confusing that we have annotations that we store in ObjectMeta and then also whatever this kind of annotation is.

**Comment by bgrant0607** [comment] 2015-02-27 17:48
Previous issue was #299.

We can store anything we want in Env on pause containers.

We still have the issue about how to find other containers.

**Comment by thockin** [comment] 2015-02-27 17:50
any month now we will finally get Docker's own labelling system checked
in... any month now...

**Comment by dchen1107** [comment] 2015-02-27 18:10
@thockin But it is still not in docker 1.5 release. 

@bgrant0607 we can put whatever we want to Env, but that introduces a huge overhead. Currently kubelet can simply call docker list and filter out non-k8s containers, or non-pod containers, or ... Then call docker inspect on the individual ones to get detail status. If we put everything to Env, we have to inspect every ones to figure out if it is a k8s container even. Please note that docker inspect is quite expense, which was main contributor of #4188 (API status for pods is flaky).

**Comment by dchen1107** [comment] 2015-02-27 18:10
cc/ @yujuhong This is the one we talked about earlier.

**Comment by bgrant0607** [comment] 2015-02-27 18:31
We should at least use uid rather than name.

**Comment by bgrant0607** [comment] 2015-02-27 18:33
Also, since we're going to post pods back, we need to eliminate the source component.

Uids are unique across namespace, so this would allow us to eliminate namespace, also.

**Comment by thockin** [comment] 2015-02-27 18:34
My point was that we should let sleeping dogs lie.  Unless we have a
driving need to add to this, I'd just as soon wait for docker's labels to
land, and then revisit this.  Do we have such a need?

**Comment by bgrant0607** [comment] 2015-02-27 18:34
Yes, we do. We need to change this in order to sync pods back to apiserver.

**Comment by thockin** [comment] 2015-02-27 18:35
This is about container names at the docker level, which is entirely an
implementation detail, isn't it?

**Comment by bgrant0607** [comment] 2015-02-27 18:35
And, my understanding is that pods that pass the name validation check in apiserver can fail on Kubelet due to the way the name is embedded.

**Comment by bgrant0607** [comment] 2015-02-27 18:36
No, they are tightly coupled.

**Comment by dchen1107** [comment] 2015-02-27 18:36
@thockin, I used to think this way, but syncing pods back change this. Also for 1.0 release, it is odd for users' pod creation failed in a weird way at kubelet level, but passed at apiserver validation.

**Comment by thockin** [comment] 2015-02-27 18:44
Maybe I just don't have the full context.  Why would it fail at the node
level?  The format of the container name was intended to allow pods with
the same name and namespace to not collide..

**Comment by bgrant0607** [comment] 2015-02-27 18:49
Dots break Kubelet container name parsing. Dots are explicitly allowed:
https://github.com/GoogleCloudPlatform/kubernetes/blob/master/pkg/api/validation/validation.go#L87
https://github.com/GoogleCloudPlatform/kubernetes/blob/e152c6710b8fd6cf96aa1be325187f93193b85e0/pkg/util/validation.go#L48

**Comment by davidopp** [comment] 2015-02-27 19:14
Can someone explain why this issue is being discussed now? That is -- why "We need to change this in order to sync pods back to apiserver." and what is the "this" ?

**Comment by yujuhong** [comment] 2015-02-27 19:35
Let's put the "sync pods back to apiserver" issue aside for a second. The behavior of Kubelet is wrong and inconsistent with our claim that names and namspaces should be DNS subdomain-compatible.

Multiple places in Kubelet use `.` as a delimiter, even though dot could be used in a valid name or namespaces.
For example,
* https://github.com/GoogleCloudPlatform/kubernetes/blob/master/pkg/kubelet/config/config.go#l342
* https://github.com/GoogleCloudPlatform/kubernetes/blob/master/pkg/kubelet/types.go#l79

A more concrete example would be that kubelet won't be able to run the two pods below at the same time as they all resort to the same name:
 - name: xxx, namespace: yyy.zzz
 - name: xxx.yyy, namespace: zzz

**Comment by yujuhong** [comment] 2015-02-27 19:44
@davidopp, we were discussing using hostname as part of the static pod name to avoid collision among nodes, but kubelet can't handle such names with `.`s in them.

**Comment by thockin** [comment] 2015-02-27 19:56
The docker container name is still parseable.  It is always
DNS_LABEL.DNS_SUBDOMAIN.source - If you split on ".", the first token is
the container name (which can not have dots), the last token is the source
(which should not have dots).  Everything in between is the namespace.

What problem are we having again?  Can someone lay out a concrete example
of a problem?

**Comment by thockin** [comment] 2015-02-27 20:07
Yu-Ju explained it to me.  I think we first need to break up the "fullname"
idea into real fields on the the container name, where fields are delimited
by _ (which is allowed by docker but not by us).

**Comment by bgrant0607** [comment] 2015-02-27 20:12
We need to eliminate the pod source, or at least use the same pod source for all pods.

IMO, we should also switch to uid

**Comment by thockin** [comment] 2015-02-27 21:58
Switching to UID in container names is user-hostile.  It's very valuable to
be able to run 'docker ps' and make sense of it.  Ideally, once we have
docker labels, we can store a lot of stuff there and minimize the name
string, though it is a fair concern about doing lots of docker API queries
just to get a sync loop done.

**Comment by bgrant0607** [comment] 2015-02-28 00:36
I'm not worried about the query performance. If we have an easy way to distinguish kubernetes vs. non-kubernetes containers by name, then we can cache the other metadata and we'd only have to do the queries upon restart.

**Comment by yujuhong** [comment] 2015-02-28 00:46
To sum up, there are a few issues:
 1. Change the internal full pod name to use underscore, instead of dot, as the delimiter. This will then be incorporated into the container name. This would not be backward compatible with existing containers.
 2. Get rid of `.source` in the full pod name as we want the apiserver to be aware of all pods. If we go this route, how could we know the source of the pod? Is it valuable to know the source of the pod?
 3. Where should we store the annotations? This is the what this issue was originally intended to discuss.
 4. How should we construct the container name? This can subsume (3).

I will fork new issues for (1) and (2), separately, as they are not so closely related to this issue. Also, not supporting the DNS subdomain names/namespaces is a real bug.

**Comment by bgrant0607** [comment] 2015-02-28 01:00
What "annotations"? If we eliminate container source there wouldn't be any.

**Comment by yujuhong** [comment] 2015-02-28 01:03
This issue originally discusses whether we would be adding more annotations, and if we do, how do we pass the annotations to the docker container.

**Comment by bgrant0607** [comment] 2015-02-28 01:03
https://github.com/docker/docker/pull/9882

**Comment by bgrant0607** [comment] 2015-02-28 08:28
Ref: #3764

**Comment by thockin** [comment] 2015-02-28 22:06
Imagine a pod with a single container named "ctr".

Today we have:

if it is from the API:
* name = pod.Name
* namespace = pod.Namespace
* uid = pod.UID
* source = "api"
* container_name =
"k8s_ctr.${hash_of_container}_${name}.${namespace}.${source}_${uid}_${random}"

If it is from a file:
* name = pod.Name
* namespace = "file-${hash_of_filename}-${hostname}"
* uid = ${hash_of_file_and_host_and_pod}
* source = "file"
* container_name =
k8s_ctr.${hash_of_container}_${name}.${namespace}.${source}_${uid}_${random}


Once we fix this what do we expect to see?

I assume something like:

* name = "${pod.Name}.${hash_of_file_and_host_and_pod}
* namespace = ${hostname}
* uid = ${hash_of_file_and_host_and_pod}
* source = "file"
* container_name =
k8s.${name_fmt_version}_ctr.${hash_of_container}_${name}_${namespace}_${source}_${uid}_${random}


name_fmt_version is new and lets us version this string

Do we need the random suffix?  I'm not sure what it is giving us.

What namespace do we use?  How do we ensure that this namespace doesn't
collide with one that a user created?

Should we mandate pods from files use GenerateName rather than Name?  We do
not handle that now, but we could require it, except it is not compatible.

**Comment by davidopp** [comment] 2015-02-28 23:53
For debugging it might be nice if the container name could continue to contain pod.Namespace and pod.UID in the source==API case, though I realize this is problematic if we want consistency with the file case.

**Comment by bgrant0607** [comment] 2015-03-01 00:54
Proposal:
* name = "${pod.Name}.${hostname}"
* namespace = ${cluster_namespace}
* uid = ${hash_of_file_and_host_and_pod_and_starttime}
* container_name =
k8s.${name_fmt_version}_ctr.${hash_of_container}_${name}_${namespace}_${uid}_${random}

Kubelet will be posting all pods to the API, and it needs to match the pods it gets back with those that are running, so the "source" will always be API. Therefore, I propose that we eliminate the source from the container names.

Generating one namespace per host would be a tremendous nuisance, especially for configurations that require explicit namespace creation prior to creating objects in those namespaces, but even just for reasoning about the daemons across hosts. I don't see how a per-node controller could work with that approach, for example.

GenerateName is problematic since it could collide with names generated on other nodes (unless we greatly increase the suffix size) and it would be harder to match pods received back from the API with those specified by files. We could potentially abuse it and just append the hostname instead of or in addition to the random suffix.

My guess is that the random suffix exists so that information from the previous container run isn't lost when we restart the container.

**Comment by thockin** [comment] 2015-03-01 03:51
I agree with respect to namespace.  I think Derek said the same and I just
stack - overflowed.

Keeping source in the container name might be nice for down-low debug?

GenerateName doesn't have to be the existing impl - it just has to be
unique enough, so adding hostname or hostname + 5 alphanums suffices.  The
nice thing is that we don't violate the sanctity of the Name field.

**Comment by yujuhong** [comment] 2015-03-02 20:07
I like the idea of using GenerateName, and we don't necessarily have to change the implementation. We will just have to set the prefix to be `pod.Name-hostname`. The 5 alphanums suffix will be appended in the current implementation.

Adding hostname directly in GenerateName() may not be feasible since the code is run on the apiserver (master node), so the hostname will always be the the master hostname.

**Comment by dchen1107** [comment] 2015-03-02 21:53
I marked this for 1.0 milestone. 

I agreed with Brian's proposal, and ok with nuking source.

**Comment by yujuhong** [comment] 2015-03-02 23:22
It seems we've reached the consensus. I'll take a crack a this issue since it is blocking my other issues.

The implementation will closely follow @bgrant0607  proposal, with a few clarifications/variations.
 - I agree that we should nuke source in general, but I also think that @thockin's point is valid -- we want to know the source of the container for debugging and for other purposes (e.g. #3371). Although we can always use ENV for this purpose, it seems like an overkill and potentially inefficient? Can we simply use `pod.Name-hostname-file` as the pod name?
 - What is `name_fmt_version` exactly?
 - The main delimiter (`_`) is missing in @bgrant0607's proposal for the container name. I assume this is not intentional. Without the delimiter, it's hard to figure out which part is name/namespace/uid, etc. The complete container name should be as follows.
 `k8s.${name_fmt_version}_${container_name}.${hash_of_container}_${pod_name}_${namespace}_${uid}_${random}`

Let me know if any of the above is inaccurate. I will also look into using GenerateName if possible, but that's not the blocker for now.

**Comment by dchen1107** [comment] 2015-03-02 23:42
We used to have 4 sources: etcd, apiserver, http, and file, so having source explicitly in container name is very useful; but some refactory and consolidation, in kubernetes, we are down to apiserver and file only. Some cloud providers might still have etcd for some short period, but it should be cleaned up soon. Also containervm environment has http and file as source, but that is different issue and should be ignored here. 

Once we finished sync-back feature, all source of pods on a running node should be apiserver, and the spec / status could be queried through apiserver too. In this case, I think nuking source does't hurt debuggability at all especially pod.Name has hostname embeded. 

I think @bgrant0607 used * to represent whatever main delimiter we are using today. :-)

**Comment by thockin** [comment] 2015-03-03 05:07
I have to withdraw the bits about GenerateName - if the apiserver generates
the name, do we POST to apiserver before starting the pod?  That seems
silly.  If not, then the name the apiserver will see is different than the
name the kubelet knows...

**Comment by davidopp** [comment] 2015-03-03 06:43
Maybe someone can write down end-to-end what will happen when you start a container via file and what will happen when you start a container via api server. 

Also I didn't understand @dchen1107's comment "Once we finished sync-back feature, all source of pods on a running node should be apiserver," If the source is supposed to denote how the pod was originally started (even once sync-back feature is implemented), don't we still want to distinguish file vs. api server?

**Comment by bgrant0607** [comment] 2015-03-03 15:25
Added quotes so the underscores wouldn't be eaten.

@davidopp The plan is to post all pods to the apiserver, so all locally created pods will come back to Kubelet as if they were created on apiserver originally.

**Comment by bgrant0607** [comment] 2015-03-03 15:28
Name generation in Kubelet needs to be deterministic, so that it can easily evaluate whether the pods in files have already been created or not. It's just a matter of how we want to express that.

GenerateName should have no effect in apiserver if Name is already initialized by Kubelet.

**Comment by yujuhong** [comment] 2015-03-30 17:58
The container/pod naming scheme in kubelet has been updated and the problem of using dot as the delimiter no longer exists.

I am going to close this issue. Feel free to reopen and adapt it if there is any specific issue of annotations you want to discuss.

**Closed by yujuhong** 2015-03-30 17:58 UTC
Labels: component/kubelet, kind/design, priority/P2, team/node
