### ISSUE TITLE
Kube-apiserver gives "Loaded: not found"

### ISSUE THREAD

**Issue by arun-gupta** [GoogleCloudPlatform/kubernetes#3326] opened 2015-01-08 18:46 UTC
Using Vagrant 1.7.2 on Mac OS X 10.10.1
Virtual Box 4.3.18 r96516

Following the instructions at https://github.com/GoogleCloudPlatform/kubernetes/blob/master/docs/getting-started-guides/vagrant.md

Viewing the status on kubernetes-master gives the following error:

[vagrant@kubernetes-master ~]$ sudo systemctl status kube-apiserver
kube-apiserver.service
   Loaded: not-found (Reason: No such file or directory)
   Active: inactive (dead)

[vagrant@kubernetes-master ~]$ sudo journalctl -r -u kube-apiserver
-- Logs begin at Fri 2013-12-20 13:00:20 UTC, end at Thu 2015-01-08 18:14:27 UTC. --
[vagrant@kubernetes-master ~]$ sudo systemctl status etcd
etcd.service
   Loaded: not-found (Reason: No such file or directory)
   Active: inactive (dead)

[vagrant@kubernetes-master ~]$ sudo systemctl status nginx
nginx.service
   Loaded: not-found (Reason: No such file or directory)
   Active: inactive (dead)

**Comment by pires** [comment] 2015-01-08 20:32
Try
```
cd /
find . -name *.service*
```

Post result.

**Comment by arun-gupta** [comment] 2015-01-08 20:37
```
[vagrant@kubernetes-master /]$ sudo find . -name *.service*
./sys/fs/cgroup/systemd/user.slice/user-0.slice/user@0.service
./sys/fs/cgroup/systemd/user.slice/user-900.slice/user@900.service
./sys/fs/cgroup/systemd/system.slice/polkit.service
./sys/fs/cgroup/systemd/system.slice/vboxadd-x11.service
./sys/fs/cgroup/systemd/system.slice/vboxadd.service
./sys/fs/cgroup/systemd/system.slice/plymouth-quit-wait.service
./sys/fs/cgroup/systemd/system.slice/plymouth-quit.service
./sys/fs/cgroup/systemd/system.slice/systemd-user-sessions.service
./sys/fs/cgroup/systemd/system.slice/auditd.service
./sys/fs/cgroup/systemd/system.slice/systemd-udevd.service
./sys/fs/cgroup/systemd/system.slice/lvm2-lvmetad.service
./sys/fs/cgroup/systemd/system.slice/systemd-journald.service
./sys/fs/cgroup/systemd/system.slice/network.service
./sys/fs/cgroup/systemd/system.slice/rc-local.service
./sys/fs/cgroup/systemd/system.slice/systemd-logind.service
./sys/fs/cgroup/systemd/system.slice/systemd-ask-password-wall.service
./sys/fs/cgroup/systemd/system.slice/dbus.service
./sys/fs/cgroup/systemd/system.slice/NetworkManager.service
./sys/fs/cgroup/systemd/system.slice/crond.service
./sys/fs/cgroup/systemd/system.slice/rpcbind.service
./sys/fs/cgroup/systemd/system.slice/sshd.service
./sys/fs/cgroup/systemd/system.slice/nfs-lock.service
./sys/fs/cgroup/systemd/system.slice/netconsole.service
./sys/fs/cgroup/systemd/system.slice/vboxadd-service.service
./sys/fs/cgroup/systemd/system.slice/system-getty.slice/getty@tty1.service
./run/systemd/generator/local-fs.target.wants/systemd-fsck-root.service
./usr/share/doc/python-slip-dbus/example/org.fedoraproject.slip.example.mechanism.service
./usr/share/doc/python-slip/dbus/example/org.fedoraproject.slip.example.mechanism.service
./usr/share/man/man5/firewalld.service.5.gz
./usr/share/man/man5/systemd.service.5.gz
./usr/share/man/man8/systemd-shutdownd.service.8.gz
./usr/share/man/man8/systemd-readahead-done.service.8.gz
./usr/share/man/man8/dracut-pre-udev.service.8.gz
./usr/share/man/man8/systemd-hibernate.service.8.gz
./usr/share/man/man8/systemd-fsck@.service.8.gz
./usr/share/man/man8/systemd-readahead-replay.service.8.gz
./usr/share/man/man8/systemd-initctl.service.8.gz
./usr/share/man/man8/systemd-poweroff.service.8.gz
./usr/share/man/man8/systemd-readahead-collect.service.8.gz
./usr/share/man/man8/systemd-localed.service.8.gz
./usr/share/man/man8/systemd-update-utmp-runlevel.service.8.gz
./usr/share/man/man8/dracut-cmdline.service.8.gz
./usr/share/man/man8/systemd-binfmt.service.8.gz
./usr/share/man/man8/systemd-journald.service.8.gz
./usr/share/man/man8/systemd-logind.service.8.gz
./usr/share/man/man8/systemd-hostnamed.service.8.gz
./usr/share/man/man8/systemd-vconsole-setup.service.8.gz
./usr/share/man/man8/systemd-kexec.service.8.gz
./usr/share/man/man8/dracut-pre-trigger.service.8.gz
./usr/share/man/man8/systemd-sysctl.service.8.gz
./usr/share/man/man8/dracut-mount.service.8.gz
./usr/share/man/man8/systemd-remount-fs.service.8.gz
./usr/share/man/man8/systemd-tmpfiles-clean.service.8.gz
./usr/share/man/man8/systemd-update-utmp.service.8.gz
./usr/share/man/man8/systemd-cryptsetup@.service.8.gz
./usr/share/man/man8/systemd-ask-password-wall.service.8.gz
./usr/share/man/man8/systemd-hybrid-sleep.service.8.gz
./usr/share/man/man8/systemd-user-sessions.service.8.gz
./usr/share/man/man8/systemd-halt.service.8.gz
./usr/share/man/man8/systemd-suspend.service.8.gz
./usr/share/man/man8/systemd-udevd.service.8.gz
./usr/share/man/man8/systemd-tmpfiles-setup-dev.service.8.gz
./usr/share/man/man8/systemd-tmpfiles-setup.service.8.gz
./usr/share/man/man8/systemd-quotacheck.service.8.gz
./usr/share/man/man8/systemd-timedated.service.8.gz
./usr/share/man/man8/systemd-backlight@.service.8.gz
./usr/share/man/man8/dracut-shutdown.service.8.gz
./usr/share/man/man8/dracut-pre-pivot.service.8.gz
./usr/share/man/man8/systemd-machined.service.8.gz
./usr/share/man/man8/systemd-fsck-root.service.8.gz
./usr/share/man/man8/systemd-ask-password-console.service.8.gz
./usr/share/man/man8/systemd-reboot.service.8.gz
./usr/share/man/man8/dracut-initqueue.service.8.gz
./usr/share/man/man8/dracut-pre-mount.service.8.gz
./usr/share/man/man8/systemd-random-seed.service.8.gz
./usr/share/man/man8/systemd-modules-load.service.8.gz
./usr/share/dbus-1/services/org.freedesktop.systemd1.service
./usr/share/dbus-1/services/org.gtk.GLib.PACRunner.service
./usr/share/dbus-1/system-services/org.freedesktop.NetworkManager.service
./usr/share/dbus-1/system-services/org.freedesktop.locale1.service
./usr/share/dbus-1/system-services/fi.w1.wpa_supplicant1.service
./usr/share/dbus-1/system-services/org.freedesktop.nm_dispatcher.service
./usr/share/dbus-1/system-services/org.freedesktop.hostname1.service
./usr/share/dbus-1/system-services/org.freedesktop.PolicyKit1.service
./usr/share/dbus-1/system-services/org.freedesktop.systemd1.service
./usr/share/dbus-1/system-services/org.freedesktop.timedate1.service
./usr/share/dbus-1/system-services/org.freedesktop.login1.service
./usr/share/dbus-1/system-services/fi.epitest.hostap.WPASupplicant.service
./usr/share/dbus-1/system-services/org.freedesktop.machine1.service
./usr/lib/systemd/user/systemd-exit.service
./usr/lib/systemd/system/network-online.target.wants/NetworkManager-wait-online.service
./usr/lib/systemd/system/rescue.target.wants/systemd-update-utmp-runlevel.service
./usr/lib/systemd/system/systemd-machined.service
./usr/lib/systemd/system/systemd-quotacheck.service
./usr/lib/systemd/system/lvm2-lvmetad.service
./usr/lib/systemd/system/nfs-mountd.service
./usr/lib/systemd/system/getty@.service
./usr/lib/systemd/system/fedora-autorelabel-mark.service
./usr/lib/systemd/system/rdisc.service
./usr/lib/systemd/system/NetworkManager-wait-online.service
./usr/lib/systemd/system/initrd-switch-root.service
./usr/lib/systemd/system/dracut-pre-mount.service
./usr/lib/systemd/system/nfs-blkmap.service
./usr/lib/systemd/system/initrd-parse-etc.service
./usr/lib/systemd/system/initrd.target.wants/dracut-pre-mount.service
./usr/lib/systemd/system/initrd.target.wants/dracut-pre-udev.service
./usr/lib/systemd/system/initrd.target.wants/dracut-cmdline.service
./usr/lib/systemd/system/initrd.target.wants/dracut-pre-trigger.service
./usr/lib/systemd/system/initrd.target.wants/dracut-pre-pivot.service
./usr/lib/systemd/system/initrd.target.wants/dracut-initqueue.service
./usr/lib/systemd/system/initrd.target.wants/dracut-mount.service
./usr/lib/systemd/system/runlevel4.target.wants/systemd-update-utmp-runlevel.service
./usr/lib/systemd/system/plymouth-poweroff.service
./usr/lib/systemd/system/dracut-pre-udev.service
./usr/lib/systemd/system/systemd-nspawn@.service
./usr/lib/systemd/system/systemd-random-seed.service
./usr/lib/systemd/system/plymouth-switch-root.service
./usr/lib/systemd/system/plymouth-start.service
./usr/lib/systemd/system/plymouth-quit-wait.service
./usr/lib/systemd/system/systemd-hostnamed.service
./usr/lib/systemd/system/systemd-binfmt.service
./usr/lib/systemd/system/systemd-udevd.service
./usr/lib/systemd/system/dbus-org.freedesktop.hostname1.service
./usr/lib/systemd/system/initrd-cleanup.service
./usr/lib/systemd/system/systemd-remount-fs.service
./usr/lib/systemd/system/emergency.service
./usr/lib/systemd/system/runlevel1.target.wants/systemd-update-utmp-runlevel.service
./usr/lib/systemd/system/debug-shell.service
./usr/lib/systemd/system/blk-availability.service
./usr/lib/systemd/system/nfs-idmap.service
./usr/lib/systemd/system/sshd-keygen.service
./usr/lib/systemd/system/plymouth-reboot.service
./usr/lib/systemd/system/nfs-server.service
./usr/lib/systemd/system/reboot.target.wants/plymouth-reboot.service
./usr/lib/systemd/system/reboot.target.wants/systemd-update-utmp-runlevel.service
./usr/lib/systemd/system/rpcsvcgssd.service
./usr/lib/systemd/system/dm-event.service
./usr/lib/systemd/system/local-fs.target.wants/systemd-remount-fs.service
./usr/lib/systemd/system/local-fs.target.wants/systemd-fsck-root.service
./usr/lib/systemd/system/local-fs.target.wants/fedora-readonly.service
./usr/lib/systemd/system/local-fs.target.wants/fedora-import-state.service
./usr/lib/systemd/system/console-shell.service
./usr/lib/systemd/system/dracut-cmdline.service
./usr/lib/systemd/system/user@.service
./usr/lib/systemd/system/systemd-localed.service
./usr/lib/systemd/system/sysinit.target.wants/systemd-random-seed.service
./usr/lib/systemd/system/sysinit.target.wants/plymouth-start.service
./usr/lib/systemd/system/sysinit.target.wants/systemd-binfmt.service
./usr/lib/systemd/system/sysinit.target.wants/systemd-udevd.service
./usr/lib/systemd/system/sysinit.target.wants/systemd-update-utmp.service
./usr/lib/systemd/system/sysinit.target.wants/plymouth-read-write.service
./usr/lib/systemd/system/sysinit.target.wants/systemd-sysctl.service
./usr/lib/systemd/system/sysinit.target.wants/systemd-journal-flush.service
./usr/lib/systemd/system/sysinit.target.wants/systemd-modules-load.service
./usr/lib/systemd/system/sysinit.target.wants/systemd-tmpfiles-setup-dev.service
./usr/lib/systemd/system/sysinit.target.wants/kmod-static-nodes.service
./usr/lib/systemd/system/sysinit.target.wants/systemd-vconsole-setup.service
./usr/lib/systemd/system/sysinit.target.wants/systemd-journald.service
./usr/lib/systemd/system/sysinit.target.wants/systemd-tmpfiles-setup.service
./usr/lib/systemd/system/sysinit.target.wants/systemd-udev-trigger.service
./usr/lib/systemd/system/runlevel5.target.wants/systemd-update-utmp-runlevel.service
./usr/lib/systemd/system/sshd@.service
./usr/lib/systemd/system/systemd-ask-password-console.service
./usr/lib/systemd/system/dbus.service
./usr/lib/systemd/system/systemd-poweroff.service
./usr/lib/systemd/system/arp-ethers.service
./usr/lib/systemd/system/systemd-fsck@.service
./usr/lib/systemd/system/kexec.target.wants/plymouth-kexec.service
./usr/lib/systemd/system/nfs-lock.service
./usr/lib/systemd/system/nfs.service
./usr/lib/systemd/system/dbus-org.freedesktop.timedate1.service
./usr/lib/systemd/system/systemd-udev-settle.service
./usr/lib/systemd/system/dbus-org.freedesktop.locale1.service
./usr/lib/systemd/system/multi-user.target.wants/plymouth-quit-wait.service
./usr/lib/systemd/system/multi-user.target.wants/dbus.service
./usr/lib/systemd/system/multi-user.target.wants/systemd-update-utmp-runlevel.service
./usr/lib/systemd/system/multi-user.target.wants/systemd-user-sessions.service
./usr/lib/systemd/system/multi-user.target.wants/systemd-logind.service
./usr/lib/systemd/system/multi-user.target.wants/plymouth-quit.service
./usr/lib/systemd/system/systemd-initctl.service
./usr/lib/systemd/system/systemd-timedated.service
./usr/lib/systemd/system/initrd-switch-root.target.wants/plymouth-switch-root.service
./usr/lib/systemd/system/initrd-switch-root.target.wants/plymouth-start.service
./usr/lib/systemd/system/systemd-update-utmp.service
./usr/lib/systemd/system/firewalld.service
./usr/lib/systemd/system/serial-getty@.service
./usr/lib/systemd/system/dnsmasq.service
./usr/lib/systemd/system/systemd-update-utmp-runlevel.service
./usr/lib/systemd/system/systemd-readahead-collect.service
./usr/lib/systemd/system/polkit.service
./usr/lib/systemd/system/systemd-user-sessions.service
./usr/lib/systemd/system/lvm2-monitor.service
./usr/lib/systemd/system/rescue.service
./usr/lib/systemd/system/runlevel3.target.wants/systemd-update-utmp-runlevel.service
./usr/lib/systemd/system/dbus-org.freedesktop.machine1.service
./usr/lib/systemd/system/halt-local.service
./usr/lib/systemd/system/plymouth-read-write.service
./usr/lib/systemd/system/systemd-sysctl.service
./usr/lib/systemd/system/graphical.target.wants/systemd-update-utmp-runlevel.service
./usr/lib/systemd/system/systemd-readahead-replay.service
./usr/lib/systemd/system/systemd-shutdownd.service
./usr/lib/systemd/system/systemd-journal-flush.service
./usr/lib/systemd/system/nfs-secure-server.service
./usr/lib/systemd/system/dracut-shutdown.service
./usr/lib/systemd/system/sshd.service
./usr/lib/systemd/system/systemd-ask-password-plymouth.service
./usr/lib/systemd/system/systemd-modules-load.service
./usr/lib/systemd/system/systemd-tmpfiles-setup-dev.service
./usr/lib/systemd/system/ebtables.service
./usr/lib/systemd/system/dbus-org.freedesktop.login1.service
./usr/lib/systemd/system/nfs-rquotad.service
./usr/lib/systemd/system/kmod-static-nodes.service
./usr/lib/systemd/system/systemd-hibernate.service
./usr/lib/systemd/system/rpcgssd.service
./usr/lib/systemd/system/systemd-vconsole-setup.service
./usr/lib/systemd/system/systemd-backlight@.service
./usr/lib/systemd/system/systemd-suspend.service
./usr/lib/systemd/system/systemd-fsck-root.service
./usr/lib/systemd/system/basic.target.wants/fedora-autorelabel-mark.service
./usr/lib/systemd/system/basic.target.wants/fedora-configure.service
./usr/lib/systemd/system/basic.target.wants/fedora-autorelabel.service
./usr/lib/systemd/system/basic.target.wants/fedora-loadmodules.service
./usr/lib/systemd/system/systemd-logind.service
./usr/lib/systemd/system/dracut-pre-trigger.service
./usr/lib/systemd/system/systemd-journald.service
./usr/lib/systemd/system/messagebus.service
./usr/lib/systemd/system/nfslock.service
./usr/lib/systemd/system/runlevel2.target.wants/systemd-update-utmp-runlevel.service
./usr/lib/systemd/system/nfs-secure.service
./usr/lib/systemd/system/systemd-halt.service
./usr/lib/systemd/system/fedora-domainname.service
./usr/lib/systemd/system/dracut-pre-pivot.service
./usr/lib/systemd/system/lvm2-pvscan@.service
./usr/lib/systemd/system/plymouth-kexec.service
./usr/lib/systemd/system/rpcbind.service
./usr/lib/systemd/system/fedora-configure.service
./usr/lib/systemd/system/dracut-initqueue.service
./usr/lib/systemd/system/rc-local.service
./usr/lib/systemd/system/auditd.service
./usr/lib/systemd/system/systemd-tmpfiles-clean.service
./usr/lib/systemd/system/fedora-readonly.service
./usr/lib/systemd/system/NetworkManager-dispatcher.service
./usr/lib/systemd/system/plymouth-quit.service
./usr/lib/systemd/system/systemd-tmpfiles-setup.service
./usr/lib/systemd/system/systemd-readahead-done.service
./usr/lib/systemd/system/rpcidmapd.service
./usr/lib/systemd/system/shutdown.target.wants/dracut-shutdown.service
./usr/lib/systemd/system/quotaon.service
./usr/lib/systemd/system/systemd-reboot.service
./usr/lib/systemd/system/dracut-mount.service
./usr/lib/systemd/system/plymouth-halt.service
./usr/lib/systemd/system/fedora-autorelabel.service
./usr/lib/systemd/system/fedora-loadmodules.service
./usr/lib/systemd/system/crond.service
./usr/lib/systemd/system/wpa_supplicant.service
./usr/lib/systemd/system/systemd-kexec.service
./usr/lib/systemd/system/systemd-ask-password-wall.service
./usr/lib/systemd/system/console-getty.service
./usr/lib/systemd/system/systemd-udev-trigger.service
./usr/lib/systemd/system/poweroff.target.wants/plymouth-poweroff.service
./usr/lib/systemd/system/poweroff.target.wants/systemd-update-utmp-runlevel.service
./usr/lib/systemd/system/systemd-readahead-drop.service
./usr/lib/systemd/system/initrd-udevadm-cleanup-db.service
./usr/lib/systemd/system/systemd-hybrid-sleep.service
./usr/lib/systemd/system/halt.target.wants/plymouth-halt.service
./usr/lib/systemd/system/fedora-import-state.service
./usr/lib/systemd/system/NetworkManager.service
./usr/lib/systemd/system/autovt@.service
./usr/lib/dracut/modules.d/90dmsquash-live/checkisomd5@.service
./usr/lib/dracut/modules.d/98systemd/dracut-mount.service.8
./usr/lib/dracut/modules.d/98systemd/dracut-pre-mount.service
./usr/lib/dracut/modules.d/98systemd/dracut-emergency.service
./usr/lib/dracut/modules.d/98systemd/dracut-pre-udev.service
./usr/lib/dracut/modules.d/98systemd/dracut-initqueue.service.8.asc
./usr/lib/dracut/modules.d/98systemd/dracut-shutdown.service.8
./usr/lib/dracut/modules.d/98systemd/emergency.service
./usr/lib/dracut/modules.d/98systemd/dracut-pre-pivot.service.8
./usr/lib/dracut/modules.d/98systemd/dracut-cmdline.service
./usr/lib/dracut/modules.d/98systemd/dracut-mount.service.8.asc
./usr/lib/dracut/modules.d/98systemd/rescue.service
./usr/lib/dracut/modules.d/98systemd/dracut-shutdown.service
./usr/lib/dracut/modules.d/98systemd/dracut-pre-trigger.service.8
./usr/lib/dracut/modules.d/98systemd/dracut-pre-udev.service.8.asc
./usr/lib/dracut/modules.d/98systemd/dracut-cmdline.service.8
./usr/lib/dracut/modules.d/98systemd/dracut-pre-trigger.service
./usr/lib/dracut/modules.d/98systemd/dracut-pre-pivot.service
./usr/lib/dracut/modules.d/98systemd/dracut-initqueue.service
./usr/lib/dracut/modules.d/98systemd/dracut-pre-mount.service.8
./usr/lib/dracut/modules.d/98systemd/dracut-pre-mount.service.8.asc
./usr/lib/dracut/modules.d/98systemd/dracut-pre-trigger.service.8.asc
./usr/lib/dracut/modules.d/98systemd/dracut-pre-pivot.service.8.asc
./usr/lib/dracut/modules.d/98systemd/dracut-pre-udev.service.8
./usr/lib/dracut/modules.d/98systemd/dracut-mount.service
./usr/lib/dracut/modules.d/98systemd/dracut-cmdline.service.8.asc
./usr/lib/dracut/modules.d/98systemd/dracut-shutdown.service.8.asc
./usr/lib/dracut/modules.d/98systemd/dracut-initqueue.service.8
./etc/systemd/system/syslog.service
./etc/systemd/system/system-update.target.wants/systemd-readahead-drop.service
./etc/systemd/system/sysinit.target.wants/lvm2-monitor.service
./etc/systemd/system/default.target.wants/systemd-readahead-collect.service
./etc/systemd/system/default.target.wants/systemd-readahead-replay.service
./etc/systemd/system/multi-user.target.wants/sshd.service
./etc/systemd/system/multi-user.target.wants/rpcbind.service
./etc/systemd/system/multi-user.target.wants/auditd.service
./etc/systemd/system/multi-user.target.wants/crond.service
./etc/systemd/system/multi-user.target.wants/NetworkManager.service
./etc/systemd/system/firewalld.service
./etc/systemd/system/getty.target.wants/getty@tty1.service
./etc/systemd/system/dbus-org.freedesktop.NetworkManager.service
./etc/systemd/system/dbus-org.freedesktop.nm-dispatcher.service
./etc/systemd/system/nfs.target.wants/nfs-lock.service
```

**Comment by pires** [comment] 2015-01-08 20:41
I see no kube related services on that system.

**Comment by arun-gupta** [comment] 2015-01-08 20:44
Here is what I did:

``export KUBERNETES_PROVIDER=vagrant
cluster/kube-up.sh``

What is missing?

**Comment by pires** [comment] 2015-01-08 20:59
Probably something changed and broke the installation. Not sure! I'm following another approach as you may have seen in #3244.

**Comment by derekwaynecarr** [comment] 2015-01-09 03:25
There was a change to Vagrant between versions 1.6 and 1.7 for how provisioner are passed.

We had to make a change recently in the OpenShift Origin repo to address:
https://github.com/openshift/origin/pull/578

You can see what we did there, I will make a similar port to Kubernetes repo tomorrow.

You can use a vagrant version >= 1.6.2 but < 1.7.1 and things should be fine.

**Comment by derekwaynecarr** [comment] 2015-01-10 16:40
Do a $make release to build the code first then do the cluster/kube-up

**Comment by arun-gupta** [comment] 2015-01-10 23:48
Kubernetes is already built, can start a cluster using https://github.com/ghodss/kubernetes-macosx-development

**Comment by arun-gupta** [comment] 2015-01-13 23:29
Built it all over again, and now it seems to be working.

**Comment by arun-gupta** [comment] 2015-01-14 00:40
This required to add 127.0.0.1 to localhost mapping in /etc/hosts. Defaults should work out of the box and so reopening this bug.

**Comment by derekwaynecarr** [comment] 2015-01-30 06:02
@arun-gupta - are you running with any vagrant plugins?

**Comment by arun-gupta** [comment] 2015-01-30 06:08
```
kubernetes> vagrant plugin list
vagrant-share (1.1.3, system)
```

**Comment by bwahn** [comment] 2015-02-11 04:58
I have same problem.
[vagrant@kubernetes-master ~]$ sudo systemctl status kube-apiserver
kube-apiserver.service
   Loaded: not-found (Reason: No such file or directory)
   Active: inactive (dead)
and there are no kube of service in vagrant.

**Comment by arun-gupta** [comment] 2015-02-11 05:07
Vagrant has been working more often for me now. Latest blog at http://blog.arungupta.me/mysql-kubernetes-service-access-wildfly-pod-techtip72/ provide more details.

**Comment by derekwaynecarr** [comment] 2015-02-11 05:23
Arun - nice blog post.  Wanted to make sure you knew that you can view the log for a container using kubectl log instead of docker exec.

**Comment by arun-gupta** [comment] 2015-02-11 05:35
That would only work with Kubernetes though, ot in a pure Docker environment, right?

Every day is a new learning :)

**Comment by derekwaynecarr** [comment] 2015-03-03 21:47
I am unable to reproduce the issue where /etc/hosts is not showing a mapping.

This should be handled by vagrant automatically inserting the entry in /etc/hosts based on the configured minion host name.

If I ssh into a box I see:

```shell
[vagrant@kubernetes-master ~]$ cat /etc/hosts
127.0.0.1 kubernetes-master kubernetes-master
::1         localhost localhost.localdomain localhost6 localhost6.localdomain6
10.245.1.3 kubernetes-minion-1
```

We add entries for each minion in the provision shell scripts, but the host name entry should be based on the vagrant plug-in itself.

Can you let me know what you see in your /etc/hosts if you are still seeing this issue after an initial creation?

**Comment by davidopp** [comment] 2015-03-19 06:50
Ping? This issue hasn't been updated in 2 weeks.

**Comment by derekwaynecarr** [comment] 2015-03-19 19:32
The change to add 127.0.0.1 mapping to etc/hosts for localhost was added here:

https://github.com/GoogleCloudPlatform/kubernetes/pull/5557

Closing this issue.

**Closed by derekwaynecarr** 2015-03-19 19:32 UTC
Labels: priority/P2, team/master
