### ISSUE TITLE
0.21.0 rc, vagrant: kube-dns failing

### ISSUE THREAD

**Issue by alexanderguzhva** [GoogleCloudPlatform/kubernetes#10900] opened 2015-07-08 00:37 UTC
39b013a
1) fresh installation without any problems, using vagrant as a cloud provider
2) kube-up.sh
3) vagrant ssh master

from kubernetes-master:
```
-- Logs begin at Tue 2015-02-24 15:27:58 UTC, end at Wed 2015-07-08 00:29:49 UTC. --
Jul 08 00:08:31 kubernetes-master kubelet[4356]: I0708 00:08:31.171374    4356 manager.go:1123] Killing container with id "596ba4ce91ac89d2d6d2b324b23548ac8058839ea0b894c0f2b745cf32c88091"
Jul 08 00:08:31 kubernetes-master kubelet[4356]: I0708 00:08:31.171125    4356 manager.go:1446] pod "kube-apiserver-kubernetes-master_default" container "kube-apiserver" is unhealthy (probe result: failure), it will be killed and re-created.
Jul 08 00:08:31 kubernetes-master kubelet[4356]: I0708 00:08:31.170488    4356 prober.go:129] Liveness probe for "kube-apiserver-kubernetes-master_default:kube-apiserver" failed (failure): Get http://:8080/healthz: dial tcp :8080: connection refused
Jul 08 00:08:13 kubernetes-master kubelet[4356]: I0708 00:08:13.911590    4356 docker.go:154] Pulling image gcr.io/google_containers/etcd:2.0.12 without credentials
Jul 08 00:08:06 kubernetes-master kubelet[4356]: I0708 00:08:06.423756    4356 docker.go:154] Pulling image gcr.io/google_containers/pause:0.8.0 without credentials
Jul 08 00:08:06 kubernetes-master kubelet[4356]: I0708 00:08:06.322592    4356 docker.go:154] Pulling image gcr.io/google_containers/pause:0.8.0 without credentials
Jul 08 00:08:01 kubernetes-master kubelet[4356]: I0708 00:08:01.320242    4356 docker.go:154] Pulling image gcr.io/google_containers/pause:0.8.0 without credentials
Jul 08 00:08:01 kubernetes-master kubelet[4356]: I0708 00:08:01.273428    4356 docker.go:154] Pulling image gcr.io/google_containers/pause:0.8.0 without credentials
Jul 08 00:08:01 kubernetes-master kubelet[4356]: I0708 00:08:01.273153    4356 provider.go:91] Refreshing cache for provider: *credentialprovider.defaultDockerConfigProvider
Jul 08 00:08:01 kubernetes-master kubelet[4356]: I0708 00:08:01.137492    4356 manager.go:1384] Need to restart pod infra container for "kube-scheduler-kubernetes-master_default" because it is not found
Jul 08 00:08:01 kubernetes-master kubelet[4356]: I0708 00:08:01.134779    4356 manager.go:1384] Need to restart pod infra container for "kube-controller-manager-kubernetes-master_default" because it is not found
Jul 08 00:08:01 kubernetes-master kubelet[4356]: I0708 00:08:01.132449    4356 manager.go:1384] Need to restart pod infra container for "kube-apiserver-kubernetes-master_default" because it is not found
Jul 08 00:08:01 kubernetes-master kubelet[4356]: I0708 00:08:01.129625    4356 manager.go:1384] Need to restart pod infra container for "etcd-server-kubernetes-master_default" because it is not found
Jul 08 00:08:01 kubernetes-master kubelet[4356]: I0708 00:08:01.116027    4356 kubelet.go:1725] Starting kubelet main sync loop.
Jul 08 00:08:01 kubernetes-master kubelet[4356]: I0708 00:08:01.115758    4356 status_manager.go:72] Kubernetes client is nil, not starting status manager.
Jul 08 00:08:01 kubernetes-master kubelet[4356]: I0708 00:08:01.109144    4356 manager.go:248] Recovery completed
Jul 08 00:08:01 kubernetes-master kubelet[4356]: I0708 00:08:01.103110    4356 manager.go:243] Starting recovery of all containers
Jul 08 00:08:01 kubernetes-master kubelet[4356]: I0708 00:08:01.095751    4356 oomparser.go:183] oomparser using systemd
Jul 08 00:08:01 kubernetes-master kubelet[4356]: I0708 00:08:01.089783    4356 manager.go:946] Started watching for new ooms in manager
Jul 08 00:08:01 kubernetes-master kubelet[4356]: I0708 00:08:01.022662    4356 factory.go:89] Registering Raw factory
Jul 08 00:08:01 kubernetes-master kubelet[4356]: I0708 00:08:01.022227    4356 factory.go:234] Registering Docker factory
Jul 08 00:08:01 kubernetes-master kubelet[4356]: I0708 00:08:01.021710    4356 factory.go:226] System is using systemd
Jul 08 00:08:00 kubernetes-master kubelet[4356]: I0708 00:08:00.758882    4356 kubelet.go:702] Running in container "/kubelet"
Jul 08 00:08:00 kubernetes-master kubelet[4356]: I0708 00:08:00.739210    4356 server.go:63] Starting to listen on 0.0.0.0:10250
Jul 08 00:08:00 kubernetes-master kubelet[4356]: I0708 00:08:00.738956    4356 server.go:82] Starting to listen read-only on 0.0.0.0:10255
Jul 08 00:08:00 kubernetes-master kubelet[4356]: W0708 00:08:00.736336    4356 kubelet.go:693] No api server defined - no node status update will be sent.
Jul 08 00:08:00 kubernetes-master kubelet[4356]: E0708 00:08:00.736310    4356 kubelet.go:682] Image garbage collection failed: unable to find data for container /
Jul 08 00:08:00 kubernetes-master kubelet[4356]: I0708 00:08:00.736078    4356 server.go:623] Started kubelet
Jul 08 00:08:00 kubernetes-master kubelet[4356]: I0708 00:08:00.735987    4356 plugins.go:180] Loaded volume plugin "kubernetes.io/rbd"
Jul 08 00:08:00 kubernetes-master kubelet[4356]: I0708 00:08:00.735966    4356 plugins.go:180] Loaded volume plugin "kubernetes.io/persistent-claim"
Jul 08 00:08:00 kubernetes-master kubelet[4356]: I0708 00:08:00.735943    4356 plugins.go:180] Loaded volume plugin "kubernetes.io/glusterfs"
Jul 08 00:08:00 kubernetes-master kubelet[4356]: I0708 00:08:00.735923    4356 plugins.go:180] Loaded volume plugin "kubernetes.io/iscsi"
Jul 08 00:08:00 kubernetes-master kubelet[4356]: I0708 00:08:00.735904    4356 plugins.go:180] Loaded volume plugin "kubernetes.io/secret"
Jul 08 00:08:00 kubernetes-master kubelet[4356]: I0708 00:08:00.735884    4356 plugins.go:180] Loaded volume plugin "kubernetes.io/nfs"
Jul 08 00:08:00 kubernetes-master kubelet[4356]: I0708 00:08:00.735863    4356 plugins.go:180] Loaded volume plugin "kubernetes.io/host-path"
Jul 08 00:08:00 kubernetes-master kubelet[4356]: I0708 00:08:00.735843    4356 plugins.go:180] Loaded volume plugin "git"
Jul 08 00:08:00 kubernetes-master kubelet[4356]: I0708 00:08:00.735831    4356 plugins.go:180] Loaded volume plugin "kubernetes.io/git-repo"
Jul 08 00:08:00 kubernetes-master kubelet[4356]: I0708 00:08:00.735812    4356 plugins.go:180] Loaded volume plugin "gce-pd"
Jul 08 00:08:00 kubernetes-master kubelet[4356]: I0708 00:08:00.735798    4356 plugins.go:180] Loaded volume plugin "kubernetes.io/gce-pd"
Jul 08 00:08:00 kubernetes-master kubelet[4356]: I0708 00:08:00.735779    4356 plugins.go:180] Loaded volume plugin "empty"
Jul 08 00:08:00 kubernetes-master kubelet[4356]: I0708 00:08:00.735764    4356 plugins.go:180] Loaded volume plugin "kubernetes.io/empty-dir"
Jul 08 00:08:00 kubernetes-master kubelet[4356]: I0708 00:08:00.735718    4356 plugins.go:180] Loaded volume plugin "kubernetes.io/aws-ebs"
Jul 08 00:08:00 kubernetes-master kubelet[4356]: I0708 00:08:00.733869    4356 container_manager_linux.go:100] Configure resource-only container /docker-daemon with memory limit: 729381273
Jul 08 00:08:00 kubernetes-master kubelet[4356]: I0708 00:08:00.733798    4356 plugins.go:56] Registering credential provider: .dockercfg
Jul 08 00:08:00 kubernetes-master kubelet[4356]: I0708 00:08:00.424357    4356 file.go:47] Watching path "/etc/kubernetes/manifests"
Jul 08 00:08:00 kubernetes-master kubelet[4356]: I0708 00:08:00.423887    4356 server.go:651] Adding manifest file: /etc/kubernetes/manifests
Jul 08 00:08:00 kubernetes-master kubelet[4356]: W0708 00:08:00.423421    4356 server.go:599] No api server defined - no events will be sent to API server.
Jul 08 00:08:00 kubernetes-master kubelet[4356]: I0708 00:08:00.422788    4356 server.go:586] cloud provider determined current node name to be kubernetes-master
Jul 08 00:08:00 kubernetes-master kubelet[4356]: I0708 00:08:00.419880    4356 docker.go:289] Connecting to docker on unix:///var/run/docker.sock
Jul 08 00:07:59 kubernetes-master kubelet[4356]: I0708 00:07:59.182320    4356 server.go:290] Successfully initialized cloud provider: "vagrant" from the config file: ""
Jul 08 00:07:59 kubernetes-master kubelet[4356]: I0708 00:07:59.181373    4356 manager.go:163] Version: {KernelVersion:3.17.4-301.fc21.x86_64 ContainerOsVersion:Fedora 21 (Twenty One) DockerVersion:1.6.0 CadvisorVersion:0.15.1}
Jul 08 00:07:59 kubernetes-master kubelet[4356]: I0708 00:07:59.179879    4356 manager.go:156] Machine: {NumCores:2 CpuFrequency:2216426 MemoryCapacity:1041973248 MachineID:6c30ad3b41fa4d1e89745cef6f22c4de SystemUUID:E29C858C-0D05-4D3E-B15A-DEF722546F8E BootID:3c54df27-9f24-4313-b837-52f22e7c89f7 Filesystems:[{Device:/dev/mapper/vg_vagrant-lv_root Capacity:40192565248} {Device:/dev/sda1 Capacity:499355648}] DiskMap:map[253:2:{Name:dm-2 Major:253 Minor:2 Size:107374182400 Scheduler:none} 253:3:{Name:dm-3 Major:253 Minor:3 Size:10737418240 Scheduler:none} 8:0:{Name:sda Major:8 Minor:0 Size:42949672960 Scheduler:cfq} 253:0:{Name:dm-0 Major:253 Minor:0 Size:40969961472 Scheduler:none} 253:1:{Name:dm-1 Major:253 Minor:1 Size:1107296256 Scheduler:none}] NetworkDevices:[{Name:cbr0 MacAddress:ee:90:03:9c:d2:43 Speed:0 Mtu:1500} {Name:eth0 MacAddress:08:00:27:9d:d2:72 Speed:0 Mtu:1500} {Name:eth1 MacAddress:08:00:27:d8:26:3c Speed:0 Mtu:1500} {Name:obr0 MacAddress:3e:0d:ab:42:ee:4d Speed:0 Mtu:1500} {Name:ovs-system MacAddress:36:ae:d5:b0:6a:df Speed:0 Mtu:1500} {Name:tun0 MacAddress:ee:90:03:9c:d2:43 Speed:0 Mtu:1500}] Topology:[{Id:0 Memory:1041973248 Cores:[{Id:0 Threads:[0] Caches:[{Size:32768 Type:Data Level:1} {Size:32768 Type:Data Level:1}]} {Id:1 Threads:[1] Caches:[{Size:32768 Type:Data Level:1} {Size:32768 Type:Data Level:1}]}] Caches:[]}]}
Jul 08 00:07:59 kubernetes-master kubelet[4356]: I0708 00:07:59.176435    4356 fs.go:93] Filesystem partitions: map[/dev/mapper/vg_vagrant-lv_root:{mountpoint:/ major:253 minor:0} /dev/sda1:{mountpoint:/boot major:8 minor:1}]
Jul 08 00:07:59 kubernetes-master kubelet[4356]: I0708 00:07:59.176044    4356 manager.go:127] cAdvisor running in container: "/"
Jul 08 00:07:59 kubernetes-master kubelet[4356]: I0708 00:07:59.175937    4356 server.go:271] Using root directory: /var/lib/kubelet
Jul 08 00:07:59 kubernetes-master systemd[1]: Started Kubernetes Kubelet Server.
Jul 08 00:07:59 kubernetes-master systemd[1]: Starting Kubernetes Kubelet Server...
```

```
[root@kubernetes-master vagrant]# kubelet get rc
I0708 00:31:19.602948   10437 manager.go:127] cAdvisor running in container: "/user.slice"
I0708 00:31:19.603780   10437 fs.go:93] Filesystem partitions: map[/dev/mapper/vg_vagrant-lv_root:{mountpoint:/ major:253 minor:0} /dev/sda1:{mountpoint:/boot major:8 minor:1}]
I0708 00:31:19.606981   10437 manager.go:156] Machine: {NumCores:2 CpuFrequency:2216426 MemoryCapacity:1041973248 MachineID:6c30ad3b41fa4d1e89745cef6f22c4de SystemUUID:E29C858C-0D05-4D3E-B15A-DEF722546F8E BootID:3c54df27-9f24-4313-b837-52f22e7c89f7 Filesystems:[{Device:/dev/mapper/vg_vagrant-lv_root Capacity:40192565248} {Device:/dev/sda1 Capacity:499355648}] DiskMap:map[253:0:{Name:dm-0 Major:253 Minor:0 Size:40969961472 Scheduler:none} 253:11:{Name:dm-11 Major:253 Minor:11 Size:10737418240 Scheduler:none} 253:2:{Name:dm-2 Major:253 Minor:2 Size:107374182400 Scheduler:none} 253:4:{Name:dm-4 Major:253 Minor:4 Size:10737418240 Scheduler:none} 253:6:{Name:dm-6 Major:253 Minor:6 Size:10737418240 Scheduler:none} 253:8:{Name:dm-8 Major:253 Minor:8 Size:10737418240 Scheduler:none} 8:0:{Name:sda Major:8 Minor:0 Size:42949672960 Scheduler:cfq} 253:1:{Name:dm-1 Major:253 Minor:1 Size:1107296256 Scheduler:none} 253:10:{Name:dm-10 Major:253 Minor:10 Size:10737418240 Scheduler:none} 253:3:{Name:dm-3 Major:253 Minor:3 Size:10737418240 Scheduler:none} 253:5:{Name:dm-5 Major:253 Minor:5 Size:10737418240 Scheduler:none} 253:7:{Name:dm-7 Major:253 Minor:7 Size:10737418240 Scheduler:none} 253:9:{Name:dm-9 Major:253 Minor:9 Size:10737418240 Scheduler:none}] NetworkDevices:[{Name:cbr0 MacAddress:ee:90:03:9c:d2:43 Speed:0 Mtu:1500} {Name:eth0 MacAddress:08:00:27:9d:d2:72 Speed:0 Mtu:1500} {Name:eth1 MacAddress:08:00:27:d8:26:3c Speed:0 Mtu:1500} {Name:obr0 MacAddress:3e:0d:ab:42:ee:4d Speed:0 Mtu:1500} {Name:ovs-system MacAddress:36:ae:d5:b0:6a:df Speed:0 Mtu:1500} {Name:tun0 MacAddress:ee:90:03:9c:d2:43 Speed:0 Mtu:1500}] Topology:[{Id:0 Memory:1041973248 Cores:[{Id:0 Threads:[0] Caches:[{Size:32768 Type:Data Level:1} {Size:32768 Type:Data Level:1}]} {Id:1 Threads:[1] Caches:[{Size:32768 Type:Data Level:1} {Size:32768 Type:Data Level:1}]}] Caches:[]}]}
I0708 00:31:19.609267   10437 manager.go:163] Version: {KernelVersion:3.17.4-301.fc21.x86_64 ContainerOsVersion:Fedora 21 (Twenty One) DockerVersion:1.6.0 CadvisorVersion:0.15.1}
I0708 00:31:19.610339   10437 plugins.go:69] No cloud provider specified.
I0708 00:31:19.611888   10437 cadvisor_linux.go:99] Failed to register cAdvisor on port 4194, retrying. Error: listen tcp :4194: bind: address already in use
I0708 00:31:20.188892   10437 docker.go:289] Connecting to docker on unix:///var/run/docker.sock
W0708 00:31:20.191026   10437 server.go:599] No api server defined - no events will be sent to API server.
I0708 00:31:20.433507   10437 plugins.go:56] Registering credential provider: .dockercfg
I0708 00:31:20.434771   10437 server.go:623] Started kubelet
E0708 00:31:20.434992   10437 kubelet.go:682] Image garbage collection failed: unable to find data for container /
W0708 00:31:20.435012   10437 kubelet.go:693] No api server defined - no node status update will be sent.
I0708 00:31:20.438198   10437 server.go:63] Starting to listen on 0.0.0.0:10250
E0708 00:31:20.443081   10437 server.go:379] Starting health server failed: listen tcp 127.0.0.1:10248: bind: address already in use
F0708 00:31:20.444267   10437 server.go:93] listen tcp 0.0.0.0:10255: bind: address already in use
I0708 00:31:20.455908   10437 kubelet.go:702] Running in container "/kubelet"
```
kubelet (even without any arguments) on both master and minions produces the same error as above

**Comment by yujuhong** [comment] 2015-07-08 00:54
@alexanderguzhva, I think you meant to run `kubectl`, instead of `kubelet`. Running `kubelet` starts another kubelet process, which would fail due to insufficient args and already bound ports.

**Comment by alexanderguzhva** [comment] 2015-07-08 01:15
whoops 8)
anyway, kubectl shows no pods and no rcs, this is different from the previous versions
```
[root@kubernetes-master vagrant]# kubectl get pods
NAME      READY     STATUS    RESTARTS   AGE
[root@kubernetes-master vagrant]# kubectl get rc
CONTROLLER   CONTAINER(S)   IMAGE(S)   SELECTOR   REPLICAS
[root@kubernetes-master vagrant]# kubectl get services
NAME         LABELS                                    SELECTOR   IP(S)        PORT(S)
kubernetes   component=apiserver,provider=kubernetes   <none>     10.247.0.1   443/TCP
```
Maybe, this is expected, but I am sure that previous versions contained kube-dns pods. But I also see that minions constantly try to restart skydns (every 30 seconds), so I wasn't sure whether apiserver is the root of the problem
```
Jul 08 01:06:05 kubernetes-minion-1 kubelet[455]: I0708 01:06:05.675067     455 manager.go:1123] Killing container with id "a557a23bddc063f4657b3a1441081806179d8b1324ed
9eaa9f0b5218682dc50a"
Jul 08 01:06:05 kubernetes-minion-1 kubelet[455]: I0708 01:06:05.675049     455 manager.go:1446] pod "kube-dns-v5-wgxn1_kube-system" container "skydns" is unhealthy (pr
obe result: failure), it will be killed and re-created.
Jul 08 01:06:05 kubernetes-minion-1 kubelet[455]: I0708 01:06:05.675019     455 prober.go:129] Liveness probe for "kube-dns-v5-wgxn1_kube-system:skydns" failed (failure
): nslookup: can't resolve 'kubernetes.default.svc.cluster.local'
```

**Comment by yujuhong** [comment] 2015-07-08 01:20
@alexanderguzhva, we recently moved all cluster add-ons pods from the `default` to the `kube-system` namespaces. You could run `kubectl get pods --all-namespaces` to see pods across all namespaces.


> But I also see that minions constantly try to restart skydns (every 30 seconds), so I wasn't sure whether apiserver is the root of the problem

This doesn't seem right. Liveness probe should not fail. Is the problem reproducible?

**Comment by alexanderguzhva** [comment] 2015-07-08 01:25
@yujuhong yes. Also, there were similar problems in 0.19.1, check #10158

**Comment by yujuhong** [comment] 2015-07-08 01:32
@alexanderguzhva, could you post a more complete version of kubelet.log (both master and minion) on http://gist.github.com ? We would have a more complete picture and can compare with the previous issue #10158. Thanks.

**Comment by alexanderguzhva** [comment] 2015-07-08 02:08
@yujuhong  here you are https://gist.github.com/alexanderguzhva/ecfce4551895a93be731
hope it helps!

**Comment by thockin** [comment] 2015-07-09 06:06
@derekwaynecarr

**Comment by derekwaynecarr** [comment] 2015-07-09 14:40
I just tried to reproduce this by doing the following:

Host OS: Fedora 21
Virtualization Provider: VirtualBox

```
$ git fetch upstream
$ git checkout release-0.21
$ make clean && make quick-release
$ export NUM_MINIONS=2
$ cluster/kube-up.sh
....
Found 2 nodes.
        NAME         LABELS                              STATUS
     1	10.245.1.3   kubernetes.io/hostname=10.245.1.3   Ready
     2	10.245.1.4   kubernetes.io/hostname=10.245.1.4   Ready
Validate output:
NAME                 STATUS    MESSAGE              ERROR
scheduler            Healthy   ok                   nil
etcd-0               Healthy   {"health": "true"}   nil
controller-manager   Healthy   ok                   nil
Cluster validation succeeded
Done, listing cluster services:

Kubernetes master is running at https://10.245.1.2
KubeDNS is running at https://10.245.1.2/api/v1/proxy/namespaces/kube-system/services/kube-dns
KubeUI is running at https://10.245.1.2/api/v1/proxy/namespaces/kube-system/services/kube-ui

$ cluster/kubectl.sh get pods --all-namespaces
NAMESPACE     NAME                READY     STATUS    RESTARTS   AGE
kube-system   kube-dns-v6-008gc   3/3       Running   0          4m
kube-system   kube-ui-v1-t0a1o    1/1       Running   0          4m

$ cluster/kubectl.sh logs kube-dns-v6-008gc kube2sky --namespace=kube-system
I0709 14:22:43.512952       1 kube2sky.go:389] Etcd server found: http://127.0.0.1:4001
I0709 14:22:44.515584       1 kube2sky.go:455] Using https://10.247.0.1:443 for kubernetes master
I0709 14:22:44.515622       1 kube2sky.go:456] Using kubernetes API 
```

I then followed the "How do I test if this is working?" issue instructions here:

https://github.com/GoogleCloudPlatform/kubernetes/blob/master/cluster/addons/dns/README.md

```
[decarr@localhost kubernetes (release-0.21)]$ cluster/kubectl.sh create -f busybox.yaml 
pods/busybox
[decarr@localhost kubernetes (release-0.21)]$ cluster/kubectl.sh get pods
NAME      READY     STATUS    RESTARTS   AGE
busybox   1/1       Running   0          1m
[decarr@localhost kubernetes (release-0.21)]$ cluster/kubectl.sh exec busybox -- nslookup kubernetes
Server:    10.247.0.10
Address 1: 10.247.0.10

Name:      kubernetes
Address 1: 10.247.0.1
```

So for me, things looked pretty good.

Can you elaborate what is different in your setup versus mine?

**Comment by derekwaynecarr** [comment] 2015-07-09 14:42
I am closing this issue, but feel free to re-open if you continue to see a problem.  If you do, please provide the output of the same steps I documented above, include what virtualization tool you are using, and from what host platform.

Thanks!

**Closed by derekwaynecarr** 2015-07-09 14:42 UTC
Labels: kind/support, priority/P2, team/cluster
