### ISSUE TITLE
Make 99% of API calls return in less than 1s; constant time to number of nodes and pods

### ISSUE THREAD

**Issue by davidopp** [GoogleCloudPlatform/kubernetes#4521] opened 2015-02-18 07:08 UTC
@lavalamp would you be interested in taking this (it's from the v1.0 roadmap)?

Also cc'ing @roberthbailey and @satnam6502 for good measure.

**Comment by gmarek-google** [comment] 2015-02-18 08:56
I'm looking at slow 'get pods' call #4196 and have a few observations about API server performance. I added a doc about turning on profiling to docs/devel, which should be helpful for trying to find bottlenecks. Sadly AFAICT most of the time is spent in YAML handling, which I guess means that we need to reduce number of etcd entries parsed in normal workflow, try to parallelize some of them, write custom YAML parser or change the way things are stored in etcd.

As first two options have no impact on things outside the master I'm trying to apply them to get pods call. I've already tried parallelizing, but it do not give big improvement.

Also I'm sometimes seeing slow response from server when checking metrics. Most of the times it's instantaneous, but once in a while it takes few seconds. I don't know yet how metrics are stored/computed, but (I guess) it's not a master API call. This could mean that there may be a problem with HTTP server being slow/overcommited from time to time.

**Comment by gmarek-google** [comment] 2015-02-18 11:26
There's an issue with this goal, namely there's no machine on which API server should have this <1sec. performance. It is important, as on GCE by default we're running on single threaded CPU, hence there's not a lot of space for parallelization of anything.

**Comment by lavalamp** [comment] 2015-02-18 16:51
1) Have we measured this and is it actually not meeting this target?
1.a) As Marek said, what is the golden system configuration upon which we will take this measurement? What is its load? 1s is meaningless by itself. I'd rather say "contstant time, with a low constant factor".

Even though it's single-core, parellelizing should still help if there's network access. I think I already did that before I left a month ago in the places it was appropriate, though.

...also it might be worth double checking if we ever allow more than one thread by setting GOMAXPROCS.

**Comment by davidopp** [comment] 2015-02-18 18:56
@lavalamp No, we haven't measured. It's possible that we already meet the goal. Also, as you noted, the goal here is under-defined, as it doesn't specify a workload. (I beileve @satnam6502 is working on workload generators.) So, part of this issue is to define a workload.

**Comment by gmarek-google** [comment] 2015-02-18 19:23
I added parallel decoding of data extracted from etcd for get pods, as it takes 1.5 to 6 sec when 50 pods are present (it's more like 1.2-4 with an empty cluster). It did not help.

Additionally ```get replicationcontroller``` is EXTREMELY slow, as per #4536. What is worse than this 15 sec "normal" runtime is that when I was trying to do ```get``` during the time when ```stop``` is running easily takes 150 sec (yup: 2.5 minutes). I noticed it in the evening, so I didn't have time to investigate it further.

I traced only APIserver part of execution.

**Comment by gmarek-google** [comment] 2015-02-19 12:54
Rephrasing my previous comment: ```get rc``` running time is far from constant. From <1sec in empty cluster to >15 sec when there's 50 RCs running, and minutes when multiple '''stop rc''' are under way (easily reproducible).

We should agree on some golden master/node configuration. I think it's kind of important, as if we assume that master will be running on single thread, the architecture may be quite different, than if we assume multithreaded one. In addition if we're aiming at multithreaded master I believe that we should add a second thread to the default configuration of the master machine for each provider, to make testing more realistic. Similar thing applies to node machines.

My personal opinion is that we should assume that both master and kubelet are running on multithreaded machines, and modify our default accordingly.
We should agree on some golden master/node configuration. I think it's kind of important, as if we assume that master will be running on single thread, the architecture may be quite different, than if we assume multithreaded one. In addition if we're aiming at multithreaded master I believe that we should add a second thread to the default configuration of the master machine for each provider, to make testing more realistic. Similar thing applies to node machines.

My personal opinion is that we should assume that both master and kubelet are running on multithreaded machines, and modify our default accordingly.

**Comment by vmarmol** [comment] 2015-02-19 16:51
As per @gmarek's comment it seems reasonable to provide a minimum spec of X cores for our SLO of Y. It does seem unreasonable to expect a single core machine to run 50 pods (of any size) in a timely manner.

**Comment by satnam6502** [comment] 2015-02-19 17:09
When I was last doing experiments I used n n1-highmem-16 master and I also tried a n1-highcpu-16 master but still ran into lots of issues -- perhaps because our API server needs to be (more?) multi-threaded?

**Comment by lavalamp** [comment] 2015-02-19 18:29
OK, I see we don't actually use GOMAXPROCS outside of our tests. I'm making a PR to add that in, so at least we'll use more cores if we have them.

**Comment by gmarek** [comment] 2015-02-20 18:05
When testing some change I run some experiments to see how far from this goal we are in two configurations:
- stupid one (master 16 cores, 4 kubelets 2 cores each), 50 replication controllers, each with 1 pod
- more-reasonable-but-still-very-small-one (master 4 cores, 10 kubelets 1 core each), 200 replication controllers, each with 1 pod
I tested get API calls (pods and rc), and it turned out that get pods is WAY faster than get rc, and the difference grows significantly with the size of the cluster. It should also be clear that gets are getting slower with more running pods.

I'm sorry for the format, but GitHub does not allow pdfs:/ All results in seconds.

1 master (highcpu-16), 4 nodes (standard-2), 50 1-pod rc		
empty	get rc 50 pods   	get pod 50 pods
0.51	| 4.19 | 0.75
0.48	| 3.53 | 0.71
0.51 | 3.41 | 0.85
0.51 | 3.47 | 0.76
0.5 | 	3.43 | 0.72
0.49 | 4.01 | 0.73
0.5 | 	4.17 | 0.72
0.51 | 3.89 | 0.72
0.49 | 3.76 | 0.83
0.51 | 3.57 | 0.75
1 master (highcpu-4), 10 nodes (standard-1), 200 1-pod rc		
get rc emtpy	get rc 200 pods	get pod 200 pods
0.5   | 	1:13.41 | 0.91
0.52 | 	1:09.00 | 0.87
0.51 | 1:10.98 | 0.85
0.5 | 		 | 6.82
0.54 | 	 | 1.68
0.51 | 	 | 1.4
0.5 | 		 | 1.43
0.54 | 	 | 1.72
0.5 | 		 | 1.4
0.48 | 	 | 1.38
0.5 | 		 | 1.37

**Comment by lavalamp** [comment] 2015-02-20 19:33
Prashanth is working on moving replication controller status computation into replication controller, which is going to have the side effect of making list rc not be O(#pods * #rc) anymore.

**Comment by lavalamp** [comment] 2015-02-20 19:34
#4675 will add GOMAXPROCS to the scheduler, which I missed yesterday.

**Comment by lavalamp** [comment] 2015-02-25 18:53
After #4429 lands, the times for replication controllers should drop down to be about the same as the pod times.

**Comment by timothysc** [comment] 2015-03-11 12:38
I'll paste my comment in this thread then: 

When checking out the performance data on the apiserver under soak testing it appears that there is a fair amount of gc work going on:

20.43% kube-apiserver [.] runtime.MSpan_Sweep
3.91% kube-apiserver [.] findrunnable
3.05% kube-apiserver [.] runtime.mallocgc
2.29% kube-apiserver [.] scanblock
1.83% kube-apiserver [.] runtime.sweepone
1.75% kube-apiserver [.] runtime.atomicload 
1.73% kube-apiserver [.] runtime.xchg
1.54% kube-apiserver [.] runtime.duffcopy
1.47% kube-apiserver [.] flushptrbuf
1.22% kube-apiserver [.] runtime.memclr
1.19% kube-apiserver [.] runqgrab

Seems related to: golang/go#9265

go version go1.3.3 linux/amd64

**Comment by timothysc** [comment] 2015-03-11 13:10
More color: 

https://github.com/GoogleCloudPlatform/kubernetes/pull/4862 shows a rc fill time ~10 minutes.  

A part of this lag is apiserver, but there are other issues in the system that we're tracing.

**Comment by lavalamp** [comment] 2015-03-11 16:41
@timothysc what process are you using to generate those numbers?

I think taking boundpods out will drastically speed adding & removing pods to the system, I think there's a lot of contention for updating that.

**Comment by timothysc** [comment] 2015-03-11 16:46
@lavalamp - https://github.com/GoogleCloudPlatform/kubernetes/issues/5260 is the load we used for the numbers above.

**Comment by davidopp** [comment] 2015-03-11 21:07
What is "rc fill time"?

**Comment by bgrant0607** [comment] 2015-03-11 21:18
Get or list replicationcontrollers. List replicationcontrollers is currently O(#RCs*#pods).

**Comment by lavalamp** [comment] 2015-03-11 21:26
listing rc's should be better now that #4751 has merged. @gmarek is it easy for you to take those measurements again?

**Comment by gmarek** [comment] 2015-03-12 07:32
Yup. I'll do it today. Are we still playing with 1 hyperthread master, or have we moved to something truly multithreaded? Are we optimising for cpu time or wall time?

**Comment by gmarek** [comment] 2015-03-12 16:19
### 1 master (standard-1), 10 nodes (standard-1), 100 1-pod rc
	
empty get pod | get rc 100 pods | get pod 100 pods
----|-----|-----
1.01	| 22.35 | 31.48
1.01	| 21.27 | 5.68
0.51 | 19.88 | 25.41
1.11 | 10.48 | 25.56
1.15 | 12.71 | 15.74

So get's got much better. Sadly stops are REALLY bad. I guess they are still O(|rc| * |pods|).

### 1 master (standard-8), 10 nodes (standard-1), 100 1-pod rc
	
empty get pod | get rc 100 pods | get pod 100 pods
----|-----|-----
1.13	| 2.01 | 2.09
1.17	| 1.90 | 1.65
1.01 | 1.81 | 1.60
1.13 | 4.00 | 1.84
1.14 | 3.07 | 1.60

Stops are way better, but still pretty bad. It's still faster to turn down cluster and start it again, than wait for 100 rc to go down.

**Comment by erictune** [comment] 2015-03-12 16:58
are these single observations, a mean or 99%ile or what?

**Comment by brendandburns** [comment] 2015-03-12 17:06
As we do these observations, can we check in scripts so that others can repro. the results?

Thanks!
--brendan

**Comment by bgrant0607** [comment] 2015-03-12 17:20
Stop polls RCs:
https://github.com/GoogleCloudPlatform/kubernetes/blob/master/pkg/kubectl/stop.go#L81

Watch should work on RC status now.

**Comment by gmarek** [comment] 2015-03-12 17:30
Those are single observations. I can write 'scripts', but they are more or less just 'for's of kubectls inside time. Literally single line scripts, but if you believe it's good to have them wrapped in something I can write something more general.

**Comment by bprashanth** [comment] 2015-03-12 18:26
If there's a lot of noise (pods dying/coming up causing the controller to update its replica count) while you're trying the resize or delete (which are the 2 write operations in stop), the writes will conflict and trigger retries. The polling interval of these retries is 100ms. I'm curious to know how much of the stop time is just `delete --all` on the pods vs waiting for the rc to notice and take action.

We can probably get rid of the overhead of listing pods of an rc every time we modify it in watchcontrollers: 
https://github.com/GoogleCloudPlatform/kubernetes/blob/master/pkg/registry/etcd/etcd.go#L125, although I believe each watch event is translated in a goroutine so they shouldn't add up to O(rc*pods).

**Comment by gmarek** [comment] 2015-03-12 18:35
On the side: I recall that someone was writing load generator - what's the status of this? If it's still far away I can hack a script which will do some kind of load testing.

**Comment by gmarek** [comment] 2015-03-13 09:45
@bprashanth The fact that you depend on goroutines explains speedup when running master on 8 hypethread machine. IIUC we still haven't decided what our target configuration is, so I don't know how much parallelism we allow. I'll write a simple script to measure execution times of basic operations.

**Comment by gmarek** [comment] 2015-03-13 14:09
I created PR #5432 with extremely simple script. It's kind of manual as it outputs time results. I lost some time trying to make variables out of those results, but failed. Somehow I wasn't able to correctly redirect stderr to stdout for timed wait call and put it into a variable.

**Comment by satnam6502** [comment] 2015-03-24 15:35
How often were each of the tests run? I noticed (for tests that are dependent on etcd performance) that if you ran the same experiment again and again the results change as etcd accumulates state between invocations.

**Comment by gmarek** [comment] 2015-03-24 15:48
Is this a good thing, or a bad thing (i.e. what do you mean by 'accumulates states'). It depends on which ones you're asking about - roughly with few second pauses.

**Comment by satnam6502** [comment] 2015-03-24 15:53
If I get a moment (which I may not since I need to change my focus to
networking/plug-ins) I will try and describe in more detail what I observed
(based on state accumulating due to events so a subsequent run of the sam
experiment may have different results from an earlier invocation). However,
I am not sure and I would need time to carefully check what is going on.

**Comment by fgrzadkowski** [comment] 2015-05-20 16:48
Status update:
@wojtek-t and me are working on three changes to meet this goal:
* Faster DeepCopy
* Speed up etcd client library by using ugorji codec to unmarshal etcd responses
* Limit number of inflight "list pods" requests
According to our manual tests, with these changes we will meet 1s goal for all requests, except for listing pods, where 99tile is around few seconds.

**Comment by timothysc** [comment] 2015-05-20 17:20
@fgrzadkowski could we add a check of the /metric counters in e2e for regression detection?

**Comment by fgrzadkowski** [comment] 2015-05-20 18:15
Which counters do you mean? We already check latency in density tests.

**Comment by bprashanth** [comment] 2015-05-20 18:19
@timothysc don't think we should fail any other e2e because of latent requests. one can invoke the same method from any e2e to log slow ones (https://github.com/GoogleCloudPlatform/kubernetes/blob/master/test/e2e/util.go#L1006).

**Comment by timothysc** [comment] 2015-05-20 18:26
@bprashanth I'm ok with that for now.  We can setup prometheus alerts on queries.

**Comment by smarterclayton** [comment] 2015-05-20 23:37
Is it worth it to build an in memory pod cache fed by etcd directly at this point, or is limiting pod list requests sufficient?   We don't really gain anything by going to etcd for pods every few seconds, and we can reduce latency by the rtt to etcd for the same effective memory cost.

**Comment by davidopp** [comment] 2015-05-21 00:27
One additional idea we discussed is increasing the interval between relists, to something more like an hour rather than 5-8 minutes. I think it's fine to wait to see if the other changes are sufficient for our 1.0 goals, but this change may be necessary for our next scalability goal (1000 nodes or whatever). @lavalamp was OK with this change as long as this interval is configurable and all of the e2e tests set it low enough to force a relist during each test, so we are sure the functionality to do a level-based restore works.

**Comment by timothysc** [comment] 2015-05-21 13:24
We've option enabled list intervals on the tests we are interested in.  As mentioned in #8119 some lists are more expensive then others. 

/cc @rrati

**Comment by davidopp** [comment] 2015-05-27 21:53
> Status update:
> @wojtek-t and me are working on three changes to meet this goal:
>
> Faster DeepCopy
> Speed up etcd client library by using ugorji codec to unmarshal etcd responses
> Limit number of inflight "list pods" requests
>
> According to our manual tests, with these changes we will
> meet 1s goal for all requests, except for listing pods, where 99tile is around few seconds.

Can you give an update on these? It looks like first one is dependent on #8860/#8872, and last one is dependent on #6770? Is there a PR or issue for the second one?

**Comment by bprashanth** [comment] 2015-05-27 23:57
I can elaborate a little on the relist situation, since I'm currently working on it:
- Half of the relist problem (#6770) is addressed by https://github.com/GoogleCloudPlatform/kubernetes/pull/8574
- The second half is split between:
 * piping the timeout in the above pr as a command line arg to the apiserver, setting it really high in prod, and lower during tests. This will not completely solve the relist problem because of the following point.
 * https://github.com/GoogleCloudPlatform/kubernetes/issues/8700. This should give us control over how often we relist.
- We dropped the high latency limit to 5s and things aren't too bad (https://github.com/GoogleCloudPlatform/kubernetes/pull/8781)

**Comment by fgrzadkowski** [comment] 2015-05-28 13:05
@davidopp There is not PR or issue for the high CPU usage of etcd client library. Recently we've observed that despite CPU not being saturated we still have high latency (99tile up to 3-4s). It seems it's not CPU bound, so for now I've focused on understanding the reasons behind it.

**Comment by timothysc** [comment] 2015-05-28 16:54
at @fgrzadkowski we see the same thing.

**Comment by bprashanth** [comment] 2015-05-28 17:26
@fgrzadkowski we don't need to saturate cpu to starve the watch goroutines. If you have a process with n goutines all taking locks and one goroutine that *somtimes* gets an event on a channel, the go scheduler seems to de-prioritize the latter (no hard evidence, a conclusion drawn just from experimentation, see the test in the first comment on https://github.com/GoogleCloudPlatform/kubernetes/issues/8700).

**Comment by timothysc** [comment] 2015-05-28 21:02
> We don't really gain anything by going to etcd for pods every few seconds, and we can reduce latency by the rtt to etcd for the same effective memory cost.

+1 

I'm also a +1 to the interval shift.

**Comment by fgrzadkowski** [comment] 2015-05-29 07:59
@bprashanth I don't follow. I'm not talking about watch go routines, but regular http handlers for requests like list or get.

**Comment by fgrzadkowski** [comment] 2015-05-29 15:11
For the last few days @wojtek-t and me were trying to understand why observe non-saturated CPU but still have high request latency (around 3s for 99tile of list pods). We found few interesting facts.

The whole list requests consists of two parts:
* generate in-memory list object
* write response

Surprisingly the second part is longer than the first one and can take seconds! There three slow parts:
1. [encoding list to json](https://github.com/GoogleCloudPlatform/kubernetes/blob/master/pkg/apiserver/apiserver.go#L273)
2. [indenting json](https://github.com/GoogleCloudPlatform/kubernetes/blob/master/pkg/apiserver/apiserver.go#L280)
3. [writing json to ResponseWriter](https://github.com/GoogleCloudPlatform/kubernetes/blob/master/pkg/apiserver/apiserver.go#L287)

Each of those steps takes hundreds of milliseconds (up to seconds)

At the same time all of the long requests are coming from density test which lists all pods every 5 or 10 s, which generates up to 10M of data each. This also explains why the CPU is not saturated - each of those heavy requests is handled in one thread, which increases high percentiles, but doesn't load the CPU. Effectively they outweigh normal requests (i.e. those not listing _all_ pods). 


To fix 1. we can use ugorji codec.

To fix 2. we can just delete this code and do the indentation on the client side (i.e. in kubectl) as systems (e.g. kubelet) do not care about indentation. This also reduces maximum size of the response to ~6M.

We have no idea why 3. is so slow. Surprisingly it's the slowest out of three and can take seconds. Any suggestion how to debug this? Is it expected? As this is network related cc-ing @thockin

**Comment by smarterclayton** [comment] 2015-05-29 15:36
Do we need to tune the output buffer of the http response writer?  Do we have any wrappers around the response writer besides the HttpLog?

**Comment by timothysc** [comment] 2015-05-29 15:48
@filbranden We don't see pod listing as the long pole in our tests, do you have the metrics values that you are looking at?

**Comment by filbranden** [comment] 2015-05-29 16:48
@timothysc I'm not really looking at metrics values right now... Are you sure you mean me here?

**Comment by timothysc** [comment] 2015-05-29 16:50
sorry for some reason my autofill is hitting you.. @fgrzadkowski ^

**Comment by filbranden** [comment] 2015-05-29 16:52
No worries, I'm glad it's not me losing my mind :-)

**Comment by bprashanth** [comment] 2015-05-29 16:57
@fgrzadkowski I was talking about the reason we have concurrent lists when we don't saturate cpu, not the reason concurrent lists are slow.

**Comment by bgrant0607** [comment] 2015-05-30 03:24
Re. indentation in the client: Please see the discussion in the original issue -- #2243. Having the ability to pretty-print the json in a browser is useful. It doesn't need to be the default, but let's not lose that. Either a URL parameter or, preferably, using User-Agent to disable indentation.

**Comment by bgrant0607** [comment] 2015-05-30 03:27
Even for curl, indentation is useful, so if we want to disable it, we should do that in our client library.

**Comment by fgrzadkowski** [comment] 2015-06-02 11:47
Status update:
Current e2e scalability tests for 100 node cluster with 4 core master in majority of runs have latency metrics similar to this:
```
INFO: Top latency metric: {Verb:LIST Resource:pods Quantile:0.99 Latency:2.420198s}
INFO: Top latency metric: {Verb:LIST Resource:pods Quantile:0.9 Latency:2.266635s}
INFO: Top latency metric: {Verb:LIST Resource:pods Quantile:0.5 Latency:1.32378s}
INFO: Top latency metric: {Verb:POST Resource:pods Quantile:0.99 Latency:481.504ms}
INFO: Top latency metric: {Verb:POST Resource:bindings Quantile:0.99 Latency:414.718ms}
```
99tile of list of pods is almost never above 3s. Other requests are always below 1s.

I also manually tested this setup with 8 core master and metrics are below 1.5s.

Today I've also reenabled load tests (#8873), that @piosz wrote some time ago but has been disabled due to e2e instability. We will observe it closely and add expectation on latency metrics tomorrow.

**Comment by erictune** [comment] 2015-06-02 12:08
In this case, the 99%ile is less than 2x the median.  So thread load
balance is good.   Problem is that average case is too slow.

**Comment by erictune** [comment] 2015-06-02 12:10
Can you quantify "CPU not saturated"?

**Comment by fgrzadkowski** [comment] 2015-06-02 12:32
@erictune Most of the time it's around 80% utilization according to htop.

**Comment by smarterclayton** [comment] 2015-06-02 13:15
Can you grab GC metrics for length of time spent in GC and the collection rate?  I think it's GOGCVERBOSE=1 or similar (or you can trigger a pprof heap dump, which will show the collection time at the bottom in a comment).  We might be stuck waiting on the GC lock to be released for that 20%

**Comment by erictune** [comment] 2015-06-02 15:23
@fgrzadkowski wrote "For the last few days @wojtek-t and me were trying to understand why observe non-saturated CPU but still have high request latency (around 3s for 99tile of list pods)."

I think you are asking why the 99%ile is 2x higher than the mean, despite cpu not being 100%.
That seems consistent with what you might expect from queuing theory.

If you use:
http://www.supositorio.com/rcalc/rcalclite.htm

and then pick:
M/M/C

then set:
 - c = 8  (hyperthreads)
 - lambda = 6.5 (requests per second, assumed)
 - mu = 1 second of cpu time per request (implied by 80% utilization, curious what QPS you measured)

then you get:
 - 80% utilization (which you stated) 
 - 1.32 mean request latency (you stated 1.32s median LIST latency, mean would be useful) 
which is consistent with your results.

Then, if you set:
Probabilites (time in system <= Seconds) to 2.26 (which is your 90%ile latency),
the calculator predicts that 2.26 is your 82%ile latency. 
That seems pretty consistent too.

From this, I conclude that there is no need to invoke garbage collection or thread starvation to explain the tail latencies you are seeing.

**Comment by davidopp** [comment] 2015-06-02 17:19
@fgrzadkowski There was a request to also test on g1-small since that's the smallest master users might run in practice. There's no expectation that the performance will be good -- we just want to make sure it is not unusable.

**Comment by fgrzadkowski** [comment] 2015-06-03 13:53
@piosz have enabled load test which creates :
* 300 rc with 5 pods each
* 25 rc with 30 pods each
* 3 rc with 250 pods each
All creations are spread across all first 10 minuts. After that we randomly resize/delete/recreate all RCs.

Metrics from the first run:
```
INFO: Top latency metric: {Verb:POST Resource:pods Quantile:0.99 Latency:1.50546s}
INFO: Top latency metric: {Verb:LIST Resource:pods Quantile:0.99 Latency:1.360146s}
INFO: Top latency metric: {Verb:LIST Resource:pods Quantile:0.9 Latency:1.022879s}
INFO: Top latency metric: {Verb:PUT Resource:pods Quantile:0.99 Latency:481.39ms}
INFO: Top latency metric: {Verb:LIST Resource:pods Quantile:0.5 Latency:400.466ms}
```

**Comment by davidopp** [comment] 2015-06-03 16:35
Thanks for the update! Can you indicate which PRs related to this issue are still out for review (other than the CoreOS one), if any?

**Comment by fgrzadkowski** [comment] 2015-06-03 17:08
CoreOS one is the only PR in-flight. Number in my previous comment where taken from jenkins.

**Comment by davidopp** [comment] 2015-06-03 17:21
> CoreOS one is the only PR in-flight. Number in my previous comment where taken from jenkins.

Great, thanks! So the CoreOS PR will improve the above numbers further? (I assume "taken from jenkins" means only using what is already in the codebase -- but wanted to make sure I am understanding correctly.)

**Comment by fgrzadkowski** [comment] 2015-06-08 08:35
@davidopp Yes. I'll send a PR to update go-etcd client library version today.

**Comment by davidopp** [comment] 2015-06-08 17:03
@fgrzadkowski : Once you're confident we're meeting the goal described in the title of this issue, please move the issue to milestone "1.0-post". (We don't need to wait on the etcd PRs to merge if we're already meeting the goal.)

**Comment by fgrzadkowski** [comment] 2015-06-09 17:22
I enabled load test. Currently it plays the following scenario:
1. [0-10min] Run 300 RCs with 5 replicas each, 25 RCs with 30 pods each, 3 RC with 250 pods each
2. [10-13min] Scale all RCs randomly and list pods within RC
3. [13-16min] Repeat 2
4. [16-26min] Delete all RC
The test is configured in a way to keep ~5 creation/deletions per second, which IMO sounds reasonable. The test checks latency metrics after all of the phases to see if we meet 1s criteria. This means that some of requests were performed when the cluster was not full.

First run gave really good results (with 8 core master):

load test:
```
INFO: Top latency metric: {Verb:LIST Resource:pods Quantile:0.99 Latency:707.259ms}
INFO: Top latency metric: {Verb:LIST Resource:pods Quantile:0.9 Latency:382.948ms}
INFO: Top latency metric: {Verb:LIST Resource:pods Quantile:0.5 Latency:239.901ms}
INFO: Top latency metric: {Verb:DELETE Resource:pods Quantile:0.99 Latency:193.937ms}
INFO: Top latency metric: {Verb:PUT Resource:nodes Quantile:0.99 Latency:161.933ms}
```

density 30 pods per node:
```
INFO: Top latency metric: {Verb:LIST Resource:pods Quantile:0.99 Latency:1.60586s}
INFO: Top latency metric: {Verb:LIST Resource:pods Quantile:0.9 Latency:969.726ms}
INFO: Top latency metric: {Verb:PUT Resource:nodes Quantile:0.99 Latency:513.258ms}
INFO: Top latency metric: {Verb:POST Resource:pods Quantile:0.99 Latency:494.578ms}
INFO: Top latency metric: {Verb:PUT Resource:pods Quantile:0.99 Latency:491.616ms}
```

I think we should pay more attention to the load test which plays more realistic scenario.

Tomorrow I will set thresholds to 1s for load test and 2s for density test.

@davidopp @brendanburns @wojtek-t Assuming that next runs will give similar results I suggest we announce victory. Does that sound reasonable to you?

**Comment by bprashanth** [comment] 2015-06-09 17:33
@fgrzadkowski just fyi, with the load test we resize rcs quickly so there's a chance you will run into https://github.com/GoogleCloudPlatform/kubernetes/issues/9147

**Comment by davidopp** [comment] 2015-06-09 19:22
> Assuming that next runs will give similar results I suggest we announce victory. Does that sound reasonable to you?

Yes.

**Comment by fgrzadkowski** [comment] 2015-06-12 09:11
@davidopp Results with 4 core master:

Density with 3 pods per node
```
INFO: Top latency metric: {Verb:POST Resource:pods Quantile:0.99 Latency:589.097ms}
INFO: Top latency metric: {Verb:PUT Resource:pods Quantile:0.99 Latency:430.241ms}
INFO: Top latency metric: {Verb:LIST Resource:pods Quantile:0.99 Latency:372.226ms}
INFO: Top latency metric: {Verb:POST Resource:bindings Quantile:0.99 Latency:359.243ms}
INFO: Top latency metric: {Verb:LIST Resource:pods Quantile:0.9 Latency:302.09ms}
```

Density with 30 pods per node
```
INFO: WARNING Top latency metric: {Verb:LIST Resource:pods Quantile:0.99 Latency:2.656382s}
INFO: Top latency metric: {Verb:LIST Resource:pods Quantile:0.9 Latency:1.269396s}
INFO: Top latency metric: {Verb:LIST Resource:pods Quantile:0.5 Latency:854.817ms}
INFO: Top latency metric: {Verb:POST Resource:pods Quantile:0.99 Latency:481.31ms}
INFO: Top latency metric: {Verb:PUT Resource:nodes Quantile:0.99 Latency:370.808ms}
```

Load test
```
INFO: Top latency metric: {Verb:LIST Resource:pods Quantile:0.99 Latency:575.679ms}
INFO: Top latency metric: {Verb:LIST Resource:pods Quantile:0.9 Latency:372.226ms}
INFO: Top latency metric: {Verb:DELETE Resource:pods Quantile:0.99 Latency:190.719ms}
INFO: Top latency metric: {Verb:PUT Resource:nodes Quantile:0.99 Latency:152.142ms}
INFO: Top latency metric: {Verb:PUT Resource:replicationcontrollers Quantile:0.99 Latency:151.097ms}
```
NOTE: For load tests some requests were performed when we were creating/deleting RCs, so the cluster was not full (full spectrum from 0 to 30 pods per node)

@davidopp I suggest we keep 4 core master, but increase the threshold for density to 3 seconds. WDYT?

**Comment by davidopp** [comment] 2015-06-12 09:17
Sure, sounds good.

**Comment by davidopp** [comment] 2015-06-12 09:18
And thanks for collecting the additional data. That doesn't look too terrible vs. the 8-core data (i.e. it's not 2x the latency).

**Closed** 2015-06-12 10:54 UTC
Labels: area/performance, priority/P1, team/master

**Comment by davidopp** [comment] 2015-06-19 23:40
After merging #9862 the latency improved

https://github.com/GoogleCloudPlatform/kubernetes/pull/9862#issuecomment-113504442
says

Results from density test with 30 pods per node in 100 node cluster with n1-standard-4 master:
```
INFO: Top latency metric: {Verb:LIST Resource:pods Quantile:0.99 Latency:1.605515s}
INFO: Top latency metric: {Verb:LIST Resource:pods Quantile:0.9 Latency:1.270142s}
INFO: Top latency metric: {Verb:LIST Resource:pods Quantile:0.5 Latency:529.251ms}
INFO: Top latency metric: {Verb:POST Resource:bindings Quantile:0.99 Latency:444.361ms}
INFO: Top latency metric: {Verb:PUT Resource:pods Quantile:0.99 Latency:426.816ms}
```
This is way better (~25%) than the usual run for density test.
