### ISSUE TITLE
Error running crontab -l in master startup script

### ISSUE THREAD

**Issue by a-robinson** [GoogleCloudPlatform/kubernetes#10142] opened 2015-06-19 23:28 UTC
When bringing up a master at version 0.19.1, I see some error messages from attempting to run crontab -l, saying that they failed due to user root having no crontab. I doubt that it directly caused an issue with the master, but for what it's worth the apiserver on the same master VM is crash-looping.

```
Running state [/etc/monit/monit_watcher.sh] at time 22:31:54.780650
Jun 19 22:31:54 gke startupscript: [INFO    ] Executing state file.managed for /etc/monit/monit_watcher.sh
Jun 19 22:31:54 gke startupscript: [INFO    ] File changed:
Jun 19 22:31:54 gke startupscript: New file
Jun 19 22:31:54 gke startupscript: [INFO    ] Completed state [/etc/monit/monit_watcher.sh] at time 22:31:54.783427
Jun 19 22:31:54 gke startupscript: [INFO    ] Running state [crontab -l | { cat; echo "* * * * * /etc/monit/monit_watcher.sh 2>&1 | logger"; } | crontab -] at time 22:3
1:54.783576
Jun 19 22:31:54 gke startupscript: [INFO    ] Executing state cmd.run for crontab -l | { cat; echo "* * * * * /etc/monit/monit_watcher.sh 2>&1 | logger"; } | crontab -
Jun 19 22:31:54 gke startupscript: [INFO    ] Executing command 'crontab -l | grep "* * * * * /etc/monit/monit_watcher.sh 2>&1 | logger"' in directory '/'
Jun 19 22:31:54 gke startupscript: [ERROR   ] Command 'crontab -l | grep "* * * * * /etc/monit/monit_watcher.sh 2>&1 | logger"' failed with return code: 1
Jun 19 22:31:54 gke startupscript: [ERROR   ] output: no crontab for root
Jun 19 22:31:54 gke startupscript: [INFO    ] Executing command 'crontab -l | { cat; echo "* * * * * /etc/monit/monit_watcher.sh 2>&1 | logger"; } | crontab -' in direc
tory '/'
Jun 19 22:31:54 gke startupscript: [INFO    ] stderr: no crontab for root
Jun 19 22:31:54 gke startupscript: [INFO    ] {'pid': 2897, 'retcode': 0, 'stderr': 'no crontab for root', 'stdout': ''}
Jun 19 22:31:54 gke startupscript: [INFO    ] Completed state [crontab -l | { cat; echo "* * * * * /etc/monit/monit_watcher.sh 2>&1 | logger"; } | crontab -] at time 22
:31:54.855173
Jun 19 22:31:54 gke startupscript: [INFO    ] Running state [monit] at time 22:31:54.860691
Jun 19 22:31:54 gke startupscript: [INFO    ] Executing state service.running for monit
Jun 19 22:31:54 gke startupscript: [INFO    ] Executing command 'runlevel' in directory '/'
Jun 19 22:31:54 gke startupscript: [INFO    ] output: N 2
Jun 19 22:31:54 gke startupscript: [INFO    ] Executing command 'service monit status' in directory '/'
Jun 19 22:31:54 gke startupscript: [INFO    ] output: monit is running.
Jun 19 22:31:54 gke startupscript: [INFO    ] The service monit is already running
```

**Comment by dchen1107** [comment] 2015-06-20 07:24
This crontab created just for watching monit, and at the end, the monit is started properly. Also at this moment, both docker and kubelet are not started by monit. Which is very unfortunately and making our boot sequence even more complicated but messy. But this shouldn't related to kube-apiserver at all. Kube-apiserver is started by kubelet, and container is started by docker. The problem is that we reconfigured our network through master, which means we need to restart docker. Somehow on your failed node, I didn't see docker is restarted. I am closing the issue here. But I think we should clean up our boot sequence after 1.0.

**Closed by dchen1107** 2015-06-20 07:24 UTC
Labels: priority/P2, team/node

**Comment by zmerlynn** [comment] 2015-06-20 19:22
Why closed? It's low priority but it's still a bug. It's extremely noisy
and hard to separate from an actual bug on startup.
