### ISSUE TITLE
Deleting an empty namespace takes O(minutes)

### ISSUE THREAD

**Issue by thockin** [GoogleCloudPlatform/kubernetes#9197] opened 2015-06-03 17:48 UTC
I created an empty namespace, with nothing in it.  Success.  Then I deleted it.  Success.  Then I tried to recreate it - it still exists.  Then I tried to delete it again:

```
Error from server: Namespace "thtest" cannot be updated: Termination is in progress, waiting for [kubernetes]
```

This is pretty bad UX.  There's nothing in it, it should be gone immediately.  The error message is not useful, either.

@derekwaynecarr

**Comment by derekwaynecarr** [comment] 2015-06-03 18:29
@thockin - when you mark a namespace for deletion, it does not know nothing is in it.

the flow is as follows:

1. user marks a namespace for deletion (what you did)
2. user is blocked from creating any new content in that namespace via admission control
3. controller validates that there is nothing in the namespace, if it has stuff, it then begins terminating all the content in that namespace.  if the namespace has a lot of stuff, this can take some time.  pods with graceful termination will be a good example.
4. once controller validates the namespace is truly empty, it does a finalize action on the namespace and removes the 'kubernetes' token from the list of namespace finalizers.
5. then the namespace is deleted from the storage forever.

in the interim between steps 2 and 5, if you issue a 

kubectl get namespaces, you see 'Terminating' in the Status column instead of Active.

I am all for improving the error message, but I can't improve the time it takes to do 2-4.

See https://github.com/GoogleCloudPlatform/kubernetes/blob/master/docs/design/namespaces.md for more details, in particular Finalizers, and the Example of a third-party that wants to take part in namespace lifecycle (in this case OpenShift) to better understand the flow enforced.

Now with that background out of the way, I am up for a better error message.

How about:

```Namespace "<name>" is being deleted at this time```

?

**Comment by derekwaynecarr** [comment] 2015-06-03 18:31
With an empty namespace, steps 2-4 should be relatively quick, and I would anticipate a few seconds tops unless there is a qps issue.

**Comment by thockin** [comment] 2015-06-03 18:35
If it were a few seconds it would not be a problem.  I am seeing literally
minutes.  Since we got rid of async operations, this is far less obvious.
Should/Could we denote (at kubectl time) the difference between "success"
and "in progress" ?

**Comment by derekwaynecarr** [comment] 2015-06-03 19:58
Are you seeing minutes on an old release or from HEAD?  How many namespaces are in the system?  You said the namespace was empty, but are there other namespaces with tons of replication controllers?  We have density tests that test your scenario in question, see https://github.com/GoogleCloudPlatform/kubernetes/pull/8434

I think the work @smarterclayton is doing with graceful pod deletion is another place where success and in-progress will come into play at kubectl time.  We could distinguish by a 202 (accepted but not yet deleted) versus a 200 or 204 to handle that.

**Comment by thockin** [comment] 2015-06-03 20:12
This is from head as of yesterday or Monday.  Nothing else is really
happening in this cluster.

**Comment by derekwaynecarr** [comment] 2015-06-03 20:54
I will debug tonight/tomorrow to see if there is a regression somewhere, but the code in question has not changed, so if things have got slow for some reason, it's because of a side-effect of something else.

**Comment by derekwaynecarr** [comment] 2015-06-03 20:58
@thockin - I am getting a number of errors like this in my controller logs:

```
watch of *api.Namespace ended with: 401: The event in requested index is outdated and cleared (the requested history has been cleared [8979/8748]
```

This is new to me, so maybe that is related.  @lavalamp - I know we recently merged some changes to the reflector code here (cant find the PR in question), but could that be related?

**Comment by derekwaynecarr** [comment] 2015-06-03 21:03
@thockin - out of curiosity, was your cluster running a long time?  spinning up a fresh cluster now, but trying to think about possible variables here.

**Comment by lavalamp** [comment] 2015-06-03 21:13
#8915 is the only thing I'm aware of-- if that code path is triggering I would expect additional 401 errors. But it should recover and do a re-list immediately. @derekwaynecarr how much time elapses between those error messages?

**Comment by derekwaynecarr** [comment] 2015-06-03 21:15
@lavalamp - will report back with what I see from HEAD when I test, I had brought my cluster down to start fresh.  Thanks for the referenced PR.

**Comment by bprashanth** [comment] 2015-06-03 21:23
@derekwaynecarr that's some-what expected since we bumped up the watch timeout, all you'll see is the etcd watch window exiring, sometimes every minute (because of node status updates). I suspect that's a red herring in this case though. see https://github.com/GoogleCloudPlatform/kubernetes/issues/8700 for context.

**Comment by lavalamp** [comment] 2015-06-03 21:30
@bprashanth -- increasing the watch timeout should *not* increase the number of 401 errors, if etcd works as expected. You should only be able to get a 401 error when the time between list and initiation of the watch is too long. If your watch is successful at first, you shouldn't be able to get a 401 error from that watch afterwards.

**Comment by bprashanth** [comment] 2015-06-03 21:36
hmm, i think go-etcd client does a new watch per notification. So even if you think you've initiated a watch (from the reflector), you're re-initiating a watch every time from some 500 goroutines that all share 4 cores in the apiserver. Agreed that increasing the timeout should not increase the 401's, just that you will now see 401s when previously you might not have, and the number of 401's really depends on what else is hitting the master.

**Comment by derekwaynecarr** [comment] 2015-06-03 23:30
I spun up a cluster on GCE and do see a longer than expected time to delete a namespace.

I need to debug further to see what is causing the regression in performance here as it used to be MUCH faster.

**Comment by bprashanth** [comment] 2015-06-03 23:32
maybe unrelated but i've observed deleting a ns with O(100) events takes ~10m

**Comment by derekwaynecarr** [comment] 2015-06-03 23:37
General performance would improve with https://github.com/GoogleCloudPlatform/kubernetes/pull/7372 , but that was gated first on  understanding what was going to happen with graceful deletion of pods.  I don't think the namespace had a large number of events given that I had just created it.   It may be good to pull in #7372 for everything but pods

**Comment by derekwaynecarr** [comment] 2015-06-03 23:48
the namespace_controller is using not using the framework. informer stuff, maybe something there was changed and got missed in those moves.

**Comment by derekwaynecarr** [comment] 2015-06-03 23:58
well, i am using it, but maybe i am using it wrong

**Comment by derekwaynecarr** [comment] 2015-06-04 01:24
A potential theory:
https://github.com/GoogleCloudPlatform/kubernetes/blob/master/pkg/namespace/namespace_controller.go#L59

if this throws an error, we ignore until the next full re-list period.  need to add more logging to see if that is the actual cause, and if we should be retrying immediately instead of waiting.

**Comment by derekwaynecarr** [comment] 2015-06-04 01:44
For what its worth, namespace deletion in OpenShift (which is doing even more than what is being done in Kubernetes is super fast, like less than a second for me), and we run more controllers so something has changed...

**Comment by derekwaynecarr** [comment] 2015-06-04 01:57
It appears to be an error is getting returned when deleteServiceAccounts, and then we wait for next full resync period to try again and actually delete (when things then pass).  Working with @liggitt on the reason, but that now makes some more sense.

**Comment by liggitt** [comment] 2015-06-04 02:02
tokencontroller deletes a service account's tokens when it the serviceaccount gets deleted. namespace finalizer should probably broadly tolerate NotFound errors when iterating and deleting

**Comment by derekwaynecarr** [comment] 2015-06-04 02:03
tokens_controller and namespace_controller are racing when deleting secrets.  fix is to update the namespace controller to not care when it gets back an item not found error on a delete call.  will send a pr.  this would all be much simpler code when / if we had collection level delete in #7372

**Comment by thockin** [comment] 2015-06-04 04:53
Thanks for digging in.  I will spin up a fresh cluster tomorrow and see if
I can repro.

**Closed** 2015-06-04 05:18 UTC
Labels: priority/P1, team/UX
