### ISSUE TITLE
apiserver under load. 

### ISSUE THREAD

**Issue by timothysc** [GoogleCloudPlatform/kubernetes#5263] opened 2015-03-10 21:08 UTC
When checking out the performance data on the apiserver under soak testing it appears that there is a fair amount of gc work going on: 

20.43%  kube-apiserver  [.] runtime.MSpan_Sweep
3.91%  kube-apiserver  [.] findrunnable
3.05%  kube-apiserver  [.] runtime.mallocgc
2.29%  kube-apiserver  [.] scanblock
1.83%  kube-apiserver  [.] runtime.sweepone
1.75%  kube-apiserver  [.] runtime.atomicload 
1.73%  kube-apiserver  [.] runtime.xchg
1.54%  kube-apiserver  [.] runtime.duffcopy
1.47%  kube-apiserver  [.] flushptrbuf
1.22%  kube-apiserver  [.] runtime.memclr
1.19%  kube-apiserver  [.] runqgrab  

Seems related to: https://github.com/golang/go/issues/9265

go version go1.3.3 linux/amd64

**Comment by goltermann** [comment] 2015-03-10 23:26
Dupe of #4521 (this is data that helps solve that one)

**Closed by goltermann** 2015-03-10 23:26 UTC
Labels: priority/P3, team/master
