### ISSUE TITLE
#7743 introduced weird glibc dep

### ISSUE THREAD

**Issue by roberthbailey** [GoogleCloudPlatform/kubernetes#7805] opened 2015-05-05 22:12 UTC
The current GCE run started at 1:55pm and is still spinning unable to launch a cluster. GKE-CI has been failing since 1:40pm.

**Comment by roberthbailey** [comment] 2015-05-05 22:14
@zmerlynn is looking into the root cause. Based on the GKE-CI failure, the candidate changes are:

```
security context initial implementation - squash (Commit 982bf19c205045259cf778ce4fe99df849daa20d)
update swagger (Commit 5e5b904e8c462b2ccf0660a6f0fa7c4d45cd4252)
Inject dependencies to rkt (Commit 5d0e5d7d6177bf7883896640abea8531b3f4400e)
Add rkt runtime to Kubelet init (Commit 22297d316a5964c9b154c0a6f172507802a732ad)
```

**Comment by zmerlynn** [comment] 2015-05-05 22:33
The root cause was the injection of a GLIBC_2.14 dep in `kubelet`:

```
zml@zml:~/kubernetes$ ldd -v _output/release-stage/server/linux-amd64/kubernetes/server/bin/kubelet
        linux-vdso.so.1 =>  (0x00007ffc6538a000)
        libpthread.so.0 => /lib/x86_64-linux-gnu/libpthread.so.0 (0x00007fd23420e000)
        libc.so.6 => /lib/x86_64-linux-gnu/libc.so.6 (0x00007fd233e49000)
        /lib64/ld-linux-x86-64.so.2 (0x00007fd234454000)

        Version information:
        _output/release-stage/server/linux-amd64/kubernetes/server/bin/kubelet:
                libpthread.so.0 (GLIBC_2.2.5) => /lib/x86_64-linux-gnu/libpthread.so.0
                libc.so.6 (GLIBC_2.14) => /lib/x86_64-linux-gnu/libc.so.6
                libc.so.6 (GLIBC_2.2.5) => /lib/x86_64-linux-gnu/libc.so.6
        /lib/x86_64-linux-gnu/libpthread.so.0:
                ld-linux-x86-64.so.2 (GLIBC_2.2.5) => /lib64/ld-linux-x86-64.so.2
                ld-linux-x86-64.so.2 (GLIBC_2.3) => /lib64/ld-linux-x86-64.so.2
                ld-linux-x86-64.so.2 (GLIBC_PRIVATE) => /lib64/ld-linux-x86-64.so.2
                libc.so.6 (GLIBC_2.14) => /lib/x86_64-linux-gnu/libc.so.6
                libc.so.6 (GLIBC_2.3.2) => /lib/x86_64-linux-gnu/libc.so.6
                libc.so.6 (GLIBC_PRIVATE) => /lib/x86_64-linux-gnu/libc.so.6
                libc.so.6 (GLIBC_2.2.5) => /lib/x86_64-linux-gnu/libc.so.6
        /lib/x86_64-linux-gnu/libc.so.6:
                ld-linux-x86-64.so.2 (GLIBC_2.3) => /lib64/ld-linux-x86-64.so.2
                ld-linux-x86-64.so.2 (GLIBC_PRIVATE) => /lib64/ld-linux-x86-64.so.2
```

Our containervm image only ships with 2.13:
```
Package: libc6
Source: eglibc
Version: 2.13-38+deb7u6
```

So kubelet didn't come up at all on GCE-Debian.

**Comment by zmerlynn** [comment] 2015-05-05 22:36
#7792 added the dep, and I reverted it in #7809

**Comment by smarterclayton** [comment] 2015-05-05 22:46
What's the process for updating the containervm image?  Is there one?

**Comment by zmerlynn** [comment] 2015-05-05 22:48
There is. I'm actually in the middle of updating it right now, but at the tail. Updating libc, though... hmm. I can look into it.

**Comment by smarterclayton** [comment] 2015-05-05 22:49
Trying to find where #7343 included an updated libc.

**Comment by zmerlynn** [comment] 2015-05-05 22:49
And I may be wrong. My build is confused.

**Comment by zmerlynn** [comment] 2015-05-05 22:52
Dammit. There's something weird going on. I may have gotten them backwards, sorry.

**Comment by zmerlynn** [comment] 2015-05-05 23:09
Yeah, mea culpa. The culprit was #7743. Reassigning this to @vmarmol to figure out next steps.

**Comment by dchen1107** [comment] 2015-05-05 23:35
My hacky way to fix such issue for my rkt demo is building kublet statically. :-(

**Comment by dchen1107** [comment] 2015-05-05 23:47
building kubelet statically has one benefit since we are working toward running kubelet as a docker containe, statically linking release kubelet image not based on large base image, such as ubuntu, like what we did in #7797

**Comment by pmorie** [comment] 2015-05-06 00:27
@dchen1107 I'm super-curious about what you had to do to get the kubelet built statically.  I want to have a scratch image w/ just kubelet and nsenter eventually.

**Comment by pmorie** [comment] 2015-05-06 01:07
I don't think building the kubelet statically is a hack, unless I'm missing something.

**Comment by vmarmol** [comment] 2015-05-06 18:23
cAdvisor has issues when built statically after Go 1.4 since we'd require running gcc which we don't want to do.

Closing in favor of #7850.

**Closed** 2015-05-06 18:24 UTC
Labels: priority/P1, team/node

**Comment by dchen1107** [comment] 2015-05-06 19:55
@pmorie, Yes I built kubelet statically, but sacrificed cAdvisor functionalities. Since my goal is demonstrating k8s + rkt integration on GCE, and I didn't have time to look into cAdvisor issues then. This is one cons we have to pay for integrate cAdvisor library into Kubelet, but there are a lot of pros too. 

@vmarmol What are the exact reasons we don't want to running gcc?

**Comment by pmorie** [comment] 2015-05-06 20:10
@vmarmol 

> cAdvisor has issues when built statically after Go 1.4 since we'd require running gcc which we don't want to do.

What requires gcc?

**Comment by vmarmol** [comment] 2015-05-06 20:57
@pmorie cAdvisor uses C for some queries to the kernel. We may be able to move them to raw syscalls with some work. I'd just want to make sure we need to :)

@dchen1107 because we won't be able to cross-compile. To cross-compile we'd need to specify a compiler in the other architectures and OSes we target.
