### ISSUE TITLE
PD tests flaky on `release-1.0` branch

### ISSUE THREAD

**Issue by zmerlynn** [GoogleCloudPlatform/kubernetes#12171] opened 2015-08-03 22:32 UTC
@ihmccreery was working on release validation for GKE and noticed that `Pod Disks should schedule a pod w/ a readonly PD on two hosts, then remove both` is flaky on the GKE tests. I just confirmed that it's not just there, it's actually flaky on the `release-1.0` branch as well, so #11758 isn't fixed on the branch. I did verify that the cherry-pick was present (#12051), so not sure what other factor is missing.

cc @saad-ali @thockin 

This is noisy enough on the release branch that we (GKE) may just skip over v1.0.2, sadly.

**Comment by saad-ali** [comment] 2015-08-03 22:38
I'll take a look at what's going on here.

**Comment by zmerlynn** [comment] 2015-08-03 22:38
go/k8s-test/job/kubernetes-e2e-gce-release/448/testReport/(root)/Kubernetes%20e2e%20suite/Pod_Disks_should_schedule_a_pod_w__a_readonly_PD_on_two_hosts__then_remove_both_/history/

for test history

**Comment by saad-ali** [comment] 2015-08-03 22:54
Ok, this issue is a different issue--it was tracked by #11302 and fixed in PR #11873 which was not cherry picked into 1.0.2 hence the test still flaking in E2E-GCE-release.

The fix is simply a test fix so it is not critical to merge it into the release branch (it only de-flakes the test, no code/BL changes).

If the noise is bothersome I can cherry pick #11873 in, let me know. Regardless I think #12051 fixes a critical bug that GKE should pick up ASAP.

**Comment by saad-ali** [comment] 2015-08-03 22:56
Looking in to run #433

**Comment by saad-ali** [comment] 2015-08-03 23:04
Confirmed 432, 429, and earlier failures of `Pod Disks should schedule a pod w/ a readonly PD on two hosts, then remove both` are #11302 (fixed in PR #11873)

**Comment by zmerlynn** [comment] 2015-08-03 23:11
Please cherry-pick #11873. The release branch needs a very strong :+1: :-1: signal, and it's just as important to keep the test fixes flowing.

We'll make a separate decision on 1.0.2 knowing that (or pound out a 1.0.3, since there's at least one other PR we want.)

**Comment by saad-ali** [comment] 2015-08-03 23:14
Sounds good. Working on a cherry pick for #11873

**Comment by saad-ali** [comment] 2015-08-05 20:11
`Pod Disks should schedule a pod w/ a readonly PD on two hosts, then remove both` has been green in `kubernetes-e2e-gce-release` since #12178 was merged 2 days ago. Closing this issue.

**Closed by saad-ali** 2015-08-05 20:11 UTC
Labels: priority/P1, team/testing
