### ISSUE TITLE
Convert all API documentation and examples to v1beta3

### ISSUE THREAD

**Issue by abonas** [GoogleCloudPlatform/kubernetes#3671] opened 2015-01-21 12:27 UTC
similar to guestbook intended for v1, v3 also needs example json for all entity types

**Comment by bgrant0607** [comment] 2015-01-21 15:05
Known issue.

Ref #1519

/cc @eparis

**Comment by timothysc** [comment] 2015-02-19 17:27
I think we may have unwittingly bumped into an ENV injection issue when submitting the old examples that are using v1beta1.  We see the e2e tests passing but they explicitly set the namespace.  

Have folks checked if previous examples submitted via the old api indeed are put into the "default" namespace,  and are resolved by the kubelet?  Currently it looks like there are no vars injected and my suspicion from looking at the code is that there is no default namespace.  

re: 'func (kl *Kubelet) getServiceEnvVarMap(ns string) (map[string]string, error)'

**Comment by ArtfulCoder** [comment] 2015-03-04 18:21
I can convert redis example to v1beta3

**Comment by bgrant0607** [comment] 2015-03-04 18:31
@sub-mod: Which examples are you working on? We're starting on this as well.

Done: cassandra, guestbook-go, guestbook, hazelcast, liveness

**Comment by lavalamp** [comment] 2015-03-04 19:06
I will do the update-demo.

**Comment by dchen1107** [comment] 2015-03-04 19:19
I am starting with  example/gce-pd

**Comment by sub-mod** [comment] 2015-03-04 19:42
@bgrant0607 
I am working on the ones in addons 
under examples folder :cassandra, guestbook-go, guestbook, hazelcast, liveness

**Comment by bgrant0607** [comment] 2015-03-04 20:21
Thanks to @lavalamp, we now have a conversion utility (which needs documentation!): #5041.

**Comment by dchen1107** [comment] 2015-03-04 21:05
Converting examples/limitrange now

**Comment by dchen1107** [comment] 2015-03-04 21:30
doing examples/resourcequota/resource-quota.json

**Comment by dchen1107** [comment] 2015-03-04 22:30
Doing examples/rethinkdb now

**Comment by bgrant0607** [comment] 2015-03-04 22:33
If you are using the conversion tool, please prune the set of fields to those relevant to the example. In particular, no config should contain status.

**Comment by bgrant0607** [comment] 2015-03-14 00:42
We'll need to cover v1beta3 in e2e, also. See #5475.

**Comment by bgrant0607** [comment] 2015-03-23 19:59
docs/volumes.md needs to be converted also (#5795)

**Comment by wojtek-t** [comment] 2015-04-10 12:53
This is duplicate of #5475

**Comment by bgrant0607** [comment] 2015-04-10 14:19
@wojtek-t You meant #6584.

**Closed by bgrant0607** 2015-04-10 14:19 UTC
Labels: api/cluster, area/documentation, area/usability, priority/P1, team/UX

**Comment by wojtek-t** [comment] 2015-04-10 14:21
@bgrant0607 Yes - sorry. I copied the wrong number.
