### ISSUE TITLE
Services with the same name in different namespaces cause kube-proxy to bug out

### ISSUE THREAD

**Issue by mikesimons** [GoogleCloudPlatform/kubernetes#4695] opened 2015-02-21 11:28 UTC
Should it be possible to have services with the same name in different namespaces? Nothing prevents it and I suspect that it should be possible but there are assumptions in code that cause this not to function correctly.

Here are some failing tests: https://github.com/mikesimons/kubernetes/compare/proxy_namespace_clash

And here is what lead me to investigate:
```
Feb 21 07:41:19 localhost.localdomain kube-proxy[19433]: I0221 07:41:19.703463   19433 config.go:233] Setting services {Services:[{TypeMeta:{Kind: APIVersion:} ObjectMeta:{Name:kubernetes Namespace:default SelfLink: UID:4575a863-b928-11e4-bc1b-080027205d4b ResourceVersion: CreationTimestamp:2015-02-20 17:45:34 +0000 UTC Labels:map[provider:kubernetes component:apiserver] Annotations:map[]} Spec:{Port:443 Protocol:TCP Selector:map[] PortalIP:119.9.53.150 ProxyPort:0 CreateExternalLoadBalancer:false PublicIPs:[] ContainerPort:{Kind:0 IntVal:0 StrVal:} SessionAffinity:None} Status:{}} {TypeMeta:{Kind: APIVersion:} ObjectMeta:{Name:kubernetes-ro Namespace:default SelfLink: UID:458766c2-b928-11e4-bc1b-080027205d4b ResourceVersion: CreationTimestamp:2015-02-20 17:45:34 +0000 UTC Labels:map[component:apiserver provider:kubernetes] Annotations:map[]} Spec:{Port:80 Protocol:TCP Selector:map[] PortalIP:119.9.9.239 ProxyPort:0 CreateExternalLoadBalancer:false PublicIPs:[] ContainerPort:{Kind:0 IntVal:0 StrVal:} SessionAffinity:None} Status:{}} {TypeMeta:{Kind: APIVersion:} ObjectMeta:{Name:syslog Namespace:default SelfLink: UID:4bc04140-b929-11e4-bc1b-080027205d4b ResourceVersion: CreationTimestamp:2015-02-20 17:52:54 +0000 UTC Labels:map[] Annotations:map[]} Spec:{Port:514 Protocol:UDP Selector:map[name:elk] PortalIP:119.9.206.11 ProxyPort:0 CreateExternalLoadBalancer:false PublicIPs:[] ContainerPort:{Kind:0 IntVal:514 StrVal:} SessionAffinity:None} Status:{}} {TypeMeta:{Kind: APIVersion:} ObjectMeta:{Name:redis Namespace:project1 SelfLink: UID:d1e4b42e-b99c-11e4-a0c0-080027205d4b ResourceVersion: CreationTimestamp:2015-02-21 07:39:51 +0000 UTC Labels:map[role:service name:read] Annotations:map[]} Spec:{Port:6379 Protocol:TCP Selector:map[name:redis] PortalIP:119.9.236.240 ProxyPort:0 CreateExternalLoadBalancer:false PublicIPs:[] ContainerPort:{Kind:0 IntVal:0 StrVal:} SessionAffinity:None} Status:{}} {TypeMeta:{Kind: APIVersion:} ObjectMeta:{Name:redis Namespace:project2 SelfLink: UID:f76c4de3-b99c-11e4-a0c0-080027205d4b ResourceVersion: CreationTimestamp:2015-02-21 07:40:54 +0000 UTC Labels:map[name:read role:service] Annotations:map[]} Spec:{Port:6379 Protocol:TCP Selector:map[name:redis] PortalIP:119.9.235.183 ProxyPort:0 CreateExternalLoadBalancer:false PublicIPs:[] ContainerPort:{Kind:0 IntVal:0 StrVal:} SessionAffinity:None} Status:{}}] Op:0}

Feb 21 07:41:19 localhost.localdomain kube-proxy[19433]: I0221 07:41:19.703801   19433 config.go:138] Setting endpoints {Endpoints:[{TypeMeta:{Kind: APIVersion:} ObjectMeta:{Name:kubernetes Namespace:default SelfLink: UID: ResourceVersion: CreationTimestamp:0001-01-01 00:00:00 +0000 UTC Labels:map[] Annotations:map[]} Endpoints:[10.0.2.15:8080]} {TypeMeta:{Kind: APIVersion:} ObjectMeta:{Name:kubernetes-ro Namespace:default SelfLink: UID: ResourceVersion: CreationTimestamp:0001-01-01 00:00:00 +0000 UTC Labels:map[] Annotations:map[]} Endpoints:[10.0.2.15:7080]} {TypeMeta:{Kind: APIVersion:} ObjectMeta:{Name:syslog Namespace:default SelfLink:/api/v1beta1/endpoints/syslog?namespace=default UID:4c837d1f-b929-11e4-bc1b-080027205d4b ResourceVersion:12 CreationTimestamp:2015-02-20 17:52:55 +0000 UTC Labels:map[] Annotations:map[]} Endpoints:[172.17.0.3:514]} {TypeMeta:{Kind: APIVersion:} ObjectMeta:{Name:redis Namespace:project1 SelfLink: UID:d24c9595-b99c-11e4-a0c0-080027205d4b ResourceVersion: CreationTimestamp:2015-02-21 07:39:52 +0000 UTC Labels:map[] Annotations:map[]} Endpoints:[]} {TypeMeta:{Kind: APIVersion:} ObjectMeta:{Name:redis Namespace:project2 SelfLink: UID:fc253202-b99c-11e4-a0c0-080027205d4b ResourceVersion: CreationTimestamp:2015-02-21 07:41:02 +0000 UTC Labels:map[] Annotations:map[]} Endpoints:[]}] Op:0}

Feb 21 07:41:19 localhost.localdomain kube-proxy[19433]: I0221 07:41:19.703923   19433 proxier.go:459] Received update notice: [{TypeMeta:{Kind: APIVersion:} ObjectMeta:{Name:kubernetes-ro Namespace:default SelfLink: UID:458766c2-b928-11e4-bc1b-080027205d4b ResourceVersion: CreationTimestamp:2015-02-20 17:45:34 +0000 UTC Labels:map[component:apiserver provider:kubernetes] Annotations:map[]} Spec:{Port:80 Protocol:TCP Selector:map[] PortalIP:119.9.9.239 ProxyPort:0 CreateExternalLoadBalancer:false PublicIPs:[] ContainerPort:{Kind:0 IntVal:0 StrVal:} SessionAffinity:None} Status:{}} {TypeMeta:{Kind: APIVersion:} ObjectMeta:{Name:syslog Namespace:default SelfLink: UID:4bc04140-b929-11e4-bc1b-080027205d4b ResourceVersion: CreationTimestamp:2015-02-20 17:52:54 +0000 UTC Labels:map[] Annotations:map[]} Spec:{Port:514 Protocol:UDP Selector:map[name:elk] PortalIP:119.9.206.11 ProxyPort:0 CreateExternalLoadBalancer:false PublicIPs:[] ContainerPort:{Kind:0 IntVal:514 StrVal:} SessionAffinity:None} Status:{}} {TypeMeta:{Kind: APIVersion:} ObjectMeta:{Name:redis Namespace:project2 SelfLink: UID:f76c4de3-b99c-11e4-a0c0-080027205d4b ResourceVersion: CreationTimestamp:2015-02-21 07:40:54 +0000 UTC Labels:map[name:read role:service] Annotations:map[]} Spec:{Port:6379 Protocol:TCP Selector:map[name:redis] PortalIP:119.9.235.183 ProxyPort:0 CreateExternalLoadBalancer:false PublicIPs:[] ContainerPort:{Kind:0 IntVal:0 StrVal:} SessionAffinity:None} Status:{}} {TypeMeta:{Kind: APIVersion:} ObjectMeta:{Name:kubernetes Namespace:default SelfLink: UID:4575a863-b928-11e4-bc1b-080027205d4b ResourceVersion: CreationTimestamp:2015-02-20 17:45:34 +0000 UTC Labels:map[provider:kubernetes component:apiserver] Annotations:map[]} Spec:{Port:443 Protocol:TCP Selector:map[] PortalIP:119.9.53.150 ProxyPort:0 CreateExternalLoadBalancer:false PublicIPs:[] ContainerPort:{Kind:0 IntVal:0 StrVal:} SessionAffinity:None} Status:{}}]

Feb 21 07:41:19 localhost.localdomain kube-proxy[19433]: I0221 07:41:19.704086   19433 proxier.go:470] Something changed for service "redis": stopping it
Feb 21 07:41:19 localhost.localdomain kube-proxy[19433]: I0221 07:41:19.726654   19433 iptables.go:186] running iptables -C [KUBE-PORTALS-CONTAINER -t nat -m comment --comment redis -p tcp -m tcp -d 119.9.236.240/32 --dport 6379 -j REDIRECT --to-ports 55814]
Feb 21 07:41:19 localhost.localdomain kube-proxy[19433]: I0221 07:41:19.729142   19433 iptables.go:186] running iptables -D [KUBE-PORTALS-CONTAINER -t nat -m comment --comment redis -p tcp -m tcp -d 119.9.236.240/32 --dport 6379 -j REDIRECT --to-ports 55814]
Feb 21 07:41:19 localhost.localdomain kube-proxy[19433]: I0221 07:41:19.733688   19433 iptables.go:186] running iptables -C [KUBE-PORTALS-HOST -t nat -m comment --comment redis -p tcp -m tcp -d 119.9.236.240/32 --dport 6379 -j DNAT --to-destination 10.0.2.15:55814]
Feb 21 07:41:19 localhost.localdomain kube-proxy[19433]: I0221 07:41:19.736540   19433 iptables.go:186] running iptables -D [KUBE-PORTALS-HOST -t nat -m comment --comment redis -p tcp -m tcp -d 119.9.236.240/32 --dport 6379 -j DNAT --to-destination 10.0.2.15:55814]
Feb 21 07:41:19 localhost.localdomain kube-proxy[19433]: I0221 07:41:19.739764   19433 proxier.go:575] Closed iptables portals for service "redis"
Feb 21 07:41:19 localhost.localdomain kube-proxy[19433]: I0221 07:41:19.739798   19433 proxier.go:480] Adding new service "redis" at 119.9.235.183:6379/TCP (local :0)
Feb 21 07:41:19 localhost.localdomain kube-proxy[19433]: I0221 07:41:19.739880   19433 proxier.go:443] Proxying for service "redis" on TCP port 37841
Feb 21 07:41:19 localhost.localdomain kube-proxy[19433]: I0221 07:41:19.739890   19433 proxier.go:492] info: &{portalIP:[0 0 0 0 0 0 0 0 0 0 255 255 119 9 235 183] portalPort:6379 protocol:TCP proxyPort:37841 socket:0xc20810c4a0 timeout:60000000000 publicIP:[] sessionAffinityType:None stickyMaxAgeMinutes:180}
Feb 21 07:41:19 localhost.localdomain kube-proxy[19433]: E0221 07:41:19.742221   19433 proxier.go:103] Accept failed: accept tcp [::]:55814: use of closed network connection
Feb 21 07:41:19 localhost.localdomain kube-proxy[19433]: E0221 07:41:19.742248   19433 proxier.go:103] Accept failed: use of closed network connection
Feb 21 07:41:19 localhost.localdomain kube-proxy[19433]: E0221 07:41:19.742257   19433 proxier.go:103] Accept failed: use of closed network connection
Feb 21 07:41:19 localhost.localdomain kube-proxy[19433]: E0221 07:41:19.742261   19433 proxier.go:103] Accept failed: use of closed network connection
Feb 21 07:41:19 localhost.localdomain kube-proxy[19433]: E0221 07:41:19.742265   19433 proxier.go:103] Accept failed: use of closed network connection
Feb 21 07:41:19 localhost.localdomain kube-proxy[19433]: E0221 07:41:19.742269   19433 proxier.go:103] Accept failed: use of closed network connection
```

The `Accept failed: use of closed network connection` is spat out indefinitely at a very high rate. All services cease to function (but timeout rather than refuse connection).

The thing of note in the logs is that in the "Setting services" message both redis instances are present where-as in the "Recieved update" message, only the project2 instance is present.

I believe that this is due to the fact that several places in pkg/proxy/config/config.go create maps keyed on service name only. Here is an example https://github.com/mikesimons/kubernetes/blob/master/pkg/proxy/config/config.go#L214

Assuming I am correct, what would be the best way to fix this? It doesn't look like the keys of the maps are used anywhere so does this need to be a map at all?

**Comment by zmerlynn** [comment] 2015-02-21 14:17
This is a dupe of #4288.

**Closed** 2015-02-21 14:17 UTC

**Comment by mikesimons** [comment] 2015-02-21 17:38
Ah, apologies @zmerlynn. I searched for the errors but did not spy that one (nor the several others referenced) :(
