### ISSUE TITLE
portforward unittest error

### ISSUE THREAD

**Issue by ddysher** [GoogleCloudPlatform/kubernetes#7173] opened 2015-04-22 16:48 UTC
```
I0422 09:58:40.823928   32558 portforward.go:216] Forwarding from 12345 -> 12345
I0422 09:58:40.824093   32558 portforward.go:216] Forwarding from 12345 -> 12345
I0422 09:58:40.824159   32558 portforward.go:216] Forwarding from 12345 -> 12345
E0422 09:58:40.824280   32558 portforward.go:205] Unable to create listener: Error listen tcp6: no suitable address found
E0422 09:58:40.824346   32558 portforward.go:205] Unable to create listener: Error listen tcp4 [::1]:12345: non-IPv4 address
E0422 09:58:40.824397   32558 portforward.go:205] Unable to create listener: Error listen tcp6 127.0.0.1:12345: bind: invalid argument
--- FAIL: TestGetListener (0.00 seconds)
	portforward_test.go:275: Asked a tcp4 forward for: localhost:12345, got listener 127.0.0.1:12345, expected: 12345
	portforward_test.go:275: Asked a tcp4 forward for: 127.0.0.1:12345, got listener 127.0.0.1:12345, expected: 12345
	portforward_test.go:275: Asked a tcp6 forward for: [::1]:12345, got listener ::1:12345, expected: 12345
	portforward_test.go:262: Test case #3 failed: Data {localhost tcp6 false ::1} an error has been raised(false) where it should not (or reciprocally): listen tcp6: no suitable address found
I0422 09:58:40.824522   32558 portforward.go:216] Forwarding from 5000 -> 5000
I0422 09:58:40.824643   32558 portforward.go:216] Forwarding from 5000 -> 5000
I0422 09:58:40.824709   32558 portforward.go:216] Forwarding from 6000 -> 6000
I0422 09:58:40.824878   32558 portforward.go:242] Handling connection for 5000
I0422 09:58:40.825124   32558 portforward.go:242] Handling connection for 6000
FAIL
FAIL	github.com/GoogleCloudPlatform/kubernetes/pkg/client/portforward	0.078s
```

I've seen this in two of my linux machines. @ncdc @akram

**Comment by ncdc** [comment] 2015-04-22 17:06
@ddysher what OS? Is ipv6 disabled?

**Comment by ddysher** [comment] 2015-04-22 17:14
Both are ubuntu 64bit
```
$ cat /proc/sys/net/ipv6/conf/all/disable_ipv6 
0
```
```
$ ifconfig
lo        Link encap:Local Loopback  
          inet addr:127.0.0.1  Mask:255.0.0.0
          inet6 addr: ::1/128 Scope:Host
          UP LOOPBACK RUNNING  MTU:65536  Metric:1
          RX packets:97016871 errors:0 dropped:0 overruns:0 frame:0
          TX packets:97016871 errors:0 dropped:0 overruns:0 carrier:0
          collisions:0 txqueuelen:0 
          RX bytes:81195700166 (81.1 GB)  TX bytes:81195700166 (81.1 GB)
```
Anything particular wrong here?

**Comment by ncdc** [comment] 2015-04-22 18:10
@ddysher not sure - I was looking at `listen tcp6: no suitable address found`

@akram please have a look at this

**Comment by ncdc** [comment] 2015-04-22 18:13
@ddysher can you paste the contents of /etc/hosts?

**Comment by ncdc** [comment] 2015-04-22 18:14
When I comment out this line in my /etc/hosts, the test fails as above:

```
::1         localhost localhost.localdomain localhost6 localhost6.localdomain6
```

**Comment by ncdc** [comment] 2015-04-22 18:17
I wonder if `"localhost"` used here (https://github.com/GoogleCloudPlatform/kubernetes/blob/master/pkg/client/portforward/portforward.go#L189) should be 127.0.0.1 instead? Will that always work on ipv4 and ipv6, or would there ever be issues?

I know @akram put in the most recent changes because `localhost` was resolving to `::1` instead of `127.0.0.1` for him, and I previously wasn't using `net.SplitHostPort`, and the extra colons in `::1` was tripping up my custom code that mimicked SplitHostPort (but didn't account for an ipv6 style localhost).

**Comment by ddysher** [comment] 2015-04-22 19:49
```
127.0.0.1       localhost

# The following lines are desirable for IPv6 capable hosts
::1     ip6-localhost ip6-loopback
fe00::0 ip6-localnet
ff00::0 ip6-mcastprefix
ff02::1 ip6-allnodes
ff02::2 ip6-allrouters
ff02::3 ip6-allhosts
```

Problem solved adding `::1         localhost localhost.localdomain localhost6 localhost6.localdomain6`.
Should we close the issue or keep finding a better solution, like mocking in the unittest?

**Comment by ncdc** [comment] 2015-04-22 19:51
I would prefer to find something that is deterministic. If localhost
sometimes resolves to 127.0.0.1 and sometimes to ::1, could we just switch
it to 127.0.0.1 and avoid this issue altogether? Or is it ever possible
that 127.0.0.1 gets resolved to ::1?

**Comment by akram** [comment] 2015-04-22 19:56
Hi,

other guys in team saw this a few hours ago, after investigation, here 
is the cause:

On some linux systems, ::1 does not resolve to localhost but to 
localhost6 or
ip6-localhost. This test needs to be refactored to do a reverse name 
lookup to be portable


         // names, err := net.LookupAddr("[::1]")
         /*{
             Hostname:                "localhost",
             Protocol:                "tcp6",
             ShouldRaiseError:        false,
             ExpectedListenerAddress: "::1",
         },*/

To workaround, comment the portion of code in port_forward_test.go
I will submit a fix in a few minutes


Akram

**Comment by akram** [comment] 2015-04-22 20:32
#7187 fixes this issue
One of the test cases fails on machine were ::1 does not resolve to localhost.
This seems to be the case for some linux distribution where ::1 resolves to localhost6 or ip6-localhost.

To workaround this, a reverse lookup on ::1 is performed, and the binding to the first name found is done.
If no name is found during resolution, the test case is skipped.

**Comment by ncdc** [comment] 2015-04-22 20:34
@akram I'd rather avoid resolving "localhost" if we can use 127.0.0.1
instead. Then all if the IPv4 vs IPv6 problems should go away, in theory.

**Comment by akram** [comment] 2015-04-22 20:50
There is a trick: the listener creation done [1] in portforward.go 
explicitely bind on "localhost" with a "tcp" parameter.
Which means: bind to localhost with the IP address that resolves first 
to it.

This is in fact, what this test cases tests.

We could fix the test case, but fixing the code requires touching 
portforward.go and that may have more impacts.

[1] 
https://github.com/GoogleCloudPlatform/kubernetes/blob/master/pkg/client/portforward/portforward.go#L189

**Comment by ncdc** [comment] 2015-04-22 20:59
I am looking for a solution in portforward.go that avoids name resolution, is deterministic, and works for IPv4 and IPv6.

**Comment by wojtek-t** [comment] 2015-04-23 10:25
/subscribe
cc @jszczepkowski

**Comment by quinton-hoole** [comment] 2015-06-15 21:29
Closing old issue.  @ncdc , @thockin  Please re-open if this still requires attention.

**Closed** 2015-06-15 21:29 UTC
Labels: area/networking, kind/bug, priority/P1, team/cluster, team/testing
