### ISSUE TITLE
"MaxPods Validates MaxPods limit number of pods that are allowed to run." has failed 22/30 times

### ISSUE THREAD

**Issue by zmerlynn** [GoogleCloudPlatform/kubernetes#10720] opened 2015-07-04 15:43 UTC
~~~This isn't a new test,~~~ but has failed on the last 22/30 e2e-gce runs and similar number on gke-ci. Looking for a culprit now.

**Comment by zmerlynn** [comment] 2015-07-04 16:00
This was introduced in #10481, at about the right time. Banning it to the flaky test list ASAP.

**Comment by davidopp** [comment] 2015-07-04 18:50
The functionality has been in the system for a while. The only thing that's new is the test. Of course it may mean the functionality is broken but much more likely is that there's a problem with the test.

**Comment by gmarek** [comment] 2015-07-06 06:26
IMO it's fixed by #10700. It wasn't a problem with functionality neither the test. Another e2e test wasn't cleaning after itself. @zmerlynn please verify and move back to gce

**Comment by wojtek-t** [comment] 2015-07-06 06:28
I agree - this test hasn't failed since #10700 was merged.

**Comment by zmerlynn** [comment] 2015-07-06 13:01
You could've sent the revert to close this bug out. :)

**Comment by wojtek-t** [comment] 2015-07-06 13:51
@zmerlynn - sorry I don't understand this comment. Why did you reopened this issue?

**Comment by zmerlynn** [comment] 2015-07-06 13:52
I was still writing the comment, sorry. In the process of diligence for sending the PR to take it off the flaky list, I noticed: Kubernetes e2e suite.MaxPods Validates MaxPods limit number of pods that are allowed to run. (Failed 3 times in the last 30 runs. Stability: 90 %)

When you closed this, that wasn't true, but this test can no longer come off.

**Comment by gmarek** [comment] 2015-07-06 15:26
I'm looking into those failures and all failures are different flavors of more general problems: dying pods, which cause `additional-pod` to be scheduled or too many container failures in `RunRC`. I can increase the tolarance fort the latter and add additional check for the first, but it'll only reduce flakyness...

**Comment by zmerlynn** [comment] 2015-07-06 16:05
Until we can get the flakiness down quite a bit, I think we should probably keep it sequestered.

**Comment by gmarek** [comment] 2015-07-06 16:51
RunRC failures have the following symptom:
`
I0706 16:27:02.084087    3094 server.go:163] HTTP InternalServerError: Internal Error: unable to find data for container /341c88bddf635ca2c858a2c3b89e54af522101694f14d2877ea1d73b8d1364b3
I0706 16:27:02.084302    3094 server.go:635] GET /stats/e2e-tests-maxp-oabfz/max-pods200-9c949f47-23fb-11e5-aeff-42010af01555-6taj7/9ff2d6c8-23fb-11e5-ab8d-42010af00091/max-pods200-9c949f47-23fb-11e5-aeff-42010af01555: (47.468479516s) 500
goroutine 4736 [running]:
github.com/GoogleCloudPlatform/kubernetes/pkg/httplog.(*respLogger).WriteHeader(0xc208cda6c0, 0x1f4)
	/go/src/github.com/GoogleCloudPlatform/kubernetes/_output/dockerized/go/src/github.com/GoogleCloudPlatform/kubernetes/pkg/httplog/log.go:188 +0x9a
net/http.Error(0x7f0da61d1bc0, 0xc208cda6c0, 0xc209d76180, 0x73, 0x1f4)
	/usr/src/go/src/net/http/server.go:1274 +0x9a
github.com/GoogleCloudPlatform/kubernetes/pkg/kubelet.(*Server).error(0xc2084030a0, 0x7f0da61d1bc0, 0xc208cda6c0, 0x7f0da6377d80, 0xc20a3a3810)
	/go/src/github.com/GoogleCloudPlatform/kubernetes/_output/dockerized/go/src/github.com/GoogleCloudPlatform/kubernetes/pkg/kubelet/server.go:164 +0x213
github.com/GoogleCloudPlatform/kubernetes/pkg/kubelet.(*Server).serveStats(0xc2084030a0, 0x7f0da61d1bc0, 0xc208cda6c0, 0xc208d8cea0)
	/go/src/github.com/GoogleCloudPlatform/kubernetes/_output/dockerized/go/src/github.com/GoogleCloudPlatform/kubernetes/pkg/kubelet/server.go:725 +0x78f
github.com/GoogleCloudPlatform/kubernetes/pkg/kubelet.(*Server).handleStats(0xc2084030a0, 0x7f0da61d1bc0, 0xc208cda6c0, 0xc208d8cea0)
	/go/src/github.com/GoogleCloudPlatform/kubernetes/_output/dockerized/go/src/github.com/GoogleCloudPlatform/kubernetes/pkg/kubelet/server.go:328 +0x46
github.com/GoogleCloudPlatform/kubernetes/pkg/kubelet.*Server.(github.com/GoogleCloudPlatform/kubernetes/pkg/kubelet.handleStats)·fm(0x7f0da61d1bc0, 0xc208cda6c0, 0xc208d8cea0)
	/go/src/github.com/GoogleCloudPlatform/kubernetes/_output/dockerized/go/src/github.com/GoogleCloudPlatform/kubernetes/pkg/kubelet/server.go:139 +0x45
net/http.HandlerFunc.ServeHTTP(0xc20847a120, 0x7f0da61d1bc0, 0xc208cda6c0, 0xc208d8cea0)
	/usr/src/go/src/net/http/server.go:1265 +0x41
net/http.(*ServeMux).ServeHTTP(0xc2086f8cf0, 0x7f0da61d1bc0, 0xc208cda6c0, 0xc208d8cea0)
	/usr/src/go/src/net/http/server.go:1541 +0x17d
github.com/GoogleCloudPlatform/kubernetes/pkg/kubelet.(*Server).ServeHTTP(0xc208403080, 0x7f0da61d1b88, 0xc2086bed20, 0xc208d8cea0)
`

**Comment by gmarek** [comment] 2015-07-06 17:01
We don't see such things in Density test, but it does have way higher tolerance (50 times higher) and does not saturate the cluster. With current scheduler semantics it fully saturated ~1/3 of the cluster which means ~30 machines. Because we have 50 times higher failure tolerance with only 15 times more load (where by load I mean number of fully saturated machines) we don't fail Density for this reason.

**Comment by davidopp** [comment] 2015-07-06 19:26
@bprashanth Could you take a look to see if there is a Kubernetes bug lurking in here? (See @gmarek's comment about dying pods)

**Comment by bprashanth** [comment] 2015-07-06 19:57
Failure to list stats for a container (https://github.com/GoogleCloudPlatform/kubernetes/issues/10720#issuecomment-118923036) is benign. Scheduling 100 pods per node is too much, we know we can't handle that load on an n1-standard, especially if we're running a resource heavy cluster addon like heapster on the same node. I'd recommend bringing down the pod count to something more manageable (I think we can handle a 100 containers, so 50 pods?). 

I'll look at restarting containers with a lower max pods in the meanwhile.

**Comment by bprashanth** [comment] 2015-07-07 02:09
@gmarek I think you should modify your test a little. It checks for running pods (https://github.com/GoogleCloudPlatform/kubernetes/blob/master/test/e2e/max_pods.go#L124) so if we had the (now fixed) scheduler bug, and the kubelet wasn't respecting max pods, we'd end up with 200 pods on a node right (and it won't fail)? Given that you need to count pods on a node, it could double as a spreading test

**Comment by gmarek** [comment] 2015-07-07 07:23
Yeah - but in this case 'additional-pod' will be able to schedule as well and the test will fail. I can do this if you think it's really important, but I don't think it's necessary.

**Comment by gmarek** [comment] 2015-07-07 13:38
FYI: I'm trying to make max-pods fail on local machine for last 6 hours, without any success. I already run max-pods test over 10 times. Also Jenkins seems to be happy. This makes me believe it's a load related flakynes, hence increasing thresholds/allowing retries will solve the issue.

**Comment by bprashanth** [comment] 2015-07-07 16:51
> Yeah - but in this case 'additional-pod' will be able to schedule as well and the test will fail.

That really depends on the nature of the bug (it could lead to container restarts if triggered the wrong way, or the additional-pod could hit at exactly the wrong limit etc). I'm ok with not fixing this asap but i would like a more stringent post condition verification when you have time :)

I have also not been able to repro, but wdyt about reducing the max pods (after profiling/discussion with the node team to figure out the exact number)?

**Comment by gmarek** [comment] 2015-07-07 18:56
Exact number for what? I believe we think that we want to run 30 user pods/node, and add some additional slack for addons. Current 100 is set up to allow stress tests, as we cannot have specific test Kubelet config (#8802 was never merged).

**Comment by bprashanth** [comment] 2015-07-07 20:52
> Exact number for what? 

Checking that one last pod is not running seems insufficient. you can still allow 200 pods to start on a single node and the last one would fail.

>Current 100 is set up to allow stress tests,

Out of curiousity, which ones? seems like a waste of time if people are debugging failures at a 100 pods per node

**Comment by gmarek** [comment] 2015-07-07 21:54
IIUC RedHat were running Density tests for larger numbers. @wojtek-t @smarterclayton

**Comment by smarterclayton** [comment] 2015-07-08 00:13
@pmorie had an env that was pushing a hundred per (I think?)

On Jul 7, 2015, at 5:55 PM, Marek Grabowski <notifications@github.com>
wrote:

IIUC RedHat were running Density tests for larger numbers. @wojtek-t
<https://github.com/wojtek-t> @smarterclayton
<https://github.com/smarterclayton>

—
Reply to this email directly or view it on GitHub
<https://github.com/GoogleCloudPlatform/kubernetes/issues/10720#issuecomment-119353991>
.

**Comment by gmarek** [comment] 2015-07-08 08:54
I've seen a couple of failures during the night (EU time), which suggests they are probably load related (US day). I'll need to enable more, and pretty verbose logging to debug further. PR doing this is #10916 and an issue #10915 for increasing verbosity for flaky test suite.

**Comment by wojtek-t** [comment] 2015-07-08 08:57
@gmarek - did you look whether there were some nodes restarted during tests that failed? It's possible that the problem might be similar to what I described in https://github.com/GoogleCloudPlatform/kubernetes/issues/10792#issuecomment-119504182

**Comment by gmarek** [comment] 2015-07-08 10:10
Yup. Kubelet restarted few times at the beginning, but not after tests started to run

**Comment by gmarek** [comment] 2015-07-09 07:34
Needs #10915 to be solved to debug further.

**Comment by gmarek** [comment] 2015-07-09 08:42
There're two kind of failures: First is
```
Expected error:
    <*errors.errorString | 0xc2085d9820>: {
        s: "4 containers failed which is more than allowed 1",
    }
    4 containers failed which is more than allowed 1
```
Which AFAICT is caused by Kubelet restarts, as @wojtek-t suggested.

Second is one that need #10915 to debug:
```
Expected
    <[]api.Event | len:0, cap:0>: []
not to be empty
```
which means that we schedule too many pods for some reason.

**Comment by rrati** [comment] 2015-07-10 19:47
We've seen this test fail on our cluster as well.  We were running kubelets without the --maxpods flag so it should have allowed 100 pods/node.  While the rc was created with the correct number of pods, the kubelets looked to allow >100 pods/node.  I saw at least 1 system with 101 pods on it.  On our cluster, it always fails with the 2nd failure:

Expected
    <[]api.Event | len:0, cap:0>: []
not to be empty

It looks like maxpods isn't limiting the number of pods running on a kubelet like it is supposed to.

**Comment by davidopp** [comment] 2015-07-10 19:53
We really need to figure out whether this is a product bug or a test bug. @bprashanth @gmarek @wojtek-t can you look into this? If it is really not possible to debug this without #10915, could one of you implement that (or find someone to do it)?

**Comment by davidopp** [comment] 2015-07-10 19:53
Also, I will manually review the code that implements the feature to see if I see any obvious problems.

**Comment by timothysc** [comment] 2015-07-10 19:59
@davidopp what we can state for certain is the kubelet indeed runs more then specified.

**Comment by gmarek** [comment] 2015-07-10 20:06
yup, I have seen a run that actually was running more than max-pods pods. This problem is really hard to debug, as I failed to reproduce it locally, hence we need to depend on failed Jenkins runs. Flakyness is ~1/10 (estimate from memory), and roughly half of it is clearly related to Kubelet restarts (those are the failures of RunRC). Without #10915 it's really hard to figure out anything, as by default we log very little.

I have absolutely no idea how Jenkins is configured, nor do I have access to it. I hoped that it's a 5 minutes of work for someone who's more familiar with it, but if that's not the case I can try to do it on Monday.

**Closed** 2015-07-14 21:59 UTC
Labels: area/test, priority/P0, team/master, team/node
