### ISSUE TITLE
GCE: Forwarding Rules and Target Pools remain after kube-down

### ISSUE THREAD

**Issue by smreed** [GoogleCloudPlatform/kubernetes#2984] opened 2014-12-16 22:31 UTC
This, combined with the fact that the target pools are not updated when creating an external load balancer, means that your next cluster could have a misconfigured LB.

1. Create cluster set NUM_MINIONS=4
2. Create a service "foo" w/ external load balancer.
3. Tear down cluster with kube-down.
4. At this point you can still see your forwarding rules and target pools.
5. Repeat step 1 w/ NUM_MINIONS=6
6. Repeat step 2
7. Note the "foo" target pool only has 4 members. kubernetes-minion-{5,6} are missing.

Possibly addressed by a proper resolution to #1836?

**Comment by jasonkuhrt** [comment] 2015-01-12 18:13
I just ran into this!

**Comment by jszczepkowski** [comment] 2015-03-04 08:03
This is related to #4630 and I'm working on it.

**Comment by roberthbailey** [comment] 2015-03-19 21:08
Closing as a dupe of #4630.

**Closed by roberthbailey** 2015-03-19 21:08 UTC
Labels: priority/P2, team/cluster-lifecycle
