### ISSUE TITLE
kubectl describe pod should include container last termination status

### ISSUE THREAD

**Issue by dchen1107** [GoogleCloudPlatform/kubernetes#11496] opened 2015-07-18 00:21 UTC
There is no easy way to retrieve last termination resource / status for a pod except kubectl get pods -o option.

**Comment by samsabed** [comment] 2015-07-28 05:57
looks similar to #10861

**Comment by saad-ali** [comment] 2015-07-31 19:49
Closing duplicate of #10861

**Closed by saad-ali** 2015-07-31 19:49 UTC
Labels: area/introspection, priority/P2, team/CSI, team/node
