### ISSUE TITLE
Kubectl refuses to respect KUBERNETES_PROVIDER when gce cluster is running

### ISSUE THREAD

**Issue by bprashanth** [GoogleCloudPlatform/kubernetes#4310] opened 2015-02-11 07:19 UTC
I ran into this issue attempting to run 2 kubernetes clusters simultaneously, one on localhost and another on gce. With a little debugging I was able to piece together the following stack trace:

```
Kubectl uses wrong api server with KUBERNETES_PROVIDER=local, while gce cluster is active
Wrong rest client created 
Wrong client config used to create rest client 
Client config loaded from ConfigCache 
ConfigCache merges empty config with contents from $HOME/.kube/.kubeconfig
```
At this point it was obvious to me that the issue was related to running 2 clusters. Very similar to https://github.com/GoogleCloudPlatform/kubernetes/issues/4298, however I can't solve this unless I actually remove the .kubeconfig (at which point I can't `get pods` from gce in a different terminal).

Assuming this isn't by design, a potential fix might be to teach the loader about KUBERNETES_PROVIDER (i.e just skip looking around for cached configs in ClientConfigLoadingRules.Load if it's set). I don't have enough context to think much further, @jlowdermilk thoughts?

**Comment by jlowdermilk** [comment] 2015-02-11 17:47
I think the right fix is to create config for the local cluster in [hack/local-up-cluster](https://github.com/GoogleCloudPlatform/kubernetes/blob/master/hack/local-up-cluster.sh).

The title brings up a broader issue, which is that kubectl doesn't respect KUBERNETES_PROVIDER anyway. We need to update `kubectl.sh` and other scripts/getting started guides to account for the fact that `kubectl` now always loads its settings from a .kubeconfig file, unless it is passed override flags (--server, --insecure-skip-tls-verify, etc).

**Comment by jlowdermilk** [comment] 2015-02-11 18:17
Going to close this as a dupe of #4298. Will update that one and fix there.

**Closed** 2015-02-11 18:18 UTC
Labels: component/CLI
