### ISSUE TITLE
kube2sky cannot connect to apiserver

### ISSUE THREAD

**Issue by ArtfulCoder** [GoogleCloudPlatform/kubernetes#8314] opened 2015-05-15 12:53 UTC
kube2sky cannot talk to apiserver 

```
root@kubernetes-minion-3nqj:/etc# docker ps
967f6215acd9        gcr.io/google_containers/kube2sky:1.4                "/kube2sky -domain=c
```
967f6215acd9 is kube2sky container.

```
root@kubernetes-minion-3nqj:/etc# docker logs 967f6215acd9
I0515 11:27:17.448247       1 kube2sky.go:148] Etcd server found: http://127.0.0.1:4001
I0515 11:27:18.451591       1 kube2sky.go:202] Using https://10.0.0.2:443 for kubernetes master
I0515 11:27:18.451604       1 kube2sky.go:203] Using kubernetes API
E0515 11:27:48.452108       1 reflector.go:130] Failed to list *api.Service: Get https://10.0.0.2:443/api/v1beta3/services: dial tcp 10.0.0.2:443: i/o timeout
```

10.0.0.2 does seem to be the virtual ip for apiserver that kube2sky is using.
```
-A KUBE-PORTALS-CONTAINER -d 10.0.0.2/32 -p tcp -m comment --comment "default/kubernetes:" -m tcp --dport 443 -j REDIRECT --to-ports 59180
-A KUBE-PORTALS-HOST -d 10.0.0.2/32 -p tcp -m comment --comment "default/kubernetes:" -m tcp --dport 443 -j DNAT --to-destination 10.240.30.233:59180
```

@vishh @thockin @cjcullen

**Comment by ArtfulCoder** [comment] 2015-05-15 13:15
the quick fix that I had of changing http to https, in my previous checkin, was a bit too quick too. We have to be more elaborate than that simplistic approach. We should be checking if we are using the RO port or not and determine protocol to be http or https.

**Comment by ArtfulCoder** [comment] 2015-05-15 14:03
untested #8318
this may not fix the issue, but we need this something like this too...

**Comment by ArtfulCoder** [comment] 2015-05-15 14:24
manually verified that #8318 fixes the problem correctly.
A new version of kube2sky will need to be pushed out.

**Comment by ArtfulCoder** [comment] 2015-05-15 17:00
```
 Failed to list *api.Service: Get https://10.0.0.2:443/api/v1beta3/services: x509: certificate is valid for 146.148.42.26, not 10.0.0.2
```

After setting up all the certs, I got the above error.
I believe we can't use https to talk to apiserver,  as long as the certs are master host ip based, and the clients are using a virtual ip to reach apiserver.

If we can do token auth over http, it would defeat the purpose since the token can be intercepted.

I believe we should rollback any changes related to using https to talk to apiserver from dns pod, or any other pod for that matter which uses virtual ip of apiserver to reach it.

For kube2sky, we can use the RO port of apiserver and move on...


@cjcullen @thockin @vishh

**Comment by vishh** [comment] 2015-05-15 17:25
The RO port is being deprecated. We just posted a public announcement that
it is being deprecated.

**Comment by ArtfulCoder** [comment] 2015-05-15 17:33
We have the explore the following options:
1. have the cert support more than 1 ip. host ip and virtual ip. Have the virtual ip assigned to apiserver.
2. add the dns name on the cert, in addition to hostip, so that pods can use dns name to access it.

**Comment by ArtfulCoder** [comment] 2015-05-15 17:54
A third option is to make skydns a master component and avoid all these cert issues by talking on localhost on unsecure port of apiserver.

I think this might be the easiest solution

**Comment by roberthbailey** [comment] 2015-05-15 17:56
@ArtfulCoder That is going to break when #6949 lands b/c it explicitly detaches the kubelet on the master from the cluster. So DNS would no longer be available from any of the nodes.

**Comment by ArtfulCoder** [comment] 2015-05-15 17:59
@roberthbailey I didnt grasp the problem completely. Do nodes need dns to join a cluster ? or Should nodes be able to work without the ability to reach the master ?

**Comment by ArtfulCoder** [comment] 2015-05-15 22:01
@brendanburns I think you might have an answer about the cert generation. Can we have the cert generated in a way that does not cause cert validation to break if apiserver is accessed via a virtual ip.

**Comment by cjcullen** [comment] 2015-05-15 22:22
Right now, we create all the system-token kubeconfig files to point at https://kubernetes. We could break the DNS token out to point at https://$MASTER_NAME, because we already sign the master's cert w/ MASTER_NAME.

For private network clusters, MASTER_NAME is just the internal DNS name of the master. For public network clusters, MASTER_NAME can be the master's IP, or later a load-balanced IP of HA masters, or a public DNS name for a (load-balanced or not) master.

**Comment by vishh** [comment] 2015-05-15 23:12
Would setting the default be master's IP reduce the friction for users who
run without an external DNS server?

**Comment by roberthbailey** [comment] 2015-05-15 23:21
To be clear, the cert configuration is only automatically plumbed in for GCE right now. There's no nice automatic solution across all cloud providers as part of v1.0 because we pushed dynamic clustering beyond the milestone. Static clustering requires cert distribution, and it's a bit ugly.

I think we want the default endpoint for non-DNS services to be the DNS name of the internal kubernetes service. This will make the transition to HA master easier, because (other than DNS) nothing will need to change for any other service that is accessing the master -- they will all just use a name that happens to get load balanced across multiple apiservers rather than just resolving to one apiserver.

**Comment by ArtfulCoder** [comment] 2015-05-16 07:11
What you say would work for all pods except the skydns pod itself. 
For skydns pod,  who would resolve the dns name of apiserver, when skydns is itself a client of apiserver? 
The skydns pod would have to be bootstrapped with the dns A record for apiserver (mapped to virtual ip)

Instead, we can simply reserve a virtual ip for apiserver. (We already do this today). apiserver cert will have the virtual ip in it. 
Other pods including skydns can then access apiserver using this virtual ip
Other pods excluding skydns, can optionally use apiserver dns name.

**Comment by roberthbailey** [comment] 2015-05-16 15:50
SkyDns can just use the $MASTER_NAME (either a resolvable dns name like kubernetes-master or the external IP of the master) in the same way that the kubelet and kube-proxy do since it's a bootstrapping service. Then everything else can ride on top of skydns and use the RW service name.

**Comment by ArtfulCoder** [comment] 2015-05-16 16:05
1. external IP would work. But do we want to use external ip for this ?
2.( User defined pods could still use a resolvable dns name.)

Some concerns with external IP:
1. Can we expect external IP to be stable across cloud providers.
2. Once apiserver is load balanced and not necessarily on master, do we rely on load balancing to happen through use of external IP or do we end up requiring a LB ?

We dont have these  concerns with virtual ip in certs..

**Comment by roberthbailey** [comment] 2015-05-17 06:24
> Can we expect external IP to be stable across cloud providers.

The fields that are signed on the cert don't have to exactly match across cloud providers. I think we want GCE to provide an example of how we suggest certs get signed but other cloud providers don't have to do it in exactly the same way (vagrant, for example, might do things insecurely by default because it's used locally). 

> Once apiserver is load balanced and not necessarily on master, do we rely on load balancing to happen through use of external IP or do we end up requiring a LB ?

I think skydns is a special case because it provides bootstrapping services (naming) to the rest of the cluster. It will always be possible for skydns to use an external IP to reach the apiserver (because kubectl will need this to work) so the degenerate case is using the external IP.

**Comment by thockin** [comment] 2015-06-01 19:14
Status on this - Abhishek, you're the assignee but I know you're on other stuff - what's the plan here?

@vishh

**Comment by ArtfulCoder** [comment] 2015-06-01 20:23
@thockin 
There are two parts to the solution:
1. For components that belong to kubernetes, e.g. kube2sky, the apiserver hostname to use is the host name of the master node. e.g. kubernetes-master. 
@vishh is working on that :  https://github.com/GoogleCloudPlatform/kubernetes/pull/8718/files

2. For user-defined pods who are unaware of the master node name, they will use the internal dns name of the apiserver : kubernetes.default.svc.cluster.local. This string would need to be added as a SAN on the APIServer server cert. This work needs to be done.

**Comment by vishh** [comment] 2015-06-01 20:33
How will #8718 address this issue? IIUC, kube2sky needs to use the public
master IP to connect to the master securely. #8718 is making kube2sky use
the 'kuberbetes' service VIP (10.0.0.2).

**Comment by thockin** [comment] 2015-06-01 20:36
This bug is about (if I recall the resolution) using salt to stick the
master's name (as defined at cluster birth) into the DNS config.

**Comment by roberthbailey** [comment] 2015-06-01 20:43
Once #8314 goes in I think this may end up as a dupe of https://github.com/GoogleCloudPlatform/kubernetes/issues/8480. I have some pending salt changes to secure the connection between kube2sky and the master.

**Closed** 2015-06-09 20:28 UTC
Labels: area/networking, priority/P1, team/cluster
