### ISSUE TITLE
Comment for Pod.Status.StartTime inconsistent with implementation

### ISSUE THREAD

**Issue by gmarek** [GoogleCloudPlatform/kubernetes#9792] opened 2015-06-15 10:00 UTC
https://github.com/GoogleCloudPlatform/kubernetes/blob/master/pkg/api/types.go#L924

It currently reads that it's a time when Kubelet acknowledged scheduled Pod, but my tests and understanding the code suggests that it's really a start time (time after all containers are started). Can someone more familiar with Kubelet code take a look as well?

@dchen1107 @vmarmol

**Comment by derekwaynecarr** [comment] 2015-06-16 03:47
If the behavior is not aligned with the description, it's a bug.  The intent was for this field to include time to do a docker pull of any requisite images.  I had added this API, it's possible there was a bug or skew in behavior.  I have a corresponding bug in Red Hat bugzilla for this that I can link to tomorrow.

**Comment by derekwaynecarr** [comment] 2015-06-16 03:47
@abhgupta

**Comment by davidopp** [comment] 2015-06-16 06:31
We should let one of the experts weigh in, but it looks to me like it's doing what is documented. AFAICT PodStatus.StartTime is set on the first call to statusManager.SetPodStatus(), which happens on the first call to syncPod() for a pod, which is before the containers are started.

**Comment by gmarek** [comment] 2015-06-16 08:24
@davidopp it indeed is called in syncPod(), but in deferred function. Hence it's done after containers are started (after containerRuntime.SyncPod() returned), AFAICT.

**Comment by davidopp** [comment] 2015-06-16 08:33
Oh, you're right. Thanks for clarifying.

**Comment by bgrant0607** [comment] 2015-06-17 22:24
cc @dchen1107

**Comment by davidopp** [comment] 2015-06-17 22:27
I'll send a PR to update the comment. The comment is clearly wrong and @gmarek is out the rest of the week.

**Comment by dchen1107** [comment] 2015-06-17 23:17
If I understood @derekwaynecarr above correctly, he think we should fix the implementation instead of the comment / description. Sounds like openshift is using such field.

**Comment by bgrant0607** [comment] 2015-06-17 23:20
The start time was used to implement ActiveDeadlineSeconds. See https://github.com/GoogleCloudPlatform/kubernetes/pull/7868#issuecomment-99706316.

**Comment by dchen1107** [comment] 2015-06-17 23:28
@bgrant0607 thanks for the pr link. I tried to find it, but failed. Yes, we should fix the implementation, not description.

**Comment by davidopp** [comment] 2015-06-18 00:02
I'm confused. @derekwaynecarr said "The intent was for this field to include time to do a docker pull of any requisite images." Isn't that what's currently happening? This call
https://github.com/GoogleCloudPlatform/kubernetes/blob/6f0c48479f51910a4c7f71365a5d1529c235ac9f/pkg/kubelet/kubelet.go#L1117
is deferred to end of syncPod(), as @gmarek mentioned.

**Comment by davidopp** [comment] 2015-06-18 00:05
Oh I see what happened. What @derekwaynecarr wrote in this issue ("time to do a docker pull of any requisite images") is different than what he wrote in the issue @bgrant0607 pointed to ("Add a timestamp to PodStatus that denotes when a Kubelet acknowledges that a Pod has been scheduled to the host.")

So which is correct?

**Comment by davidopp** [comment] 2015-06-18 00:06
(And by correct, I mean which is the desired behavior, not what is implemented, which is clear.)

**Comment by dchen1107** [comment] 2015-06-18 00:36
@davidopp both are the same and correct. But the implementation might be messed up since it is in syncPod's deferred function mentioned by @gmarek. I will double check the code later.

**Comment by dchen1107** [comment] 2015-06-18 00:47
Ok, I think there is bug since the feature first introduced to kubernetes. Kubelet generated podStatus in syncPod when kubelet first acknowledges the pod on the node, but never cached it in status_manager. Later in the same syncPod's deffered function, kubelet regenerated the status, and cached this version.

**Comment by derekwaynecarr** [comment] 2015-06-18 01:42
The intent was for the following:

1. Kubelet observes a pod is binded to its host.
2. Kubelet records the pod.Status.StartTime
3. Kubelet does a docker pull for container(s) image
4. Kubelet starts the pod

This does sound like a regression because I currently hold a Bugzilla issue for OpenShift that the StartTime is being applied after the image is pulled.

@dchen1107 - it does sound like the change in behavior you noted may have happened.  I should have some time tomorrow to debug this further, but if you see where the change was introduced I would appreciate the assistance.

**Comment by bprashanth** [comment] 2015-06-18 02:44
> Kubelet observes a pod is binded to its host.

@derekwaynecarr do you mean as soon as the kubelet has received the nofitication for a new pod bound to its node, or as soon as the kubelet starts processing that notification? If you don't care eitherway we can have the StartTime reflect the former, and it would help monitor watch latencies as well

**Comment by gmarek** [comment] 2015-06-18 05:27
+1 @bprashanth - having this reflect binding time would make monitoring slightly simpler, as we won't need to instrument the code to get watch lag.

**Comment by derekwaynecarr** [comment] 2015-06-18 14:35
@bprashanth - can you distinguish between "kubelet has received the notification for a new pod bound to its node" vs "as soon as the kubelet starts processing that notification"?  I want start time to be set by the Kubelet, not by another component that binds the pod to a node (i.e. the scheduler should NOT set the value, if we want that, we should have another flag that is scheduledAt or something).  If I understand correctly, I would like the value to be "kubelet has received the notification for a new pod bound to its node" since that is closest to the idea that the "kubelet has acked the pod is bound to its node" which was the spirit of the design.

**Comment by bprashanth** [comment] 2015-06-18 15:36
@derekwaynecarr 
> can you distinguish between "kubelet has received the notification for a new pod bound to its node" 

The reflector on the node (not the scheduler, this is client side) has stored the new pod in a queue. The kubelet won't observe this pod if it isn't waiting in syncLoop (https://github.com/GoogleCloudPlatform/kubernetes/blob/master/pkg/kubelet/kubelet.go#L1669). Reasons it might not be waiting in syncLoop are eg: that it's creating pod workers or deleting pods.

> vs "as soon as the kubelet starts processing that notification"?

The kubelet has pulled the update out of that channel. 

> "kubelet has received the notification for a new pod bound to its node" 

Hmm, so it sounds like 1 will suffice?

**Comment by derekwaynecarr** [comment] 2015-06-18 16:43
@bprashanth - 1 is my preference.

**Comment by dchen1107** [comment] 2015-06-18 18:23
I think the record for the initial PodStatus when kubelet acknowledge the pod at the initial time is missing, should be a simple fix. The only concern I had is that when node is under resource pressure, kubelet / docker might slowly take action on PodSpec, which might affects the feature introduced by #7868 since it makes ActiveDeadlineSeconds very undeterministic.

**Comment by bprashanth** [comment] 2015-06-18 18:28
That's why i asked for clarification between the 2 cases, and it sounded like the startttime including this slow-kubelet time, when it happens, was ok?

**Comment by yujuhong** [comment] 2015-06-18 19:48
> The only concern I had is that when node is under resource pressure, kubelet / docker might slowly take action on PodSpec, which might affects the feature introduced by #7868 since it makes ActiveDeadlineSeconds very undeterministic.

That is also my understanding. `StartTime` is used mainly with ActiveDeadlineSeconds to determine how long a container/pod has been running, and kubelet is responsible for terminating the pod/container once the deadline has been reached. Given that image pulling may take a long time, the active deadline could be inaccurate.


> That's why i asked for clarification between the 2 cases, and it sounded like the startttime including this slow-kubelet time, when it happens, was ok?

Hmm...is it really okay if the pod has passed the deadline before the containers are started?

**Comment by bprashanth** [comment] 2015-06-18 19:56
That really depends on how you define the deadline (i.e there could be "virtual" resources a user is consuming even if the kubelet hasn't seen the pod. A typical example is limit range quota -- though for that one might want to set the StartTime even earlier).  @derekwaynecarr since you wanted the initial feature, wdyt?

**Comment by derekwaynecarr** [comment] 2015-06-18 20:12
I want what was originally discussed when doing ```ActiveDeadlineSeconds``` which means that the ```StartTime``` takes effect before any docker image pulls occur.  It is intentionally NOT the container start time.   Hence, I would like "kubelet has received the notification for a new pod bound to its node" to be ```StartTime```.

**Comment by dchen1107** [comment] 2015-06-18 21:45
Ok, let me just quickly send a fix for this. We can work on the issue for slow action from kubelet / docker under resource pressure later.

**Closed** 2015-06-19 15:05 UTC
Labels: kind/bug, priority/P2, team/node
