### ISSUE TITLE
Vagrant networking doesn't allow master->container networking

### ISSUE THREAD

**Issue by jbeda** [GoogleCloudPlatform/kubernetes#3580] opened 2015-01-16 22:40 UTC
This breaks the `test/e2e/network.go` test.

The HTTP proxy capability of the apiserver assumes it can talk directly to containers.  This works on GCE but not on vagrant (and probably other clusters that only stitch together networking on nodes).

**Comment by jbeda** [comment] 2015-01-16 22:41
I'm disabling the test for now as part of #3530.

**Comment by jbeda** [comment] 2015-01-20 21:59
Also breaks `test/e2e/cluster_dns.go`.

**Comment by roberthbailey** [comment] 2015-03-03 00:24
@derekwaynecarr - have you had a chance to take a look at this? Is it still an issue?

**Comment by derekwaynecarr** [comment] 2015-03-03 00:36
This is fixed

**Comment by derekwaynecarr** [comment] 2015-03-06 18:27
Closing this because the issue is fixed.

**Closed by derekwaynecarr** 2015-03-06 18:27 UTC
Labels: area/networking, cluster/platform/vagrant, priority/P2, team/cluster-lifecycle

**Comment by karlkfi** [comment] 2015-06-22 19:16
@derekwaynecarr I see 3 tests still being skipped, linking to this issue:
1. [DNS should provide DNS for the cluster](https://github.com/GoogleCloudPlatform/kubernetes/blob/master/test/e2e/dns.go#L148)
1. [DNS should provide DNS for services](https://github.com/GoogleCloudPlatform/kubernetes/blob/master/test/e2e/dns.go#L213)
1. [Networking should function for intra-pod communication](https://github.com/GoogleCloudPlatform/kubernetes/blob/master/test/e2e/networking.go#L77)

Do these work on vagrant now? Should the tests be un-skipped? Or was the "fix" to skip them?

**Comment by derekwaynecarr** [comment] 2015-06-23 17:05
The "fix" was to skip them, but I think we should remove that "fix".

**Comment by thockin** [comment] 2016-03-11 17:10
@derekwaynecarr I haven't spun up vagrant lately - is this still an issue for DNS tests?  We want to make DNS a conformance test.

**Comment by derekwaynecarr** [comment] 2016-03-12 01:31
DNS is on in vagrant.

I can run conformance tests Monday and we can update the referenced tests
