### ISSUE TITLE
Little to no validation occurs on a Minion on create

### ISSUE THREAD

**Issue by derekwaynecarr** [GoogleCloudPlatform/kubernetes#4992] opened 2015-03-03 19:09 UTC
Looking at the current code:

https://github.com/GoogleCloudPlatform/kubernetes/blob/master/pkg/api/validation/validation.go#L826

we do no validation on a minion.Spec value, therefore any initial capacity or external ids avoid validation.

this can also result in our node controller when paired with a cloud provider to create invalid nodes.

**Comment by smarterclayton** [comment] 2015-03-04 01:09
Should be fixed to use new genericetcd! :)

**Comment by bprashanth** [comment] 2015-03-19 17:00
You'd still need to teach the validation strategy to run through the node spec right?

**Comment by smarterclayton** [comment] 2015-03-19 19:11
Yes

**Comment by bprashanth** [comment] 2015-03-19 19:15
@kazegusuri

**Comment by rjnagal** [comment] 2015-03-20 00:01
@bprashanth assigned this to myself. Let me know if you were planning to work on it.

**Comment by bprashanth** [comment] 2015-03-20 01:40
oh, no, but @kazegusuri's been doing some node/etcd work off late so just make sure you both don't tread toes :)

**Comment by kazegusuri** [comment] 2015-03-20 08:27
ValidateMinion and ValidateMinionUpdate are called even for now, and they are called via strategy once #5441 is merged.
I haven't touched validations to Node yet, so please do it thanks.

**Comment by bprashanth** [comment] 2015-03-20 16:08
The problem is validate minion doesn't validate the spec, it stops with objectmeta.
https://github.com/GoogleCloudPlatform/kubernetes/blob/master/pkg/api/validation/validation.go#L844

**Comment by rjnagal** [comment] 2015-03-23 17:00
I added two validations to Spec:

- ExternalID: required.
- Capacity: cpu and memory required. We could schedule pods that don't specify resources to nodes that don't publish resources. But it looks like we assume that these fields are present at other places in the code.

**Comment by smarterclayton** [comment] 2015-03-23 17:02
That will be a breaking change for api consumers.  We should double check and announce that.

----- Original Message -----

**Comment by rjnagal** [comment] 2015-03-23 17:16
I am fixing the tests and checking the checking the current usages. Capacity is the one thats worrisome.

@dchen1107 believes that these values are assumed to be required already in other subsystems. We'll verify before committing the change.

@smarterclayton What's the best list to announce the change?

**Comment by smarterclayton** [comment] 2015-03-23 17:29
https://github.com/GoogleCloudPlatform/kubernetes/blob/master/docs/devel/api_changes.md :)

----- Original Message -----

**Comment by smarterclayton** [comment] 2015-03-23 17:31
Heh, it doesn't describe *where* to discuss changes.  So we should also add that as well.  kubernetes-dev and adding to a changelog were also described.

----- Original Message -----

**Comment by rjnagal** [comment] 2015-03-26 20:07
Fixed by #5929

**Closed by rjnagal** 2015-03-26 20:07 UTC
Labels: api/cluster, component/nodecontroller, priority/P2, team/master
