### ISSUE TITLE
Scheduler is not using watch to monitor nodes

### ISSUE THREAD

**Issue by fgrzadkowski** [GoogleCloudPlatform/kubernetes#6563] opened 2015-04-08 11:52 UTC
For some reason scheduler has a logic to watch nodes, but it is disabled:

https://github.com/GoogleCloudPlatform/kubernetes/blob/master/plugin/pkg/scheduler/factory/factory.go#L169

This is not very heavy, because there will be up to 100 nodes, but we should get rid of this.

@lavalamp @davidopp @wojtek-t

**Comment by fgrzadkowski** [comment] 2015-04-08 13:33
@piosz This is not a blocker for v1.0

**Comment by wojtek-t** [comment] 2015-04-08 14:07
@lavalamp 
 Is it possible to replace a poller with simple "watch with field selector" here:
https://github.com/GoogleCloudPlatform/kubernetes/blob/master/plugin/pkg/scheduler/factory/factory.go#L169
?

Basically pollMinions filters out all nodes that doesn't have condition NodeReady (plus are unschedulable, but this is easy to change to field selector). The problem is that "Node.Status.Conditions" is an array and IIUC there is currently no support for selectors on arrays.
Do we want to add it?

The alternative would be to wrap the watch interface + filtering function into another watch interface.

**Comment by lavalamp** [comment] 2015-04-08 17:10
@wojtek-t I almost did this yesterday as part of #6546, but ended up not doing it. I think watch everything and filter in the client on request is probably easiest.

**Comment by wojtek-t** [comment] 2015-04-16 14:04
Fixed by #6717 and  #6857

**Closed by wojtek-t** 2015-04-16 14:04 UTC
Labels: area/performance, priority/P2, team/master
