### ISSUE TITLE
kube2sky 1.9 'fails to open /etc/resolv.conf'

### ISSUE THREAD

**Issue by jeffbean** [GoogleCloudPlatform/kubernetes#9903] opened 2015-06-16 22:07 UTC
Installation of skydns is not working for Kubernetes 0.18.0. Info and logs below. 

Running Kube 0.18.0 installed form CentOS7 testing repo.
```
Arch        : x86_64
Version     : 0.18.0
Release     : 0.2.git5520386.el7
```

Errors from kube2sky container:
```
[root@kube-master-test-01 kube]# kubectl logs kube-dns-v3-utqrr kube2sky
I0616 21:56:11.626437       1 kube2sky.go:388] Etcd server found: http://127.0.0.1:4001
I0616 21:56:13.630064       1 kube2sky.go:451] Using https://kubernetes:443 for kubernetes master
I0616 21:56:13.630102       1 kube2sky.go:452] Using kubernetes API 
E0616 21:56:13.632186       1 reflector.go:136] Failed to list *api.Endpoints: Get https://kubernetes:443/api/v1beta3/endpoints: dial tcp: error reading DNS config: open /etc/resolv.conf: permission denied
E0616 21:56:13.632428       1 reflector.go:136] Failed to list *api.Service: Get https://kubernetes:443/api/v1beta3/services: dial tcp: error reading DNS config: open /etc/resolv.conf: permission denied
E0616 21:56:14.632709       1 reflector.go:136] Failed to list *api.Endpoints: Get https://kubernetes:443/api/v1beta3/endpoints: dial tcp: error reading DNS config: open /etc/resolv.conf: permission denied
E0616 21:56:14.632856       1 reflector.go:136] Failed to list *api.Service: Get https://kubernetes:443/api/v1beta3/services: dial tcp: error reading DNS config: open /etc/resolv.conf: permission denied
E0616 21:56:15.633118       1 reflector.go:136] Failed to list *api.Endpoints: Get https://kubernetes:443/api/v1beta3/endpoints: dial tcp: error reading DNS config: open /etc/resolv.conf: permission denied
E0616 21:56:15.633457       1 reflector.go:136] Failed to list *api.Service: Get https://kubernetes:443/api/v1beta3/services: dial tcp: error reading DNS config: open /etc/resolv.conf: permission denied
```

skydns is running on pod:
```
[root@kube-master-test-01 kube]# kubectl get po kube-dns-v3-utqrr
POD                 IP            CONTAINER(S)   IMAGE(S)                                         HOST                               LABELS                                                           STATUS    CREATED              MESSAGE
kube-dns-v3-utqrr   172.17.0.13                                                                   kube-minion-test-01/10.21.224.65   k8s-app=kube-dns,kubernetes.io/cluster-service=true,version=v3   Running   About a minute       
                                  skydns         gcr.io/google_containers/skydns:2015-03-11-001                                                                                                       Running   Less than a second   last termination: exit code 2
                                  etcd           gcr.io/google_containers/etcd:2.0.9                                                                                                                  Running   Less than a second   
                                  kube2sky       gcr.io/google_containers/kube2sky:1.9                                                                                                                Running   Less than a second   
```

The skydns rc file:  `/etc/kubernetes/addons/dns/skydns-rc.yaml `
```
apiVersion: v1beta3
kind: ReplicationController
metadata:
  name: kube-dns-v3
  namespace: default
  labels:
    k8s-app: kube-dns-v3
    kubernetes.io/cluster-service: "true"
spec:
  replicas: 1
  selector:
    k8s-app: kube-dns
    version: v3
  template:
    metadata:
      labels:
        k8s-app: kube-dns
        version: v3
        kubernetes.io/cluster-service: "true"
    spec:
      containers:
      - name: etcd
        image: gcr.io/google_containers/etcd:2.0.9
        command:
        - /usr/local/bin/etcd
        - -listen-client-urls
        - http://127.0.0.1:2379,http://127.0.0.1:4001
        - -advertise-client-urls
        - http://127.0.0.1:2379,http://127.0.0.1:4001
        - -initial-cluster-token
        - skydns-etcd
      - name: kube2sky
        image: gcr.io/google_containers/kube2sky:1.9
        args:
        # command = "/kube2sky"
        - -domain=kube.local
        - -kubecfg_file=/etc/dns_token/kubeconfig
        volumeMounts:
        - mountPath: /etc/dns_token
          name: dns-token
          readOnly: true
      - name: skydns
        image: gcr.io/google_containers/skydns:2015-03-11-001
        args:
        # command = "/skydns"
        - -machines=http://localhost:4001
        - -addr=0.0.0.0:53
        - -domain=kube.local.
        ports:
        - containerPort: 53
          name: dns
          protocol: UDP
        - containerPort: 53
          name: dns-tcp
          protocol: TCP
        livenessProbe:
          exec:
            command:
            - /bin/sh
            - -c
            - nslookup kubernetes.default.kube.local localhost >/dev/null
          initialDelaySeconds: 30
          timeoutSeconds: 5
      dnsPolicy: Default  # Don't use cluster DNS.
      volumes:
      - name: dns-token
        secret:
          secretName: token-system-dns
```

**Comment by thockin** [comment] 2015-06-18 22:30
Can't reproduce.  Can you `kubectl exec` into the kube2sky container and poke?  Does /etc/resolv.conf exist?  What does it hold?  What is the file mode on it?  what UID is kube2sky running as?

**Comment by jeffbean** [comment] 2015-06-19 00:49
Permissions are the same on all nodes and master:
```
[root@kube-master-demo ~]# ll /etc/resolv.conf 
-rw-r--r--. 1 root root 69 Jun 18 20:26 /etc/resolv.conf
[root@kube-master-demo ~]# cat /etc/resolv.conf
# Generated by NetworkManager
search pode.local
nameserver 127.0.0.1
```

The process is running as root:
```
[root@kube-node-demo-01 ~]# ps -ef | grep kube2sky
root      1804 10433  0 20:27 ?        00:00:00 /kube2sky -domain=kube.local -kubecfg_file=/etc/dns_token/kubeconfig
```

Sorry for the trouble but I can not seem to get into that container based on the `kubectl exec` help.
```
[root@kube-master-test-01 ~]# kubectl exec kube-dns-v3-utqrr kube2sky ls /etc/
nsenter: failed to execute env: No such file or directory
error: Error executing remote command: Error executing command in container: exit status 1

[root@kube-master-test-01 ~]# kubectl exec kube-dns-v3-utqrr kube2sky ls 
nsenter: failed to execute env: No such file or directory
error: Error executing remote command: Error executing command in container: exit status 1

[root@kube-master-test-01 ~]# kubectl exec kube-dns-v3-utqrr -c kube2sky ls 
env: can't execute 'kube-dns-v3-utqrr': No such file or directory
error: Error executing remote command: Error executing command in container: exit status 127

[root@kube-master-test-01 ~]# kubectl exec kube-dns-v3-utqrr -c kube2sky date
env: can't execute 'kube-dns-v3-utqrr': No such file or directory
error: Error executing remote command: Error executing command in container: exit status 127

[root@kube-master-test-01 ~]# kubectl exec kube-dns-v3-utqrr -c kube2sky cat /etc/resolv.conf
env: can't execute 'kube-dns-v3-utqrr': No such file or directory
error: Error executing remote command: Error executing command in container: exit status 127

[root@kube-master-test-01 ~]# kubectl exec kube-dns-v3-utqrr -c kube2sky -i -t -- bash -il
env: can't execute 'kube-dns-v3-utqrr': No such file or directory

```

**Comment by thockin** [comment] 2015-06-19 00:57
@ncdc for an assist on exec

**Comment by ncdc** [comment] 2015-06-19 01:02
With the `nsenter` exec handler, the container must have `env` installed and in the default `PATH`. v0.19 adds support for different exec handlers, and defaults to Docker's native `exec`, which would get rid of this `env` issue, but v0.19 is required.

**Comment by jeffbean** [comment] 2015-06-20 19:44
I am working to get a working reproduction process that I can share to help figure this out.

**Comment by thockin** [comment] 2015-06-25 00:18
Jeff, I'm going to close this for now - if you have a repro, please reopen ASAP

**Closed by thockin** 2015-06-25 00:18 UTC
Labels: priority/P1, team/cluster

**Comment by EmmEff** [comment] 2015-09-09 13:38
FWIW, I just had the same issue on Atomic:

    [fedora@master-01 ~]$ kubectl version
    Client Version: version.Info{Major:"1", Minor:"1+", GitVersion:"v1.1.0-alpha.0.1588+e44c8e6661c931", GitCommit:"e44c8e6661c931f7fd434911b0d3bca140e1df3a", GitTreeState:"clean"}
    Server Version: version.Info{Major:"1", Minor:"1+", GitVersion:"v1.1.0-alpha.0.1588+e44c8e6661c931", GitCommit:"e44c8e6661c931f7fd434911b0d3bca140e1df3a", GitTreeState:"clean"}

The "permission denied" error was legitimate.  Despite having global read perms and a non-zero size, the root user (including the kube2sky process) was unable to access `/etc/resolv.conf`.  I could not cat the file from a `docker exec` session as `root`.

Given the need to press on and my lacking K8s debugging proficiency, I simply killed the "kube-dns" rc and recreated.  The problem did not recur.

**Comment by thockin** [comment] 2015-09-09 16:17
Weird - if anyone can repro this I want to know.
