### ISSUE TITLE
Consider replacement json marshalling system

### ISSUE THREAD

**Issue by lavalamp** [GoogleCloudPlatform/kubernetes#4872] opened 2015-02-26 21:58 UTC
I thought there was an issue for this, but I can't seem to find it.

Off the top of my head, there's two compelling reasons to consider this:
* Generate errors on finding a disallowed field
* Performance - we spend most of our time marshalling/converting/unmarshalling.

I just ran across this, which may be relevant: https://github.com/rainingclouds/autobindings

**Comment by thockin** [comment] 2015-02-26 22:14
+1

**Comment by thockin** [comment] 2015-02-26 22:15
Do you think this is plausible for 1.0?  Instinct says not/...

**Comment by lavalamp** [comment] 2015-02-26 22:17
IMO, post 1.0.

**Comment by bgrant0607** [comment] 2015-02-28 09:02
Dupe of #3338

**Closed by bgrant0607** 2015-02-28 09:02 UTC
Labels: priority/P2
