### ISSUE TITLE
Kubelet fills up root partition with its logs

### ISSUE THREAD

**Issue by marekbiskup** [GoogleCloudPlatform/kubernetes#10482] opened 2015-06-29 16:47 UTC
```
biskup@e2e-test-biskup-master:~$ ls -lh /var/log/kubelet.log
-rw-r--r-- 1 root root 8.6G Jun 29 16:41 /var/log/kubelet.log
```

```
W0629 09:06:25.698877    2949 status_manager.go:73] Failed to updated pod status: Kubernetes client is nil, skipping pod status updates
W0629 09:06:25.698901    2949 status_manager.go:73] Failed to updated pod status: Kubernetes client is nil, skipping pod status updates
W0629 09:06:25.698909    2949 status_manager.go:73] Failed to updated pod status: Kubernetes client is nil, skipping pod status updates
W0629 09:06:25.698915    2949 status_manager.go:73] Failed to updated pod status: Kubernetes client is nil, skipping pod status updates
W0629 09:06:25.698920    2949 status_manager.go:73] Failed to updated pod status: Kubernetes client is nil, skipping pod status updates
W0629 09:06:25.698925    2949 status_manager.go:73] Failed to updated pod status: Kubernetes client is nil, skipping pod status updates
W0629 09:06:25.698931    2949 status_manager.go:73] Failed to updated pod status: Kubernetes client is nil, skipping pod status updates
W0629 09:06:25.698936    2949 status_manager.go:73] Failed to updated pod status: Kubernetes client is nil, skipping pod status updates
W0629 09:06:25.698941    2949 status_manager.go:73] Failed to updated pod status: Kubernetes client is nil, skipping pod status updates
```

I think it happened after etcd-failure test failed

```
Etcd failure 
  should recover from SIGKILL
  /go/src/github.com/GoogleCloudPlatform/kubernetes/_output/dockerized/go/src/github.com/GoogleCloudPlatform/kubernetes/test/e2e/etcd_failure.go:67
[BeforeEach] Etcd failure
  /go/src/github.com/GoogleCloudPlatform/kubernetes/_output/dockerized/go/src/github.com/GoogleCloudPlatform/kubernetes/test/e2e/etcd_failure.go:47
STEP: Creating a kubernetes client
>>> testContext.KubeConfig: /usr/local/google/home/biskup/.kube/config
STEP: Building a namespace api object
INFO: Waiting up to 2m0s for service account default to be provisioned in ns e2e-tests-etcd-failure-8zda2
INFO: Service account default in ns e2e-tests-etcd-failure-8zda2 found. (46.757466ms)
STEP: Waiting for a default service account to be provisioned in namespace
INFO: Waiting up to 2m0s for service account default to be provisioned in ns e2e-tests-etcd-failure-8zda2
INFO: Service account default in ns e2e-tests-etcd-failure-8zda2 found. (43.391572ms)
STEP: 2015-06-29 12:26:03.73032658 +0200 CEST Creating replication controller baz
INFO: 2015-06-29 12:26:03.785454394 +0200 CEST Created replication controller with name: baz, namespace: e2e-tests-etcd-failure-8zda2, replica count: 1
INFO: 2015-06-29 12:26:13.785705497 +0200 CEST Pods: 1 out of 1 created, 1 running, 0 pending, 0 waiting, 0 inactive, 0 unknown 
[It] should recover from SIGKILL
  /go/src/github.com/GoogleCloudPlatform/kubernetes/_output/dockerized/go/src/github.com/GoogleCloudPlatform/kubernetes/test/e2e/etcd_failure.go:67
STEP: failing etcd
INFO: Using SSH key: /usr/local/google/home/biskup/.ssh/google_compute_engine
INFO: Using SSH key: /usr/local/google/home/biskup/.ssh/google_compute_engine
INFO: Using SSH key: /usr/local/google/home/biskup/.ssh/google_compute_engine
INFO: Using SSH key: /usr/local/google/home/biskup/.ssh/google_compute_engine
INFO: Using SSH key: /usr/local/google/home/biskup/.ssh/google_compute_engine
INFO: Using SSH key: /usr/local/google/home/biskup/.ssh/google_compute_engine
INFO: Using SSH key: /usr/local/google/home/biskup/.ssh/google_compute_engine
INFO: Using SSH key: /usr/local/google/home/biskup/.ssh/google_compute_engine
INFO: Using SSH key: /usr/local/google/home/biskup/.ssh/google_compute_engine
INFO: Using SSH key: /usr/local/google/home/biskup/.ssh/google_compute_engine
INFO: Using SSH key: /usr/local/google/home/biskup/.ssh/google_compute_engine
INFO: Using SSH key: /usr/local/google/home/biskup/.ssh/google_compute_engine
INFO: Using SSH key: /usr/local/google/home/biskup/.ssh/google_compute_engine
INFO: Using SSH key: /usr/local/google/home/biskup/.ssh/google_compute_engine
STEP: assert that the pre-existing replication controller recovers
STEP: deleting pods from existing replication controller
INFO: apiserver returned error, as expected before recovery: 501: All the given peers are not reachable (failed to propose on members [http://127.0.0.1:4001] twice [last error: Get http://127.0.0.1:4001/v2/keys/registry/pods/e2e-tests-etcd-failure-8zda2?quorum=false&recursive=true&sorted=true: dial tcp 127.0.0.1:4001: connection refused]) [0]
INFO: apiserver returned error, as expected before recovery: 501: All the given peers are not reachable (failed to propose on members [http://127.0.0.1:4001] twice [last error: Get http://127.0.0.1:4001/v2/keys/registry/pods/e2e-tests-etcd-failure-8zda2?quorum=false&recursive=true&sorted=true: dial tcp 127.0.0.1:4001: connection refused]) [0]
...
INFO: apiserver returned error, as expected before recovery: 501: All the given peers are not reachable (failed to propose on members [http://127.0.0.1:4001] twice [last error: Get http://127.0.0.1:4001/v2/keys/registry/pods/e2e-tests-etcd-failure-8zda2?quorum=false&recursive=true&sorted=true: dial tcp 127.0.0.1:4001: connection refused]) [0]
[AfterEach] Etcd failure
  /go/src/github.com/GoogleCloudPlatform/kubernetes/_output/dockerized/go/src/github.com/GoogleCloudPlatform/kubernetes/test/e2e/etcd_failure.go:49
STEP: Collecting events from namespace "e2e-tests-etcd-failure-8zda2".

• Failure [61.259 seconds]
Etcd failure
/go/src/github.com/GoogleCloudPlatform/kubernetes/_output/dockerized/go/src/github.com/GoogleCloudPlatform/kubernetes/test/e2e/etcd_failure.go:68
  should recover from SIGKILL [It]
  /go/src/github.com/GoogleCloudPlatform/kubernetes/_output/dockerized/go/src/github.com/GoogleCloudPlatform/kubernetes/test/e2e/etcd_failure.go:67

  Expected error:
      <*errors.errorString | 0xc208029110>: {
          s: "timed out waiting for the condition",
      }
      timed out waiting for the condition
  not to have occurred

  /go/src/github.com/GoogleCloudPlatform/kubernetes/_output/dockerized/go/src/github.com/GoogleCloudPlatform/kubernetes/test/e2e/etcd_failure.go:139
------------------------------
```
All other tests than failed

Kubelet logs just before it started repeating the same message over and over again:
```
I0629 09:06:25.200069    2949 server.go:623] Started kubelet
E0629 09:06:25.200281    2949 kubelet.go:677] Image garbage collection failed: unable to find data for container /
W0629 09:06:25.200302    2949 kubelet.go:688] No api server defined - no node status update will be sent.
I0629 09:06:25.202776    2949 server.go:63] Starting to listen on 0.0.0.0:10250
I0629 09:06:25.246891    2949 server.go:82] Starting to listen read-only on 0.0.0.0:10255
I0629 09:06:25.255236    2949 kubelet.go:697] Running in container "/kubelet"
I0629 09:06:25.369598    2949 factory.go:234] Registering Docker factory
I0629 09:06:25.369955    2949 factory.go:89] Registering Raw factory
I0629 09:06:25.426357    2949 manager.go:946] Started watching for new ooms in manager
I0629 09:06:25.426412    2949 oomparser.go:199] OOM parser using kernel log file: "/var/log/kern.log"
I0629 09:06:25.452867    2949 manager.go:243] Starting recovery of all containers
I0629 09:06:25.531113    2949 manager.go:248] Recovery completed
I0629 09:06:25.539561    2949 status_manager.go:69] Starting to sync pod status with apiserver
I0629 09:06:25.539580    2949 kubelet.go:1706] Starting kubelet main sync loop.
W0629 09:06:25.562467    2949 status_manager.go:73] Failed to updated pod status: Kubernetes client is nil, skipping pod status updates
```

**Comment by a-robinson** [comment] 2015-06-29 17:24
@bprashanth - looks like #10471 may fix this?

**Comment by bprashanth** [comment] 2015-06-29 17:31
That fix will reduce the noise in the logs of the kubelet on the master (which looks to be the case here). The kubelet can still be quite chatty, so we should rotate that log.

**Comment by dchen1107** [comment] 2015-06-29 18:34
#10471 should fix the issue. Close it.

**Comment by bprashanth** [comment] 2015-06-29 18:35
We should still logrotate! (bug report seems to indicate we don't)

**Comment by a-robinson** [comment] 2015-06-30 05:20
@bprashanth judging by my currently running master's logrotate configuration, we do rotate logs. I'd assume this kubelet was just logging so fast that it filled up the disk before logrotate kicked in.

**Comment by a-robinson** [comment] 2015-06-30 05:23
Yeah, we appear to have logrotate set up to run hourly. If the kubelet was really spamming the logs as quickly as it looks in @marekbiskup's snippet (every few microseconds), it definitely could have filled up the disk in less than an hour.

**Comment by alex-mohr** [comment] 2015-06-30 06:19
This is the Nth "kubelet fills up the disk with log spam" issue.  What kind of regression test do we need to prevent M more of them?

**Comment by dchen1107** [comment] 2015-06-30 23:09
We did have logrotation, but on those bad node, kubelet writes those loggings too quickly before logrotation take action yet.

**Closed** 2015-06-30 23:56 UTC
Labels: priority/P1, team/node
