### ISSUE TITLE
Error from watch

### ISSUE THREAD

**Issue by rrati** [GoogleCloudPlatform/kubernetes#4854] opened 2015-02-26 18:44 UTC
While running large numbers of pods on our kubernetes cluster we are seeing:

replication_controller.go:143] error from watch during sync: 401: The event in requested index is outdated and cleared (the requested history has been cleared [3047769/3039389]) [3048768]

We see this in the replication controller and apiserver logs

**Comment by thockin** [comment] 2015-02-26 19:06
@lavalamp

**Comment by lavalamp** [comment] 2015-02-26 19:24
Will look

**Comment by dchen1107** [comment] 2015-02-26 19:29
I looked at this together with folks from Redhat yesterday. This log is printed as error is misleading since it doesn't cause any real issue. Both replication controller and apiserver already handled such watch error.

**Comment by lavalamp** [comment] 2015-02-26 19:35
When we get this error, we should re-list and try again and everything should Just Work (tm). I will double check that it does that and make a PR to clarify the message in the log.

One additional possibility is that processing the result of the list takes so long that the watch window has expired by the time we're finished. In that case this should degrade to just polling, and the error still shouldn't be a problem.

**Comment by lavalamp** [comment] 2015-02-26 23:32
Actually the replication controller's use of the list/watch pattern is incorrect, although not catastrophically so. I will fix.

**Comment by lavalamp** [comment] 2015-02-27 02:15
Don't like fixing this all the time, so I'm going to do this and #4877 at the same time. About half done.

**Comment by lavalamp** [comment] 2015-03-03 00:40
Reducing priority since these errors are not a problem in practice.

**Comment by lavalamp** [comment] 2015-04-23 23:12
I think this issue is covered by our other performance related issues (e.g., #7162). Additionally, this specific error message shouldn't exist after #6866 is done.

**Comment by fgrzadkowski** [comment] 2015-05-04 11:44
This problem occurs when:
1. Client receives change via watch
2. 1000 other non-interesting changes happen in etcd
3. Watch connection breaks (every 5 min)
4. We try re-establish connection but fail with this error so we need to list all objects again.

As @lavalamp mentioned this doesn't cause any real issues. It will be fixed with new etcd 3.0 api.

Closing as "Working as intended".

**Closed by fgrzadkowski** 2015-05-04 11:44 UTC
Labels: priority/P2, team/master
