### ISSUE TITLE
Kube-api-server does not fall back on to a live etcd node in a etcd cluster configuration.

### ISSUE THREAD

**Issue by tanmaybinaykiya** [GoogleCloudPlatform/kubernetes#7423] opened 2015-04-28 05:08 UTC
I shutdown 2 out of the 3 nodes in an etcd cluster of 3 nodes running on coreos. The kube-api-server was triggered by providing all etcd nodes as arguments. Yet kubectl kept curling a dead etcd node, as opposed to falling back to the live on.

**Comment by davidopp** [comment] 2015-04-28 05:12
Thanks for reporting this. Since it's a dupe of #6559 (as you observed), I'm going to close it, and we can continue the discussion there.

**Closed by davidopp** 2015-04-28 05:12 UTC
