### ISSUE TITLE
e2e networking.go namespaces are not being created

### ISSUE THREAD

**Issue by jayunit100** [GoogleCloudPlatform/kubernetes#6539] opened 2015-04-07 21:34 UTC
odd, but when i run e2e's like `networking.go`, I'm finding that the namespace created by it `nettest-1234` is not listed in `kubectl get namespaces`.

So, does this mean that "get namespaces" doesnt gaurantee to return all namespaces, or is it a bug ? If the former, the spec should be changed.  

This can easily be reproduced from head.

1) run `networking.go`
2) while running, run `watch -n 1 cluster/kubect.sh get namespaces`

And you will only see 'default' in the list.

**Comment by derekwaynecarr** [comment] 2015-04-08 00:35
It should list all namespaces.  

Is e2e cleaning up after itself

Will investigate to see if I can reproduce

**Comment by jayunit100** [comment] 2015-04-08 01:43
hmm .ok thanks ! i'll try to see if i can find a good reproducer.  

also i  can help to  add a e2e test to kubectl for this

**Comment by rrati** [comment] 2015-04-08 17:02
@derekwaynecarr Where does kubectl look for namespaces?  I assume under /registry/namespaces and the namespaces created by the e2e test never get put there.  Pods, events, etc get put under a directory for the namespace but nothing is put under /registry/namespaces.  I assume that is why get namespaces doesn't show them.

**Comment by derekwaynecarr** [comment] 2015-04-08 17:38
@jayunit100 @rrati - kubectl will call the rest api, so ```v1beta3/namespaces```, which will look in etcd under ```/registry/namespaces```.  

i do not know much about networking.go, but it looks like it creates some stuff in the ```default``` namespace, and some other stuff in a ```nettest-*``` namespace.  There is no call that is explicitly creating those namespaces, so the ```NamespaceAutoProvision``` admission control plug-in should create one when getting the request for you.  

Do you know if that admission_control flag is set on your e2e environment for kube-apiserver to include admission_control=NamespaceAutoProvision?

**Comment by derekwaynecarr** [comment] 2015-04-08 17:41
I am updating the issue text to be a little more prescriptive of the scenario since kubectl get namespaces itself works fine, but in the test scenario, the e2e test is not getting the namespace created.

**Comment by jayunit100** [comment] 2015-04-08 17:55
thanks were looking into this

**Comment by jayunit100** [comment] 2015-04-08 18:00
@rrati and @derekwaynecarr have helped me resolve this, with the following config at the end of /etc/kuberentes/apiserver ...

```
admission_control=NamespaceLifecycle,NamespaceAutoProvision,AlwaysAdmit"
``` 

So i guess as follow on we need to make sure the ns exists before proceeding w/ tests in e2es.

**Comment by rrati** [comment] 2015-04-08 18:02
The options should result in the ns being created on the fly, so no need to try to create a head of time.  Not yet anyway

**Comment by derekwaynecarr** [comment] 2015-04-08 18:12
Issue appears resolve,d, closing.

**Closed by derekwaynecarr** 2015-04-08 18:12 UTC
Labels: kind/bug, priority/P1, team/master

**Comment by jayunit100** [comment] 2015-04-08 23:31
confirmed removed and updating test ^ above so that namespace is bootstrapped / killed properly. thanks for helping with this one derek !
