### ISSUE TITLE
Verify Kubernetes with Docker 1.7 RC

### ISSUE THREAD

**Issue by vmarmol** [GoogleCloudPlatform/kubernetes#8918] opened 2015-05-28 15:21 UTC
Looks like the 1.7 RC is out:

https://gist.github.com/vieux/42189ac13129efbadd15

**Comment by dchen1107** [comment] 2015-05-28 18:11
cc/ @bgrant0607 @vishh

**Comment by bgrant0607** [comment] 2015-05-28 21:02
There are big changes in 1.7: networking, volumes, ...  Are there draft release notes somewhere? I didn't see any.

**Comment by dchen1107** [comment] 2015-06-05 20:58
I am taking over this one from Vish and will send out the initial assessment by end of today. @bgrant0607, you can find the pending changelog from this commit:

https://github.com/jfrazelle/docker/blob/51c0f8f1f00dbf4501e847964fb4f967c71e1235/CHANGELOG.md

**Comment by dchen1107** [comment] 2015-06-05 23:00
Ok, I brought up an e2e cluster with docker 1.7.0-rc2, and here are the initial test result:

Summarizing 16 Failures:

[Fail] Density [BeforeEach] [Performance suite] should allow starting 3 pods per node 
/go/src/github.com/GoogleCloudPlatform/kubernetes/_output/dockerized/go/src/github.com/GoogleCloudPlatform/kubernetes/test/e2e/density.go:63

[Fail] Density [BeforeEach] [Performance suite] should allow starting 30 pods per node 
/go/src/github.com/GoogleCloudPlatform/kubernetes/_output/dockerized/go/src/github.com/GoogleCloudPlatform/kubernetes/test/e2e/density.go:63

[Fail] Services [It] should be able to create a functioning external load balancer 
/go/src/github.com/GoogleCloudPlatform/kubernetes/_output/dockerized/go/src/github.com/GoogleCloudPlatform/kubernetes/test/e2e/service.go:272

[Fail] Services [It] should correctly serve identically named services in different namespaces on different external IP addresses 
/go/src/github.com/GoogleCloudPlatform/kubernetes/_output/dockerized/go/src/github.com/GoogleCloudPlatform/kubernetes/test/e2e/service.go:796

[Fail] Secrets [It] should be consumable from pods 
/go/src/github.com/GoogleCloudPlatform/kubernetes/_output/dockerized/go/src/github.com/GoogleCloudPlatform/kubernetes/test/e2e/util.go:645

[Fail] Services [It] should be able to change the type and nodeport settings of a service 
/go/src/github.com/GoogleCloudPlatform/kubernetes/_output/dockerized/go/src/github.com/GoogleCloudPlatform/kubernetes/test/e2e/service.go:413

[Fail] Services [It] should release the load balancer when Type goes from LoadBalancer -> NodePort 
/go/src/github.com/GoogleCloudPlatform/kubernetes/_output/dockerized/go/src/github.com/GoogleCloudPlatform/kubernetes/test/e2e/service.go:542

[Fail] ResizeNodes [AfterEach] should be able to add nodes. 
/go/src/github.com/GoogleCloudPlatform/kubernetes/_output/dockerized/go/src/github.com/GoogleCloudPlatform/kubernetes/test/e2e/resize_nodes.go:241

[Fail] Services [It] should be able to create a functioning NodePort service 
/go/src/github.com/GoogleCloudPlatform/kubernetes/_output/dockerized/go/src/github.com/GoogleCloudPlatform/kubernetes/test/e2e/service.go:1032

[Fail] DNS [It] should provide DNS for services 
/go/src/github.com/GoogleCloudPlatform/kubernetes/_output/dockerized/go/src/github.com/GoogleCloudPlatform/kubernetes/test/e2e/dns.go:138

[Fail] Cluster level logging using Elasticsearch [It] should check that logs from pods on all nodes are ingested into Elasticsearch 
/go/src/github.com/GoogleCloudPlatform/kubernetes/_output/dockerized/go/src/github.com/GoogleCloudPlatform/kubernetes/test/e2e/es_cluster_logging.go:148

[Fail] Networking [It] should function for intra-pod communication 
/go/src/github.com/GoogleCloudPlatform/kubernetes/_output/dockerized/go/src/github.com/GoogleCloudPlatform/kubernetes/test/e2e/networking.go:136

[Fail] ResizeNodes [It] should be able to delete nodes. 
/go/src/github.com/GoogleCloudPlatform/kubernetes/_output/dockerized/go/src/github.com/GoogleCloudPlatform/kubernetes/test/e2e/resize_nodes.go:273

[Fail] SSH [It] should SSH to all nodes and run commands 
/go/src/github.com/GoogleCloudPlatform/kubernetes/_output/dockerized/go/src/github.com/GoogleCloudPlatform/kubernetes/test/e2e/ssh.go:76

[Fail] PreStop [It] should call prestop when killing a pod 
/go/src/github.com/GoogleCloudPlatform/kubernetes/_output/dockerized/go/src/github.com/GoogleCloudPlatform/kubernetes/test/e2e/pre_stop.go:141

[Fail] Pod Disks [It] should schedule a pod w/ a readonly PD on two hosts, then remove both. 
/go/src/github.com/GoogleCloudPlatform/kubernetes/_output/dockerized/go/src/github.com/GoogleCloudPlatform/kubernetes/test/e2e/pd.go:157

Ran 61 of 70 Specs in 7700.197 seconds
FAIL! -- 45 Passed | 16 Failed | 2 Pending | 7 Skipped --- FAIL: TestE2E (7700.63s)
FAIL

Of course some test failures are caused by previous failures, for example: #9345. But things look badly so far. Next step is debugging with one or two failures. Will update with more information later.

**Comment by dchen1107** [comment] 2015-06-05 23:01
My e2e cluster is sync up to commit: 636b40ffa1992815c5063fe8b3f8b9fce67aaf7f and our jerkin e2e test are green.

**Comment by vishh** [comment] 2015-06-05 23:02
v1.7 has networking and volumes changes. So its required to probe the test
failures in detail. Thanks for picking this up Dawn.

**Comment by dchen1107** [comment] 2015-06-05 23:03
@vishh you are right! That is the goal here. :-)

**Comment by dchen1107** [comment] 2015-06-09 00:20
Here are more updates:

1) I analyzed the failures I reported above. The most failures came after failed ResizeNode which leaving one node NotReady. By installing dnsutils, nslookup kubernetes.default.cluster.local on the node without skydns pod failed:

```
# nslookup
> set type=A
> set port=59094
> server 10.240.146.175
Default server: 10.240.146.175
Address: 10.240.146.175#59094
> kubernetes.default.cluster.local
;; connection timed out; no servers could be reached
```

Looks like the node is allocated to a different route caused by ResizeNode which adding and remove nodes.

2) I manually ran ResizeNode, then dns, service, tests many times, all passed. Looks like the failures are transient ones. 

3) Some of above failures are existing flaky tests, I reran all tests by skipping those flaky ones: " --ginkgo.skip=Skipped|Etcd.*SIGKILL|Density.*30\spods|ResizeNode|PD|Elasticsearch|identically\snamed\sservices|external\sload\sbalancer|Services.*Type\sgoes\sfrom|Services.*nodeport\ssettings "

Now only two failures:

[Fail] Density [BeforeEach] [Performance suite] should allow starting 3 pods per node 
/go/src/github.com/GoogleCloudPlatform/kubernetes/_output/dockerized/go/src/github.com/GoogleCloudPlatform/kubernetes/test/e2e/density.go:63

[Fail] Docker Containers [It] should be able to override the image's default command and arguments 
/go/src/github.com/GoogleCloudPlatform/kubernetes/_output/dockerized/go/src/github.com/GoogleCloudPlatform/kubernetes/test/e2e/util.go:645

The density one is a failure on Mkdir in test itself. Will file a separate issue to test.

Still Looking into docker container failure.

**Comment by dchen1107** [comment] 2015-06-10 23:27
Filed https://github.com/docker/docker/pull/13867 to docker, which causes several failures reported above since it takes much longer time to get a node into a ready state. The issue is going to be fixed in docker 1.7 release.

Also observed much higher failure rate with PreStop test with 1.7.0-rc2, which never failed with docker 1.7 from our jenkin-e2e reports. Still investigate it.

**Comment by dchen1107** [comment] 2015-06-11 22:54
docker/docker#13850 is fixed. Also there are some network regression found in rc2 too. Will tested it again with rc3 once it is out (today or tomorrow. )

**Comment by dchen1107** [comment] 2015-06-16 16:35
Had offline chat with @brendandburns. So far both docker issues I filed has a proposed fix, and need to verify them with rc4. But this shouldn't be our 1.0 release blocker. Lower the priority to p2/

**Comment by dchen1107** [comment] 2015-06-26 16:45
I ran validation tests against docker 1.7 yesterday. Several tests are failed due to failed to get token from metadata service. The below is one of examples: @roberthbailey any idea?

$ cluster/kubectl.sh describe services external-lb-test  --namespace=e2e-tests-service-0-gq3qa
Name:			external-lb-test
Labels:			<none>
Selector:		testid=external-lb-test-30e33641-1b90-11e5-9f89-24be050deb0e
Type:			LoadBalancer
IP:			10.0.147.146
Port:			<unnamed>	80/TCP
NodePort:		<unnamed>	31562/TCP
Endpoints:		<none>
Session Affinity:	None
Events:
  FirstSeen				LastSeen			Count	From			SubobjectPath	Reason				Message
  Thu, 25 Jun 2015 16:16:24 -0700	Thu, 25 Jun 2015 16:26:14 -0700	108	{service-controller }			creating loadbalancer failed	Error getting LB for service e2e-tests-service-0-gq3qa/external-lb-test: Get https://www.googleapis.com/compute/v1/projects/golden-system-455/regions/us-central1/forwardingRules/a30e5a17e1b9011e5801942010af0056?alt=json: oauth2/google: can't get a token from the metadata service; not running on GCE
  Thu, 25 Jun 2015 16:16:24 -0700	Thu, 25 Jun 2015 16:26:14 -0700	108	{service-controller }			creating loadbalancer failed	Error getting LB for service e2e-tests-service-0-gq3qa/external-lb-test: Get https://www.googleapis.com/compute/v1/projects/golden-system-455/regions/us-central1/forwardingRules/a30e5a17e1b9011e5801942010af0056?alt=json: oauth2/google: can't get a token from the metadata service; not running on GCE

**Comment by roberthbailey** [comment] 2015-06-26 17:23
@dchen1107 This happens occasionally on GCE when the metadata server isn't behaving properly.

**Comment by dchen1107** [comment] 2015-06-26 18:24
I ran into that issue quite frequently lately with e2e. Anyway, I manually test dns and service, and found a bug / regression from docker 1.7 release: docker/docker/issues/14209

**Closed** 2015-08-12 05:17 UTC
Labels: dependency/docker, priority/P2, team/node
