### ISSUE TITLE
kubelet test is flaky

### ISSUE THREAD

**Issue by bgrant0607** [GoogleCloudPlatform/kubernetes#6490] opened 2015-04-06 22:41 UTC
Appears to deadlock or otherwise hang after a few seconds and then hit the 5-minute timeout.

From start of log:
```
W0406 21:21:50.436464   21680 docker.go:482] found a container with the "k8s" prefix, but too few fields (2): "k8s_unidentified"
...
E0406 21:21:53.397806   21680 server.go:614] Timed out waiting for client to create streams
panic: test timed out after 5m0s
```
followed by stack traces of zillions of goroutines that mostly report being blocked for 4+ minutes.

Recent instances:
https://travis-ci.org/GoogleCloudPlatform/kubernetes/jobs/57351393
https://travis-ci.org/GoogleCloudPlatform/kubernetes/jobs/57389027

cc @dchen1107

**Comment by dchen1107** [comment] 2015-04-07 00:21
I tried to reproduce the issue by run kubelet unittests 200 times (100 for v1beta1, and 100 for v1beta3), but failed to reproduce the issue.

```
$ hack/test-go.sh -i 100 pkg/kubelet/
Running tests for APIVersion: v1beta1
+++ [0406 16:42:23] Running 100 times
+++ [0406 16:42:23] github.com/GoogleCloudPlatform/kubernetes/pkg/kubelet/
...
+++ [0406 16:55:17] 100 / 100 passed
Running tests for APIVersion: v1beta3
+++ [0406 16:55:17] Running 100 times
...
+++ [0406 17:08:11] 100 / 100 passed
```

I poked around, and found the only difference between my local machine and test machine is that I am running go 1.4.2 and test machine is running 1.3 (both failure cases posted by @bgrant0607 are with 1.3.0). I remembered from online I saw a deadlock issue reported against old golang version, but haven't found that issue yet. I will continue trying to reproduce the issue.

**Comment by rjnagal** [comment] 2015-04-07 15:39
Saw this in travis runs too:
https://travis-ci.org/GoogleCloudPlatform/kubernetes/jobs/57428080

**Comment by bgrant0607** [comment] 2015-04-07 15:44
Yes, there have been multiple failures today. Check shippable, also.

**Comment by rjnagal** [comment] 2015-04-07 15:56
FWIW, these are not all kubelet tests failing, but all of them have many kubelet go routines in the trace - mostly stuck in managePodLoop().

**Comment by dchen1107** [comment] 2015-04-07 18:04
I reran a couple of thousands time last night before I leave, and all passed. Yu-Ju just pointed out that the failure posted above by @jnagal is go1.4. Shippable is in a really bad shape today, tons of different tests are failed, which should be handled separately.

**Comment by dchen1107** [comment] 2015-04-07 19:43
Ok, with some hacky debugging message added into kubelet package, even I couldn't reproduce the very failure report here, I made some progress on understanding the issue here. Basically there are two issues:

1) The flaky tests reported here are TestServeExecInContainer. All reports posted here have the same stack trace below:

```
goroutine 364 [chan send, 2 minutes]:
github.com/docker/spdystream.(*idleAwareFramer).WriteFrame(0xc20810d560, 0x7f80bb632478, 0xc208470460, 0x0, 0x0)
	/home/travis/gopath/src/github.com/GoogleCloudPlatform/kubernetes/Godeps/_workspace/src/github.com/docker/spdystream/connection.go:116 +0x18e
github.com/docker/spdystream.(*Stream).WriteData(0xc208377400, 0xc2085b2640, 0x5, 0x8, 0x0, 0x0, 0x0)
	/home/travis/gopath/src/github.com/GoogleCloudPlatform/kubernetes/Godeps/_workspace/src/github.com/docker/spdystream/stream.go:63 +0x389
github.com/docker/spdystream.(*Stream).Write(0xc208377400, 0xc2085b2640, 0x5, 0x8, 0x0, 0x0, 0x0)
	/home/travis/gopath/src/github.com/GoogleCloudPlatform/kubernetes/Godeps/_workspace/src/github.com/docker/spdystream/stream.go:68 +0x78
github.com/GoogleCloudPlatform/kubernetes/pkg/kubelet.TestServeExecInContainer(0xc208038510)
	/home/travis/gopath/src/github.com/GoogleCloudPlatform/kubernetes/_output/local/go/src/github.com/GoogleCloudPlatform/kubernetes/pkg/kubelet/server_test.go:856 +0x1cac
testing.tRunner(0xc208038510, 0x1665e40)
	/usr/local/go/src/pkg/testing/testing.go:422 +0x110
created by testing.RunTests
	/usr/local/go/src/pkg/testing/testing.go:504 +0xb46
```

2) There are tons of goroutines, especially one created for each pod. Kubelet leak those goroutines.

```
I0407 12:40:29.015028   23740 server_test.go:681] ???? BEGINE TestServeExecInContainer with 106 goroutines
I0407 12:40:29.037029   23740 server_test.go:914] ???? ENDING TestServeExecInContainer with 147 goroutines
```
One can see when test initial run, there are 106 goroutines. Test itself create another 41 goroutines, but none of them are created for podWorkder.

**Comment by yujuhong** [comment] 2015-04-07 19:45
FWIW, the tests in server_test.go were creating go routines it didn't need at all. I just removed them in #6527

**Comment by dchen1107** [comment] 2015-04-07 19:54
@yujuhong Thanks for cleanup. Now the number down to 91:

```
I0407 12:50:20.218265   25918 server_test.go:676] ???? BEGINE TestServeExecInContainer with 91 goroutines
I0407 12:50:20.241959   25918 server_test.go:909] ???? ENDING TestServeExecInContainer with 125 goroutines
```

**Comment by dchen1107** [comment] 2015-04-07 23:37
cc/ @ncdc

**Comment by ncdc** [comment] 2015-04-08 00:15
Did something change related to this recently? I haven't heard any flakiness reports for a long time, and now they're starting up again. Any ideas?

**Comment by dchen1107** [comment] 2015-04-08 00:22
I didn't see any changes related to this feature. Actually I even couldn't reproduce it on my desktop. 

Please note that the comment I made above https://github.com/GoogleCloudPlatform/kubernetes/issues/6490#issuecomment-90709952:

all those leftover goroutines are separate issue thought.

**Comment by ncdc** [comment] 2015-04-08 16:19
This has exposed a deadlock in spdystream.

I'll work with @dmcgowan to come up with a fix.

**Comment by ncdc** [comment] 2015-04-08 16:29
Upstream issue https://github.com/docker/spdystream/issues/49

**Comment by quinton-hoole** [comment] 2015-04-08 18:42
Cool ncdc@ !  dchen1107@, by the way, I've run across a few similar bugs recently where their reproducibility hinges mainly on how the test cluster was brought up.  If the test cluster comes up right, then the tests pass 100% forever.  If the cluster comes up bad, the tests fail, sometimes forever.  Were you rerunning your tests against the same test cluster?  Or rebuilding your test cluster between every test invocation?

**Comment by dchen1107** [comment] 2015-04-08 18:58
@quinton-hoole This is unittests, not e2e. We saw test flakiness through travis and shippable, but never on my desktop.

**Comment by ncdc** [comment] 2015-04-09 16:01
This will hopefully fix the deadlock: https://github.com/docker/spdystream/pull/50. I will do a bump commit once it's merged.

**Comment by dchen1107** [comment] 2015-04-09 16:13
@ncdc Thanks for your quick fix. I will clean up goroutines after that.

**Comment by ncdc** [comment] 2015-04-09 16:14
@dchen1107 it's entirely possible there's some bugs in my exec & port forwarding code around leaking goroutines. Are you going to take an initial look to see what's sticking around?

**Comment by dchen1107** [comment] 2015-04-09 16:22
Yes, your test leak some goroutine, but other tests too.

**Closed** 2015-04-09 17:25 UTC
Labels: area/test, priority/P1, team/node
