### ISSUE TITLE
Watch API always returns Waiting for Pod Status

### ISSUE THREAD

**Issue by nathanameye** [GoogleCloudPlatform/kubernetes#4022] opened 2015-02-02 16:20 UTC
The Watch API always returns 'Waiting' for Pod status, but the REST API provides a different value which appears to be accurate (Pending, Running, etc.).

**Comment by ddysher** [comment] 2015-02-03 04:54
This is a known issue, we have a TODO for it:
https://github.com/GoogleCloudPlatform/kubernetes/blob/master/pkg/registry/pod/rest.go#L158

Openshit has some hacks to make it work at client side I think.  /cc @smarterclayton 

In general, our object status strategy is kind of broken.  pod status is cached and periodically updated in master, replication controller status is calculated on demands in storage level, node status is pushed from node controller, etc.  This is a larger issue we need to fix.

**Comment by nathanameye** [comment] 2015-02-03 05:02
Thanks for the update, I hadn't seen the TODO and @brendandburns had asked me to mention it here.

**Comment by bgrant0607** [comment] 2015-02-03 05:48
Dupe of #2726.

**Closed by bgrant0607** 2015-02-03 05:48 UTC
Labels: component/apiserver, kind/bug, priority/P2
