### ISSUE TITLE
The pod status is not changed for approximately 15 minutes after node crash.

### ISSUE THREAD

**Issue by peter-braun** [GoogleCloudPlatform/kubernetes#4160] opened 2015-02-05 13:10 UTC
Setup: 3 nodes, 1 replication controller with a pod having 2 replicas.

    # kubectl get node
    NAME                LABELS              STATUS
    node00              <none>              Ready
    node01              <none>              Ready
    node02              <none>              Ready
    node03              <none>              NotReady
    node04              <none>              NotReady
    
    # kubectl get rc
    CONTROLLER          CONTAINER(S)        IMAGE(S)            SELECTOR                REPLICAS
    blocker             blocker             oam-blocker         run-container=blocker   2
    
    # kubectl get po
    POD                 IP                  CONTAINER(S)        IMAGE(S)            HOST                   LABELS                  STATUS
    blocker-fplln       10.246.1.4          blocker             oam-blocker         node00/192.168.1.100   run-container=blocker   Running
    blocker-gziey       10.246.3.2          blocker             oam-blocker         node02/192.168.1.102   run-container=blocker   Running

I unplug the node at 

    virsh # destroy node02
    Domain node02 destroyed
    
    virsh #
    # date
    Thu Feb  5 12:50:59 CET 2015

Kubenetes realizes that the node has gone in about 30 seconds. But the pod's status remains `Running` for approximately 15 minutes:

    ----- Thu Feb 5 12:51:27 CET 2015 -----
    -- Nodes:
    NAME                LABELS              STATUS
    node00              <none>              Ready
    node01              <none>              Ready
    node02              <none>              Ready
    node03              <none>              NotReady
    node04              <none>              NotReady
    -- Pods:
    POD                 IP                  CONTAINER(S)        IMAGE(S)            HOST                   LABELS                  STATUS
    blocker-fplln       10.246.1.4          blocker             oam-blocker         node00/192.168.1.100   run-container=blocker   Running
    blocker-gziey       10.246.3.2          blocker             oam-blocker         node02/192.168.1.102   run-container=blocker   Running
    ----- Thu Feb 5 12:51:32 CET 2015 -----
    -- Nodes:
    NAME                LABELS              STATUS
    node00              <none>              Ready
    node01              <none>              Ready
    node02              <none>              NotReady
    node03              <none>              NotReady
    node04              <none>              NotReady
    -- Pods:
    POD                 IP                  CONTAINER(S)        IMAGE(S)            HOST                   LABELS                  STATUS
    blocker-fplln       10.246.1.4          blocker             oam-blocker         node00/192.168.1.100   run-container=blocker   Running
    blocker-gziey       10.246.3.2          blocker             oam-blocker         node02/192.168.1.102   run-container=blocker   Running
    
    ...
    
    ----- Thu Feb 5 13:06:28 CET 2015 -----
    -- Nodes:
    NAME                LABELS              STATUS
    node00              <none>              Ready
    node01              <none>              Ready
    node02              <none>              NotReady
    node03              <none>              NotReady
    node04              <none>              NotReady
    -- Pods:
    POD                 IP                  CONTAINER(S)        IMAGE(S)            HOST                   LABELS                  STATUS
    blocker-fplln       10.246.1.4          blocker             oam-blocker         node00/192.168.1.100   run-container=blocker   Running
    blocker-gziey       10.246.3.2          blocker             oam-blocker         node02/192.168.1.102   run-container=blocker   Running
    ----- Thu Feb 5 13:06:33 CET 2015 -----
    -- Nodes:
    NAME                LABELS              STATUS
    node00              <none>              Ready
    node01              <none>              Ready
    node02              <none>              NotReady
    node03              <none>              NotReady
    node04              <none>              NotReady
    -- Pods:
    POD                 IP                  CONTAINER(S)        IMAGE(S)            HOST                   LABELS                  STATUS
    blocker-fplln       10.246.1.4          blocker             oam-blocker         node00/192.168.1.100   run-container=blocker   Running
    blocker-gziey                           blocker             oam-blocker         node02/192.168.1.102   run-container=blocker   Unknown

In my opinion the change of a node's status from `Running` to `Unknown` should immediately make every bound pods' status `Unknown`.

Peter

**Comment by brendandburns** [comment] 2015-02-05 16:27
This is a regression (likely due to some work we did in the pod cache in
the master.)

I will investigate today.

Sorry!
Brendan

**Comment by brendandburns** [comment] 2015-02-09 21:09
I believe that this was fixed with #4169.  Please re-open if it re-occurs.

**Closed by brendandburns** 2015-02-09 21:09 UTC
Labels: kind/bug, priority/P1, team/UX
