### ISSUE TITLE
Networking should function for intra-pod communication e2e test is broken

### ISSUE THREAD

**Issue by roberthbailey** [GoogleCloudPlatform/kubernetes#8326] opened 2015-05-15 17:40 UTC
It's failing on both GCE and GKE-CI. It appears to have broken somewhere around build number 2509/2510 which includes a likely candidate PR (#8278). 

/cc @lavalamp @quinton-hoole @ixdy

**Comment by quinton-hoole** [comment] 2015-05-15 17:44
I was about to debug this one.  I'll take it.

**Comment by quinton-hoole** [comment] 2015-05-15 17:53
Root cause is almost definitely one of these:

Summary

1. Fix secrets example pod (details)
2. Fixing the permissions on python files. (details)
3. Changing the implementation of DeepCopy to use reflection instead of Gob encode/decode. (details)
4. Fix networking test (details)
4. Changing hooks.py back to executable. (details)
6. OOM protected docker processes (-900) (details)
6. Move proxySocket out of proxier.go to proxysocket.go (details)

Commit f614367c6cebe9b70319abf7d0f0797848aa73d8 by @pmorie
Fix secrets example pod
The file was modified	docs/secrets.md

Commit d8b9e2e1847982a86549c0193759922493e694fe by @mbruzek
Fixing the permissions on python files.
The file was modified	cluster/juju/charms/trusty/kubernetes-master/hooks/install.py
The file was modified	cluster/juju/return-node-ips.py
The file was modified	cluster/juju/charms/trusty/kubernetes-master/hooks/hooks.py

Commit 4d031abc1679ccdc6ad0a2b4dd08d8dd71f7fb84 by @krousey
Changing the implementation of DeepCopy to use reflection instead of Gob encode/decode.
The file was added	pkg/api/copy_test.go
The file was modified	pkg/conversion/deep_copy_test.go
The file was modified	pkg/conversion/deep_copy.go

Commit f8207040034097e783ead6882a451989c404a753 by @dbsmith
Fix networking test
The file was modified	contrib/for-tests/network-tester/webserver.go
The file was modified	contrib/for-tests/network-tester/rc.json
The file was modified	test/e2e/networking.go
The file was modified	contrib/for-tests/network-tester/Makefile

Commit 985375e82b80f82426eefafe7d5da99309080e7a by @mbruzek
Changing hooks.py back to executable.
The file was modified	cluster/juju/charms/trusty/kubernetes/hooks/hooks.py

Commit ebbb130af86b1e2ab7a7c0aa1a6a868f64f122d7 by @dawnchen
OOM protected docker processes (-900)
The file was modified	pkg/kubelet/dockertools/manager.go
The file was modified	pkg/util/util.go
The file was modified	pkg/kubelet/container_manager_linux.go

Commit 78d2fda4808d64563cd8c8a8dbaf8200f777b25a by @ben.the.elder
Move proxySocket out of proxier.go to proxysocket.go
Moves proxySocket out of proxier.go to new proxysocket.go in proxy
package in order to start separating proxy logic and implementation and
make proxier more manageable to review.
The file was modified	pkg/proxy/proxier.go
The file was added	pkg/proxy/proxysocket.go

**Comment by quinton-hoole** [comment] 2015-05-15 18:04
Pretty sure it's  commit f820704, so rolling back #8278 now.  cc @lavalamp .

**Comment by quinton-hoole** [comment] 2015-05-15 19:36
The above rollback solved that immediate problem, but now the test, while proceeding healthily, is timing out.  More debugging or optimization required:

Networking 
should function for intra-pod communication
..... [irrelevant stuff deleted] .....
INFO: Proxy status call returned in 4.861944ms
INFO: Attempt 35/60: test still running
INFO: About to make a proxy status call
Build timed out (after 90 minutes). Marking the build as aborted.
Build timed out (after 90 minutes). Marking the build as failed.

Ran 40 of 46 Specs in 5069.444 seconds
FAIL! -- 18 Passed | 0 Failed | 1 Pending | 5 Skipped Build was aborted
Recording test results

**Comment by quinton-hoole** [comment] 2015-05-15 22:47
I'm not entirely sure why, but the test is running normally again, completing consistently in 13 seconds.
Closing this issue for now.

![screen shot 2015-05-15 at 15 45 17](https://cloud.githubusercontent.com/assets/10390785/7663074/9887b8fe-fb19-11e4-84cc-ef39dfc1a611.png)

**Closed by quinton-hoole** 2015-05-15 22:47 UTC
Labels: area/test, priority/P0, team/testing
