### ISSUE TITLE
v1beta3 Silently fails to label a pod if labels is not in metadata

### ISSUE THREAD

**Issue by elibixby** [GoogleCloudPlatform/kubernetes#7677] opened 2015-05-02 20:10 UTC
Should fail on making the call, (or if backwards compatibility is desired, should successfully label the pod).

**Comment by thockin-cc** [comment] 2015-05-04 01:13
This is yet another case of the JSON parser silently ignoring unknown
fields. We should have a canonical bug for this and close all of these as
dups.

**Comment by bgrant0607** [comment] 2015-05-04 20:08
Yes, dupe of #7598. Even --validate doesn't catch this.

**Closed by bgrant0607** 2015-05-04 20:08 UTC
Labels: priority/support, team/UX
