### ISSUE TITLE
Cluster/Kube-up.sh doesnt work for other clouds

### ISSUE THREAD

**Issue by Snesha** [GoogleCloudPlatform/kubernetes#9537] opened 2015-06-10 00:12 UTC
With the latest changes, kube-up now has a requirement on gcloud. 

This breaks all other clouds and even if I do install the SDK, there are further requirements to install docs / set the project etc. Could you please update to allow an alternate path to allow k8s setup for AWS & Azure?

**Comment by roberthbailey** [comment] 2015-06-10 05:10
What gcloud commands is it trying to run? Doing a quick code search I only see gcloud references in the gce / gke directories (and in the phabricator example for firewall rules) so I'm not sure how it would be getting invoked for other providers. 

@justinsb - Can you double check that gcloud isn't needed to provision on AWS?

**Comment by justinsb** [comment] 2015-06-10 16:04
@Snesha happy to look into this for AWS - you definitely shouldn't need gcloud to bring up a cluster on AWS.  (I can't really speak to Azure, but I suspect/hope whatever the issues is with AWS will be the same issue as Azure).

As @roberthbailey I don't see where we would be using gcloud.  It looks like we would use it if you tried to do a kubernetes release, but only Googlers can do that anyway.  Can you please let me know the error you're getting?

**Comment by justinsb** [comment] 2015-07-16 14:38
I'm going to close this; we've made lots of improvements to our docs & these scripts, and I'm guessing these will address the problem.  @Snesha if you can reproduce, please feel free to reopen!

**Closed by justinsb** 2015-07-16 14:38 UTC
Labels: area/platform/aws, kind/support, team/cluster-lifecycle
