### ISSUE TITLE
Proposal: SkyDNS entry per Pod

### ISSUE THREAD

**Issue by yugui** [GoogleCloudPlatform/kubernetes#3243] opened 2015-01-06 07:39 UTC
I propose adding per-pod hostname to the SkyDNS records which kube2sky generates.

# Background
Load-balanced service doesn't fit to a kind of applications which need to directly contact to its peers, e.g. groupcache (https://github.com/golang/groupcache).

More general discussion has been done in #260. But in this issue, I'd like to focus on the direct access to a particular pod in a service but not to discuss generalization of load balancing mechanism.

# Proposal
Suppose that we have a service called "cache" backed with three pods.
This proposal is to add a hostname for each pod in SkyDNS records.
* 1.cache.default.kubernetes.local ==> Pod IP of the first pod
* 2.cache.default.kubernetes.local ==> second pod
* 3.cache.default.kubernetes.local ==> third pod

kube2sky watches boundPods, and it keeps reflecting the latest pod IPs to DNS records.

This is basically same as [a comment by thockin]( https://github.com/GoogleCloudPlatform/kubernetes/issues/260#issuecomment-57671926) in #260, but about hostname but not about IP address.

**Comment by thockin** [comment] 2015-01-06 15:36
We have an open proposal for a similar form of service, rather than pod,
such that the IPs are stable over pod moves, etc.  We just have not gotten
to it yet.

**Comment by bgrant0607** [comment] 2015-01-06 17:41
I'm closing this as a dupe of #260 and/or #1607. Please add your use case to one of those issues. Pods don't and won't have durable names, any more than individual containers do.

**Closed by bgrant0607** 2015-01-06 17:41 UTC
