### ISSUE TITLE
Nodes seem to be updating its status way too frequently

### ISSUE THREAD

**Issue by fabioy** [GoogleCloudPlatform/kubernetes#5864] opened 2015-03-24 18:55 UTC
May be a result of PR #5714. On GCE, the master kube-apiserver.log is flooded with entries like:

I0324 18:53:46.443512    9483 handlers.go:109] GET /api/v1beta1/minions/e2e-test-fabioy-minion-ipwx.c.fabioy-cloud-test-1.internal: (2.978675593s) 200 [[kubelet/v0.10.0 (linux/amd64) kubernetes/9707a94] 10.240.151.207:46823]
I0324 18:53:46.444040    9483 handlers.go:109] GET /api/v1beta1/minions/e2e-test-fabioy-minion-ipwx.c.fabioy-cloud-test-1.internal: (2.979451401s) 200 [[kubelet/v0.10.0 (linux/amd64) kubernetes/9707a94] 10.240.151.207:46800]
I0324 18:53:46.450698    9483 handlers.go:109] PUT /api/v1beta1/minions/e2e-test-fabioy-minion-ipwx.c.fabioy-cloud-test-1.internal: (3.778122997s) 409 [[kubelet/v0.10.0 (linux/amd64) kubernetes/9707a94] 10.240.151.207:41179]
I0324 18:53:46.451696    9483 handlers.go:109] PUT /api/v1beta1/minions/e2e-test-fabioy-minion-ipwx.c.fabioy-cloud-test-1.internal: (3.772748134s) 409 [[kubelet/v0.10.0 (linux/amd64) kubernetes/9707a94] 10.240.151.207:46706]

The log is filling at a rate of hundreds of these types of requests a second (this is during e2e test on GCE). 

At the very least, there should be a rate limiter on how often pods update/fetch their status.

**Comment by fabioy** [comment] 2015-03-24 18:56
@fgrzadkowski, @vmarmol

**Comment by vmarmol** [comment] 2015-03-24 20:03
Taking a look, thanks for reporting @fabioy!

**Comment by vmarmol** [comment] 2015-03-24 20:13
@fabioy these look like node statuses not pod statuses?

**Comment by fabioy** [comment] 2015-03-24 20:20
You're probably right. I couldn't readily tell from the logs.

On Tue, Mar 24, 2015 at 1:14 PM, Victor Marmol <notifications@github.com>
wrote:

> @fabioy <https://github.com/fabioy> these look like node statuses not pod
> statuses?
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/GoogleCloudPlatform/kubernetes/issues/5864#issuecomment-85674518>
> .
>



-- 
*-- Fabio Yeon*

**Comment by vmarmol** [comment] 2015-03-24 20:44
Load-balancing to @dchen1107 :) assigning to you

**Comment by dchen1107** [comment] 2015-03-25 00:53
Found the bug in the code, will sent out fix shortly.

**Comment by dchen1107** [comment] 2015-03-25 16:51
It turns out this is no bug, and it works as intended. Under current design, we treat nodeStatus as heatbeat message:

When kubelet first starts up, it post nodeStatus every 500 millisec for first 2sec for a faster cluster startup. After this, kubelet post nodeStatus every 2sec. NodeController processes those heatbeat messages, and if it missed sequentially continuous 4 heatbeats, it will mark unreachable. 

Above intervals is reasonable to me, but we could tune them though. I am going to close the issue. 

cc/ @ddysher @bgrant0607

**Closed by dchen1107** 2015-03-25 16:51 UTC
Labels: component/kubelet, kind/bug, priority/P1, team/node

**Comment by quinton-hoole** [comment] 2015-03-25 20:11
As an aside, TCP keepalives are a very cheap way to do these sorts of remote heartbeats (all in-kernel).  Then you can potentially do low latency edge-triggered rather than level triggered event reporting.

**Comment by dchen1107** [comment] 2015-03-25 20:16
@quinton-hoole I raised the same point when first introducing nodeStatus as heatbeat. If I remembered it correctly, the answer is that we can evolve it later. @ddysher Correct me if I were wrong here.

**Comment by ddysher** [comment] 2015-03-25 20:55
Based on the log timing, it's just for faster startup, like @dchen1107 said.

As to performance, yes, we wanted to evolve it later (which is 'now').

**Comment by ghodss** [comment] 2015-04-07 05:43
Is there another issue tracking the reduction of these PUTs?

**Comment by ghodss** [comment] 2015-04-07 05:50
Just as a heads up, I started up a completely idle 0.14.2 500 node cluster with an n1-standard-8 instance as the master and the master is completely 100% loaded to the point that 50% of requests return 429 due to node status GET's and PUT's. I know the target 1.0 size is 100 nodes but it would be great to optimize this at least a bit.

**Comment by gmarek** [comment] 2015-04-07 06:05
@wojtek-t @fgrzadkowski

**Comment by wojtek-t** [comment] 2015-04-07 06:24
In my opinion, the first thing that we should do is to increase the "heartbeat duration".
IIUC, the main reason for it is to move the pods that are running on broken machine to another machine in case the machine is unreachable. But I think this case is pretty similar to restarting the pod that failed (e.g. due to crash). However, we are currently examining pods only every 10 seconds. So for me it doesn't give much value to send heartbeat from a node every 2 seconds.
But I also agree that we should probably come up with a better mechanism than sending the whole NodeStatus from Kubelet as a heartbeat.

**Comment by dchen1107** [comment] 2015-04-07 16:42
The issue was filed because we believe there is a bug, but turns out it is config parameters of interval at startup time. To tune the NodeStatus interval and other NodeStatus related performance issues are covered by #5953 and several other issues.

**Comment by dchen1107** [comment] 2015-04-07 16:43
@ghodss  Let's move the discussion to #5953.
