### ISSUE TITLE
Pods being scheduled on shut down machines

### ISSUE THREAD

**Issue by tanmaybinaykiya** [GoogleCloudPlatform/kubernetes#7222] opened 2015-04-23 10:10 UTC
I am running my cluster on aws. The setups has a etcd cluster with 3 etcd nodes, 1 master and 4 minions.
I am running a simple hello-world  nodejs script using docker to test my application. For skydns i am using the steps mentioned [here](https://github.com/GoogleCloudPlatform/kubernetes/blob/ebcc45b11c64d17b589c0592426646c7e977f3c6/cluster/addons/dns/README.md#how-do-i-configure-it]) 

I shutdown all minions, while my master and etcd were running. 
A kubectl get nodes on the master showed that two nodes were not ready and the other two as ready 
    
    core@ip-172-31-24-64 ~ $ ./kubectl get nodes
    NAME           LABELS        STATUS
    172.31.25.11   Schedulable   name=dns      NotReady
    172.31.25.12   Schedulable   name=dns      NotReady
    172.31.26.95   Schedulable   name=minion   Ready
    172.31.27.92   Schedulable   name=minion   Ready
  
**Is it expected that the LABEL for a shut-down node is Schedulable?**
I now scheduled my pods using replicationControllers and created the associated services. One of the pods was scheduled on a "NotReady" node. 
 
     core@ip-172-31-24-64 ~ $ ./kubectl get pods 
     POD               IP           CONTAINER(S)   IMAGE(S)                               HOST            LABELS           STATUS    CREATED
     replicont-0cj5l   172.17.0.4   basicnodejs    basicnodejs   172.31.26.95/    name=replicont   Running   19 minutes
     replicont-gl3wm   172.17.0.4   basicnodejs    basicnodejs   172.31.27.92/    name=replicont   Running   19 minutes
     skydns-1ad74      172.17.0.5   etcd           quay.io/coreos/etcd:latest             172.31.27.92/   name=skydns      Running   18 minutes
                                    kube2sky       kubernetes/kube2sky:1.0                                                           
                                    skydns         kubernetes/skydns:2014-12-23-001                                                  
     skydns-oib7w                   etcd           quay.io/coreos/etcd:latest             172.31.25.12/   name=skydns      Pending   7 minutes
                                    kube2sky       kubernetes/kube2sky:1.0                                                           
                                    skydns         kubernetes/skydns:2014-12-23-001  

I ran a kubectl delete pod on the problematic pod and the new pod was scheduled on another node which is not up. 
I waited for some time(may have been 5-10 minutes) and the pod was rescheduled on a live node. So I killed it and a new one was scheduled on a shutdown node.

**Comment by bprashanth** [comment] 2015-04-23 18:13
The scheduler should filter out nodes that aren't ready

**Comment by rrati** [comment] 2015-05-01 17:17
@bprashanth The scheduler used to filter out nodes that aren't ready when it does its scheduling pass.  If it is no longer doing that then that's a regression from previous functionality.

**Comment by rrati** [comment] 2015-05-01 17:28
@bprashanth The Schedulable label doesn't really mean the node will be scheduled to.  It is a flag the admin can set on the node but the Ready/NotReady status should determine if a node is scheduled to if the flag is Schedulable.

**Comment by bprashanth** [comment] 2015-05-02 00:06
@rrati this bug is about the node condition status being unknown (most likely by the nodecontroller), I suspect @lavalamp is swaped anway so I might as well fix this (feel free to object :).

**Comment by lavalamp** [comment] 2015-05-02 00:11
Yes, the scheduler had a regression (my fault!)-- this is at the top of my list if @bprashanth doesn't steal it.

Schedulable/unschedulable and Ready/NotReady/unknown are two separate features; the scheduler needs to pay attention to both. The latter is currently broken.

**Comment by wojtek-t** [comment] 2015-05-04 07:02
>
Schedulable/unschedulable and Ready/NotReady/unknown are two separate features; the scheduler needs to pay attention to both. The latter is currently broken.

That's true. But the first one should work correctly.

**Comment by wojtek-t** [comment] 2015-05-05 11:17
@bprashanth @lavalamp - are you working on it? If not I can take this tomorrow (I think we should fix it since people are already complaining for it - see #7351)

**Comment by bprashanth** [comment] 2015-05-05 14:28
@wojtek-t yeah sorry for the delay I have a pr, will get some integration tests today. got sidetracked debugging the other e2e scalability failures.

**Comment by lavalamp** [comment] 2015-05-11 20:26
#7668 was merged, this should be fixed.

**Closed by lavalamp** 2015-05-11 20:26 UTC
Labels: priority/P1, team/master
