### ISSUE TITLE
ChooseHostInterface() can choose IPv6 which is not valid for the master

### ISSUE THREAD

**Issue by smarterclayton** [GoogleCloudPlatform/kubernetes#7716] opened 2015-05-04 18:20 UTC
The master sets its endpoints into the 'kubernetes' service, but endpoints can only be IPv4 today.  So ChooseHostInterface() should either not return an IPv6 address, or we should allow endpoints to be IPv6.

**Comment by roberthbailey** [comment] 2015-05-04 18:23
I think that this is likely the cause of #7282.

**Comment by thockin-cc** [comment] 2015-05-04 18:28
I thought that function explicitly checked for v4. @quinton-hoole got any
bandwidth for review?

**Comment by smarterclayton** [comment] 2015-05-04 18:35
It doesn't - and on my mac, it fails to find this address when I add that logic.  Not sure if that's FlagPointToPoint or something:

```
en0: flags=8863<UP,BROADCAST,SMART,RUNNING,SIMPLEX,MULTICAST> mtu 1500
	ether 78:31:c1:b7:60:42 
	inet6 fe80::7a31:c1ff:feb7:6042%en0 prefixlen 64 scopeid 0x4 
	inet 10.192.208.72 netmask 0xfffffc00 broadcast 10.192.211.255
	nd6 options=1<PERFORMNUD>
	media: autoselect
	status: active
```

----- Original Message -----
> I thought that function explicitly checked for v4. @quinton-hoole got any
> bandwidth for review?

**Comment by smarterclayton** [comment] 2015-05-04 18:47
PEBKAC for the issue I mentioned above, #7721 is opened to fix the choice.

**Comment by quinton-hoole** [comment] 2015-05-04 20:20
Yeah, I can take a look at #7721 later this afternoon, just as soon as I've unbroken ELB's :-)
smarterclayton@ let me know if #7721 is more urgent than that.

**Comment by quinton-hoole** [comment] 2015-05-04 20:32
#7721 was smaller than I thought, so committed priority inversion I reviewed  it :-)

**Closed** 2015-05-04 21:09 UTC
Labels: component/apiserver, kind/bug, priority/P1, team/master
