### ISSUE TITLE
shippable recent builds are failing

### ISSUE THREAD

**Issue by mikedanese** [GoogleCloudPlatform/kubernetes#10420] opened 2015-06-26 19:41 UTC
This step: https://github.com/GoogleCloudPlatform/kubernetes/blob/master/shippable.yml#L16-L21

```
source $HOME/.gvm/scripts/gvm;
 if [[ $SHIPPABLE_GO_VERSION == "tip" ]]; then gvm install tip; gvm use tip; fi
 if [[ $SHIPPABLE_GO_VERSION == *release* ]]; then gvm install release; gvm use release; fi
/root/1b9a1da4-6608-422e-ac92-6b887d443ddd.sh: eval: line 92: syntax error in conditional expression
```

https://app.shippable.com/builds/558da4718f3d3c0c00e71d81
https://app.shippable.com/builds/558da12e37e4f10c00f2db55
https://app.shippable.com/builds/558d9eba8f3d3c0c00e6c7e9
https://app.shippable.com/builds/558da2c68f3d3c0c00e70bfb
https://app.shippable.com/builds/558d98178f3d3c0c00e63d42

cc @ric03uec @manishas @ixdy @jlowdermilk

**Comment by manishas** [comment] 2015-06-26 19:43
We'll take a look ASAP. Tagging @avinci

**Comment by bgrant0607** [comment] 2015-06-26 23:22
The last successful build was about 7 hours ago.

**Comment by manishas** [comment] 2015-06-26 23:22
@minedanese Builds on Shuppable should be working now.  Thanks!

**Comment by manishas** [comment] 2015-06-26 23:33
we're looking into this further....

**Comment by avinci** [comment] 2015-06-27 00:43
OK we have 2 issues. We upgraded our backend to run on top Kube. For some reasons our eval scripts started failing and we fixed that. That resolved GO install.

Second, we had put in timeouts to be more aggressive than our prior versions. There was a bug on that one ended up timing out about 10 of Kube builds. We fixed that and now builds are running.

On the latest build https://app.shippable.com/builds/558debfa5b023e0c0087cc74 we are seeing this behavior
* KUBE_TEST_API_VERSIONS="v1",KUBE_TEST_ETCD_PREFIXES="registry" is passing
* KUBE_TEST_API_VERSIONS="v1beta3",KUBE_TEST_ETCD_PREFIXES="kubernetes.io/registry" is failing with this error 
`ResourceVersion:"420", FieldPath:"implicitly required container POD"}): reason: 'started' Started with docker id /k8s_POD.450
F0627 00:33:18.033576 33736 integration.go:880] FAILED: pod never started running timed out waiting for the condition
I0627 00:33:18.565718 33736 kubelet.go:1736] Periodic sync
I0627 00:33:18.791504 33736 kubelet.go:1736] Periodic sync
!!! Error in ./hack/test-integration.sh:49
'"${KUBE_OUTPUT_HOSTBIN}/integration" --v=${LOG_LEVEL} --api-version="$1" --max-concurrency="${KUBE_INTEGRATION_TEST_MAX_CONCURRENCY}"' exited with status 255
Call stack:`

I am not sure if this is our error. Can someone help me with this?

**Comment by mikedanese** [comment] 2015-06-27 00:50
@avinci @manishas Thanks for all your work! We have had a build succeed again so the error you saw may be a flake by our test. I will kick it and see if they problem goes away.

https://app.shippable.com/builds/558dee152799150b00218baf

**Comment by avinci** [comment] 2015-06-27 00:54
awesome. Apologize for the craziness today. We are on Kube 100% now and its a huge upgrade from our poor mans orchestration that we had. Hopefully the timeouts should reduce significantly now :-)

**Comment by bgrant0607** [comment] 2015-06-27 01:45
@avinci Love that you're on Kubernetes. Very cool. 

Given that, it's in our interests to ensure it works well for you. :-)  Was the eval script failure somehow caused by Kubernetes?

**Comment by avinci** [comment] 2015-06-27 01:53
@bgrant0607 It has to do with the version of python and ubuntu we are running. Nothing to do with Kube. But very strange that double quotes and single quotes had the problem...

This surfaced as we had new machines we provisioned for the new versions...

**Comment by mikedanese** [comment] 2015-06-27 03:20
@avinci That is awesome you are using Kubernetes! Kubernetes CI on Kubernetes. Very meta. I see green builds now so I'm closing.

**Comment by mikedanese** [comment] 2015-06-29 01:35
Reopening as many of our builds are still experiencing timeouts. What is the new timeout duration? Are our builds taking to long now that the build timeout has been reduced?

https://app.shippable.com/builds/558ffcdfec761d0b001c8db4
https://app.shippable.com/builds/55904fa5ec761d0b001fdb73
https://app.shippable.com/builds/55909990ec761d0b00217372
https://app.shippable.com/builds/5590942479f14d0b00ead53d

**Comment by avinci** [comment] 2015-06-29 12:17
our timeout patch was reverted due to newer deploys. We have it permanently added now and should not occur. Please let me know if otherwise..

**Comment by mikedanese** [comment] 2015-06-29 17:47
Thanks @avinci. We aren't seeing timeouts this morning but a many of our integration tests are failing which I'm currently trying to debug. The problem could very well be on our side. Were any other configurations changed (e.g. memory_limit reduced)?

**Comment by avinci** [comment] 2015-06-29 17:50
no, we are doing 4GB/2 core..

One thing we are seeing is kubelet is shooting up in CPU util on the host machines. there is a bug I am tracking. Not sure if this has any effect... https://github.com/GoogleCloudPlatform/kubernetes/issues/10451

**Comment by mikedanese** [comment] 2015-06-29 17:53
Okay thanks for info. We will keep digging. cc @dchen1107

**Comment by manishas** [comment] 2015-06-30 04:15
We had to revert back to our old orchestration due to issues similar to #10451 and also https://groups.google.com/forum/#!topic/google-containers/aoWv7wCd4uk

We're debugging further but for now builds should be back to normal. We're watching the builds very closely.

**Comment by avinci** [comment] 2015-06-30 11:26
Currently KUBE is freezing all the running containers on a minion which causes our builds to timeout as they are run only once pods. This happens when kubelet starts to eat up CPU for no reason as described by the bug above...

**Comment by mikedanese** [comment] 2015-06-30 15:42
@avinci thanks for reporting. We are looking into it. what cloud provider are you using, GKE? What version of kubernetes are you running? How much cpu/memory do the nodes have? How many pods usually run per node?

**Comment by avinci** [comment] 2015-06-30 15:44
AWS c4.X8Large I think its 36 cores with 60GB memory and we have a Provisioned IOPS disk of 1TB with 6000io

**Comment by avinci** [comment] 2015-06-30 15:45
We have reverted back to our old systems and kube builds have been running 20mins each mostly green since last 6-8 builds

**Comment by dchen1107** [comment] 2015-06-30 17:29
I updated #10451 which has the same cause as this one. This is known issue because heapster collects /stats too frequently. PR #9809 was merged for v0.20 release should mitigate the issue.

@yujuhong did measurement on today's kubelet, and measurement can be found at https://github.com/GoogleCloudPlatform/kubernetes/issues/10451#issuecomment-117268016

**Comment by avinci** [comment] 2015-06-30 17:31
any idea why this happens?
https://groups.google.com/forum/#!topic/google-containers/aoWv7wCd4uk

**Comment by yujuhong** [comment] 2015-06-30 17:39
> any idea why this happens?
> https://groups.google.com/forum/#!topic/google-containers/aoWv7wCd4uk

@avinci, the error message means that the system was running out of inotify watches. There was some discussion in #7815 related to this topic.

How many containers were you running on the machine?

**Comment by avinci** [comment] 2015-06-30 17:42
We currently are running around 30-40 containers out of which atleast 30% of the containers are Kube containers like pause etc. 

again on c4.x8 machine. we are seeing tons of other scale issues, space not found, not available resources all sorts of just runtime operational issues...

**Comment by mikedanese** [comment] 2015-06-30 17:54
@avinci are you using the aws cloud provider scripts or do you have a custom deployment of kubernetes?

We should maybe increase sysctl limits with salt config. I've seen people run into limits for `fs.inotify.max_user_watches`, `net.ipv4.netfilter.ip_conntrack_max`, `fs.file-max` and ulimit.

**Comment by dchen1107** [comment] 2015-06-30 21:13
@avinci There are two issues reported from the link you were referring at: https://groups.google.com/forum/#!topic/google-containers/aoWv7wCd4uk

1) Both error messages are come from cadvisor. In Kubernetes environment, cadvisor is running as part of kubelet for better integration in the future. 
2) The first one: cadvisor tries to run du to get disk usage of each docker container, and report it as part of per container metrics even kubernetes haven't utilize such information yet. Sometimes du failed due to the race between garbage collecting dead containers and cadvisor queries the stats. Again, we should improve the integration between cadvisor and kubelet in a long run to prevent such race, but cadvisor does handle such failure gracefully today. That error message is just red herrring here.
3) The second one related to inotify. The cadvisor issue is filed at https://github.com/google/cadvisor/issues/703 and fixed by https://github.com/google/cadvisor/pull/726. Kubernetes include such fix through pr: https://github.com/GoogleCloudPlatform/kubernetes/pull/9750, which is in v0.20.X release. 

cc/ @vmarmol and @rjnagal @vishh on cAdvisor. Please correct me if the timeline is wrong.

**Closed** 2015-07-09 17:19 UTC
Labels: area/test, priority/P1, team/testing
