### ISSUE TITLE
kubectl.sh create service crashes unhelpfully

### ISSUE THREAD

**Issue by satnam6502** [GoogleCloudPlatform/kubernetes#4095] opened 2015-02-04 02:30 UTC
```
$../../../cluster/kubectl.sh create -f serve-hostnames-service.yaml
Running: ../../../cluster/../cluster/gce/../../_output/dockerized/bin/linux/amd64/kubectl create -f serve-hostnames-service.yaml
F0203 18:21:01.268562   17955 create.go:78] 
make: *** [create] Error 255
```

serve-hostnames-service.yaml:
```
apiVersion: v1beta1
kind: Service
id: serve-hostnames
containerPort: hostname
port: 9500
labels:
  name: serve-hostnames
selector:
  name: serve-hostnames
createExternalLoadBalancer: true
```

serve-hostnames-rc.yaml:
```
kind: ReplicationController
apiVersion: v1beta1
id: serve-hostnames
namespace: default
desiredState:
  replicas: 5
  replicaSelector:
    name: serve-hostnames
  podTemplate:
   desiredState:
     manifest:
       version: v1beta1
       id: serve-hostnames
       containers:
         - name: serve-hostname
           image: "kubernetes/serve_hostname:1.1"
           ports:
             - name: hostname
               containerPort: 9376
               protocol: TCP
   labels:
      name: serve-hostnames
```

What is running:
```
$ make net
gcloud compute forwarding-rules --project kubernetes-scale describe --region asia-east1 serve-hostnames
IPAddress: 104.155.233.3
IPProtocol: TCP
creationTimestamp: '2015-02-03T18:20:33.774-08:00'
id: '5370661519023167823'
kind: compute#forwardingRule
name: serve-hostnames
portRange: 9500-9500
region: https://www.googleapis.com/compute/v1/projects/kubernetes-scale/regions/asia-east1
selfLink: https://www.googleapis.com/compute/v1/projects/kubernetes-scale/regions/asia-east1/forwardingRules/serve-hostnames
target: https://www.googleapis.com/compute/v1/projects/kubernetes-scale/regions/asia-east1/targetPools/serve-hostnames
satnam@satnam-linux:~/gocode/src/github.com/GoogleCloudPlatform/kubernetes/test/scalability/serve_hostnames$ make
../../../cluster/kubectl.sh get pods
Running: ../../../cluster/../cluster/gce/../../_output/dockerized/bin/linux/amd64/kubectl get pods
POD                                          IP                  CONTAINER(S)            IMAGE(S)                            HOST                                                        LABELS                                   STATUS
elasticsearch-logging-controller-fplln                           elasticsearch-logging   dockerfile/elasticsearch            k50-minion-6.c.kubernetes-scale.internal/                   name=elasticsearch-logging               Unknown
kibana-logging-controller-gziey                                  kibana-logging          kubernetes/kibana:1.0               k50-minion-6.c.kubernetes-scale.internal/                   name=kibana-logging                      Unknown
monitoring-heapster-controller-0133o                             heapster                kubernetes/heapster:v0.6            k50-minion-4.c.kubernetes-scale.internal/                   name=heapster,uses=monitoring-influxdb   Unknown
monitoring-influx-grafana-controller-ls6k1                       influxdb                kubernetes/heapster_influxdb:v0.3   k50-minion-4.c.kubernetes-scale.internal/                   name=influxGrafana                       Unknown
                                                                 grafana                 kubernetes/heapster_grafana:v0.3                                                                                                         
serve-hostnames-t3w5u                        10.244.43.6         serve-hostname          kubernetes/serve_hostname:1.1       k50-minion-44.c.kubernetes-scale.internal/104.155.224.188   name=serve-hostnames                     Running
serve-hostnames-vyvg6                        10.244.34.6         serve-hostname          kubernetes/serve_hostname:1.1       k50-minion-35.c.kubernetes-scale.internal/104.155.239.178   name=serve-hostnames                     Running
serve-hostnames-yd44r                        10.244.0.7          serve-hostname          kubernetes/serve_hostname:1.1       k50-minion-1.c.kubernetes-scale.internal/104.155.232.195    name=serve-hostnames                     Running
serve-hostnames-yv8wh                        10.244.13.6         serve-hostname          kubernetes/serve_hostname:1.1       k50-minion-14.c.kubernetes-scale.internal/104.155.234.52    name=serve-hostnames                     Running
serve-hostnames-zdrpp                        10.244.41.6         serve-hostname          kubernetes/serve_hostname:1.1       k50-minion-42.c.kubernetes-scale.internal/104.155.234.173   name=serve-hostnames                     Running
skydns-oh43e                                                     etcd                    quay.io/coreos/etcd:latest          k50-minion-4.c.kubernetes-scale.internal/                   k8s-app=skydns                           Unknown
                                                                 kube2sky                kubernetes/kube2sky:1.0                                                                                                                  
                                                                 skydns                  kubernetes/skydns:2014-12-23-001                                                                                                         
../../../cluster/kubectl.sh get replicationControllers
Running: ../../../cluster/../cluster/gce/../../_output/dockerized/bin/linux/amd64/kubectl get replicationControllers
CONTROLLER                             CONTAINER(S)            IMAGE(S)                            SELECTOR                     REPLICAS
elasticsearch-logging-controller       elasticsearch-logging   dockerfile/elasticsearch            name=elasticsearch-logging   1
kibana-logging-controller              kibana-logging          kubernetes/kibana:1.0               name=kibana-logging          1
monitoring-heapster-controller         heapster                kubernetes/heapster:v0.6            name=heapster                1
monitoring-influx-grafana-controller   influxdb                kubernetes/heapster_influxdb:v0.3   name=influxGrafana           1
                                       grafana                 kubernetes/heapster_grafana:v0.3                                 
serve-hostnames                        serve-hostname          kubernetes/serve_hostname:1.1       name=serve-hostnames         5
skydns                                 etcd                    quay.io/coreos/etcd:latest          k8s-app=skydns               1
                                       kube2sky                kubernetes/kube2sky:1.0                                          
                                       skydns                  kubernetes/skydns:2014-12-23-001                                 
../../../cluster/kubectl.sh get services
Running: ../../../cluster/../cluster/gce/../../_output/dockerized/bin/linux/amd64/kubectl get services
NAME                    LABELS                                    SELECTOR                     IP                  PORT
elasticsearch-logging   name=elasticsearch-logging                name=elasticsearch-logging   10.0.27.250         9200
kibana-logging          name=kibana-logging                       name=kibana-logging          10.0.36.98          5601
kubernetes              component=apiserver,provider=kubernetes   <none>                       10.0.0.2            443
kubernetes-ro           component=apiserver,provider=kubernetes   <none>                       10.0.0.1            80
monitoring-grafana      <none>                                    name=influxGrafana           10.0.12.41          80
monitoring-heapster     <none>                                    name=heapster                10.0.159.101        80
monitoring-influxdb     <none>                                    name=influxGrafana           10.0.9.170          80
serve-hostnames         name=serve-hostnames                      name=serve-hostnames         10.0.218.217        9500
skydns                  k8s-app=skydns                            k8s-app=skydns               10.0.0.10           53
```

External IP does not work -- perhaps due to the failed create services call?
```
$ make net
gcloud compute forwarding-rules --project kubernetes-scale describe --region asia-east1 serve-hostnames
IPAddress: 104.155.233.3
IPProtocol: TCP
creationTimestamp: '2015-02-03T18:20:33.774-08:00'
id: '5370661519023167823'
kind: compute#forwardingRule
name: serve-hostnames
portRange: 9500-9500
region: https://www.googleapis.com/compute/v1/projects/kubernetes-scale/regions/asia-east1
selfLink: https://www.googleapis.com/compute/v1/projects/kubernetes-scale/regions/asia-east1/forwardingRules/serve-hostnames
target: https://www.googleapis.com/compute/v1/projects/kubernetes-scale/regions/asia-east1/targetPools/serve-hostnames
$ curl 104.155.233.3:9500
curl: (7) Failed to connect to 104.155.233.3 port 9500: Connection refused
```

Port 9500 is open for TCP on the default network. If you exec into one of the containers and speak to the internal service IP then it works fine.

**Comment by bgrant0607** [comment] 2015-02-04 03:18
Hmm. That looks like the err result returned by Visit:
https://github.com/GoogleCloudPlatform/kubernetes/blob/master/pkg/kubectl/cmd/create.go#L78

Maybe an issue with the aggregate error reporting? @thockin

**Comment by satnam6502** [comment] 2015-02-04 03:20
And it seems to be intermittent. The last three times I ran it I found it worked.

**Comment by bgrant0607** [comment] 2015-03-09 21:59
@nikhiljindal Could you please see if you can reproduce this issue?

**Comment by brendandburns** [comment] 2015-03-28 03:40
I can't repro this in 10 tries, I'm closing as obsolete/non-reproducible.  If it re-occurs, please re-open and include logs from the apiserver...

**Closed by brendandburns** 2015-03-28 03:40 UTC
Labels: component/CLI, kind/bug, priority/P1, team/UX
