### ISSUE TITLE
Make the Vagrant cluster creation more reliable and predictable

### ISSUE THREAD

**Issue by roberthbailey** [GoogleCloudPlatform/kubernetes#4302] opened 2015-02-10 23:45 UTC
@arun-gupta  reported a variety of failure modes in #4297.

**Comment by zutherb** [comment] 2015-02-21 16:25
+1

**Comment by sidharta-s** [comment] 2015-02-23 19:48
I figured I'd add to this issue rather than create a new one. I attempted to create a vagrant cluster today (dev tree is up to date) with 1 Master and 1 Minion and the cluster creation is stuck in the 'Validating master' loop ( for over 10 minutes in the validating loop ). salt-master and salt-minion logs seem to be empty ( they don't appear to be running, in fact ). 

```
[vagrant@kubernetes-master ~]$  journalctl -ru salt-master
-- Logs begin at Fri 2013-12-20 13:00:20 UTC, end at Mon 2015-02-23 19:34:40 UTC. --
[vagrant@kubernetes-master ~]$  journalctl -ru salt-minion
-- Logs begin at Fri 2013-12-20 13:00:20 UTC, end at Mon 2015-02-23 19:34:44 UTC. --
[vagrant@kubernetes-master ~]$ ps auxxww | grep salt
vagrant   4987  0.0  0.1 112664   980 pts/0    S+   19:34   0:00 grep --color=auto salt
```

**Comment by sidharta-s** [comment] 2015-02-23 19:53
I still have the cluster running in case anybody wants additional information.

**Comment by sidharta-s** [comment] 2015-02-23 22:37
/cc @derekwaynecarr 

please let me know if there is any other information about my vagrant setup that I need to post here.

**Comment by derekwaynecarr** [comment] 2015-02-24 12:05
I have been working to get more stability in this environment over last few days.  

Can you try again from HEAD after this merges: https://github.com/GoogleCloudPlatform/kubernetes/pull/4754

**Comment by derekwaynecarr** [comment] 2015-02-24 12:07
Can you also verify that you built a release prior to running cluster/Kube-up?

**Comment by sidharta-s** [comment] 2015-02-24 21:23
@derekwaynecarr  yes, I started from scratch and built a release before running cluster/kube-up.sh - cluster/kube-up.sh seems to fail fairly early in case there is no release build available.

**Comment by sidharta-s** [comment] 2015-02-24 21:24
@derekwaynecarr It looks like https://github.com/GoogleCloudPlatform/kubernetes/pull/4754 got merged. I'll try again and get back to you.

**Comment by sidharta-s** [comment] 2015-02-25 22:16
The vagrant cluster seems to come up ( completes master and minion validation ). However, there is new  credentials related error that is showing up at the end of running cluster/kube-up.sh : 

```
_output/dockerized/bin/darwin/amd64/kubectl --kubeconfig=/Users/sseethana/.kubernetes_vagrant_kubeconfig get minions -o template -t {{range.items}}{{.id}}:{{end}}
F0225 13:42:29.259483   97883 get.go:151] crypto/tls: failed to parse certificate PEM data
```

**Comment by ddysher** [comment] 2015-02-27 03:32
I'll add one more problem I've encountered.  Runing from head:
```
Each machine instance has been created/updated.
  Now waiting for the Salt provisioning process to complete on each machine.
  This can take some time based on your network, disk, and cpu speed.
  It is possible for an error to occur during Salt provision of cluster and this could loop forever.
Validating master
Validating minion-1
.............................
Waiting for each minion to be registered with cloud provider
current-context: "vagrant"
Running: hack/../cluster/../cluster/vagrant/../../cluster/../cluster/vagrant/../../_output/dockerized/bin/linux/amd64/kubectl --kubeconfig=/home/deyuan/.kubernetes_vagrant_kubeconfig get minions -o template -t {{range.items}}{{.id}}:{{end}}
F0226 22:28:27.747961   14306 get.go:151] request [&{Method:GET URL:https://10.245.1.2:443/api/v1beta1/minions Proto:HTTP/1.1 ProtoMajor:1 ProtoMinor:1 Header:map[] Body:<nil> ContentLength:0 TransferEncoding:[] Close:false Host:10.245.1.2:443 Form:map[] PostForm:map[] MultipartForm:<nil> Trailer:map[] RemoteAddr: RequestURI: TLS:<nil>}] failed (502) 502 Bad Gateway: <html>
<head><title>502 Bad Gateway</title></head>
<body bgcolor="white">
<center><h1>502 Bad Gateway</h1></center>
<hr><center>nginx/1.4.7</center>
</body>
</html>
```

**Comment by derekwaynecarr** [comment] 2015-02-27 06:04
New to me.  Will investigate more tomorrow.

**Comment by derekwaynecarr** [comment] 2015-02-27 06:05
Also new to me :-) - will see if I can reproduce either.

**Comment by rreinurm** [comment] 2015-02-27 08:41
Your credendials and certificates are not working with new environment. Just delete your .kubernetes_vagrant_* files and recreate the cluster. It would be nice to automate this task, if you tear down the cluster.

**Comment by derekwaynecarr** [comment] 2015-02-27 17:48
I am able to reproduce the 502 Bad Gateway error and am working on determining what changed in order to provide a resolution over the last couple days.  Please assign this issue to me.

**Comment by derekwaynecarr** [comment] 2015-02-27 17:56
The issue appears to me that the kube-apiserver is not getting provisioned by salt correctly.

Parsing Salt logs to determine why.

**Comment by derekwaynecarr** [comment] 2015-02-27 17:57
```shell
kube-apiserver.service - Kubernetes API Server
   Loaded: loaded (/usr/lib/systemd/system/kube-apiserver.service; disabled)
   Active: failed (Result: resources)
     Docs: https://github.com/GoogleCloudPlatform/kubernetes

Feb 27 17:56:33 kubernetes-master systemd[1]: Starting Kubernetes API Server...
Feb 27 17:56:33 kubernetes-master systemd[1]: Failed to load environment files: No such file or directory
Feb 27 17:56:33 kubernetes-master systemd[1]: kube-apiserver.service failed to run 'start' task: No such file or directory
Feb 27 17:56:33 kubernetes-master systemd[1]: Failed to start Kubernetes API Server.
Feb 27 17:56:33 kubernetes-master systemd[1]: Unit kube-apiserver.service entered failed state.
```

**Comment by derekwaynecarr** [comment] 2015-02-27 17:58
```shell
[vagrant@kubernetes-master ~]$ cat /etc/sysconfig/kube-apiserver
cat: /etc/sysconfig/kube-apiserver: No such file or directory
```

Looks like the file is not getting laid down by salt for some reason ;-)

**Comment by derekwaynecarr** [comment] 2015-02-27 18:06
The Jinja template was changed as part of identifying the cluster.

Fixing up now, and will send a PR to close this issue.

```
==> master: kubernetes-master:
==> master: ----------
==> master:           ID: /etc/sysconfig/kube-apiserver
==> master:     Function: file.managed
==> master:       Result: False
==> master:      Comment: Unable to manage file: Jinja variable 'cluster_name' is undefined
==> master:      Started: 18:05:35.643311
==> master:     Duration: 52.049 ms
==> master:      Changes:   
==> master: ----------
==> master:           ID: kube-apiserver
==> master:     Function: service.running
==> master:       Result: False
==> master:      Comment: One or more requisite failed: {'kube-apiserver./etc/sysconfig/kube-apiserver': "Unable to manage file: Jinja variable 'cluster_name' is undefined"}
==> master:      Started
```

**Closed** 2015-02-27 18:42 UTC
Labels: priority/P3, team/cluster-lifecycle

**Comment by sidharta-s** [comment] 2015-02-27 22:29
@rreinurm that was it, thanks!
