### ISSUE TITLE
kubectl UX around namespaces is awkward

### ISSUE THREAD

**Issue by thockin** [GoogleCloudPlatform/kubernetes#10435] opened 2015-06-26 23:27 UTC
```
k --namespace=test get rc test-dns -o yaml | sed 's/foo/bar/' | k update -f -
the namespace from the provided object "test" does not match the namespace "default". You must pass '--namespace=test' to perform this operation.
```

It's very clear what I intended to happen.  I get WHY this is happening (default context) but it's clunky.  Can we do better?

**Comment by bgrant0607** [comment] 2015-06-27 04:32
Dupe of #7789

**Closed by bgrant0607** 2015-06-27 04:32 UTC
Labels: priority/P2, team/UX
