### ISSUE TITLE
Error reporting mirror pods status

### ISSUE THREAD

**Issue by marekbiskup** [GoogleCloudPlatform/kubernetes#8650] opened 2015-05-22 01:11 UTC
```
$ kubectl get pods
(...)
fluentd-elasticsearch-kubernetes-minion-7ewp                                                                                             kubernetes-minion-7ewp/                 <none>                                                                        Pending   Less than a second   
                                                            fluentd-elasticsearch   gcr.io/google_containers/fluentd-elasticsearch:1.5                                                                                                                                   
fluentd-elasticsearch-kubernetes-minion-aizq                                                                                             kubernetes-minion-aizq/                 <none>                                                                        Pending   1 seconds   
                                                            fluentd-elasticsearch   gcr.io/google_containers/fluentd-elasticsearch:1.5                                                                                                                                 
(...)  
```

The status is always pending with the created time equal 1s or less than 1s.

The logs from kubelet show these messages at about a second interval:
```
E0522 01:10:23.012618    2893 kubelet.go:1074] Deleting mirror pod "fluentd-elasticsearch-kubernetes-minion-aizq_default" because it is outdated
W0522 01:10:24.217263    2893 status_manager.go:60] Failed to updated pod status: error updating status for pod "fluentd-elasticsearch-kubernetes-minion-aizq": pods "fluentd-elasticsearch-kubernetes-minion-aizq" not found
```

**Comment by derekwaynecarr** [comment] 2015-05-22 01:46
Duplicate of:
https://github.com/GoogleCloudPlatform/kubernetes/issues/8642

**Closed by derekwaynecarr** 2015-05-22 01:46 UTC
