### ISSUE TITLE
kubectl replace requires --force to be useful?

### ISSUE THREAD

**Issue by jlowdermilk** [GoogleCloudPlatform/kubernetes#12352] opened 2015-08-06 18:15 UTC
```
$ kubectl create -f docs/user-guide/pod.yaml
pod "nginx" created

$ cluster/kubectl.sh replace -f docs/user-guide/pod.yaml
The Pod "nginx" is invalid.
spec: invalid value '{Volumes:<nil> Containers:[{Name:nginx Image:nginx Command:<nil> Args:<nil> WorkingDir: Ports:[{Name: HostPort:0 ContainerPort:80 Protocol:TCP HostIP:}] Env:<nil> Resources:{Limits:map[cpu:100m] Requests:map[]} VolumeMounts:<nil> LivenessProbe:<nil> ReadinessProbe:<nil> Lifecycle:<nil> TerminationMessagePath:/dev/termination-log ImagePullPolicy:IfNotPresent SecurityContext:<nil>}] RestartPolicy:Always TerminationGracePeriodSeconds:<nil> ActiveDeadlineSeconds:<nil> DNSPolicy:ClusterFirst NodeSelector:<nil> ServiceAccountName: NodeName: HostNetwork:false ImagePullSecrets:<nil>}': may not update fields other than container.image
```

Is this intended? If `kubectl replace` will only work when `--force` is passed, why is it even an option?

**Comment by nikhiljindal** [comment] 2015-08-06 20:03
cc @caesarxuchao

**Comment by caesarxuchao** [comment] 2015-08-06 21:34
It is the intended behavior. The error message is `may not update fields other than container.image`, this means the config doesn't pass the validation, so the `kubectl replace` failed. I think in the future we will allow user to update other fields, but not now.

`--force` is very different from `kubectl replace`. Under the hood, `kubectl replace` calls etcd's `compareAndSwap` to update a resource. In contrast, `--force` deletes the resource, then creates a new one with the supplied config, it's the same as running `kubectl delete` and then running `kubectl create`.

What I'm more concerned about is the error message you get. Are you running from the HEAD? #12114 should make `kubectl replace` return a more concise error message, which is `may not update fields other than container.image`.

**Comment by jlowdermilk** [comment] 2015-08-06 22:52
> It is the intended behavior. The error message is may not update fields other than container.image, this means the config doesn't pass the validation, so the kubectl replace failed.

It's literally the same config tho; nothing is being changed, so the command should be a no-op, not an invalid update.

And yes, I am running from head. Running with kubectl `1.0.1` the output is
```
Replace failed: may not update fields other than container.image
```
So that's likely a regression.

**Comment by caesarxuchao** [comment] 2015-08-06 23:49
> It's literally the same config tho; nothing is being changed, so the command should be a no-op, not an invalid update.

I don't quite follow. What do you mean by "should be a no-op"?

**Comment by jlowdermilk** [comment] 2015-08-06 23:58
I have `pod.yaml` file which defines the resource I want running in kubernetes. I create it with
```
kubectl create -f pod.yaml
```
I now want to update kubernetes to reflect changes I've made to `pod.yaml`. Now, I haven't actually made any changes, so I would expect the command to print "no changes to make" or something similar. I run
```
kubectl replace -f pod.yaml
```
and get a message saying I can only change the image... but I haven't changed *anything*. This seems like a bug.

**Comment by caesarxuchao** [comment] 2015-08-07 00:02
Oh, I see, that is a bug. Thank you for the explanation. I'll take a look.

About the error message, what I got on my cluster is:
```
Update failedspec: invalid value 'content of spec is not printed out, please refer to the "details"', Details: may not update fields other than container.image
```
which is what I would expect.

**Comment by bgrant0607** [comment] 2015-08-07 22:07
http://kubernetes.io/v1.0/docs/user-guide/managing-deployments.html#in-place-updates-of-resources

**Comment by bgrant0607** [comment] 2015-08-07 22:09
It's not a bug.

**Comment by bgrant0607** [comment] 2015-08-07 22:11
Dupe of #11157

**Comment by jlowdermilk** [comment] 2015-08-07 22:12
If it's not a bug, then my original questions stands: why is `--force` not the default or simply absorbed/removed (i.e. `kubectl replace` always means `kubectl replace --force`) if the command will always fail without it?

**Closed by bgrant0607** 2015-08-07 22:11 UTC
Labels: component/kubectl, kind/friction, team/ux

**Comment by bgrant0607** [comment] 2015-08-07 22:12
It doesn't always fail. You have invalid expectations. Do a get, modify, replace.

**Comment by jlowdermilk** [comment] 2015-08-07 22:15
Ah I see. That warrants a mention in help text, as I incorrectly assumed replace would work with partial schema files. I'll make that change and divert other questions about usefulness of replace to #11157.

**Comment by bgrant0607** [comment] 2015-08-07 22:16
Thanks. If you'd like to help with #1702 or #8263, which will improve user experience in this area, that would be welcome. I'd like to get those into 1.1.

**Comment by caesarxuchao** [comment] 2015-08-07 22:24
Oh, I forgot that you need to fill in all the fields. Sorry @jlowdermilk.
