### ISSUE TITLE
podIP appears twice in pod json

### ISSUE THREAD

**Issue by abonas** [GoogleCloudPlatform/kubernetes#3429] opened 2015-01-13 12:55 UTC
podIP appears twice in the pod json. Once directly under "current state" section, and the second time under "net". Is there a reason for this duplication?

**Comment by jbeda** [comment] 2015-01-13 17:51
Punting to @bgrant0607 wrt API questions.

**Comment by dchen1107** [comment] 2015-01-13 18:10
The same reason I gave in #3427. Kubelet now only reports ContainerStatus. PodStatus / PodCondition is observed at master side based on a set of ContainerStatus. There is no other way to get PodIP except net container.

**Comment by bgrant0607** [comment] 2015-01-13 19:05
@abonas This is a temporary state due to some problems with the implementation.

**Comment by brendandburns** [comment] 2015-02-03 00:30
Closing this since I think it is working as intended (for now)

**Closed by brendandburns** 2015-02-03 00:30 UTC
Labels: api/cluster, api/kubelet, kind/support, priority/P1
