### ISSUE TITLE
REST api - Document usage of 'namespace'

### ISSUE THREAD

**Issue by abonas** [GoogleCloudPlatform/kubernetes#3173] opened 2014-12-30 14:16 UTC
document usage of 'namespace'  attribute - which entities is it relevant to, when different namespaces should be used, can all namespaces be extracted to check what exists on the environment, etc.

**Comment by smarterclayton** [comment] 2015-01-04 18:44
This is a good place to start https://github.com/GoogleCloudPlatform/kubernetes/blob/master/docs/design/namespaces.md

**Comment by abonas** [comment] 2015-01-05 14:03
@smarterclayton indeed a good place to start, thank you.
I didn't find in that document the following (and there's no place to comment there):
1. How can someone create a namespace?  Can it be done via REST? Because creating a pod/service on a namespace should imply that a namespace already exists.
2. Getting a list of all already existing namespaces?
3. should clients specify namespace as an internal attribute of an entity in addition to specifying it in the url? if yes, it's duplication.
4. once an entity was set a namespace - is there a way to move it between namespaces?
5. I am assuming there will be a validation that entities do not communicate cross namespaces? let's say pod belongs to namespace 'default' and service that works with that pod was defined as part of namespace "new_namespace" - that will fail on the service creation?
thank you

**Comment by derekwaynecarr** [comment] 2015-01-05 14:23
A few comments:

1. There is no process to create a namespace.  If policy allows a user to create a pod in a namespace, then the namespace exists, and is allowed to be used.
2. This is not supported yet.  There is some discussion on materializing a namespace in etcd to support this, but right now, this is not the case.
3. The value on the URL is used if not specified in the entity.  If a value in the entity is specified that is different than the URL, an error occurs.  The value in the entity is common to be supplied on update operations.
4. There is no ability to move across namespaces at this time.
5. This is how things work today - if there is a space where that is not happening, its a bug, and feel free to open an issue, I will address.  We plan to add network level isolation in the future.

Thanks!

----- Original Message -----

**Comment by abonas** [comment] 2015-01-05 14:40
@derekwaynecarr  thank you for clarifications.

Regarding  "There is no process to create a namespace. If policy allows a user to create a pod in a namespace, then the namespace exists, and is allowed to be used." - so it means that the namespace must be created upfront (not from REST api) as part of the policy, is that correct?

Regarding "The value in the entity is common to be supplied on update operations" - if the value of namespace is not supported to be updated, then why it should be part of the entity, especially since the update anyway occurs on the specific namespace in the url?

Is namespace as part of url as described in the doc supported only in v3? I am getting 404 on v1 for:
GET http://localhost:8080/api/v1beta1/ns/default/services

**Comment by derekwaynecarr** [comment] 2015-01-05 15:28
There is no explicit creation of a namespace - a namespace is just used when content is assigned to it.

Regarding "The value in the entity is common to be supplied on update operations", it's more an issue on the client flow.

I hope there is no disagreement that we need the namespace in the resource that is returned from the server.  This is a common need for things like the replication controller that do query operations like the following:

1. LIST/WATCH replication controllers across all namespaces
2. For each replication controller X, list pods in X.Namespace  (to do this, the replication controller X needed to have its namespace in the response entity)

Since the object returned has the namespace, it's sensible to think that clients will just mutate that object and PUT it back when making changes, for example, when you update the replication size of a replication controller, you most likely will get the object from the server, change one field, and put it back.  As a result, it will have the namespace on the input request entity.

Regarding "Namespace as part of URL"

It works fine on HEAD now (just confirmed) using Vagrant based env.

If you have a client using v1beta1, it will generate urls of the form http://<server>/api/v1beta1/<resource>?namespace=<namespace>, but the server will accept both formats.  If you have a v1beta3 client, it will generate urls of form http://<server>/api/v1beta3/ns/<namespace>/<resource>

You should be able to curl the following:

curl -k -u vagrant:vagrant https://10.245.1.2/api/v1beta1/ns/default/services
curl -k -u vagrant:vagrant https://10.245.1.2/api/v1beta1/services?namespace=default

Thanks,

----- Original Message -----

**Comment by abonas** [comment] 2015-01-05 16:00
@derekwaynecarr  I am using a hack/local setup, not vagrant

**Comment by derekwaynecarr** [comment] 2015-01-05 18:58
The only thing that would differ is the server location, but it should work fine there as well.

----- Original Message -----

**Comment by abonas** [comment] 2015-01-05 19:04
@derekwaynecarr , if there's no way to list namespaces, how  users are expected to work with urls containing namespaces to get all entities in an environment, or even per namespace without knowing its name? like the use case that you mention - LIST/WATCH replication controllers across all namespaces - I am assuming that at least the LIST is supposed to be a GET operation cross namespaces - how the request should look like?

**Comment by derekwaynecarr** [comment] 2015-01-05 19:09
I am still wrestling with the need to materialize a namespace as an object in our store.  There is an issue where this is being discussed.

I don't think its 100% settled, and I imagine we will ultimately need to support a LIST namespaces API.  

Today, you can list across all namespaces for a particular resource type by just doing:

GET /api/v1beta3/<resource>

will return pods in namespace a, b, c, etc.

----- Original Message -----

**Comment by abonas** [comment] 2015-01-05 19:36
@derekwaynecarr I would say that based on the feature description, it does have to be an object resource for those exact 2 reasons at least:
a. putting it as part of url makes it a resource (versus filtering with it as a query parameter). a resource based on REST is usually representing an entity/independent persisted object.
b. the need to be able to list namespaces (or perhaps add/delete too) in order to be able to use it from REST.

**Comment by thockin** [comment] 2015-01-23 23:00
To clarify point 5 above.  If you create a pod in namespace "foo" and a service in "bar", that service will not find the pod, even if the labels are a match.  Right?

But that is not an error event, it's just an empty result from a selector.

And further, as far as I know there is not network isolation across namespaces - pods can ping each other if they know the right IPs, and pods can consume services in other namespaces if they know the service IPs (which DNS makes easier).

I think this has to be allowed, though perhaps (in the fullness of time) that can be policy based rather than wide open.

**Comment by smarterclayton** [comment] 2015-01-24 00:28
Some of the work Rajat and Mrunal are doing enables namespace based VXLANs with a simple SDN controller on OVS.  In that model, there has to be an admin policy to allow communication across namespaces.  But I think that's orthogonal to this discussion - policy (determined by an admin) is what controls that network segregation.

**Comment by bgrant0607** [comment] 2015-03-05 00:01
Could we get a summary of this discussion into the namespaces doc?

**Comment by derekwaynecarr** [comment] 2015-03-05 00:37
Yes.  Working on documentation updates

**Comment by derekwaynecarr** [comment] 2015-03-20 19:06
The namespaces design doc was updated.  please re-open or ask for clarifications to that doc as needed if you still have questions.

**Closed by derekwaynecarr** 2015-03-20 19:06 UTC
Labels: api/cluster, area/documentation, area/usability, priority/P2, team/UX
