### ISSUE TITLE
New minions cannot be added using kubectl

### ISSUE THREAD

**Issue by kelseyhightower** [GoogleCloudPlatform/kubernetes#8468] opened 2015-05-18 23:56 UTC
Kubernetes: v0.17.0

```
/usr/local/bin/kubectl version
Client Version: version.Info{Major:"0", Minor:"17", GitVersion:"v0.17.0", GitCommit:"82f8bdac06ddfacf493a9ed0fedc85f5ea62ebd5", GitTreeState:"clean"}
Server Version: version.Info{Major:"0", Minor:"17", GitVersion:"v0.17.0", GitCommit:"82f8bdac06ddfacf493a9ed0fedc85f5ea62ebd5", GitTreeState:"clean"}
```

I get the following error when I attempt to register a new minion using kubectl

```
/usr/local/bin/kubectl create -f kube2.c.kubestack.internal 
Error: minion "kube2.c.kubestack.internal" already exists
```

The minon gets created, but the error is wrong because:

Before running the above command the state my k8s cluster looked like the following:

```
/opt/bin/etcdctl ls / --recursive
/registry
/registry/services
/registry/services/specs
/registry/services/specs/default
/registry/services/specs/default/kubernetes
/registry/services/specs/default/kubernetes-ro
/registry/services/endpoints
/registry/services/endpoints/default
/registry/services/endpoints/default/kubernetes
/registry/services/endpoints/default/kubernetes-ro
/registry/events
/registry/events/default
/registry/events/default/kube1.c.kubestack.internal.13df7559eeac779d
/registry/events/default/kube0.c.kubestack.internal.13df755a320e7f30
/registry/events/default/kube2.c.kubestack.internal.13df755e2203a5d4
/registry/events/default/kube4.c.kubestack.internal.13df7599180c069d
/registry/events/default/kube3.c.kubestack.internal.13df759d67f03ec8
/registry/events/default/kube0.c.kubestack.internal.13df75c4d93c4bd1
/registry/events/default/kube1.c.kubestack.internal.13df75cb9a3aefc9
/registry/minions
/registry/minions/kube0.c.kubestack.internal
/registry/minions/kube1.c.kubestack.internal
/registry/ranges
/registry/ranges/serviceips
/registry/namespaces
/registry/namespaces/default
```

**Comment by lavalamp** [comment] 2015-05-19 21:37
How is your node controller configured?

The fact that you've got events for kube2.c.kubestack.internal makes me think something is going on with node controller.

**Comment by bgrant0607** [comment] 2015-05-28 17:24
Could be a consequence of auto-registration -- #6949

**Comment by roberthbailey** [comment] 2015-05-28 18:51
Auto-registration wasn't part of 0.17.0, so that shouldn't affect it.

**Comment by bgrant0607** [comment] 2015-05-28 19:34
@kelseyhightower Are you using v1beta1 or v1beta3, and kind Minion or Node?

**Comment by bgrant0607** [comment] 2015-08-04 04:00
Closing as dupe of #8520

**Closed by bgrant0607** 2015-08-04 04:00 UTC
Labels: priority/P1, team/cluster-lifecycle, team/CSI, team/master
