### ISSUE TITLE
Container.Command should unmarshal from a plain string OR array

### ISSUE THREAD

**Issue by thockin** [GoogleCloudPlatform/kubernetes#1256] opened 2014-09-10 15:46 UTC
This is confusing to users, I think.  We should receive the command field as either an array of strings or as a single string.

e.g. 

    "command": [ "foo" ]

should be the same as 

    "command": "foo"

**Comment by bgrant0607** [comment] 2015-02-05 01:16
Partial dupe of #2316

**Closed by bgrant0607** 2015-02-05 01:16 UTC
Labels: api/cluster, area/usability, priority/P2
