### ISSUE TITLE
Is there any meaning to a service with an empty selector?

### ISSUE THREAD

**Issue by abonas** [GoogleCloudPlatform/kubernetes#3712] opened 2015-01-22 13:26 UTC
For example, kubernetes-ro service appears with empty selector (this service was created by the hack/local cluster)  - is that ok? What meaning such service has if it has no entity to fwd traffic to?

**Comment by thockin** [comment] 2015-01-22 17:30
kubernetes and kubernetes-ro are currently "virtual" - they are not backed
by running pods, but by the master itself.

**Comment by abonas** [comment] 2015-01-22 20:43
@thockin, if that's internal impl, why is it exposed to user?
let's say a client pulls all entities and builds a UI around it. 
then a service with no selector arrives, and it's internal to kube - how the client should know not to present it/touch it? (similar to the "net" container in pods)

**Comment by thockin** [comment] 2015-01-22 20:48
It's exposed exactly FOR users - so they can find the apiserver.  It has a
corresponding Endpoints object, it gets a portal IP and a kube-proxy rule,
and it gets service env vars and a DNS name.

The fact that it is virtual is an implementation detail.  That it exists is
all users should need to know.

**Comment by thockin** [comment] 2015-01-22 20:48
And FWIW, the master components may one day actually be pods...

**Comment by abonas** [comment] 2015-01-22 20:52
@thockin thanks for the explanation. so any general rule how to distinguish kube pods/services from user defined?

**Comment by thockin** [comment] 2015-01-22 20:55
Do we need to distinguish them?  We could add labels, I guess, if it is really important to distinguish them.

@bgrant0607

**Comment by abonas** [comment] 2015-01-22 21:02
sometimes users would want to see only the things they defined and not implementation details of the system.

**Comment by thockin** [comment] 2015-01-22 21:04
One could argue this is why the users should be using labels.  I'm not
against defining labels for "special" stuff, but it's new territory, so we
should enter with caution.

**Comment by brendandburns** [comment] 2015-01-22 21:11
I think the right answer might be to put them in a special "cluster" or
"system" namespace.

**Comment by thockin** [comment] 2015-01-22 21:20
See #3293

If we put them in a "kubernetes" ns, the DNS name would be
kubernetes.kubernetes.kubernetes.local :)

I'm not against segmenting them into a different namespace.  We just need
to decide on what that namespace is called, plumb through that
configuration, decide on compatibility for a short while or not, and decide
if that namespace is "special" or just "different" - i.e. should the
skydns, heapster, etc pods go into this namespace?

**Comment by bgrant0607** [comment] 2015-01-22 21:41
@abonas As @thockin said, the services are there for applications that need to contact the apiserver. Additionally, nil selectors can be used by users to import external services.

Adding labels to the kubernetes services won't help. Users need to manage their objects using labels.

/cc @smarterclayton

**Comment by smarterclayton** [comment] 2015-01-22 21:45
Yeah, lots of consumers will expose "special" services.  IN fact, in many clusters the "special" services will outweigh the unspecial ones.  At this point, the namespace they are in is completely arbitrary, and I think because it is a name, it should be free for the end user to choose where they are surfaced.

**Comment by derekwaynecarr** [comment] 2015-01-22 21:46
Per the proposal here: #3613, I think the ```default``` namespace should continue to hold these services, and they require no special labels.  I sense @abonas comment is made without thinking through what Kubernetes operators do to bootstrap a cluster.  I think it's reasonable that ```default``` namespace holds everything you need to run, and operators may or may not choose to segment their data in other namespaces.  If they want to not see this information, its an exact reason for why they should use their own namespace.  I don't think we need anything new here.

**Comment by thockin** [comment] 2015-01-22 21:49
@smarterclayton - I'm not clear on your meaning.  Did you mean that we
should make the "cluster admin" namespace a config param that everyone
knows about and can be different cluster-to-cluster?  Or did you mean that
default is as arbitrary a name as any other?

I'd be fine moving things out of default into "kube" or "kubernetes" or
"cluster" or something, but I am less convinced that a flag is a good thing.

**Comment by derekwaynecarr** [comment] 2015-01-22 21:50
@thockin - wherever we stick this stuff, it should be the namespace that is initially bootstrapped, which today is ```default```.  I continue to believe that is as good a name as any other.  I do not see a need to do more here.

**Comment by smarterclayton** [comment] 2015-01-22 21:54
I think as soon as you bring naming into the picture, making decisions based on names gets very tricky (what if I want my logging service to be everywhere?).  If there is a magic namespace that exposes things to the rest of the cluster, we should ask whether there's only one magic namespace, or multiple?  Are services supposed to cross namespaces?  It's great that pods can find the master... but that's not the only thing they'll need to find in each namespace.  And baking in special names (or customizable names) into your app code is fragile, because then your code only works inside Kubernetes.

I'm just trying to pump the brakes on special services prior to us designing them... :)

----- Original Message -----

**Comment by thockin** [comment] 2015-01-22 21:57
oh, to be clear, I don't want "special" services - I am merely asking if
moving non-user-defined objects (where that is defined very loosely) out of
"default" is worthwhile.  I tend to agree with Derek that it's not worth
energy.

**Comment by erictune** [comment] 2015-01-22 22:41
@smarterclayton agree with you that *lots of consumers will expose "special" services*

We should not use the (namespace + k8s-service + skydns) mechanism for publishing the location of those special services.   We should decouple the choice of namespace to run the pods of the service in from the well-known dns address of special services.  

Otherwise, it will be hard to move the pods of the service to another namespace, which people will definitely want to do as they grow.

Instead, we need a place to publish well-known services which is not tied to the namespace of the pods of that service.

**Comment by thockin** [comment] 2015-01-22 23:11
@etune you open a whole new topic.  I've noodled with the idea of a Name
resource type.  We would generate a Name for each Service as
"service.namespace", but users could also add their own Name resources.

**Comment by abonas** [comment] 2015-01-23 13:04
@bgrant0607  I'd like to understand better your comment regarding nil selectors used to export external services - can you elaborate? give an example? my understanding is that service redirects traffic to pods based on labels. with nil selector service does nothing, so why is it a service in the first place?

@erictune  I'm pro decoupling special services/internal implementation services from user defined entities. whether by separate namespace, or by saying that the default namespace is reserved, or by any other solution. because otherwise internal implementation and user defined content are mixed and that's no good for a proper management.

@simon3z  @itamarh just tagging you so you could see this issue and the related discussions.

**Comment by smarterclayton** [comment] 2015-01-23 15:42
Services abstract backends - they don't have to abstract pods.  Some examples: 

* You want to have an external database cluster in production, but in test you use your own databases.  You would have a service for both and use the environment variables, but the production service has a nil selector with its endpoints set to the database cluster.
* You want to have an empty service because you're reserving a name (that isn't accessible yet) but will be in the future
* You want to point your service to a service in another namespace or on another cluster.  You set the endpoints for your service to the publicIPs of the other service.

----- Original Message -----

**Comment by abonas** [comment] 2015-01-23 20:24
@smarterclayton , thanks.
regarding the last point - I was under impression (based on some other discussion) that there would not be cross namespace interaction? that entities can can access only entities in the same namespace?

**Comment by thockin** [comment] 2015-01-23 20:38
Cross-namespace is currently allowed and I think has to be allowed, though
perhaps (in the fullness of time) that can be policy based rather than wide
open.

**Comment by abonas** [comment] 2015-01-23 22:55
@thockin please see this correspondence. my understanding is that there is isolation
https://github.com/GoogleCloudPlatform/kubernetes/issues/3173#issuecomment-68711242
https://github.com/GoogleCloudPlatform/kubernetes/issues/3173#issuecomment-68713577

**Comment by thockin** [comment] 2015-01-23 23:01
Responded there.  I think there's some less-than-crystal-clear words in
play.

**Comment by brendandburns** [comment] 2015-01-24 04:27
+1 to Eric's comment about ensuring there is a consistent manner for system
services like kubernetes-ro, if that's not fixes for all clusters it's
going to be a nightmare to write reusable containers for multiple different
clusters.

I don't care if we do that by using a constant namespace, or by giving
system services two different names, but there needs to be at least one
name that is constant.

Regarding default vs. cluster namespace, I think the issue is one of
clutter as a user is starting to understand k8s, you turn up a new cluster,
launch a pod, or service, and it's hard to find your one object on the sea
of system created pods and services.  It's visual clutter that confuses
people as they onboard.

**Comment by thockin** [comment] 2015-01-27 06:29
@abonas - can you drop me a line (my github name at google) - I want to ask
you something, and you have no contact info :)

**Comment by rsokolowski** [comment] 2015-03-04 12:34
@brendandburns, sorry for naive question but why would I care as an user that wants to run its existing workload on Kubernetes about kubernetes-ro ? If I write an application that uses kubernetes-ro then I'm locked into Kubernetes.
I understand the need for kubernetes-ro being accessible by cluster level services such as monitoring, logging. I also can imagine that a power user might want to start its own cluster services that use kubernetes-ro. I don't see clearly why would majority of users care about kubernetes-ro being visible from their container. 

I see a reason for the cluster services being visible and accessible for Kubernetes developer, but from an user perspective such services only make the system more complex: why do I see these services (pods,rc) ? are they related to my application ? should I care about them (especially when I use hosted Kubernetes) ? why does my container get all these environment variables for cluster services ?

**Comment by rsokolowski** [comment] 2015-03-04 13:01
I will update service.md file to explain why one would have service without a selector.

**Comment by brendandburns** [comment] 2015-03-04 13:29
Right now, every service goes everywhere for simplicity.  Name spacing and
filtering probably make sense in the long run, but it's not a high priority
for v1.0

Brendan

**Closed** 2015-03-04 18:11 UTC
Labels: api/cluster, area/documentation, area/usability, priority/P2, team/UX
