### ISSUE TITLE
Integration test is flaky due to time out and pods not started

### ISSUE THREAD

**Issue by dchen1107** [GoogleCloudPlatform/kubernetes#4443] opened 2015-02-14 00:27 UTC
Once a while, I saw the failure as the below, and re-run works

F0214 00:24:10.780696     700 integration.go:297] FAILED: pods never started running timed out waiting for the condition
!!! Error in hack/test-integration.sh:47
  '"${KUBE_OUTPUT_HOSTBIN}/integration" --v=2' exited with status 255
Call stack:
  1: hack/test-integration.sh:47 main(...)
Exiting with status 1
+++ Integration test cleanup complete
!!! Error in hack/../build/../build/common.sh:405
  '"${docker_cmd[@]}" "$@"' exited with status 1
Call stack:
  1: hack/../build/../build/common.sh:405 kube::build::run_build_command(...)
  2: hack/../build/release.sh:36 main(...)
Exiting with status 1

**Comment by brendandburns** [comment] 2015-02-14 01:47
Should we try upgrading e2e clusters to n1-standard-1?

**Comment by roberthbailey** [comment] 2015-04-01 04:05
Dupe of #4500.

**Closed by roberthbailey** 2015-04-01 04:05 UTC
Labels: area/test, priority/P1, team/testing
