### ISSUE TITLE
Pods running on a system that kubernetes doesn't know about after replication controller delete

### ISSUE THREAD

**Issue by rrati** [GoogleCloudPlatform/kubernetes#5020] opened 2015-03-04 14:23 UTC
If I create a replication controller with a thousand pods and wait for all those pods to start and use this defer:

defer func () {
 By("Cleaning up the replication controller")
 rc.Spec.Replicas = 0
 if _, err := c.ReplicationControllers(ns).Update(rc); err != nil {
 Failf("Failed to resize replication controller %s to zero: %v", name, err)
 }

// Delete the replication controller.
 if err := c.ReplicationControllers(ns).Delete(name); err != nil {
 Failf("Failed to delete replication controller %s: %v", name, err)
 }
}()

Then I end up with kubernetes having deleted the replication controller, no pods in kubernetes, but there are pods still running on the systems and they never die.

**Comment by erictune** [comment] 2015-03-04 21:07
Deleting a replication controller does not delete its pods.  This is by design.  

The way to do this is the Stop() method  of ReplicationController in pkg/kubectl/stop.go.

**Comment by erictune** [comment] 2015-03-04 21:07
Please feel free to reopen if necessary.

**Comment by rrati** [comment] 2015-03-05 12:57
@erictune Deleting a replication controller and having its pods still in kube is expected, but that's is not what is happening here.  The code sets the replication count to 0 then deletes the controller.  The result of that is that there is no replication controller in kubernetes, nor do any of its pods show up via kubectl.  However, if you inspect the physical systems (via docker) you find numerous pods running from that replication controller.  Kubernetes knows nothing about these pods and the only way to remove them is to stop docker and the kubelet and clean out etcd.

There should never be a case where there are pods running on physical systems started by kubernetes that kubernetes doesn't know about.  In this case I would have expected some or all of the pods from the replication controller to still show up in kubernetes if the replication controller was deleted before it finished killing all the pods.  That wasn't what happened.

**Comment by bgrant0607** [comment] 2015-03-05 15:11
These are failed pods/containers, or are they running? 

Lack of GC of dead containers is a known issue: #157.

@dchen1107

**Comment by rrati** [comment] 2015-03-05 15:17
@bgrant0607 The pods are running on the hosts.

**Comment by dchen1107** [comment] 2015-03-05 17:32
@bgrant0607 I think the issue is not related to GC of dead containers. 

It looks like the pods are running on the node all the time; but after rc set the count to zero, then is removed, pods are still running, and there is no way to view the pods' status from kubectl. Couple of possibilities here:

1) When rc set the count to zero, the pod is not removed. Bug in ReplicaController.
2) ReplicaController does removed pod, but kubelet is not handle it properly. Regression bug in Kubelet. There are several big refactories in kubelet lately. I can quickly verify this.

@rrati, which version are you running here?

**Comment by rrati** [comment] 2015-03-05 17:38
@dchen1107 We are always running against a nightly snapshot of master and we have seen this across multiple versions.  The last test I ran was against this sha:

6f6218cc1edc1d89e582691c5a2f47467f444e3a

**Comment by dchen1107** [comment] 2015-03-05 17:57
I quickly test it, and everything looks fine. Please note that my test didn't stretch the system as mush as your density_test here. I have a cluster with 4 nodes, and start a rc, then resize it to 20, later resize it back to 0. Kubectl shows 0 count of such pods, and I ssh into the node, all containers including POD infrastructure ones are terminated properly.

**Comment by dchen1107** [comment] 2015-03-05 17:59
@rrati what is the node status of kubectl get nodes? Are all of them at Ready or NotReady?

**Comment by rrati** [comment] 2015-03-05 18:08
I saw this running 100 pods/node on 13 minions (so 1300 pods total).  When the delete returns, all pods have been removed from the systems except for a few.  In my last test 8 containers + 8 pause containers (16 total containers) were left running across 2 systems.  I believe this issue gets worse the more systems and pods are involved.

**Comment by bgrant0607** [comment] 2015-03-05 18:31
Do you see the bound pods in etcd? You could use etcdctl to look, or could get /boundpods from apiserver.

**Comment by dchen1107** [comment] 2015-03-05 18:32
@rrati, you are right. 

Could you run etcdctl to check if those pods are still bound to that particular node? command should be: 
```
etcdctl --peers <etcd_ip_and_port> get /registry/nodes/<node_id>/boundpods
```
If those pods are still bound to those two nodes, I think there is an issue in replicaController. Of course, etcd itself could be problem. @saad-ali is running some tests to generate some benchmark for us: #4432

**Comment by dchen1107** [comment] 2015-03-05 18:38
With a little bit load: 4 nodes and 400 pods, I could reproduce the issue. Those removed pods are running on the system, but kubectl get pods shows nothing. I checked etcd, and found those pods are still bound to the nodes. This is a serious bug in the system

**Comment by bgrant0607** [comment] 2015-03-05 18:44
We closed #2794 not because it was fixed, but because the plan is to nuke boundpods #2483.

**Comment by dchen1107** [comment] 2015-03-05 18:47
Yes, this is known issue. Basically it is due to boundPods can get out of sync, and we decided to nuke boundPods completely for v1.0.

**Comment by timothysc** [comment] 2015-03-05 21:06
@dchen1107 do you have details here as to what the root case is?

**Comment by bgrant0607** [comment] 2015-03-06 01:39
Lack of atomic multi-object deletion and lack of a reconciliation loop (or even a retry loop) to deal with cases where the pod was deleted but the boundPod was not.
https://github.com/GoogleCloudPlatform/kubernetes/blob/master/pkg/registry/pod/etcd/etcd.go#L228

**Comment by timothysc** [comment] 2015-03-10 17:04
@rrati  - We should re-eval after: https://github.com/GoogleCloudPlatform/kubernetes/pull/5252 is in.

**Comment by dchen1107** [comment] 2015-03-10 21:25
There are more prs pending to get rid of BoundPods completely, thus we won't run into this out-of-sync on boundpods and pods issue. Should be fixed soon.

**Comment by erictune** [comment] 2015-03-10 22:10
#5252 should not matter.

**Comment by bgrant0607** [comment] 2015-03-12 00:01
No longer writing boundpods as of #5320.

**Comment by bgrant0607** [comment] 2015-03-12 00:02
Assigned to @erictune to close/dedupe.

**Comment by erictune** [comment] 2015-03-12 16:47
@rrati We've deleted boundPods yesterday.  Please reopen if you see this with code built today or later.

**Closed by erictune** 2015-03-12 16:47 UTC
Labels: kind/bug, kind/support, priority/P1, priority/support, team/master
