### ISSUE TITLE
Commit fails on gendocs error

### ISSUE THREAD

**Issue by satnam6502** [GoogleCloudPlatform/kubernetes#4412] opened 2015-02-13 05:52 UTC
This keeps happening to me.

```
$ git commit -m "getlogs"
# github.com/GoogleCloudPlatform/kubernetes/pkg/util
_output/local/go/src/github.com/GoogleCloudPlatform/kubernetes/pkg/util/util.go:81: undefined: glog.ErrorDepth
!!! Error in /Users/satnam/gocode/src/github.com/GoogleCloudPlatform/kubernetes/hack/lib/golang.sh:282
  'go install "${goflags[@]:+${goflags[@]}}" -ldflags "${version_ldflags}" "${binaries[@]}"' exited with status 2
Call stack:
  1: /Users/satnam/gocode/src/github.com/GoogleCloudPlatform/kubernetes/hack/lib/golang.sh:282 kube::golang::build_binaries(...)
  2: /Users/satnam/gocode/src/github.com/GoogleCloudPlatform/kubernetes/hack/build-go.sh:26 main(...)
Exiting with status 1
!!! Error in hack/verify-gendocs.sh:25
  '"${KUBE_ROOT}/hack/build-go.sh" cmd/gendocs' exited with status 1
Call stack:
  1: hack/verify-gendocs.sh:25 main(...)
Exiting with status 1
FAILED: Unresolved errors - aborting the commit.
The message of your attempted commit was:
getlogs

# *** ERROR: *** docs are out of sync between cli and markdown
# run hack/run-gendocs.sh > docs/kubectl.md to regenerate

#
# Your commit will be aborted unless you regenerate docs.
    COMMIT_BLOCKED_ON_GENDOCS

$ hack/run-gendocs.sh > docs/kubectl.md to regenerate
# github.com/GoogleCloudPlatform/kubernetes/pkg/util
_output/local/go/src/github.com/GoogleCloudPlatform/kubernetes/pkg/util/util.go:81: undefined: glog.ErrorDepth
!!! Error in /Users/satnam/gocode/src/github.com/GoogleCloudPlatform/kubernetes/hack/lib/golang.sh:282
  'go install "${goflags[@]:+${goflags[@]}}" -ldflags "${version_ldflags}" "${binaries[@]}"' exited with status 2
Call stack:
  1: /Users/satnam/gocode/src/github.com/GoogleCloudPlatform/kubernetes/hack/lib/golang.sh:282 kube::golang::build_binaries(...)
  2: /Users/satnam/gocode/src/github.com/GoogleCloudPlatform/kubernetes/hack/build-go.sh:26 main(...)
Exiting with status 1
!!! Error in hack/run-gendocs.sh:25
  '"${KUBE_ROOT}/hack/build-go.sh" cmd/gendocs' exited with status 1
Call stack:
  1: hack/run-gendocs.sh:25 main(...)
Exiting with status 1
```

**Comment by satnam6502** [comment] 2015-02-13 06:34
After synching to HEAD, doing a make clean and then a rebuild I get:
```
+++ Building go targets for linux/amd64:
    cmd/kube-proxy
    cmd/kube-apiserver
    cmd/kube-controller-manager
    cmd/kubelet
    plugin/cmd/kube-scheduler
_output/dockerized/go/src/github.com/GoogleCloudPlatform/kubernetes/pkg/master/server/server.go:32:2:
_output/dockerized/go/src/github.com/GoogleCloudPlatform/kubernetes/pkg/apiserver/api_installer.go:20:1: expected 'STRING', found '<<'
_output/dockerized/go/src/github.com/GoogleCloudPlatform/kubernetes/pkg/apiserver/api_installer.go:37:61: expected 'STRING', found 'go'
_output/dockerized/go/src/github.com/GoogleCloudPlatform/kubernetes/pkg/apiserver/api_installer.go:42:1: expected 'STRING', found 'type'
_output/dockerized/go/src/github.com/GoogleCloudPlatform/kubernetes/pkg/apiserver/api_installer.go:52:61: expected 'STRING', found 'go'
_output/dockerized/go/src/github.com/GoogleCloudPlatform/kubernetes/pkg/apiserver/api_installer.go:56:1: expected 'STRING', found 'type'
_output/dockerized/go/src/github.com/GoogleCloudPlatform/kubernetes/pkg/apiserver/api_installer.go:64:1: expected 'STRING', found 'var'
_output/dockerized/go/src/github.com/GoogleCloudPlatform/kubernetes/pkg/apiserver/api_installer.go:67:61: expected 'STRING', found 'go'
_output/dockerized/go/src/github.com/GoogleCloudPlatform/kubernetes/pkg/apiserver/api_installer.go:87:2: expected 'STRING', found 'for'
_output/dockerized/go/src/github.com/GoogleCloudPlatform/kubernetes/pkg/apiserver/api_installer.go:97:2: expected 'STRING', found 'for'
_output/dockerized/go/src/github.com/GoogleCloudPlatform/kubernetes/pkg/apiserver/api_installer.go:98:61: expected 'STRING', found 'go'
_output/dockerized/go/src/github.com/GoogleCloudPlatform/kubernetes/pkg/apiserver/api_installer.go:99:3: expected 'STRING', found 'if'
!!! Error in /go/src/github.com/GoogleCloudPlatform/kubernetes/hack/lib/golang.sh:303
  'go install "${goflags[@]:+${goflags[@]}}" -ldflags "${version_ldflags}" "${binaries[@]}"' exited with status 1
Call stack:
  1: /go/src/github.com/GoogleCloudPlatform/kubernetes/hack/lib/golang.sh:303 kube::golang::build_binaries(...)
  2: hack/build-cross.sh:28 main(...)
Exiting with status 1
!!! Error in /go/src/github.com/GoogleCloudPlatform/kubernetes/hack/lib/golang.sh:238
  '( kube::golang::setup_env; local version_ldflags; version_ldflags=$(kube::version::ldflags); local host_platform; host_platform=$(kube::golang::host_platform); local goflags; eval "goflags=(${KUBE_GOFLAGS:-})"; local use_go_build; local -a targets=(); local arg; for arg in "$@";
do
    if [[ "${arg}" == "--use_go_build" ]]; then
        use_go_build=true;
    else
...
```

**Comment by satnam6502** [comment] 2015-02-13 06:35
I'll just tgz the files on my MBP an email them to myself and unpack them on my work machine and check them in there. But it would be good to know how to become less of a caveman.

**Comment by jlowdermilk** [comment] 2015-02-13 21:39
I've encountered this once myself, and I think @roberthbailey had it happen as well. The time I've seen it happen is when I was running `hack/build-go.sh` in a screen session, which makes me think it's caused by brittle assumptions about gopath/env variables in either our build script or the go linker. It seems like you have a consistent repro though; what sort of dev environment do you hit this error on?

**Comment by satnam6502** [comment] 2015-02-13 21:44
This is working directly on my MacBook Pro.

Satnam

**Comment by brendandburns** [comment] 2015-03-10 23:45
Closing as obsolete.

**Closed by brendandburns** 2015-03-10 23:45 UTC
Labels: priority/support, team/UX
