### ISSUE TITLE
v1beta3 conversion using kube-version-change dropped attribute nodeSelector

### ISSUE THREAD

**Issue by mbforbes** [GoogleCloudPlatform/kubernetes#7800] opened 2015-05-05 21:36 UTC
Reported via "Containers at Google" Google Group:

>I just tried out the kube-version-change, worked for me to convert from v1beta1 to v1beta3.  however, my database landed on the wrong node (minion), digging into i notice that the selector was dropped:
>```
>    nodeSelector: {databasenode: 'true'}
>```
>Here are my nodes:
>```
>    core@yb1 ~/prs $ kubectl get nodes
>    NAME            LABELS              STATUS
>    45.55.192.230   <none>              Ready
>    45.55.192.232   databasenode=true   Ready
>```
>I stuck the nodeSelector in the correct spot in the kube-version-change translated file and ran it again and the pod was created on the correct node.

**Comment by lavalamp** [comment] 2015-05-05 22:42
I cannot reproduce on the below pod. I'll ask for the exact pre-conversion pod in the email thread.

```
apiVersion: v1beta1
desiredState:
  manifest:
    containers:
      - image: nginx
        name: nginx
    id: nginx
    version: v1beta1
id: nginx
kind: Pod
labels:
  env: test
nodeSelector:
  disktype: ssd
```

**Comment by lgfausak** [comment] 2015-05-05 23:56
i note that the file you are showing above is yaml, but, i didn't have any luck with yaml, i had to convert to json, the kube-version-change, then convert back to yaml. when I copy your file, and run it:

    apiVersion: v1beta1
    desiredState:
      manifest:
        containers:
          - image: nginx
            name: nginx
        id: nginx
        version: v1beta1
    id: nginx
    kind: Pod
    labels:
      env: test
    nodeSelector:
      disktype: ssd

then run it:

    gfausak@kube:~/git/lgfausak/k8s/k8s/prs$ kube-version-change -i o.yaml
    2015/05/05 18:42:15 Couldn't decode input: "couldn't get version/kind: invalid character 'a' looking for beginning of value"

so obviously I have a wrong version or I am running the command incorrectly?  I have a yamltojson pipeline:

    jycat o.yaml -t json | kube-version-change | jycat -t yaml

which produces:

    apiVersion: v1beta3
    kind: Pod
    metadata:
      creationTimestamp: null
      labels: {env: test}
      name: nginx
    spec:
      containers:
      - capabilities: {}
        image: nginx
        imagePullPolicy: IfNotPresent
        name: nginx
        resources: {}
        terminationMessagePath: /dev/termination-log
      dnsPolicy: ClusterFirst
      nodeSelector: {disktype: ssd}
      restartPolicy: Always
      volumes: null
    status: {}

that appeared to work for me as well.  Here is my file:

    apiVersion: v1beta1
    id: pg-master-controller
    kind: ReplicationController
    labels:
      name: serving
    desiredState:
      replicas: 1
      replicaSelector:
        name: pg-master
      podTemplate:
        labels:
          name: pg-master
        desiredState:
          manifest:
            nodeSelector:
              databasenode: 'true'
            containers:
            - env:
              - key: WAIT_TYPE
                value: file
              - key: WAIT_FILE
                value: /run/postgresql/ready
              - key: WAIT_TIME
                value: '60'
              image: tacodata/abroute-docker-db:latest
              name: pg-data
              volumeMounts:
              - mountPath: /var/lib/postgresql
                name: pg-data
              - mountPath: /etc/postgresql
                name: pg-conf
              - mountPath: /run/postgresql
                name: pg-run
            - env:
              - key: WAIT_TYPE
                value: file
              - key: WAIT_FILE
                value: /run/postgresql/ready
              - key: WAIT_TIME
                value: '60'
              image: tacodata/abroute-docker-postgres:latest
              name: pg-sql
              ports:
              - containerPort: 5432
                hostPort: 5432
                name: postgres
              volumeMounts:
              - mountPath: /var/lib/postgresql
                name: pg-data
              - mountPath: /etc/postgresql
                name: pg-conf
              - mountPath: /run/postgresql
                name: pg-run
            id: pg-master
            version: v1beta1
            volumes:
            - name: pg-data
            - name: pg-conf
            - name: pg-run

then when I save this as p.yaml and run it through the translation:

    jycat p.yaml -t json | kube-version-change | jycat -t yaml

I get this:

    apiVersion: v1beta3
    kind: ReplicationController
    metadata:
      creationTimestamp: null
      labels: {name: serving}
      name: pg-master-controller
    spec:
      replicas: 1
      selector: {name: pg-master}
      template:
        metadata:
          creationTimestamp: null
          labels: {name: pg-master}
        spec:
          containers:
          - capabilities: {}
            env:
            - {name: WAIT_TYPE, value: file}
            - {name: WAIT_FILE, value: /run/postgresql/ready}
            - {name: WAIT_TIME, value: '60'}
            image: tacodata/abroute-docker-db:latest
            imagePullPolicy: Always
            name: pg-data
            resources: {}
            terminationMessagePath: /dev/termination-log
            volumeMounts:
            - {mountPath: /var/lib/postgresql, name: pg-data}
            - {mountPath: /etc/postgresql, name: pg-conf}
            - {mountPath: /run/postgresql, name: pg-run}
          - capabilities: {}
            env:
            - {name: WAIT_TYPE, value: file}
            - {name: WAIT_FILE, value: /run/postgresql/ready}
            - {name: WAIT_TIME, value: '60'}
            image: tacodata/abroute-docker-postgres:latest
            imagePullPolicy: Always
            name: pg-sql
            ports:
            - {containerPort: 5432, hostPort: 5432, name: postgres, protocol: TCP}
            resources: {}
            terminationMessagePath: /dev/termination-log
            volumeMounts:
            - {mountPath: /var/lib/postgresql, name: pg-data}
            - {mountPath: /etc/postgresql, name: pg-conf}
            - {mountPath: /run/postgresql, name: pg-run}
          dnsPolicy: ClusterFirst
          restartPolicy: Always
          volumes:
          - emptyDir: {medium: ''}
            gcePersistentDisk: null
            gitRepo: null
            glusterfs: null
            hostPath: null
            iscsi: null
            name: pg-data
            nfs: null
            secret: null
          - emptyDir: {medium: ''}
            gcePersistentDisk: null
            gitRepo: null
            glusterfs: null
            hostPath: null
            iscsi: null
            name: pg-conf
            nfs: null
            secret: null
          - emptyDir: {medium: ''}
            gcePersistentDisk: null
            gitRepo: null
            glusterfs: null
            hostPath: null
            iscsi: null
            name: pg-run
            nfs: null
            secret: null
    status: {replicas: 0}

most of what I do I am guessing, so, it wouldn't surprise me to find out I am doing it all wrong :-)  thanks for taking a look at it!

**Comment by lavalamp** [comment] 2015-05-06 00:08
kube-version-change understands yaml, you shouldn't have to convert it to json first. E.g., here's what I did:

```
$ cat tmp.yaml
apiVersion: v1beta1
desiredState:
  manifest:
    containers:
      - image: nginx
        name: nginx
    id: nginx
    version: v1beta1
id: nginx
kind: Pod
labels:
  env: test
nodeSelector:
  disktype: ssd

$ _output/local/bin/linux/amd64/kube-version-change < tmp.yaml 
apiVersion: v1beta3
kind: Pod
metadata:
  creationTimestamp: null
  labels:
    env: test
  name: nginx
spec:
  containers:
  - capabilities: {}
    image: nginx
    imagePullPolicy: IfNotPresent
    name: nginx
    resources: {}
    terminationMessagePath: /dev/termination-log
  dnsPolicy: ClusterFirst
  nodeSelector:
    disktype: ssd
  restartPolicy: Always
  volumes: null
status: {}
```

What version are you running?

**Comment by nikhiljindal** [comment] 2015-05-06 00:08
Doesnt look like you are running the latest kube-version-change.
You should not get
 ```Couldn't decode input: "couldn't get version/kind: invalid character 'a' looking for beginning of value"``` error if you are synced past #6849.

**Comment by lgfausak** [comment] 2015-05-06 00:39
i don't see a version flag for kube-version-change:

    kube-version-change --help 2>&1 | sed 's/^/    /'
    Usage of kube-version-change:
      -i, --input="-": Input source; '-' means stdin
          --log_flush_frequency=5s: Maximum number of seconds between log flushes
      -v, --out-version="v1beta3": Version to convert input to
      -o, --output="-": Output destination; '-' means stdout
      -r, --rewrite="": If nonempty, use this as both input and output.

anyway, you're right, i think i am back a few versions in my source tree.  I cloned:

    git clone https://github.com/GoogleCloudPlatform/kubernetes.git

but I can't get the build to work:

    hack/build-go.sh cmd/kube-version-change

outputs this:

    gfausak@kube:~/git/kubernetes$ hack/build-go.sh cmd/kube-version-change
    +++ [0505 19:34:52] Building go targets for linux/amd64:
        cmd/kube-version-change
    # github.com/GoogleCloudPlatform/kubernetes/pkg/conversion
    _output/local/go/src/github.com/GoogleCloudPlatform/kubernetes/pkg/conversion/deep_copy.go:27: undefined: sync.Pool
    !!! Error in /home/gfausak/git/kubernetes/hack/lib/golang.sh:323
      'go install "${goflags[@]:+${goflags[@]}}" -ldflags "${version_ldflags}" "${nonstatics[@]:+${nonstatics[@]}}"' exited with status 2
    Call stack:
      1: /home/gfausak/git/kubernetes/hack/lib/golang.sh:323 kube::golang::build_binaries_for_platform(...)
      2: /home/gfausak/git/kubernetes/hack/lib/golang.sh:448 kube::golang::build_binaries(...)
      3: hack/build-go.sh:26 main(...)

I know nothing about go, but, it appears I have a missing symbol.  It built this morning (albeit, an older version, probably circa 0.15.0).

At this point should we close this issue.  It appears to be operator error.

**Comment by lavalamp** [comment] 2015-05-06 00:44
Hm, is sync.Pool a go 1.4 only thing? Anyway, sounds good.

**Closed by lavalamp** 2015-05-06 00:44 UTC
Labels: priority/P1, team/UX

**Comment by lgfausak** [comment] 2015-05-06 01:15
I just managed to get a new go, v1.4.2, and compiled the current kubernetes tree with the hack/build-go.sh script above.  That version does work with a yaml file!  BUT, it still drops by nodeSelector when run against the data in the p.yaml file above...

**Comment by mbforbes** [comment] 2015-05-06 01:26
@lgfausak hmm, you're getting different results than @lavalamp running the same command against the same yaml file at HEAD?

**Comment by lgfausak** [comment] 2015-05-06 02:28
I don't know.  I just tried my new kube-version-change against his pod file, that worked (the nodeSelector stays in the yaml output text).  But, with my file, the nodeSelector disappears.  One difference I see with my file is that the 'spec' is nested, in lavalamp's file it isn't.  I don't know if that makes a difference. Here is with my file:

    grep -c nodeSelector p.yaml
    1
    kube-version-change < p.yaml | grep -c nodeSelector
    0

Here is with lavalamp's file:

    grep -c nodeSelector o.yaml
    1
    kube-version-change < o.yaml | grep -c nodeSelector
    1

I think my issues with the yaml vs. json on input was a red herring.

**Comment by lavalamp** [comment] 2015-05-06 18:01
Yes, the nesting level makes a large difference. In v1beta1, nodeSelector is a child of Pod, not of Manifest. https://github.com/GoogleCloudPlatform/kubernetes/blob/master/pkg/api/v1beta1/types.go#L751

If this was scheduling for you as expected previously, it was only accidentally working. (Try `kubectl --create validate` with your original file.)

**Comment by lgfausak** [comment] 2015-05-06 19:52
yup, that was the issue, thanks for following up.
