### ISSUE TITLE
External load balancer creation should be a post-creation "initializer", not inline

### ISSUE THREAD

**Issue by smarterclayton** [GoogleCloudPlatform/kubernetes#5180] opened 2015-03-09 14:32 UTC
As discussed https://github.com/GoogleCloudPlatform/kubernetes/issues/5156 and in other places, the load balancer creation should not be synchronous with resource creation (goes against the "dumb resources" model) but instead be applied by a controller both before and after creation.

**Comment by derekwaynecarr** [comment] 2015-03-09 14:40
+1

**Comment by brendandburns** [comment] 2015-03-13 23:36
I'll take this on.

**Comment by quinton-hoole** [comment] 2015-03-13 23:39
This seems like a duplicate of #5156.  Should we close one of them?

**Comment by quinton-hoole** [comment] 2015-03-17 18:30
@brendandburns Are you actively working on this?  If so, I suggest that we close #5156 as a duplicate.

**Comment by a-robinson** [comment] 2015-03-23 22:30
Should we be adding an entirely new server component for this, along the lines of the kube-scheduler? It feels pretty heavyweight for just this small problem, but could be the start of the cloud-provider controller requested in #5665 (and the first implementation of the initializer concept from #3585).

The shortcut alternative I see would be to add a background goroutine to the apiserver to act as a controller, avoiding the extra operational concerns of adding a new process to the master.

**Comment by quinton-hoole** [comment] 2015-03-23 22:37
I'm happy with the shortcut for now.

**Comment by a-robinson** [comment] 2015-03-23 22:41
I may have spoke too soon, it looks like the node-controller pattern (which uses background goroutines) is a natural one to follow for this. I'll move ahead with that.

**Closed** 2015-04-15 00:50 UTC
Labels: api/cloudprovider, priority/P1, team/cluster

**Comment by smarterclayton** [comment] 2015-04-18 00:30
We still need to make portal ip assignment asynchronous and post creation - since DNS will require a service cache, I'm tempted to conflate it with #6666, or use it to inform the design.  @thockin opinion?

**Comment by thockin** [comment] 2015-04-26 03:29
Yeah, moving IP assignment to be async is probably the best way to handle
multi-master (or use etcd directly?).  That shouldn't matter to kube-proxy
(the wait stream will just have more events)

**Comment by smarterclayton** [comment] 2015-04-26 15:36
> On Apr 25, 2015, at 11:30 PM, Tim Hockin <notifications@github.com> wrote:
> 
> Yeah, moving IP assignment to be async is probably the best way to handle
> multi-master (or use etcd directly?). That shouldn't matter to kube-proxy
> (the wait stream will just have more events)

The use etcd directly seems complex in terms of code (have an object that represents the allocation state and do a CAS to apply it).  Allocation state is either a bit array (w/ bloom filter?) or a more compact representation (prefix tree) stored in etcd.  Could shard in the future.  

The simple singleton controller approach on the other hand is really simple, but races in ha are very dangerous (the rest of our controllers don't have that problem because they're mostly level driven).  But we can always upgrade the controller to do the CAS-allocated-map.  

My pref would be let's get the code out of the apiserver path now, then come back and deal with ha

**Comment by thockin** [comment] 2015-04-26 15:52
Other than HA, what impetus is there for moving it out of line?

**Comment by smarterclayton** [comment] 2015-04-26 15:58
That's the primary reason on my end.  And architectural purity, but purity and $3.25 will get you a cup of coffee.

**Comment by jayunit100** [comment] 2015-09-03 17:43
shall we fix     `return 2 * time.Minute`   in apiserver.go now?
