### ISSUE TITLE
Put load-balancer status messages into service.status.loadBalancer

### ISSUE THREAD

**Issue by thockin** [GoogleCloudPlatform/kubernetes#9308] opened 2015-06-05 06:17 UTC
Currently we have an event for failed LBs, would be nice to put it into the API.

**Comment by bgrant0607** [comment] 2015-06-05 23:14
Dupe of #8992, which you also filed. :-)

**Closed by bgrant0607** 2015-06-05 23:14 UTC
Labels: priority/P2, team/cluster

**Comment by thockin** [comment] 2015-06-06 22:13
Better twice than not at all :)
