### ISSUE TITLE
Regression: mirror pods get deleted and recreated repeated due to spec mismatch

### ISSUE THREAD

**Issue by dchen1107** [GoogleCloudPlatform/kubernetes#8642] opened 2015-05-21 22:51 UTC
During debugging #8637, I noticed that one of services pods: monitoring and logging pods stuck at pending sometimes forever:

```
$ cluster/kubectl.sh get pods --namespace="default"
fluentd-elasticsearch-kubernetes-minion-9q50                                                                                             kubernetes-minion-9q50/                 <none>                                                                        Pending      About an hour   
                                                            fluentd-elasticsearch   gcr.io/google_containers/fluentd-elasticsearch:1.5                                                                                                                                      
...

$ cluster/kubectl.sh get pods -o yaml fluentd-elasticsearch-kubernetes-minion-9q50
apiVersion: v1beta3
kind: Pod
metadata:
  annotations:
    kubernetes.io/config.mirror: mirror
    kubernetes.io/config.source: file
  creationTimestamp: 2015-05-21T21:01:21Z
  name: fluentd-elasticsearch-kubernetes-minion-9q50
  namespace: default
  resourceVersion: "33083"
  selfLink: /api/v1beta3/namespaces/default/pods/fluentd-elasticsearch-kubernetes-minion-9q50
  uid: 884b09be-fffc-11e4-92b6-42010af084a4
spec:
  containers:
  - capabilities: {}
    env:
    - name: FLUENTD_ARGS
      value: -qq
    image: gcr.io/google_containers/fluentd-elasticsearch:1.5
    imagePullPolicy: IfNotPresent
    name: fluentd-elasticsearch
    resources:
      limits:
        cpu: 100m
    securityContext:
      capabilities: {}
      privileged: false
    terminationMessagePath: /dev/termination-log
    volumeMounts:
    - mountPath: /varlog
      name: varlog
    - mountPath: /var/lib/docker/containers
      name: containers
  dnsPolicy: ClusterFirst
  host: kubernetes-minion-9q50
  restartPolicy: Always
  serviceAccount: ""
  volumes:
  - hostPath:
      path: /var/log
    name: varlog
  - hostPath:
      path: /var/lib/docker/containers
    name: containers
status:
  phase: Pending

```

I logged into the node, and found the container is running happily on the node:

```
# docker ps -a | grep fluentd-elasticsearch-kubernetes-minion-9q50
5219fed9570b        gcr.io/google_containers/fluentd-elasticsearch:1.5   "\"/bin/sh -c '/usr/   2 hours ago         Up 2 hours                                     k8s_fluentd-elasticsearch.c99175f6_fluentd-elasticsearch-kubernetes-minion-9q50_default_a8d3815def5de29fd315adf5d9fc5acc_3feacf95   
68e799daa598        gcr.io/google_containers/pause:0.8.0                 "/pause"               2 hours ago         Up 2 hours                                     k8s_POD.e4cc795_fluentd-elasticsearch-kubernetes-minion-9q50_default_a8d3815def5de29fd315adf5d9fc5acc_e6a32500                      
a029f8710c93        gcr.io/google_containers/pause:0.8.0                 "/pause"               2 hours ago                                                        k8s_POD.e4cc795_fluentd-elasticsearch-kubernetes-minion-9q50_default_a8d3815def5de29fd315adf5d9fc5acc_82b1abf7                      
7b7c2c97aa50        gcr.io/google_containers/fluentd-elasticsearch:1.5   "\"/bin/sh -c '/usr/   2 hours ago         Exited (143) 2 hours ago                       k8s_fluentd-elasticsearch.c99175f6_fluentd-elasticsearch-kubernetes-minion-9q50_default_a8d3815def5de29fd315adf5d9fc5acc_f47f189b   
fe98a27d7687        gcr.io/google_containers/pause:0.8.0                 "/pause"               2 hours ago         Exited (0) 2 hours ago                         k8s_POD.e4cc795_fluentd-elasticsearch-kubernetes-minion-9q50_default_a8d3815def5de29fd315adf5d9fc5acc_d4c77781                      

```

Looks like status is never reported from kubelet. I checked kubelet log, then I found:
```
E0521 21:01:18.661917    2486 kubelet.go:1074] Deleting mirror pod "fluentd-elasticsearch-kubernetes-minion-9q50_default" because it is outdated
W0521 21:01:19.175759    2486 status_manager.go:60] Failed to updated pod status: error updating status for pod "fluentd-elasticsearch-kubernetes-minion-9q50": pods "fluentd-elasticsearch-kubernetes-minion-9q50" not found
```

Why we cannot delete mirror pod? and Created a new one? Because this regression, once we run into such state, the rest of test won't be triggered, and eventually timeout / failed.

**Comment by dchen1107** [comment] 2015-05-21 23:00
#8442 checks those service pods in ready state, and prevent the test to run once it is pending. 

cc/ @yujuhong I think this is the real issue I talked to you earlier about PodStatus.

**Comment by yujuhong** [comment] 2015-05-21 23:13
I spoke to @dchen1107 offline. For some reason, kubelet thinks the spec of the mirror pod does not match the static pod locally. It then decides to delete the mirror pod and recreate it, repeatedly. As a result of that, it slows down (due to the QPS limit?) reporting statuses of other pods. This can be reproduced by running the e2e "Shell" test. I am looking into why the specs would suddenly mismatch. Does any recent PR that modifies the spec in apiserver?

**Comment by yujuhong** [comment] 2015-05-21 23:38
The recently introduced default cpu share limit was not there in the static pod, causing the difference between its spec and the mirror pod's.

**Comment by derekwaynecarr** [comment] 2015-05-21 23:48
Seeing this as well.  Makes the whole cluster slow and unusable for me.

**Comment by derekwaynecarr** [comment] 2015-05-21 23:52
Is there a desired fix for this?

**Comment by yujuhong** [comment] 2015-05-21 23:59
@dchen1107 said she would add default resource limits to the static pod manifest files. If we go for that, I think it's reasonable to fail (not run the static pod) if resource limit is not specified.

Also, the resource limits set in the mirror pods are not meaningful because kubelet creates containers based on the spec of the static pod. In general, static pods do not subject to any defaulting values applied at the apiserver.

**Comment by quinton-hoole** [comment] 2015-05-22 00:34
Pretty sure that this is fixed by #7170.
Certainly testing against head since then works well for me.   What version are you testing?

**Comment by yujuhong** [comment] 2015-05-22 00:42
#7170 was fixing node status, and the problem had been around for a while.
This issue is about pod status, which is still unfixed in head. These two are very different, and my cluster do include the #7170 fix :)

This issue will slow down kubelet at times, but if you get lucky and the pod status (running) get sent out in time, the tests will still pass.

**Comment by derekwaynecarr** [comment] 2015-05-22 00:43
There is no way the issue is fixed by that PR. I am still seeing the issue on HEAD. The system gets worse the longer its up.  I agree with the analysis of the issue in source PR

**Comment by dchen1107** [comment] 2015-05-22 02:24
I am on this one, and here is proposed solution in my mind so far (not final yet since I haven't put too much thoughts into it yet):

1) For all our static pods I am going to update them with some initial cpu limit for now. This should quickly stop flakiness caused by this particular issue. 
2) Next step is that for static pods, if there is no initial cpu limit, kubelet should refuse to run. Before I do this, I need to send an announcement to our container-vm users about this potential breakage for the in the future. 

Another potential fix is we can ignore resource changes when comparing if a mirror pod is updated or not. I think @yujuhong is proposed a similiar one earlier. But I had a concern with it: this is defeat the initial purpose we created mirror pods and sync back to master. So if one made some resource changes on the static pods, you have to always ssh-ed into the node to see if the new value applied or not. Also eventually (post 1.0) those mirrored pod's resource limit is going to be used by scheduler when calculating if user pods are fit or not, we need them to be accurated. Another concern is in the code implementation itself to distinuguish mirror pods future from rest of pods. I guess this shouldn't be the big issue here.

Any more suggestions here? 

One puzzle I had is that why master component pods doesn't have issue at all. I manually restart kube-apiserver pod, still doesn't have the issue.

**Comment by derekwaynecarr** [comment] 2015-05-22 03:38
Depending on time we could just remove the default limit from the limit range as a stop gap.

**Comment by davidopp** [comment] 2015-05-22 06:19
Can you just bypass defaulting at the apiserver when you create mirror pods? I can't think of any other solution that works in general and is easily maintainable. Approach 2 you described in the previous entry works if we are defaulting cpu limit, but breaks as soon as we default anything else. Same problem with ignoring resource differences when comparing mirror pod to static pod -- as long as defaulting only touches resources, that works, but if we change it to touch other stuff, then it breaks.

**Comment by dchen1107** [comment] 2015-05-22 07:17
@davidopp Commit I had https://github.com/dchen1107/kubernetes-1/commit/626d25d50e3237c39a59098085ce5f78310e2efb can quickly fix current bleeding issue. 

Currently we only have master component pods and fluentd pod are file based by default. Master component pods doesn't create any issue now because mirror pods aren't created at the first place (due to recent change made by @roberthbailey). 

Also file-based pods will have issue only when its spec doesn't have initial value, and need to update (delete miss matched mirror pod, and recreate a new one). Please note that with my commit, everything is working even I manually update its cpu limit from 100m to 200m, there is no issue at all, and query pod  shows accurate result with the new limit too:

```
$ cluster/kubectl.sh get pods -o yaml fluentd-elasticsearch-e2e-test-dawnchen-minion-29s2
apiVersion: v1beta3
kind: Pod
metadata:
  annotations:
    kubernetes.io/config.mirror: mirror
    kubernetes.io/config.source: file
  creationTimestamp: 2015-05-22T06:58:45Z
  name: fluentd-elasticsearch-e2e-test-dawnchen-minion-29s2
  namespace: default
  resourceVersion: "629"
  selfLink: /api/v1beta3/namespaces/default/pods/fluentd-elasticsearch-e2e-test-dawnchen-minion-29s2
  uid: fd217298-004f-11e5-888c-42010af0647c
spec:
  containers:
  - capabilities: {}
    env:
    - name: FLUENTD_ARGS
      value: -qq
    image: gcr.io/google_containers/fluentd-elasticsearch:1.5
    imagePullPolicy: IfNotPresent
    name: fluentd-elasticsearch
    resources:
      limits:
        cpu: 200m
...
```

@bgrant0607 How badly we request all users using file-based pod feature providing default cpu limit for now? Eventually we want to get rid of file-based pods completely, also encouraging the user provides the initial resource limit is aligning with our direction in a long run anyway.

**Comment by davidopp** [comment] 2015-05-22 07:24
@dchen1107 Just to clarify, what I was suggesting was for a "real fix" not the temporary measure to stop the bleeding (which you already have in your PR). But what do you think of what I suggested as the longer-term fix? My point is that today, we default CPU, but in the future, we may default anything. It seems that the most maintainable fix is to just not do defaulting when creating mirror pod from static pod. Is that possible?

I wonder if the reason manual update works (what you described in your last comment) is because we don't go through the defaulting when you do an update, only a create? (Though that sounds like a bug.)

IMO we don't need CPU default right now, especially since we already have kubelet flag for limiting pods per machine (though unfortunately it's currently set to 100 because we haven't reconfigured the tests that intentionally run lots of pods per node, to override the flag. we can change the default to 30 and add an override mechanism if this is important.)

**Comment by bgrant0607** [comment] 2015-05-22 14:11
Comparing a config file with the live state and expecting them to match is doomed. The recommended approach is described by #1702. Kubelet could store the config as an annotation in the mirror pod and compare with that.

**Comment by bgrant0607** [comment] 2015-05-22 14:33
@davidopp Does the scheduler favor nodes with the fewest pods even if they don't specify resources? LimitRange does cause that to happen.

**Closed** 2015-05-22 15:59 UTC
Labels: area/test, priority/P0, team/node

**Comment by yujuhong** [comment] 2015-05-22 17:22
> The recommended approach is described by #1702. Kubelet could store the config as an annotation in the mirror pod and compare with that.

Storing the config as an annotation sounds good to me. Filed #8683

**Comment by Evil4Fish** [comment] 2018-04-16 09:17
Although this closed, it still appears in my environment：
`Apr 16 05:16:23 ubuntu kubelet[1847]: W0416 05:16:23.196969    1847 kubelet.go:1602] Deleting mirror pod "kube-controller-manager-ubuntu_kube-system(d4746eba-4156-11e8-84f4-0050569b7580)" because it is outdated
Apr 16 05:16:25 ubuntu kubelet[1847]: W0416 05:16:25.210714    1847 kubelet.go:1602] Deleting mirror pod "etcd-ubuntu_kube-system(d50d021a-4156-11e8-84f4-0050569b7580)" because it is outdated
Apr 16 05:16:25 ubuntu kubelet[1847]: W0416 05:16:25.210922    1847 kubelet.go:1602] Deleting mirror pod "kube-scheduler-ubuntu_kube-system(d52b8124-4156-11e8-84f4-0050569b7580)" because it is outdated
Apr 16 05:16:25 ubuntu kubelet[1847]: W0416 05:16:25.211102    1847 kubelet.go:1602] Deleting mirror pod "kube-apiserver-ubuntu_kube-system(d5a59d14-4156-11e8-84f4-0050569b7580)" because it is outdated
Apr 16 05:16:26 ubuntu kubelet[1847]: W0416 05:16:26.304259    1847 kubelet.go:1602] Deleting mirror pod "kube-controller-manager-ubuntu_kube-system(d5e29b69-4156-11e8-84f4-0050569b7580)" because it is outdated
Apr 16 05:16:27 ubuntu kubelet[1847]: W0416 05:16:27.221519    1847 kubelet.go:1602] Deleting mirror pod "etcd-ubuntu_kube-system(d6d6c835-4156-11e8-84f4-0050569b7580)" because it is outdated
Apr 16 05:16:28 ubuntu kubelet[1847]: W0416 05:16:28.307348    1847 kubelet.go:1602] Deleting mirror pod "kube-scheduler-ubuntu_kube-system(d6f54738-4156-11e8-84f4-0050569b7580)" because it is outdated
Apr 16 05:16:28 ubuntu kubelet[1847]: W0416 05:16:28.312400    1847 kubelet.go:1602] Deleting mirror pod "kube-apiserver-ubuntu_kube-system(d713d092-4156-11e8-84f4-0050569b7580)" because it is outdated
Apr 16 05:16:29 ubuntu kubelet[1847]: W0416 05:16:29.231625    1847 kubelet.go:1602] Deleting mirror pod "kube-controller-manager-ubuntu_kube-system(d78de2ee-4156-11e8-84f4-0050569b7580)" because it is outdated
Apr 16 05:16:29 ubuntu kubelet[1847]: W0416 05:16:29.231697    1847 kubelet.go:1602] Deleting mirror pod "etcd-ubuntu_kube-system(d807eb91-4156-11e8-84f4-0050569b7580)" because it is outdated
Apr 16 05:16:30 ubuntu kubelet[1847]: W0416 05:16:30.306746    1847 kubelet.go:1602] Deleting mirror pod "kube-scheduler-ubuntu_kube-system(d8637adb-4156-11e8-84f4-0050569b7580)" because it is outdated
Apr 16 05:16:31 ubuntu kubelet[1847]: W0416 05:16:31.241884    1847 kubelet.go:1602] Deleting mirror pod "kube-apiserver-ubuntu_kube-system(d88203ad-4156-11e8-84f4-0050569b7580)" because it is outdated
Apr 16 05:16:31 ubuntu kubelet[1847]: W0416 05:16:31.241931    1847 kubelet.go:1602] Deleting mirror pod "kube-controller-manager-ubuntu_kube-system(d93917e2-4156-11e8-84f4-0050569b7580)" because it is outdated
Apr 16 05:16:32 ubuntu kubelet[1847]: W0416 05:16:32.304783    1847 kubelet.go:1602] Deleting mirror pod "etcd-ubuntu_kube-system(d957a035-4156-11e8-84f4-0050569b7580)" because it is outdated
Apr 16 05:16:33 ubuntu kubelet[1847]: W0416 05:16:33.253003    1847 kubelet.go:1602] Deleting mirror pod "kube-controller-manager-ubuntu_kube-system(da6a45d4-4156-11e8-84f4-0050569b7580)" because it is outdated
Apr 16 05:16:33 ubuntu kubelet[1847]: W0416 05:16:33.253072    1847 kubelet.go:1602] Deleting mirror pod "kube-apiserver-ubuntu_kube-system(da4bc41d-4156-11e8-84f4-0050569b7580)" because it is outdated
Apr 16 05:16:33 ubuntu kubelet[1847]: W0416 05:16:33.253347    1847 kubelet.go:1602] Deleting mirror pod "kube-scheduler-ubuntu_kube-system(d9d1e953-4156-11e8-84f4-0050569b7580)" because it is outdated
Apr 16 05:16:34 ubuntu kubelet[1847]: W0416 05:16:34.308397    1847 kubelet.go:1602] Deleting mirror pod "etcd-ubuntu_kube-system(daa75308-4156-11e8-84f4-0050569b7580)" because it is outdated
Apr 16 05:16:35 ubuntu kubelet[1847]: W0416 05:16:35.263126    1847 kubelet.go:1602] Deleting mirror pod "kube-scheduler-ubuntu_kube-system(db5e6cde-4156-11e8-84f4-0050569b7580)" because it is outdated
Apr 16 05:16:35 ubuntu kubelet[1847]: W0416 05:16:35.263174    1847 kubelet.go:1602] Deleting mirror pod "kube-apiserver-ubuntu_kube-system(db3fe9f6-4156-11e8-84f4-0050569b7580)" because it is outdated
Apr 16 05:16:35 ubuntu kubelet[1847]: W0416 05:16:35.263247    1847 kubelet.go:1602] Deleting mirror pod "kube-controller-manager-ubuntu_kube-system(db21640f-4156-11e8-84f4-0050569b7580)" because it is outdated
Apr 16 05:16:37 ubuntu kubelet[1847]: W0416 05:16:37.273773    1847 kubelet.go:1602] Deleting mirror pod "etcd-ubuntu_kube-system(dc158d60-4156-11e8-84f4-0050569b7580)" because it is outdated
Apr 16 05:16:38 ubuntu kubelet[1847]: W0416 05:16:38.307290    1847 kubelet.go:1602] Deleting mirror pod "kube-controller-manager-ubuntu_kube-system(dd283121-4156-11e8-84f4-0050569b7580)" because it is outdated
Apr 16 05:16:38 ubuntu kubelet[1847]: W0416 05:16:38.318406    1847 kubelet.go:1602] Deleting mirror pod "kube-scheduler-ubuntu_kube-system(dceb2965-4156-11e8-84f4-0050569b7580)" because it is outdated
Apr 16 05:16:38 ubuntu kubelet[1847]: W0416 05:16:38.323775    1847 kubelet.go:1602] Deleting mirror pod "kube-apiserver-ubuntu_kube-system(dd09b088-4156-11e8-84f4-0050569b7580)" because it is outdated
Apr 16 05:16:38 ubuntu kubelet[1847]: W0416 05:16:38.419965    1847 status_manager.go:476] Failed to update status for pod "etcd-ubuntu_kube-system(dddf4ae8-4156-11e8-84f4-0050569b7580)": Operation cannot be fulfilled on pods "etcd-ubuntu": StorageError: invalid object, Code: 4, Key: /registry/pods/kube-system/etcd-ubuntu, ResourceVersion: 0, AdditionalErrorMsg: Precondition failed: UID in precondition: dddf4ae8-4156-11e8-84f4-0050569b7580, UID in object meta:
Apr 16 05:16:39 ubuntu kubelet[1847]: W0416 05:16:39.283698    1847 kubelet.go:1602] Deleting mirror pod "etcd-ubuntu_kube-system(dddf4ae8-4156-11e8-84f4-0050569b7580)" because it is outdated
Apr 16 05:16:41 ubuntu kubelet[1847]: W0416 05:16:41.294126    1847 kubelet.go:1602] Deleting mirror pod "kube-controller-manager-ubuntu_kube-system(de966b4e-4156-11e8-84f4-0050569b7580)" because it is outdated
Apr 16 05:16:41 ubuntu kubelet[1847]: W0416 05:16:41.294270    1847 kubelet.go:1602] Deleting mirror pod "kube-apiserver-ubuntu_kube-system(def1f034-4156-11e8-84f4-0050569b7580)" because it is outdated
Apr 16 05:16:41 ubuntu kubelet[1847]: W0416 05:16:41.294405    1847 kubelet.go:1602] Deleting mirror pod "kube-scheduler-ubuntu_kube-system(deb4eafe-4156-11e8-84f4-0050569b7580)" because it is outdated
Apr 16 05:16:42 ubuntu kubelet[1847]: W0416 05:16:42.316170    1847 kubelet.go:1602] Deleting mirror pod "etcd-ubuntu_kube-system(df4d8557-4156-11e8-84f4-0050569b7580)" because it is outdated
Apr 16 05:16:43 ubuntu kubelet[1847]: W0416 05:16:43.307084    1847 kubelet.go:1602] Deleting mirror pod "kube-apiserver-ubuntu_kube-system(e060285a-4156-11e8-84f4-0050569b7580)" because it is outdated
Apr 16 05:16:43 ubuntu kubelet[1847]: W0416 05:16:43.307373    1847 kubelet.go:1602] Deleting mirror pod "kube-controller-manager-ubuntu_kube-system(e041a3df-4156-11e8-84f4-0050569b7580)" because it is outdated
Apr 16 05:16:44 ubuntu kubelet[1847]: W0416 05:16:44.314136    1847 kubelet.go:1602] Deleting mirror pod "kube-scheduler-ubuntu_kube-system(e07ead67-4156-11e8-84f4-0050569b7580)" because it is outdated
Apr 16 05:16:44 ubuntu kubelet[1847]: W0416 05:16:44.315251    1847 kubelet.go:1602] Deleting mirror pod "etcd-ubuntu_kube-system(e0bbbc0f-4156-11e8-84f4-0050569b7580)" because it is outdated
Apr 16 05:16:44 ubuntu kubelet[1847]: W0416 05:16:44.420120    1847 status_manager.go:476] Failed to update status for pod "kube-controller-manager-ubuntu_kube-system(e135ca98-4156-11e8-84f4-0050569b7580)": Operation cannot be fulfilled on pods "kube-controller-manager-ubuntu": StorageError: invalid object, Code: 4, Key: /registry/pods/kube-system/kube-controller-manager-ubuntu, ResourceVersion: 0, AdditionalErrorMsg: Precondition failed: UID in precondition: e135ca98-4156-11e8-84f4-0050569b7580, UID in object meta:
Apr 16 05:16:45 ubuntu kubelet[1847]: W0416 05:16:45.319193    1847 kubelet.go:1602] Deleting mirror pod "kube-controller-manager-ubuntu_kube-system(e135ca98-4156-11e8-84f4-0050569b7580)" because it is outdated
Apr 16 05:16:45 ubuntu kubelet[1847]: W0416 05:16:45.319427    1847 kubelet.go:1602] Deleting mirror pod "kube-apiserver-ubuntu_kube-system(e117427b-4156-11e8-84f4-0050569b7580)" because it is outdated
Apr 16 05:16:46 ubuntu kubelet[1847]: W0416 05:16:46.324151    1847 kubelet.go:1602] Deleting mirror pod "etcd-ubuntu_kube-system(e1ece487-4156-11e8-84f4-0050569b7580)" because it is outdated
Apr 16 05:16:46 ubuntu kubelet[1847]: W0416 05:16:46.324283    1847 kubelet.go:1602] Deleting mirror pod "kube-scheduler-ubuntu_kube-system(e1ce6457-4156-11e8-84f4-0050569b7580)" because it is outdated
Apr 16 05:16:46 ubuntu kubelet[1847]: W0416 05:16:46.620286    1847 status_manager.go:476] Failed to update status for pod "etcd-ubuntu_kube-system(e1ece487-4156-11e8-84f4-0050569b7580)": Operation cannot be fulfilled on pods "etcd-ubuntu": StorageError: invalid object, Code: 4, Key: /registry/pods/kube-system/etcd-ubuntu, ResourceVersion: 0, AdditionalErrorMsg: Precondition failed: UID in precondition: e1ece487-4156-11e8-84f4-0050569b7580, UID in object meta:
Apr 16 05:16:47 ubuntu kubelet[1847]: W0416 05:16:47.329452    1847 kubelet.go:1602] Deleting mirror pod "kube-controller-manager-ubuntu_kube-system(e2c2824a-4156-11e8-84f4-0050569b7580)" because it is outdated
Apr 16 05:16:48 ubuntu kubelet[1847]: W0416 05:16:48.335305    1847 kubelet.go:1602] Deleting mirror pod "kube-apiserver-ubuntu_kube-system(e2e103f0-4156-11e8-84f4-0050569b7580)" because it is outdated
Apr 16 05:16:48 ubuntu kubelet[1847]: W0416 05:16:48.620186    1847 status_manager.go:476] Failed to update status for pod "kube-scheduler-ubuntu_kube-system(e39824fc-4156-11e8-84f4-0050569b7580)": Operation cannot be fulfilled on pods "kube-scheduler-ubuntu": StorageError: invalid object, Code: 4, Key: /registry/pods/kube-system/kube-scheduler-ubuntu, ResourceVersion: 0, AdditionalErrorMsg: Precondition failed: UID in precondition: e39824fc-4156-11e8-84f4-0050569b7580, UID in object meta:
Apr 16 05:16:49 ubuntu kubelet[1847]: W0416 05:16:49.340254    1847 kubelet.go:1602] Deleting mirror pod "etcd-ubuntu_kube-system(e379a3bc-4156-11e8-84f4-0050569b7580)" because it is outdated
Apr 16 05:16:49 ubuntu kubelet[1847]: W0416 05:16:49.340399    1847 kubelet.go:1602] Deleting mirror pod "kube-scheduler-ubuntu_kube-system(e39824fc-4156-11e8-84f4-0050569b7580)" because it is outdated`
