### ISSUE TITLE
resource quota update does not take effect until create/delete another ResourceQuota

### ISSUE THREAD

**Issue by njuicsgz** [GoogleCloudPlatform/kubernetes#6845] opened 2015-04-15 02:30 UTC
## Description
Resource quota update does not take effect until create/delete another ResourceQuota. I am not sure it is an issue or design. 

## environment
```
root@AMZ-IAD-WallE-35-50:~/paas/kube-manage/resourcequota# kubectl version
Client Version: version.Info{Major:"0", Minor:"13+", GitVersion:"v0.13.2-1-g58b98aca84becd", GitCommit:"58b98aca84becdabbfc8d719c47b375a6a1bc855", GitTreeState:"clean"}
Server Version: version.Info{Major:"0", Minor:"13+", GitVersion:"v0.13.2-1-g58b98aca84becd", GitCommit:"58b98aca84becdabbfc8d719c47b375a6a1bc855", GitTreeState:"clean"}
```
## Issue reproduce
```
# ls
test2.rq.json  test.rq.json

# kubectl describe resourcequota my-quota2 --namespace=test          
Name:                   my-quota2
Resource                Used    Hard
--------                ----    ----
cpu                     1       2
memory                  1Gi     2Gi
pods                    1       2
replicationcontrollers  1       2
resourcequotas          1       2
services                0       2

# cat test2.rq.json 
{
  "apiVersion": "v1beta3",
  "kind": "ResourceQuota",
  "metadata": {
    "namespace": "test",
    "name": "my-quota2",
  },
  "spec": {
    "hard": {
      "memory": "4Gi",
      "cpu": "4",
      "pods": "4",
      "services": "4",
      "replicationcontrollers":"4",
      "resourcequotas":"4",
    },
  }
}

# kubectl update -f test2.rq.json --namespace=test
my-quota2

# kubectl describe resourcequota my-quota2 --namespace=test
Name:                   my-quota2
Resource                Used    Hard
--------                ----    ----
cpu                     1       2
memory                  1Gi     2Gi
pods                    1       2
replicationcontrollers  1       2
resourcequotas          1       2
services                0       2

[The quota does not change to 4 from 2 as my expect.]

# cat test.rq.json             
{
  "apiVersion": "v1beta3",
  "kind": "ResourceQuota",
  "metadata": {
    "namespace": "test",
    "name": "my-quota",
  },
  "spec": {
    "hard": {
      "memory": "5Gi",
      "cpu": "5",
      "pods": "5",
      "services": "5",
      "replicationcontrollers":"5",
      "resourcequotas":"5",
    },
  }
}

# kubectl create -f test.rq.json --namespace=test               
my-quota

# kubectl get quota --namespace=test
NAME
my-quota
my-quota2

# kubectl describe resourcequota my-quota2 --namespace=test      
Name:                   my-quota2
Resource                Used    Hard
--------                ----    ----
cpu                     1       4
memory                  1Gi     4Gi
pods                    1       4
replicationcontrollers  1       4
resourcequotas          2       4
services                0       4
[It changed when create another quota, and also change for delete action]
```

**Comment by derekwaynecarr** [comment] 2015-04-16 01:43
I am 99% sure that the issue is the update is changing the Spec and the Kubectl client is showing the Status.  The Status will update at the next quota sync interval to align with the desired Spec.  Can you describe what KUBERNETES environment you are using so I can verify?  In particular, how is kube-controller-manager started?

You can confirm this by doing 

kubectl get quota -o json 

And you should see the spec update occurred and if you wait 1 minute you will see the status take effect.


A few options to improve user experience:

1.  Improve latency of updating status with spec.  This has some potential side effects that I need to think through with how the current controller is structured.
2.  Change kubectl output to show spec if it differs from status so it's clear that the system will ultimately drive to its desired state.  This seems like a good thing to do in general, will experiment with some options to present this information, but I am open to your input.  I think even a single line noting that the enforced usage limits are different than the desired state but will reconcile soon.

**Comment by njuicsgz** [comment] 2015-04-16 07:44
Sure to append config of kube-controller-manager:
```
# cat /etc/default/kube-controller-manager 
# Use KUBE_CONTROLLER_MANAGER_OPTS to modify the start/restart options
KUBE_CONTROLLER_MANAGER_OPTS="--master=10.1.35.50:8080 \
--machines=10.1.35.51,10.1.35.52,10.1.35.53,10.1.35.54,10.1.35.55,10.1.35.56,10.1.35.57 \
--v=2"
And it start with 'service kube-controller-manager'.
```
Tried the cmd, the spec updated as you said, however, the status refuse to take effect after more than 5 mins. I am not sure if it is caused by my version v0.13.2.

**Comment by derekwaynecarr** [comment] 2015-04-16 19:03
I see the issue, will send a PR.  It appears the quota status was only getting marked as dirty for update if the usage changed, and not the underlying limit itself.  So I suspect if you removed a pod (assuming you were tracking total number of pods), you would see the status kept updated to the desired spec.

**Comment by njuicsgz** [comment] 2015-04-17 01:01
The status changed correctly after resizing a rc and wait a while (8s).

**Closed** 2015-04-17 19:52 UTC
Labels: priority/P2, team/cluster

**Comment by derekwaynecarr** [comment] 2015-04-17 20:10
I want to update the Kubectl output to show the desired value if it differs from the status value.  I will look to do that in the next few days.  I think that would eliminate all confusion.
