### ISSUE TITLE
YAML File "cmd" doesnt support same thing as docker CMD.

### ISSUE THREAD

**Issue by jayunit100** [GoogleCloudPlatform/kubernetes#3575] opened 2015-01-16 21:03 UTC
Commands like this .

``` /bin/bash /opt/run.sh ```

Don't work if pasted into the YAML file like so:

```
      1 id: spark
      2 kind: Pod
      3 apiVersion: v1beta1
      4 desiredState:
      5   manifest:
      6     version: v1beta1
      7     id: spark
      8     containers:
      9       - name: spark
     10         image: jayunit100/spark2
                  command:
                      - /bin/bash /opt/run.sh
     11         cpu: 1000
     12         ports:
     13           - name: sp
     14             containerPort: 7077
     15 labels:
     16   name: spark
```

The reason is that *stat* winds up returning something along the lines of 

` exec: \"/bin/bash /opt/run.sh\": stat /bin/bash /opt/run.sh: no such file or directory"[1:48pm]`

This is a pretty significant usability issue, as this is *not* caught by `--validate true` and can only be seen if we go directly into the docker logs ( `journalctl -f -u docker`), these errors dont go into docker logs and aren't reported in kubelet's either.

**Comment by jayunit100** [comment] 2015-01-16 21:07
Note the workaround to this that I found was to simply use CMD inside the dockerfile itself.  In this case, we don't run into any yaml / cmd forwarding issues, so i bet this might be fixable by just properly breaking up the command directive's arguments as explicit params in the yaml file.

**Comment by smarterclayton** [comment] 2015-01-16 21:24
Ah, you hit https://github.com/GoogleCloudPlatform/kubernetes/issues/2316 effectively.  We're trying to get this sorted out in a way that's clear to users but gives them the flexibility for the underlying execution.

**Comment by jayunit100** [comment] 2015-01-16 22:24
Yup ! Another workaround , actually, is do use multiple bullets under `command` like is done in the guestbook vttablet-pod-template example.........
```
 command:
- bash
- "-c"
- >-
```

**Comment by goltermann** [comment] 2015-01-28 00:42
Closing as this has been answered.  Dupe of #2316.

**Closed by goltermann** 2015-01-28 00:42 UTC
