### ISSUE TITLE
error registering a node after reboot

### ISSUE THREAD

**Issue by marekbiskup** [GoogleCloudPlatform/kubernetes#10671] opened 2015-07-02 12:21 UTC
I run into this problem when trying to run a test with the patch from #10487, so it may not be a true problem. But I suggest someone have a quick look at it - it looks like a race condition somewhere (maybe we're not handling some error properly?)

After reboot test, both nodes disappeared:
```
biskup@cathedral:~/go/src/github.com/GoogleCloudPlatform/kubernetes$ cluster/kubectl.sh get node
NAME                          LABELS                                               STATUS
e2e-test-biskup-minion-o97i   kubernetes.io/hostname=e2e-test-biskup-minion-o97i   NotReady
e2e-test-biskup-minion-owoj   kubernetes.io/hostname=e2e-test-biskup-minion-owoj   NotReady
```

kubelet logs:
```
I0702 10:47:26.455407    2374 status_manager.go:56] Starting to sync pod status with apiserver
I0702 10:47:26.455441    2374 kubelet.go:1616] Starting kubelet main sync loop.
E0702 10:47:36.831206    2374 kubelet.go:1538] error getting node: node e2e-test-biskup-minion-o97i not found
E0702 10:47:46.603740    2374 http.go:54] Failed to read URL: http://metadata.google.internal/computeMetadata/v1beta1/instance/attributes/google-container-manifest: 404 Not Found
I0702 10:47:47.586379    2856 server.go:271] Using root directory: /var/lib/kubelet
I0702 10:47:47.586561    2856 manager.go:127] cAdvisor running in container: "/"
I0702 10:47:47.586861    2856 fs.go:93] Filesystem partitions: map[/dev/disk/by-uuid/d1f816ed-d274-4db7-bc93-4984de845be6:{mountpoint:/ major:8 minor:1}]
I0702 10:47:47.589180    2856 machine.go:229] Couldn't collect info from any of the files in "/etc/machine-id,/var/lib/dbus/machine-id"
I0702 10:47:47.589229    2856 manager.go:156] Machine: {NumCores:1 CpuFrequency:2500000 MemoryCapacity:3892027392 MachineID: SystemUUID:44D6F6F1-6B8D-B1A2-1F8A-AD6195D0E78E BootID:0ddcf04d-f84e-41fb-bf28-1
4ff131f69a5 Filesystems:[{Device:/dev/disk/by-uuid/d1f816ed-d274-4db7-bc93-4984de845be6 Capacity:105553100800}] DiskMap:map[8:0:{Name:sda Major:8 Minor:0 Size:107374182400 Scheduler:cfq}] NetworkDevices:[{
Name:eth0 MacAddress:42:01:0a:f0:2a:1a Speed:0 Mtu:1460}] Topology:[{Id:0 Memory:3892027392 Cores:[{Id:0 Threads:[0] Caches:[{Size:32768 Type:Data Level:1} {Size:32768 Type:Instruction Level:1} {Size:26214
4 Type:Unified Level:2}]}] Caches:[{Size:31457280 Type:Unified Level:3}]}]}
I0702 10:47:47.589492    2856 manager.go:163] Version: {KernelVersion:3.16.0-0.bpo.4-amd64 ContainerOsVersion:Debian GNU/Linux 7 (wheezy) DockerVersion:Unknown CadvisorVersion:0.15.1}
I0702 10:47:47.594403    2856 server.go:290] Successfully initialized cloud provider: "gce" from the config file: ""
I0702 10:47:49.004127    2856 docker.go:289] Connecting to docker on unix:///var/run/docker.sock
I0702 10:47:49.005041    2856 server.go:586] cloud provider determined current node name to be e2e-test-biskup-minion-o97i
I0702 10:47:49.005328    2856 server.go:651] Adding manifest file: /etc/kubernetes/manifests
I0702 10:47:49.005347    2856 file.go:47] Watching path "/etc/kubernetes/manifests"
I0702 10:47:49.005359    2856 server.go:661] Watching apiserver
E0702 10:47:49.005767    2856 manager.go:139] Failed to execute Info() call to the Docker client: dial unix /var/run/docker.sock: no such file or directory
W0702 10:47:49.005783    2856 manager.go:140] Using fallback default of /var/lib/docker for location of Docker runtime
I0702 10:47:49.005793    2856 plugins.go:56] Registering credential provider: .dockercfg
I0702 10:47:49.029863    2856 plugins.go:56] Registering credential provider: google-dockercfg
I0702 10:47:49.030297    2856 plugins.go:56] Registering credential provider: google-dockercfg-url
I0702 10:47:49.030766    2856 plugins.go:56] Registering credential provider: google-container-registry
I0702 10:47:49.030840    2856 container_manager_linux.go:100] Configure resource-only container /docker-daemon with memory limit: 2724419174
I0702 10:47:49.031939    2856 container_manager_linux.go:277] Found 63 PIDs in root, 35 of them are kernel related
I0702 10:47:49.031952    2856 container_manager_linux.go:284] Moving non-kernel threads: [1 351 480 481 1681 1816 1825 1868 1898 1968 2280 2328 2330 2343 2354 2372 2417 2465 2468 2491 2493 2499 2500 2593 2
676 2856 2862 2863]
I0702 10:47:49.218988    2856 container_manager_linux.go:277] Found 35 PIDs in root, 35 of them are kernel related
I0702 10:47:49.222400    2856 container_bridge.go:129] MASQUERADE rule doesn't exist, recreate it
I0702 10:47:49.644133    2856 kubelet.go:1924] Recording NodeNotReady event message for node e2e-test-biskup-minion-o97i
I0702 10:47:49.644210    2856 kubelet.go:781] Attempting to register node e2e-test-biskup-minion-o97i
I0702 10:47:49.773331    2856 kubelet.go:798] Unable to register e2e-test-biskup-minion-o97i with the apiserver: node "e2e-test-biskup-minion-o97i" already exists
I0702 10:47:50.194261    2856 kubelet.go:1924] Recording NodeNotReady event message for node e2e-test-biskup-minion-o97i
I0702 10:47:50.194315    2856 kubelet.go:781] Attempting to register node e2e-test-biskup-minion-o97i
I0702 10:47:50.208949    2856 kubelet.go:798] Unable to register e2e-test-biskup-minion-o97i with the apiserver: node "e2e-test-biskup-minion-o97i" already exists
I0702 10:47:51.187454    3057 server.go:271] Using root directory: /var/lib/kubelet
```
Then the errors keep on repeating.

Apiserver logs don't have anything special:
```
I0702 10:47:26.121950       9 handlers.go:135] GET /api/v1/nodes: (1.522451ms) 200 [[kube-controller-manager/v0.20.2 (linux/amd64) kubernetes/f578924] 127.0.0.1:59192]
I0702 10:47:27.885580       9 handlers.go:135] GET /api/v1/nodes: (1.266544ms) 200 [[kube-controller-manager/v0.20.2 (linux/amd64) kubernetes/f578924] 127.0.0.1:59192]
I0702 10:47:27.899098       9 handlers.go:135] PUT /api/v1/nodes/e2e-test-biskup-minion-o97i/status: (10.880543ms) 200 [[kube-controller-manager/v0.20.2 (linux/amd64) kubernetes/f578924] 127.0.0.1:59192]
I0702 10:47:29.110505       9 handlers.go:135] GET /api/v1/nodes/e2e-test-biskup-minion-owoj: (1.541321ms) 200 [[kubelet/v0.20.2 (linux/amd64) kubernetes/f578924] 10.240.239.152:54567]
I0702 10:47:29.123213       9 handlers.go:135] PUT /api/v1/nodes/e2e-test-biskup-minion-owoj/status: (10.038043ms) 200 [[kubelet/v0.20.2 (linux/amd64) kubernetes/f578924] 10.240.239.152:54567]
I0702 10:47:29.340616       9 handlers.go:135] GET /api/v1/resourcequotas: (871.772µs) 200 [[kube-controller-manager/v0.20.2 (linux/amd64) kubernetes/f578924] 127.0.0.1:59192]
I0702 10:47:30.274323       9 handlers.go:135] GET /healthz: (28.447µs) 0 [[Go 1.1 package http] 127.0.0.1:54657]
I0702 10:47:31.385304       9 handlers.go:135] GET /api/v1beta3/watch/services?resourceVersion=2205: (2m52.15879354s) 0 [[kube2sky/v0.20.0 (linux/amd64) kubernetes/unknown] 10.240.239.152:54480]
I0702 10:47:31.446121       9 handlers.go:135] GET /api/v1beta3/watch/endpoints?resourceVersion=2205: (2m52.216224614s) 0 [[kube2sky/v0.20.0 (linux/amd64) kubernetes/unknown] 10.240.239.152:54482]
I0702 10:47:31.475084       9 handlers.go:135] GET /api/v1beta3/watch/namespaces?resourceVersion=2275: (53.703345009s) 0 [[heapster/v0.19.3 (linux/amd64) kubernetes/unknown] 10.240.239.152:54694]
I0702 10:47:31.475226       9 handlers.go:135] GET /api/v1beta3/watch/pods?fieldSelector=spec.host%21%3D&resourceVersion=2203: (2m55.638885479s) 0 [[heapster/v0.19.3 (linux/amd64) kubernetes/unknown] 10.240.239.152:54458]
I0702 10:47:31.475325       9 handlers.go:135] GET /api/v1beta3/watch/nodes?resourceVersion=2203: (2m55.62691246s) 0 [[heapster/v0.19.3 (linux/amd64) kubernetes/unknown] 10.240.239.152:54462]
I0702 10:47:31.475555       9 handlers.go:135] GET /api/v1beta3/watch/events?resourceVersion=2205: (2m54.194364795s) 0 [[heapster/v0.19.3 (linux/amd64) kubernetes/unknown] 10.240.239.152:54460]
I0702 10:47:32.403169       9 handlers.go:135] GET /api/v1/watch/endpoints?resourceVersion=2203: (2m57.466623268s) 0 [[kube-proxy/v0.20.2 (linux/amd64) kubernetes/f578924] 10.240.239.152:54450]
I0702 10:47:32.403421       9 handlers.go:135] GET /api/v1/watch/services?resourceVersion=2200: (3m7.320232171s) 0 [[kube-proxy/v0.20.2 (linux/amd64) kubernetes/f578924] 10.240.239.152:54431]
I0702 10:47:32.424266       9 handlers.go:135] GET /api/v1/watch/nodes?fieldSelector=metadata.name%3De2e-test-biskup-minion-owoj&resourceVersion=2217: (2m24.210929316s) 0 [[kubelet/v0.20.2 (linux/amd64) kubernetes/f578924] 10.240.239.152:54561]
```

**Comment by zmerlynn** [comment] 2015-07-02 12:28
Is this a dupe of #10368? You might try patching in #10593.

**Comment by dchen1107** [comment] 2015-07-02 17:04
It is indeed a dup of #10368.

**Closed by dchen1107** 2015-07-02 17:04 UTC
Labels: team/cluster-lifecycle, team/node
