### ISSUE TITLE
DNS is broken after node reboot

### ISSUE THREAD

**Issue by mbforbes** [GoogleCloudPlatform/kubernetes#8144] opened 2015-05-12 23:22 UTC
This is blocking #7580 (test reboot).

I originally ran into this trying to run the guestbook test after the nodes had all rebooted; here is the [log for the failed guestbook test](https://gist.github.com/mbforbes/ff74c87346f724b0fc8e).

I added more logging to help understand what is happening. I added the following logging [after this line](https://github.com/GoogleCloudPlatform/kubernetes/blob/40ec627cd4df486916572a495a7f139c3faedddb/test/e2e/kubectl.go#L153):

```go
Logf("Call to makeRequestToGuestbook(client, cmd='%s', arg='%s', ns='%s') failed.", cmd, arg, ns)
Logf("\t response: expected '%s', got: '%s'", expectedResponse, res)
Logf("\t error:    expected '<nil>', got: '%v'", err)
```

The first time it's called I get an error that says `no endpoints available for "frontend"`, but then after that, I get the following repeated errors:

```
INFO: Call to makeRequestToGuestbook(client, cmd='get', arg='', ns='e2e-tests-kubectl-7d744f0d-775f-4fd0-93b2-88135adbc11e') failed.
INFO: 	 response: expected '{"data": ""}', got: '<br />
<b>Fatal error</b>:  Uncaught exception 'Predis\Connection\ConnectionException' with message 'php_network_getaddresses: getaddrinfo failed: Name or service not known [tcp://redis-slave:6379]' in /vendor/predis/predis/lib/Predis/Connection/AbstractConnection.php:141
Stack trace:
#0 /vendor/predis/predis/lib/Predis/Connection/StreamConnection.php(96): Predis\Connection\AbstractConnection-&gt;onConnectionError('php_network_get...', 0)
#1 /vendor/predis/predis/lib/Predis/Connection/StreamConnection.php(70): Predis\Connection\StreamConnection-&gt;tcpStreamInitializer(Object(Predis\Connection\ConnectionParameters))
#2 /vendor/predis/predis/lib/Predis/Connection/AbstractConnection.php(96): Predis\Connection\StreamConnection-&gt;createResource()
#3 /vendor/predis/predis/lib/Predis/Connection/StreamConnection.php(144): Predis\Connection\AbstractConnection-&gt;connect()
#4 /vendor/predis/predis/lib/Predis/Connection/AbstractConnection.php(181): Predis\Connection\StreamConnection-&gt;connect()
#5 /vendor/predis/predis/lib/Predis/Connection/StreamConnectio in <b>/vendor/predis/predis/lib/Predis/Connection/AbstractConnection.php</b> on line <b>141</b><br />
'
INFO: 	 error:    expected '<nil>', got: '<nil>'
```

Just to make that more readable, the error before the stack trace is: `Uncaught exception 'Predis\Connection\ConnectionException' with message 'php_network_getaddresses: getaddrinfo failed: Name or service not known [tcp://redis-slave:6379]' in /vendor/predis/predis/lib/Predis/Connection/AbstractConnection.php:141`

Any tips or help greatly appreciated. I'm not sure where in the tcp / services / php / redis stack this is going wrong.

Apologies in advance for the large cc:
+cc @roberthbailey @zmerlynn @quinton-hoole @ixdy

**Comment by roberthbailey** [comment] 2015-05-13 00:13
@piosz (since he originally ported this test from shell to go and may have some ideas)

**Comment by piosz** [comment] 2015-05-13 06:12
It looks like a problem with DNS. Is DNS working after node reboot? Could you provide some details how can I reproduce the bug?

**Comment by mbforbes** [comment] 2015-05-13 06:39
Hey @piosz, thanks for jumping in. No, DNS isn't working after reboot—here's [a log of the DNS test](https://gist.github.com/mbforbes/1135339f4a5e2beda85e).

This is actually fairly easy to reproduce:
- create a testing cluster with `go run hack/e2e.go --v --up`
- ssh into each node and run `sudo reboot`, then waiting for all nodes/pods to be Running & ready
- run the test of your choice; for example, to run guestbook, run `go run hack/e2e.go --v --test --test_args="--ginkgo.focus=guestbook"`

This is done programmatically in #7580 and tests start breaking, including guestbook, DNS, elasticsearch, and influx / heapster. Any help greatly appreciated!

**Comment by roberthbailey** [comment] 2015-05-13 06:48
@thockin FYI

Should we just rename this issue "DNS is broken after reboot"?

**Comment by thockin** [comment] 2015-05-13 07:00
What does reboot have to do with DNS?  That's bizarre.  Trying to repro

**Comment by thockin** [comment] 2015-05-13 07:18
From controller-manager logs:

I0513 07:13:10.186807       7 defaults.go:179] upward merge of
container.Capabilities.Add for container skydns
I0513 07:13:10.186848       7 defaults.go:183] upward merge of
container.Capabilities.Drop for container skydns
I0513 07:13:10.186873       7 defaults.go:189] downward merge of
container.Privileged for container skydns
I0513 07:13:10.189282       7 controller_utils.go:98] Controller kube-dns
either never recorded expectations, or the ttl expired.
I0513 07:13:10.191572       7 replication_controller.go:339] Finished
syncing controller "default/kube-dns" (2.346368ms)
I0513 07:13:10.191395       7 endpoints_controller.go:258] Finished syncing
service "default/kube-dns" endpoints. (20.849555ms)

@lavalamp - you touched it last, any clue what this means?

It says it synced service kube-dns, but 'get endpoints' shows nothing.

root@e2e-test-thockin-master:/home/thockin# kubectl get endpoints kube-dns
NAME       ENDPOINTS
kube-dns   <none>

root@e2e-test-thockin-master:/home/thockin# kubectl get service kube-dns
NAME       LABELS
   SELECTOR           IP(S)       PORT(S)
kube-dns   k8s-app=kube-dns,kubernetes.io/cluster-service=true,name=kube-dns
  k8s-app=kube-dns   10.0.0.10   53/UDP

                                  53/TCP

root@e2e-test-thockin-master:/home/thockin# kubectl get pods -l
k8s-app=kube-dns
POD              IP           CONTAINER(S)   IMAGE(S)
                  HOST                                          LABELS
                                           STATUS    CREATED      MESSAGE
kube-dns-6tbbb   10.245.0.4
                  e2e-test-thockin-minion-fdo0/146.148.61.252
k8s-app=kube-dns,kubernetes.io/cluster-service=true   Running   15 hours

                              skydns
gcr.io/google_containers/skydns:2015-03-11-001

Running   15 minutes
                              etcd
gcr.io/google_containers/etcd:2.0.9

 Running   15 minutes
                              kube2sky
gcr.io/google_containers/kube2sky:1.4

 Running   9 seconds    last termination: exit code 1

**Comment by piosz** [comment] 2015-05-13 07:33
Thanks @mbforbes for details. The problem with guestbook should be figured out once DNS starts working. I'll also take a look into the problem with DNS.

cc @satnam6502 who may have an idea why elasticsearch doesn't work

**Comment by satnam6502** [comment] 2015-05-13 07:35
The elasticsearch test needs DNS to be working. So if DNS if busted, the elasticsearch e2e test will fail.

**Comment by satnam6502** [comment] 2015-05-13 07:36
Although note that I did update the Elasticsearch logging setup on Tuesday and I did slightly adjust the elasticsearch logging e2e test.

**Comment by piosz** [comment] 2015-05-13 11:55
kube2sky is crashlooping with the following error:
```
2015/05/13 11:54:46 Etcd server found: http://127.0.0.1:4001
2015/05/13 11:54:47 Failed to create a kubernetes client: stat /etc/dns_token/kubeconfig: no such file or directory
```

Crashloop logs:
```
pszczesniak@kubernetes-minion-v115:~$ sudo docker ps -a
CONTAINER ID        IMAGE                                                COMMAND                CREATED                  STATUS                          PORTS               NAMES
d747cec0c714        gcr.io/google_containers/kube2sky:1.4                "/kube2sky -domain=c   Less than a second ago                                                       k8s_kube2sky.cb40782f_kube-dns-pw41j_default_e8583425-f955-11e4-8669-42010af012c8_4ec6d028                                          
dd7a4b46ad3e        gcr.io/google_containers/kube2sky:1.4                "/kube2sky -domain=c   11 seconds ago           Exited (1) 8 seconds ago                            k8s_kube2sky.cb40782f_kube-dns-pw41j_default_e8583425-f955-11e4-8669-42010af012c8_cfa9a2ff                                          
3ff7f50003fb        gcr.io/google_containers/kube2sky:1.4                "/kube2sky -domain=c   21 seconds ago           Exited (1) 18 seconds ago                           k8s_kube2sky.cb40782f_kube-dns-pw41j_default_e8583425-f955-11e4-8669-42010af012c8_2ac1d06d                                          
cba76b58e697        gcr.io/google_containers/kube2sky:1.4                "/kube2sky -domain=c   31 seconds ago           Exited (1) 28 seconds ago                           k8s_kube2sky.cb40782f_kube-dns-pw41j_default_e8583425-f955-11e4-8669-42010af012c8_a5d29473                                          
832cecca3f76        gcr.io/google_containers/kube2sky:1.4                "/kube2sky -domain=c   41 seconds ago           Exited (1) 38 seconds ago                           k8s_kube2sky.cb40782f_kube-dns-pw41j_default_e8583425-f955-11e4-8669-42010af012c8_eba7a878                                          
be83e7e16546        gcr.io/google_containers/kube2sky:1.4                "/kube2sky -domain=c   51 seconds ago           Exited (1) 48 seconds ago                           k8s_kube2sky.cb40782f_kube-dns-pw41j_default_e8583425-f955-11e4-8669-42010af012c8_bfa9a817
```

**Comment by satnam6502** [comment] 2015-05-13 15:27
So it looks like it is not finding the dns_token secret?

**Comment by antmanler** [comment] 2015-05-13 15:49
+1 the same issue, cannot find dns_token

**Comment by roberthbailey** [comment] 2015-05-13 16:51
This appears to be caused by #7958.

**Comment by thockin** [comment] 2015-05-13 16:53
I was just writing the same response.  Yes,

**Comment by lavalamp** [comment] 2015-05-13 17:38
Yeah, the crashloop explains why endpoints controller isn't making any endpoints (I *am* getting nervous because there's been NO BUGS in my rewrite of endpoints controller, so there's probably a really awful one waiting to bite us, but this is not it.). This is clearly #7958. Let's just close this as a dup?

**Comment by piosz** [comment] 2015-05-13 17:39
duplicate of #7958

**Closed by piosz** 2015-05-13 17:39 UTC
Labels: area/test, area/upgrade, kind/bug, kind/example, priority/P1, team/testing
