### ISSUE TITLE
Feature request: add ability to view logs of pod in failed state

### ISSUE THREAD

**Issue by derekwaynecarr** [GoogleCloudPlatform/kubernetes#4640] opened 2015-02-20 01:47 UTC
While working to build applications on Kubernetes, I found it difficult to view the logs of a container that went into a failed state.  I had to SSH into the node, docker ps -a, and docker logs to see the root cause.  We should provide a mechanism via kubelet to view logs of containers not yet garbage collected for access via kubectl to improve developer productivity.

/cc @smarterclayton

**Comment by smarterclayton** [comment] 2015-02-23 20:20
Ah, this was a regression due to #4373.  It's very harmful for RestartPolicyNever pods, slightly less important for RestartAlways.

**Comment by smarterclayton** [comment] 2015-02-23 20:20
@bgrant0607 I'd like to bump this back to P1, it makes run once pods impossible to view the logs on.

**Comment by satnam6502** [comment] 2015-02-23 20:23
Are you using Elasticsearch cluster level logging?
I have peen pondering the idea of producing a pob that makes it easy to browse the logs of current and recent pods through a web interface by fetching the information from Elasticsearch and then cross-referencing with the master to map pods to Docker container IDs etc.
Would that be useful for you? If yes, I can make that a priority after I nail the end to end test for cluster level logging?

**Comment by smarterclayton** [comment] 2015-02-23 20:51
We are not, quite yet - we're trying to have both the simpler level and the higher level work at the same time (so you can do streaming without ElasticSearch, and if you have ES you get the better experience).

----- Original Message -----

**Comment by smarterclayton** [comment] 2015-02-23 20:51
But we do want to consume it.

----- Original Message -----

**Comment by dchen1107** [comment] 2015-02-23 21:08
yes, #4373 adds the restriction to only running container, and we should provide ability to view logs of pod in failed state. But the previous way is too ad hoc. When you view the log, you could view the running one, or previous failing one right before Kubelet restart one when policy is RestartNever.

**Comment by bgrant0607** [comment] 2015-02-23 21:08
@saad-ali

**Comment by bgrant0607** [comment] 2015-02-23 21:11
@vishh

**Comment by bgrant0607** [comment] 2015-02-23 21:17
@smarterclayton Priority bumped up. Agree that #4373 was a regression.

**Comment by smarterclayton** [comment] 2015-02-23 21:32
New algorithm, always find the most recent container attempt and show that?

**Comment by dchen1107** [comment] 2015-02-23 21:40
@smarterclayton Yes, we are going to support like this.

**Comment by satnam6502** [comment] 2015-02-23 21:40
I've created an issue #4736 ... if it gets traction I am happy to work on it. I also plan to tweak our Elasticsearch cluster level bring up code to remote the last shread of a GCE specific call (to get the public IP of a service) with the equivalent `kubectl` call (although this feature would not be needed for a cluster level log viewer).

**Comment by dchen1107** [comment] 2015-02-23 22:58
cc/ @ArtfulCoder

**Comment by vishh** [comment] 2015-03-04 20:30
This should be fixed on HEAD

**Comment by vishh** [comment] 2015-03-05 23:35
Kubelet does not track the last failed container instance and so this issue isn't fully resolved. Re-opening it.

**Comment by vishh** [comment] 2015-03-30 18:46
@dchen1107: I assume you are working on this. Can you confirm?

**Comment by vishh** [comment] 2015-04-15 00:12
Ping @dchen1107

**Comment by dchen1107** [comment] 2015-04-15 00:21
Yes, just re-assign it to me. Will deal it tomorrow.

**Comment by derekwaynecarr** [comment] 2015-04-16 02:43
Since we are now running kube-apiserver and other master components in a pod, will it be possible via some quick shortcut to go directly to the kubelet to read failed kube-apiserver logs when the kube-apiserver itself fails to start?

----- Original Message -----

**Comment by bgrant0607** [comment] 2015-04-27 22:24
Status: @dchen1107 has made some progress, but other issues have preempted this, so it won't be done for a couple weeks.

**Comment by smarterclayton** [comment] 2015-04-28 01:27
We can assist if necessary.

**Closed** 2015-05-12 00:08 UTC
Labels: area/introspection, area/usability, priority/P1, team/UX
