### ISSUE TITLE
Add more cases to kubectl e2e test

### ISSUE THREAD

**Issue by gmarek** [GoogleCloudPlatform/kubernetes#8557] opened 2015-05-20 11:11 UTC
If I'm not mistaken only things called in this test are:
* create -f
* resize rc
* rolling-update
+ some direct API server calls. 

kubectl have way more commands available, which are probably not automatically tested anywhere
```
Available Commands: 
  get            Display one or many resources
  describe       Show details of a specific resource
  create         Create a resource by filename or stdin
  update         Update a resource by filename or stdin.
  delete         Delete a resource by filename, stdin, resource and ID, or by resources and label selector.
  namespace      SUPERCEDED: Set and view the current Kubernetes namespace
  log            Print the logs for a container in a pod.
  rolling-update Perform a rolling update of the given ReplicationController.
  resize         Set a new size for a Replication Controller.
  exec           Execute a command in a container.
  port-forward   Forward one or more local ports to a pod.
  proxy          Run a proxy to the Kubernetes API server
  run-container  Run a particular image on the cluster.
  stop           Gracefully shut down a resource by id or filename.
  expose         Take a replicated application and expose it as Kubernetes Service
  label          Update the labels on a resource
  config         config modifies kubeconfig files
  cluster-info   Display cluster info
  api-versions   Print available API versions.
  version        Print the client and server version information.
  help           Help about any command
```

We need at least some tests for kubectl commands: 
- [ ] get
- [ ] describe (?)
- [ ] update (e.g. #8449)
- [ ] delete
- [ ] namespace
- [ ] exec
- [ ] run-container
- [ ] stop
- [ ] expose (?)
- [ ] config (?)
- [ ] version (?)

**Comment by roberthbailey** [comment] 2015-05-20 16:41
This test just replaced the shell e2e tests for kubectl. It is by no means comprehensive. One question is how many of the kubectl commands need to be tested in e2e vs having a stand-alone testing framework for kubectl (that can be run locally for faster dev cycles). 

@jlowdermilk

**Comment by jlowdermilk** [comment] 2015-05-20 16:55
kubectl commands also get tested by `hack/test-cmd.sh` integration tests. Of the above list it's mainly the streaming commands (exec, log, port-forward, proxy) that lack test coverage.

I think any of the simple CRUD operations can be covered via integration tests. Multi-step operations (rolling-update) and streaming operations (exec, proxy) should get e2e coverage.

**Comment by gmarek** [comment] 2015-05-21 12:20
I beg to differ - we do need way more coverage, even if it's in the integration tests. If the coverage was sufficient for non-streaming commands we wouldn't have #8449.

I think that kubectl should be one of the things that are better tested as v1.0 is coming.

**Comment by bgrant0607** [comment] 2015-08-04 04:01
Closing as dupe of #10764

**Closed by bgrant0607** 2015-08-04 04:01 UTC
Labels: area/test, component/kubectl, priority/P2, team/ux
