### ISSUE TITLE
Update docs/cli.md (and other docs and examples) for kubectl

### ISSUE THREAD

**Issue by bgrant0607** [GoogleCloudPlatform/kubernetes#1928] opened 2014-10-21 18:55 UTC
Once kubectl is ready to replace kubecfg in most scenarios (probably everything other than rolling update), we should replace uses/mentions of kubecfg in documentation and examples.

/cc @ghodss @smarterclayton

**Comment by brendandburns** [comment] 2015-01-27 05:46
Closing as a dupe of #2144

**Closed by brendandburns** 2015-01-27 05:46 UTC
Labels: area/config-deployment, area/documentation, area/usability, component/client, priority/P1
