### ISSUE TITLE
Implement validation for endpoint.

### ISSUE THREAD

**Issue by hurf** [GoogleCloudPlatform/kubernetes#6408] opened 2015-04-03 08:55 UTC
When using endpoint to bind a pod to a service I found there is no validation. for example: 

      "kind": "Endpoints",
      "apiVersion": "v1beta1",
      "id": "myapp",
      "endpoints": ["173.194.112.206:80800"]
      
can still be created.
  
By looking into the code found a TODO is left there. Need to implement this.

**Comment by feihujiang** [comment] 2015-04-03 09:42
I have implemented this, but I encounted a problem while uploading the patch because of the GFW, I will try to upload it after the weekend.

**Comment by gmarek** [comment] 2015-04-03 12:32
There's my PR in flight: #5709

**Comment by yujuhong** [comment] 2015-04-03 16:55
Thanks for reporting the issue! As @gmarek pointed out, this is a dupe of #2572. Closing.

**Closed by yujuhong** 2015-04-03 16:55 UTC
