### ISSUE TITLE
Public service IPv4 collides despite using namespaces

### ISSUE THREAD

**Issue by mwuertinger** [GoogleCloudPlatform/kubernetes#4293] opened 2015-02-10 19:23 UTC
# Summary
- **Use case:** Create two or more publicly reachable services with the same id in different k8s namespaces.
- **Outcome:** The two services end up with the same public IPv4 address.
- **Expected behavior:** Each service gets its own public IPv4 address.

# Detailed description
When creating a service with load balancer in different k8s namespaces I end up with the same public IPv4 address.

```bash
echo "{\"Namespace\":\"test-2\"}" > ~/.kubernetes_ns
gcloud preview container services create --config-file=myapp.service.json
echo "{\"Namespace\":\"test-3\"}" > ~/.kubernetes_ns
gcloud preview container services create --config-file=myapp.service.json
```

myapp.service.json:
```json
{
  "apiVersion": "v1beta1",
  "kind": "Service",
  "id": "myapp",
  "port": 8080,
  "containerPort": "http",
  "selector": {
    "name": "myapp"
  },
  "labels": {
    "name": "myapp"
  },
  "createExternalLoadBalancer": true
}
```

Result from /api/v1beta2/services:
```json
{
  "id": "myapp",
  "uid": "b715420c-b153-11e4-ba44-42010af0c380",
  "creationTimestamp": "2015-02-10T18:36:23Z",
  "selfLink": "/api/v1beta2/services/myapp?namespace=test-2",
  "resourceVersion": 130,
  "namespace": "test-2",
  "port": 8080,
  "protocol": "TCP",
  "labels": {
    "name": "myapp"
  },  
  "selector": {
    "name": "myapp"
  },  
  "createExternalLoadBalancer": true,
  "publicIPs": [
    "104.154.37.74"
  ],  
  "containerPort": "http",
  "portalIP": "10.135.247.183",
  "sessionAffinity": "None"
},
{
  "id": "myapp",
  "uid": "2ddd7e1b-b157-11e4-ba44-42010af0c380",
  "creationTimestamp": "2015-02-10T19:01:11Z",
  "selfLink": "/api/v1beta2/services/myapp?namespace=test-3",
  "resourceVersion": 212,
  "namespace": "test-3",
  "port": 8080,
  "protocol": "TCP",
  "labels": {
    "name": "myapp"
  },  
  "selector": {
    "name": "myapp"
  },  
  "createExternalLoadBalancer": true,
  "publicIPs": [
    "104.154.37.74"
  ],  
  "containerPort": "http",
  "portalIP": "10.135.242.223",
  "sessionAffinity": "None"
}
```

Both services have the same public IPv4 address (104.154.37.74). My expectation would be to get two different IP addresses to that I can use both services which are living in their respective namespaces.

I'm using the image: container-vm-v20150129

```bash
mw@k8s-cluster-5-node-1:~$ kubelet --version
Kubernetes v0.10.0-dirty
mw@k8s-cluster-5-node-1:~$ docker --version
Docker version 1.4.1, build 5bc2ff8
```

```bash
mw@manhattan:~$ gcloud --version
Google Cloud SDK 0.9.46

bq 2.0.18
bq-nix 2.0.18
compute 2015.01.22
core 2015.02.05
core-nix 2014.10.20
dns 2015.01.15
gcutil 1.16.5
gcutil-nix 1.16.5
gsutil 4.8
gsutil-nix 4.6
preview 2015.01.31
preview-extensions-linux-x86_64 0.9.1
sql 2015.01.31
```

**Comment by roberthbailey** [comment] 2015-02-10 20:02
Dupe of #4288?

**Comment by mwuertinger** [comment] 2015-02-10 21:19
Yep. Sorry, didn't find that one.

**Comment by roberthbailey** [comment] 2015-02-10 21:40
Thanks. Closing this as a dupe.

**Closed by roberthbailey** 2015-02-10 21:40 UTC
Labels: priority/P2, team/cluster
