### ISSUE TITLE
integration test flaky due to missing endpoints

### ISSUE THREAD

**Issue by dchen1107** [GoogleCloudPlatform/kubernetes#6045] opened 2015-03-27 07:06 UTC
I0327 07:02:03.729736     732 integration.go:287] default/service2 endpoint: 1.2.3.4:1234 &api.ObjectReference{Kind:"Pod", Namespace:"default", Name:"foo", UID:"2823d7fd-d44f-11e4-9efc-02420a0000c3", APIVersion:"", ResourceVersion:"186", FieldPath:""}
I0327 07:02:03.730711     732 integration.go:283] Error on creating endpoints: endpoints "service1" not found
F0327 07:02:03.730752     732 integration.go:785] FAILED: service in other namespace should have no endpoints: false <nil>
!!! Error in hack/test-integration.sh:47
  '"${KUBE_OUTPUT_HOSTBIN}/integration" --v=2 --apiVersion="$1"' exited with status 255
Call stack:

**Comment by bgrant0607** [comment] 2015-04-04 00:27
This is failing quite often now, esp. on v1beta3 builds. Not yet sure if it's 100% broken yet, though.

**Comment by ghodss** [comment] 2015-04-04 00:39
I'm seeing the error Dawn wrote above as well as the following error near constantly on v1beta3.

```
F0403 23:57:52.507693   10953 integration.go:815] FAILED: unexpected endpoints: timed out waiting for the condition
```

**Comment by bgrant0607** [comment] 2015-04-04 01:03
Not 100% broken. Last build passed after being restarted.

**Comment by ghodss** [comment] 2015-04-05 10:10
So I spent some time digging into this. Both errors seem to have the root cause that the endpoints controller (pkg/service/endpoints_controller.go) is taking forever (on the order of tens of seconds) to do its job of synchronizing the endpoint objects to the current state of services and pods. If you increase the time out to 60 seconds instead of 30, these errors both go away.

There are a few reasons it's so slow. The endpoints controller is a serial loop that does 4-5 calls to the apiserver per service that it synchronizes endpoints for. I added some logging to pkg/service/endpoints_controller.go and found that, at least on the Linux VM on my mac, it was taking about 2-3 seconds for each and every apiserver call. That's also the reason that this has also gotten worse recently - the addition of patchservice as a test object gives the endpoint controller even more work to do, and delays the creation of endpoints for `runServiceTest` by an average of an extra 10 seconds or so.

There are a few ways to resolve this issue, and we should probably do them sequentially:

1. Increase the timeout. This makes the test less flakey without penalizing tests that run quickly, but if someone actually does break the tests, it may take them an extra minute or two to get feedback.
1. Figure out why apiserver is taking so long to respond to endpoints_controller's API calls. If this is expected, we can skip this step, but 2-3 seconds for simple CRUD calls seems ridiculously high.
1. Batch the calls together in pkg/service/endpoints_controller.go to improve performance.
1. After 2. and/or 3. are done, revert 1. :)

cc @thockin

**Comment by thockin** [comment] 2015-04-07 21:50
Also discussed in #6518

**Comment by wojtek-t** [comment] 2015-04-08 09:53
cc @fgrzadkowski

**Comment by ghodss** [comment] 2015-04-09 10:59
Do we have any idea why apiserver is so slow in the integration test?

**Comment by wojtek-t** [comment] 2015-04-10 12:30
There are few open issues touching this (e.g. #6518 as mentioned by @thockin).
But I think that the main reason was that we were running all the integration tests in parallel. This has been fixed yesterday (see e.g. #6669).
Do you still observe this issue?

**Comment by piosz** [comment] 2015-04-21 11:38
I ran integration tests 100 times from today's head and all passes, so closing the issue.

**Closed by piosz** 2015-04-21 11:38 UTC
Labels: misc/perf-1.0, priority/P1, team/any, team/cluster, team/testing

**Comment by ghodss** [comment] 2015-04-25 01:05
Yes, 2. looks much better - most calls are now taking a few milliseconds, although https://github.com/GoogleCloudPlatform/kubernetes/blob/master/pkg/service/endpoints_controller.go#L337 still takes about 200ms, but it's not a big deal atm.
