### ISSUE TITLE
AWS ELBs can only be created if your VPC is named "kubernetes-vpc"

### ISSUE THREAD

**Issue by jcderr** [GoogleCloudPlatform/kubernetes#11754] opened 2015-07-23 16:18 UTC
Using LoadBalancer service types on AWS, `findVPC` eventually gets called, which starts with declaring that it's looking for the hard-coded VPC name of 'kubernetes-vpc'.

See [here](https://github.com/GoogleCloudPlatform/kubernetes/blob/530bff315ff034d0c9098004f35f01d26ab40aaa/pkg/cloudprovider/aws/aws.go#L1447).

I'm not going to go rename all of my AWS assets just for this. This code should instead look into the AWS metadata to find the VPC ID and, if needed, describe it to get its name.

**Comment by thockin** [comment] 2015-07-23 16:30
@justinsb

**Comment by philk** [comment] 2015-07-23 22:02
Dupe of #9801

**Closed** 2015-07-23 23:20 UTC
Labels: priority/P1, team/cluster
