### ISSUE TITLE
Pods being scheduled on 'NotReady' node

### ISSUE THREAD

**Issue by antoineco** [GoogleCloudPlatform/kubernetes#7623] opened 2015-05-01 16:07 UTC
I have a simple setup with 1 master and 2 nodes running a couple of pods on Kubernetes v0.16.0.
When I simulate a crash on one of them, pods keep being scheduled on it indefinitely.

```
$ kubectl get nodes

NAME                                        LABELS    STATUS
ip-10-0-21-131.eu-west-1.compute.internal   <none>    Ready
ip-10-0-21-132.eu-west-1.compute.internal   <none>    NotReady
```

```
$ kubectl get pods
web-4a3cq       10.144.71.11     ip-10-0-21-131.eu-west-1.compute.internal/10.0.21.131   app=web      Running   23 hours 
web-st0du                        ip-10-0-21-132.eu-west-1.compute.internal/              app=web      Pending   2 seconds
```

```
$ journalctl -u kube-controller-manager
nodecontroller.go:431] node ip-10-0-21-132.eu-west-1.compute.internal hasn't been updated for 15m30.391884952s. Last ready condition is: {Type:Ready Status:Unknown LastHeartbeatTime:2015-05-01 15:30:47 +0000 UTC LastTransitionTime:2015-05-01 15:31:29 +0000 UTC Reason:Kubelet stopped posting node status. Message:}
nodecontroller.go:504] Evicting pods2: 2015-05-01 15:46:19.911780538 +0000 UTC is later than 2015-05-01 15:46:19.911779449 +0000 UTC + -10s
nodecontroller.go:175] Error syncing cloud: Request has expired. (RequestExpired)nodecontroller.go:431] node ip-10-0-21-132.eu-west-1.compute.internal hasn't been updated for 15m35.402783207s. Last ready condition is: {Type:Ready Status:Unkn
own LastHeartbeatTime:2015-05-01 15:30:47 +0000 UTC LastTransitionTime:2015-05-01 15:31:29 +0000 UTC Reason:Kubelet stopped posting node status. Message:}
nodecontroller.go:504] Evicting pods2: 2015-05-01 15:46:24.924422488 +0000 UTC is later than 2015-05-01 15:46:24.924421484 +0000 UTC + -10snodecontroller.go:584] Delete all pods from ip-10-0-21-132.eu-west-1.compute.internal
nodecontroller.go:595] Delete pod api-seu4e
nodecontroller.go:595] Delete pod web-mbpos
replication_controller.go:253] Too few "api" replicas, creating 1
replication_controller.go:253] Too few "web" replicas, creating 1
endpoints_controller.go:314] Failed to find an IP for pod default/web-hcxtd
endpoints_controller.go:314] Failed to find an IP for pod default/api-rb12s
endpoints_controller.go:314] Failed to find an IP for pod default/web-hcxtd
endpoints_controller.go:314] Failed to find an IP for pod default/api-rb12s
```

**Comment by jlowdermilk** [comment] 2015-05-01 21:51
It looks like it's the "web" replication controller keeps trying to reschedule pods after they get evicted. Can you post the schema for the 'web' replication controller? If the pod spec has a hostPort, that would explain why it's trying to schedule on the dead node.

**Comment by jlowdermilk** [comment] 2015-05-01 21:52
That being said, it seems like controller manager should be smart enough to not try to schedule on an unhealthy node.

**Comment by jlowdermilk** [comment] 2015-05-01 21:53
@yujuhong, can you take a look?

**Comment by bprashanth** [comment] 2015-05-02 01:14
Closing as duplicate of https://github.com/GoogleCloudPlatform/kubernetes/issues/7222

**Closed by bprashanth** 2015-05-02 01:14 UTC
Labels: component/controller-manager, kind/bug, team/master
