### ISSUE TITLE
Watching pod events don't ever show pod changing to running state

### ISSUE THREAD

**Issue by jimmidyson** [GoogleCloudPlatform/kubernetes#4113] opened 2015-02-04 16:42 UTC
When using the `/api/v1beta2/watch/pods` pod events only ever show pod as `Waiting`. e.g.

    curl -k https://localhost:8443/api/v1beta2/watch/pods/60767d85-ac8b-11e4-85fd-54ee7527188d

Returns:

```
{"type":"MODIFIED","object":{"kind":"Pod","id":"60767d85-ac8b-11e4-85fd-54ee7527188d","uid":"60767d85-ac8b-11e4-85fd-54ee7527188d",<SNIP>,"status":"Waiting",<SNIP>}}}
{"type":"MODIFIED","object":{"kind":"Pod","id":"60f0b4c1-ac8b-11e4-85fd-54ee7527188d","uid":"60f0b4c1-ac8b-11e4-85fd-54ee7527188d",<SNIP>,"status":"Waiting",<SNIP>}}}
```

However if you watch events you see the corresponding events for the boundPod entering the `Running` state:

     curl -k https://localhost:8443/api/v1beta2/watch/events | grep 60f0b4c1-ac8b-11e4-85fd-54ee7527188d

```
{"type":"ADDED","object":{"kind":"Event","id":"60f0b4c1-ac8b-11e4-85fd-54ee7527188d.13bfc062f3a4fbdb","uid":"62be59d5-ac8b-11e4-85fd-54ee7527188d","creationTimestamp":"2015-02-04T16:32:18Z","selfLink":"/api/v1beta2/events/60f0b4c1-ac8b-11e4-85fd-54ee7527188d.13bfc062f3a4fbdb","resourceVersion":26,"apiVersion":"v1beta2","namespace":"default","involvedObject":{"kind":"Pod","namespace":"default","name":"60f0b4c1-ac8b-11e4-85fd-54ee7527188d","uid":"60f0b4c1-ac8b-11e4-85fd-54ee7527188d","apiVersion":"v1beta1","resourceVersion":"21"},"reason":"failedScheduling","message":"Error scheduling: no minions available to schedule pods","source":"master","timestamp":"2015-02-04T16:32:18Z"}}
{"type":"ADDED","object":{"kind":"Event","id":"60f0b4c1-ac8b-11e4-85fd-54ee7527188d.13bfc0660a327b62","uid":"6aa656f3-ac8b-11e4-85fd-54ee7527188d","creationTimestamp":"2015-02-04T16:32:31Z","selfLink":"/api/v1beta2/events/60f0b4c1-ac8b-11e4-85fd-54ee7527188d.13bfc0660a327b62","resourceVersion":45,"apiVersion":"v1beta2","namespace":"default","involvedObject":{"kind":"BoundPod","namespace":"default","name":"60f0b4c1-ac8b-11e4-85fd-54ee7527188d","uid":"60f0b4c1-ac8b-11e4-85fd-54ee7527188d","apiVersion":"v1beta1","fieldPath":"spec.containers{registry-container}"},"reason":"created","message":"Created with docker id afab08cea073041ade8ff76f64208c82558b68e7c34056070db2909c2dfee588","source":"master","timestamp":"2015-02-04T16:32:31Z"}}
{"type":"ADDED","object":{"kind":"Event","id":"60f0b4c1-ac8b-11e4-85fd-54ee7527188d.13bfc065c1d0bf4c","uid":"69ed87ce-ac8b-11e4-85fd-54ee7527188d","creationTimestamp":"2015-02-04T16:32:30Z","selfLink":"/api/v1beta2/events/60f0b4c1-ac8b-11e4-85fd-54ee7527188d.13bfc065c1d0bf4c","resourceVersion":39,"apiVersion":"v1beta2","namespace":"default","involvedObject":{"kind":"BoundPod","namespace":"default","name":"60f0b4c1-ac8b-11e4-85fd-54ee7527188d","uid":"60f0b4c1-ac8b-11e4-85fd-54ee7527188d","apiVersion":"v1beta1","fieldPath":"implicitly required container POD"},"reason":"pulled","message":"Successfully pulled image \"openshift/origin-pod:v0.2.2\"","source":"master","timestamp":"2015-02-04T16:32:30Z"}}
{"type":"ADDED","object":{"kind":"Event","id":"60f0b4c1-ac8b-11e4-85fd-54ee7527188d.13bfc065c2342241","uid":"69ee66ae-ac8b-11e4-85fd-54ee7527188d","creationTimestamp":"2015-02-04T16:32:30Z","selfLink":"/api/v1beta2/events/60f0b4c1-ac8b-11e4-85fd-54ee7527188d.13bfc065c2342241","resourceVersion":40,"apiVersion":"v1beta2","namespace":"default","involvedObject":{"kind":"Pod","namespace":"default","name":"60f0b4c1-ac8b-11e4-85fd-54ee7527188d","uid":"60f0b4c1-ac8b-11e4-85fd-54ee7527188d","apiVersion":"v1beta1","resourceVersion":"21"},"reason":"scheduled","message":"Successfully assigned 60f0b4c1-ac8b-11e4-85fd-54ee7527188d to jimmi-redhat.localnet","source":"master","timestamp":"2015-02-04T16:32:30Z"}}
{"type":"ADDED","object":{"kind":"Event","id":"60f0b4c1-ac8b-11e4-85fd-54ee7527188d.13bfc065e0726a0c","uid":"6a3b706a-ac8b-11e4-85fd-54ee7527188d","creationTimestamp":"2015-02-04T16:32:31Z","selfLink":"/api/v1beta2/events/60f0b4c1-ac8b-11e4-85fd-54ee7527188d.13bfc065e0726a0c","resourceVersion":43,"apiVersion":"v1beta2","namespace":"default","involvedObject":{"kind":"BoundPod","namespace":"default","name":"60f0b4c1-ac8b-11e4-85fd-54ee7527188d","uid":"60f0b4c1-ac8b-11e4-85fd-54ee7527188d","apiVersion":"v1beta1","fieldPath":"implicitly required container POD"},"reason":"created","message":"Created with docker id f9246a56306bef3fd62e583fa229dca0c661d97f28184a19044f1eb329ea3894","source":"master","timestamp":"2015-02-04T16:32:31Z"}}
{"type":"ADDED","object":{"kind":"Event","id":"60f0b4c1-ac8b-11e4-85fd-54ee7527188d.13bfc0660f0ef697","uid":"6ab4764e-ac8b-11e4-85fd-54ee7527188d","creationTimestamp":"2015-02-04T16:32:31Z","selfLink":"/api/v1beta2/events/60f0b4c1-ac8b-11e4-85fd-54ee7527188d.13bfc0660f0ef697","resourceVersion":46,"apiVersion":"v1beta2","namespace":"default","involvedObject":{"kind":"BoundPod","namespace":"default","name":"60f0b4c1-ac8b-11e4-85fd-54ee7527188d","uid":"60f0b4c1-ac8b-11e4-85fd-54ee7527188d","apiVersion":"v1beta1","fieldPath":"spec.containers{registry-container}"},"reason":"started","message":"Started with docker id afab08cea073041ade8ff76f64208c82558b68e7c34056070db2909c2dfee588","source":"master","timestamp":"2015-02-04T16:32:31Z"}}
```

Is there any way to watch all pod events, including succesful scheduling & starting?

**Comment by bgrant0607** [comment] 2015-02-13 20:15
Dupe of #2726 and #3692 .

**Comment by bgrant0607** [comment] 2015-02-13 20:16
@jimmidyson Not yet, but working on it.

**Closed by bgrant0607** 2015-02-13 20:15 UTC
Labels: priority/P2, team/cluster, team/UX
