### ISSUE TITLE
Existing forwarding rule not updated on service creation

### ISSUE THREAD

**Issue by rsokolowski** [GoogleCloudPlatform/kubernetes#4228] opened 2015-02-06 23:08 UTC
Environment: GCE.
I've created a service with createExternalLoadBalancer set to true. This has automatically added forwarding rule for "port" specified in the service.
Later, I've destroyed the cluster using kube-down.sh (I guess). The forwarding rule was not removed (probably it would be nice to have it removed automatically). 
Later, I've create new cluster and wanted to start the service again, but with different "port" exposed this time. kubectl create -f service.json worked fine, however the forwarding rule that was already present hasn't been updated.
kubectl should at least complain and warn the user that forwarding rule already exist (and might be incorrect).

**Comment by jlowdermilk** [comment] 2015-02-07 01:52
IIRC there was a thread about adding shutdown hooks to the master so it can clean up any cloudprovider-specific resources it's using. cc @bgrant0607, @brendandburns

**Comment by zmerlynn** [comment] 2015-02-07 02:26
I think this is a dupe of #2984

**Comment by davidopp** [comment] 2015-02-07 07:00
I agree... (And #4013, which was a dupe of #2984... We should probably fix this :-)

**Closed by davidopp** 2015-02-07 07:00 UTC
Labels: api/cloudprovider, area/usability, team/master
