### ISSUE TITLE
After replication controller is deleted, some nodes do not kill running containers

### ISSUE THREAD

**Issue by saad-ali** [GoogleCloudPlatform/kubernetes#9833] opened 2015-06-16 00:11 UTC
Discovered this while debugging with @ArtfulCoder 

Some nodes do not kill containers after associated replication controller is deleted.

**Repro steps:**
* You may use a standard GCE 4 node cluster `n1-standard-1 (1 vCPU, 3.8 GB memory)`
* Download [sleepypod.yaml](https://gist.github.com/saad-ali/7d04ff21534729c6c42a)
  * It defines a replication controller with 300 replicas with 10 containers per pod using a *tiny* container which contains a statically compiled C program that just starts up and goes to sleep for a very long time.
* Execute `./cluster/kubectl.sh create -f sleepypod.yaml` to create the replica controller
* Execute `./cluster/kubectl.sh describe rc sleepypod` repeatedly to check how many pods are scheduled.
  * Monitor `Pods Status`
  * Wait until the number of scheduled pods stops increasing (depending on the size of your cluster, you will not be able to schedule all 300 replicas, that's ok).
* Call `./cluster/kubectl.sh delete -f sleepypod.yaml` to delete the replica controller
* Call `./cluster/kubectl.sh get pods` verify there are no `sleepypod-...` in the response
* SSH into each node machine and execute `sudo ps | grep sleepy`

**Expected result:**
* All nodes should have no running `sleepypod-...` containers

**Actual result:**
* One or more nodes will not terminate the `sleepypod:` and associated `pause` containers running on it:
```
...
5a43b2d1f759        saadali/sleepy:v0.2                                  "/sleepy"              4 hours ago         Up 4 hours                              k8s_sleepycontainer10.b9d85f66_sleepypod-mekmp_default_9fa3ef74-1393-11e5-aded-42010af07014_7d082525                                
06ab4cabc565        gcr.io/google_containers/pause:0.8.0                 "/pause"               4 hours ago         Up 4 hours                              k8s_POD.e4cc795_sleepypod-112c1_default_9fe56947-1393-11e5-aded-42010af07014_b2310383                                               
4c70725574ed        saadali/sleepy:v0.2                                  "/sleepy"              4 hours ago         Up 4 hours                              k8s_sleepycontainer4.63e5f39_sleepypod-eckpv_default_9f9ba8ea-1393-11e5-aded-42010af07014_e0f13706                                  
3e491a34c918        saadali/sleepy:v0.2                                  "/sleepy"              4 hours ago         Up 4 hours                              k8s_sleepycontainer3.2a15f38_sleepypod-eckpv_default_9f9ba8ea-1393-11e5-aded-42010af07014_9d181ac0                                  
eb9543fc63b9        saadali/sleepy:v0.2                                  "/sleepy"              4 hours ago         Up 4 hours                              k8s_sleepycontainer5.9db5f3a_sleepypod-q9dpx_default_9f9f8436-1393-11e5-aded-42010af07014_47c74ea6                                  
532f0ba08f95        saadali/sleepy:v0.2                                  "/sleepy"              4 hours ago         Up 4 hours                              k8s_sleepycontainer1.fb585f36_sleepypod-81gxh_default_9fc28c32-1393-11e5-aded-42010af07014_708dac19                                 
d1798807a41f        saadali/sleepy:v0.2                                  "/sleepy"              4 hours ago         Up 4 hours                              k8s_sleepycontainer1.fb585f36_sleepypod-zpgxi_default_9fa6ca8a-1393-11e5-aded-42010af07014_4fdaf5f0                                 
a35f6cf4e3f5        saadali/sleepy:v0.2                                  "/sleepy"              4 hours ago         Up 4 hours                              k8s_sleepycontainer1.fb585f36_sleepypod-i1pw2_default_9fa948c9-1393-11e5-aded-42010af07014_791453ee                                 
e3a2d3b387d3        saadali/sleepy:v0.2                                  "/sleepy"              4 hours ago         Up 4 hours                              k8s_sleepycontainer8.14b25f3d_sleepypod-bj214_default_9faf6559-1393-11e5-aded-42010af07014_e97eebb8                                 
81b51e9f56eb        saadali/sleepy:v0.2                                  "/sleepy"              4 hours ago         Up 4 hours                              k8s_sleepycontainer6.d785f3b_sleepypod-x67qk_default_9fb8cd56-1393-11e5-aded-42010af07014_c290eba3                                  
564fd2380bc0        gcr.io/google_containers/pause:0.8.0                 "/pause"               4 hours ago         Up 4 hours                              k8s_POD.e4cc795_sleepypod-81gxh_default_9fc28c32-1393-11e5-aded-42010af07014_deaf6b10                                               
4db197a952f9        saadali/sleepy:v0.2                                  "/sleepy"              4 hours ago         Up 4 hours                              k8s_sleepycontainer1.fb585f36_sleepypod-di4rg_default_9fabd5ae-1393-11e5-aded-42010af07014_df47b02d                                 
...
```

Restarting kubelet (`service kubelet restart`) or restarting docker causes the running containers to all get killed.

**Comment by dchen1107** [comment] 2015-06-16 00:16
Is a watcher issue or kubelet failed to take an action here?

**Comment by bprashanth** [comment] 2015-06-16 00:48
a good way to debug this would be to send an event from the kubelet anytime it notices either a create or delete for a pod via the watch conduit. that would be useful in general. If we see/don't see this event it rules out 1/2 the possible bug scenarios.

**Comment by derekwaynecarr** [comment] 2015-06-16 02:27
@smarterclayton - i thought I may have seen similar behavior today when stress testing but I had thought I may have done something stupid on the node.  We need to track this as well

**Comment by bprashanth** [comment] 2015-06-16 04:53
Can we convert comment 0 into an e2e test? AFAIK we don't have one that checks end to end deletes of countainers on the kubelet. Instead of ssh-ing we would use the proxy to scrape /pods on the node.

**Comment by dchen1107** [comment] 2015-06-16 04:56
@bprashanth Do we believe that syncPod response times is getting really big under resource stress, or just simply an bug with either watcher or kubelet?

**Comment by dchen1107** [comment] 2015-06-16 04:57
I will update e2e test to validate end to end deletes of containers.

**Comment by dchen1107** [comment] 2015-06-16 07:35
Ok, when you observed such issue, have you checked the node Status by running kubectl get nodes? Are those nodes still in Ready state? 

Obviously your test scenario are putting our nodes overcommitted for both cpu and memory. I think I mentioned that when you first designed such test case. :-)  When a node is under resource pressure, everything could be slowly, including kubelet and docker. I tried to reproduce your issue based on steps you described above, i couldn't reproduce the issue unless the node becomes NotReady under resource pressure. When a node is NotReady, it is reasonable it doesn't stop all running containers.

**Comment by jayunit100** [comment] 2015-06-16 16:47
In the e2e for namespaces, we have an extinguish() function which quantifies how many ns are extinguished.  Maybe that test can be extended @dchen1107 ? or just write a new one.  just a thought.

**Comment by bprashanth** [comment] 2015-06-16 17:04
@dchen1107 that was my initial argument as well, however 2 things made me rethink:

1. The kubelet has a max-pods setting but not max-containers. @saad-ali and @ArtfulCoder profiled their containers and specified the resource requirements in yaml, so I don't think the containers themselves exhausted resources. 

2. The described scenario had containers stick around for hours, longer than I would expect for a slow  kubelet (as you described the node could be NotReady though).
 
>Do we believe that syncPod response times is getting really big under resource stress, or just simply an bug with either watcher or kubelet?

If we fail to delete something on the kubelet, we should retry every SyncPods, so unless SyncPods is hung or docker is not responding I don't see how this could happen. OTOH, if the watch failed, we should relist every 5m, so unless the apiserver was down, I don't see how this... essentially I would need to debug to figure this out.

**Comment by dchen1107** [comment] 2015-06-16 21:03
Close this one as dup of #9895

**Closed by dchen1107** 2015-06-16 21:03 UTC
Labels: kind/bug, priority/P1, team/node
