### ISSUE TITLE
TestSyncProbedNodeStatusEvictPods is flaky

### ISSUE THREAD

**Issue by bgrant0607** [GoogleCloudPlatform/kubernetes#6247] opened 2015-03-31 21:56 UTC
It may be due to an event that was just added to node controller (#6155).

@vmarmol @gmarek @simon3z 

```
==================
WARNING: DATA RACE
Read by goroutine 66:
  reflect.memmove()
      /usr/local/go/src/pkg/reflect/value.go:39 +0x190
  reflect.packEface()
      /usr/local/go/src/pkg/reflect/value.go:138 +0xe4
  reflect.valueInterface()
      /usr/local/go/src/pkg/reflect/value.go:1100 +0x2bd
  reflect.Value.Interface()
      /usr/local/go/src/pkg/reflect/value.go:1070 +0x69
  fmt.(*pp).printValue()
      /usr/local/go/src/pkg/fmt/print.go:826 +0x4e3
  fmt.(*pp).printReflectValue()
      /usr/local/go/src/pkg/fmt/print.go:966 +0x1658
  fmt.(*pp).printArg()
      /usr/local/go/src/pkg/fmt/print.go:794 +0x695
  fmt.(*pp).doPrintf()
      /usr/local/go/src/pkg/fmt/print.go:1159 +0x2aba
  fmt.Sprintf()
      /usr/local/go/src/pkg/fmt/print.go:203 +0x89
  testing.(*common).Errorf()
      /usr/local/go/src/pkg/testing/testing.go:332 +0x5c
  github.com/GoogleCloudPlatform/kubernetes/pkg/cloudprovider/controller.TestSyncProbedNodeStatusEvictPods()
      /home/travis/gopath/src/github.com/GoogleCloudPlatform/kubernetes/_output/local/go/src/github.com/GoogleCloudPlatform/kubernetes/pkg/cloudprovider/controller/nodecontroller_test.go:1076 +0x2035
  testing.tRunner()
      /usr/local/go/src/pkg/testing/testing.go:422 +0x10f
Previous write by goroutine 71:
  github.com/GoogleCloudPlatform/kubernetes/pkg/client.(*FakeEvents).Create()
      /home/travis/gopath/src/github.com/GoogleCloudPlatform/kubernetes/_output/local/go/src/github.com/GoogleCloudPlatform/kubernetes/pkg/client/fake_events.go:35 +0x182
  github.com/GoogleCloudPlatform/kubernetes/pkg/client/record.recordEvent()
      /home/travis/gopath/src/github.com/GoogleCloudPlatform/kubernetes/_output/local/go/src/github.com/GoogleCloudPlatform/kubernetes/pkg/client/record/event.go:149 +0x3b1
  github.com/GoogleCloudPlatform/kubernetes/pkg/client/record.func·001()
      /home/travis/gopath/src/github.com/GoogleCloudPlatform/kubernetes/_output/local/go/src/github.com/GoogleCloudPlatform/kubernetes/pkg/client/record/event.go:120 +0x241
  github.com/GoogleCloudPlatform/kubernetes/pkg/client/record.func·003()
      /home/travis/gopath/src/github.com/GoogleCloudPlatform/kubernetes/_output/local/go/src/github.com/GoogleCloudPlatform/kubernetes/pkg/client/record/event.go:206 +0x14a
Goroutine 66 (running) created at:
  testing.RunTests()
      /usr/local/go/src/pkg/testing/testing.go:504 +0xb46
  testing.Main()
      /usr/local/go/src/pkg/testing/testing.go:435 +0xa2
  main.main()
      github.com/GoogleCloudPlatform/kubernetes/pkg/cloudprovider/controller/_test/_testmain.go:117 +0x18b
Goroutine 71 (running) created at:
  github.com/GoogleCloudPlatform/kubernetes/pkg/client/record.(*eventBroadcasterImpl).StartEventWatcher()
      /home/travis/gopath/src/github.com/GoogleCloudPlatform/kubernetes/_output/local/go/src/github.com/GoogleCloudPlatform/kubernetes/pkg/client/record/event.go:208 +0x133
  github.com/GoogleCloudPlatform/kubernetes/pkg/client/record.(*eventBroadcasterImpl).StartRecordingToSink()
      /home/travis/gopath/src/github.com/GoogleCloudPlatform/kubernetes/_output/local/go/src/github.com/GoogleCloudPlatform/kubernetes/pkg/client/record/event.go:136 +0x1a8
  github.com/GoogleCloudPlatform/kubernetes/pkg/cloudprovider/controller.NewNodeController()
      github.com/GoogleCloudPlatform/kubernetes/pkg/cloudprovider/controller/_test/_obj_test/nodecontroller.go:69 +0x18a
  github.com/GoogleCloudPlatform/kubernetes/pkg/cloudprovider/controller.TestSyncProbedNodeStatusEvictPods()
      /home/travis/gopath/src/github.com/GoogleCloudPlatform/kubernetes/_output/local/go/src/github.com/GoogleCloudPlatform/kubernetes/pkg/cloudprovider/controller/nodecontroller_test.go:1067 +0x1be1
  testing.tRunner()
      /usr/local/go/src/pkg/testing/testing.go:422 +0x10f
==================
I0331 21:43:40.251410   17630 nodecontroller.go:68] Sending events to api server.
E0331 21:43:40.252892   17630 nodecontroller.go:300] Can't collect information for node node0: Not Implemented
E0331 21:43:40.252995   17630 nodecontroller.go:462] Can't get ip address of node node0: lookup node0: no such host
I0331 21:43:40.253388   17630 nodecontroller.go:68] Sending events to api server.
E0331 21:43:40.256319   17630 nodecontroller.go:300] Can't collect information for node node0: Not Implemented
E0331 21:43:40.256759   17630 nodecontroller.go:462] Can't get ip address of node node0: lookup node0: no such host
--- FAIL: TestSyncProbedNodeStatusEvictPods (0.02 seconds)
	nodecontroller_test.go:1076: time out waiting for deleting pods, expected [], got [{Action:get-event Value:node0.13d0b34bda50931b}]
I0331 21:43:40.258081   17630 nodecontroller.go:68] Sending events to api server.
I0331 21:43:40.259404   17630 nodecontroller.go:68] Sending events to api server.
I0331 21:43:40.261956   17630 nodecontroller.go:68] Sending events to api server.
I0331 21:43:40.264475   17630 nodecontroller.go:68] Sending events to api server.
I0331 21:43:40.265897   17630 nodecontroller.go:68] Sending events to api server.
I0331 21:43:40.269912   17630 nodecontroller.go:68] Sending events to api server.
I0331 21:43:40.271704   17630 nodecontroller.go:68] Sending events to api server.
I0331 21:43:40.272866   17630 nodecontroller.go:68] Sending events to api server.
I0331 21:43:40.274552   17630 nodecontroller.go:68] Sending events to api server.
FAIL
coverage: 78.5% of statements
FAIL	github.com/GoogleCloudPlatform/kubernetes/pkg/cloudprovider/controller	0.193s
```

**Comment by vmarmol** [comment] 2015-03-31 22:01
Dupe of #6199. The fix for that is under review (the code is getting removed).

**Closed by vmarmol** 2015-03-31 22:01 UTC
Labels: component/nodecontroller, kind/bug, priority/P1, team/master
